(function () {
  const { UI, esc } = App;

  // ---- example data: the Northwind tenant's certificate authority (Sprints 24, 25a) ----
  const ISSUERS0 = () => [
    { id: 'iss-root-g1', kind: 'root', name: 'Northwind Platform Root CA G1', org: 'Northwind', keyType: 'ecdsa-p256', custody: 'signer process', serial: '01', generation: 1, pathLen: 'none', notBefore: '10 Jan 2026', notAfter: '08 Jan 2036', state: 'active', crlNumber: 42, replacedBy: null, tenant: 'platform', urls: { crl: 'https://ai.northwind.local/pki/crl/iss-root-g1.crl', cert: 'https://ai.northwind.local/pki/ca/iss-root-g1.crt', ocsp: 'https://ai.northwind.local/pki/ocsp' }, crls: [{ number: 42, thisUpdate: '19 Sep 06:00', nextUpdate: '20 Sep 06:00', entries: 1 }, { number: 41, thisUpdate: '18 Sep 06:00', nextUpdate: '19 Sep 06:00', entries: 1 }, { number: 40, thisUpdate: '17 Sep 06:00', nextUpdate: '18 Sep 06:00', entries: 0 }] },
    { id: 'iss-nw-g2', kind: 'intermediate', name: 'Northwind Issuing CA', org: 'Northwind', keyType: 'ecdsa-p256', custody: 'signer process', serial: '4a:91:c3:0e:7b', generation: 2, pathLen: 0, notBefore: '01 Jun 2026', notAfter: '31 May 2031', state: 'active', crlNumber: 117, replacedBy: null, tenant: 'Northwind', urls: { crl: 'https://ai.northwind.local/pki/crl/iss-nw-g2.crl', cert: 'https://ai.northwind.local/pki/ca/iss-nw-g2.crt', ocsp: 'https://ai.northwind.local/pki/ocsp' }, crls: [{ number: 117, thisUpdate: '19 Sep 13:40', nextUpdate: '19 Sep 19:40', entries: 3 }, { number: 116, thisUpdate: '19 Sep 07:40', nextUpdate: '19 Sep 13:40', entries: 2 }, { number: 115, thisUpdate: '19 Sep 01:40', nextUpdate: '19 Sep 07:40', entries: 2 }, { number: 114, thisUpdate: '18 Sep 19:40', nextUpdate: '19 Sep 01:40', entries: 2 }, { number: 113, thisUpdate: '18 Sep 13:40', nextUpdate: '18 Sep 19:40', entries: 2 }] },
    { id: 'iss-nw-g1', kind: 'intermediate', name: 'Northwind Issuing CA', org: 'Northwind', keyType: 'ecdsa-p256', custody: 'signer process', serial: '2f:00:ab:19:de', generation: 1, pathLen: 0, notBefore: '12 Jan 2026', notAfter: '11 Jan 2031', state: 'retired', crlNumber: 61, replacedBy: 'iss-nw-g2', tenant: 'Northwind', retiredAt: '01 Jun 2026', urls: { crl: 'https://ai.northwind.local/pki/crl/iss-nw-g1.crl', cert: 'https://ai.northwind.local/pki/ca/iss-nw-g1.crt', ocsp: 'https://ai.northwind.local/pki/ocsp' }, crls: [{ number: 61, thisUpdate: '19 Sep 13:40', nextUpdate: '19 Sep 19:40', entries: 4 }] }
  ];
  const PROFILES0 = () => [
    { id: 'p-servers', name: 'servers-internal', kind: 'server', maxDays: 398, defaultDays: 90, state: 'active', policy: { domains: ['*.northwind.local', 'ai.northwind.local'], allowWildcard: false, ipRanges: ['10.20.0.0/16'], emailDomains: [], uriPrefixes: [], keyTypes: ['P-256', 'P-384', 'RSA 2048', 'RSA 3072'] }, issued: 31 },
    { id: 'p-clients', name: 'clients-mtls', kind: 'client', maxDays: 825, defaultDays: 365, state: 'active', policy: { domains: ['*.northwind.local'], allowWildcard: false, ipRanges: [], emailDomains: ['northwind.local'], uriPrefixes: ['spiffe://northwind.local/'], keyTypes: ['P-256', 'Ed25519', 'RSA 3072'] }, issued: 14 },
    { id: 'p-codesign', name: 'code-signing-release', kind: 'code-signing', maxDays: 1185, defaultDays: 365, state: 'disabled', policy: { domains: [], allowWildcard: false, ipRanges: [], emailDomains: ['northwind.local'], uriPrefixes: ['https://git.northwind.local/'], keyTypes: ['P-384', 'RSA 4096'] }, issued: 2 }
  ];
  // daysLeft is relative to 19 Sep 2026
  const CERTS0 = () => [
    { id: 'c-7731', cn: 'ai.northwind.local', sans: ['dns:ai.northwind.local', 'dns:console.northwind.local'], profile: 'servers-internal', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:aa:03', keyType: 'P-256', notBefore: '03 Sep 2026', notAfter: '02 Dec 2026', daysLeft: 74, state: 'valid', requestedBy: 'ACME account acct-19', acme: 'acct-19', fp: 'SHA-256 7A:3F:91:0C:E2:B8:44:19:D0:5E:AA:72:C1:08:3B:F6:2D:97:E4:10:5C:88:0B:A3:6F:D1:42:9E:7B:C5:13:60', renewedFrom: 'c-7402' },
    { id: 'c-7728', cn: 'ollama-gpu-01.northwind.local', sans: ['dns:ollama-gpu-01.northwind.local', 'ip:10.20.4.11'], profile: 'servers-internal', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:aa:02', keyType: 'RSA 3072', notBefore: '27 Jun 2026', notAfter: '25 Sep 2026', daysLeft: 6, state: 'valid', requestedBy: 'Mara Okafor', fp: 'SHA-256 1C:0D:88:E7:52:3A:B9:F4:61:7E:D2:05:9C:AB:30:4F:E8:17:6B:C9:02:5D:F3:A8:74:1E:B6:0A:C7:93:2F:58' },
    { id: 'c-7719', cn: 'rabbitmq.northwind.local', sans: ['dns:rabbitmq.northwind.local'], profile: 'servers-internal', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:a9:f1', keyType: 'P-256', notBefore: '16 Jul 2026', notAfter: '14 Oct 2026', daysLeft: 25, state: 'valid', requestedBy: 'ACME account acct-19', acme: 'acct-19', fp: 'SHA-256 9E:44:D1:7B:20:F8:63:AC:0E:5B:97:3D:C4:12:A6:E0:7F:28:B5:D9:41:6C:03:FE:8A:B7:19:52:E6:0D:C8:34' },
    { id: 'c-7702', cn: 'exprsn-cli build-03', sans: ['email:build@northwind.local', 'uri:spiffe://northwind.local/build-03'], profile: 'clients-mtls', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:a9:cc', keyType: 'Ed25519', notBefore: '02 Aug 2026', notAfter: '02 Aug 2027', daysLeft: 317, state: 'valid', requestedBy: 'Felix Brandt', fp: 'SHA-256 B3:61:0F:AE:92:C7:14:D8:5A:E3:70:2B:9F:46:C1:0D:88:E5:37:A2:6E:F1:0B:59:C4:7D:12:A9:3F:E8:65:20' },
    { id: 'c-7690', cn: 'postgres-02.northwind.local', sans: ['dns:postgres-02.northwind.local', 'ip:10.20.6.22'], profile: 'servers-internal', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:a9:8e', keyType: 'P-256', notBefore: '14 Aug 2026', notAfter: '12 Nov 2026', daysLeft: 54, state: 'revoked', revokedAt: '17 Sep 09:12', reason: 'keyCompromise', invalidityDate: '16 Sep 2026', requestedBy: 'Jonas Lindqvist', fp: 'SHA-256 4D:98:2A:F0:6B:C3:E1:57:0A:B4:8F:21:D6:7C:93:E5:3F:A0:1B:C8:66:D2:09:7E:F4:5A:B1:38:0C:E9:72:A5' },
    { id: 'c-7402', cn: 'ai.northwind.local', sans: ['dns:ai.northwind.local', 'dns:console.northwind.local'], profile: 'servers-internal', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:a8:10', keyType: 'P-256', notBefore: '05 Jun 2026', notAfter: '03 Sep 2026', daysLeft: -16, state: 'revoked', revokedAt: '03 Sep 10:30', reason: 'superseded', requestedBy: 'ACME account acct-19', acme: 'acct-19', fp: 'SHA-256 E0:17:5C:B9:A2:0F:D4:6E:81:3B:C7:92:1A:F5:0D:68:B3:4E:D7:29:A6:0C:F8:55:1E:B2:7A:93:C4:06:D9:3F' },
    { id: 'c-7655', cn: 'release-signing', sans: ['email:release@northwind.local', 'uri:https://git.northwind.local/northwind/exprsn-ai'], profile: 'code-signing-release', issuer: 'iss-nw-g2', serial: '5b:12:9e:47:c0:a9:41', keyType: 'P-384', notBefore: '20 Aug 2026', notAfter: '20 Aug 2027', daysLeft: 335, state: 'valid', requestedBy: 'Jonas Lindqvist', fp: 'SHA-256 2B:C6:71:9D:04:E8:5F:A3:16:D0:7B:C2:98:3E:F1:0A:67:B4:D5:29:8C:E3:0F:A1:5D:76:B8:14:C9:2E:F0:83' },
    { id: 'c-7211', cn: 'ldap.northwind.local', sans: ['dns:ldap.northwind.local'], profile: 'servers-internal', issuer: 'iss-nw-g1', serial: '2f:00:ab:19:de:00:77', keyType: 'RSA 2048', notBefore: '20 Mar 2026', notAfter: '22 Apr 2027', daysLeft: 215, state: 'valid', requestedBy: 'Aisha Bello', fp: 'SHA-256 77:A1:3E:C0:5D:F9:26:B8:0E:4A:D3:91:6C:F2:08:B5:E7:3A:1D:C4:59:0F:A8:6B:D2:17:E5:3C:90:B4:2A:F6' }
  ];
  const EAB0 = () => [
    { id: 'eab-3', name: 'cert-manager prod', state: 'bound', accountId: 'acct-19', createdAt: '02 Jun 2026', boundAt: '02 Jun 2026' },
    { id: 'eab-4', name: 'traefik edge', state: 'active', accountId: null, createdAt: '12 Sep 2026', boundAt: null },
    { id: 'eab-2', name: 'cert-manager staging', state: 'revoked', accountId: 'acct-11', createdAt: '14 Jan 2026', boundAt: '14 Jan 2026' }
  ];
  const ACCOUNTS0 = () => [
    { id: 'acct-19', thumbprint: 'kK3xP0kO9W9f3QrVbW3aZ1nUx6P-2vJm6rB2c7hYtQw', keyType: 'EC', contact: 'mailto:platform@northwind.local', status: 'valid', eabKeyId: 'eab-3', createdAt: '02 Jun 2026', orders: 23 },
    { id: 'acct-11', thumbprint: 'Yx9E2mPa0c4LqB7rZdF8sW1vNhK3jT6uRgA5oH2iC0Q', keyType: 'RSA', contact: 'mailto:ops-staging@northwind.local', status: 'deactivated', eabKeyId: 'eab-2', createdAt: '14 Jan 2026', orders: 8 }
  ];
  const ORDERS0 = () => [
    { id: 'ord-2291', accountId: 'acct-19', identifiers: ['ai.northwind.local', 'console.northwind.local'], status: 'valid', expires: '26 Sep 2026', error: null, certificateId: 'c-7731', createdAt: '03 Sep 07:58' },
    { id: 'ord-2304', accountId: 'acct-19', identifiers: ['rabbitmq.northwind.local'], status: 'ready', expires: '20 Sep 09:10', error: null, certificateId: null, createdAt: '19 Sep 09:10' },
    { id: 'ord-2305', accountId: 'acct-19', identifiers: ['*.lab.northwind.local'], status: 'invalid', expires: '20 Sep 11:02', error: 'dns-01: no TXT record at _acme-challenge.lab.northwind.local (urn:ietf:params:acme:error:dns)', certificateId: null, createdAt: '19 Sep 11:02' },
    { id: 'ord-2306', accountId: 'acct-19', identifiers: ['grafana.northwind.local'], status: 'pending', expires: '20 Sep 13:30', error: null, certificateId: null, createdAt: '19 Sep 13:30' },
    { id: 'ord-2307', accountId: 'acct-19', identifiers: ['minio.northwind.local'], status: 'processing', expires: '20 Sep 14:01', error: null, certificateId: null, createdAt: '19 Sep 14:01' }
  ];
  const REASONS = ['unspecified', 'keyCompromise', 'affiliationChanged', 'superseded', 'cessationOfOperation', 'privilegeWithdrawn'];
  const SORT_LABEL = { expiry: 'Soonest expiry', cn: 'Common name', issued: 'Most recently issued' };
  const parseDay = (s) => { const m = { Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5, Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11 }; const p = s.split(' '); return new Date(+p[2], m[p[1]], +p[0]).getTime(); };
  const expiryCell = (c) => c.state === 'revoked' ? '<span class="muted">' + esc(c.notAfter) + '</span>' : c.daysLeft <= 7 ? '<span style="color:var(--danger-fg)">' + esc(c.notAfter) + ', ' + c.daysLeft + ' d</span>' : c.daysLeft <= 30 ? '<span style="color:var(--warn-fg)">' + esc(c.notAfter) + ', ' + c.daysLeft + ' d</span>' : esc(c.notAfter);
  const statePill = (c) => c.state === 'revoked' ? UI.pill('revoked', 'danger') : c.daysLeft <= 7 ? UI.pill('expiring, ' + c.daysLeft + ' d', 'danger') : c.daysLeft <= 30 ? UI.pill('expiring', 'warn') : UI.pill('valid', 'ok');

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
  const init = (st) => {
    if (st.issuers) return;
    st.issuers = ISSUERS0(); st.profiles = PROFILES0(); st.certs = CERTS0(); st.eab = EAB0(); st.accounts = ACCOUNTS0(); st.orders = ORDERS0();
    st.tab = 'certs'; st.acmeTab = 'eab'; st.query = ''; st.stateFilter = 'all'; st.issuerFilter = 'all'; st.profileFilter = 'all'; st.sort = 'expiry'; st.orderFilter = 'all';
    st.custody = 'signer process'; st.selIssuer = 'iss-nw-g2'; st.selCert = 'c-7728'; st.problem = null; st.revealed = null;
    st.acme = { enabled: true, profile: 'servers-internal', eabRequired: true, challenges: ['http-01', 'dns-01'], directoryUrl: 'https://ai.northwind.local/pki/acme/northwind/directory', updatedAt: '12 Sep 2026' };
  };

  App.register({
    id: 'certificates', title: 'Certificates', section: 'admin', crumb: ['Admin', 'Certificates'],
    summary: 'Issuers, profiles, issuance from a CSR, revocation, CRLs, ACME directory, expiring certificates',
    commands: [
      { label: 'Issue a certificate', sub: 'Certificates', run(app) { const s = app.stateFor('certificates'); init(s); s.tab = 'certs'; s.openIssue = true; app.render(); } },
      { label: 'Sign the next CRL now', sub: 'Certificates', run(app) { app.toast('pki.crl job queued for Northwind Issuing CA (202). CRL 118 follows in a moment.', 'ok'); } }
    ],
    label: () => 'confidential',
    states: [
      { title: 'Custody unavailable', tone: 'warn', text: 'No signer process or OpenBao transit is reachable. Routes that make keys answer 409 (step custody); rotation, new issuers and key generation are disabled until it is back.', apply(ctx) { init(ctx.state); ctx.state.custody = 'unavailable'; ctx.state.tab = 'issuers'; ctx.rerender(); } },
      { title: 'Name refused by profile', tone: 'danger', text: 'A CSR asked for a name outside the profile. The refusal is 422 with step names and the offending name; it is audited as pki.issue.refused and nothing is issued.', apply(ctx) { init(ctx.state); ctx.state.tab = 'certs'; ctx.state.problem = { step: 'names', name: { type: 'dns', value: 'api.contoso.example' }, profile: 'servers-internal' }; ctx.rerender(); } },
      { title: 'Issuer retired after rotation', tone: 'neutral', text: 'Rotation makes a new key and certificate (generation plus one). The old issuer stops issuing but keeps serving its CRL and OCSP, with replacedBy pointing at the new one.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'issuers'; const cur = st.issuers.find((i) => i.id === 'iss-nw-g2'); if (cur && cur.state === 'active') rotate(ctx, cur, true); else ctx.rerender(); } },
      { title: 'Certificate expiring in 7 days', tone: 'warn', text: 'The pki.expiry sweep notified the requester at 30 days and again at 7 (kind pki.certificate.expiring, also by email). A certificate with a valid renewal is skipped.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'certs'; st.stateFilter = 'expiring'; st.selCert = 'c-7728'; st.expiryNote = true; ctx.rerender(); } },
      { title: 'ACME order invalid', tone: 'danger', text: 'The dns-01 challenge found no TXT record. The challenge, its authorization and the order are invalid; the client must place a new order.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'acme'; st.acmeTab = 'orders'; st.orderFilter = 'invalid'; st.selOrder = 'ord-2305'; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state; init(st);
      if (ctx.params.id) { const id = ctx.params.id; delete ctx.params.id; if (st.certs.some((c) => c.id === id)) { st.tab = 'certs'; st.selCert = id; } else if (st.issuers.some((i) => i.id === id)) { st.tab = 'issuers'; st.selIssuer = id; } }
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }
      const custodyDown = st.custody === 'unavailable';
      const active = st.issuers.find((i) => i.kind === 'intermediate' && i.state === 'active');
      const expiring = st.certs.filter((c) => c.state === 'valid' && c.daysLeft <= 30);
      const tabs = UI.tabs([{ id: 'issuers', label: 'Issuers', count: st.issuers.length }, { id: 'certs', label: 'Certificates', count: st.certs.length }, { id: 'profiles', label: 'Profiles', count: st.profiles.length }, { id: 'acme', label: 'ACME', count: st.orders.filter((o) => o.status === 'pending' || o.status === 'processing' || o.status === 'ready').length }], st.tab);

      let body = '', insp = '';
      // ---------------- Issuers ----------------
      if (st.tab === 'issuers') {
        const sel = st.issuers.find((i) => i.id === st.selIssuer) || st.issuers[0];
        body += custodyDown ? UI.notice('<b>Custody unavailable.</b> Neither the signer process (SIGNER_SOCKET) nor OpenBao transit answers. Issuers and the OCSP responder keep working from stored certificates; anything that makes or uses a private key answers <span class="mono">409</span> with <span class="mono">step: custody</span>.', 'warn', UI.btn('Platform status', { size: 'sm', attrs: 'data-goplatform' }) + UI.btn('Retry', { kind: 'ghost', size: 'sm', attrs: 'data-retrycustody' })) : '';
        body += UI.table(['Issuer', 'Kind', 'Key', 'Custody', 'Gen', 'Valid from', 'Valid to', 'CRL', 'State'], st.issuers.map((i) => ({ cells: [esc(i.name) + (i.tenant === 'platform' ? ' ' + UI.pill('platform', 'outline') : ''), esc(i.kind), '<span class="mono">' + esc(i.keyType) + '</span>', esc(i.custody), '<span class="num">' + i.generation + '</span>', esc(i.notBefore), esc(i.notAfter), '<span class="num">' + i.crlNumber + '</span>', UI.pill(i.state, i.state === 'active' ? 'ok' : i.state === 'retired' ? '' : 'danger') + (i.replacedBy ? ' <span class="muted" style="font-size:12px">replaced by gen ' + (st.issuers.find((x) => x.id === i.replacedBy) || {}).generation + '</span>' : '')], attrs: 'data-issuer="' + i.id + '"', selected: i.id === sel.id })), { minWidth: '820px' })
          + '<div class="muted" style="font-size:12px">A root is retired by rotation, never revoked. One active intermediate per tenant: it carries the CRL distribution point and the OCSP and caIssuers URLs of the root\'s public routes. <a href="#" data-goplatform>The root belongs to Platform</a> and needs platform:manage.</div>';
        const chain = sel.kind === 'root' ? [sel] : [sel, st.issuers[0]];
        insp = '<div class="eyebrow">Selected issuer</div><div style="font-size:15px;font-weight:600">' + esc(sel.name) + ' <span class="muted">G' + sel.generation + '</span></div>'
          + UI.kv([['State', UI.pill(sel.state, sel.state === 'active' ? 'ok' : sel.state === 'retired' ? '' : 'danger')], ['Serial', '<span class="mono">' + esc(sel.serial) + '</span>'], ['Key type', '<span class="mono">' + esc(sel.keyType) + '</span>'], ['Custody', esc(custodyDown ? 'unavailable' : sel.custody)], ['Path length', esc(sel.pathLen)], ['Validity', esc(sel.notBefore) + ' to ' + esc(sel.notAfter)], ['Issued certificates', '<span class="num">' + st.certs.filter((c) => c.issuer === sel.id).length + '</span>'], ['Replaced by', sel.replacedBy ? '<a href="#" data-issuerlink="' + sel.replacedBy + '">generation ' + (st.issuers.find((x) => x.id === sel.replacedBy) || {}).generation + '</a>' : 'no']], 2)
          + '<div class="eyebrow">Chain</div>' + UI.timeline(chain.map((c, i) => ({ title: esc(c.name) + ' G' + c.generation, text: c.kind === 'root' ? 'self-signed, keyCertSign and cRLSign' : 'signed by the active root, pathLen 0', tone: i === 0 ? 'accent' : 'ok' })))
          + '<div class="eyebrow">Public URLs</div><div class="vstack gap4 mono" style="font-size:11px;overflow-wrap:anywhere">' + ['crl', 'cert', 'ocsp'].map((k) => '<span>' + esc(sel.urls[k]) + '</span>').join('') + '</div>'
          + '<div class="eyebrow">Last CRLs</div>' + UI.table(['No.', 'This update', 'Next update', 'Entries'], sel.crls.map((c) => ['<span class="num">' + c.number + '</span>', esc(c.thisUpdate), esc(c.nextUpdate), '<span class="num">' + c.entries + '</span>']), { clickable: false, minWidth: '0', cls: 'bare' })
          + '<div class="hstack wrap gap6">' + UI.btn('Rotate', { kind: 'primary', size: 'sm', attrs: 'data-rotate', disabled: custodyDown || sel.state !== 'active', title: custodyDown ? 'Needs key custody' : '' }) + UI.btn('Reissue', { size: 'sm', attrs: 'data-reissue', disabled: custodyDown || sel.state === 'revoked' }) + UI.btn('Sign CRL now', { size: 'sm', attrs: 'data-crl', disabled: sel.state === 'revoked' }) + (sel.kind === 'intermediate' && sel.state === 'active' ? UI.btn('Revoke', { kind: 'danger', size: 'sm', attrs: 'data-revokeissuer' }) : '') + '</div>'
          + '<span class="muted" style="font-size:12px">Rotate, reissue and revoke need a recent sign-in.</span>';
      }
      // ---------------- Certificates ----------------
      if (st.tab === 'certs') {
        const q = st.query.toLowerCase();
        let rows = st.certs.filter((c) => (!q || (c.cn + ' ' + c.sans.join(' ') + ' ' + c.serial + ' ' + c.requestedBy).toLowerCase().includes(q))
          && (st.stateFilter === 'all' || (st.stateFilter === 'expiring' ? c.state === 'valid' && c.daysLeft <= 30 : c.state === st.stateFilter))
          && (st.issuerFilter === 'all' || c.issuer === st.issuerFilter) && (st.profileFilter === 'all' || c.profile === st.profileFilter));
        rows = rows.slice().sort((a, b) => st.sort === 'cn' ? a.cn.localeCompare(b.cn) : st.sort === 'issued' ? parseDay(b.notBefore) - parseDay(a.notBefore) : (a.state === 'revoked') - (b.state === 'revoked') || a.daysLeft - b.daysLeft);
        if (!rows.some((c) => c.id === st.selCert)) st.selCert = rows.length ? rows[0].id : null;
        const sel = st.certs.find((c) => c.id === st.selCert);
        body += (st.problem ? UI.problem('Name refused by profile ' + st.problem.profile, 'The CSR asks for ' + st.problem.name.type + ' name ' + st.problem.name.value + ', which the profile\'s domains (*.northwind.local, ai.northwind.local) do not allow. 422, step: names. Nothing was issued; the refusal is audited as pki.issue.refused. Fix the CSR or ask a pki admin to widen the profile.', '7c2e51a0d9b34f8e9a1b6c0d2e3f4a5b') + '<div>' + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearproblem' }) + UI.btn('Open profile', { kind: 'ghost', size: 'sm', attrs: 'data-openprofile="p-servers"' }) + '</div>' : '')
          + (st.expiryNote && sel && sel.daysLeft <= 7 && sel.state === 'valid' ? UI.notice('<b>' + esc(sel.cn) + ' expires in ' + sel.daysLeft + ' days.</b> ' + esc(sel.requestedBy) + ' was notified at 30 days (20 Aug) and at 7 days (18 Sep), in the console and by email. Renew it here or let the ACME client order again.', 'warn', UI.btn('Renew now', { size: 'sm', attrs: 'data-renew' })) : '')
          + (expiring.length && !st.expiryNote ? UI.notice('<b>' + expiring.length + ' certificates expire within 30 days.</b> ' + esc(expiring.map((c) => c.cn + ' (' + c.daysLeft + ' d)').join(', ')) + '. Owners have been notified; renewals in flight are skipped.', 'warn', UI.btn('Show', { size: 'sm', attrs: 'data-showexpiring' })) : '')
          + (st.revealed ? UI.notice('<b>' + esc(st.revealed.title) + '</b> ' + esc(st.revealed.text) + '<div class="mono" style="margin-top:4px;overflow-wrap:anywhere;font-size:11px">' + esc(st.revealed.secret) + '</div>', 'warn', UI.btn('Copy', { size: 'sm', attrs: 'data-copy="' + esc(st.revealed.secret) + '"' }) + UI.btn('Done', { kind: 'ghost', size: 'sm', attrs: 'data-revealdone' })) : '')
          + '<div class="toolbar">' + UI.search('Filter by name, SAN, serial or requester', 'data-search', st.query)
          + '<span class="relative">' + UI.btn(st.stateFilter === 'all' ? 'State' : 'State: ' + st.stateFilter, { size: 'sm', icon: 'filter', attrs: 'data-menu="state"', cls: st.stateFilter !== 'all' ? 'active' : '' }) + '</span>'
          + '<span class="relative">' + UI.btn(st.issuerFilter === 'all' ? 'Issuer' : 'Issuer: G' + (st.issuers.find((i) => i.id === st.issuerFilter) || {}).generation, { size: 'sm', icon: 'filter', attrs: 'data-menu="issuer"', cls: st.issuerFilter !== 'all' ? 'active' : '' }) + '</span>'
          + '<span class="relative">' + UI.btn(st.profileFilter === 'all' ? 'Profile' : 'Profile: ' + st.profileFilter, { size: 'sm', icon: 'filter', attrs: 'data-menu="profile"', cls: st.profileFilter !== 'all' ? 'active' : '' }) + '</span>'
          + '<span class="relative">' + UI.btn(SORT_LABEL[st.sort], { size: 'sm', icon: 'sort', attrs: 'data-menu="sort"' }) + '</span>'
          + '<span class="muted right" style="font-size:12px">' + rows.length + ' of ' + st.certs.length + '</span></div>'
          + UI.table(['Common name', 'SANs', 'Profile', 'Serial', 'Key', 'Issued', 'Expires', 'State', 'Requested by'], rows.map((c) => ({ cells: [esc(c.cn), '<span class="muted" style="font-size:12px">' + esc(c.sans.join(', ')) + '</span>', '<a href="#" data-openprofile="' + esc((st.profiles.find((p) => p.name === c.profile) || {}).id || '') + '">' + esc(c.profile) + '</a>', '<span class="mono" style="font-size:11px">' + esc(c.serial) + '</span>', '<span class="mono">' + esc(c.keyType) + '</span>', esc(c.notBefore), expiryCell(c), statePill(c), esc(c.requestedBy)], attrs: 'data-cert="' + c.id + '"', selected: c.id === st.selCert })), { minWidth: '980px', emptyTitle: 'No certificates match', emptyText: 'Clear the filters to see the tenant\'s certificates, newest first.' });
        if (sel) {
          const issuer = st.issuers.find((i) => i.id === sel.issuer);
          insp = '<div class="hstack"><div class="eyebrow grow">Selected certificate</div>' + statePill(sel) + '</div><div style="font-size:15px;font-weight:600;overflow-wrap:anywhere">' + esc(sel.cn) + '</div>'
            + UI.kv([['Serial', '<span class="mono" style="font-size:11px">' + esc(sel.serial) + '</span>'], ['Key type', '<span class="mono">' + esc(sel.keyType) + '</span>'], ['Issuer', '<a href="#" data-issuerlink="' + sel.issuer + '">' + esc(issuer.name) + ' G' + issuer.generation + '</a>'], ['Profile', esc(sel.profile)], ['Not before', esc(sel.notBefore)], ['Not after', esc(sel.notAfter)], ['Requested by', esc(sel.requestedBy)], ['ACME account', sel.acme ? '<a href="#" data-acmeacct="' + sel.acme + '">' + esc(sel.acme) + '</a>' : 'none'], ['Renewed from', sel.renewedFrom ? '<a href="#" data-certlink="' + sel.renewedFrom + '">' + esc(sel.renewedFrom) + '</a>' : 'no'], ['Renewal', (st.certs.find((c) => c.renewedFrom === sel.id) || {}).id ? '<a href="#" data-certlink="' + st.certs.find((c) => c.renewedFrom === sel.id).id + '">' + esc(st.certs.find((c) => c.renewedFrom === sel.id).id) + '</a>' : 'none']], 2)
            + (sel.state === 'revoked' ? UI.notice('<b>Revoked ' + esc(sel.revokedAt) + '</b>, reason <span class="mono">' + esc(sel.reason) + '</span>' + (sel.invalidityDate ? ', invalid since ' + esc(sel.invalidityDate) : '') + '. On CRL ' + issuer.crlNumber + '; OCSP answers revoked.', 'danger') : '')
            + '<div class="eyebrow">Subject alternative names</div><div class="vstack gap4">' + sel.sans.map((s) => '<span class="mono" style="font-size:12px">' + esc(s) + '</span>').join('') + '</div>'
            + '<div class="eyebrow">Fingerprint</div><div class="mono" style="font-size:11px;overflow-wrap:anywhere">' + esc(sel.fp) + '</div>'
            + '<div class="eyebrow">Chain</div>' + UI.timeline([{ title: esc(sel.cn), text: 'end-entity, ' + esc(sel.keyType), tone: sel.state === 'revoked' ? 'danger' : 'accent' }, { title: esc(issuer.name) + ' G' + issuer.generation, text: 'intermediate, pathLen 0', tone: 'ok' }, { title: esc(st.issuers[0].name), text: 'root, from the trust store', tone: 'ok' }])
            + '<div class="hstack wrap gap6">' + UI.btn('Renew', { kind: 'primary', size: 'sm', attrs: 'data-renew', disabled: sel.state === 'revoked' || custodyDown }) + UI.btn('Export', { size: 'sm', icon: 'download', attrs: 'data-export' }) + UI.btn('PKCS#12', { size: 'sm', attrs: 'data-p12' }) + (sel.state !== 'revoked' ? UI.btn('Revoke', { kind: 'danger', size: 'sm', attrs: 'data-revokecert' }) : '') + '</div>';
        }
      }
      // ---------------- Profiles ----------------
      if (st.tab === 'profiles') {
        const kindNote = { server: 'dNSName and iPAddress, serverAuth, at most 398 days', client: 'dNSName, iPAddress, rfc822Name and URI, clientAuth, 825 days', 'code-signing': 'rfc822Name and URI, needs a CN, codeSigning, 1185 days' };
        body += '<div class="hstack"><span class="muted grow" style="font-size:12px">A profile is the upper bound of what may be issued under it: names, key types and lifetime. Each CSR\'s names are checked against it; a refusal is 422 with the step and the name.</span>' + UI.btn('New profile', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newprofile' }) + '</div>'
          + '<div class="grid3">' + st.profiles.map((p) => UI.panel(null, '<div class="hstack"><div style="font-size:15px;font-weight:600" class="grow mono">' + esc(p.name) + '</div>' + UI.pill(p.state, p.state === 'active' ? 'ok' : '') + '</div><div class="muted" style="font-size:12px">' + esc(p.kind) + ': ' + esc(kindNote[p.kind]) + '</div>'
            + UI.kv([['Max days', '<span class="num">' + p.maxDays + '</span>'], ['Default days', '<span class="num">' + p.defaultDays + '</span>'], ['Issued', '<span class="num">' + p.issued + '</span>'], ['Wildcards', p.policy.allowWildcard ? 'allowed' : 'refused']], 2)
            + '<div class="eyebrow">Policy</div><div class="vstack gap4" style="font-size:12px">' + (p.policy.domains.length ? '<div><span class="muted">Domains</span> <span class="mono">' + esc(p.policy.domains.join(', ')) + '</span></div>' : '') + (p.policy.ipRanges.length ? '<div><span class="muted">IP ranges</span> <span class="mono">' + esc(p.policy.ipRanges.join(', ')) + '</span></div>' : '') + (p.policy.emailDomains.length ? '<div><span class="muted">Email domains</span> <span class="mono">' + esc(p.policy.emailDomains.join(', ')) + '</span></div>' : '') + (p.policy.uriPrefixes.length ? '<div><span class="muted">URI prefixes</span> <span class="mono">' + esc(p.policy.uriPrefixes.join(', ')) + '</span></div>' : '') + '<div><span class="muted">Key types</span> <span class="mono">' + esc(p.policy.keyTypes.join(', ')) + '</span></div></div>'
            + '<div class="hstack wrap gap6">' + UI.btn('Edit', { size: 'sm', attrs: 'data-editprofile="' + p.id + '"' }) + UI.btn(p.state === 'active' ? 'Disable' : 'Enable', { size: 'sm', attrs: 'data-toggleprofile="' + p.id + '"' }) + UI.btn('Delete', { kind: 'ghost', size: 'sm', attrs: 'data-delprofile="' + p.id + '"', disabled: p.issued > 0, title: p.issued > 0 ? 'Certificates were issued under it' : '' }) + '</div>', { attrs: 'data-profilecard="' + p.id + '"' })).join('') + '</div>';
      }
      // ---------------- ACME ----------------
      if (st.tab === 'acme') {
        const a = st.acme; const prof = st.profiles.find((p) => p.name === a.profile);
        body += UI.panel('Directory', '<div class="formgrid" style="--cols:3">' + UI.field('Directory', UI.toggle(a.enabled ? 'Open' : 'Closed', a.enabled, 'data-acmetoggle data-manual')) + UI.field('Server profile', UI.select(st.profiles.filter((p) => p.kind === 'server').map((p) => p.name), a.profile, 'data-acmeprofile'), 'Orders are issued under it; its names are the upper bound') + UI.field('External account binding', UI.toggle(a.eabRequired ? 'Required' : 'Not required', a.eabRequired, 'data-eabtoggle data-manual')) + '</div>'
          + '<div class="hstack wrap gap6"><span class="muted" style="font-size:12px">Challenges</span>' + UI.chip('http-01', a.challenges.includes('http-01'), 'data-chall="http-01"') + UI.chip('dns-01', a.challenges.includes('dns-01'), 'data-chall="dns-01"') + '<span class="muted" style="font-size:12px">Wildcards need dns-01' + (prof && prof.policy.allowWildcard ? '' : '; profile ' + esc(a.profile) + ' refuses wildcards anyway') + '</span></div>'
          + UI.kv([['Directory URL', '<span class="mono" style="font-size:11px">' + esc(a.directoryUrl) + '</span> ' + UI.btn('Copy', { kind: 'ghost', size: 'xs', attrs: 'data-copy="' + esc(a.directoryUrl) + '"' })], ['Updated', esc(a.updatedAt) + ' by Jonas Lindqvist']], 2)
          + (a.enabled ? '' : UI.notice('<b>The directory is closed.</b> Clients get 404 with an ACME problem until it is opened again; existing certificates stay valid.', 'info')), { actions: UI.btn('Save', { kind: 'primary', size: 'sm', attrs: 'data-acmesave' }) });
        body += UI.tabs([{ id: 'eab', label: 'EAB keys', count: st.eab.length }, { id: 'accounts', label: 'Accounts', count: st.accounts.length }, { id: 'orders', label: 'Orders', count: st.orders.length }], st.acmeTab, 'data-subtabs');
        if (st.acmeTab === 'eab') {
          body += (st.revealed && st.revealed.kind === 'eab' ? UI.notice('<b>EAB key ' + esc(st.revealed.title) + ' created.</b> The HMAC key is shown once; give the client this kid and key. It binds one account.<div class="mono" style="margin-top:4px;overflow-wrap:anywhere;font-size:11px">kid ' + esc(st.revealed.kid) + '<br>hmacKey ' + esc(st.revealed.secret) + '</div>', 'warn', UI.btn('Copy', { size: 'sm', attrs: 'data-copy="' + esc(st.revealed.secret) + '"' }) + UI.btn('Done', { kind: 'ghost', size: 'sm', attrs: 'data-revealdone' })) : '')
            + '<div>' + UI.btn('Create EAB key', { kind: 'primary', size: 'sm', icon: 'key', attrs: 'data-neweab' }) + '</div>'
            + UI.table(['Name', 'Key id', 'State', 'Bound account', 'Created', 'Bound', { label: '', right: true }], st.eab.map((k) => [esc(k.name), '<span class="mono">' + esc(k.id) + '</span>', UI.pill(k.state, k.state === 'bound' ? 'ok' : k.state === 'active' ? 'info' : 'danger'), k.accountId ? '<a href="#" data-acmeacct="' + k.accountId + '">' + esc(k.accountId) + '</a>' : '<span class="muted">none yet</span>', esc(k.createdAt), esc(k.boundAt || ''), k.state === 'revoked' ? '' : UI.btn('Revoke', { kind: 'ghost', size: 'sm', attrs: 'data-revokeeab="' + k.id + '"' })]), { clickable: false, minWidth: '0' })
            + '<span class="muted" style="font-size:12px">The MAC key is sealed with the tenant key and never shown again. Revoking a key stops it binding an account; an account it already bound stays.</span>';
        } else if (st.acmeTab === 'accounts') {
          body += UI.table(['Account', 'Key thumbprint', 'Key', 'Contact', 'Status', 'EAB key', 'Orders', 'Created', { label: '', right: true }], st.accounts.map((ac) => ({ cells: ['<span class="mono">' + esc(ac.id) + '</span>', '<span class="mono" style="font-size:11px;overflow-wrap:anywhere">' + esc(ac.thumbprint) + '</span>', esc(ac.keyType), '<span class="mono" style="font-size:12px">' + esc(ac.contact) + '</span>', UI.pill(ac.status, ac.status === 'valid' ? 'ok' : ac.status === 'deactivated' ? '' : 'danger'), esc(ac.eabKeyId || ''), '<a href="#" data-acctorders="' + ac.id + '"><span class="num">' + ac.orders + '</span></a>', esc(ac.createdAt), ac.status === 'valid' ? UI.btn('Revoke', { kind: 'ghost', size: 'sm', attrs: 'data-revokeacct="' + ac.id + '"' }) : ''], attrs: 'data-acct="' + ac.id + '"', selected: ac.id === st.selAcct })), { minWidth: '900px' })
            + '<span class="muted" style="font-size:12px">Revoking an account (RFC 8555, by the server) makes its pending and ready orders invalid. Deactivation is the client\'s own doing.</span>';
        } else {
          const rows = st.orders.filter((o) => (st.orderFilter === 'all' || o.status === st.orderFilter) && (!st.orderAcct || o.accountId === st.orderAcct));
          if (!rows.some((o) => o.id === st.selOrder)) st.selOrder = rows.length ? rows[0].id : null;
          const o = st.orders.find((x) => x.id === st.selOrder);
          body += '<div class="toolbar"><span class="relative">' + UI.btn(st.orderFilter === 'all' ? 'Status' : 'Status: ' + st.orderFilter, { size: 'sm', icon: 'filter', attrs: 'data-menu="order"', cls: st.orderFilter !== 'all' ? 'active' : '' }) + '</span>' + (st.orderAcct ? UI.chip('account ' + esc(st.orderAcct) + ' <span class="x">×</span>', true, 'data-clearacct') : '') + '<span class="muted right" style="font-size:12px">' + rows.length + ' of ' + st.orders.length + ' orders, ' + st.orders.filter((x) => x.status !== 'valid' && x.status !== 'invalid').length + ' open (at most 300 per account)</span></div>'
            + UI.table(['Order', 'Account', 'Identifiers', 'Status', 'Expires', 'Certificate', 'Created'], rows.map((x) => ({ cells: ['<span class="mono">' + esc(x.id) + '</span>', '<span class="mono">' + esc(x.accountId) + '</span>', '<span class="mono" style="font-size:12px">' + esc(x.identifiers.join(', ')) + '</span>', UI.pill(x.status, x.status === 'valid' ? 'ok' : x.status === 'invalid' ? 'danger' : x.status === 'ready' ? 'info' : x.status === 'processing' ? 'info' : 'warn'), esc(x.expires), x.certificateId ? '<a href="#" data-certlink="' + x.certificateId + '">' + esc(x.certificateId) + '</a>' : '', esc(x.createdAt)], attrs: 'data-order="' + x.id + '"', selected: x.id === st.selOrder })), { minWidth: '820px', emptyTitle: 'No orders match' })
            + (o && o.status === 'invalid' ? UI.problem('Order ' + o.id + ' is invalid', o.error + '. The challenge, its authorization and the order are invalid; the client places a new order after fixing the record. Orders last PKI_ACME_ORDER_HOURS.', '0f3a9c1e22b7489d8e6a51c0d4f7b2a1') : o ? UI.panel('Order ' + o.id, UI.kv([['Status', UI.pill(o.status)], ['Identifiers', '<span class="mono">' + esc(o.identifiers.join(', ')) + '</span>'], ['Challenges', o.identifiers[0].startsWith('*') ? 'dns-01 (wildcard)' : esc(st.acme.challenges.join(', '))], ['Expires', esc(o.expires)]], 4) + '<span class="muted" style="font-size:12px">' + (o.status === 'pending' ? 'Waiting for the client to answer a challenge.' : o.status === 'processing' ? 'A pki.acme.validate job is fetching http://' + esc(o.identifiers[0]) + '/.well-known/acme-challenge/… through the service address checks.' : o.status === 'ready' ? 'Every name is proven; the client finalizes with a CSR naming exactly these names.' : 'Finalized and issued by the active intermediate.') + '</span>') : '');
        }
      }

      root.innerHTML = '<style>'
        + '#main > .page > *{flex-shrink:0}'
        + '#main .certificates-insp .kv .v{font-size:12px}'
        + '</style>'
        + '<div class="page">' + UI.pagehead('Certificates', 'The Northwind certificate authority: issuers in ' + esc(custodyDown ? 'unavailable custody' : 'the signer process') + ', profiles, issuance, revocation, CRLs and OCSP, and the ACME directory.', (active ? UI.pill('issuing CA G' + active.generation + ' active', 'ok') : UI.pill('no active intermediate', 'danger')) + UI.btn('Issue certificate', { kind: 'primary', icon: 'plus', attrs: 'data-issue', disabled: !active }) + UI.btn('Sign CRL now', { attrs: 'data-crl' }))
        + tabs + body
        + '<div style="margin-top:auto"><div class="eyebrow" style="margin-bottom:8px">States to design from this page</div>' + UI.states(this.states) + '</div></div>'
        + (insp ? '<aside class="inspector w360 certificates-insp" aria-label="Inspector">' + insp + '</aside>' : '');

      // ---- events ----
      ctx.on('click', '[data-tab]', (e, t) => { if (t.closest('[data-subtabs]')) st.acmeTab = t.dataset.tab; else st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', 'tr[data-issuer]', (e, t) => { st.selIssuer = t.dataset.issuer; ctx.rerender(); });
      ctx.on('click', 'tr[data-cert]', (e, t) => { if (e.target.closest('a')) return; st.selCert = t.dataset.cert; st.expiryNote = false; ctx.rerender(); });
      ctx.on('click', 'tr[data-order]', (e, t) => { if (e.target.closest('a')) return; st.selOrder = t.dataset.order; ctx.rerender(); });
      ctx.on('click', 'tr[data-acct]', (e, t) => { if (e.target.closest('a,button')) return; st.selAcct = t.dataset.acct; ctx.rerender(); });
      ctx.on('input', '[data-search]', (e, t) => { st.query = t.value; ctx.rerender(); const i = ctx.$('[data-search]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } });
      ctx.on('click', '[data-menu]', (e, t) => {
        const k = t.dataset.menu;
        if (k === 'state') menu(ctx, t, [['all', 'All states'], ['valid', 'Valid'], ['expiring', 'Expiring within 30 days'], ['revoked', 'Revoked']], st.stateFilter, (v) => { st.stateFilter = v; ctx.rerender(); });
        if (k === 'issuer') menu(ctx, t, [['all', 'Every issuer']].concat(st.issuers.filter((i) => i.kind === 'intermediate').map((i) => [i.id, i.name + ' G' + i.generation])), st.issuerFilter, (v) => { st.issuerFilter = v; ctx.rerender(); });
        if (k === 'profile') menu(ctx, t, [['all', 'Every profile']].concat(st.profiles.map((p) => [p.name, p.name])), st.profileFilter, (v) => { st.profileFilter = v; ctx.rerender(); });
        if (k === 'sort') menu(ctx, t, Object.keys(SORT_LABEL).map((s) => [s, SORT_LABEL[s]]), st.sort, (v) => { st.sort = v; ctx.rerender(); });
        if (k === 'order') menu(ctx, t, [['all', 'All statuses'], ['pending', 'Pending'], ['processing', 'Processing'], ['ready', 'Ready'], ['valid', 'Valid'], ['invalid', 'Invalid']], st.orderFilter, (v) => { st.orderFilter = v; ctx.rerender(); });
      });
      ctx.on('click', '[data-showexpiring]', () => { st.stateFilter = 'expiring'; st.sort = 'expiry'; ctx.rerender(); });
      ctx.on('click', '[data-clearproblem]', () => { st.problem = null; ctx.rerender(); });
      ctx.on('click', '[data-revealdone]', () => { st.revealed = null; ctx.rerender(); });
      ctx.on('click', '[data-copy]', (e, t) => { try { navigator.clipboard && navigator.clipboard.writeText(t.dataset.copy); } catch (err) { /* clipboard unavailable */ } ctx.toast('Copied.'); });
      ctx.on('click', '[data-goplatform]', (e) => { e.preventDefault(); ctx.navigate('platform'); });
      ctx.on('click', '[data-retrycustody]', () => { st.custody = 'signer process'; ctx.rerender(); ctx.toast('Signer process answering again on SIGNER_SOCKET. Key routes are back.', 'ok'); });
      ctx.on('click', '[data-issuerlink]', (e, t) => { e.preventDefault(); st.tab = 'issuers'; st.selIssuer = t.dataset.issuerlink; ctx.rerender(); });
      ctx.on('click', '[data-certlink]', (e, t) => { e.preventDefault(); st.tab = 'certs'; st.stateFilter = 'all'; st.issuerFilter = 'all'; st.profileFilter = 'all'; st.query = ''; st.selCert = t.dataset.certlink; st.expiryNote = false; ctx.rerender(); });
      ctx.on('click', '[data-acmeacct]', (e, t) => { e.preventDefault(); st.tab = 'acme'; st.acmeTab = 'accounts'; st.selAcct = t.dataset.acmeacct; ctx.rerender(); });
      ctx.on('click', '[data-acctorders]', (e, t) => { e.preventDefault(); st.acmeTab = 'orders'; st.orderAcct = t.dataset.acctorders; st.orderFilter = 'all'; ctx.rerender(); });
      ctx.on('click', '[data-clearacct]', () => { st.orderAcct = null; ctx.rerender(); });
      ctx.on('click', '[data-openprofile]', (e, t) => { e.preventDefault(); st.tab = 'profiles'; ctx.rerender(); const card = ctx.$('[data-profilecard="' + t.dataset.openprofile + '"]'); if (card) { card.style.outline = '2px solid var(--accent)'; setTimeout(() => { card.style.outline = ''; }, 1500); } });

      // issuers
      ctx.on('click', '[data-rotate]', () => { const i = st.issuers.find((x) => x.id === st.selIssuer); if (i) rotate(ctx, i, false); });
      ctx.on('click', '[data-reissue]', () => { const i = st.issuers.find((x) => x.id === st.selIssuer); ctx.confirm({ title: 'Reissue ' + esc(i.name) + ' G' + i.generation, tag: 'same key', tone: 'info', body: '<p class="fg2" style="margin:0">The same key gets a new serial and validity' + (i.kind === 'intermediate' ? ', signed by the current root' : '') + '. Certificates issued before still verify. Needs a recent sign-in.</p>' + UI.field('Validity (days)', UI.input(i.kind === 'root' ? '3650' : '1825', { type: 'number' })), kv: [['Issuer', esc(i.name)], ['Current serial', esc(i.serial)]], ok: 'Reissue' }).then((ok) => { if (!ok) return; i.serial = i.serial.replace(/^..:/, '7e:'); i.notBefore = '19 Sep 2026'; i.notAfter = i.kind === 'root' ? '17 Sep 2036' : '18 Sep 2031'; ctx.rerender(); ctx.toast(esc(i.name) + ' reissued. Audited pki.issuer.reissued.', 'ok'); }); });
      ctx.on('click', '[data-crl]', () => { const i = st.issuers.find((x) => x.id === st.selIssuer) || active; if (!i) return; i.crlNumber += 1; i.crls.unshift({ number: i.crlNumber, thisUpdate: 'just now', nextUpdate: 'in 6 h', entries: i.crls[0].entries }); i.crls = i.crls.slice(0, 5); ctx.rerender(); ctx.toast('pki.crl job queued for ' + esc(i.name) + ' (202). CRL ' + i.crlNumber + ' signed; the OCSP responder certificate was checked too.', 'ok'); });
      ctx.on('click', '[data-revokeissuer]', () => { const i = st.issuers.find((x) => x.id === st.selIssuer); ctx.confirm({ title: 'Revoke ' + esc(i.name) + ' G' + i.generation, tag: 'stops issuance', tone: 'danger', body: '<p class="fg2" style="margin:0">Every certificate under it stops verifying once relying parties see the root\'s next CRL (a pki.crl job is queued now). The tenant has no issuing CA until a new intermediate is created. Needs a recent sign-in.</p>' + UI.field('Reason', UI.select(['cACompromise', 'keyCompromise', 'affiliationChanged', 'cessationOfOperation'], 'cACompromise')), kv: [['Issuer', esc(i.name)], ['Issued certificates', String(st.certs.filter((c) => c.issuer === i.id).length)]], ok: 'Revoke issuer' }).then((ok) => { if (!ok) return; i.state = 'revoked'; i.revokedAt = 'just now'; st.issuers[0].crlNumber += 1; ctx.rerender(); ctx.toast(esc(i.name) + ' revoked. Listed on the root\'s CRL ' + st.issuers[0].crlNumber + '; audited pki.issuer.revoked.', 'danger', 5000); }); });

      // certificates
      ctx.on('click', '[data-issue]', () => issueModal(ctx));
      ctx.on('click', '[data-renew]', () => { const c = st.certs.find((x) => x.id === st.selCert); if (!c) return; let revokeOld = true; ctx.modal({ title: 'Renew ' + esc(c.cn), body: '<p class="fg2" style="margin:0">A new certificate for the same names under <b>' + esc(c.profile) + '</b>, from the active intermediate. Without a CSR it keeps the old certificate\'s key.</p><div class="formgrid">' + UI.field('CSR (optional)', UI.textarea('', { placeholder: '-----BEGIN CERTIFICATE REQUEST-----', rows: 3 })) + UI.field('Days', UI.input(String((st.profiles.find((p) => p.name === c.profile) || {}).defaultDays || 90), { type: 'number' })) + '</div>' + UI.toggle('Revoke the old certificate as superseded', true, 'data-revokeold'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Renew', { kind: 'primary', attrs: 'data-dorenew' }), onMount(m) { m.querySelector('[data-revokeold]').addEventListener('click', () => { revokeOld = !revokeOld; }); m.querySelector('[data-dorenew]').addEventListener('click', () => { App.closeOverlay(); const n = Object.assign({}, c, { id: 'c-77' + (40 + st.certs.length), serial: c.serial.replace(/..$/, 'f' + st.certs.length), notBefore: '19 Sep 2026', notAfter: '18 Dec 2026', daysLeft: 90, state: 'valid', renewedFrom: c.id, requestedBy: 'Mara Okafor', acme: null, revokedAt: null, reason: null }); st.certs.unshift(n); if (revokeOld && c.state === 'valid') { c.state = 'revoked'; c.revokedAt = 'just now'; c.reason = 'superseded'; } st.selCert = n.id; st.expiryNote = false; st.stateFilter = 'all'; ctx.rerender(); ctx.toast(esc(c.cn) + ' renewed as ' + n.id + (revokeOld ? '; the old one is revoked as superseded' : '') + '. Audited pki.certificate.renewed.', 'ok', 5000); }); } }); });
      ctx.on('click', '[data-revokecert]', () => { const c = st.certs.find((x) => x.id === st.selCert); if (!c) return; ctx.confirm({ title: 'Revoke ' + esc(c.cn), tag: 'RFC 5280', tone: 'danger', body: '<p class="fg2" style="margin:0">Cached OCSP answers are dropped on every instance and the issuer\'s next CRL is queued. Holds and removeFromCRL are not supported; cACompromise is for issuers.</p><div class="formgrid">' + UI.field('Reason', UI.select(REASONS, 'keyCompromise', 'data-reason')) + UI.field('Invalidity date (optional)', UI.input('', { type: 'date', attrs: 'data-invalidity' })) + '</div>', kv: [['Serial', esc(c.serial)], ['Profile', esc(c.profile)], ['Expires', esc(c.notAfter)]], ok: 'Revoke' }).then((ok) => { if (!ok) return; c.state = 'revoked'; c.revokedAt = 'just now'; c.reason = (document.querySelector('[data-reason]') || {}).value || 'keyCompromise'; const i = st.issuers.find((x) => x.id === c.issuer); i.crlNumber += 1; i.crls.unshift({ number: i.crlNumber, thisUpdate: 'just now', nextUpdate: 'in 6 h', entries: i.crls[0].entries + 1 }); i.crls = i.crls.slice(0, 5); ctx.rerender(); ctx.toast(esc(c.cn) + ' revoked (' + esc(c.reason) + '). OCSP answers revoked now; CRL ' + i.crlNumber + ' queued.', 'danger', 5000); }); });
      ctx.on('click', '[data-export]', (e, t) => menu(ctx, t.parentElement.classList.contains('relative') ? t : wrapRelative(t), [['pem', 'PEM (application/x-pem-file)'], ['der', 'DER (application/pkix-cert)'], ['chain', 'Chain up to the root (PEM)']], null, (v) => ctx.toast('Download started: ' + esc(st.selCert) + '.' + (v === 'chain' ? 'chain.pem' : v) + '. Audited pki.certificate.exported.', 'ok')));
      ctx.on('click', '[data-p12]', () => { const c = st.certs.find((x) => x.id === st.selCert); ctx.modal({ title: 'PKCS#12 for ' + esc(c.cn), body: '<p class="fg2" style="margin:0">The certificate and its chain as a PKCS#12 file: PBES2 with PBKDF2-HMAC-SHA256 (100,000 iterations) and AES-256-CBC, HMAC-SHA256 integrity. It holds no private key; the CA never had it.</p>' + UI.field('Password', UI.input('', { type: 'password', placeholder: '8 to 200 characters', attrs: 'data-p12pw' })), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Download', { kind: 'primary', attrs: 'data-dop12' }), onMount(m) { m.querySelector('[data-dop12]').addEventListener('click', () => { const pw = m.querySelector('[data-p12pw]').value; if (pw.length < 8) { ctx.toast('The password needs at least 8 characters.', 'warn'); return; } App.closeOverlay(); ctx.toast('Download started: ' + esc(c.id) + '.p12 (application/x-pkcs12).', 'ok'); }); } }); });

      // profiles
      ctx.on('click', '[data-newprofile]', () => profileModal(ctx, null));
      ctx.on('click', '[data-editprofile]', (e, t) => profileModal(ctx, st.profiles.find((p) => p.id === t.dataset.editprofile)));
      ctx.on('click', '[data-toggleprofile]', (e, t) => { const p = st.profiles.find((x) => x.id === t.dataset.toggleprofile); p.state = p.state === 'active' ? 'disabled' : 'active'; ctx.rerender(); ctx.toast('Profile ' + esc(p.name) + ' ' + p.state + '. Audited pki.profile.updated.', p.state === 'active' ? 'ok' : 'warn'); });
      ctx.on('click', '[data-delprofile]', (e, t) => { const p = st.profiles.find((x) => x.id === t.dataset.delprofile); ctx.confirm({ title: 'Delete profile ' + esc(p.name), tone: 'danger', body: '<p class="fg2" style="margin:0">No certificate was issued under it. The ACME directory cannot name it afterwards.</p>', ok: 'Delete' }).then((ok) => { if (!ok) return; st.profiles = st.profiles.filter((x) => x.id !== p.id); ctx.rerender(); ctx.toast('Profile deleted (204). Audited pki.profile.deleted.', 'ok'); }); });

      // acme
      ctx.on('click', '[data-acmetoggle]', () => { st.acme.enabled = !st.acme.enabled; ctx.rerender(); });
      ctx.on('click', '[data-eabtoggle]', () => { st.acme.eabRequired = !st.acme.eabRequired; ctx.rerender(); });
      ctx.on('change', '[data-acmeprofile]', (e, t) => { st.acme.profile = t.value; ctx.rerender(); });
      ctx.on('click', '[data-chall]', (e, t) => { const c = t.dataset.chall; const i = st.acme.challenges.indexOf(c); if (i >= 0) { if (st.acme.challenges.length === 1) { ctx.toast('Keep at least one challenge type.', 'warn'); return; } st.acme.challenges.splice(i, 1); } else st.acme.challenges.push(c); ctx.rerender(); });
      ctx.on('click', '[data-acmesave]', () => { st.acme.updatedAt = 'just now'; ctx.rerender(); ctx.toast('ACME settings saved. Audited pki.acme.settings.updated. The directory ' + (st.acme.enabled ? 'answers at ' + esc(st.acme.directoryUrl) : 'is closed (404)') + '.', 'ok'); });
      ctx.on('click', '[data-neweab]', () => ctx.modal({ title: 'Create EAB key', body: '<p class="fg2" style="margin:0">An external account binding key (RFC 8555 7.3.4). The HMAC key is shown once and binds one account.</p>' + UI.field('Name', UI.input('', { placeholder: 'e.g. traefik edge', attrs: 'data-eabname' })), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create', { kind: 'primary', attrs: 'data-doeab' }), onMount(m) { m.querySelector('[data-doeab]').addEventListener('click', () => { const name = m.querySelector('[data-eabname]').value.trim() || 'new client'; App.closeOverlay(); const id = 'eab-' + (st.eab.length + 3); st.eab.unshift({ id, name, state: 'active', accountId: null, createdAt: '19 Sep 2026', boundAt: null }); st.revealed = { kind: 'eab', title: name, kid: id, secret: 'q7Vb2nX9pL0kRz4sTe8wYh1uJc6mAo3fGd5iBk2nQp0', text: '' }; ctx.rerender(); ctx.toast('EAB key created. Audited pki.acme.eab.created.', 'ok'); }); } }));
      ctx.on('click', '[data-revokeeab]', (e, t) => { const k = st.eab.find((x) => x.id === t.dataset.revokeeab); ctx.confirm({ title: 'Revoke EAB key ' + esc(k.name), tone: 'danger', body: '<p class="fg2" style="margin:0">The key can no longer bind an account.' + (k.accountId ? ' Account ' + esc(k.accountId) + ', which it bound, stays valid.' : '') + '</p>', ok: 'Revoke' }).then((ok) => { if (!ok) return; k.state = 'revoked'; ctx.rerender(); ctx.toast('EAB key revoked. Audited pki.acme.eab.revoked.', 'ok'); }); });
      ctx.on('click', '[data-revokeacct]', (e, t) => { const ac = st.accounts.find((x) => x.id === t.dataset.revokeacct); const open = st.orders.filter((o) => o.accountId === ac.id && (o.status === 'pending' || o.status === 'ready' || o.status === 'processing')); ctx.confirm({ title: 'Revoke account ' + esc(ac.id), tag: 'RFC 8555', tone: 'danger', body: '<p class="fg2" style="margin:0">The account is revoked by the server. Its ' + open.length + ' pending and ready orders become invalid; certificates it already holds stay valid.</p>', kv: [['Contact', esc(ac.contact)], ['Orders', String(ac.orders)]], ok: 'Revoke account' }).then((ok) => { if (!ok) return; ac.status = 'revoked'; open.forEach((o) => { o.status = 'invalid'; o.error = 'account revoked'; }); ctx.rerender(); ctx.toast('Account ' + esc(ac.id) + ' revoked; ' + open.length + ' orders invalid. Audited pki.acme.account.revoked.', 'danger'); }); });
      ctx.on('click', '.state-card', (e, t) => ctx.app.applyState(+t.dataset.state));
    }
  });

  function wrapRelative(btn) { const s = document.createElement('span'); s.className = 'relative'; btn.parentNode.insertBefore(s, btn); s.appendChild(btn); return btn; }

  function rotate(ctx, i, silent) {
    const st = ctx.state;
    const doIt = () => {
      const n = Object.assign({}, i, { id: i.id.replace(/g\d+$/, 'g' + (i.generation + 1)), generation: i.generation + 1, serial: i.kind === 'root' ? '02' : '6c:2d:e0:91:ab', notBefore: '19 Sep 2026', notAfter: i.kind === 'root' ? '17 Sep 2036' : '18 Sep 2031', state: 'active', crlNumber: 1, replacedBy: null, crls: [{ number: 1, thisUpdate: 'just now', nextUpdate: 'in 6 h', entries: 0 }] });
      n.urls = { crl: 'https://ai.northwind.local/pki/crl/' + n.id + '.crl', cert: 'https://ai.northwind.local/pki/ca/' + n.id + '.crt', ocsp: 'https://ai.northwind.local/pki/ocsp' };
      i.state = 'retired'; i.replacedBy = n.id; i.retiredAt = 'just now';
      st.issuers.splice(st.issuers.indexOf(i) + 1, 0, n); st.selIssuer = n.id; ctx.rerender();
      ctx.toast(esc(i.name) + ' rotated to generation ' + n.generation + '. G' + i.generation + ' is retired: it stops issuing and keeps serving its CRL and OCSP. Audited pki.issuer.rotated.', 'ok', 5000);
    };
    if (silent) { doIt(); return; }
    ctx.confirm({ title: 'Rotate ' + esc(i.name) + ' G' + i.generation, tag: 'new key', tone: 'info', body: '<p class="fg2" style="margin:0">A new key and certificate in the signer process (generation ' + (i.generation + 1) + '). The current issuer becomes retired with replacedBy, stops issuing and keeps serving its CRL and OCSP, so certificates it issued stay verifiable. Needs a recent sign-in.</p>' + UI.field('Validity (days)', UI.input(i.kind === 'root' ? '3650' : '1825', { type: 'number' })), kv: [['Issuer', esc(i.name)], ['Key type', esc(i.keyType)], ['Issued under it', String(st.certs.filter((c) => c.issuer === i.id).length)]], ok: 'Rotate' }).then((ok) => { if (ok) doIt(); });
  }

  function issueModal(ctx) {
    const st = ctx.state; const active = st.issuers.find((i) => i.kind === 'intermediate' && i.state === 'active'); if (!active) return;
    let mode = 'csr';
    const body = () => '<div class="seg" data-issuemode>' + ['csr', 'generate'].map((m) => '<button type="button" data-seg="' + m + '" class="' + (m === mode ? 'active' : '') + '">' + (m === 'csr' ? 'From a CSR' : 'Generate the key here') + '</button>').join('') + '</div>'
      + '<div class="formgrid">' + (mode === 'csr' ? '<div class="span2">' + UI.field('CSR (PEM PKCS#10)', UI.textarea('', { placeholder: '-----BEGIN CERTIFICATE REQUEST-----\nMIIC…', rows: 4, attrs: 'data-csr' }), 'Its self-signature must verify (400, step csr). Keys: P-256, P-384, RSA 2048 to 4096, Ed25519, as the profile allows.') + '</div>' : UI.field('Key type', UI.select(['ec-p256', 'ec-p384', 'rsa-2048', 'rsa-3072', 'rsa-4096'], 'ec-p256')) + UI.field('PKCS#12 password', UI.input('', { type: 'password', placeholder: '8 to 200 characters', attrs: 'data-genpw' }), 'The key is made here, bundled with the certificate and chain, returned once and never stored'))
      + UI.field('Profile', UI.select(st.profiles.filter((p) => p.state === 'active').map((p) => p.name), 'servers-internal', 'data-iprofile')) + UI.field('Days', UI.input('90', { type: 'number', attrs: 'data-idays' }), 'Over the profile\'s maximum is 422; never past the issuer\'s expiry (clamped)')
      + (mode === 'generate' ? UI.field('Common name', UI.input('', { placeholder: 'grafana.northwind.local', attrs: 'data-icn' })) : '') + '<div class="span2">' + UI.field('Subject alternative names', UI.input('', { placeholder: 'dns:grafana.northwind.local, ip:10.20.4.30', attrs: 'data-isans' }), 'Else the CSR\'s subjectAltName, else (server profiles) its CN. Each name is checked against the profile.') + '</div></div>'
      + UI.notice('Issued at once by <b>' + esc(active.name) + ' G' + active.generation + '</b>. A name outside the profile is refused with 422 (step names) and audited as pki.issue.refused.', 'info');
    const m = ctx.modal({ title: 'Issue certificate', cls: 'wide', body: body(), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Issue', { kind: 'primary', attrs: 'data-doissue' }), onMount(el) { wire(el); } });
    function wire(el) {
      el.querySelectorAll('[data-issuemode] [data-seg]').forEach((b) => b.addEventListener('click', () => { mode = b.dataset.seg; el.querySelector('.vstack').innerHTML = body(); wire(el); }));
      el.querySelector('[data-doissue]').addEventListener('click', () => {
        const prof = st.profiles.find((p) => p.name === el.querySelector('[data-iprofile]').value);
        const days = +el.querySelector('[data-idays]').value || prof.defaultDays;
        const sansRaw = el.querySelector('[data-isans]').value.trim();
        const sans = sansRaw ? sansRaw.split(',').map((s) => s.trim()).filter(Boolean) : (mode === 'csr' ? ['dns:grafana.northwind.local'] : []);
        const cn = mode === 'generate' ? (el.querySelector('[data-icn]').value.trim() || (sans[0] || 'dns:new-host.northwind.local').replace(/^\w+:/, '')) : (sans[0] || 'dns:grafana.northwind.local').replace(/^\w+:/, '');
        if (mode === 'generate' && el.querySelector('[data-genpw]').value.length < 8) { ctx.toast('The PKCS#12 password needs at least 8 characters.', 'warn'); return; }
        if (days > prof.maxDays) { ctx.toast('422, step lifetime: ' + days + ' days is over the profile\'s maximum of ' + prof.maxDays + '.', 'danger'); return; }
        const bad = sans.find((s) => /^dns:/.test(s) && !prof.policy.domains.some((d) => d.startsWith('*.') ? s.slice(4).endsWith(d.slice(1)) && s.slice(4) !== d.slice(2) : s.slice(4) === d) && prof.kind === 'server');
        if (bad) { App.closeOverlay(); st.problem = { step: 'names', name: { type: 'dns', value: bad.slice(4) }, profile: prof.name }; ctx.rerender(); return; }
        App.closeOverlay();
        const c = { id: 'c-77' + (40 + st.certs.length), cn, sans: sans.length ? sans : ['dns:' + cn], profile: prof.name, issuer: active.id, serial: '5b:12:9e:47:c0:ab:' + (10 + st.certs.length).toString(16), keyType: mode === 'csr' ? 'P-256' : el.querySelector('select').value.replace('ec-p', 'P-').replace('rsa-', 'RSA '), notBefore: '19 Sep 2026', notAfter: days >= 365 ? '19 Sep 2027' : days >= 180 ? '18 Mar 2027' : '18 Dec 2026', daysLeft: days, state: 'valid', requestedBy: 'Mara Okafor', fp: 'SHA-256 ' + 'A0:1B:2C:3D:4E:5F:60:71:82:93:A4:B5:C6:D7:E8:F9:0A:1B:2C:3D:4E:5F:60:71:82:93:A4:B5:C6:D7:E8:F9' };
        st.certs.unshift(c); prof.issued += 1; st.selCert = c.id; st.stateFilter = 'all'; st.query = '';
        if (mode === 'generate') st.revealed = { title: c.id + ' issued with a generated key.', text: 'The PKCS#12 bundle is downloaded once and never stored; audited pki.certificate.issued with keyGenerated true.', secret: 'MIIKcQIBAzCCCjcGCSqGSIb3DQEHAaCCCigEggokMIIKIDCCBNcGCSqGSIb3DQEHBqCCBMgwggTEAgEAMIIEvQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI…' };
        ctx.rerender(); ctx.toast(esc(cn) + ' issued by ' + esc(active.name) + ' G' + active.generation + ' for ' + days + ' days (201). Audited pki.certificate.issued.', 'ok', 5000);
      });
    }
    return m;
  }

  function profileModal(ctx, p) {
    const st = ctx.state; const isNew = !p;
    const v = p || { name: '', kind: 'server', maxDays: 398, defaultDays: 90, policy: { domains: [], allowWildcard: false, ipRanges: [], emailDomains: [], uriPrefixes: [], keyTypes: ['P-256', 'RSA 3072'] } };
    ctx.modal({ title: isNew ? 'New profile' : 'Edit profile ' + esc(v.name), cls: 'wide', body: '<div class="formgrid">' + UI.field('Name', UI.input(v.name, { attrs: 'data-pname', readonly: !isNew })) + UI.field('Kind', UI.select(['server', 'client', 'code-signing'], v.kind, 'data-pkind' + (isNew ? '' : ' disabled')), 'server: 398 days at most; client: 825; code-signing: 1185') + UI.field('Max days', UI.input(String(v.maxDays), { type: 'number', attrs: 'data-pmax' })) + UI.field('Default days', UI.input(String(v.defaultDays), { type: 'number', attrs: 'data-pdef' }))
      + UI.field('Domains', UI.input(v.policy.domains.join(', '), { placeholder: '*.northwind.local, ai.northwind.local', attrs: 'data-pdom' }), '*.domain allows every name below it') + UI.field('IP ranges (CIDR)', UI.input(v.policy.ipRanges.join(', '), { attrs: 'data-pip' })) + UI.field('Email domains', UI.input(v.policy.emailDomains.join(', '), { attrs: 'data-pmail' })) + UI.field('URI prefixes', UI.input(v.policy.uriPrefixes.join(', '), { attrs: 'data-puri' })) + '<div class="span2">' + UI.field('Key types', UI.input(v.policy.keyTypes.join(', '), { attrs: 'data-pkeys' })) + '</div></div>' + UI.toggle('Allow wildcard names (also needs dns-01 for ACME)', v.policy.allowWildcard, 'data-pwild'),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(isNew ? 'Create' : 'Save', { kind: 'primary', attrs: 'data-psave' }),
      onMount(m) { m.querySelector('[data-psave]').addEventListener('click', () => { const name = m.querySelector('[data-pname]').value.trim().toLowerCase().replace(/\s+/g, '-'); if (!name) { ctx.toast('A profile needs a name.', 'warn'); return; } if (isNew && st.profiles.some((x) => x.name === name)) { ctx.toast('409: a profile named ' + esc(name) + ' exists.', 'danger'); return; } const kind = m.querySelector('[data-pkind]').value; const cap = { server: 398, client: 825, 'code-signing': 1185 }[kind]; let maxDays = +m.querySelector('[data-pmax]').value || cap; if (maxDays > cap) { ctx.toast('422: ' + kind + ' profiles issue at most ' + cap + ' days. Set to ' + cap + '.', 'warn'); maxDays = cap; } const split = (sel) => m.querySelector(sel).value.split(',').map((s) => s.trim()).filter(Boolean); const next = { name, kind, maxDays, defaultDays: Math.min(maxDays, +m.querySelector('[data-pdef]').value || maxDays), policy: { domains: split('[data-pdom]'), ipRanges: split('[data-pip]'), emailDomains: split('[data-pmail]'), uriPrefixes: split('[data-puri]'), keyTypes: split('[data-pkeys]'), allowWildcard: m.querySelector('[data-pwild]').classList.contains('on') } }; App.closeOverlay(); if (isNew) st.profiles.push(Object.assign({ id: 'p-' + name, state: 'active', issued: 0 }, next)); else Object.assign(p, next); ctx.rerender(); ctx.toast('Profile ' + esc(name) + (isNew ? ' created (201). Audited pki.profile.created.' : ' saved. Audited pki.profile.updated.'), 'ok'); }); } });
  }
})();
