(function () {
  const { UI, esc } = App;

  // ---- example data: Northwind customer-service channels in the reviewer's workspaces ----
  const channels0 = () => [
    { id: 'ch-returns', name: 'Returns desk', kind: 'chat', workspace: 'Field Sales', label: 'public', state: 'active', reviewMode: 'escalated', target: { kind: 'profile', name: 'support-fast' }, instructions: 'Answer about returns and refunds for orders placed on the web shop. Never promise a refund amount; hand over to a person when the customer asks or when an order number is disputed.', allowAnonymous: true, messagesPerMinute: 10, sessionsPerHour: 30, retentionDays: 30, greeting: 'Hello, this is the Northwind returns desk. How can we help?', publicKey: 'chk_returns_7f3a9c1e', created: '2 Jun 2026', open: 3, escalated: 1 },
    { id: 'ch-billing', name: 'Billing questions', kind: 'email', workspace: 'Finance Ops', label: 'internal', state: 'active', reviewMode: 'always', target: { kind: 'agent', name: 'billing-helper' }, instructions: 'Explain invoices and payment terms. Every answer is reviewed before it is sent.', allowAnonymous: false, messagesPerMinute: 5, sessionsPerHour: 10, retentionDays: 90, greeting: '', publicKey: 'chk_billing_0c91d4b2', created: '14 Jul 2026', open: 4, escalated: 0, email: { address: 'billing@northwind.example', fromName: 'Northwind Billing', imap: { host: 'imap.northwind.example', port: 993, secure: true, user: 'billing@northwind.example', passwordRef: 'vault:kv/channels/billing#imap', mailbox: 'INBOX' }, smtp: { host: 'smtp.northwind.example', port: 465, secure: true, user: 'billing@northwind.example', passwordRef: 'vault:kv/channels/billing#smtp' }, mailgunKeyRef: '', uidValidity: 1719326400, lastUid: 4188, lastPoll: 'today 14:20' } },
    { id: 'ch-people', name: 'People Ops helpdesk', kind: 'chat', workspace: 'People Ops', label: 'internal', state: 'paused', reviewMode: 'never', target: { kind: 'profile', name: 'hr-assistant' }, instructions: 'Answer policy questions from the People Ops knowledge base only.', allowAnonymous: false, messagesPerMinute: 10, sessionsPerHour: 20, retentionDays: 30, greeting: 'People Ops helpdesk. Ask about leave, benefits or payroll dates.', publicKey: 'chk_people_e5d09a7c', created: '20 Aug 2026', open: 0, escalated: 0, pausedBy: 'Noor Rahimi', pausedAt: '18 Sep 17:30' },
    { id: 'ch-webshop', name: 'Old webshop chat', kind: 'chat', workspace: 'Field Sales', label: 'public', state: 'deleted', reviewMode: 'escalated', target: { kind: 'profile', name: 'support-fast' }, instructions: '', allowAnonymous: true, messagesPerMinute: 10, sessionsPerHour: 10, retentionDays: 30, greeting: '', publicKey: 'chk_webshop_2a7c9e4d', created: '1 Mar 2026', open: 0, escalated: 0, deletedAt: '30 Aug 2026' }
  ];
  const sessions0 = () => [
    { id: 's-9102', channel: 'ch-returns', state: 'open', label: 'public', customer: { kind: 'anonymous', name: 'Visitor 4f2a', email: '' }, subject: 'Return label for order 88-1042', messages: 4, last: 'today 14:31', started: 'today 14:27' },
    { id: 's-9099', channel: 'ch-returns', state: 'escalated', label: 'public', customer: { kind: 'identified', name: 'Anna Keller', email: 'anna.keller@example.com', externalId: 'cust-20911' }, subject: 'Refund not received for 88-0977', messages: 7, last: 'today 14:21', started: 'today 13:55', escalatedAt: 'today 14:18', escalation: 'The customer asked for a person' },
    { id: 's-9101', channel: 'ch-returns', state: 'open', label: 'public', customer: { kind: 'identified', name: 'Marco Ruiz', email: 'm.ruiz@example.org', externalId: 'cust-20880' }, subject: 'Damaged item, order 88-1031', messages: 5, last: 'today 14:09', started: 'today 13:58' },
    { id: 's-9087', channel: 'ch-returns', state: 'closed', label: 'public', customer: { kind: 'anonymous', name: 'Visitor 9c10', email: '' }, subject: 'Return window', messages: 3, last: '18 Sep 16:40', started: '18 Sep 16:33', closedBy: 'customer' },
    { id: 's-9080', channel: 'ch-returns', state: 'hidden', label: 'public', customer: { kind: 'anonymous', name: 'Visitor 1b77', email: '' }, subject: '(hidden by moderation)', messages: 2, last: '18 Sep 11:02', started: '18 Sep 11:00', flag: 'F-2306' },
    { id: 's-7721', channel: 'ch-billing', state: 'open', label: 'internal', customer: { kind: 'identified', name: 'Petra Novak', email: 'p.novak@contoso.example', externalId: '' }, subject: 'Invoice INV-2026-08-311: wrong VAT rate', messages: 3, last: 'today 13:40', started: 'today 09:12', via: 'email' },
    { id: 's-7719', channel: 'ch-billing', state: 'open', label: 'internal', customer: { kind: 'identified', name: 'Accounts payable, Fabrikam', email: 'ap@fabrikam.example', externalId: '' }, subject: 'Payment terms for Q4 orders', messages: 2, last: 'today 11:05', started: 'today 10:48', via: 'email' },
    { id: 's-7715', channel: 'ch-billing', state: 'open', label: 'internal', customer: { kind: 'identified', name: 'Jon Alvarez', email: 'jon@alvarez.example', externalId: '' }, subject: 'Duplicate charge on card ending 4421', messages: 4, last: '18 Sep 18:12', started: '18 Sep 15:30', via: 'email' },
    { id: 's-7702', channel: 'ch-billing', state: 'closed', label: 'internal', customer: { kind: 'identified', name: 'Lisa Chen', email: 'lisa.chen@example.net', externalId: '' }, subject: 'Copy of invoice INV-2026-07-118', messages: 2, last: '12 Sep 09:40', started: '12 Sep 09:02', via: 'email', closedBy: 'Mara Okafor' }
  ];
  const transcripts0 = {
    's-9099': [
      { seq: 1, role: 'notice', state: 'delivered', via: 'chat', text: 'Hello, this is the Northwind returns desk. How can we help?', at: '13:55' },
      { seq: 2, role: 'customer', state: 'delivered', via: 'chat', text: 'I returned order 88-0977 three weeks ago and still have no refund.', at: '13:56' },
      { seq: 3, role: 'assistant', state: 'delivered', via: 'chat', text: 'Thank you. The return for 88-0977 was received on 1 September and marked as inspected. Refunds are issued within 14 days of inspection, so this one is late. I can ask a colleague to look at it.', at: '13:56' },
      { seq: 4, role: 'customer', state: 'delivered', via: 'chat', text: 'Yes please. I want to talk to a person.', at: '14:17' },
      { seq: 5, role: 'notice', state: 'delivered', via: 'chat', text: 'A person will follow up in this conversation.', at: '14:18' },
      { seq: 6, role: 'customer', state: 'delivered', via: 'chat', text: 'Also, how much will I get back? I paid 149 EUR.', at: '14:20' },
      { seq: 7, role: 'assistant', state: 'held', via: 'chat', text: 'You will receive the full 149 EUR plus the 4.90 EUR shipping within 3 working days.', flag: 'F-2305', at: '14:21' }
    ],
    's-9101': [
      { seq: 1, role: 'notice', state: 'delivered', via: 'chat', text: 'Hello, this is the Northwind returns desk. How can we help?', at: '13:58' },
      { seq: 2, role: 'customer', state: 'delivered', via: 'chat', text: 'The jacket from order 88-1031 arrived with a torn sleeve.', at: '13:59' },
      { seq: 3, role: 'assistant', state: 'delivered', via: 'chat', text: 'Sorry about that. You can return it free of charge; I can send a prepaid label to the address on the order.', at: '13:59' },
      { seq: 4, role: 'customer', state: 'delivered', via: 'chat', text: 'Please do. My IBAN for the refund is DE89 3704 0044 0532 0130 00.', at: '14:08' },
      { seq: 5, role: 'assistant', state: 'held', via: 'chat', text: 'Noted, the refund goes to DE89 3704 0044 0532 0130 00 once the jacket is back.', flag: 'F-2307', at: '14:09' }
    ],
    's-9102': [
      { seq: 1, role: 'notice', state: 'delivered', via: 'chat', text: 'Hello, this is the Northwind returns desk. How can we help?', at: '14:27' },
      { seq: 2, role: 'customer', state: 'delivered', via: 'chat', text: 'I need a return label for order 88-1042.', at: '14:28' },
      { seq: 3, role: 'assistant', state: 'delivered', via: 'chat', text: 'I have sent a prepaid label to the email on the order. Drop the parcel at any post office within 14 days.', at: '14:28' },
      { seq: 4, role: 'customer', state: 'delivered', via: 'chat', text: 'Thanks.', at: '14:31' }
    ],
    's-7721': [
      { seq: 1, role: 'customer', state: 'delivered', via: 'email', text: 'Invoice INV-2026-08-311 applies 19% VAT but we are registered in Austria. Please correct it.', at: '09:12' },
      { seq: 2, role: 'assistant', state: 'rejected', via: 'email', text: 'The invoice is correct as issued.', at: '09:40', rejectedBy: 'Jonas Lindqvist', reason: 'Wrong: reverse charge applies' },
      { seq: 3, role: 'agent', state: 'delivered', via: 'email', text: 'Thank you for flagging this. Reverse charge applies to your Austrian VAT id; a corrected invoice follows today.', at: '13:40', author: 'Jonas Lindqvist' }
    ],
    's-7719': [
      { seq: 1, role: 'customer', state: 'delivered', via: 'email', text: 'What payment terms apply to orders placed in Q4?', at: '10:48' },
      { seq: 2, role: 'assistant', state: 'held', via: 'email', text: 'Orders placed from 1 October are on 30 days net; early payment within 10 days earns a 2% discount.', flag: 'F-2311', at: '11:05' }
    ]
  };
  const held0 = () => [
    { id: 'hr-1', channel: 'ch-returns', session: 's-9099', seq: 7, flag: 'F-2305', checkpoint: 'channel-review', since: 'today 14:21', left: 14, of: 30, customer: 'Anna Keller', text: 'You will receive the full 149 EUR plus the 4.90 EUR shipping within 3 working days.', why: 'Review mode escalated: the session was escalated, so every answer waits for a reviewer.' },
    { id: 'hr-2', channel: 'ch-returns', session: 's-9101', seq: 5, flag: 'F-2307', checkpoint: 'model-output', since: 'today 14:09', left: 2, of: 30, customer: 'Marco Ruiz', text: 'Noted, the refund goes to DE89 3704 0044 0532 0130 00 once the jacket is back.', why: 'Guardrail PII-IBAN (require-approval) at model-output: the answer repeats an IBAN.' },
    { id: 'hr-3', channel: 'ch-billing', session: 's-7719', seq: 2, flag: 'F-2311', checkpoint: 'channel-review', since: 'today 11:05', left: 160, of: 240, customer: 'Accounts payable, Fabrikam', text: 'Orders placed from 1 October are on 30 days net; early payment within 10 days earns a 2% discount.', why: 'Review mode always: every answer on this channel waits for a reviewer.' }
  ];
  const outbox0 = () => [
    { id: 'ob-512', session: 's-7721', to: 'p.novak@contoso.example', subject: 'Re: Invoice INV-2026-08-311: wrong VAT rate', state: 'sent', attempts: 1, at: 'today 13:40', messageId: '<ob-512@northwind.example>' },
    { id: 'ob-509', session: 's-7715', to: 'jon@alvarez.example', subject: 'Re: Duplicate charge on card ending 4421', state: 'failed', attempts: 5, at: '18 Sep 19:02', error: '451 4.7.1 greylisted, try again later (five attempts)', messageId: '<ob-509@northwind.example>' },
    { id: 'ob-503', session: 's-7702', to: 'lisa.chen@example.net', subject: 'Re: Copy of invoice INV-2026-07-118', state: 'bounced', attempts: 1, at: '12 Sep 09:41', messageId: '<ob-503@northwind.example>' },
    { id: 'ob-514', session: 's-7719', to: 'ap@fabrikam.example', subject: 'Re: Payment terms for Q4 orders', state: 'queued', attempts: 0, at: 'waiting for review', messageId: '' }
  ];
  const bounces0 = () => [
    { id: 'b-31', outbox: 'ob-503', kind: 'hard', status: '550 5.1.1', reason: 'User unknown', source: 'imap', at: '12 Sep 09:43' },
    { id: 'b-30', outbox: 'ob-498', kind: 'complaint', status: '', reason: 'Marked as spam by the recipient', source: 'mailgun', at: '9 Sep 08:15' },
    { id: 'b-29', outbox: 'ob-491', kind: 'soft', status: '452 4.2.2', reason: 'Mailbox full', source: 'generic', at: '5 Sep 17:20' }
  ];
  const exports0 = () => [
    { id: 'job-5e21a0', channel: 'ch-billing', from: '1 Aug 2026', to: '31 Aug 2026', sessions: 212, state: 'finished', by: 'Jonas Lindqvist', at: '2 Sep 08:10', size: '1.8 MB' },
    { id: 'job-5f3b77', channel: 'ch-returns', from: '1 Sep 2026', to: '19 Sep 2026', sessions: 388, state: 'running', by: 'Mara Okafor', at: 'today 14:00', size: '' }
  ];

  const small = (t) => '<span class="muted" style="font-size:12px">' + t + '</span>';
  const statePill = (s) => UI.pill(s, s === 'open' ? 'ok' : s === 'escalated' ? 'warn' : s === 'hidden' ? 'danger' : s === 'paused' ? 'warn' : s === 'deleted' ? 'danger' : s === 'active' ? 'ok' : '');
  const timeText = (left) => left < 0 ? 'overdue ' + (-left) + ' min' : left >= 120 ? Math.round(left / 60) + ' h left' : left + ' min left';
  const secret = (p) => p + '_' + Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }

  App.register({
    id: 'channels', title: 'Channels', section: 'admin', crumb: ['Admin', 'Channels'],
    summary: 'Customer-service channels: sessions and transcripts, held replies with approve, edit and reject, email threads, retention, exports',
    label: (st) => { const c = (st.channels || []).find((x) => x.id === st.sel); return c ? c.label : null; },
    commands: [{ label: 'Decide the next held reply', sub: 'Channels', run(app) { const s = app.stateFor('channels'); s.tab = 'held'; app.render(); } }, { label: 'Create a channel', sub: 'Channels', run(app) { app.stateFor('channels').openNew = true; app.render(); } }],
    states: [
      { title: 'Edited held reply reaches the customer as edited', tone: 'ok', text: 'Edit delivers the reviewer\'s text; the model\'s text is kept as original on the message and the flag records the decision.', apply(ctx) { const st = ctx.state; st.sel = 'ch-returns'; const h = st.held.find((x) => x.id === 'hr-1'); if (h) decideHeld(ctx, h, 'edit', 'The refund for 88-0977 is being processed by a colleague now. The amount is confirmed by email within 3 working days; shipping of 4.90 EUR is refunded only when the item was faulty.', null, true); st.tab = 'sessions'; st.sessionSel = 's-9099'; ctx.rerender(); } },
      { title: 'Session escalated', tone: 'warn', text: 'The customer asked for a person: the session escalates, reviewers holding channels:review in the workspace are notified, and every further answer waits.', apply(ctx) { const st = ctx.state; st.sel = 'ch-returns'; st.tab = 'sessions'; st.sessionSel = 's-9099'; st.escalationNote = true; ctx.rerender(); ctx.toast('s-9099 escalated: the customer asked for a person. Field Sales reviewers notified.', 'warn', 5000); } },
      { title: 'Channel paused refuses new sessions', tone: 'info', text: 'A paused channel answers 404 to new public sessions and ends customer tokens until it is active again; open sessions wait.', apply(ctx) { const st = ctx.state; st.sel = 'ch-people'; st.tab = 'settings'; ctx.rerender(); } },
      { title: 'Mail failed after five attempts', tone: 'danger', text: 'The channels.send job tries five times; then the outbox row is failed and channel.mail.failed is audited. A person can answer again.', apply(ctx) { const st = ctx.state; st.sel = 'ch-billing'; st.tab = 'email'; st.mailFailedNote = true; ctx.rerender(); } },
      { title: 'Vault reference not readable', tone: 'danger', text: 'IMAP and SMTP passwords are vault: references, read as the saver at every connection. When the saver loses the policy the poll fails with 403 and the mailbox stops being read.', apply(ctx) { const st = ctx.state; st.sel = 'ch-billing'; st.tab = 'settings'; st.vaultProblem = true; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      if (!st.channels) { st.channels = channels0(); st.sessions = sessions0(); st.transcripts = JSON.parse(JSON.stringify(transcripts0)); st.held = held0(); st.outbox = outbox0(); st.bounces = bounces0(); st.exports = exports0(); }
      st.tab = st.tab || 'sessions'; st.query = st.query || ''; st.fkind = st.fkind || 'all'; st.fstate = st.fstate || 'live'; st.sstate = st.sstate || 'all'; st.ssort = st.ssort || 'activity';
      if (ctx.params.channel) { st.sel = ctx.params.channel; delete ctx.params.channel; }
      if (ctx.params.session) { const s = st.sessions.find((x) => x.id === ctx.params.session); if (s) { st.sel = s.channel; st.tab = 'sessions'; st.sessionSel = s.id; } delete ctx.params.session; }
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }

      const list = st.channels.filter((c) => (!st.query || c.name.toLowerCase().includes(st.query.toLowerCase())) && (st.fkind === 'all' || c.kind === st.fkind) && (st.fstate === 'all' || (st.fstate === 'live' ? c.state !== 'deleted' : c.state === st.fstate)));
      if (!st.sel || !st.channels.some((c) => c.id === st.sel)) st.sel = list.length ? list[0].id : st.channels[0].id;
      const c = st.channels.find((x) => x.id === st.sel);
      const heldFor = (id) => st.held.filter((h) => h.channel === id);
      const left = '<div class="leftpane w320"><div class="hstack"><div class="eyebrow grow">Channels</div>' + (st.held.length ? UI.pill(st.held.length + ' held', 'warn') : '') + '</div>'
        + UI.search('Search channels', 'data-search', st.query)
        + '<div class="hstack gap6 wrap"><span class="relative">' + UI.btn(st.fkind === 'all' ? 'Kind' : st.fkind, { size: 'xs', icon: 'filter', attrs: 'data-fkind', cls: st.fkind === 'all' ? '' : 'active' }) + '</span><span class="relative">' + UI.btn({ live: 'Active and paused', all: 'Any state', active: 'Active', paused: 'Paused', deleted: 'Deleted' }[st.fstate], { size: 'xs', icon: 'filter', attrs: 'data-fstate', cls: st.fstate === 'live' ? '' : 'active' }) + '</span></div>'
        + '<div class="vstack" style="gap:2px">' + list.map((x) => UI.listItem(esc(x.name) + ' ' + UI.pill(x.kind, 'outline'), esc(x.workspace) + ', review ' + esc(x.reviewMode) + (x.state === 'active' ? ', ' + x.open + ' open' : ', ' + x.state), { active: x.id === st.sel, attrs: 'data-channel="' + x.id + '"', right: heldFor(x.id).length ? UI.pill(heldFor(x.id).length + ' held', 'warn') : UI.label(x.label, { sm: true }) })).join('') + (list.length ? '' : UI.empty('No channels match', 'Clear the filters.')) + '</div>'
        + '<div style="margin-top:auto">' + UI.btn('New channel', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newchannel' }) + '</div></div>';

      const chSessions = st.sessions.filter((s) => s.channel === c.id);
      const tabs = UI.tabs([{ id: 'sessions', label: 'Sessions', count: chSessions.filter((s) => s.state === 'open' || s.state === 'escalated').length }, { id: 'held', label: 'Held replies', count: heldFor(c.id).length }, { id: 'settings', label: 'Settings' }].concat(c.kind === 'email' ? [{ id: 'email', label: 'Email' }] : []).concat([{ id: 'exports', label: 'Exports', count: st.exports.filter((e) => e.channel === c.id).length }]), st.tab);
      const head = UI.pagehead(c.name, UI.pill(c.kind, 'outline') + ' · ' + esc(c.workspace) + ' · answers with ' + esc(c.target.kind) + ' <a href="#" data-gotarget>' + esc(c.target.name) + '</a> · review mode ' + esc(c.reviewMode) + ' · retention ' + (c.retentionDays ? c.retentionDays + ' days' : 'keep') + ' · created ' + esc(c.created), statePill(c.state) + UI.label(c.label));
      let body = '';

      if (c.state === 'deleted') {
        body = UI.notice('<b>Deleted on ' + esc(c.deletedAt) + '.</b> Its open sessions were closed and customer tokens stopped working. Transcripts stay until the retention purge; exports remain downloadable.', 'warn');
      } else if (st.tab === 'sessions') {
        let rows = chSessions.filter((s) => st.sstate === 'all' || s.state === st.sstate);
        rows = rows.slice().sort((a, b) => st.ssort === 'started' ? b.started.localeCompare(a.started) : st.ssort === 'escalated' ? ((b.state === 'escalated') - (a.state === 'escalated')) || b.last.localeCompare(a.last) : b.last.localeCompare(a.last));
        if (st.sessionSel && !chSessions.some((s) => s.id === st.sessionSel)) st.sessionSel = null;
        const s = st.sessions.find((x) => x.id === st.sessionSel) || null;
        body = (c.state === 'paused' ? UI.notice('<b>Paused.</b> New sessions are refused (404) and customer tokens have stopped working until the channel is active again. Open sessions are kept.', 'warn', UI.btn('Resume', { size: 'sm', attrs: 'data-resume' })) : '')
          + UI.panel('Sessions', '<div class="toolbar">' + UI.seg([{ id: 'all', label: 'All' }, { id: 'open', label: 'Open' }, { id: 'escalated', label: 'Escalated' }, { id: 'closed', label: 'Closed' }, { id: 'hidden', label: 'Hidden' }], st.sstate, 'data-sstate') + '<span class="relative">' + UI.btn({ activity: 'Newest activity', started: 'Newest first', escalated: 'Escalated first' }[st.ssort], { size: 'sm', icon: 'sort', attrs: 'data-ssort' }) + '</span>' + small(rows.length + ' of ' + chSessions.length + ' sessions; within your workspaces and clearance only') + '</div>'
            + UI.table(['Session', 'State', 'Customer', 'Subject', { label: 'Messages', right: true }, 'Started', 'Last activity'], rows.map((x) => ({ cells: ['<span class="mono">' + esc(x.id) + '</span>', statePill(x.state) + (x.state === 'escalated' ? '<br>' + small(esc(x.escalation)) : ''), x.customer.kind === 'anonymous' ? esc(x.customer.name) + ' ' + UI.pill('anonymous', 'outline') : esc(x.customer.name) + '<br>' + small(esc(x.customer.email)), esc(x.subject), '<span class="num">' + x.messages + '</span>' + (st.held.some((h) => h.session === x.id) ? ' ' + UI.pill('held', 'warn') : ''), esc(x.started), esc(x.last)], attrs: 'data-session="' + x.id + '"', selected: x.id === st.sessionSel })), { minWidth: '820px', emptyTitle: 'No sessions', emptyText: 'Nothing in this state.' }))
          + (s ? transcriptPanel(st, c, s) : small('Pick a session to read its transcript, answer as a person, close it or export it.'));
      } else if (st.tab === 'held') {
        const hs = heldFor(c.id).slice().sort((a, b) => a.since.localeCompare(b.since));
        body = UI.notice('<b>Held replies wait in the workspace flag queue too.</b> Flags can approve or reject them (flags:review); editing the text before it goes out needs this screen. The customer sees <span class="mono">state: pending</span> until you decide. Approve delivers the reply as written; edit delivers your text and keeps the model\'s as original; reject withdraws it and tells the customer a person will follow up.', 'info', UI.btn('Open Flags', { kind: 'ghost', size: 'sm', attrs: 'data-goflags' }))
          + (hs.length ? hs.map((h) => '<div class="panel channels-held"><div class="hstack wrap"><span class="mono">' + esc(h.flag) + '</span>' + UI.pill(h.checkpoint, h.checkpoint === 'model-output' ? 'danger' : 'info') + '<span class="fg2">session <a href="#" data-opensession="' + esc(h.session) + '">' + esc(h.session) + '</a>, ' + esc(h.customer) + '</span><span class="grow"></span>' + (h.left < 0 ? '<span style="color:var(--danger-fg)">' + esc(timeText(h.left)) + '</span>' : small(esc(timeText(h.left)) + ' of ' + h.of + ' min')) + '</div>'
            + '<div class="channels-reply serif">' + esc(h.text) + '</div>' + small(esc(h.why))
            + '<div class="hstack wrap gap6" style="margin-top:8px">' + UI.btn('Approve', { kind: 'primary', size: 'sm', attrs: 'data-held="approve" data-id="' + h.id + '"' }) + UI.btn('Edit and send', { size: 'sm', icon: 'edit', attrs: 'data-held="edit" data-id="' + h.id + '"' }) + UI.btn('Reject', { kind: 'danger', size: 'sm', attrs: 'data-held="reject" data-id="' + h.id + '"' }) + UI.btn('Open flag', { kind: 'ghost', size: 'sm', attrs: 'data-openflag="' + h.flag + '"' }) + '</div></div>').join('') : UI.empty('Nothing held', 'Replies waiting for review on ' + c.name + ' appear here, oldest first.'))
          + (st.heldDone ? UI.notice(st.heldDone, 'ok', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearhelddone' })) : '');
      } else if (st.tab === 'settings') {
        body = (c.state === 'paused' ? UI.notice('<b>Paused by ' + esc(c.pausedBy) + ', ' + esc(c.pausedAt) + '.</b> New sessions are refused with 404 and customer tokens have stopped working; open sessions and held replies are kept until it is active again.', 'warn', UI.btn('Resume', { size: 'sm', kind: 'primary', attrs: 'data-resume' })) : '')
          + (st.vaultProblem && c.id === 'ch-billing' ? UI.problem('Vault reference not readable', 'The IMAP poll at 14:20 failed: vault:kv/channels/billing#imap is read as Jonas Lindqvist, who saved it, and his vault policy no longer allows read on kv/channels (403, step vault-policy, audited as vault.denied). The mailbox is not being read. Save the reference again as yourself, or restore his grant in Vault.', '5a9c3e1b7d2f4a6c8e0b2d4f6a8c0e2b') : '')
          + UI.panel('Channel', '<div class="formgrid" style="--cols:3">' + UI.field('Name', UI.input(c.name, { attrs: 'data-cname' })) + UI.field('Label', UI.select(['public', 'internal', 'confidential'], c.label, 'data-clabel'), 'Under the workspace ceiling, your clearance and the target\'s label; a pool below it is never leased') + UI.field('Review mode', UI.select([{ value: 'never', label: 'never: answers go straight out unless a guardrail holds them' }, { value: 'escalated', label: 'escalated: once escalated, every answer waits' }, { value: 'always', label: 'always: every answer waits' }], c.reviewMode, 'data-creview')) + UI.field('Target', UI.select(['profile support-fast', 'profile hr-assistant', 'agent billing-helper', 'agent returns-agent (restricted)'], c.target.kind + ' ' + c.target.name, 'data-ctarget'), 'Customer channels never run an agent\'s tools; 422 step target when it cannot answer at the label') + UI.field('Messages per minute', UI.input(String(c.messagesPerMinute), { type: 'number', attrs: 'data-cmpm' })) + UI.field('Sessions per hour', UI.input(String(c.sessionsPerHour), { type: 'number', attrs: 'data-csph' })) + UI.field('Retention (days)', UI.input(c.retentionDays == null ? '' : String(c.retentionDays), { type: 'number', attrs: 'data-cret', placeholder: 'empty keeps sessions' }), 'Sessions idle longer are purged with their messages, threads and outbox rows') + '</div>'
            + UI.field('Instructions', UI.textarea(c.instructions, { rows: 3, attrs: 'data-cinstr' })) + (c.kind === 'chat' ? UI.field('Greeting', UI.input(c.greeting, { attrs: 'data-cgreet' })) : '') + UI.toggle('Allow anonymous customers', c.allowAnonymous, 'data-canon')
            + '<div class="hstack wrap gap6" style="margin-top:8px">' + UI.btn('Save', { kind: 'primary', size: 'sm', attrs: 'data-savechannel' }) + (c.state === 'active' ? UI.btn('Pause', { size: 'sm', icon: 'pause', attrs: 'data-pause' }) : UI.btn('Resume', { size: 'sm', icon: 'play', attrs: 'data-resume' })) + UI.btn('Run retention purge now', { size: 'sm', attrs: 'data-purge' }) + (c.kind === 'email' ? UI.btn('Poll mailbox now', { size: 'sm', icon: 'refresh', attrs: 'data-poll' }) : '') + UI.btn('Delete channel', { kind: 'danger', size: 'sm', attrs: 'data-delete' }) + '</div>')
          + UI.panel('Keys and secrets', UI.kv([['Public key', '<span class="mono">' + esc(c.publicKey) + '</span> ' + small('the site passes it to start a session')], ['Identity secret', small('stored hashed; signs the site\'s customer identity assertions') + '<br>' + UI.btn('Rotate', { size: 'xs', attrs: 'data-rotate="identity"' })], ['Webhook secret', c.kind === 'email' ? small('stored hashed; signs generic inbound mail webhooks') + '<br>' + UI.btn('Rotate', { size: 'xs', attrs: 'data-rotate="webhook"' }) : small('chat channels have none')], ['Public endpoints', '<span class="mono" style="font-size:12px">POST /api/public/channels/sessions</span>' + (c.kind === 'email' ? '<br><span class="mono" style="font-size:12px">POST /api/public/channels/' + esc(c.publicKey) + '/email/generic</span><br><span class="mono" style="font-size:12px">POST /api/public/channels/' + esc(c.publicKey) + '/email/mailgun</span>' : '')]], 2)
            + (st.rotated && st.rotated.channel === c.id ? UI.notice('<b>New ' + esc(st.rotated.which) + ' secret. Copy it now; it is shown once.</b> The old one stopped working at once.<div class="mono" style="margin-top:4px;overflow-wrap:anywhere">' + esc(st.rotated.value) + '</div>', 'warn', UI.btn('Copy', { size: 'sm', attrs: 'data-copy="' + esc(st.rotated.value) + '"' }) + UI.btn('Done', { kind: 'ghost', size: 'sm', attrs: 'data-rotatedone' })) : ''))
          + (c.kind === 'email' ? UI.panel('Mail settings', '<div class="formgrid" style="--cols:3">' + UI.field('Address', UI.input(c.email.address, { attrs: 'data-eaddr' })) + UI.field('From name', UI.input(c.email.fromName, { attrs: 'data-efrom' })) + UI.field('Mailgun signing key', UI.input(c.email.mailgunKeyRef, { attrs: 'data-emg', placeholder: 'vault:kv/channels/billing#mailgun' }), 'Without it the Mailgun endpoint is 404') + UI.field('IMAP host', UI.input(c.email.imap.host + ':' + c.email.imap.port, { attrs: 'data-eimap' })) + UI.field('IMAP user', UI.input(c.email.imap.user, { attrs: 'data-eimapuser' })) + UI.field('IMAP password', UI.input(c.email.imap.passwordRef, { attrs: 'data-eimappw' }), 'A vault: reference only; a literal password is 400') + UI.field('SMTP host', UI.input(c.email.smtp.host + ':' + c.email.smtp.port, { attrs: 'data-esmtp' })) + UI.field('SMTP user', UI.input(c.email.smtp.user, { attrs: 'data-esmtpuser' })) + UI.field('SMTP password', UI.input(c.email.smtp.passwordRef, { attrs: 'data-esmtppw' }), 'Read as the saver at every connection (<a href="#" data-govault>Vault</a>)') + '</div>' + UI.toggle('Implicit TLS (otherwise STARTTLS is required)', c.email.imap.secure, 'data-etls') + '<div class="hstack gap6" style="margin-top:8px">' + UI.btn('Save mail settings', { kind: 'primary', size: 'sm', attrs: 'data-savemail' }) + small('Hosts pass the service address rules and the tenant\'s allowed hosts at every connection.') + '</div>') : '');
      } else if (st.tab === 'email') {
        const ob = st.outbox.filter((o) => chSessions.some((s) => s.id === o.session));
        body = (st.mailFailedNote ? UI.notice('<b>ob-509 failed after five attempts</b> (451 greylisted): channel.mail.failed audited; the customer has not received the answer. Answer again from the session, or fix the SMTP route and resend.', 'danger', UI.btn('Resend', { size: 'sm', attrs: 'data-resend="ob-509"' }) + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearmail' })) : '')
          + '<div class="grid3">' + UI.stat(String(ob.filter((o) => o.state === 'queued').length), 'queued', small('wait for review or the next send job')) + UI.stat(String(ob.filter((o) => o.state === 'failed').length), 'failed', small('five attempts, then channel.mail.failed')) + UI.stat(String(st.bounces.length), 'bounces recorded', small('DSN by IMAP, generic and Mailgun events')) + '</div>'
          + UI.panel('Outbox', UI.table(['Row', 'Session', 'To', 'Subject', 'State', { label: 'Attempts', right: true }, 'When', ''], ob.map((o) => ['<span class="mono">' + esc(o.id) + '</span>', '<a href="#" data-opensession="' + esc(o.session) + '">' + esc(o.session) + '</a>', esc(o.to), esc(o.subject), UI.pill(o.state, o.state === 'sent' ? 'ok' : o.state === 'failed' || o.state === 'bounced' ? 'danger' : 'info') + (o.error ? '<br>' + small(esc(o.error)) : ''), '<span class="num">' + o.attempts + '</span>', esc(o.at), o.state === 'failed' ? UI.btn('Resend', { size: 'xs', attrs: 'data-resend="' + o.id + '"' }) : '']), { clickable: false, minWidth: '900px' }) + small('Sent from ' + esc(c.email.address) + ' with In-Reply-To and References threading and Auto-Submitted: auto-replied on model-written answers. A reply joins a session only when its In-Reply-To or References name one of that session\'s Message-IDs and it comes from the session\'s customer address.'))
          + '<div class="cols">' + UI.panel('Bounces', UI.table(['Kind', 'Outbox row', 'Status', 'Reason', 'Source', 'When'], st.bounces.map((b) => [UI.pill(b.kind, b.kind === 'hard' || b.kind === 'complaint' ? 'danger' : 'warn'), '<span class="mono">' + esc(b.outbox) + '</span>', '<span class="mono">' + esc(b.status) + '</span>', esc(b.reason), UI.pill(b.source, 'outline'), esc(b.at)]), { clickable: false, minWidth: '0' }), { cls: 'grow' })
          + UI.panel('IMAP cursor', UI.kv([['Mailbox', '<span class="mono">' + esc(c.email.imap.mailbox) + '</span> on ' + esc(c.email.imap.host)], ['UIDVALIDITY', '<span class="mono">' + c.email.uidValidity + '</span>'], ['Last UID seen', '<span class="mono">' + c.email.lastUid + '</span>'], ['Last poll', esc(c.email.lastPoll) + (st.polled ? ' ' + UI.pill('job queued', 'info') : '')], ['Ignored', 'auto-submitted, bulk and list mail, mailer daemons, mail from the channel\'s own address; messages over 10 MB']], 1) + '<div style="margin-top:8px">' + UI.btn('Poll now', { size: 'sm', icon: 'refresh', attrs: 'data-poll' }) + '</div>', { cls: 'w360' }) + '</div>';
      } else if (st.tab === 'exports') {
        const ex = st.exports.filter((e) => e.channel === c.id);
        body = UI.panel('Export sessions as CSV', '<div class="formgrid" style="--cols:3">' + UI.field('From', UI.input('2026-09-01', { type: 'date', attrs: 'data-xfrom' })) + UI.field('To', UI.input('2026-09-19', { type: 'date', attrs: 'data-xto' })) + '<div class="field"><label>&nbsp;</label>' + UI.btn('Start export', { kind: 'primary', attrs: 'data-export' }) + '</div></div>' + small('Every session created in the window (at most 10,000, those within your clearance) as one CSV, built by a channels.export job and sealed in the blob store. Columns: channel, session, seq, time, role, state, via, label, text, original; a leading = + - @ is made inert. Downloading is audited as channel.transcript.exported.'))
          + UI.panel('Exports', UI.table(['Job', 'Window', { label: 'Sessions', right: true }, 'State', 'Requested by', 'When', 'Size', ''], ex.map((e) => ['<span class="mono">' + esc(e.id) + '</span>', esc(e.from) + ' to ' + esc(e.to), '<span class="num">' + e.sessions + '</span>', UI.pill(e.state, e.state === 'finished' ? 'ok' : 'info'), esc(e.by), esc(e.at), esc(e.size), e.state === 'finished' && e.by === 'Mara Okafor' ? UI.btn('Download', { size: 'xs', icon: 'download', attrs: 'data-download="' + e.id + '"' }) : e.state === 'finished' ? small('only the requester') : small('running')]), { clickable: false, minWidth: '0', emptyTitle: 'No exports', emptyText: 'Start one above.' }));
      }

      root.innerHTML = '<style>'
        + '#main > .page > *{flex-shrink:0}'
        + '#main .channels-held .hstack{gap:8px}#main .channels-reply{font-size:15px;line-height:1.5;padding:8px 10px;background:var(--panel2);border-radius:6px;margin:6px 0 4px}'
        + '#main .channels-msg{display:flex;gap:10px;padding:8px 10px;border-radius:6px}#main .channels-msg.customer{background:var(--panel2)}#main .channels-msg.assistant,#main .channels-msg.agent{background:var(--accent-tint)}#main .channels-msg.notice{color:var(--muted);font-size:12px;justify-content:center}'
        + '#main .channels-msg .who{min-width:84px;font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}#main .channels-msg .body{flex:1;font-size:14px;line-height:1.5}'
        + '#main .channels-msg.held{outline:1px dashed var(--warn-fg)}#main .channels-msg.rejected .body,#main .channels-msg.hidden .body{color:var(--muted);text-decoration:line-through}'
        + '#main .channels-orig{font-size:12px;color:var(--muted);margin-top:4px;padding-left:8px;border-left:2px solid var(--line)}'
        + '#main .dt td > .mono:first-child{white-space:nowrap}'
        + '</style>'
        + left + '<div class="page">' + head + tabs + body
        + '<div style="margin-top:auto"><div class="eyebrow" style="margin-bottom:8px">States to design from this page</div>' + UI.states(this.states) + '</div></div>';

      // ---- events ----
      ctx.on('click', '.state-card', (e, t) => ctx.app.applyState(+t.dataset.state));
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('input', '[data-search]', (e, t) => { st.query = t.value; const v = t.value; ctx.rerender(); const i = ctx.$('[data-search]'); if (i) { i.focus(); i.value = v; } });
      ctx.on('click', '[data-fkind]', (e, t) => menu(ctx, t, [['all', 'Any kind'], ['chat', 'Chat'], ['email', 'Email']], st.fkind, (v) => { st.fkind = v; ctx.rerender(); }));
      ctx.on('click', '[data-fstate]', (e, t) => menu(ctx, t, [['live', 'Active and paused'], ['active', 'Active'], ['paused', 'Paused'], ['deleted', 'Deleted'], ['all', 'Any state']], st.fstate, (v) => { st.fstate = v; ctx.rerender(); }));
      ctx.on('click', '[data-channel]', (e, t) => { st.sel = t.dataset.channel; st.sessionSel = null; st.vaultProblem = false; if (st.tab === 'email' && st.channels.find((x) => x.id === st.sel).kind !== 'email') st.tab = 'sessions'; ctx.rerender(); });
      ctx.on('click', '[data-gotarget]', (e) => { e.preventDefault(); ctx.navigate(c.target.kind === 'profile' ? 'profiles' : 'runs', c.target.kind === 'profile' ? { profile: c.target.name } : {}); });
      ctx.on('click', '[data-goflags]', () => ctx.navigate('flags'));
      ctx.on('click', '[data-openflag]', (e, t) => { e.preventDefault(); ctx.navigate('flags', { id: t.dataset.openflag }); });
      ctx.on('click', '[data-govault]', (e) => { e.preventDefault(); ctx.navigate('vault', { path: 'kv/channels/billing' }); });
      ctx.on('click', '[data-goaudit]', (e) => { e.preventDefault(); ctx.navigate('usage-audit'); });
      ctx.on('click', '[data-copy]', (e, t) => ctx.toast('Copied to the clipboard.'));
      // sessions
      ctx.on('click', '[data-sstate] [data-seg]', (e, t) => { st.sstate = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-ssort]', (e, t) => menu(ctx, t, [['activity', 'Newest activity'], ['started', 'Newest first'], ['escalated', 'Escalated first']], st.ssort, (v) => { st.ssort = v; ctx.rerender(); }));
      ctx.on('click', 'tr[data-session]', (e, t) => { st.sessionSel = t.dataset.session; st.escalationNote = false; ctx.rerender(); });
      ctx.on('click', '[data-opensession]', (e, t) => { e.preventDefault(); const s = st.sessions.find((x) => x.id === t.dataset.opensession); st.sel = s.channel; st.tab = 'sessions'; st.sessionSel = s.id; st.sstate = 'all'; ctx.rerender(); });
      ctx.on('input', '[data-replydraft]', (e, t) => { st.replyDraft = t.value; });
      ctx.on('click', '[data-reply]', () => { const s = st.sessions.find((x) => x.id === st.sessionSel); const text = (st.replyDraft || '').trim(); if (!text) { ctx.toast('Write the answer first.', 'warn'); return; } const tr = st.transcripts[s.id] || (st.transcripts[s.id] = []); tr.push({ seq: tr.length + 1, role: 'agent', state: 'delivered', via: s.via || 'chat', text, at: 'now', author: 'Mara Okafor' }); s.messages += 1; s.last = 'just now'; if (s.via === 'email') st.outbox.unshift({ id: 'ob-' + (515 + st.outbox.length), session: s.id, to: s.customer.email, subject: 'Re: ' + s.subject, state: 'queued', attempts: 0, at: 'just now', messageId: '' }); st.replyDraft = ''; ctx.rerender(); ctx.toast('Answered as a person (role agent)' + (s.via === 'email' ? '; queued in the outbox.' : '; delivered at once.'), 'ok'); });
      ctx.on('click', '[data-closesession]', async () => { const s = st.sessions.find((x) => x.id === st.sessionSel); const ok = await ctx.confirm({ title: 'Close ' + s.id, tone: 'info', body: '<p style="margin:0" class="fg2">The customer\'s token stops working. ' + (s.via === 'email' ? 'A reply from the customer reopens the session.' : 'An identified customer who comes back starts a new session.') + ' Event channel.session.closed.</p>', kv: [['Customer', s.customer.name], ['Messages', String(s.messages)]], ok: 'Close session' }); if (!ok) return; s.state = 'closed'; s.closedBy = 'Mara Okafor'; st.held = st.held.filter((h) => h.session !== s.id); c.open = Math.max(0, c.open - 1); ctx.rerender(); ctx.toast(esc(s.id) + ' closed.', ''); });
      ctx.on('click', '[data-exportcsv]', () => { const s = st.sessions.find((x) => x.id === st.sessionSel); ctx.toast('Downloading ' + esc(s.id) + '.csv (' + s.messages + ' rows). Audited as channel.transcript.exported.', 'ok'); });
      ctx.on('click', '[data-reportmsg]', (e, t) => { const s = st.sessions.find((x) => x.id === st.sessionSel); const seq = +t.dataset.reportmsg; ctx.modal({ title: 'Report message ' + seq + ' of ' + esc(s.id), body: UI.field('Reason', UI.select(['Abuse', 'Sensitive data', 'Spam', 'Other'], 'Abuse')) + UI.field('Note', UI.textarea('', { rows: 2 })) + UI.notice('Files a report flag (type channel-message) in ' + esc(c.workspace) + '\'s queue. Hiding a channel message removes it from what the customer and the model see; hiding a session ends the customer\'s token.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Report', { kind: 'primary', attrs: 'data-doreport' }), onMount(m) { m.querySelector('[data-doreport]').addEventListener('click', () => { App.closeOverlay(); ctx.toast('Reported as F-2312 in the Customer channels queue. <a href="#/moderation" style="color:inherit">Open Moderation</a>', 'ok', 5000); }); } }); });
      ctx.on('click', '[data-held]', (e, t) => { const h = st.held.find((x) => x.id === t.dataset.id); if (h) decideHeld(ctx, h, t.dataset.held); });
      ctx.on('click', '[data-clearhelddone]', () => { st.heldDone = null; ctx.rerender(); });
      // settings
      ctx.on('click', '[data-savechannel]', () => { const label = ctx.$('[data-clabel]').value, target = ctx.$('[data-ctarget]').value; if (/restricted/.test(target)) { ctx.toast('agent returns-agent is labelled restricted and cannot answer at ' + label + ': 422 step target.', 'danger'); return; } if (label === 'confidential' && c.workspace !== 'Finance Ops') { ctx.toast('Label confidential is above the ' + c.workspace + ' ceiling: 403 step zone.', 'danger'); return; } Object.assign(c, { name: ctx.$('[data-cname]').value.trim() || c.name, label, reviewMode: ctx.$('[data-creview]').value, target: { kind: target.split(' ')[0], name: target.split(' ')[1] }, messagesPerMinute: +ctx.$('[data-cmpm]').value || c.messagesPerMinute, sessionsPerHour: +ctx.$('[data-csph]').value || c.sessionsPerHour, retentionDays: ctx.$('[data-cret]').value === '' ? null : +ctx.$('[data-cret]').value, instructions: ctx.$('[data-cinstr]').value, greeting: ctx.$('[data-cgreet]') ? ctx.$('[data-cgreet]').value : c.greeting, allowAnonymous: ctx.$('[data-canon]').classList.contains('on') }); ctx.rerender(); ctx.toast('Channel saved; the binding was checked again. Audited as channel.updated.', 'ok'); });
      ctx.on('click', '[data-savemail]', () => { const pw = ctx.$('[data-eimappw]').value.trim(), spw = ctx.$('[data-esmtppw]').value.trim(); if (!/^vault:[a-z0-9./_-]+#[A-Za-z0-9_-]+$/.test(pw) || !/^vault:[a-z0-9./_-]+#[A-Za-z0-9_-]+$/.test(spw)) { ctx.toast('Credentials must be vault: references (vault:<path>#<key>); a literal password is 400.', 'danger'); return; } c.email.imap.passwordRef = pw; c.email.smtp.passwordRef = spw; c.email.address = ctx.$('[data-eaddr]').value; c.email.fromName = ctx.$('[data-efrom]').value; c.email.mailgunKeyRef = ctx.$('[data-emg]').value.trim(); st.vaultProblem = false; ctx.rerender(); ctx.toast('Mail settings saved; you are now the owner of the references and they were checked readable for you.', 'ok'); });
      ctx.on('click', '[data-pause]', async () => { const ok = await ctx.confirm({ title: 'Pause ' + c.name, tag: 'refuses new sessions', tone: 'danger', body: '<p style="margin:0" class="fg2">New public sessions answer 404 and customer tokens stop working until the channel is active again. Open sessions and held replies are kept.</p>', kv: [['Open sessions', String(c.open)]], ok: 'Pause' }); if (!ok) return; c.state = 'paused'; c.pausedBy = 'Mara Okafor'; c.pausedAt = 'just now'; ctx.rerender(); ctx.toast(esc(c.name) + ' paused.', 'warn'); });
      ctx.on('click', '[data-resume]', () => { c.state = 'active'; ctx.rerender(); ctx.toast(esc(c.name) + ' is active again; new sessions are accepted.', 'ok'); });
      ctx.on('click', '[data-purge]', () => ctx.toast('Retention purge queued (202). Sessions idle for more than ' + (c.retentionDays || '∞') + ' days are deleted with their messages; open hold flags closed as rejected. Audited per channel as channel.session.purged.', 'ok', 5000));
      ctx.on('click', '[data-poll]', () => { st.polled = true; ctx.rerender(); ctx.toast('channels.imap-poll job queued (202). Reads up to the next batch above UID ' + c.email.lastUid + '.', 'ok'); });
      ctx.on('click', '[data-delete]', async () => { const ok = await ctx.confirm({ title: 'Delete ' + c.name, tag: 'closes open sessions', tone: 'danger', body: '<p style="margin:0" class="fg2">The channel is deleted (state deleted) and its ' + c.open + ' open sessions are closed; customer tokens stop working. Transcripts stay until the retention purge.</p>', ok: 'Delete channel' }); if (!ok) return; c.state = 'deleted'; c.deletedAt = '19 Sep 2026'; st.sessions.filter((s) => s.channel === c.id && (s.state === 'open' || s.state === 'escalated')).forEach((s) => { s.state = 'closed'; s.closedBy = 'channel deleted'; }); st.held = st.held.filter((h) => h.channel !== c.id); c.open = 0; st.fstate = 'all'; ctx.rerender(); ctx.toast(esc(c.name) + ' deleted.', 'warn'); });
      ctx.on('click', '[data-rotate]', async (e, t) => { const which = t.dataset.rotate; const ok = await ctx.confirm({ title: 'Rotate ' + which + ' secret', tag: 'old secret stops at once', tone: 'danger', body: '<p style="margin:0" class="fg2">' + (which === 'identity' ? 'Identity assertions signed with the old secret are refused from now on; update the site first.' : 'Inbound mail webhooks signed with the old secret are refused (401); update the provider.') + ' The new value is shown once.</p>', ok: 'Rotate' }); if (!ok) return; st.rotated = { channel: c.id, which, value: secret(which === 'identity' ? 'chs' : 'chw') }; ctx.rerender(); ctx.toast('Secret rotated. Copy it now.', 'warn'); });
      ctx.on('click', '[data-rotatedone]', () => { st.rotated = null; ctx.rerender(); });
      ctx.on('click', '[data-newchannel]', () => newChannelModal(ctx));
      if (st.openNew) { st.openNew = false; setTimeout(() => newChannelModal(ctx), 50); }
      // email
      ctx.on('click', '[data-resend]', (e, t) => { const o = st.outbox.find((x) => x.id === t.dataset.resend); o.state = 'queued'; o.attempts = 0; o.error = null; o.at = 'just now'; st.mailFailedNote = false; ctx.rerender(); ctx.toast(esc(o.id) + ' queued again for the next channels.send run.', 'ok'); });
      ctx.on('click', '[data-clearmail]', () => { st.mailFailedNote = false; ctx.rerender(); });
      // exports
      ctx.on('click', '[data-export]', () => { const from = ctx.$('[data-xfrom]').value, to = ctx.$('[data-xto]').value; const id = 'job-' + Math.random().toString(16).slice(2, 8); st.exports.unshift({ id, channel: c.id, from, to, sessions: chSessions.length, state: 'running', by: 'Mara Okafor', at: 'just now', size: '' }); ctx.rerender(); ctx.toast('Export queued (202, ' + id + '). You are notified when the CSV is ready.', 'ok'); setTimeout(() => { const e2 = st.exports.find((x) => x.id === id); if (e2) { e2.state = 'finished'; e2.size = '0.2 MB'; if (ctx.app.state.route === 'channels' && !document.getElementById('overlay')) ctx.rerender(); } }, 2500); });
      ctx.on('click', '[data-download]', (e, t) => ctx.toast('Downloading ' + esc(t.dataset.download) + '.csv. Audited as channel.transcript.exported.', 'ok'));
    }
  });

  function transcriptPanel(st, c, s) {
    const tr = st.transcripts[s.id] || [];
    const msgs = tr.map((m) => '<div class="channels-msg ' + m.role + ' ' + m.state + '"><span class="who">' + esc(m.role === 'agent' ? (m.author || 'person') : m.role) + '</span><div class="body">' + (m.state === 'hidden' ? '<span class="muted">Hidden by moderation.</span>' : esc(m.text)) + (m.original ? '<div class="channels-orig">Model wrote: ' + esc(m.original) + '</div>' : '') + (m.state === 'held' ? '<div class="channels-orig">Held for review, flag <a href="#" data-openflag="' + esc(m.flag) + '">' + esc(m.flag) + '</a>; the customer sees state: pending. <a href="#" data-tab="held">Decide on the Held replies tab</a>.</div>' : '') + (m.state === 'rejected' ? '<div class="channels-orig">Rejected by ' + esc(m.rejectedBy) + ': ' + esc(m.reason) + '. The customer was told a person will follow up.</div>' : '') + '</div><span class="muted" style="font-size:11px;white-space:nowrap">' + esc(m.at) + ' · ' + esc(m.via) + (m.state === 'delivered' || m.role === 'customer' ? '' : ' · ' + esc(m.state)) + '</span>' + (m.role !== 'notice' && m.state !== 'hidden' ? UI.iconbtn('flag', 'Report this message', { attrs: 'data-reportmsg="' + m.seq + '"', cls: 'sm ghost', size: 13 }) : '') + '</div>').join('');
    const canAnswer = s.state === 'open' || s.state === 'escalated';
    return (s.state === 'escalated' ? UI.notice('<b>Escalated ' + esc(s.escalatedAt) + ': ' + esc(s.escalation) + '.</b> Reviewers holding channels:review in ' + esc(c.workspace) + ' were notified.' + (c.reviewMode === 'escalated' ? ' Every answer on this session now waits for a reviewer.' : ''), 'warn') : '')
      + (s.state === 'hidden' ? UI.notice('<b>Hidden by moderation</b> (<a href="#" data-openflag="' + esc(s.flag) + '">' + esc(s.flag) + '</a>): the customer\'s token stopped working and the transcript is shown to reviewers only.', 'danger') : '')
      + UI.panel('Transcript of ' + s.id, '<div class="hstack wrap" style="margin-bottom:8px">' + statePill(s.state) + '<span class="fg2">' + esc(s.customer.name) + (s.customer.email ? ', ' + esc(s.customer.email) : '') + (s.customer.externalId ? ', <span class="mono">' + esc(s.customer.externalId) + '</span>' : '') + '</span><span class="grow"></span>' + UI.label(s.label, { sm: true }) + small('started ' + esc(s.started) + ', ' + (s.via || 'chat')) + '</div>'
        + '<div class="vstack gap6">' + (msgs || small('No messages stored for this example session.')) + '</div>'
        + (canAnswer ? '<div style="margin-top:10px">' + UI.textarea(st.replyDraft || '', { rows: 2, placeholder: 'Answer as a person (role agent). Delivered at once' + (s.via === 'email' ? ' by email from ' + c.email.address : '') + '.', attrs: 'data-replydraft' }) + '</div>' : ''),
        { actions: (canAnswer ? UI.btn('Send answer', { kind: 'primary', size: 'sm', icon: 'send', attrs: 'data-reply' }) + UI.btn('Close session', { size: 'sm', attrs: 'data-closesession' }) : '') + UI.btn('Transcript CSV', { kind: 'ghost', size: 'sm', icon: 'download', attrs: 'data-exportcsv' }) });
  }

  function decideHeld(ctx, h, decision, presetText, presetReason, silent) {
    const st = ctx.state;
    const finish = (text, reason) => {
      const s = st.sessions.find((x) => x.id === h.session); const tr = st.transcripts[h.session] || []; const m = tr.find((x) => x.seq === h.seq);
      if (m) { if (decision === 'approve') { m.state = 'delivered'; } else if (decision === 'edit') { m.original = m.text; m.text = text; m.state = 'delivered'; m.editedBy = 'Mara Okafor'; } else { m.state = 'rejected'; m.rejectedBy = 'Mara Okafor'; m.reason = reason || 'Withdrawn by the reviewer'; tr.push({ seq: tr.length + 1, role: 'notice', state: 'delivered', via: m.via, text: 'A person will follow up on your question.', at: 'now' }); if (s) s.messages += 1; } }
      if (s) { s.last = 'just now'; if (s.via === 'email' && decision !== 'reject') { const o = st.outbox.find((x) => x.session === s.id && x.state === 'queued'); if (o) { o.state = 'sent'; o.attempts = 1; o.at = 'just now'; o.messageId = '<' + o.id + '@northwind.example>'; } } }
      st.held = st.held.filter((x) => x.id !== h.id);
      st.heldDone = '<b>' + esc(h.flag) + ' ' + (decision === 'approve' ? 'approved: the reply went to ' + esc(h.customer) + ' as written.' : decision === 'edit' ? 'edited: your text went to ' + esc(h.customer) + '; the model\'s text is kept as original on the message.' : 'rejected: the reply was withdrawn and ' + esc(h.customer) + ' was told a person will follow up.') + '</b> Audited as channel.reply.' + (decision === 'reject' ? 'rejected' : 'sent') + (decision === 'edit' ? ' (edited: true) and channel.reply.edited' : '') + '; the flag records the decision. <a href="#" data-opensession="' + esc(h.session) + '">Open the session</a>.';
      if (!silent) { ctx.rerender(); ctx.toast(esc(h.flag) + ' ' + (decision === 'approve' ? 'approved and delivered.' : decision === 'edit' ? 'edited and delivered.' : 'rejected and withdrawn.'), decision === 'reject' ? 'warn' : 'ok'); }
    };
    if (silent) { finish(presetText, presetReason); return; }
    if (decision === 'approve') { ctx.confirm({ title: 'Approve reply', tag: 'delivers now', tone: 'info', body: '<p style="margin:0" class="fg2">The reply goes to the customer as written' + (h.channel === 'ch-billing' ? ', by email from the channel\'s address' : '') + '. The hold flag is recorded as approved.</p><div class="serif" style="padding:8px 10px;background:var(--panel2);border-radius:6px">' + esc(h.text) + '</div>', kv: [['Flag', h.flag], ['Session', h.session], ['Customer', h.customer]], ok: 'Approve and send' }).then((ok) => { if (ok) finish(); }); return; }
    if (decision === 'edit') { ctx.modal({ title: 'Edit and send', cls: 'wide', body: UI.notice('Your text is delivered instead; the model\'s text is kept as <span class="mono">original</span> on the message and in the CSV. Audited as channel.reply.sent with edited: true and channel.reply.edited.', 'info') + UI.field('Reply to ' + esc(h.customer), UI.textarea(h.text, { rows: 4, attrs: 'data-etext' })) + small('Why it was held: ' + esc(h.why)), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Send edited reply', { kind: 'primary', attrs: 'data-esend' }), onMount(m) { m.querySelector('[data-esend]').addEventListener('click', () => { const text = m.querySelector('[data-etext]').value.trim(); if (!text) { ctx.toast('The reply cannot be empty; reject it instead.', 'warn'); return; } if (text === h.text) { ctx.toast('Unchanged text: use Approve.', 'warn'); return; } App.closeOverlay(); finish(text); }); } }); return; }
    ctx.confirm({ title: 'Reject reply', tag: 'withdraws it', tone: 'danger', body: '<p style="margin:0" class="fg2">The reply is withdrawn; the customer is told a person will follow up and the session stays open for you to answer. The hold flag is recorded as rejected.</p>' + UI.field('Reason', UI.select(['Wrong or unsupported figure', 'Repeats customer PII', 'Promises something we cannot keep', 'Other'], h.checkpoint === 'model-output' ? 'Repeats customer PII' : 'Promises something we cannot keep', 'data-rreason')), kv: [['Flag', h.flag], ['Session', h.session], ['Customer', h.customer]], ok: 'Reject' }).then((ok) => { if (ok) finish(null, 'Rejected by the reviewer'); });
  }

  function newChannelModal(ctx) {
    const st = ctx.state;
    ctx.modal({ title: 'New channel', cls: 'wide',
      body: '<div class="formgrid" style="--cols:3">' + UI.field('Workspace', UI.select(['Field Sales', 'Finance Ops', 'People Ops'], 'Field Sales', 'data-nws')) + UI.field('Kind', UI.select(['chat', 'email'], 'chat', 'data-nkind')) + UI.field('Name', UI.input('', { attrs: 'data-nname', placeholder: 'Order status' })) + UI.field('Label', UI.select(['public', 'internal', 'confidential'], 'public', 'data-nlabel'), 'Under the workspace ceiling, your clearance and the target\'s label') + UI.field('Target', UI.select(['profile support-fast', 'profile hr-assistant', 'agent billing-helper', 'agent returns-agent (restricted)'], 'profile support-fast', 'data-ntarget'), 'A published profile or agent; agents answer with their profile and system prompt, never their tools') + UI.field('Review mode', UI.select(['never', 'escalated', 'always'], 'escalated', 'data-nreview')) + UI.field('Messages per minute', UI.input('10', { type: 'number', attrs: 'data-nmpm' })) + UI.field('Sessions per hour', UI.input('10', { type: 'number', attrs: 'data-nsph' })) + UI.field('Retention (days)', UI.input('30', { type: 'number', attrs: 'data-nret' })) + '</div>'
        + UI.field('Instructions', UI.textarea('', { rows: 2, attrs: 'data-ninstr', placeholder: 'What the channel may and may not answer' })) + UI.field('Greeting (chat)', UI.input('', { attrs: 'data-ngreet' })) + UI.toggle('Allow anonymous customers', true, 'data-nanon')
        + '<div class="divider"></div><div class="eyebrow">Email (email channels only)</div><div class="formgrid" style="--cols:3">' + UI.field('Address', UI.input('', { attrs: 'data-naddr', placeholder: 'orders@northwind.example' })) + UI.field('IMAP host:port', UI.input('', { attrs: 'data-nimap', placeholder: 'imap.northwind.example:993' })) + UI.field('IMAP password', UI.input('', { attrs: 'data-nimappw', placeholder: 'vault:kv/channels/orders#imap' })) + UI.field('SMTP host:port', UI.input('', { attrs: 'data-nsmtp', placeholder: 'smtp.northwind.example:465' })) + UI.field('SMTP password', UI.input('', { attrs: 'data-nsmtppw', placeholder: 'vault:kv/channels/orders#smtp' })) + UI.field('Mailgun signing key', UI.input('', { attrs: 'data-nmg', placeholder: 'vault:kv/channels/orders#mailgun' })) + '</div>' + small('Credentials must be vault: references (400 otherwise), readable by you at save and read as you at use. Hosts pass the service address rules and the tenant\'s allowed hosts.'),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create channel', { kind: 'primary', attrs: 'data-ncreate' }),
      onMount(m) { m.querySelector('[data-ncreate]').addEventListener('click', () => {
        const ws = m.querySelector('[data-nws]').value, kind = m.querySelector('[data-nkind]').value, name = m.querySelector('[data-nname]').value.trim(), label = m.querySelector('[data-nlabel]').value, target = m.querySelector('[data-ntarget]').value;
        if (!name) { ctx.toast('A channel needs a name.', 'warn'); return; }
        if (/restricted/.test(target)) { ctx.toast('agent returns-agent is labelled restricted and cannot answer at ' + label + ': 422 step target.', 'danger'); return; }
        if (label === 'confidential' && ws !== 'Finance Ops') { ctx.toast('Label confidential is above the ' + ws + ' ceiling: 403 step zone.', 'danger'); return; }
        const refOk = (v) => !v || /^vault:[a-z0-9./_-]+#[A-Za-z0-9_-]+$/.test(v);
        if (kind === 'email' && (!refOk(m.querySelector('[data-nimappw]').value.trim()) || !refOk(m.querySelector('[data-nsmtppw]').value.trim()))) { ctx.toast('Mail credentials must be vault: references: 400.', 'danger'); return; }
        App.closeOverlay();
        const id = 'ch-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); const publicKey = 'chk_' + id.slice(3).replace(/-/g, '') + '_' + Math.random().toString(16).slice(2, 10);
        const ch = { id, name, kind, workspace: ws, label, state: 'active', reviewMode: m.querySelector('[data-nreview]').value, target: { kind: target.split(' ')[0], name: target.split(' ')[1] }, instructions: m.querySelector('[data-ninstr]').value, allowAnonymous: m.querySelector('[data-nanon]').classList.contains('on'), messagesPerMinute: +m.querySelector('[data-nmpm]').value || 10, sessionsPerHour: +m.querySelector('[data-nsph]').value || 10, retentionDays: m.querySelector('[data-nret]').value === '' ? null : +m.querySelector('[data-nret]').value, greeting: m.querySelector('[data-ngreet]').value, publicKey, created: '19 Sep 2026', open: 0, escalated: 0 };
        if (kind === 'email') { const [ih, ip] = (m.querySelector('[data-nimap]').value || 'imap.northwind.example:993').split(':'); const [sh, sp] = (m.querySelector('[data-nsmtp]').value || 'smtp.northwind.example:465').split(':'); ch.email = { address: m.querySelector('[data-naddr]').value || name.toLowerCase().replace(/\s+/g, '') + '@northwind.example', fromName: 'Northwind ' + name, imap: { host: ih, port: +ip || 993, secure: true, user: m.querySelector('[data-naddr]').value, passwordRef: m.querySelector('[data-nimappw]').value.trim() || 'vault:kv/channels/' + id.slice(3) + '#imap', mailbox: 'INBOX' }, smtp: { host: sh, port: +sp || 465, secure: true, user: m.querySelector('[data-naddr]').value, passwordRef: m.querySelector('[data-nsmtppw]').value.trim() || 'vault:kv/channels/' + id.slice(3) + '#smtp' }, mailgunKeyRef: m.querySelector('[data-nmg]').value.trim(), uidValidity: 1758290400, lastUid: 0, lastPoll: 'never' }; }
        st.channels.unshift(ch); st.sel = id; st.tab = 'settings'; st.fstate = 'live'; st.fkind = 'all';
        st.rotated = { channel: id, which: 'identity', value: secret('chs') + (kind === 'email' ? '\nwebhook secret: ' + secret('chw') : '') };
        ctx.rerender(); ctx.toast(esc(name) + ' created (201). The secrets are shown once on the Settings tab.', 'ok', 5000);
      }); } });
  }
})();
