(function () {
  const { UI, esc } = App;

  // ---- example data: Northwind, the caller's workspaces (Finance Ops, People Ops, Field Sales) ----
  const groups0 = () => [
    { id: 'g-close', name: 'Month-end close', workspace: 'Finance Ops', description: 'Everyone on the close calendar: cut-off, accruals, flash report and the ledger freeze. Posts are the daily close notices.', visibility: 'private', joinMode: 'request', label: 'confidential', members: 14, role: 'owner', state: 'active', created: '3 Mar 2026' },
    { id: 'g-travel', name: 'Travel policy working group', workspace: 'Finance Ops', description: 'Drafting the 2027 travel policy with People Ops. Open to anyone in the workspace.', visibility: 'public', joinMode: 'open', label: 'internal', members: 31, role: 'member', state: 'active', created: '12 Jun 2026' },
    { id: 'g-audit', name: 'Audit liaison', workspace: 'Finance Ops', description: 'The contact group for the external auditors. Known only to its members and invitees.', visibility: 'hidden', joinMode: 'invite', label: 'confidential', members: 6, role: 'moderator', state: 'active', created: '20 Jan 2026' },
    { id: 'g-champions', name: 'AI champions', workspace: 'People Ops', description: 'People who run the monthly show-and-tell on what the assistants can do.', visibility: 'public', joinMode: 'open', label: 'internal', members: 58, role: 'none', state: 'active', created: '8 Feb 2026' },
    { id: 'g-emea', name: 'EMEA field kickoff', workspace: 'Field Sales', description: null, visibility: 'private', joinMode: 'request', label: 'internal', members: 22, role: 'none', state: 'active', created: '1 Sep 2026' },
    { id: 'g-board', name: 'Board pack reviewers', workspace: 'Finance Ops', description: null, visibility: 'private', joinMode: 'invite', label: 'confidential', members: 4, role: 'none', state: 'active', created: '15 Aug 2026' }
  ];
  const members0 = { 'g-close': [
    { user: 'Mara Okafor', username: 'mokafor', role: 'owner', joined: '3 Mar 2026' }, { user: 'Priya Nair', username: 'pnair', role: 'moderator', joined: '3 Mar 2026' }, { user: 'Jonas Lindqvist', username: 'jlindqvist', role: 'member', joined: '4 Mar 2026' },
    { user: 'Tomasz Weber', username: 'tweber', role: 'member', joined: '10 Mar 2026' }, { user: 'Lena Hoffmann', username: 'lhoffmann', role: 'member', joined: '2 Apr 2026' }, { user: 'Felix Brandt', username: 'fbrandt', role: 'member', joined: '18 Aug 2026' }
  ] };
  const requests0 = () => [
    { id: 'r-1', group: 'g-close', kind: 'request', user: 'Samir Haddad', role: 'member', state: 'pending', expires: '26 Sep 2026', when: '19 Sep 09:40' },
    { id: 'r-2', group: 'g-close', kind: 'invite', user: 'Noor Rahimi', role: 'member', state: 'pending', expires: '30 Sep 2026', when: '16 Sep 15:02', by: 'Priya Nair' },
    { id: 'r-3', group: 'g-close', kind: 'invite', user: 'Aisha Bello', role: 'moderator', state: 'expired', expires: '12 Sep 2026', when: '29 Aug 10:10', by: 'Mara Okafor' },
    { id: 'r-4', group: 'g-close', kind: 'request', user: 'Felix Brandt', role: 'member', state: 'accepted', expires: '', when: '18 Aug 11:30', decidedBy: 'Priya Nair' }
  ];
  const posts0 = () => [
    { id: 'gp-531', group: 'g-close', author: 'Mara Okafor', body: 'Cut-off for September is Wednesday 30 Sep, 18:00 CEST. Accruals above 25k EUR need a ticket by Tuesday noon.', label: 'confidential', state: 'sent', when: '19 Sep 08:55' },
    { id: 'gp-530', group: 'g-close', author: 'Priya Nair', body: 'The intercompany recon call moved to 11:00 today; the invite is on the group calendar.', label: 'confidential', state: 'sent', when: '19 Sep 08:10' },
    { id: 'gp-528', group: 'g-close', author: 'Tomasz Weber', body: null, label: 'confidential', state: 'hidden', when: '18 Sep 17:20', flag: 'F-2308' },
    { id: 'gp-526', group: 'g-close', author: 'Jonas Lindqvist', body: 'Reminder that the flash report template changed: the FX line is now split by currency.', label: 'confidential', state: 'sent', when: '17 Sep 14:02' },
    { id: 'gp-412', group: 'g-travel', author: 'Noor Rahimi', body: 'Draft 3 of the policy is in the Travel KB. Comments by Friday.', label: 'internal', state: 'sent', when: '18 Sep 10:30' }
  ];
  const events0 = () => [
    { id: 'e-6', group: 'g-close', title: 'Intercompany reconciliation call', date: '2026-09-19', start: '11:00', end: '12:00', tz: 'Europe/Berlin', allDay: false, location: 'Teams, Finance Ops room', capacity: null, maxGuests: 0, reminders: [60, 10], label: 'confidential', state: 'scheduled', sequence: 2, going: 9, maybe: 2, guests: 0, checkedIn: 7, myRsvp: 'going' },
    { id: 'e-1', group: 'g-close', title: 'Close kickoff', date: '2026-09-28', start: '09:00', end: '10:00', tz: 'Europe/Berlin', allDay: false, location: 'Room 4.02, Hamburg', capacity: 20, maxGuests: 0, reminders: [1440, 60], label: 'confidential', state: 'scheduled', sequence: 1, going: 14, maybe: 3, guests: 0, checkedIn: 0, myRsvp: 'going' },
    { id: 'e-4', group: 'g-close', title: 'Ledger freeze', date: '2026-09-30', start: '18:00', end: '18:30', tz: 'UTC', allDay: false, location: 'Chat only', capacity: null, maxGuests: 0, reminders: [30], label: 'confidential', state: 'scheduled', sequence: 1, going: 11, maybe: 0, guests: 0, checkedIn: 0, myRsvp: 'maybe' },
    { id: 'e-2', group: 'g-close', title: 'Q3 flash report review', date: '2026-10-02', start: '14:00', end: '15:30', tz: 'Europe/Berlin', allDay: false, location: 'Room 4.02, Hamburg', capacity: 25, maxGuests: 0, reminders: [1440, 60], label: 'confidential', state: 'scheduled', sequence: 1, going: 15, maybe: 2, guests: 0, checkedIn: 0, myRsvp: null },
    { id: 'e-7', group: 'g-close', title: 'Audit walkthrough (small room)', date: '2026-10-06', start: '10:00', end: '11:30', tz: 'Europe/Berlin', allDay: false, location: 'Room 2.11, Hamburg', capacity: 8, maxGuests: 0, reminders: [60], label: 'confidential', state: 'scheduled', sequence: 1, going: 8, maybe: 1, guests: 0, checkedIn: 0, myRsvp: null },
    { id: 'e-3', group: 'g-close', title: 'Finance offsite', date: '2026-10-15', endDate: '2026-10-16', start: '', end: '', tz: 'Europe/Lisbon', allDay: true, location: 'Lisbon office', capacity: 40, maxGuests: 1, reminders: [10080, 1440], label: 'confidential', state: 'scheduled', sequence: 3, going: 22, maybe: 6, guests: 4, checkedIn: 0, myRsvp: 'going' },
    { id: 'e-5', group: 'g-travel', title: 'Travel policy Q&A', date: '2026-09-22', start: '16:00', end: '17:00', tz: 'Europe/Berlin', allDay: false, location: 'Teams', capacity: null, maxGuests: 0, reminders: [60], label: 'internal', state: 'scheduled', sequence: 1, going: 19, maybe: 4, guests: 0, checkedIn: 0, myRsvp: null }
  ];
  const reminders0 = {
    'e-6': [{ min: 60, fire: '19 Sep 10:00', state: 'sent', recipients: 11, sentAt: '19 Sep 10:00' }, { min: 10, fire: '19 Sep 10:50', state: 'sent', recipients: 11, sentAt: '19 Sep 10:50' }],
    'e-1': [{ min: 1440, fire: '27 Sep 09:00', state: 'scheduled', recipients: 17 }, { min: 60, fire: '28 Sep 08:00', state: 'scheduled', recipients: 17 }],
    'e-4': [{ min: 30, fire: '30 Sep 17:30 UTC', state: 'scheduled', recipients: 11 }],
    'e-2': [{ min: 1440, fire: '1 Oct 14:00', state: 'scheduled', recipients: 17 }, { min: 60, fire: '2 Oct 13:00', state: 'scheduled', recipients: 17 }],
    'e-7': [{ min: 60, fire: '6 Oct 09:00', state: 'scheduled', recipients: 9 }],
    'e-3': [{ min: 10080, fire: '8 Oct 00:00', state: 'scheduled', recipients: 28 }, { min: 1440, fire: '14 Oct 00:00', state: 'scheduled', recipients: 28 }],
    'e-5': [{ min: 60, fire: '22 Sep 15:00', state: 'scheduled', recipients: 23 }]
  };
  const attendees0 = { 'e-6': [['Mara Okafor', 'going', true], ['Priya Nair', 'going', true], ['Jonas Lindqvist', 'going', true], ['Tomasz Weber', 'going', false], ['Lena Hoffmann', 'maybe', false], ['Felix Brandt', 'going', true]] };
  const feeds0 = () => [
    { id: 'cf-1', kind: 'user', target: 'My calendar', url: 'https://ai.northwind.local/calendar/feeds/cf-1/9f1c…b2a7.ics', created: '14 Mar 2026', lastUsed: 'today 07:02', revoked: null },
    { id: 'cf-2', kind: 'group', target: 'Month-end close', url: 'https://ai.northwind.local/calendar/feeds/cf-2/41de…0c93.ics', created: '3 Mar 2026', lastUsed: '18 Sep 22:15', revoked: null },
    { id: 'cf-3', kind: 'event', target: 'Finance offsite', url: 'https://ai.northwind.local/calendar/feeds/cf-3/7a08…e411.ics', created: '20 Aug 2026', lastUsed: '2 Sep 09:40', revoked: '10 Sep 2026' }
  ];
  const cases0 = () => [
    { id: 'F-2308', group: 'g-close', kind: 'report', object: 'group-post gp-528', rule: 'User report: sensitive data', sev: 'medium', state: 'confirmed, hidden', due: '18 Sep 21:20', label: 'confidential' },
    { id: 'F-2309', group: 'g-close', kind: 'guard', object: 'group-event e-3 (description)', rule: 'PII detector', sev: 'low', state: 'open', due: '20 Sep 09:00', label: 'confidential' }
  ];

  const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  const fmtDate = (iso) => { const [y, m, d] = iso.split('-').map(Number); return d + ' ' + MONTHS[m - 1].slice(0, 3) + ' ' + y; };
  const when = (e) => e.allDay ? fmtDate(e.date) + (e.endDate ? ' to ' + fmtDate(e.endDate) : '') + ', all day (' + e.tz + ')' : fmtDate(e.date) + ', ' + e.start + ' to ' + e.end + ' ' + e.tz;
  const remText = (m) => m >= 10080 ? (m / 10080) + ' week' + (m === 10080 ? '' : 's') : m >= 1440 ? (m / 1440) + ' day' + (m === 1440 ? '' : 's') : m >= 60 ? (m / 60) + ' h' : m + ' min';
  const visPill = (v) => UI.pill(v, v === 'hidden' ? 'warn' : v === 'private' ? '' : 'outline');
  const rolePill = (r) => r === 'none' ? '' : UI.pill(r, r === 'owner' ? 'accent' : r === 'moderator' ? 'info' : 'outline');
  const canModerate = (g) => g.role === 'owner' || g.role === 'moderator' || true; // Mara also holds groups:manage (tenant admin acts as owner)
  const small = (t) => '<span class="muted" style="font-size:12px">' + t + '</span>';

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }

  function calendar(st, events, year, month) {
    const first = new Date(year, month, 1); const startDow = (first.getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate();
    let cells = ''; for (let i = 0; i < startDow; i++) cells += '<div class="groups-day pad"></div>';
    for (let d = 1; d <= days; d++) {
      const iso = year + '-' + String(month + 1).padStart(2, '0') + '-' + String(d).padStart(2, '0');
      const todays = events.filter((e) => e.date <= iso && (e.endDate || e.date) >= iso);
      const isToday = iso === '2026-09-19';
      cells += '<div class="groups-day' + (isToday ? ' today' : '') + '"><div class="n">' + d + '</div>' + todays.map((e) => '<button type="button" class="groups-ev ' + (e.state === 'cancelled' ? 'cancelled' : '') + (e.id === st.eventSel ? ' on' : '') + '" data-event="' + e.id + '" title="' + esc(e.title) + '">' + (e.allDay ? '' : '<span class="mono">' + esc(e.start) + '</span> ') + esc(e.title) + '</button>').join('') + '</div>';
    }
    return '<div class="groups-cal"><div class="hstack" style="margin-bottom:6px">' + UI.iconbtn('chev', 'Previous month', { attrs: 'data-cal="-1"', cls: 'sm ghost groups-prev', size: 14 }) + '<b class="grow" style="text-align:center">' + MONTHS[month] + ' ' + year + '</b>' + UI.iconbtn('chev', 'Next month', { attrs: 'data-cal="1"', cls: 'sm ghost', size: 14 }) + '</div><div class="groups-grid">' + ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d) => '<div class="groups-dow">' + d + '</div>').join('') + cells + '</div></div>';
  }

  App.register({
    id: 'groups', title: 'Groups and events', crumb: ['Groups and events'],
    summary: 'Groups with join modes, requests and invitations, posts, a calendar with RSVP and check-in, reminders, feed URLs',
    label: (st) => { const g = (st.groups || []).find((x) => x.id === st.sel); return g ? g.label : null; },
    commands: [{ label: 'Create a group', sub: 'Groups and events', run(app) { app.stateFor('groups').openNew = true; app.render(); } }, { label: 'Create an event', sub: 'Groups and events', run(app) { const s = app.stateFor('groups'); s.tab = 'events'; s.openNewEvent = true; app.render(); } }],
    states: [
      { title: 'Join needs a request', tone: 'info', text: 'A request-mode group answers 202 with the pending request; moderators are notified. Asking again returns the same request.', apply(ctx) { const st = ctx.state; st.mode = 'discover'; st.sel = 'g-emea'; st.tab = 'overview'; st.requested = st.requested || {}; st.requested['g-emea'] = { id: 'r-9', when: 'just now' }; ctx.rerender(); } },
      { title: 'Capacity reached', tone: 'danger', text: 'Capacity counts people with their guests. An RSVP past it is 409 with the places left.', apply(ctx) { const st = ctx.state; st.sel = 'g-close'; st.tab = 'events'; st.eventSel = 'e-7'; st.capacityProblem = 'e-7'; st.calMonth = 9; ctx.rerender(); } },
      { title: 'Event cancelled, attendees notified', tone: 'warn', text: 'Cancelling stops the reminders and notifies every attendee (going or maybe) in the console and by email, without the title or reason.', apply(ctx) { const st = ctx.state; st.sel = 'g-close'; st.tab = 'events'; st.eventSel = 'e-2'; st.calMonth = 9; const e = st.events.find((x) => x.id === 'e-2'); if (e && e.state !== 'cancelled') { e.state = 'cancelled'; e.cancelReason = 'Moved into the close kickoff'; e.notified = e.going + e.maybe; (st.reminders['e-2'] || []).forEach((r) => { if (r.state === 'scheduled') r.state = 'cancelled'; }); } st.cancelledNote = 'e-2'; ctx.rerender(); } },
      { title: 'Hidden group (moderation)', tone: 'warn', text: 'A group hidden through moderation is closed to everyone but managers and its owners; its events leave calendars and reminders stop.', apply(ctx) { const st = ctx.state; if (!st.groups.some((g) => g.id === 'g-vendor')) st.groups.push({ id: 'g-vendor', name: 'Vendor chatter', workspace: 'Finance Ops', description: 'Hidden by moderation on 18 Sep (F-2301, upheld).', visibility: 'private', joinMode: 'open', label: 'internal', members: 9, role: 'none', state: 'hidden', created: '2 Jul 2026' }); st.mode = 'discover'; st.sel = 'g-vendor'; st.tab = 'overview'; ctx.rerender(); } },
      { title: 'Last owner cannot leave', tone: 'danger', text: 'A group keeps at least one owner: leaving or demoting the last one is 409. Hand over ownership first.', apply(ctx) { const st = ctx.state; st.sel = 'g-close'; st.tab = 'members'; st.leaveProblem = true; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      if (!st.groups) { st.groups = groups0(); st.members = JSON.parse(JSON.stringify(members0)); st.requests = requests0(); st.posts = posts0(); st.events = events0(); st.reminders = JSON.parse(JSON.stringify(reminders0)); st.attendees = JSON.parse(JSON.stringify(attendees0)); st.feeds = feeds0(); st.cases = cases0(); st.requested = {}; }
      st.mode = st.mode || 'mine'; st.tab = st.tab || 'overview'; st.query = st.query || ''; st.fws = st.fws || 'all'; st.fvis = st.fvis || 'all'; st.fjoin = st.fjoin || 'all'; if (st.calMonth == null) st.calMonth = 8; st.calYear = 2026;
      if (ctx.params.group) { st.sel = ctx.params.group; if (!st.groups.some((g) => g.id === st.sel && g.role !== 'none')) st.mode = 'discover'; delete ctx.params.group; }
      if (ctx.params.event) { const e = st.events.find((x) => x.id === ctx.params.event); if (e) { st.sel = e.group; st.tab = 'events'; st.eventSel = e.id; st.calMonth = +e.date.slice(5, 7) - 1; } delete ctx.params.event; }
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }

      let list = st.groups.filter((g) => st.mode === 'mine' ? g.role !== 'none' : true);
      list = list.filter((g) => (!st.query || (g.name + ' ' + (g.description || '')).toLowerCase().includes(st.query.toLowerCase())) && (st.fws === 'all' || g.workspace === st.fws) && (st.fvis === 'all' || g.visibility === st.fvis) && (st.fjoin === 'all' || g.joinMode === st.fjoin));
      if (!st.sel || !st.groups.some((g) => g.id === st.sel)) st.sel = list.length ? list[0].id : st.groups[0].id;
      const g = st.groups.find((x) => x.id === st.sel);
      const isMember = g.role !== 'none'; const isOwner = g.role === 'owner'; const isMod = g.role === 'owner' || g.role === 'moderator'; const hidden = g.state === 'hidden';
      const readsContent = (isMember || g.visibility === 'public') && !hidden;

      const left = '<div class="leftpane w320">' + UI.seg([{ id: 'mine', label: 'My groups' }, { id: 'discover', label: 'Discover' }], st.mode, 'data-modeseg')
        + UI.search('Search groups', 'data-search', st.query)
        + '<div class="hstack gap6 wrap"><span class="relative">' + UI.btn(st.fws === 'all' ? 'Workspace' : st.fws, { size: 'xs', icon: 'filter', attrs: 'data-fws', cls: st.fws === 'all' ? '' : 'active' }) + '</span><span class="relative">' + UI.btn(st.fvis === 'all' ? 'Visibility' : st.fvis, { size: 'xs', icon: 'filter', attrs: 'data-fvis', cls: st.fvis === 'all' ? '' : 'active' }) + '</span><span class="relative">' + UI.btn(st.fjoin === 'all' ? 'Join mode' : st.fjoin, { size: 'xs', icon: 'filter', attrs: 'data-fjoin', cls: st.fjoin === 'all' ? '' : 'active' }) + '</span></div>'
        + '<div class="vstack" style="gap:2px">' + list.map((x) => UI.listItem(esc(x.name) + (x.state === 'hidden' ? ' ' + UI.pill('hidden by moderation', 'warn') : ''), esc(x.workspace) + ', ' + x.members + ' members, ' + esc(x.visibility) + ', ' + esc(x.joinMode), { active: x.id === st.sel, attrs: 'data-group="' + x.id + '"', right: rolePill(x.role) || UI.label(x.label, { sm: true }) })).join('') + (list.length ? '' : UI.empty('No groups match', st.mode === 'mine' ? 'You are in no group that matches. Try Discover.' : 'Hidden groups are known only to their members and invitees.')) + '</div>'
        + '<div style="margin-top:auto">' + UI.btn('New group', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newgroup' }) + '</div></div>';

      const tabs = UI.tabs([{ id: 'overview', label: 'Overview' }, { id: 'members', label: 'Members', count: g.members }, { id: 'posts', label: 'Posts', count: st.posts.filter((p) => p.group === g.id).length }, { id: 'events', label: 'Events', count: st.events.filter((e) => e.group === g.id && e.state !== 'cancelled').length }, { id: 'feeds', label: 'Feeds' }].concat(isMod ? [{ id: 'cases', label: 'Cases', count: st.cases.filter((c) => c.group === g.id && c.state === 'open').length }] : []), st.tab);
      const headActions = (hidden ? '' : isMember ? (st.tab === 'overview' ? UI.btn('Leave', { kind: 'ghost', size: 'sm', attrs: 'data-leave' }) : '') : st.requested[g.id] ? UI.pill('request pending', 'info') + UI.btn('Withdraw', { kind: 'ghost', size: 'sm', attrs: 'data-withdrawmine' }) : UI.btn(g.joinMode === 'open' ? 'Join' : g.joinMode === 'request' ? 'Ask to join' : 'Invite only', { kind: 'primary', size: 'sm', attrs: 'data-join', disabled: g.joinMode === 'invite' && !st.showJoinRefusal })) + UI.label(g.label);
      const head = UI.pagehead(g.name, esc(g.workspace) + ' · ' + visPill(g.visibility) + ' · join: ' + esc(g.joinMode) + ' · ' + g.members + ' members' + (g.role !== 'none' ? ' · your role: ' + esc(g.role) : '') + ' · created ' + esc(g.created), headActions);
      let body = '', aside = '';

      if (hidden) {
        body = UI.notice('<b>Hidden by moderation.</b> ' + esc(g.description) + ' The group is closed to everyone but managers and its owners; its events are left out of calendars and their reminders are not sent. An upheld appeal restores it.', 'warn', UI.btn('Open in Moderation', { size: 'sm', attrs: 'data-gomoderation' }));
      } else if (st.tab === 'overview') {
        body = (st.requested[g.id] ? UI.notice('<b>Request sent (202).</b> Your request to join ' + esc(g.name) + ' is pending; the group\'s moderators were notified. Asking again returns the same request. It expires after 14 days.', 'info') : '')
          + (st.joinRefused === g.id ? UI.problem('Invite only', g.name + ' admits people by invitation: joining is 403 with step join-mode unless you hold an invitation, which the Join button would then accept. Ask an owner or moderator to invite you.', '2b7f9e1c4a6d4f0b8c3e5a7d9f1b3c5e') : '')
          + (st.leaveProblem && g.id === 'g-close' && st.tab === 'overview' ? UI.problem('Last owner cannot leave', 'You are the only owner of Month-end close. Make someone else an owner on the Members tab first; the group keeps at least one owner (409).', '6c1d8a3f5b2e4c7a9d0f2b4e6a8c1d3f') : '')
          + UI.panel('About', readsContent || isMember ? '<div class="serif" style="font-size:15px;line-height:1.5">' + esc(g.description || 'No description yet.') + '</div>' : UI.notice('The description and content are shown to members only (private group). Join to read them.', 'info'))
          + '<div class="grid3">' + UI.stat(String(g.members), 'members', small(st.requests.filter((r) => r.group === g.id && r.state === 'pending').length + ' pending requests and invitations')) + UI.stat(String(st.events.filter((e) => e.group === g.id && e.state !== 'cancelled' && e.date >= '2026-09-19').length), 'upcoming events', small('next: ' + esc((st.events.filter((e) => e.group === g.id && e.state !== 'cancelled' && e.date >= '2026-09-19').sort((a, b) => a.date.localeCompare(b.date))[0] || {}).title || 'none'))) + UI.stat(String(st.posts.filter((p) => p.group === g.id && p.state !== 'hidden').length), 'posts', small('newest ' + esc((st.posts.filter((p) => p.group === g.id)[0] || {}).when || ''))) + '</div>'
          + (isOwner || isMod ? UI.panel('Settings', '<div class="formgrid" style="--cols:3">' + UI.field('Name', UI.input(g.name, { attrs: 'data-sname', readonly: !isOwner })) + UI.field('Visibility', UI.select(['public', 'private', 'hidden'], g.visibility, 'data-svis' + (isOwner ? '' : ' disabled'))) + UI.field('Join mode', UI.select(['open', 'request', 'invite'], g.joinMode, 'data-sjoin' + (isOwner ? '' : ' disabled'))) + UI.field('Label', UI.select(['public', 'internal', 'confidential', 'restricted'], g.label, 'data-slabel' + (isOwner ? '' : ' disabled')), 'At most the workspace ceiling (' + (g.workspace === 'Finance Ops' ? 'confidential' : 'internal') + '); raising it raises every post and event and re-checks the sockets in the room') + '</div>' + UI.field('Description', UI.textarea(g.description || '', { rows: 2, attrs: 'data-sdesc' + (isOwner ? '' : ' readonly') })) + '<div class="hstack gap6">' + UI.btn('Save', { kind: 'primary', size: 'sm', attrs: 'data-savesettings', disabled: !isOwner }) + (isOwner ? UI.btn('Delete group', { kind: 'danger', size: 'sm', attrs: 'data-delete' }) : small('Settings are the owner\'s; moderators handle requests, members, posts and events.')) + '</div>') : '')
          + small('Workspace membership is the outer boundary: a member who leaves ' + esc(g.workspace) + ' loses this group at once, whatever their group role.');
      } else if (st.tab === 'members') {
        const mem = st.members[g.id] || [{ user: 'Owner (not shown)', username: '', role: 'owner', joined: '' }];
        const reqs = st.requests.filter((r) => r.group === g.id);
        body = (st.leaveProblem && g.id === 'g-close' ? UI.problem('Last owner cannot leave', 'You are the only owner of Month-end close. Make someone else an owner first; the group keeps at least one owner (409). Demoting yourself is refused for the same reason.', '6c1d8a3f5b2e4c7a9d0f2b4e6a8c1d3f') : '')
          + (readsContent ? UI.panel('Members', UI.table(['Member', 'Account', 'Role', 'Joined', ''], mem.map((m) => [esc(m.user) + (m.username === 'mokafor' ? ' ' + UI.pill('you', 'accent') : ''), '<span class="mono">' + esc(m.username) + '</span>', rolePill(m.role), esc(m.joined), isMod ? '<span class="hstack gap6" style="justify-content:flex-end">' + (isOwner ? '<span class="relative">' + UI.btn('Role', { size: 'xs', attrs: 'data-rolemenu="' + esc(m.username) + '"' }) + '</span>' : '') + UI.btn(m.username === 'mokafor' ? 'Leave' : 'Remove', { size: 'xs', kind: 'ghost', attrs: (m.username === 'mokafor' ? 'data-leave' : 'data-remove="' + esc(m.username) + '"'), disabled: !isOwner && m.role !== 'member' && m.username !== 'mokafor' }) + '</span>' : '']), { clickable: false, minWidth: '0' }) + (mem.length < g.members ? small((g.members - mem.length) + ' more members not shown in this example.') : ''), { actions: isMod ? UI.btn('Invite', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-invite' }) : '' }) : UI.notice('The member list is shown to readers of the content. Join first.', 'info'))
          + (isMod ? UI.panel('Requests and invitations', UI.table(['Kind', 'Person', 'Role', 'State', 'Expires', 'When', ''], reqs.map((r) => [UI.pill(r.kind, r.kind === 'invite' ? 'info' : 'outline'), esc(r.user) + (r.by ? ' ' + small('invited by ' + esc(r.by)) : ''), esc(r.role), UI.pill(r.state, r.state === 'pending' ? 'warn' : r.state === 'accepted' ? 'ok' : r.state === 'expired' || r.state === 'declined' ? '' : 'outline') + (r.decidedBy ? ' ' + small('by ' + esc(r.decidedBy)) : ''), esc(r.expires || ''), esc(r.when), r.state === 'pending' ? '<span class="hstack gap6" style="justify-content:flex-end">' + (r.kind === 'request' ? UI.btn('Accept', { size: 'xs', kind: 'primary', attrs: 'data-accept="' + r.id + '"' }) + UI.btn('Decline', { size: 'xs', attrs: 'data-decline="' + r.id + '"' }) : UI.btn('Withdraw', { size: 'xs', attrs: 'data-withdraw="' + r.id + '"' })) + '</span>' : r.state === 'expired' && r.kind === 'invite' ? UI.btn('Invite again', { size: 'xs', attrs: 'data-invite' }) : '']), { clickable: false, minWidth: '0', emptyTitle: 'Nothing pending', emptyText: 'Requests and invitations appear here.' }) + small('One pending request or invitation per person (409 otherwise). The workspace boundary and label are checked again when a request is accepted (422).')) : '');
      } else if (st.tab === 'posts') {
        const posts = st.posts.filter((p) => p.group === g.id);
        body = readsContent ? ((isMember ? UI.panel('New notice', UI.textarea(st.draft || '', { rows: 2, placeholder: 'A notice for the group (up to 10,000 characters). Screened at the user-input checkpoint.', attrs: 'data-draft' }) + '<div class="hstack gap6">' + UI.btn('Post', { kind: 'primary', size: 'sm', icon: 'send', attrs: 'data-post' }) + small('A guardrail block refuses the post (422 step guardrails); a redaction is stored redacted.') + '</div>') : UI.notice('Posting needs membership; public groups can be read by everyone in the workspace.', 'info'))
          + (st.postRefused ? UI.problem('Post refused by a guardrail', 'The text matched Secrets detector (an API key). Nothing was stored. 422 with step guardrails.', '8d2b4f6a1c3e4d5f7a9b1c3d5e7f9a2b') : '')
          + '<div class="vstack gap12">' + posts.map((p) => '<div class="panel groups-post"><div class="hstack"><b>' + esc(p.author) + '</b>' + small(esc(p.when)) + '<span class="grow"></span>' + UI.label(p.label, { sm: true }) + (p.state === 'hidden' ? UI.pill('hidden', 'warn') : '') + '</div>' + (p.state === 'hidden' ? '<div class="groups-tomb">Hidden by a moderator' + (isMod ? ' (<a href="#" data-openflag="' + esc(p.flag) + '">' + esc(p.flag) + '</a>). Shown to moderators only as a tombstone.' : '.') + '</div>' : '<div class="serif" style="font-size:15px;line-height:1.5">' + esc(p.body) + '</div>') + '<div class="hstack gap6" style="margin-top:6px">' + ((p.author === 'Mara Okafor' || isMod) && p.state !== 'hidden' ? UI.btn('Delete', { size: 'xs', kind: 'ghost', icon: 'trash', attrs: 'data-delpost="' + p.id + '"' }) : '') + (p.state !== 'hidden' ? UI.btn('Report', { size: 'xs', kind: 'ghost', icon: 'flag', attrs: 'data-report="' + p.id + '"' }) : '') + '</div></div>').join('') + (posts.length ? '' : UI.empty('No posts yet', 'Notices from members appear here, newest first.')) + '</div>') : UI.notice('Posts are shown to members of a private group. Join to read them.', 'info');
      } else if (st.tab === 'events') {
        const evs = st.events.filter((e) => e.group === g.id).sort((a, b) => a.date.localeCompare(b.date) || a.start.localeCompare(b.start));
        if (!st.eventSel || !evs.some((e) => e.id === st.eventSel)) st.eventSel = (evs.find((e) => e.date >= '2026-09-19' && e.state !== 'cancelled') || evs[0] || {}).id || null;
        const ev = st.events.find((e) => e.id === st.eventSel) || null;
        body = (st.cancelledNote && ev && ev.id === st.cancelledNote ? UI.notice('<b>' + esc(ev.title) + ' cancelled.</b> ' + ev.notified + ' attendees (going or maybe) were notified in the console (event.cancelled) and by email with the time and a link, never the title or the reason. Its reminders are cancelled. Audited as group.event.cancelled.', 'warn', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearcancel' })) : '')
          + (st.capacityProblem && ev && ev.id === st.capacityProblem ? UI.problem('Capacity reached', ev.title + ' takes ' + ev.capacity + ' people including guests and ' + (ev.going + ev.guests) + ' are going. Your RSVP was refused with 409 and left: 0. You can answer maybe or declined, or ask a moderator to raise the capacity.', '4f8a2c6e0b1d4a3f9c5e7b2d8a0c4e6f') : '')
          + '<div class="cols groups-cols"><div class="grow">' + calendar(st, evs, st.calYear, st.calMonth) + '</div></div>'
          + UI.panel('Events', UI.table(['Event', 'When', 'Location', 'Attendance', 'Capacity', 'State', 'Your RSVP'], evs.map((e) => ({ cells: ['<b>' + esc(e.title) + '</b>' + (e.sequence > 1 ? ' ' + small('rev ' + e.sequence) : ''), esc(when(e)), esc(e.location), '<span class="num">' + e.going + '</span> going, <span class="num">' + e.maybe + '</span> maybe' + (e.guests ? ', <span class="num">' + e.guests + '</span> guests' : '') + (e.checkedIn ? ', <span class="num">' + e.checkedIn + '</span> checked in' : ''), e.capacity ? '<span class="num">' + (e.going + e.guests) + ' of ' + e.capacity + '</span>' + ((e.going + e.guests) >= e.capacity ? ' ' + UI.pill('full', 'danger') : '') : small('unlimited'), e.state === 'cancelled' ? UI.pill('cancelled', 'danger') : UI.pill('scheduled', 'ok'), e.myRsvp ? UI.pill(e.myRsvp, e.myRsvp === 'going' ? 'ok' : e.myRsvp === 'maybe' ? 'warn' : '') : small('none')], attrs: 'data-event="' + e.id + '"', selected: e.id === st.eventSel })), { minWidth: '820px', emptyTitle: 'No events', emptyText: 'Moderators create events for the group.' }), { actions: isMod ? UI.btn('New event', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newevent' }) : '' });
        aside = '<aside class="inspector w360">' + (ev ? '<div class="hstack"><div class="eyebrow grow">Selected event</div>' + (ev.state === 'cancelled' ? UI.pill('cancelled', 'danger') : UI.label(ev.label, { sm: true })) + '</div><div class="groups-title">' + esc(ev.title) + '</div><div class="fg2">' + esc(when(ev)) + '</div>'
          + UI.kv([['Location', esc(ev.location)], ['Time zone', '<span class="mono">' + esc(ev.tz) + '</span>' + (ev.tz !== 'UTC' ? '<br>' + small('stored in UTC; a wall-clock time that occurs twice takes the earlier instant') : '')], ['Capacity', ev.capacity ? (ev.going + ev.guests) + ' of ' + ev.capacity + ' (people with guests)' : 'unlimited'], ['Guests', ev.maxGuests ? 'up to ' + ev.maxGuests + ' each' : 'none'], ['Reminders', ev.reminders.map(remText).join(', ') + ' before'], ['Attendance', ev.going + ' going, ' + ev.maybe + ' maybe, ' + ev.guests + ' guests, ' + ev.checkedIn + ' checked in'], ['Revision', 'sequence ' + ev.sequence]], 1)
          + (ev.state === 'cancelled' ? UI.notice('Cancelled: ' + esc(ev.cancelReason || 'no reason given') + '. ' + (ev.notified || 0) + ' attendees notified.', 'warn') : '<div class="eyebrow" style="margin-top:8px">Your RSVP</div>' + UI.seg([{ id: 'going', label: 'Going' }, { id: 'maybe', label: 'Maybe' }, { id: 'declined', label: 'Declined' }], ev.myRsvp || '', 'data-rsvp') + (ev.maxGuests ? UI.field('Guests', UI.select(Array.from({ length: ev.maxGuests + 1 }, (_, i) => String(i)), String(st.myGuests || 0), 'data-guests')) : ''))
          + '<div class="vstack gap6" style="margin-top:10px">' + UI.btn('Attendees', { attrs: 'data-attendees' }) + UI.btn('Reminders', { attrs: 'data-reminders' }) + (isMod && ev.state !== 'cancelled' ? UI.btn('Edit', { attrs: 'data-editevent' }) + UI.btn('Cancel event', { kind: 'danger', attrs: 'data-cancelevent' }) : '') + UI.btn('Calendar feed for this event', { kind: 'ghost', attrs: 'data-eventfeed' }) + '</div>' : UI.empty('No event selected', 'Pick one in the calendar or the list.')) + '</aside>';
      } else if (st.tab === 'feeds') {
        body = UI.notice('<b>Feed URLs are public links.</b> No session or cookie: the signature in the URL is an HMAC over the feed\'s id, tenant, owner, kind and target. The feed is rendered as you at every fetch (workspace, group and clearance). Events above CALENDAR_FEED_MAX_LABEL (internal) appear as <span class="mono">Busy (confidential)</span> without details. Revoking makes the link a 404.', 'info')
          + UI.panel('Your calendar feeds', UI.table(['Kind', 'Target', 'URL', 'Created', 'Last used', 'State', ''], st.feeds.map((f) => [UI.pill(f.kind, 'outline'), esc(f.target), '<span class="mono" style="font-size:12px;overflow-wrap:anywhere">' + esc(f.url) + '</span>', esc(f.created), esc(f.lastUsed), f.revoked ? UI.pill('revoked ' + f.revoked, 'danger') : UI.pill('active', 'ok'), f.revoked ? '' : '<span class="hstack gap6" style="justify-content:flex-end">' + UI.btn('Copy', { size: 'xs', attrs: 'data-copy="' + esc(f.url) + '"' }) + UI.btn('Revoke', { size: 'xs', kind: 'ghost', attrs: 'data-revokefeed="' + f.id + '"' }) + '</span>']), { clickable: false, minWidth: '0' }), { actions: UI.btn('New feed', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newfeed' }) })
          + small('A user feed covers the last 30 days and the next year, cancelled events as STATUS:CANCELLED. Rate-limited per address.');
      } else if (st.tab === 'cases') {
        const cs = st.cases.filter((c) => c.group === g.id);
        body = UI.panel('Cases on this group\'s content', UI.table(['Flag', 'Kind', 'Object', 'Rule', 'Severity', 'State', 'Due', ''], cs.map((c) => ['<span class="mono">' + esc(c.id) + '</span>', UI.pill(c.kind, 'outline'), '<span class="mono">' + esc(c.object) + '</span>', esc(c.rule), UI.pill(c.sev, c.sev === 'high' ? 'danger' : c.sev === 'medium' ? 'warn' : ''), UI.pill(c.state, c.state === 'open' ? 'warn' : ''), esc(c.due), '<span class="hstack gap6" style="justify-content:flex-end">' + UI.btn('Open in Flags', { size: 'xs', attrs: 'data-openflag="' + c.id + '"' }) + UI.btn('Moderation', { size: 'xs', kind: 'ghost', attrs: 'data-gomoderation' }) + '</span>']), { clickable: false, minWidth: '0', emptyTitle: 'No cases', emptyText: 'Reports and moderation checks on posts, events and the group itself appear here.' }))
          + small('Group content is moderated with three object types: group-post (hidden posts shown to nobody but moderators), group (a hidden group is closed to everyone but managers and owners) and group-event (left out of calendars, reminders not sent).');
      }

      root.innerHTML = '<style>'
        + '#main > .page > *{flex-shrink:0}'
        + '#main .groups-title{font-size:16px;font-weight:600;margin:4px 0 2px}'
        + '#main .groups-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:2px}'
        + '#main .groups-prev svg{transform:rotate(180deg)}'
        + '#main .groups-dow{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);padding:2px 4px}'
        + '#main .groups-day{min-height:64px;border:1px solid var(--line);border-radius:4px;padding:2px 4px;background:var(--panel)}'
        + '#main .groups-day.pad{border-color:transparent;background:transparent}'
        + '#main .groups-day.today{border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}'
        + '#main .groups-day .n{font-size:11px;color:var(--muted);text-align:right}'
        + '#main .groups-ev{display:block;width:100%;text-align:left;border:0;border-radius:3px;padding:1px 4px;margin-top:2px;font:inherit;font-size:11px;line-height:1.3;background:var(--accent-tint);color:var(--fg);cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'
        + '#main .groups-ev.on{outline:2px solid var(--accent)}#main .groups-ev.cancelled{background:var(--danger-bg);color:var(--danger-fg);text-decoration:line-through}'
        + '#main .groups-post .hstack{gap:8px}#main .groups-tomb{display:inline-block;padding:6px 10px;background:var(--sel);color:var(--muted);font-size:13px;border-radius:4px}'
        + '#main .inspector .kv .v{overflow-wrap:anywhere}'
        + '</style>'
        + left + '<div class="page">' + head + tabs + body
        + '<div style="margin-top:auto"><div class="eyebrow" style="margin-bottom:8px">States to design from this page</div>' + UI.states(this.states) + '</div></div>' + aside;

      // ---- events ----
      ctx.on('click', '.state-card', (e, t) => ctx.app.applyState(+t.dataset.state));
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-modeseg] [data-seg]', (e, t) => { st.mode = t.dataset.seg; st.sel = null; ctx.rerender(); });
      ctx.on('input', '[data-search]', (e, t) => { st.query = t.value; const v = t.value; ctx.rerender(); const i = ctx.$('[data-search]'); if (i) { i.focus(); i.value = v; } });
      ctx.on('click', '[data-fws]', (e, t) => menu(ctx, t, [['all', 'Any workspace'], ['Finance Ops', 'Finance Ops'], ['People Ops', 'People Ops'], ['Field Sales', 'Field Sales']], st.fws, (v) => { st.fws = v; ctx.rerender(); }));
      ctx.on('click', '[data-fvis]', (e, t) => menu(ctx, t, [['all', 'Any visibility'], ['public', 'Public'], ['private', 'Private'], ['hidden', 'Hidden']], st.fvis, (v) => { st.fvis = v; ctx.rerender(); }));
      ctx.on('click', '[data-fjoin]', (e, t) => menu(ctx, t, [['all', 'Any join mode'], ['open', 'Open'], ['request', 'Request'], ['invite', 'Invite']], st.fjoin, (v) => { st.fjoin = v; ctx.rerender(); }));
      ctx.on('click', '[data-group]', (e, t) => { st.sel = t.dataset.group; st.tab = st.tab === 'cases' ? 'overview' : st.tab; st.joinRefused = null; st.leaveProblem = false; ctx.rerender(); });
      ctx.on('click', '[data-gomoderation]', () => ctx.navigate('moderation'));
      ctx.on('click', '[data-openflag]', (e, t) => { e.preventDefault(); ctx.navigate('flags', { id: t.dataset.openflag }); });
      ctx.on('click', '[data-copy]', (e, t) => { ctx.toast('Copied: ' + esc(t.dataset.copy.slice(0, 48)) + '…'); });
      // join, leave, delete, settings
      ctx.on('click', '[data-join]', async () => {
        if (g.joinMode === 'open') { const ok = await ctx.confirm({ title: 'Join ' + g.name, tone: 'info', body: '<p style="margin:0" class="fg2">You become a member at once and can post, RSVP and read the content. The group\'s label is ' + esc(g.label) + '; your clearance covers it.</p>', ok: 'Join' }); if (!ok) return; g.role = 'member'; g.members += 1; ctx.rerender(); ctx.toast('Joined ' + esc(g.name) + ' (200, role member).', 'ok'); return; }
        if (g.joinMode === 'request') { st.requested[g.id] = { id: 'r-' + (10 + Object.keys(st.requested).length), when: 'just now' }; ctx.rerender(); ctx.toast('Request sent (202). The moderators of ' + esc(g.name) + ' were notified.', 'ok'); return; }
        st.joinRefused = g.id; ctx.rerender();
      });
      ctx.on('click', '[data-withdrawmine]', () => { delete st.requested[g.id]; ctx.rerender(); ctx.toast('Request withdrawn.'); });
      ctx.on('click', '[data-leave]', async () => { if (g.role === 'owner' && g.id === 'g-close') { st.leaveProblem = true; ctx.rerender(); return; } const ok = await ctx.confirm({ title: 'Leave ' + g.name, tag: 'closes the room', tone: 'danger', body: '<p style="margin:0" class="fg2">You stop seeing its content and events; your sockets leave the group\'s room at once. ' + (g.joinMode !== 'open' ? 'Rejoining needs ' + (g.joinMode === 'request' ? 'a new request' : 'an invitation') + '.' : '') + '</p>', ok: 'Leave' }); if (!ok) return; g.role = 'none'; g.members -= 1; st.mode = 'discover'; ctx.rerender(); ctx.toast('You left ' + esc(g.name) + '.', ''); });
      ctx.on('click', '[data-delete]', async () => { const ok = await ctx.confirm({ title: 'Delete ' + g.name, tag: 'cannot be undone', tone: 'danger', body: '<p style="margin:0" class="fg2">The group is deleted (state deleted), pending requests are cancelled and event reminders stop. Posts and events go with it. Audited as group.deleted.</p>', kv: [['Members', String(g.members)], ['Events', String(st.events.filter((e) => e.group === g.id).length)]], ok: 'Delete group' }); if (!ok) return; st.groups = st.groups.filter((x) => x.id !== g.id); st.sel = null; ctx.rerender(); ctx.toast(esc(g.name) + ' deleted.', 'warn'); });
      ctx.on('click', '[data-savesettings]', () => { const name = ctx.$('[data-sname]').value.trim(); const vis = ctx.$('[data-svis]').value, join = ctx.$('[data-sjoin]').value, label = ctx.$('[data-slabel]').value, desc = ctx.$('[data-sdesc]').value; const ceiling = g.workspace === 'Finance Ops' ? 3 : 2; const lv = { public: 1, internal: 2, confidential: 3, restricted: 4 }[label]; if (lv > ceiling) { ctx.toast('Label ' + label + ' is above the ' + esc(g.workspace) + ' ceiling: 422.', 'danger'); return; } if (lv > 3) { ctx.toast('Label restricted is above your clearance: 403.', 'danger'); return; } const raised = lv > { public: 1, internal: 2, confidential: 3, restricted: 4 }[g.label]; Object.assign(g, { name: name || g.name, visibility: vis, joinMode: join, label, description: desc }); ctx.rerender(); ctx.toast('Settings saved.' + (raised ? ' Posts and events raised to ' + label + '; everyone in the room is checked again.' : '') + ' Audited as group.updated.', 'ok'); });
      ctx.on('click', '[data-newgroup]', () => newGroupModal(ctx));
      if (st.openNew) { st.openNew = false; setTimeout(() => newGroupModal(ctx), 50); }
      // members
      ctx.on('click', '[data-rolemenu]', (e, t) => { const u = t.dataset.rolemenu; menu(ctx, t, [['owner', 'Owner'], ['moderator', 'Moderator'], ['member', 'Member']], (st.members[g.id].find((m) => m.username === u) || {}).role, (v) => { const m = st.members[g.id].find((x) => x.username === u); if (m.role === 'owner' && v !== 'owner' && st.members[g.id].filter((x) => x.role === 'owner').length === 1) { st.leaveProblem = true; ctx.rerender(); return; } m.role = v; ctx.rerender(); ctx.toast(esc(m.user) + ' is now ' + v + '. Audited as group.member.role.', 'ok'); }); });
      ctx.on('click', '[data-remove]', async (e, t) => { const m = st.members[g.id].find((x) => x.username === t.dataset.remove); const ok = await ctx.confirm({ title: 'Remove ' + m.user, tone: 'danger', body: '<p style="margin:0" class="fg2">Removed from the group at once; their sockets leave the room. They can ask to join again.</p>', ok: 'Remove' }); if (!ok) return; st.members[g.id] = st.members[g.id].filter((x) => x !== m); g.members -= 1; ctx.rerender(); ctx.toast(esc(m.user) + ' removed. Event group.member.removed.', ''); });
      ctx.on('click', '[data-invite]', () => ctx.modal({ title: 'Invite to ' + esc(g.name), body: UI.field('Person', UI.select(['Noor Rahimi (People Ops)', 'Samir Haddad (Field Sales)', 'Aisha Bello (Finance Ops)', 'Felix Brandt (Finance Ops, member already)'], 'Aisha Bello (Finance Ops)', 'data-iuser')) + UI.field('Role', UI.select(isOwner ? ['member', 'moderator', 'owner'] : ['member'], 'member', 'data-irole'), isOwner ? '' : 'Moderators invite members; owners may invite moderators and owners') + UI.notice('The invitee must be active, in ' + esc(g.workspace) + ' and cleared for ' + esc(g.label) + ' (422 step workspace otherwise). One pending invitation or request per person. Expires after 14 days.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Send invitation', { kind: 'primary', attrs: 'data-doinvite' }), onMount(m) { m.querySelector('[data-doinvite]').addEventListener('click', () => { const u = m.querySelector('[data-iuser]').value; App.closeOverlay(); if (!/Finance Ops/.test(u) && g.workspace === 'Finance Ops') { ctx.toast(esc(u.replace(/\s*\(.*\)$/, '')) + ' is not in ' + esc(g.workspace) + ': 422 step workspace.', 'danger'); return; } if (/already/.test(u)) { ctx.toast('Already a member: 409.', 'warn'); return; } if (st.requests.some((r) => r.group === g.id && r.user === u.replace(/\s*\(.*\)$/, '') && r.state === 'pending')) { ctx.toast('A pending invitation or request exists for them: 409.', 'warn'); return; } st.requests.unshift({ id: 'r-' + (20 + st.requests.length), group: g.id, kind: 'invite', user: u.replace(/\s*\(.*\)$/, ''), role: m.querySelector('[data-irole]').value, state: 'pending', expires: '3 Oct 2026', when: 'just now', by: 'Mara Okafor' }); ctx.rerender(); ctx.toast('Invitation sent (201); the invitee is notified.', 'ok'); }); } }));
      ctx.on('click', '[data-accept]', (e, t) => { const r = st.requests.find((x) => x.id === t.dataset.accept); r.state = 'accepted'; r.decidedBy = 'Mara Okafor'; g.members += 1; if (st.members[g.id]) st.members[g.id].push({ user: r.user, username: r.user.toLowerCase().replace(/^(\w)\w+\s+/, '$1'), role: r.role, joined: 'today' }); ctx.rerender(); ctx.toast(esc(r.user) + ' is now a member. Event group.member.added.', 'ok'); });
      ctx.on('click', '[data-decline]', (e, t) => { const r = st.requests.find((x) => x.id === t.dataset.decline); r.state = 'declined'; r.decidedBy = 'Mara Okafor'; ctx.rerender(); ctx.toast('Request declined.'); });
      ctx.on('click', '[data-withdraw]', (e, t) => { const r = st.requests.find((x) => x.id === t.dataset.withdraw); r.state = 'withdrawn'; ctx.rerender(); ctx.toast('Invitation withdrawn.'); });
      // posts
      ctx.on('input', '[data-draft]', (e, t) => { st.draft = t.value; });
      ctx.on('click', '[data-post]', () => { const text = (st.draft || '').trim(); if (!text) { ctx.toast('Write something first.', 'warn'); return; } if (/sk-[a-z0-9]{8,}|api[_ -]?key/i.test(text)) { st.postRefused = true; ctx.rerender(); return; } st.posts.unshift({ id: 'gp-' + (532 + st.posts.length), group: g.id, author: 'Mara Okafor', body: text, label: g.label, state: 'sent', when: 'just now' }); st.draft = ''; st.postRefused = false; ctx.rerender(); ctx.toast('Posted. Members in the room get group.post.created.', 'ok'); });
      ctx.on('click', '[data-delpost]', async (e, t) => { const p = st.posts.find((x) => x.id === t.dataset.delpost); const ok = await ctx.confirm({ title: 'Delete post', tone: 'danger', body: '<p style="margin:0" class="fg2">Removes the notice for everyone. Audited as group.post.deleted.</p>', ok: 'Delete' }); if (!ok) return; st.posts = st.posts.filter((x) => x !== p); ctx.rerender(); ctx.toast('Post deleted.'); });
      ctx.on('click', '[data-report]', (e, t) => { const p = st.posts.find((x) => x.id === t.dataset.report); ctx.modal({ title: 'Report this post', body: UI.field('Reason', UI.select(['Harassment', 'Spam', 'Sensitive data', 'Wrong or unsupported figure', 'Other'], 'Sensitive data')) + UI.field('Note', UI.textarea('', { rows: 2 })) + UI.notice('Files a report flag (type group-post) in ' + esc(g.workspace) + '\'s queue. Reporting the same post again while it is open returns the same flag.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Report', { kind: 'primary', attrs: 'data-doreport' }), onMount(m) { m.querySelector('[data-doreport]').addEventListener('click', () => { App.closeOverlay(); const id = 'F-23' + (20 + st.cases.length); st.cases.push({ id, group: g.id, kind: 'report', object: 'group-post ' + p.id, rule: 'User report', sev: 'medium', state: 'open', due: '19 Sep 18:30', label: g.label }); ctx.rerender(); ctx.toast('Reported as ' + id + '. Audited as moderation.reported.', 'ok'); }); } }); });
      // events
      ctx.on('click', '[data-event]', (e, t) => { st.eventSel = t.dataset.event; st.capacityProblem = null; ctx.rerender(); });
      ctx.on('click', '[data-cal]', (e, t) => { st.calMonth += +t.dataset.cal; if (st.calMonth < 0) { st.calMonth = 11; st.calYear -= 1; } if (st.calMonth > 11) { st.calMonth = 0; st.calYear += 1; } ctx.rerender(); });
      ctx.on('click', '[data-clearcancel]', () => { st.cancelledNote = null; ctx.rerender(); });
      ctx.on('click', '[data-rsvp] [data-seg]', (e, t) => { const ev = st.events.find((x) => x.id === st.eventSel); const r = t.dataset.seg; const guests = +((ctx.$('[data-guests]') || {}).value || 0); if (guests > ev.maxGuests) { ctx.toast('Up to ' + ev.maxGuests + ' guests: 422.', 'danger'); return; } if (r === 'going' && ev.capacity && ev.myRsvp !== 'going' && ev.going + ev.guests + 1 + guests > ev.capacity) { st.capacityProblem = ev.id; ctx.rerender(); return; } const was = ev.myRsvp; if (was === 'going') { ev.going -= 1; ev.guests -= (st.myGuests || 0); } if (was === 'maybe') ev.maybe -= 1; if (r === 'going') { ev.going += 1; ev.guests += guests; } if (r === 'maybe') ev.maybe += 1; ev.myRsvp = r; st.myGuests = guests; st.capacityProblem = null; ctx.rerender(); ctx.toast('RSVP: ' + r + (guests ? ' with ' + guests + ' guest' + (guests === 1 ? '' : 's') : '') + '. Event group.event.rsvp.', 'ok'); });
      ctx.on('change', '[data-guests]', (e, t) => { st.myGuests = +t.value; });
      ctx.on('click', '[data-attendees]', () => { const ev = st.events.find((x) => x.id === st.eventSel); const list = st.attendees[ev.id] || [['Mara Okafor', ev.myRsvp || 'none', false], ['Priya Nair', 'going', false], ['Tomasz Weber', 'going', false], ['Lena Hoffmann', 'maybe', false], ['Jonas Lindqvist', 'declined', false]]; st.attendees[ev.id] = list; ctx.drawer({ title: 'Attendees: ' + esc(ev.title), body: small(isMod ? 'Moderators see declined answers and check people in. Someone checked in without an RSVP is added as going.' : 'Readers see who is going or maybe.') + UI.table(['Person', 'RSVP', isMod ? 'Checked in' : ''], list.filter((a) => isMod || a[1] === 'going' || a[1] === 'maybe').map((a, i) => [esc(a[0]), UI.pill(a[1], a[1] === 'going' ? 'ok' : a[1] === 'maybe' ? 'warn' : ''), isMod ? UI.toggle(a[2] ? 'yes' : 'no', a[2], 'data-checkin="' + i + '"') : '']), { clickable: false, minWidth: '0' }) + '<div style="margin-top:8px">' + small((ev.going + ev.guests) + ' going including guests, ' + ev.maybe + ' maybe, ' + ev.checkedIn + ' checked in.') + '</div>', actions: UI.btn('Close', { attrs: 'data-close' }), onMount(d) { d.querySelectorAll('[data-checkin]').forEach((b) => b.addEventListener('click', () => { const a = list[+b.dataset.checkin]; a[2] = b.classList.contains('on'); ev.checkedIn += a[2] ? 1 : -1; b.querySelector('span:last-child').textContent = a[2] ? 'yes' : 'no'; if (a[2] && a[1] !== 'going') { a[1] = 'going'; ev.going += 1; } ctx.toast(esc(a[0]) + (a[2] ? ' checked in.' : ' check-in removed.'), 'ok'); })); }, onClose() { ctx.rerender(); } }); });
      ctx.on('click', '[data-reminders]', () => { const ev = st.events.find((x) => x.id === st.eventSel); const rs = st.reminders[ev.id] || []; ctx.drawer({ title: 'Reminders: ' + esc(ev.title), body: small('Each offset is a row and a calendar.reminder job at its time; the row moves scheduled → sending → sent with a compare-and-set, so a retried job never sends twice. Attendees who can still read the event are notified in the console and by email.') + UI.table(['Before', 'Fires at', 'State', { label: 'Recipients', right: true }, 'Sent'], rs.map((r) => [esc(remText(r.min)), esc(r.fire), UI.pill(r.state, r.state === 'sent' ? 'ok' : r.state === 'scheduled' ? 'info' : r.state === 'cancelled' || r.state === 'skipped' ? '' : 'warn'), '<span class="num">' + r.recipients + '</span>', esc(r.sentAt || '')]), { clickable: false, minWidth: '0', emptyTitle: 'No reminders', emptyText: 'Add offsets when editing the event.' }), actions: UI.btn('Close', { attrs: 'data-close' }) }); });
      ctx.on('click', '[data-cancelevent]', async () => { const ev = st.events.find((x) => x.id === st.eventSel); const ok = await ctx.confirm({ title: 'Cancel ' + ev.title, tag: 'notifies ' + (ev.going + ev.maybe) + ' attendees', tone: 'danger', body: '<p style="margin:0" class="fg2">Stops the reminders and notifies every attendee (going or maybe) in the console and by email with the time and a link, never the title or the reason. The event stays listed as cancelled and appears as STATUS:CANCELLED in feeds.</p>' + UI.field('Reason (kept with the event, not sent)', UI.input('', { attrs: 'data-creason' })), kv: [['Event', ev.title], ['When', when(ev)]], ok: 'Cancel event', cancel: 'Keep it' }); if (!ok) return; ev.state = 'cancelled'; ev.cancelReason = 'Cancelled by a moderator'; ev.notified = ev.going + ev.maybe; (st.reminders[ev.id] || []).forEach((r) => { if (r.state === 'scheduled') r.state = 'cancelled'; }); st.cancelledNote = ev.id; ctx.rerender(); ctx.toast(esc(ev.title) + ' cancelled; ' + ev.notified + ' attendees notified.', 'warn'); });
      ctx.on('click', '[data-editevent]', () => eventModal(ctx, g, st.events.find((x) => x.id === st.eventSel)));
      ctx.on('click', '[data-newevent]', () => eventModal(ctx, g, null));
      if (st.openNewEvent) { st.openNewEvent = false; setTimeout(() => eventModal(ctx, g, null), 50); }
      ctx.on('click', '[data-eventfeed]', () => { const ev = st.events.find((x) => x.id === st.eventSel); const f = { id: 'cf-' + (st.feeds.length + 1), kind: 'event', target: ev.title, url: 'https://ai.northwind.local/calendar/feeds/cf-' + (st.feeds.length + 1) + '/' + Math.random().toString(16).slice(2, 6) + '…' + Math.random().toString(16).slice(2, 6) + '.ics', created: 'today', lastUsed: 'never', revoked: null }; st.feeds.push(f); st.tab = 'feeds'; ctx.rerender(); ctx.toast('Feed created (201). Copy the URL into your calendar app. Audited as calendar.feed.created.', 'ok', 5000); });
      // feeds
      ctx.on('click', '[data-newfeed]', () => ctx.modal({ title: 'New calendar feed', body: UI.field('Kind', UI.select([{ value: 'user', label: 'My calendar (my groups and RSVPs)' }, { value: 'group', label: 'Group: ' + g.name }, { value: 'event', label: 'One event' }], 'group', 'data-fkind')) + UI.notice('The URL carries the signature. Anyone with it reads the feed as you, within your clearance and CALENDAR_FEED_MAX_LABEL. Revoke it if it leaks.', 'warn'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create', { kind: 'primary', attrs: 'data-dofeed' }), onMount(m) { m.querySelector('[data-dofeed]').addEventListener('click', () => { const kind = m.querySelector('[data-fkind]').value; App.closeOverlay(); const n = st.feeds.length + 1; st.feeds.push({ id: 'cf-' + n, kind, target: kind === 'user' ? 'My calendar' : kind === 'group' ? g.name : ((st.events.find((x) => x.group === g.id) || {}).title || 'Event'), url: 'https://ai.northwind.local/calendar/feeds/cf-' + n + '/' + Math.random().toString(16).slice(2, 6) + '…' + Math.random().toString(16).slice(2, 6) + '.ics', created: 'today', lastUsed: 'never', revoked: null }); ctx.rerender(); ctx.toast('Feed created (201).', 'ok'); }); } }));
      ctx.on('click', '[data-revokefeed]', async (e, t) => { const f = st.feeds.find((x) => x.id === t.dataset.revokefeed); const ok = await ctx.confirm({ title: 'Revoke feed', tone: 'danger', body: '<p style="margin:0" class="fg2">The link answers 404 from now on, the same as an unknown feed. Calendar apps using it stop updating.</p>', kv: [['Kind', f.kind], ['Target', f.target], ['Last used', f.lastUsed]], ok: 'Revoke' }); if (!ok) return; f.revoked = '19 Sep 2026'; ctx.rerender(); ctx.toast('Feed revoked. Audited as calendar.feed.revoked.', ''); });
    }
  });

  function newGroupModal(ctx) {
    const st = ctx.state;
    ctx.modal({ title: 'New group', body: '<div class="formgrid">' + UI.field('Workspace', UI.select(['Finance Ops', 'People Ops', 'Field Sales'], 'Finance Ops', 'data-gws')) + UI.field('Name', UI.input('', { attrs: 'data-gname', placeholder: 'Quarter-end reviewers' })) + UI.field('Visibility', UI.select(['public', 'private', 'hidden'], 'private', 'data-gvis')) + UI.field('Join mode', UI.select(['open', 'request', 'invite'], 'request', 'data-gjoin')) + UI.field('Label', UI.select(['public', 'internal', 'confidential', 'restricted'], 'internal', 'data-glabel'), 'At most the workspace ceiling (422) and your clearance (403)') + '</div>' + UI.field('Description', UI.textarea('', { rows: 2, attrs: 'data-gdesc' })) + UI.notice('You become the owner. Hidden groups are known only to members, invitees and managers.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create', { kind: 'primary', attrs: 'data-gcreate' }), onMount(m) { m.querySelector('[data-gcreate]').addEventListener('click', () => { const ws = m.querySelector('[data-gws]').value, name = m.querySelector('[data-gname]').value.trim(), label = m.querySelector('[data-glabel]').value; if (!name) { ctx.toast('A group needs a name.', 'warn'); return; } const lv = { public: 1, internal: 2, confidential: 3, restricted: 4 }[label]; if (lv > (ws === 'Finance Ops' ? 3 : 2)) { ctx.toast('Label ' + label + ' is above the ' + ws + ' ceiling: 422.', 'danger'); return; } if (lv > 3) { ctx.toast('Label restricted is above your clearance: 403.', 'danger'); return; } App.closeOverlay(); const id = 'g-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); st.groups.unshift({ id, name, workspace: ws, description: m.querySelector('[data-gdesc]').value, visibility: m.querySelector('[data-gvis]').value, joinMode: m.querySelector('[data-gjoin]').value, label, members: 1, role: 'owner', state: 'active', created: '19 Sep 2026' }); st.members[id] = [{ user: 'Mara Okafor', username: 'mokafor', role: 'owner', joined: '19 Sep 2026' }]; st.mode = 'mine'; st.sel = id; st.tab = 'overview'; ctx.rerender(); ctx.toast(esc(name) + ' created (201); you are its owner. Event group.created.', 'ok'); }); } });
  }

  function eventModal(ctx, g, ev) {
    const st = ctx.state; const isNew = !ev;
    const v = ev || { title: '', date: '2026-10-07', endDate: '', start: '10:00', end: '11:00', tz: 'Europe/Berlin', allDay: false, location: '', capacity: '', maxGuests: 0, reminders: [1440, 60] };
    ctx.modal({ title: isNew ? 'New event in ' + esc(g.name) : 'Edit ' + esc(v.title), cls: 'wide',
      body: '<div class="formgrid" style="--cols:3">' + UI.field('Title', UI.input(v.title, { attrs: 'data-etitle' })) + UI.field('Location', UI.input(v.location, { attrs: 'data-eloc' })) + UI.field('Time zone', UI.select(['Europe/Berlin', 'Europe/Lisbon', 'Europe/London', 'America/New_York', 'UTC'], v.tz, 'data-etz'), 'IANA name; offsets are 400') + UI.field('Date', UI.input(v.date, { type: 'date', attrs: 'data-edate' })) + UI.field('Start', UI.input(v.start, { type: 'time', attrs: 'data-estart' })) + UI.field('End', UI.input(v.end, { type: 'time', attrs: 'data-eend' })) + UI.field('Capacity', UI.input(v.capacity == null ? '' : String(v.capacity), { type: 'number', attrs: 'data-ecap', placeholder: 'unlimited' }), 'People with their guests') + UI.field('Guests per person', UI.input(String(v.maxGuests), { type: 'number', attrs: 'data-eguests' })) + UI.field('Reminders (minutes before)', UI.input(v.reminders.join(', '), { attrs: 'data-erem' }), 'Up to five, at most 28 days') + '</div>' + UI.toggle('All day', v.allDay, 'data-eallday')
        + UI.notice('Wall-clock times are stored in UTC with the zone. A time that occurs twice (the autumn clock change) takes the earlier instant; one in a spring gap moves forward by the gap. Events last at most 31 days.' + (isNew ? '' : ' A change attendees see moves the sequence; a new time or reminder list reschedules the reminders.'), 'info'),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(isNew ? 'Create event' : 'Save', { kind: 'primary', attrs: 'data-esave' }),
      onMount(m) { m.querySelector('[data-esave]').addEventListener('click', () => {
        const title = m.querySelector('[data-etitle]').value.trim(); if (!title) { ctx.toast('An event needs a title.', 'warn'); return; }
        const rem = m.querySelector('[data-erem]').value.split(',').map((x) => +x.trim()).filter((x) => x > 0); if (rem.length > 5 || rem.some((x) => x > 40320)) { ctx.toast('Up to five reminders, at most 28 days before: 400.', 'danger'); return; }
        const next = { title, location: m.querySelector('[data-eloc]').value, tz: m.querySelector('[data-etz]').value, date: m.querySelector('[data-edate]').value || v.date, start: m.querySelector('[data-estart]').value || v.start, end: m.querySelector('[data-eend]').value || v.end, capacity: +m.querySelector('[data-ecap]').value || null, maxGuests: +m.querySelector('[data-eguests]').value || 0, reminders: rem, allDay: m.querySelector('[data-eallday]').classList.contains('on') };
        App.closeOverlay();
        if (isNew) { const id = 'e-' + (10 + st.events.length); st.events.push(Object.assign({ id, group: g.id, label: g.label, state: 'scheduled', sequence: 1, going: 1, maybe: 0, guests: 0, checkedIn: 0, myRsvp: 'going' }, next)); st.reminders[id] = rem.map((r) => ({ min: r, fire: fmtDate(next.date) + ', ' + r + ' min before', state: 'scheduled', recipients: 1 })); st.eventSel = id; st.calMonth = +next.date.slice(5, 7) - 1; ctx.toast('Event created (201). Members in the room get group.event.created.', 'ok'); }
        else { const retime = next.date !== ev.date || next.start !== ev.start || next.end !== ev.end || next.reminders.join() !== ev.reminders.join(); Object.assign(ev, next); ev.sequence += 1; if (retime) st.reminders[ev.id] = rem.map((r) => ({ min: r, fire: fmtDate(ev.date) + ', ' + r + ' min before', state: 'scheduled', recipients: ev.going + ev.maybe })); ctx.toast('Event saved; sequence is now ' + ev.sequence + '.' + (retime ? ' Reminders rescheduled.' : '') + ' Attendees get group.event.updated.', 'ok'); }
        ctx.rerender();
      }); } });
  }
})();
