(function () {
  const { UI, esc } = App;

  // ---------- data ----------
  const CLIENTS = [
    { id: 'console', name: 'Exprsn-AI console', type: 'confidential, BFF', grants: 'authorization code and PKCE, refresh', scopes: 'openid chat:* context:*', status: 'active', clientId: 'c_a1c0ffee', lifetime: '10 min', refresh: '8 h, rotated on use', models: 'per profile', used: '2 min ago', pkce: true, redirects: ['https://ai.northwind.local/auth/callback', 'https://ai.northwind.local/auth/silent'], grantList: ['authorization_code', 'refresh_token'], secret: 'held in OpenBao, never shown', created: '3 Feb 2026', consent: 'first party, pre-consented' },
    { id: 'cli', name: 'exprsn CLI', type: 'public', grants: 'device authorization', phase: 'Phase 5', scopes: 'chat:write inference:invoke', status: 'planned', clientId: 'c_cli_public', lifetime: '10 min', refresh: '24 h, rotated on use', models: 'chat-default, fast', used: 'never', pkce: true, redirects: ['urn:ietf:wg:oauth:2.0:oob'], grantList: ['urn:ietf:params:oauth:grant-type:device_code', 'refresh_token'], secret: 'none, public client', created: 'planned', consent: 'user approves the device code' },
    { id: 'svc-close-bot', name: 'svc-close-bot', type: 'service account', grants: 'client credentials', scopes: 'inference:invoke:analyst', status: 'active', clientId: 'c_7f21ab90', lifetime: '10 min', refresh: 'none', models: 'analyst', used: '11 min ago', pkce: false, redirects: [], grantList: ['client_credentials'], secret: 'xs_live_9QmT4v...redacted-in-mockup', created: '19 Sep 2026', consent: 'not applicable', fresh: true },
    { id: 'ledger-notebook', name: 'Ledger Notebook', type: 'third party', grants: 'authorization code and PKCE', scopes: 'chat:read chat:write', status: 'active', clientId: 'c_3d9e77b1', lifetime: '10 min', refresh: '8 h, rotated on use', models: 'chat-default', used: 'yesterday', pkce: true, redirects: ['https://notebook.northwind.local/oauth/cb'], grantList: ['authorization_code', 'refresh_token'], secret: 'created 2 Jun 2026', created: '2 Jun 2026', consent: 'user consent on first use, 27 granted' }
  ];

  const SAML = [
    { name: 'Confluence (on-prem)', entity: 'https://wiki.northwind.local/saml', acs: 'https://wiki.northwind.local/plugins/servlet/samlconsumer', nameid: 'emailAddress', cert: 'expires 4 Mar 2027', status: 'active' },
    { name: 'Grafana', entity: 'https://grafana.northwind.local/saml/metadata', acs: 'https://grafana.northwind.local/saml/acs', nameid: 'persistent', cert: 'expires 12 Nov 2026', status: 'active' },
    { name: 'Legacy expense portal', entity: 'urn:northwind:expenses', acs: 'https://expenses.northwind.local/sso/acs', nameid: 'unspecified', cert: 'expired 1 Aug 2026', status: 'disabled' }
  ];

  const SCOPES = [
    ['openid profile email groups', 'Identity claims', 'pre-consented'], ['chat:read, chat:write', 'Own conversations', 'user consent'], ['inference:invoke[:model]', 'Direct model calls via native or OpenAI-compatible API', 'user consent'],
    ['context:read, context:write', 'Knowledge bases and documents', 'user consent'], ['images:generate', 'Image jobs', 'user consent'], ['tools:invoke, agents:run', 'Tool calls and agent runs', 'user consent, with per-call confirmation for writes'],
    ['models:read, models:manage', 'Model registry, pulls, approvals', 'admin only'], ['tools:manage, agents:manage', 'Tool, agent and skill registry', 'admin only'], ['guardrails:manage', 'Guardrail profiles', 'admin only'],
    ['training:submit, training:manage', 'Datasets and fine-tune jobs', 'admin only'], ['admin:tenant, admin:system, audit:read', 'Administration and audit', 'admin only']
  ];

  const KEYS0 = [
    { kid: 'k-2026-07', alg: 'ES256', state: 'signing', created: '14 Jul 2026', rotates: '12 Oct 2026, in 23 days' },
    { kid: 'k-2026-04', alg: 'ES256', state: 'verify only, overlap', created: '15 Apr 2026', rotates: 'removed 28 Jul 2026' }
  ];

  const UPSTREAM = [
    { name: 'AD FS, corp.northwind.local', protocol: 'SAML 2.0 (we are SP)', reach: 'on-prem, directory zone', status: 'connected', used: 'Field Sales sign-ins' },
    { name: 'Contoso Keycloak', protocol: 'OIDC (we are RP)', reach: 'on-prem, partner link', status: 'connected', used: 'Platform lab' },
    // 1.4.0: GitHub (B-1804) and AT-Protocol (B-1808) user stores in the same chain
    { name: 'GitHub, northwind-io', protocol: 'github', reach: 'github.com over the egress proxy', status: 'connected', used: '14 sign-ins this week', detail: 'allowedOrgs northwind-io, northwind-finance; scopes read:user user:email read:org; callback /federation/github/callback; organisations become groups org and teams org/team-slug' },
    { name: 'AT-Protocol accounts', protocol: 'atproto', reach: 'any PDS the service URL checks allow', status: 'connected', used: '3 bound users', detail: 'boundOnly: true (unbound DIDs are refused, auth.login.refused reason not_bound); authServers: pds.northwind.social, bsky.social; no passwords, no directory' }
  ];

  // 1.4.0 identity gaps (B-1801 to B-1805, B-1807): the tenant's sign-up and MFA policy, sign-ups, invitations, CSV imports, DID bindings
  const POLICY0 = { signup: { mode: 'approval', domains: ['northwind.local', '*.northwind.local'], requireEmailVerification: true, roles: ['member'], clearance: 'internal', workspace: 'People Ops' }, mfa: { require: 'roles', roles: ['knowledge-curator', 'flag-reviewer'], graceDays: 14, trustedDeviceDays: 30, effectiveAt: '19 Sep 2026' }, updatedBy: 'Aisha Bello', updatedAt: '19 Sep 2026, 09:14' };
  const SIGNUPS0 = [
    { userId: 'u-3101', username: 'dami.okonkwo', displayName: 'Dami Okonkwo', email: 'd.okonkwo@northwind.local', emailVerified: true, domain: 'northwind.local', state: 'pending', createdAt: '19 Sep 10:21' },
    { userId: 'u-3102', username: 'r.steiner', displayName: 'Rosa Steiner', email: 'rosa@plant.northwind.local', emailVerified: false, domain: 'plant.northwind.local', state: 'pending', createdAt: '19 Sep 13:40' },
    { userId: 'u-3098', username: 'kwame.a', displayName: 'Kwame Asante', email: 'k.asante@northwind.local', emailVerified: true, domain: 'northwind.local', state: 'approved', createdAt: '17 Sep 16:02', decidedBy: 'Aisha Bello', decidedAt: '18 Sep 08:30' },
    { userId: 'u-3095', username: 'guest77', displayName: 'Guest', email: 'guest77@northwind.local', emailVerified: false, domain: 'northwind.local', state: 'rejected', createdAt: '15 Sep 22:11', decidedBy: 'Aisha Bello', decidedAt: '16 Sep 08:02', reason: 'Not a known colleague' }
  ];
  const INVITES0 = [
    { id: 'i-41', email: 'd.okonkwo@northwind.local', workspace: 'Finance Ops', roles: ['member', 'flag-reviewer'], clearance: 'confidential', invitedBy: 'Jonas Lindqvist', state: 'pending', createdAt: '19 Sep 09:50', expiresAt: '26 Sep 2026' },
    { id: 'i-40', email: 'n.rahimi@northwind.local', workspace: 'People Ops', roles: ['member'], clearance: 'internal', invitedBy: 'Mara Okafor', state: 'accepted', createdAt: '12 Sep', expiresAt: '19 Sep 2026', acceptedBy: 'nrahimi', acceptedAt: '12 Sep 15:20' },
    { id: 'i-38', email: 'contractor@fabrikam.example', workspace: 'Field Sales', roles: ['member'], clearance: 'internal', invitedBy: 'Samir Haddad', state: 'expired', createdAt: '1 Sep', expiresAt: '8 Sep 2026' }
  ];
  const IMPORTS0 = [
    { id: 'imp-12', state: 'done', dryRun: false, rows: 42, summary: { create: 30, update: 9, unchanged: 3, conflict: 0, error: 0, applied: 39 }, by: 'Aisha Bello', at: '18 Sep 2026, 17:05' },
    { id: 'imp-13', state: 'done', dryRun: true, rows: 18, summary: { create: 12, update: 2, unchanged: 1, conflict: 2, error: 1, applied: 0 }, by: 'Mara Okafor', at: '19 Sep 2026, 11:48',
      report: [{ row: 4, kind: 'user', key: 'tweber', action: 'conflict', detail: 'account linked to another store (OpenLDAP)' }, { row: 9, kind: 'user', key: 'r.steiner', action: 'conflict', detail: 'email rosa@plant.northwind.local is used by u-3102' }, { row: 15, kind: 'mapping', key: 'cn=ops-leads', action: 'error', detail: 'role tenant-admin is not one you may grant' }, { row: 2, kind: 'membership', key: 'dokonkwo → finance-ops', action: 'create', detail: 'direct membership' }] }
  ];
  const DIDS0 = [
    { user: 'mokafor', did: 'did:plc:7iza6de2dwap2sbkpav7c6c6', handle: 'mara.northwind.social', verified: true, proof: 'profile' },
    { user: 'tweber', did: 'did:plc:ewvi7nxzyoun6zhxrhs64oiz', handle: 'tomasz.bsky.social', verified: false, proof: null, pending: '20 Sep 14:02' },
    { user: 'phaddad', did: 'did:web:samir.northwind.social', handle: 'samir.northwind.social', verified: true, proof: 'oauth' }
  ];
  // 1.6.0 (B-7101, B-7102): each workspace's MCP server, authorized by this tenant's own issuer.
  const MCP_BASE = 'https://ai.northwind.local/mcp/northwind/';
  const MCP_GROUPS = [['workflows', 'Workflows', 'published workflows, as workflow_<name>'], ['agents', 'Agents', 'agents published to the workspace, as agent_<name>'], ['knowledge', 'Knowledge', 'one search tool per published knowledge base'], ['tools', 'Registry tools', 'tools published to the workspace'], ['records', 'App records', 'list, query, count, aggregate, create, update, delete']];
  const MCP_TOOLS = [['workflow_close_checklist', 'workflows', 'read'], ['workflow_post_journal', 'workflows', 'write'], ['agent_Analyst', 'agents', 'read'], ['knowledge_finance_policies', 'knowledge', 'read'], ['jira_internal_search_issues', 'tools', 'read'], ['messages_send', 'tools', 'write'], ['records_entities', 'records', 'read'], ['records_query', 'records', 'read'], ['records_aggregate', 'records', 'read'], ['records_create', 'records', 'write'], ['records_delete', 'records', 'destructive']];
  const MCPPUBS0 = [
    { ws: 'Finance Ops', id: '01J8FINOPS0000000000000AAA', ceiling: 'confidential', enabled: true, groups: ['workflows', 'knowledge', 'records'], label: 'internal', dpop: false, updated: '2 Oct 2026, Aisha Bello' },
    { ws: 'People Ops', id: '01J8PEOPLE0000000000000BBB', ceiling: 'confidential', enabled: true, groups: ['agents', 'knowledge'], label: 'confidential', dpop: true, updated: '4 Oct 2026, Mara Okafor' },
    { ws: 'Field Sales', id: '01J8FIELDS0000000000000CCC', ceiling: 'internal', enabled: false, groups: ['workflows', 'agents', 'knowledge', 'tools', 'records'], label: 'internal', dpop: false, updated: null }
  ];
  // 1.7.0 (B-12201): the tenant's standing approvals for MCP write calls, as an identity admin sees them.
  const MCPSTANDING0 = [
    { id: 'a1', user: 'mia', ws: 'Finance Ops', tool: 'records_create', client: 'Claude', side: 'write', label: 'internal', until: 'Oct 16, 10:30', uses: 14, state: 'active' },
    { id: 'a2', user: 'noah', ws: 'Finance Ops', tool: null, client: null, side: 'destructive', label: 'internal', until: 'Oct 12, 18:00', uses: 2, state: 'active' },
    { id: 'a3', user: 'mia', ws: 'People Ops', tool: 'records_update', client: 'Claude', side: 'write', label: 'confidential', until: 'Oct 8, 09:00', uses: 31, state: 'expired' }
  ];
  const MCPCLIENTS0 = [
    { name: 'Claude', clientId: 'c_5a64c298', type: 'public', redirect: 'https://claude.ai/api/mcp/auth_callback', scopes: 'tools:invoke agents:run inference:invoke knowledge:read records:read records:write', used: 'today 10:12', created: '2 Oct 2026' },
    { name: 'MCP Inspector', clientId: 'c_0be41c77', type: 'public', redirect: 'http://localhost:6274/oauth/callback', scopes: 'records:read', used: 'never', created: '6 Oct 2026' }
  ];
  // 1.6.0 (B-7201, B-7202): a SCIM 2.0 store, pushed to by Entra ID at /scim/v2, with its tokens and recent changes
  const SCIM0 = {
    id: 'scim-entra', name: 'Entra ID provisioning', enabled: true, baseUrl: 'https://ai.northwind.local/scim/v2', users: 412, activeUsers: 398, groups: 23, groupMappings: 6, lastChangeAt: '19 Sep 2026, 13:42', signInStores: ['AD FS, corp.northwind.local'], defaultRoles: [],
    tokens: [
      { id: 'st-3', name: 'Entra ID connector', prefix: '3f9a1c0b7d21', state: 'active', createdAt: '2 Sep 2026', expiresAt: '2 Sep 2027', lastUsedAt: '2 min ago', lastUsedIp: '10.40.2.18' },
      { id: 'st-1', name: 'Okta pilot', prefix: '91be04d2c6aa', state: 'revoked', createdAt: '12 Jun 2026', expiresAt: '12 Jun 2027', lastUsedAt: '30 Jun 2026', lastUsedIp: '10.40.2.77' }
    ],
    changes: [
      { title: 'scim.user.deactivated: d.okonkwo', text: 'active false from Entra ID: 2 sessions, 1 OAuth grant, 1 API key and 1 app password ended', meta: '13:42', tone: 'danger' },
      { title: 'scim.user.access.changed: k.asante', text: 'Added to Finance Analysts: knowledge-curator, confidential, workspace Finance Ops; sessions ended', meta: '13:40', tone: 'info' },
      { title: 'scim.group.patched: Finance Analysts', text: '1 member added, 1 removed', meta: '13:40', tone: '' },
      { title: 'scim.user.created: r.steiner@northwind.local', text: 'Default roles none: waits for a group', meta: '11:05', tone: 'ok' }
    ]
  };
  const SAMPLE_CSV = 'kind,username,display_name,email,roles,clearance,workspace,provider,group\nuser,dokonkwo,Dami Okonkwo,d.okonkwo@northwind.local,member;flag-reviewer,confidential,,,\nmembership,dokonkwo,,,,,finance-ops,,\nmapping,,,,knowledge-curator,internal,,OpenLDAP,cn=kb-curators\nuser,tweber,Tomasz Weber,t.weber@northwind.local,member,internal,,,';

  const SESSIONS = [
    { user: 'Mara Okafor', signed: '09:02 today', method: 'Kerberos, passkey', client: 'Exprsn-AI console' },
    { user: 'Tomasz Wieczorek', signed: '08:41 today', method: 'LDAP password, TOTP', client: 'Exprsn-AI console' },
    { user: 'svc-close-bot', signed: 'token, 11 min ago', method: 'client credentials', client: 'svc-close-bot' },
    { user: 'Priya Natarajan', signed: 'yesterday 17:20', method: 'Kerberos', client: 'Ledger Notebook' }
  ];

  const jwks = (keys) => JSON.stringify({ keys: keys.filter((k) => !/removed/.test(k.rotates)).map((k) => ({ kty: 'EC', crv: 'P-256', use: 'sig', alg: k.alg, kid: k.kid, x: k.kid === 'k-2026-07' ? 'f83OJ3D2xF1Bg8vub9tLe1gHMzV76e8Tus9uPHvRVEU' : k.kid === 'k-2026-04' ? 'x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0' : 'WbL0aQ8XdYvPq8j2hCnJf1lyuY3fNc6h8gJ1F2pKq7c', y: k.kid === 'k-2026-07' ? 'x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0' : k.kid === 'k-2026-04' ? '4Etl6SRW2YiLUrN5vfvVHuhp7x8PxltmWWlbbM4IFyM' : 'p9c2Hn0yQ4mR7dJxK1sVb3wFzLqT8uE6aC5oN2iG4kY' })) }, null, 2);

  // 1.6.0 (B-7201, B-7202): SCIM provisioning in the user stores and federation tab.
  function scimPanel(st) {
    const sc = st.scim;
    const live = sc.tokens.filter((t) => t.state === 'active');
    const shown = st.scimShown ? UI.notice('<b>Copy the token now: it is shown once.</b> Paste it with the base URL into the provisioning settings of ' + esc(st.scimShown.name) + '.<div class="codebox mono" style="margin-top:6px;word-break:break-all" data-scimtoken>' + esc(st.scimShown.token) + '</div><div class="muted" style="font-size:12px">Expires ' + esc(st.scimShown.expiresAt) + '. We keep only its prefix and a keyed hash.</div>', 'accent', UI.btn('Copy token', { size: 'sm', attrs: 'data-scimcopy' }) + UI.btn('Done', { size: 'sm', kind: 'ghost', attrs: 'data-scimdone' })) : '';
    const deprov = st.scimDeprovisioned ? UI.notice('<b>d.okonkwo was deprovisioned by Entra ID</b> at 13:42 (active false). The account is disabled; 2 sessions, 1 OAuth grant, 1 API key and 1 app password ended within the same request. A later active true re-enables it; an administrator\'s own disable stays.', 'danger', UI.btn('Open audit', { size: 'sm', kind: 'ghost', attrs: 'data-scimaudit' })) : '';
    const tokens = UI.table(['Token', 'Prefix', 'State', 'Last used', 'Expires', ''], sc.tokens.map((t) => ['<b>' + esc(t.name) + '</b><div class="muted" style="font-size:12px">made ' + esc(t.createdAt) + '</div>', '<span class="mono">exai_scim1_' + esc(t.prefix) + '_…</span>', UI.pill(t.state, t.state === 'active' ? 'ok' : t.state === 'revoked' ? '' : 'warn'), esc(t.lastUsedAt) + (t.lastUsedIp ? '<div class="muted mono" style="font-size:12px">' + esc(t.lastUsedIp) + '</div>' : ''), esc(t.expiresAt), t.state === 'active' ? UI.btn('Revoke', { size: 'xs', kind: 'danger', attrs: 'data-scimrevoke="' + esc(t.id) + '" aria-label="Revoke ' + esc(t.name) + '"' }) : '']), { clickable: false, minWidth: '640px', emptyTitle: 'No SCIM tokens', emptyText: 'Make a token for the identity provider that provisions this store.' });
    return '<section class="panel" aria-labelledby="identity-scim-h"><div class="hstack wrap"><h2 class="eyebrow" id="identity-scim-h" style="margin:0">SCIM provisioning: ' + esc(sc.name) + '</h2>' + UI.pill(sc.enabled ? 'enabled' : 'disabled', sc.enabled ? 'ok' : '') + '<span class="right hstack gap6">' + UI.btn('Re-apply group mappings', { size: 'sm', kind: 'ghost', attrs: 'data-scimreapply' }) + UI.btn('New SCIM token', { size: 'sm', icon: 'key', kind: 'primary', attrs: 'data-scimtokennew' }) + '</span></div>'
      + '<div class="fg2" style="font-size:13px;margin:6px 0">Entra ID or Okta pushes users and groups here (SCIM 2.0, RFC 7643 and 7644): create, replace, patch, delete, filters and paging. The store takes no passwords; its users sign in through the stores it names. Group mappings with this store turn SCIM groups into roles, clearance and workspaces.</div>'
      + shown + deprov
      + UI.kv([['Base URL', '<span class="mono">' + esc(sc.baseUrl) + '</span> ' + UI.btn('Copy', { size: 'xs', kind: 'ghost', attrs: 'data-copy="' + esc(sc.baseUrl) + '" aria-label="Copy the SCIM base URL"' })], ['Users', sc.activeUsers + ' active of ' + sc.users], ['Groups', sc.groups + ', ' + sc.groupMappings + ' group mappings name them'], ['Sign in through', sc.signInStores.map(esc).join(', ') || 'none named: its users cannot sign in yet'], ['Last change', esc(sc.lastChangeAt)], ['Live tokens', String(live.length)]], 2)
      + tokens
      + '<div class="eyebrow" style="margin-top:10px">Recent SCIM changes</div>' + UI.timeline(sc.changes)
      + '</section>';
  }

  App.register({
    id: 'identity', title: 'Identity', section: 'admin', summary: 'OIDC clients, SAML providers, scopes and consent, signing keys, user stores (GitHub, AT-Protocol), sign-up and MFA policy, invitations, CSV imports, DID bindings, the MCP server (publication, self-registration)',
    commands: [
      { label: 'Invite someone', sub: 'Identity', run(app) { const s = app.stateFor('identity'); s.tab = 'policy'; s.policyView = 'invitations'; s.openInvite = true; app.render(); } },
      { label: 'Create an OIDC client', sub: 'Identity', run(app) { app.stateFor('identity').openCreate = true; app.render(); } },
      { label: 'Rotate the signing key', sub: 'Identity', run(app) { app.stateFor('identity').tab = 'keys'; app.stateFor('identity').openRotate = true; app.render(); } }
    ],
    states: [
      { title: 'After the reveal', tone: 'neutral', text: 'The secret field shows only its creation date and a rotate action.', apply(ctx) { ctx.state.tab = 'clients'; ctx.state.client = 'svc-close-bot'; ctx.state.revealed = ctx.state.revealed || {}; ctx.state.revealed['svc-close-bot'] = '19 Sep 2026, 13:51'; ctx.rerender(); } },
      { title: 'Key nearing expiry', tone: 'warn', text: '14 days before rotation a banner appears. The new key is published to JWKS before it signs.', apply(ctx) { ctx.state.tab = 'keys'; ctx.state.keyExpiring = true; ctx.rerender(); } },
      { title: 'Upstream federation', tone: 'info', text: 'Only on-prem identity providers can be added. Cloud providers are unreachable from this network.', apply(ctx) { ctx.state.tab = 'upstream'; ctx.state.openUpstream = true; ctx.rerender(); } },
      { title: 'Sign-up pending approval', tone: 'warn', text: 'With the approval mode, a new account is created disabled and identity admins get a notice. Approve activates it; reject keeps it disabled and tells the user by email.', apply(ctx) { ctx.state.tab = 'policy'; ctx.state.policyView = 'signups'; ctx.rerender(); } },
      { title: 'MFA grace restarted', tone: 'info', text: 'Widening the MFA requirement restarts the grace period: covered accounts sign in without a factor for graceDays, then enrol first. Audited with graceRestarted.', apply(ctx) { ctx.state.tab = 'policy'; ctx.state.policyView = 'policy'; ctx.state.graceRestarted = true; ctx.rerender(); } },
      { title: 'Import dry run with conflicts', tone: 'warn', text: 'A dry run plans and reports every row; conflicts (an account linked to another store, a reused address) and errors (a role the importer may not grant) change nothing.', apply(ctx) { ctx.state.tab = 'imports'; ctx.state.importSel = 'imp-13'; ctx.rerender(); } },
      { title: 'SCIM token shown once', tone: 'info', text: 'A new SCIM token is shown once, with the base URL to paste into Entra ID or Okta; afterwards only its prefix and last use are listed.', apply(ctx) { ctx.state.tab = 'upstream'; ctx.state.scimShown = { name: 'Entra ID connector', token: 'exai_scim1_5c2e9d40a1f3_Qm7wT2xK9pLr4ZcV8nB1sYdF6hJ3gA0eUiOqWtXyRkM', expiresAt: '19 Sep 2027' }; ctx.rerender(); } },
      { title: 'Deprovisioned by SCIM', tone: 'danger', text: 'Entra ID set active to false: the user is disabled and their sessions, OAuth grants, API keys and app passwords end within one request. Audited as scim.user.deactivated.', apply(ctx) { ctx.state.tab = 'upstream'; ctx.state.scimDeprovisioned = true; ctx.rerender(); } },
      { title: 'SAML metadata import', tone: 'neutral', text: 'Parsed entity ID, ACS URLs and certificate are shown for review before saving.', apply(ctx) { ctx.state.tab = 'saml'; ctx.state.openSaml = true; ctx.rerender(); } },
      // 1.6.0 (B-7101, B-7102): the MCP server.
      { title: 'MCP server published', tone: 'ok', text: 'A workspace publishes its MCP server: clients connect to its URL, sign in through this issuer and see the groups it publishes, filtered by each person\'s roles and the label.', apply(ctx) { ctx.state.tab = 'mcp'; ctx.state.mcpJust = 'Finance Ops'; ctx.rerender(); } },
      { title: 'Standing approval revoked by an admin', tone: 'warn', text: 'An identity admin sees every standing approval of the tenant (who granted it, for which client, tool, class and period, and how many calls it covered) and can revoke any; the person\'s next covered call waits for a per-call approval again. Audited mcp.server.standing.revoked with by: admin.', apply(ctx) { const st = ctx.state; st.tab = 'mcp'; st.mcpStanding = MCPSTANDING0.map((x) => Object.assign({}, x)); st.mcpStanding[1].state = 'revoked'; st.mcpStandingNote = true; ctx.rerender(); } },
      { title: 'Token for another resource', tone: 'danger', text: 'A token issued for the API or another workspace is refused with 401, and WWW-Authenticate names the protected resource metadata so the client can get the right one (RFC 8707, RFC 9728).', apply(ctx) { ctx.state.tab = 'mcp'; ctx.state.mcpRefusal = true; ctx.rerender(); } },
      { title: 'Self-registration on', tone: 'warn', text: 'With dynamic client registration on, any MCP client that reaches the issuer can register itself; each one still asks every person for consent, and only for the MCP scopes.', apply(ctx) { ctx.state.tab = 'mcp'; ctx.state.mcpDcr = true; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      st.tab = st.tab || 'clients'; st.client = st.client || 'svc-close-bot'; st.revealed = st.revealed || {}; st.keys = st.keys || KEYS0.map((k) => Object.assign({}, k)); st.clients = st.clients || CLIENTS.map((c) => Object.assign({}, c)); st.saml = st.saml || SAML.slice(); st.upstream = st.upstream || UPSTREAM.slice(); st.scim = st.scim || JSON.parse(JSON.stringify(SCIM0)); st.revoked = st.revoked || {}; st.q = st.q || '';
      if (ctx.params.client) { const c = st.clients.find((x) => x.name === ctx.params.client || x.id === ctx.params.client); if (c) { st.client = c.id; st.tab = 'clients'; } }
      if (ctx.params.tab) st.tab = ctx.params.tab;
      st.policy = st.policy || JSON.parse(JSON.stringify(POLICY0)); st.policyView = st.policyView || 'policy'; st.signups = st.signups || SIGNUPS0.map((x) => Object.assign({}, x)); st.invites = st.invites || INVITES0.map((x) => Object.assign({}, x)); st.imports = st.imports || IMPORTS0.map((x) => Object.assign({}, x)); st.dids = st.dids || DIDS0.map((x) => Object.assign({}, x)); st.signupFilter = st.signupFilter || 'pending';
      st.mcpPubs = st.mcpPubs || MCPPUBS0.map((x) => Object.assign({}, x, { groups: x.groups.slice() })); st.mcpStanding = st.mcpStanding || MCPSTANDING0.map((x) => Object.assign({}, x)); st.mcpClients = st.mcpClients || MCPCLIENTS0.slice(); if (st.mcpDcr == null) st.mcpDcr = false;
      const client = st.clients.find((c) => c.id === st.client) || st.clients[2];
      const signing = st.keys.find((k) => k.state === 'signing');

      const tabs = UI.tabs([{ id: 'clients', label: 'OIDC clients', count: st.clients.length }, { id: 'saml', label: 'SAML service providers', count: st.saml.length }, { id: 'scopes', label: 'Scopes and consent' }, { id: 'keys', label: 'Keys' }, { id: 'upstream', label: 'User stores and federation' }, { id: 'policy', label: 'Sign-up and MFA policy', count: st.signups.filter((x) => x.state === 'pending').length }, { id: 'imports', label: 'CSV imports' }, { id: 'dids', label: 'AT-Protocol accounts' }, { id: 'mcp', label: 'MCP server', count: st.mcpPubs.filter((x) => x.enabled).length }, { id: 'sessions', label: 'Sessions' }], st.tab);
      const banner = st.keyExpiring ? UI.notice('<b>Signing key ' + esc(signing.kid) + ' rotates in 13 days.</b> The next key is generated now and published to JWKS so relying parties cache it before it signs anything.', 'warn', UI.btn('Rotate now', { size: 'sm', attrs: 'data-rotatekey' })) : '';

      let body = '';
      if (st.tab === 'clients') {
        const rows = st.clients.filter((c) => !st.q || (c.name + ' ' + c.type + ' ' + c.scopes).toLowerCase().includes(st.q.toLowerCase()));
        body = '<div class="hstack wrap">' + UI.search('Search clients', 'data-q', st.q) + '<span class="muted" style="font-size:12px">Every API call carries a scoped token from this issuer. Tokens stay in the BFF; browsers hold only a session cookie.</span></div>'
          + UI.table(['Client', 'Type', 'Grants', 'Scopes', 'Status'], rows.map((c) => ({ cells: ['<b>' + esc(c.name) + '</b>', esc(c.type), esc(c.grants) + (c.phase ? ' ' + UI.pill(c.phase, 'outline') : ''), '<span class="mono">' + esc(c.scopes) + '</span>', UI.pill(c.status, c.status === 'active' ? 'ok' : c.status === 'planned' ? 'outline' : 'warn')], attrs: 'data-client="' + c.id + '"', selected: c.id === client.id })), { minWidth: '700px', emptyTitle: 'No clients match', emptyText: 'Clear the search or create a client.' })
          + '<div class="eyebrow">Signing keys, 90 day rotation</div>' + keysTable(true)
          + UI.panel('Delivered in stages', UI.kv([['Phase 1', 'Code and PKCE, client credentials, refresh rotation, LDAP'], ['Phase 4', 'Token exchange for agents, audience-bound tokens for MCP'], ['Phase 5', 'SAML IdP, Kerberos SPNEGO, device flow, DPoP, on-prem federation']], 3));
      } else if (st.tab === 'saml') {
        body = '<div class="hstack"><span class="fg2">Applications that only speak SAML get assertions from the same issuer, with the same groups and clearance claims.</span><span class="right">' + UI.btn('Import metadata', { size: 'sm', icon: 'upload', attrs: 'data-saml' }) + '</span></div>'
          + UI.table(['Service provider', 'Entity ID', 'ACS URL', 'NameID', 'Certificate', 'Status', ''], st.saml.map((s, i) => [ '<b>' + esc(s.name) + '</b>', '<span class="mono">' + esc(s.entity) + '</span>', '<span class="mono">' + esc(s.acs) + '</span>', esc(s.nameid), esc(s.cert), UI.pill(s.status, s.status === 'active' ? 'ok' : s.status === 'disabled' ? 'warn' : 'info'), s.status === 'disabled' ? UI.btn('Enable', { size: 'xs', attrs: 'data-samlenable="' + i + '"' }) : UI.btn('Download IdP metadata', { size: 'xs', kind: 'ghost', attrs: 'data-copy="idp-metadata.xml"' }) ]), { clickable: false, minWidth: '860px' })
          + UI.notice('The IdP entity ID is <span class="mono">https://ai.northwind.local/saml/idp</span>. Assertions are signed with the current signing key and expire after 5 minutes.', 'info');
      } else if (st.tab === 'scopes') {
        body = UI.table(['Scope', 'Grants', 'Consent'], SCOPES.map((s) => ['<span class="mono">' + esc(s[0]) + '</span>', esc(s[1]), esc(s[2])]), { clickable: false, minWidth: '640px' })
          + '<div class="grid2">' + UI.panel('Consent policy', UI.toggle('First-party clients are pre-consented', true, 'data-manual') + UI.toggle('Third-party clients ask on first use', true, 'data-manual') + UI.toggle('Remember consent for 90 days', true, 'data-manual') + '<div class="muted" style="font-size:12px">Effective permission is client scopes intersected with role permissions, then clearance and zone. Scopes never widen a role.</div>')
          + UI.panel('Token shape', UI.kv([['Access token', 'JWT, ES256, 10 min, audience-bound'], ['Refresh token', 'opaque, rotated on every use (RFC 9700)'], ['Agent delegation', 'token exchange with an act claim (RFC 8693)'], ['High assurance', 'PAR and DPoP, optional per client'], ['Introspection', 'RFC 7662 for opaque tokens; revocation on logout and disable']], 1)) + '</div>';
      } else if (st.tab === 'keys') {
        body = '<div class="hstack"><span class="eyebrow">Signing keys, 90 day rotation</span><span class="right hstack gap6">' + UI.btn('Copy JWKS URL', { size: 'sm', kind: 'ghost', attrs: 'data-copy="https://ai.northwind.local/.well-known/jwks.json"' }) + UI.btn('Rotate signing key', { size: 'sm', kind: 'primary', icon: 'key', attrs: 'data-rotatekey' }) + '</span></div>' + keysTable(false)
          + '<div class="grid2">' + UI.panel('JWKS preview', '<div class="fg2" style="font-size:12px">Served at <span class="mono">/.well-known/jwks.json</span>. The overlap key stays listed until every token it signed has expired.</div>' + UI.code(jwks(st.keys), 'json'))
          + UI.panel('Where keys live', UI.kv([['Store', 'OpenBao transit, never on disk in the app zone'], ['Algorithm', 'ES256 (P-256)'], ['Rotation', 'every 90 days with a 14 day overlap window'], ['Discovery', '/.well-known/openid-configuration'], ['Data keys', 'per-tenant envelope keys in the same transit mount']], 1) + '<div>' + UI.btn('Open secrets health', { size: 'sm', attrs: 'data-goplatform' }) + '</div>') + '</div>';
      } else if (st.tab === 'upstream') {
        body = '<div class="hstack"><span class="fg2">Optional federation: this issuer acts as OIDC relying party or SAML service provider to an on-prem identity provider.</span><span class="right">' + UI.btn('Add upstream provider', { size: 'sm', icon: 'plus', attrs: 'data-upstream' }) + '</span></div>'
          + UI.table(['Provider', 'Protocol', 'Reachability', 'Status', 'Used by', ''], st.upstream.map((u, i) => ['<b>' + esc(u.name) + '</b>', /^(github|atproto)$/.test(u.protocol) ? UI.pill(u.protocol, 'outline') : esc(u.protocol), esc(u.reach), UI.pill(u.status), esc(u.used), u.detail ? UI.btn('Settings', { size: 'xs', kind: 'ghost', attrs: 'data-storedetail="' + i + '"' }) : '']), { clickable: false, minWidth: '720px' })
          + UI.notice('Since 1.4.0 the chain also takes a <b>GitHub</b> store (OAuth app, allowed organisations, verified primary address only) and an <b>AT-Protocol</b> store (a bound DID signs in as its user; others are provisioned just in time with the handle as username and the DID as their only group). Both pass the service URL checks when saved and at every connection.', 'info')
          + scimPanel(st)
          + '<div class="grid2">' + UI.panel('Primary authentication', UI.kv([['Kerberos SPNEGO', 'HTTP/ai.northwind.local keytab, validated against the KDC'], ['LDAP bind', 'LDAPS to OpenLDAP; never a clear bind'], ['Second factor', 'WebAuthn passkeys and TOTP, required for admin roles'], ['Device flow', 'RFC 8628 for the CLI, Phase 5'], ['Fallback order', 'Kerberos, then password, then MFA']], 1) + '<div>' + UI.btn('Test a login', { size: 'sm', attrs: 'data-testlogin' }) + '</div>')
          + UI.panel('Air gap', UI.notice('Cloud identity providers are unreachable from this network. Only on-prem providers in the directory zone or over a partner link can be upstream.', 'info') + '<div>' + UI.btn('Open zones', { size: 'sm', kind: 'ghost', attrs: 'data-gozones' }) + '</div>') + '</div>';
      } else if (st.tab === 'policy') {
        const pol = st.policy; const pendingN = st.signups.filter((x) => x.state === 'pending').length;
        body = UI.seg([{ id: 'policy', label: 'Policy' }, { id: 'signups', label: 'Sign-ups (' + pendingN + ' pending)' }, { id: 'invitations', label: 'Invitations' }], st.policyView, 'data-policyseg');
        if (st.policyView === 'policy') {
          body += (st.graceRestarted ? UI.notice('<b>MFA requirement widened; the grace period restarted.</b> Accounts it now covers may sign in without a factor until 3 Oct 2026, then enrol first. Audited identity.mfa_policy.updated with graceRestarted.', 'info', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-gracedone' })) : '')
            + '<div class="grid2">' + UI.panel('Self-registration (B-1801, B-1802)', '<div class="formgrid">' + UI.field('Mode', UI.select([{ value: 'closed', label: 'closed (default)' }, { value: 'open', label: 'open' }, { value: 'approval', label: 'open with approval' }], pol.signup.mode, 'data-pol="signup.mode"')) + UI.field('Default workspace', UI.select(['People Ops', 'Field Sales', 'Finance Ops'], pol.signup.workspace, 'data-pol="signup.workspace"')) + UI.field('Allowed email domains', UI.textarea(pol.signup.domains.join('\n'), { rows: 2, attrs: 'data-pol="signup.domains"' }), 'One per line; *.example.com covers subdomains; empty allows any. Up to 200.') + UI.field('Default roles', '<div class="hstack wrap gap6">' + ['member', 'flag-reviewer', 'knowledge-curator'].map((r) => UI.check(r, pol.signup.roles.indexOf(r) >= 0, 'data-polrole="' + r + '"')).join('') + '</div>', 'Only these three roles may be granted at sign-up.') + UI.field('Default clearance', UI.select(['public', 'internal', 'confidential'], pol.signup.clearance, 'data-pol="signup.clearance"'), 'At most yours.') + '</div>' + UI.toggle('Require a verified email address for local accounts', pol.signup.requireEmailVerification, 'data-polverify') + '<div class="muted" style="font-size:12px">Also covers other local accounts with an unproven address; accounts created by an admin, imported or from an invitation count as proven. Public: <span class="mono">POST /api/auth/register</span>, throttled per address and per email.</div>')
            + UI.panel('Second factor policy and trusted devices (B-1803)', '<div class="formgrid">' + UI.field('Require a second factor', UI.select([{ value: 'off', label: 'off (only roles that always need one)' }, { value: 'all', label: 'everyone' }, { value: 'roles', label: 'listed roles' }], pol.mfa.require, 'data-pol="mfa.require"')) + UI.field('Grace period, days', UI.input(pol.mfa.graceDays, { type: 'number', attrs: 'data-pol="mfa.graceDays" min="0" max="90"' }), 'After the requirement last widened, or the account\'s creation if later.') + UI.field('Roles', '<div class="hstack wrap gap6">' + ['member', 'knowledge-curator', 'flag-reviewer', 'connection-admin'].map((r) => UI.check(r, pol.mfa.roles.indexOf(r) >= 0, 'data-polmfarole="' + r + '"' + (pol.mfa.require !== 'roles' ? ' disabled' : ''))).join('') + '</div>', 'Admin roles always need one; these are added to them.') + UI.field('Trusted device period, days', UI.input(pol.mfa.trustedDeviceDays, { type: 'number', attrs: 'data-pol="mfa.trustedDeviceDays" min="0" max="90"' }), '0 to 90. 0 allows no trusted devices; shortening it ends older trust at once.') + '</div>' + UI.kv([['Effective', esc(pol.mfa.effectiveAt)], ['Last change', esc(pol.updatedBy) + ', ' + esc(pol.updatedAt)], ['Email codes', 'allowed as the second factor for admin roles (Sprint 28 decision; docs/security.md known gap)']], 1)) + '</div>'
            + '<div class="hstack wrap"><span class="muted grow" style="font-size:12px">Saving audits identity.signup_policy.updated and identity.mfa_policy.updated. Upstream (OIDC, SAML, GitHub, AT-Protocol) and Kerberos sign-ins follow the same MFA policy.</span>' + UI.btn('Save policy', { kind: 'primary', size: 'sm', attrs: 'data-savepolicy' }) + '</div>';
        } else if (st.policyView === 'signups') {
          const list = st.signups.filter((x) => st.signupFilter === 'all' || x.state === st.signupFilter);
          body += '<div class="toolbar">' + UI.seg([{ id: 'pending', label: 'Pending' }, { id: 'approved', label: 'Approved' }, { id: 'rejected', label: 'Rejected' }, { id: 'all', label: 'All' }], st.signupFilter, 'data-signupseg') + '<span class="muted right" style="font-size:12px">' + list.length + ' sign-ups</span></div>'
            + UI.table(['Username', 'Name', 'Email', 'Domain', 'State', 'Signed up', 'Decided', { label: '', right: true }], list.map((x) => ['<span class="mono">' + esc(x.username) + '</span>', esc(x.displayName), '<span class="mono">' + esc(x.email) + '</span> ' + (x.emailVerified ? UI.pill('verified', 'ok') : UI.pill('unverified', 'warn')), esc(x.domain), UI.pill(x.state, x.state === 'pending' ? 'warn' : x.state === 'approved' ? 'ok' : 'danger'), esc(x.createdAt), x.decidedBy ? esc(x.decidedBy) + ', ' + esc(x.decidedAt) + (x.reason ? '<div class="muted" style="font-size:12px">' + esc(x.reason) + '</div>' : '') : '', x.state === 'pending' ? '<span class="hstack gap6" style="justify-content:flex-end">' + UI.btn('Approve', { size: 'xs', kind: 'primary', attrs: 'data-approve="' + x.userId + '"' }) + UI.btn('Reject', { size: 'xs', attrs: 'data-reject="' + x.userId + '"' }) + '</span>' : '']), { clickable: false, minWidth: '900px', emptyTitle: 'No sign-ups here', emptyText: 'Sign-ups appear when the mode is open or approval.' })
            + '<div class="muted" style="font-size:12px">Approval activates the account; rejection keeps it disabled (409 once decided). The user is told by email. Audited user.signup.approved or user.signup.rejected.</div>';
        } else {
          body += '<div class="hstack"><span class="fg2">Workspace admins with <span class="mono">members:invite</span> invite people with roles they may grant and a clearance at most theirs. Tenant admins see every invitation; other inviters their own.</span><span class="right">' + UI.btn('Invite someone', { size: 'sm', icon: 'plus', kind: 'primary', attrs: 'data-invite' }) + '</span></div>'
            + UI.table(['Email', 'Workspace', 'Roles', 'Clearance', 'Invited by', 'State', 'Expires', { label: '', right: true }], st.invites.map((x) => ['<span class="mono">' + esc(x.email) + '</span>', esc(x.workspace), '<span class="mono">' + esc(x.roles.join(' ')) + '</span>', UI.label(x.clearance, { sm: true }), esc(x.invitedBy), UI.pill(x.state, x.state === 'pending' ? 'info' : x.state === 'accepted' ? 'ok' : x.state === 'revoked' ? 'danger' : 'warn') + (x.acceptedBy ? '<div class="muted" style="font-size:12px">as ' + esc(x.acceptedBy) + ', ' + esc(x.acceptedAt) + '</div>' : ''), esc(x.expiresAt), x.state === 'pending' ? UI.btn('Withdraw', { size: 'xs', kind: 'ghost', attrs: 'data-withdraw="' + x.id + '"' }) : '']), { clickable: false, minWidth: '900px' })
            + '<div class="muted" style="font-size:12px">Links are <span class="mono">#/signin?invitation=&lt;token&gt;</span>, valid for 7 days, stored as SHA-256. A new invitation replaces a pending one for the same address and workspace. Needs SMTP (409 without).</div>';
        }
      } else if (st.tab === 'imports') {
        const sel = st.imports.find((x) => x.id === st.importSel) || null;
        body = '<div class="hstack"><span class="fg2">CSV imports of users, memberships and group mappings (B-1805). The file is sealed with the tenant key and run as a job under your roles and clearance; a dry run plans and reports, changing nothing.</span><span class="right">' + UI.btn('Import CSV', { size: 'sm', icon: 'upload', kind: 'primary', attrs: 'data-import' }) + '</span></div>'
          + UI.table(['Import', 'State', 'Mode', 'Rows', 'Create', 'Update', 'Unchanged', 'Conflicts', 'Errors', 'Applied', 'By'], st.imports.map((x) => ({ cells: ['<span class="mono">' + esc(x.id) + '</span>', UI.pill(x.state, x.state === 'done' ? 'ok' : x.state === 'failed' ? 'danger' : 'info'), x.dryRun ? UI.pill('dry run', 'outline') : 'applied', String(x.rows), String(x.summary.create), String(x.summary.update), String(x.summary.unchanged), x.summary.conflict ? '<span style="color:var(--warn-fg)">' + x.summary.conflict + '</span>' : '0', x.summary.error ? '<span style="color:var(--danger-fg)">' + x.summary.error + '</span>' : '0', String(x.summary.applied), esc(x.by) + '<div class="muted" style="font-size:12px">' + esc(x.at) + '</div>'], attrs: 'data-import-row="' + x.id + '"', selected: sel && sel.id === x.id })), { minWidth: '900px' })
          + (sel && sel.report ? UI.panel('Report for ' + sel.id + (sel.dryRun ? ' (dry run, nothing changed)' : ''), UI.table(['Row', 'Kind', 'Key', 'Action', 'Detail'], sel.report.map((r) => [String(r.row), esc(r.kind), '<span class="mono">' + esc(r.key) + '</span>', UI.pill(r.action, r.action === 'conflict' ? 'warn' : r.action === 'error' ? 'danger' : r.action === 'create' ? 'ok' : 'info'), esc(r.detail)]), { clickable: false, minWidth: '0', cls: 'bare' }) + '<div class="hstack wrap"><span class="muted grow" style="font-size:12px">Fix the conflicting rows and run again, or apply: accepted rows are written (accounts, then mappings, then memberships) and the conflicts skipped.</span>' + UI.btn('Apply accepted rows', { size: 'sm', kind: 'primary', attrs: 'data-applyimport' }) + '</div>') : sel ? UI.notice('Import ' + esc(sel.id) + ' applied ' + sel.summary.applied + ' rows with no conflicts. Each change was audited with via: import.', 'ok') : '')
          + UI.panel('File format', UI.code(SAMPLE_CSV, 'csv') + '<div class="muted" style="font-size:12px">Header row; columns in any order; unknown columns refused. <span class="mono">kind=user</span> creates a local account (roles separated by ;) or updates one; <span class="mono">membership</span> adds a direct membership (workspace by slug or id); <span class="mono">mapping</span> adds or changes a group mapping (one role; provider empty for any). At most 5 MB and 10,000 rows.</div>');
      } else if (st.tab === 'dids') {
        body = '<div class="hstack"><span class="fg2">Users bind their own AT-Protocol DID in Settings (a profile challenge or the OAuth flow). Bound DIDs sign in as their user through the <span class="mono">atproto</span> store.</span><span class="right hstack gap6">' + UI.btn('Check an account', { size: 'sm', attrs: 'data-checkaccount' }) + UI.btn('Open AT-Protocol', { size: 'sm', kind: 'ghost', attrs: 'data-goatproto' }) + '</span></div>'
          + UI.table(['User', 'DID', 'Handle', 'State', 'Proof', { label: '', right: true }], st.dids.map((d) => ['<span class="mono">' + esc(d.user) + '</span>', '<span class="mono" style="overflow-wrap:anywhere">' + esc(d.did) + '</span>', '<span class="mono">' + esc(d.handle) + '</span>', d.verified ? UI.pill('verified', 'ok') : UI.pill('challenge pending', 'warn') + '<div class="muted" style="font-size:12px">expires ' + esc(d.pending) + '</div>', d.proof ? UI.pill(d.proof, 'outline') : '', UI.btn('Remove binding', { size: 'xs', kind: 'ghost', attrs: 'data-rmdid="' + esc(d.user) + '"' })]), { clickable: false, minWidth: '760px', emptyTitle: 'No bindings', emptyText: 'Users bind a DID from Settings.' })
          + '<div class="muted" style="font-size:12px">Removing a binding is audited atproto.did.removed (204). Handles are checked both ways: the DNS or well-known record must give the DID, and the DID document must name the handle back.</div>';
      } else if (st.tab === 'mcp') {
        body = mcpBody();
      } else {
        const rows = SESSIONS.filter((s) => !st.revoked[s.user]);
        body = '<div class="eyebrow">Active sessions, all tenants</div>' + UI.table(['User', 'Signed in', 'Method', 'Client', ''], rows.map((s) => ['<b>' + esc(s.user) + '</b>', esc(s.signed), esc(s.method), esc(s.client), UI.btn('Revoke', { size: 'xs', attrs: 'data-revoke="' + esc(s.user) + '"' })]), { clickable: false, minWidth: '560px', emptyTitle: 'No active sessions', emptyText: 'Sessions appear when someone signs in or a service account requests a token.' })
          + '<div class="muted" style="font-size:12px">Revocation also invalidates refresh tokens. Users disabled by directory sync lose their sessions within one sync interval.</div><div>' + UI.btn('Open tenant sessions', { size: 'sm', kind: 'ghost', attrs: 'data-gotenants' }) + '</div>';
      }

      function keysTable(compact) {
        return UI.table(['Key ID', 'Algorithm', 'State', 'Created', 'Rotates'], st.keys.map((k) => ['<span class="mono">' + esc(k.kid) + '</span>', esc(k.alg), UI.pill(k.state, k.state === 'signing' ? 'ok' : k.state === 'next, published' ? 'info' : 'outline'), esc(k.created), esc(k.rotates) + (st.keyExpiring && k.state === 'signing' ? ' ' + UI.pill('13 days', 'warn') : '')]), { clickable: false, minWidth: compact ? '520px' : '600px' });
      }

      // ----- inspector -----
      const revealedAt = st.revealed[client.id];
      const secretBlock = client.grantList.indexOf('client_credentials') >= 0 || client.type.indexOf('third') >= 0 || client.id === 'console'
        ? (client.id === 'console' ? UI.kv([['Client secret', esc(client.secret)]], 1)
          : (client.fresh && !revealedAt)
            ? '<div class="id-secret"><div class="hstack"><b>Secret shown once</b>' + UI.pill('copy now', 'warn') + '</div><div class="mono" style="overflow-wrap:anywhere">' + esc(client.secret) + '</div><div class="muted" style="font-size:12px">Copy it now. It cannot be shown again, only rotated.</div><div class="hstack gap6">' + UI.btn('Copy secret', { size: 'sm', kind: 'primary', attrs: 'data-copysecret' }) + UI.btn('Rotate secret', { size: 'sm', attrs: 'data-rotatesecret' }) + '</div></div>'
            : UI.kv([['Client secret', 'created ' + esc(revealedAt || client.secret.replace('created ', '')) + '<div style="margin-top:6px">' + UI.btn('Rotate secret', { size: 'sm', attrs: 'data-rotatesecret' }) + '</div>']], 1))
        : UI.kv([['Client secret', 'none, public client with PKCE']], 1);
      const insp = '<div class="eyebrow">' + esc(client.type) + '</div><div style="font-size:15px;font-weight:600">' + esc(client.name) + ' ' + UI.pill(client.status, client.status === 'active' ? 'ok' : 'outline') + '</div>'
        + UI.kv([['Client ID', '<span class="mono">' + esc(client.clientId) + '</span>'], ['Access token lifetime', esc(client.lifetime)], ['Refresh', esc(client.refresh)], ['Allowed models', esc(client.models)], ['Last used', esc(client.used)], ['Consent', esc(client.consent)]], 2)
        + '<div class="field"><span class="fl">Redirect URIs</span>' + (client.redirects.length ? client.redirects.map((r) => '<div class="mono" style="overflow-wrap:anywhere">' + esc(r) + '</div>').join('') : '<div class="muted">none</div>') + '</div>'
        + '<div class="field"><span class="fl">Grant types</span><div class="hstack wrap gap4">' + client.grantList.map((g) => UI.pill(g, 'outline')).join('') + '</div></div>'
        + '<div class="field"><span class="fl">Scopes</span><div class="mono">' + esc(client.scopes) + '</div></div>'
        + UI.toggle(client.grantList.indexOf('client_credentials') >= 0 ? 'PKCE not applicable to client credentials' : 'PKCE required', client.pkce, 'data-pkce' + (client.grantList.indexOf('client_credentials') >= 0 ? ' data-manual data-na style="opacity:.6"' : ''))
        + secretBlock
        + '<div class="divider"></div><div class="vstack gap6">' + UI.btn('Edit client', { size: 'sm', icon: 'edit', attrs: 'data-edit' }) + (client.type === 'service account' ? UI.btn('Open service account', { size: 'sm', kind: 'ghost', attrs: 'data-gotenants' }) : '') + (client.status === 'active' ? UI.btn('Disable client', { size: 'sm', kind: 'danger', attrs: 'data-disable' }) : '') + '</div>';

      root.innerHTML = '<style>.main > .page > .tablewrap,.main > .page > .panel,.main > .page > .notice{flex-shrink:0}.id-secret{display:flex;flex-direction:column;gap:6px;padding:10px 12px;border:1px solid var(--warn-fg);border-radius:6px;background:var(--warn-bg)}.id-secret .muted{color:var(--warn-fg)}</style>'
        + '<div class="page">' + UI.pagehead('Identity and SSO', 'The identity service is the only token issuer', UI.btn('Test a login', { attrs: 'data-testlogin' }) + UI.btn('Create client', { kind: 'primary', icon: 'plus', attrs: 'data-create' }))
        + banner + tabs + body
        + '</div>'
        + '<aside class="inspector">' + insp + '</aside>';

      // ----- modals -----
      function rotateKey() {
        ctx.confirm({ title: 'Rotate signing key', tag: 'affects every client', tone: 'info', body: '<p style="margin:0" class="fg2">Generates a new ES256 key in OpenBao transit and publishes it to JWKS. It starts signing after the 14 day overlap; the current key stays listed for verification until then.</p>', kv: [['Current', esc(signing.kid)], ['New', 'k-2026-09'], ['Overlap', '14 days']], ok: 'Rotate' }).then((ok) => {
          if (!ok) return;
          st.keys = [{ kid: 'k-2026-09', alg: 'ES256', state: 'next, published', created: '19 Sep 2026', rotates: 'signs from 3 Oct 2026' }].concat(st.keys.map((k) => k.state === 'signing' ? Object.assign({}, k, { rotates: '3 Oct 2026, in 14 days' }) : k));
          st.keyExpiring = false; st.tab = 'keys'; ctx.rerender(); ctx.toast('k-2026-09 published to JWKS. It signs from 3 Oct; k-2026-07 verifies until then.', 'ok', 5000);
        });
      }
      function createClient() {
        ctx.modal({ title: 'Create client', cls: 'wide',
          body: '<div class="formgrid">' + UI.field('Name', UI.input('', { attrs: 'data-cname placeholder="Treasury dashboard"' })) + UI.field('Type', UI.select(['confidential, BFF', 'public', 'service account', 'third party'], 'third party', 'data-ctype')) + UI.field('Redirect URIs', UI.textarea('https://treasury.northwind.local/oauth/cb', { rows: 2, attrs: 'data-credir' }), 'One per line. Exact match; wildcards are refused.') + UI.field('Scopes', UI.input('chat:read chat:write', { attrs: 'data-cscopes' })) + '<div class="span2 hstack wrap gap12">' + UI.check('authorization code', true, 'data-g="authorization_code"') + UI.check('refresh token', true, 'data-g="refresh_token"') + UI.check('client credentials', false, 'data-g="client_credentials"') + UI.check('device authorization', false, 'data-g="device_code"') + UI.check('token exchange', false, 'data-g="token_exchange"') + '</div>' + '<div class="span2">' + UI.toggle('PKCE required', true, 'data-cpkce') + '</div></div>' + UI.notice('The client secret is shown once after creation. Third-party clients ask users for consent on first use.', 'info'),
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create client', { kind: 'primary', attrs: 'data-cgo' }),
          onMount(m) { m.querySelector('[data-cgo]').addEventListener('click', () => { const name = m.querySelector('[data-cname]').value.trim() || 'New client'; const type = m.querySelector('[data-ctype]').value; const grants = Array.prototype.slice.call(m.querySelectorAll('[data-g]:checked')).map((i) => i.dataset.g); const id = 'c-' + Date.now(); App.closeOverlay(); st.clients.push({ id: id, name: name, type: type, grants: grants.join(', ').replace(/_/g, ' '), scopes: m.querySelector('[data-cscopes]').value, status: 'active', clientId: 'c_' + Math.random().toString(16).slice(2, 10), lifetime: '10 min', refresh: grants.indexOf('refresh_token') >= 0 ? '8 h, rotated on use' : 'none', models: 'per profile', used: 'never', pkce: m.querySelector('[data-cpkce]').classList.contains('on'), redirects: m.querySelector('[data-credir]').value.split('\n').map((s) => s.trim()).filter(Boolean), grantList: grants, secret: 'xs_live_' + Math.random().toString(36).slice(2, 12) + '...shown-once', created: '19 Sep 2026', consent: type === 'third party' ? 'user consent on first use' : 'pre-consented', fresh: type !== 'public' }); st.client = id; st.tab = 'clients'; ctx.rerender(); ctx.toast('Client ' + esc(name) + ' created. Copy the secret now.', 'ok', 5000); }); }
        });
      }
      function samlImport() {
        ctx.modal({ title: 'SAML metadata import', cls: 'wide',
          body: UI.field('Service provider metadata XML', UI.textarea('<EntityDescriptor entityID="https://treasury.northwind.local/saml">\n  <SPSSODescriptor>\n    <AssertionConsumerService Location="https://treasury.northwind.local/saml/acs" index="0"/>\n    <KeyDescriptor use="signing"><X509Certificate>MIIC...</X509Certificate></KeyDescriptor>\n  </SPSSODescriptor>\n</EntityDescriptor>', { rows: 6, attrs: 'data-xml' }), 'Paste the file contents or upload it. Nothing is fetched over the network.') + '<div id="saml-parsed"></div>',
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Parse', { attrs: 'data-parse' }) + UI.btn('Save provider', { kind: 'primary', attrs: 'data-samlsave disabled' }),
          onMount(m) {
            const parse = () => { m.querySelector('#saml-parsed').innerHTML = '<div class="eyebrow">Parsed, review before saving</div>' + UI.kv([['Entity ID', '<span class="mono">https://treasury.northwind.local/saml</span>'], ['ACS URLs', '<span class="mono">https://treasury.northwind.local/saml/acs</span> (index 0, POST)'], ['Certificate', 'CN=treasury.northwind.local, expires 2 Feb 2028, SHA-256 3f:9a:…:c1'], ['NameID format', 'emailAddress'], ['Signed requests', 'yes'], ['Issuer', 'Exprsn-CA']], 2); m.querySelector('[data-samlsave]').removeAttribute('disabled'); };
            m.querySelector('[data-parse]').addEventListener('click', parse); parse();
            m.querySelector('[data-samlsave]').addEventListener('click', () => { App.closeOverlay(); st.saml.push({ name: 'Treasury', entity: 'https://treasury.northwind.local/saml', acs: 'https://treasury.northwind.local/saml/acs', nameid: 'emailAddress', cert: 'expires 2 Feb 2028', status: 'active' }); st.tab = 'saml'; ctx.rerender(); ctx.toast('Service provider Treasury saved. Assertions include groups and clearance.', 'ok'); });
          }
        });
      }
      function upstreamModal() {
        ctx.modal({ title: 'Add upstream provider',
          body: UI.notice('<b>Only on-prem identity providers can be added.</b> Cloud providers are unreachable from this network, so their discovery documents cannot be fetched.', 'info') + '<div class="formgrid">' + UI.field('Name', UI.input('', { placeholder: 'AD FS, plant.northwind.local' })) + UI.field('Protocol', UI.select(['OIDC (we are RP)', 'SAML 2.0 (we are SP)'], 'OIDC (we are RP)')) + UI.field('Issuer or metadata', UI.input('https://', { attrs: 'data-uiss' }), 'Must resolve inside the directory zone or over a partner link.') + UI.field('Maps to tenant', UI.select(['Northwind', 'Contoso Freight'], 'Northwind')) + '</div><div id="up-check"></div>',
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Check reachability', { attrs: 'data-ucheck' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-usave disabled' }),
          onMount(m) {
            m.querySelector('[data-ucheck]').addEventListener('click', () => { const v = m.querySelector('[data-uiss]').value; const cloud = /login\.microsoftonline|okta\.com|accounts\.google|auth0\.com|^https:\/\/$/.test(v); m.querySelector('#up-check').innerHTML = cloud ? UI.notice('<b>Unreachable.</b> ' + esc(v || 'that address') + ' is outside every zone. Add an on-prem provider instead.', 'danger') : UI.notice('Reachable from the directory zone. Discovery document fetched through the egress proxy.', 'ok'); if (!cloud) m.querySelector('[data-usave]').removeAttribute('disabled'); });
            m.querySelector('[data-usave]').addEventListener('click', () => { App.closeOverlay(); st.upstream.push({ name: m.querySelector('[data-uiss]').value.replace(/^https?:\/\//, ''), protocol: 'OIDC (we are RP)', reach: 'on-prem, directory zone', status: 'connected', used: 'not yet' }); ctx.rerender(); ctx.toast('Upstream provider saved.', 'ok'); });
          }
        });
      }
      function testLogin() {
        ctx.modal({ title: 'Test a login',
          body: '<div class="formgrid">' + UI.field('Method', UI.select(['Kerberos SPNEGO', 'LDAP password and TOTP', 'Device code'], 'Kerberos SPNEGO', 'data-tm')) + UI.field('As', UI.input('mokafor')) + '</div><div id="tl-out">' + UI.timeline([{ title: 'Ready', text: 'Runs the real flow against the identity service with a test audience. No session is created.' }]) + '</div>',
          actions: UI.btn('Close', { attrs: 'data-close' }) + UI.btn('Run', { kind: 'primary', attrs: 'data-tlrun' }),
          onMount(m) { m.querySelector('[data-tlrun]').addEventListener('click', () => { const method = m.querySelector('[data-tm]').value; const steps = method === 'Kerberos SPNEGO' ? [['401 Negotiate returned', 'ok'], ['SPNEGO token for HTTP/ai.northwind.local validated against the KDC', 'ok'], ['LDAP lookup: 6 groups, clearance confidential', 'ok'], ['Authorization code issued, PKCE verified', 'ok'], ['ID, access and refresh tokens minted with k-2026-07', 'ok']] : method === 'Device code' ? [['Device code WDJB-MJHT issued, expires in 15 min', 'ok'], ['Waiting for the user to approve at /device', 'warn']] : [['LDAPS bind as uid=mokafor,ou=people,ou=northwind', 'ok'], ['TOTP verified, skew 0 steps', 'ok'], ['LDAP lookup: 6 groups, clearance confidential', 'ok'], ['Tokens minted with k-2026-07', 'ok']]; let i = 0; const out = m.querySelector('#tl-out'); const draw = () => { out.innerHTML = UI.timeline(steps.slice(0, i + 1).map((s, j) => ({ title: s[0], tone: j < i ? s[1] : (j === steps.length - 1 ? s[1] : 'accent'), meta: j < i || j === steps.length - 1 ? (j * 38 + 42) + ' ms' : 'running' }))); if (++i < steps.length) setTimeout(draw, 350); }; draw(); }); }
        });
      }
      if (st.openCreate) { st.openCreate = false; setTimeout(createClient, 50); }
      if (st.openRotate) { st.openRotate = false; setTimeout(rotateKey, 50); }
      if (st.openSaml) { st.openSaml = false; setTimeout(samlImport, 50); }
      if (st.openUpstream) { st.openUpstream = false; setTimeout(upstreamModal, 50); }

      function inviteModal() {
        ctx.modal({ title: 'Invite someone', body: '<div class="formgrid">' + UI.field('Email', UI.input('', { type: 'email', placeholder: 'name@northwind.local', attrs: 'data-iemail' })) + UI.field('Workspace', UI.select(['Finance Ops', 'People Ops', 'Field Sales'], 'Finance Ops', 'data-iws'), 'Without tenant:manage, one you belong to.') + UI.field('Clearance', UI.select(['public', 'internal', 'confidential'], 'internal', 'data-iclr'), 'At most yours (confidential).') + '<div class="field"><span class="fl">Roles you may grant</span><div class="hstack wrap gap6">' + ['member', 'flag-reviewer', 'knowledge-curator', 'model-admin', 'tool-admin'].map((r) => UI.check(r, r === 'member', 'data-irole="' + r + '"')).join('') + UI.check('tenant-admin', false, 'disabled title="Only a system admin grants this role"') + '</div></div></div>' + UI.notice('The link goes by email, is valid for 7 days and creates a local account with these roles in the workspace; the address counts as verified. Audited user.invitation.created.', 'info'),
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Send invitation', { kind: 'primary', attrs: 'data-isend' }),
          onMount(m) { m.querySelector('[data-isend]').addEventListener('click', () => { const email = m.querySelector('[data-iemail]').value.trim(); if (!/@/.test(email)) { ctx.toast('Enter an email address.', 'warn'); return; } const roles = Array.prototype.slice.call(m.querySelectorAll('[data-irole]:checked')).map((c) => c.dataset.irole); App.closeOverlay(); st.invites = st.invites.filter((x) => !(x.state === 'pending' && x.email === email && x.workspace === m.querySelector('[data-iws]').value)); st.invites.unshift({ id: 'i-' + (42 + st.invites.length), email, workspace: m.querySelector('[data-iws]').value, roles: roles.length ? roles : ['member'], clearance: m.querySelector('[data-iclr]').value, invitedBy: 'Mara Okafor', state: 'pending', createdAt: 'just now', expiresAt: '26 Sep 2026' }); st.policyView = 'invitations'; ctx.rerender(); ctx.toast('Invitation sent to ' + esc(email) + ' (201). A pending one for the same address and workspace was replaced.', 'ok', 4500); }); } });
      }
      function importModal() {
        ctx.modal({ title: 'Import users, memberships and mappings', cls: 'wide', body: UI.field('CSV', UI.textarea(SAMPLE_CSV, { rows: 7, attrs: 'data-csv' }), 'text/csv, at most 5 MB and 10,000 rows. Stored sealed; dropped once the job has run.') + '<div class="hstack wrap gap12">' + UI.check('Dry run: plan and report, change nothing', true, 'data-dry') + UI.check('Send invitation links to new accounts instead of passwords nobody knows', false, 'data-sendinv') + '</div>' + UI.notice('Every row is checked like the API: roles you may grant, clearance at or below yours, accounts whose roles you may manage. The job runs under your current roles.', 'info'),
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Queue import', { kind: 'primary', attrs: 'data-igo' }),
          onMount(m) { m.querySelector('[data-igo]').addEventListener('click', () => { const dry = m.querySelector('[data-dry]').checked; const rows = m.querySelector('[data-csv]').value.split('\n').filter(Boolean).length - 1; const id = 'imp-' + (14 + st.imports.length - 2); App.closeOverlay(); const imp = { id, state: 'running', dryRun: dry, rows: Math.max(0, rows), summary: { create: 0, update: 0, unchanged: 0, conflict: 0, error: 0, applied: 0 }, by: 'Mara Okafor', at: 'just now' }; st.imports.unshift(imp); st.importSel = id; ctx.rerender(); ctx.toast('Import ' + id + ' queued (202). Audited ' + (dry ? 'user.import.dry_run' : 'user.import.requested') + '.', 'ok'); setTimeout(() => { imp.state = 'done'; imp.summary = { create: Math.max(0, rows - 2), update: 1, unchanged: 0, conflict: 1, error: 0, applied: dry ? 0 : Math.max(0, rows - 1) }; imp.report = [{ row: 2, kind: 'user', key: 'dokonkwo', action: 'create', detail: 'local account; invitation link' + (m.querySelector('[data-sendinv]').checked ? ' sent' : ' not sent') }, { row: 3, kind: 'membership', key: 'dokonkwo → finance-ops', action: 'create', detail: 'direct membership' }, { row: 4, kind: 'mapping', key: 'cn=kb-curators', action: 'create', detail: 'knowledge-curator, clearance internal, provider OpenLDAP' }, { row: 5, kind: 'user', key: 'tweber', action: 'conflict', detail: 'account linked to another store (OpenLDAP)' }]; if (ctx.app.state.route === 'identity' && !document.getElementById('overlay')) ctx.rerender(); }, 1400); }); } });
      }
      function checkAccountModal() {
        ctx.modal({ title: 'Check an AT-Protocol account', body: UI.field('Handle or DID', UI.input('tomasz.bsky.social', { attrs: 'data-chk' })) + '<div id="chk-out">' + UI.timeline([{ title: 'Ready', text: 'Resolves the account step by step: handle, DID, document, PDS, its authorization server and that server\'s metadata. Nothing is signed in. Audited atproto.account.checked.' }]) + '</div>',
          actions: UI.btn('Close', { attrs: 'data-close' }) + UI.btn('Check', { kind: 'primary', attrs: 'data-chkrun' }),
          onMount(m) { m.querySelector('[data-chkrun]').addEventListener('click', () => { const v = m.querySelector('[data-chk]').value.trim(); const refused = /169\.254|metadata|localhost|^10\./.test(v); const steps = refused ? [['Handle ' + v, 'resolves to a link-local address: refused, never fetched (422 step handle, reason refused)', 'danger']] : [['Handle ' + (v || 'tomasz.bsky.social'), 'DNS TXT _atproto → did:plc:ewvi7nxzyoun6zhxrhs64oiz', 'ok'], ['DID document', 'plc.directory; alsoKnownAs names the handle back', 'ok'], ['PDS', 'https://morel.us-east.host.bsky.network; protected-resource metadata names one authorization server', 'ok'], ['Authorization server', 'https://bsky.social: PAR, S256, ES256 DPoP, private_key_jwt, scope atproto', 'ok'], ['Metadata', 'issuer matches; client metadata document reachable', 'ok']]; let i = 0; const out = m.querySelector('#chk-out'); const draw = () => { out.innerHTML = UI.timeline(steps.slice(0, i + 1).map((s, j) => ({ title: s[0], text: s[1], tone: j < i || j === steps.length - 1 ? s[2] : 'accent', meta: (j * 41 + 38) + ' ms' }))); if (++i < steps.length) setTimeout(draw, 320); }; draw(); }); } });
      }
      if (st.openInvite) { st.openInvite = false; setTimeout(inviteModal, 50); }

      // ----- handlers (B-3413 additions) -----
      ctx.on('click', '[data-policyseg]', (e, t) => { st.policyView = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-signupseg]', (e, t) => { st.signupFilter = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-gracedone]', () => { st.graceRestarted = false; ctx.rerender(); });
      ctx.on('change', '[data-pol]', (e, t) => { const path = t.dataset.pol.split('.'); const v = t.tagName === 'TEXTAREA' ? t.value.split('\n').map((x) => x.trim()).filter(Boolean) : t.type === 'number' ? +t.value : t.value; const prev = st.policy[path[0]][path[1]]; st.policy[path[0]][path[1]] = v; if (path[1] === 'require' && (v === 'all' || (v === 'roles' && prev === 'off'))) st.policyWidened = true; st.policyDirty = true; if (path[1] === 'require') ctx.rerender(); });
      ctx.on('change', '[data-polrole]', (e, t) => { const r = t.dataset.polrole; const a = st.policy.signup.roles; if (t.checked && a.indexOf(r) < 0) a.push(r); if (!t.checked) st.policy.signup.roles = a.filter((x) => x !== r); st.policyDirty = true; });
      ctx.on('change', '[data-polmfarole]', (e, t) => { const r = t.dataset.polmfarole; const a = st.policy.mfa.roles; if (t.checked && a.indexOf(r) < 0) { a.push(r); st.policyWidened = true; } if (!t.checked) st.policy.mfa.roles = a.filter((x) => x !== r); st.policyDirty = true; });
      ctx.on('click', '[data-polverify]', () => { st.policy.signup.requireEmailVerification = !st.policy.signup.requireEmailVerification; st.policyDirty = true; });
      ctx.on('click', '[data-savepolicy]', async () => { const pol = st.policy; const ok = await ctx.confirm({ title: 'Save the identity policy', tag: st.policyWidened ? 'restarts the grace period' : 'tenant-wide', tone: 'info', body: '<p class="fg2" style="margin:0">Applies to every sign-in from now on' + (st.policyWidened ? '. The MFA requirement widened, so covered accounts get ' + pol.mfa.graceDays + ' days to enrol a factor.' : '.') + '</p>', kv: [['Sign-up', esc(pol.signup.mode) + ', ' + (pol.signup.domains.length ? esc(pol.signup.domains.join(', ')) : 'any domain')], ['Verified email', pol.signup.requireEmailVerification ? 'required' : 'not required'], ['Second factor', esc(pol.mfa.require) + (pol.mfa.require === 'roles' ? ': ' + esc(pol.mfa.roles.join(', ')) : '')], ['Trusted devices', pol.mfa.trustedDeviceDays + ' days']], ok: 'Save' }); if (!ok) return; pol.updatedBy = 'Mara Okafor'; pol.updatedAt = 'just now'; pol.mfa.effectiveAt = 'now'; st.graceRestarted = !!st.policyWidened; st.policyWidened = false; st.policyDirty = false; ctx.rerender(); ctx.toast('Policy saved. Audited identity.signup_policy.updated and identity.mfa_policy.updated' + (st.graceRestarted ? ' (graceRestarted).' : '.'), 'ok', 4500); });
      ctx.on('click', '[data-approve]', async (e, t) => { const x = st.signups.find((s) => s.userId === t.dataset.approve); const ok = await ctx.confirm({ title: 'Approve ' + x.displayName, tone: 'info', body: '<p class="fg2" style="margin:0">Activates the account with the policy\'s default roles, clearance and workspace. The user is told by email.</p>', kv: [['Username', esc(x.username)], ['Email', esc(x.email) + (x.emailVerified ? ', verified' : ', not verified yet')], ['Roles', esc(st.policy.signup.roles.join(', '))], ['Workspace', esc(st.policy.signup.workspace)]], ok: 'Approve' }); if (!ok) return; x.state = 'approved'; x.decidedBy = 'Mara Okafor'; x.decidedAt = 'just now'; ctx.rerender(); ctx.toast(esc(x.username) + ' approved and active. Audited user.signup.approved.', 'ok'); });
      ctx.on('click', '[data-reject]', (e, t) => { const x = st.signups.find((s) => s.userId === t.dataset.reject); ctx.modal({ title: 'Reject ' + esc(x.displayName), body: UI.field('Reason', UI.select(['Not a known colleague', 'Duplicate of an existing account', 'Wrong tenant', 'Other'], 'Not a known colleague', 'data-rreason'), 'Sent to the user by email and kept with the sign-up.') + UI.notice('The account stays disabled. A later approval is refused (409 once decided).', 'warn'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Reject', { kind: 'danger', attrs: 'data-rgo' }), onMount(m) { m.querySelector('[data-rgo]').addEventListener('click', () => { x.state = 'rejected'; x.decidedBy = 'Mara Okafor'; x.decidedAt = 'just now'; x.reason = m.querySelector('[data-rreason]').value; App.closeOverlay(); ctx.rerender(); ctx.toast(esc(x.username) + ' rejected. Audited user.signup.rejected.', 'warn'); }); } }); });
      ctx.on('click', '[data-invite]', inviteModal);
      ctx.on('click', '[data-withdraw]', async (e, t) => { const x = st.invites.find((i) => i.id === t.dataset.withdraw); const ok = await ctx.confirm({ title: 'Withdraw the invitation?', tone: 'danger', body: '<p class="fg2" style="margin:0">The link stops working at once (204). Audited user.invitation.revoked.</p>', kv: [['Email', esc(x.email)], ['Workspace', esc(x.workspace)]], ok: 'Withdraw' }); if (!ok) return; x.state = 'revoked'; x.revokedAt = 'just now'; ctx.rerender(); ctx.toast('Invitation withdrawn.', 'ok'); });
      ctx.on('click', '[data-import]', importModal);
      ctx.on('click', 'tr[data-import-row]', (e, t) => { if (e.target.closest('button')) return; st.importSel = t.dataset.importRow; ctx.rerender(); });
      ctx.on('click', '[data-applyimport]', async () => { const sel = st.imports.find((x) => x.id === st.importSel); const ok = await ctx.confirm({ title: 'Apply the accepted rows of ' + sel.id, tone: 'info', body: '<p class="fg2" style="margin:0">Accounts first, then mappings, then memberships; each change audited with via: import. Conflicts and errors are skipped.</p>', kv: [['Create', String(sel.summary.create)], ['Update', String(sel.summary.update)], ['Skipped', String(sel.summary.conflict + sel.summary.error)]], ok: 'Apply' }); if (!ok) return; const id = 'imp-' + (14 + st.imports.length - 2); st.imports.unshift({ id, state: 'done', dryRun: false, rows: sel.rows, summary: Object.assign({}, sel.summary, { applied: sel.summary.create + sel.summary.update }), by: 'Mara Okafor', at: 'just now' }); st.importSel = id; ctx.rerender(); ctx.toast('Import ' + id + ' applied ' + (sel.summary.create + sel.summary.update) + ' rows. Audited user.import.completed.', 'ok', 4500); });
      ctx.on('click', '[data-checkaccount]', checkAccountModal);
      ctx.on('click', '[data-goatproto]', () => ctx.navigate('atproto', { tab: 'accounts' }));
      ctx.on('click', '[data-rmdid]', async (e, t) => { const d = st.dids.find((x) => x.user === t.dataset.rmdid); const ok = await ctx.confirm({ title: 'Remove the binding for ' + d.user + '?', tone: 'danger', body: '<p class="fg2" style="margin:0">The DID no longer signs in as this user. With boundOnly on the store, it is refused entirely.</p>', kv: [['DID', '<span class="mono">' + esc(d.did) + '</span>'], ['Handle', esc(d.handle)]], ok: 'Remove binding' }); if (!ok) return; st.dids = st.dids.filter((x) => x.user !== d.user); ctx.rerender(); ctx.toast('Binding removed (204). Audited atproto.did.removed.', 'ok'); });
      ctx.on('click', '[data-storedetail]', (e, t) => { const u = st.upstream[+t.dataset.storedetail]; ctx.drawer({ title: esc(u.name) + ' ' + UI.pill(u.protocol, 'outline'), body: UI.kv([['Protocol', esc(u.protocol)], ['Reachability', esc(u.reach)], ['Status', UI.pill(u.status)], ['Used by', esc(u.used)]], 1) + '<div class="eyebrow">Configuration</div><div class="fg2" style="font-size:13px">' + esc(u.detail) + '</div>' + (u.protocol === 'github' ? UI.notice('Register the OAuth app\'s callback as <span class="mono">https://ai.northwind.local/federation/github/callback</span>. The client secret is a secret reference; the access token is never stored.', 'info') : UI.notice('Sign-in is an OAuth flow with PAR, PKCE and DPoP against the account\'s authorization server; the PDS confirms the session for the same DID. Tokens are revoked afterwards, never stored.', 'info')) + '<div class="hstack gap6">' + UI.btn('Test connection', { size: 'sm', attrs: 'data-storetest' }) + UI.btn('Disable store', { size: 'sm', kind: 'danger', attrs: 'data-close data-storedisable' }) + '</div>', actions: UI.btn('Close', { kind: 'ghost', attrs: 'data-close' }), onMount(d) { d.querySelector('[data-storetest]').addEventListener('click', () => ctx.toast(u.protocol === 'github' ? 'Addresses pass the service URL checks; API reachable; client secret reference readable.' : 'Client metadata address reachable; client assertion key present.', 'ok', 4000)); d.querySelector('[data-storedisable]').addEventListener('click', () => { u.status = 'disabled'; ctx.rerender(); ctx.toast(esc(u.name) + ' disabled. It leaves the sign-in options at once.', 'warn'); }); } }); });

      // ----- the MCP server (B-7101, B-7102) -----
      function mcpBody() {
        const just = st.mcpJust ? st.mcpPubs.find((x) => x.ws === st.mcpJust) : null;
        return UI.notice('Each workspace can publish an MCP server. Clients such as Claude Desktop connect to its URL, sign in through this tenant\'s issuer (OAuth 2.1, PKCE) and act as the person who signed in: their roles, the token\'s scopes, the label the workspace publishes at, guardrails and approvals apply to every call, and every call is audited <span class="mono">mcp.server.call</span>.', 'info')
          + (just ? UI.notice('<b>' + esc(just.ws) + ' publishes its MCP server.</b> Connection URL <span class="mono" style="overflow-wrap:anywhere">' + esc(MCP_BASE + just.id) + '</span>. People find it under Settings, MCP access.', 'ok', UI.btn('Copy URL', { size: 'sm', attrs: 'data-mcpcopy="' + esc(just.id) + '"' })) : '')
          + (st.mcpRefusal ? UI.panel('A token for another resource', '<div class="fg2" style="font-size:12px">The client sent a token issued for the API (audience <span class="mono">https://ai.northwind.local/api</span>) to the Finance Ops server. Each server accepts only tokens whose audience is its own URL (RFC 8707), and the API refuses tokens for an MCP server.</div>'
            + UI.code('HTTP/1.1 401 Unauthorized\nWWW-Authenticate: Bearer resource_metadata="https://ai.northwind.local/.well-known/oauth-protected-resource/mcp/northwind/' + MCPPUBS0[0].id + '",\n  scope="tools:invoke agents:run inference:invoke knowledge:read records:read records:write",\n  error="invalid_token", error_description="The access token is invalid, expired, revoked, or was issued for another resource."', 'http'), { actions: UI.btn('Dismiss', { size: 'xs', kind: 'ghost', attrs: 'data-mcpdismiss' }) }) : '')
          + UI.panel('Self-registration', UI.toggle('Let MCP clients register themselves (RFC 7591)', st.mcpDcr, 'data-mcpdcr data-manual')
            + UI.kv([['Registration endpoint', st.mcpDcr ? '<span class="mono">https://ai.northwind.local/oauth/register</span>' : '<span class="muted">not offered</span>'], ['Issuer', '<span class="mono">https://ai.northwind.local</span>'], ['Scopes a client may ask for', '<span class="mono">tools:invoke agents:run inference:invoke knowledge:read records:read records:write offline_access</span>']], 1)
            + (st.mcpDcr ? UI.notice('<b>Self-registration is on.</b> Any MCP client that reaches the issuer can register a public client with HTTPS or loopback redirect URIs. Each one asks every person for consent before it acts, and only for the MCP scopes.', 'warn') : '<span class="muted" style="font-size:12px">Off: an identity admin creates the client for each MCP client under OIDC clients, with its redirect URI.</span>'))
          + '<div class="eyebrow">Workspaces</div>'
          + UI.table(['Workspace', 'MCP server', 'Tool groups', 'Label', 'DPoP', 'Connection URL', { label: '', right: true }], st.mcpPubs.map((x) => ({ cells: ['<b>' + esc(x.ws) + '</b><div class="muted" style="font-size:11px">ceiling ' + esc(x.ceiling) + '</div>', x.enabled ? UI.pill('published', 'ok') : UI.pill('off', 'outline'), esc(x.groups.map((g) => (MCP_GROUPS.find((y) => y[0] === g) || [g, g])[1]).join(', ')), UI.label(x.label, { sm: true }), x.dpop ? UI.pill('required', 'info') : '<span class="muted">optional</span>', x.enabled ? '<span class="mono" style="font-size:12px;overflow-wrap:anywhere">' + esc(MCP_BASE + x.id) + '</span>' : '<span class="muted">not published</span>', '<span class="hstack gap6" style="justify-content:flex-end">' + (x.enabled ? UI.iconbtn('copy', 'Copy the URL of ' + x.ws, { attrs: 'data-mcpcopy="' + esc(x.id) + '"', cls: 'sm ghost' }) : '') + UI.btn('Edit', { size: 'sm', attrs: 'data-mcpedit="' + esc(x.id) + '" aria-label="Edit the MCP server of ' + esc(x.ws) + '"' }) + '</span>'], attrs: 'data-mcprow="' + esc(x.id) + '"' })), { minWidth: '760px', clickable: false })
          + '<div class="muted" style="font-size:12px">Clients find the issuer from the server\'s protected resource metadata (RFC 9728) and ask for a token for that server\'s URL (RFC 8707). Tokens for the API or another workspace are refused with 401.</div>'
          + UI.panel('Clients that registered themselves', UI.table(['Client', 'Client ID', 'Redirect URI', 'Scopes', 'Last used', { label: '', right: true }], st.mcpClients.map((c) => [esc(c.name) + ' ' + UI.pill(c.type, 'outline'), '<span class="mono">' + esc(c.clientId) + '</span>', '<span class="mono" style="font-size:12px;overflow-wrap:anywhere">' + esc(c.redirect) + '</span>', '<span class="mono" style="font-size:12px;overflow-wrap:anywhere">' + esc(c.scopes) + '</span>', esc(c.used), '<span class="hstack" style="justify-content:flex-end">' + UI.btn('Open', { size: 'xs', kind: 'ghost', attrs: 'data-mcpclient="' + esc(c.clientId) + '" aria-label="Open ' + esc(c.name) + ' under OIDC clients"' }) + '</span>']), { minWidth: '640px', clickable: false, emptyTitle: 'No self-registered clients', emptyText: 'With self-registration on, MCP clients that register themselves are listed here.' })
            + '<span class="muted" style="font-size:12px">Disable or remove them under OIDC clients; disabling ends their tokens at once.</span>')
          // B-12201: standing approvals across the tenant.
          + UI.panel('Standing approvals', '<div class="fg2" style="font-size:12px">People grant them under Settings, MCP access: a client may run write calls as them without a per-call approval, for one tool or every write tool of a server, for up to 30 days. Guardrail holds still wait. Revoke any of them here.</div>'
            + (st.mcpStandingNote ? UI.notice('<b>Revoked.</b> noah\'s next write call from any client in Finance Ops waits for his approval again. Audited mcp.server.standing.revoked (by: admin).', 'warn') : '')
            + UI.table(['Person', 'Covers', 'Client', 'Up to', 'Until', 'Covered calls', { label: '', right: true }], st.mcpStanding.map((a) => ({ cells: [esc(a.user), (a.tool ? '<span class="mono">' + esc(a.tool) + '</span>' : '<b>Every write tool</b>') + '<div class="muted" style="font-size:11px">' + esc(a.ws) + '</div>', a.client ? esc(a.client) : '<span class="muted">any client</span>', UI.pill(a.side, a.side === 'write' ? 'warn' : 'danger') + ' ' + UI.label(a.label, { sm: true }), esc(a.until), String(a.uses), '<span class="hstack" style="justify-content:flex-end">' + (a.state === 'active' ? UI.btn('Revoke', { size: 'sm', kind: 'ghost', attrs: 'data-standrevokeadmin="' + a.id + '" aria-label="Revoke the standing approval of ' + esc(a.user) + ' for ' + esc(a.tool || 'every write tool') + '"' }) : UI.pill(a.state, a.state === 'revoked' ? 'danger' : 'outline')) + '</span>'] })), { minWidth: '0', cls: 'bare', clickable: false, emptyTitle: 'No standing approvals', emptyText: 'Every write call from an MCP client waits for the person\'s approval.' }));
      }
      function mcpEdit(id) {
        const x = st.mcpPubs.find((p) => p.id === id);
        const draft = { enabled: x.enabled, groups: x.groups.slice(), label: x.label, dpop: x.dpop };
        const labels = ['public', 'internal', 'confidential', 'restricted'].filter((l) => ['public', 'internal', 'confidential', 'restricted'].indexOf(l) <= ['public', 'internal', 'confidential', 'restricted'].indexOf(x.ceiling));
        const preview = () => '<div class="eyebrow">What it publishes, as you would see it</div>' + UI.table(['Tool', 'Group', 'Side effect'], MCP_TOOLS.filter((t) => draft.groups.indexOf(t[1]) >= 0).map((t) => ['<span class="mono">' + esc(t[0]) + '</span>', esc(t[1]), UI.pill(t[2] === 'read' ? 'read-only' : t[2], t[2] === 'read' ? 'ok' : t[2] === 'write' ? 'warn' : 'danger')]), { minWidth: '0', clickable: false, emptyTitle: 'No groups', emptyText: 'Pick at least one tool group.' }) + '<span class="muted" style="font-size:12px">Write and destructive calls wait until the person approves them in Settings, MCP access.</span>';
        ctx.drawer({
          title: 'MCP server of ' + esc(x.ws),
          body: UI.toggle('Published', draft.enabled, 'data-pubon') + UI.kv([['Connection URL', '<span class="mono" style="overflow-wrap:anywhere">' + esc(MCP_BASE + x.id) + '</span>'], ['Protected resource metadata', '<span class="mono" style="overflow-wrap:anywhere;font-size:12px">https://ai.northwind.local/.well-known/oauth-protected-resource/mcp/northwind/' + esc(x.id) + '</span>']], 1)
            + '<fieldset class="vstack gap6" style="border:0;padding:0;margin:0"><legend class="eyebrow">Tool groups</legend>' + MCP_GROUPS.map((g) => UI.check(g[1] + ': ' + g[2], draft.groups.indexOf(g[0]) >= 0, 'data-pubgroup="' + g[0] + '"')).join('') + '</fieldset>'
            + UI.field('Highest label a call carries', UI.select(labels, draft.label, 'data-publabel'), 'Each person\'s clearance is lowered to it for calls here; the workspace ceiling is ' + esc(x.ceiling) + '.')
            + UI.toggle('Require DPoP-bound tokens', draft.dpop, 'data-pubdpop') + '<div data-pubpreview>' + preview() + '</div>',
          actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-pubsave' }),
          onMount(m) {
            m.querySelectorAll('[data-pubgroup]').forEach((el) => el.addEventListener('change', () => { const g = el.dataset.pubgroup; draft.groups = draft.groups.filter((y) => y !== g).concat(el.checked ? [g] : []); m.querySelector('[data-pubpreview]').innerHTML = preview(); }));
            m.querySelector('[data-pubsave]').addEventListener('click', async () => {
              draft.enabled = m.querySelector('[data-pubon]').getAttribute('aria-checked') === 'true';
              draft.label = m.querySelector('[data-publabel]').value;
              draft.dpop = m.querySelector('[data-pubdpop]').getAttribute('aria-checked') === 'true';
              App.closeOverlay();
              const turning = draft.enabled !== x.enabled;
              const ok = await ctx.confirm({ title: (turning ? (draft.enabled ? 'Publish' : 'Stop publishing') : 'Save') + ' the MCP server of ' + esc(x.ws) + '?', tone: turning && !draft.enabled ? 'danger' : 'info', body: '<p class="fg2" style="margin:0">' + (turning && !draft.enabled ? 'Clients get 404 at its URL from the next request; tokens issued for it stop being useful.' : 'Clients see the groups below on their next tools/list.') + '</p>', kv: [['Groups', esc(draft.groups.join(', ') || 'none')], ['Label', esc(draft.label)], ['DPoP', draft.dpop ? 'required' : 'optional']], ok: turning ? (draft.enabled ? 'Publish' : 'Stop publishing') : 'Save' });
              if (!ok) return;
              Object.assign(x, draft, { updated: 'just now, Mara Okafor' });
              if (draft.enabled && turning) st.mcpJust = x.ws;
              ctx.rerender(); ctx.toast(esc(x.ws) + (turning ? (draft.enabled ? ' publishes its MCP server.' : ' no longer publishes its MCP server.') : ': MCP server saved.') + ' Audited mcp.server.' + (turning ? (draft.enabled ? 'published' : 'unpublished') : 'publication.updated') + '.', turning && !draft.enabled ? 'warn' : 'ok');
            });
          }
        });
      }

      // ----- handlers -----
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-mcpedit]', (e, t) => mcpEdit(t.dataset.mcpedit));
      ctx.on('click', '[data-mcpcopy]', (e, t) => { const url = MCP_BASE + t.dataset.mcpcopy; if (navigator.clipboard) navigator.clipboard.writeText(url).then(() => ctx.toast('Copied.', 'ok'), () => ctx.toast('Copy failed; select the URL instead.', 'warn')); else ctx.toast('Copy failed; select the URL instead.', 'warn'); });
      ctx.on('click', '[data-mcpdismiss]', () => { st.mcpRefusal = false; ctx.rerender(); });
      ctx.on('click', '[data-standrevokeadmin]', async (e, t) => {
        const a = st.mcpStanding.find((x) => x.id === t.dataset.standrevokeadmin);
        const ok = await ctx.confirm({ title: 'Revoke ' + esc(a.user) + '\'s standing approval?', tone: 'danger', body: '<div class="fg2">' + esc(a.user) + '\'s next ' + esc(a.tool || 'write') + ' call from ' + esc(a.client || 'any client') + ' in ' + esc(a.ws) + ' waits for a per-call approval again. The approval stays listed for 30 days with the ' + a.uses + ' calls it covered.</div>', ok: 'Revoke' });
        if (!ok) return; a.state = 'revoked'; st.mcpStandingNote = true; ctx.rerender(); ctx.toast('Standing approval revoked. Audited mcp.server.standing.revoked.', 'ok');
      });
      ctx.on('click', '[data-mcpclient]', (e, t) => { st.tab = 'clients'; ctx.rerender(); ctx.toast('Self-registered clients are listed with the others; ' + esc(t.dataset.mcpclient) + ' is a public client with PKCE.'); });
      ctx.on('click', '[data-mcpdcr]', async () => {
        const on = !st.mcpDcr;
        const ok = await ctx.confirm({ title: (on ? 'Let' : 'Stop letting') + ' MCP clients register themselves?', tone: on ? 'warn' : 'info', body: '<p class="fg2" style="margin:0">' + (on ? 'The discovery document names <span class="mono">/oauth/register</span>. Any client that reaches the issuer can register a public client; each one asks every person for consent, and only for the MCP scopes.' : 'Registration answers 404. Clients that registered before keep working until you disable them under OIDC clients.') + '</p>', ok: on ? 'Turn on' : 'Turn off' });
        if (!ok) return;
        st.mcpDcr = on; ctx.rerender(); ctx.toast('Self-registration ' + (on ? 'on' : 'off') + '. Audited mcp.server.settings.updated.', on ? 'warn' : 'ok');
      });
      ctx.on('click', 'tr[data-client]', (e, t) => { st.client = t.dataset.client; ctx.rerender(); });
      ctx.on('input', '[data-q]', (e, t) => { st.q = t.value; const v = t.value; ctx.rerender(); const i = ctx.$('[data-q]'); if (i) { i.focus(); i.setSelectionRange(v.length, v.length); } });
      ctx.on('click', '[data-create]', createClient);
      ctx.on('click', '[data-rotatekey]', rotateKey);
      ctx.on('click', '[data-saml]', samlImport);
      ctx.on('click', '[data-upstream]', upstreamModal);
      // ----- SCIM (1.6.0, B-7201) -----
      ctx.on('click', '[data-scimtokennew]', () => ctx.modal({
        title: 'New SCIM token',
        body: '<div class="formgrid">' + UI.field('Name', UI.input('Entra ID connector', { attrs: 'data-scimname aria-label="Token name"' }), 'Who uses it, so the list says which provider it is.') + UI.field('Expires after', UI.select(['30 days', '90 days', '365 days'], '365 days', 'data-scimdays aria-label="Expires after"'), 'At most IDENTITY_SCIM_TOKEN_MAX_DAYS (365) on this server.') + '</div>' + UI.notice('The token is shown once. It reads and writes this store\'s users and groups only; holders of identity:manage revoke it here.', 'info'),
        actions: UI.btn('Cancel', { kind: 'ghost', attrs: 'data-close' }) + UI.btn('Make token', { kind: 'primary', attrs: 'data-close data-scimmake' }),
        onMount(m) { m.querySelector('[data-scimmake]').addEventListener('click', () => { const name = m.querySelector('[data-scimname]').value.trim() || 'SCIM token'; const days = m.querySelector('[data-scimdays]').value; st.scim.tokens.unshift({ id: 'st-' + Date.now(), name, prefix: '5c2e9d40a1f3', state: 'active', createdAt: '19 Sep 2026', expiresAt: days === '30 days' ? '19 Oct 2026' : days === '90 days' ? '18 Dec 2026' : '19 Sep 2027', lastUsedAt: 'never', lastUsedIp: null }); st.scimShown = { name, token: 'exai_scim1_5c2e9d40a1f3_Qm7wT2xK9pLr4ZcV8nB1sYdF6hJ3gA0eUiOqWtXyRkM', expiresAt: st.scim.tokens[0].expiresAt }; ctx.rerender(); ctx.toast('SCIM token made. Copy it now: it is shown once.', 'ok'); }); }
      }));
      ctx.on('click', '[data-scimcopy]', () => { st.scimShown = null; ctx.rerender(); ctx.toast('Token copied. It is no longer shown here.', 'ok'); });
      ctx.on('click', '[data-scimdone]', () => { st.scimShown = null; ctx.rerender(); });
      ctx.on('click', '[data-scimrevoke]', async (e, t) => { const tok = st.scim.tokens.find((x) => x.id === t.dataset.scimrevoke); const ok = await ctx.confirm({ title: 'Revoke ' + esc(tok.name) + '?', tag: 'stops provisioning', tone: 'danger', body: '<p class="fg2" style="margin:0">The provider\'s next request is refused with 401. Users and groups already provisioned stay as they are.</p>', kv: [['Prefix', '<span class="mono">' + esc(tok.prefix) + '</span>'], ['Last used', esc(tok.lastUsedAt)]], ok: 'Revoke' }); if (!ok) return; tok.state = 'revoked'; ctx.rerender(); ctx.toast(esc(tok.name) + ' revoked. Audited as scim.token.revoked.', 'warn'); });
      ctx.on('click', '[data-scimreapply]', async () => { const ok = await ctx.confirm({ title: 'Re-apply group mappings', tone: 'info', body: '<p class="fg2" style="margin:0">Recomputes roles, clearance and workspaces for every user of ' + esc(st.scim.name) + ' from their SCIM groups, as a job. Anyone whose access changes is signed out once.</p>', kv: [['Users', String(st.scim.users)], ['Group mappings', String(st.scim.groupMappings)]], ok: 'Re-apply' }); if (!ok) return; st.scim.changes.unshift({ title: 'scim.mappings.reapplied', text: 'Job identity.scim.reapply queued for ' + st.scim.users + ' users', meta: 'now', tone: 'info' }); ctx.rerender(); ctx.toast('Re-applying group mappings to ' + st.scim.users + ' users. Follow it under Jobs.', 'ok'); });
      ctx.on('click', '[data-scimaudit]', () => ctx.navigate('usage-audit', { tab: 'audit', q: 'scim.user.deactivated' }));
      ctx.on('click', '[data-testlogin]', testLogin);
      ctx.on('click', '[data-samlenable]', (e, t) => { const s = st.saml[+t.dataset.samlenable]; ctx.confirm({ title: 'Enable ' + esc(s.name), tone: 'info', body: '<p class="fg2" style="margin:0">Its signing certificate expired on 1 Aug 2026. Upload fresh metadata first, or enable with signed requests off.</p>', ok: 'Enable anyway' }).then((ok) => { if (!ok) return; s.status = 'active'; s.cert = 'expired 1 Aug 2026, unsigned requests'; ctx.rerender(); ctx.toast(esc(s.name) + ' enabled. Audit event written.', 'warn'); }); });
      ctx.on('click', '[data-copysecret]', () => { st.revealed[client.id] = '19 Sep 2026, 13:51'; ctx.rerender(); ctx.toast('Secret copied. It is no longer shown here.', 'ok'); });
      ctx.on('click', '[data-rotatesecret]', () => ctx.confirm({ title: 'Rotate secret', tag: 'breaks running jobs', tone: 'danger', body: '<p class="fg2" style="margin:0">The current secret stops working immediately. Update ' + esc(client.name) + ' with the new one, which is shown once.</p>', kv: [['Client', esc(client.name)], ['Last used', esc(client.used)]], ok: 'Rotate' }).then((ok) => { if (!ok) return; client.secret = 'xs_live_' + Math.random().toString(36).slice(2, 12) + '...shown-once'; client.fresh = true; delete st.revealed[client.id]; ctx.rerender(); ctx.toast('Secret rotated. Copy it now.', 'ok'); }));
      ctx.on('click', '[data-pkce]', (e, t) => { if (t.hasAttribute('data-na')) return; client.pkce = !client.pkce; ctx.toast('PKCE ' + (client.pkce ? 'required' : 'optional') + ' for ' + esc(client.name) + '.'); });
      ctx.on('click', '[data-disable]', () => ctx.confirm({ title: 'Disable ' + esc(client.name), tag: 'revokes tokens', tone: 'danger', body: '<p class="fg2" style="margin:0">Every access and refresh token for this client is revoked. Users see a sign-in prompt on their next request.</p>', ok: 'Disable' }).then((ok) => { if (!ok) return; client.status = 'disabled'; ctx.rerender(); ctx.toast(esc(client.name) + ' disabled. Tokens revoked; audit event written.', 'warn'); }));
      ctx.on('click', '[data-edit]', () => ctx.modal({ title: 'Edit ' + esc(client.name), body: '<div class="formgrid">' + UI.field('Access token lifetime', UI.select(['5 min', '10 min', '30 min'], client.lifetime)) + UI.field('Allowed models', UI.input(client.models)) + UI.field('Scopes', UI.input(client.scopes, { attrs: 'data-escopes' })) + UI.field('Redirect URIs', UI.textarea(client.redirects.join('\n'), { rows: 2 })) + '</div>', actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-esave' }), onMount(m) { m.querySelector('[data-esave]').addEventListener('click', () => { client.scopes = m.querySelector('[data-escopes]').value; App.closeOverlay(); ctx.rerender(); ctx.toast('Client saved. Existing tokens keep their scopes until they expire.', 'ok'); }); } }));
      ctx.on('click', '[data-revoke]', (e, t) => { const u = t.dataset.revoke; ctx.confirm({ title: 'Revoke session', tag: 'signs out', tone: 'danger', body: '<p class="fg2" style="margin:0">Ends the session and its refresh tokens now.</p>', kv: [['User', esc(u)]], ok: 'Revoke' }).then((ok) => { if (!ok) return; st.revoked[u] = true; ctx.rerender(); ctx.toast('Session for ' + esc(u) + ' revoked.', 'ok'); }); });
      ctx.on('click', '[data-gotenants]', () => ctx.navigate('tenants', { workspace: 'finance-ops', tab: client.type === 'service account' ? 'services' : 'sessions' }));
      ctx.on('click', '[data-gozones]', () => ctx.navigate('zones', { zone: 'directory' }));
      ctx.on('click', '[data-goplatform]', () => ctx.navigate('platform', { tab: 'secrets' }));
    }
  });
})();
