(function () {
  const { UI, esc } = App;

  // Sidebar entry, added at load so app.js stays untouched (Sprint 29): before Platform, with the operator's screens.
  (function () { const g = (App.NAV || []).find((x) => x.group === 'Admin'); if (!g || g.items.some((i) => i.id === 'jobs')) return; const k = g.items.findIndex((i) => i.id === 'platform'); const it = { id: 'jobs', label: 'Jobs and queues', icon: 'clock' }; if (k < 0) g.items.push(it); else g.items.splice(k, 0, it); })();

  // ---- example data: the one JobQueue (BullMQ on Redis, or database polling), the Scheduler and the tenant cache (B-2102) ----
  const TYPES0 = () => [
    { type: 'webhook.deliver', domain: 'Channels and webhooks', queued: 9, running: 2, oldest: 1, failed24: 3, p50: 320, p95: 1900, timeout: '30 s', concurrency: 8, paused: false, registered: 'server/src/webhooks', description: 'Delivers one event to one outbound webhook: signed body, retries with backoff up to WEBHOOK_MAX_ATTEMPTS, then the target\'s breaker opens.', series: [3, 4, 6, 5, 9, 12, 9, 7] },
    { type: 'knowledge.index', domain: 'Knowledge', queued: 6, running: 2, oldest: 4, failed24: 1, p50: 42000, p95: 180000, timeout: '20 min', concurrency: 2, paused: false, registered: 'server/src/knowledge', description: 'Chunks and embeds the documents of one knowledge base through the gateway; sealed text, vectors in the vector store.', series: [1, 2, 2, 3, 2, 4, 6, 6] },
    { type: 'knowledge.sync', domain: 'Knowledge', queued: 2, running: 0, oldest: 2, failed24: 0, p50: 12000, p95: 90000, timeout: '20 min', concurrency: 2, paused: false, registered: 'server/src/knowledge', description: 'Pulls one source (S3, Git, a database view, a web crawl) and queues knowledge.index for what changed.', series: [0, 1, 0, 2, 1, 1, 2, 2] },
    { type: 'media.process', domain: 'Media and images', queued: 3, running: 1, oldest: 3, failed24: 0, p50: 65000, p95: 240000, timeout: '30 min', concurrency: 1, paused: false, registered: 'server/src/media', description: 'Runs one preset (transcode, transcribe, frames) on a media asset with ffmpeg and Whisper; outputs stay in the blob store.', series: [2, 1, 3, 2, 2, 4, 3, 3] },
    { type: 'image.generate', domain: 'Media and images', queued: 2, running: 1, oldest: 1, failed24: 0, p50: 9800, p95: 31000, timeout: '5 min', concurrency: 2, paused: false, registered: 'server/src/images', description: 'One image request on a ComfyUI or diffusers worker, safety-checked before it is stored.', series: [1, 2, 2, 1, 3, 2, 2, 2] },
    { type: 'agent.run', domain: 'Chat and agents', queued: 1, running: 1, oldest: 0, failed24: 0, p50: 24000, p95: 120000, timeout: '15 min', concurrency: 4, paused: false, registered: 'server/src/agents', description: 'One agent run: tool calls through the registry, approvals as checkpoints, memory write-back at the end.', series: [2, 3, 2, 4, 3, 2, 1, 1] },
    { type: 'memory.extract', domain: 'Chat and agents', queued: 4, running: 0, oldest: 2, failed24: 0, p50: 1800, p95: 6000, timeout: '2 min', concurrency: 2, paused: false, registered: 'server/src/memory', description: 'Extracts memories from a finished conversation by rule; embeds them with the first embedding model by name.', series: [4, 3, 5, 4, 6, 5, 4, 4] },
    { type: 'file.scan', domain: 'Moderation and files', queued: 5, running: 1, oldest: 2, failed24: 1, p50: 900, p95: 4200, timeout: '2 min', concurrency: 4, paused: false, registered: 'server/src/files', description: 'Type check and ClamAV scan of a new file version in quarantine; nothing is readable before it passes.', series: [3, 5, 4, 6, 5, 7, 5, 5] },
    { type: 'attachment.scan', domain: 'Moderation and files', queued: 1, running: 0, oldest: 1, failed24: 0, p50: 700, p95: 3100, timeout: '2 min', concurrency: 4, paused: false, registered: 'server/src/chat', description: 'The same check for chat and message attachments.', series: [1, 1, 2, 1, 1, 2, 1, 1] },
    { type: 'moderation', domain: 'Moderation and files', queued: 0, running: 1, oldest: 0, failed24: 0, p50: 400, p95: 2100, timeout: '1 min', concurrency: 1, paused: false, registered: 'server/src/moderation', description: 'The moderation sweep: SLA timers, escalations and sanction expiry every MODERATION_SWEEP_SECONDS; failed items go to the dead-letter queue.', series: [1, 1, 1, 1, 1, 1, 1, 1] },
    { type: 'channels.send', domain: 'Channels and webhooks', queued: 2, running: 0, oldest: 1, failed24: 0, p50: 1200, p95: 4800, timeout: '1 min', concurrency: 4, paused: false, registered: 'server/src/channels', description: 'Sends one released reply to the customer over SMTP; a bounce is recorded once.', series: [2, 1, 2, 3, 2, 2, 2, 2] },
    { type: 'channels.imap-poll', domain: 'Channels and webhooks', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 2600, p95: 9000, timeout: '2 min', concurrency: 1, paused: false, registered: 'server/src/channels', description: 'Polls one email channel\'s mailbox every CHANNELS_IMAP_POLL_SECONDS and threads new mail by Message-ID.', series: [1, 1, 1, 1, 1, 1, 1, 0] },
    { type: 'channels.reply', domain: 'Channels and webhooks', queued: 1, running: 1, oldest: 0, failed24: 0, p50: 5400, p95: 14000, timeout: '2 min', concurrency: 4, paused: false, registered: 'server/src/channels', description: 'Drafts the answer for a customer session through the channel\'s profile; a hold flag keeps it for review.', series: [2, 2, 3, 2, 4, 3, 2, 2] },
    { type: 'pki.crl', domain: 'PKI and vault', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 1500, p95: 3000, timeout: '5 min', concurrency: 1, paused: false, registered: 'server/src/pki', description: 'Publishes a numbered CRL for one issuer, signed in the signer process.', series: [1, 0, 1, 0, 1, 0, 1, 0] },
    { type: 'pki.acme.validate', domain: 'PKI and vault', queued: 0, running: 0, oldest: 0, failed24: 2, p50: 2200, p95: 8000, timeout: '2 min', concurrency: 2, paused: false, registered: 'server/src/pki', description: 'Validates an ACME challenge (http-01 through the service address checks, or dns-01) and finalises the order.', series: [0, 1, 0, 0, 2, 1, 0, 0] },
    { type: 'ops.backup.create', domain: 'Platform operations', queued: 0, running: 0, oldest: 0, failed24: 1, p50: 380000, p95: 620000, timeout: '60 min', concurrency: 1, paused: false, registered: 'server/src/ops', description: 'Streams a consistent backup of the database and, with PLATFORM_BACKUP_BLOBS, the blob store to the backup bucket.', series: [1, 1, 1, 1, 1, 1, 1, 1] },
    { type: 'training.tick', domain: 'Training', queued: 0, running: 1, oldest: 0, failed24: 0, p50: 600, p95: 1400, timeout: '1 min', concurrency: 1, paused: false, registered: 'server/src/training', description: 'Advances every training job: windows, pre-emption, checkpoints reported by the worker, packaging and registration.', series: [1, 1, 1, 1, 1, 1, 1, 1] },
    { type: 'plugin.invoke', domain: 'Apps', queued: 1, running: 1, oldest: 0, failed24: 2, p50: 1100, p95: 5200, timeout: 'PLUGIN_SCRIPT_TIMEOUT_SECONDS', concurrency: 'PLUGIN_CONCURRENCY per plugin', paused: false, registered: 'server/src/plugins', description: 'Runs one plugin for one event: declarative actions, or a script handler in the sandbox with a scoped token.', series: [2, 3, 2, 4, 2, 3, 2, 2] },
    { type: 'apps.import', domain: 'Apps', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 15000, p95: 60000, timeout: '20 min', concurrency: 1, paused: false, registered: 'server/src/apps', description: 'Imports CSV rows into an entity (at most APPS_IMPORT_MAX_ROWS) with a dry-run report first.', series: [0, 0, 1, 0, 0, 0, 1, 0] },
    { type: 'feed', domain: 'Social', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 2400, p95: 7000, timeout: '5 min', concurrency: 1, paused: false, registered: 'server/src/feed', description: 'Trending tags every FEED_TRENDING_MINUTES and the weekly digest written by FEED_DIGEST_PROFILE.', series: [1, 0, 1, 0, 1, 0, 1, 0] },
    { type: 'users.import', domain: 'Identity', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 8000, p95: 30000, timeout: '20 min', concurrency: 1, paused: false, registered: 'server/src/identity', description: 'A CSV of users, memberships and group mappings, with a dry run that reports conflicts and changes nothing.', series: [0, 0, 0, 1, 0, 0, 0, 0] },
    { type: 'directory.sync', domain: 'Identity', queued: 0, running: 0, oldest: 0, failed24: 0, p50: 4200, p95: 12000, timeout: '10 min', concurrency: 1, paused: false, registered: 'server/src/identity/sync.ts', description: 'Links directory users and groups just in time into the users table; every DIRECTORY_SYNC_MINUTES per tenant.', series: [1, 1, 1, 1, 1, 1, 1, 1] }
  ];
  const DOMAINS = ['Knowledge', 'Chat and agents', 'Media and images', 'Moderation and files', 'Channels and webhooks', 'Platform operations', 'PKI and vault', 'Identity', 'Apps', 'Social', 'Training'];
  const JOBS0 = () => [
    { id: 'j-8821', type: 'knowledge.index', tenant: 'Northwind', workspace: 'Finance Ops', state: 'running', progress: 62, attempts: 1, created: '14:03', started: '14:04', ageMin: 7, duration: '6 min', node: 'api-1', payload: ['kbId', 'documentIds', 'reason'], message: 'embedding chunk 1,240 of 2,000', error: null, trace: '4bf92f3577b34da6a3ce929d0e0e4736', events: [{ title: 'queued', meta: '14:03:10', tone: '' }, { title: 'claimed by api-1', meta: '14:04:02', tone: 'info' }, { title: 'progress 62 %', text: 'embedding chunk 1,240 of 2,000', meta: '14:09:48', tone: 'accent' }] },
    { id: 'j-8820', type: 'webhook.deliver', tenant: 'Northwind', workspace: 'Finance Ops', state: 'running', progress: 0, attempts: 2, created: '14:08', started: '14:09', ageMin: 2, duration: '', node: 'api-1', payload: ['webhookId', 'eventId', 'attempt'], message: 'attempt 2 to siem.northwind.local', error: null, trace: '7a1c0e9d2b4f4a6c8d0e1f2a3b4c5d6e', events: [{ title: 'queued', meta: '14:08:30', tone: '' }, { title: 'attempt 1 failed', text: '503 from siem.northwind.local', meta: '14:08:31', tone: 'warn' }, { title: 'attempt 2', meta: '14:09:31', tone: 'info' }] },
    { id: 'j-8819', type: 'media.process', tenant: 'Northwind', workspace: 'People Ops', state: 'running', progress: 35, attempts: 1, created: '13:58', started: '13:59', ageMin: 12, duration: '11 min', node: 'api-2', payload: ['assetId', 'preset', 'params'], message: 'transcribe-srt, 12 of 34 min', error: null, trace: '0c3e8a1b5d7f4e2a9b1c3d5e7f9a0b2c', events: [{ title: 'queued', meta: '13:58:02', tone: '' }, { title: 'claimed by api-2', meta: '13:59:00', tone: 'info' }, { title: 'progress 35 %', meta: '14:09:10', tone: 'accent' }] },
    { id: 'j-8818', type: 'agent.run', tenant: 'Northwind', workspace: 'Field Sales', state: 'running', progress: 50, attempts: 1, created: '14:06', started: '14:06', ageMin: 4, duration: '4 min', node: 'api-1', payload: ['runId', 'agentId', 'input'], message: 'waiting on approval, step 3', error: null, trace: '9d8c7b6a5f4e4d3c2b1a0f9e8d7c6b5a', events: [{ title: 'queued', meta: '14:06:00', tone: '' }, { title: 'tool lookup_account', meta: '14:06:20', tone: 'info' }, { title: 'approval requested', text: 'step 3 waits on Felix Brandt', meta: '14:07:05', tone: 'warn' }] },
    { id: 'j-8817', type: 'file.scan', tenant: 'Northwind', workspace: 'Legal', state: 'queued', progress: 0, attempts: 0, created: '14:09', started: null, ageMin: 1, duration: '', node: '', payload: ['fileId', 'versionId'], message: null, error: null, trace: '1e2d3c4b5a6f4e7d8c9b0a1f2e3d4c5b', events: [{ title: 'queued', meta: '14:09:41', tone: '' }] },
    { id: 'j-8816', type: 'memory.extract', tenant: 'Northwind', workspace: 'Finance Ops', state: 'queued', progress: 0, attempts: 0, created: '14:08', started: null, ageMin: 2, duration: '', node: '', payload: ['conversationId'], message: null, error: null, trace: '2f3e4d5c6b7a4f8e9d0c1b2a3f4e5d6c', events: [{ title: 'queued', meta: '14:08:12', tone: '' }] },
    { id: 'j-8815', type: 'knowledge.sync', tenant: 'Northwind', workspace: 'Finance Ops', state: 'queued', progress: 0, attempts: 0, created: '14:06', started: null, ageMin: 4, duration: '', node: '', payload: ['sourceId'], message: null, error: null, trace: '3a4b5c6d7e8f4a9b0c1d2e3f4a5b6c7d', events: [{ title: 'queued', meta: '14:06:30', tone: '' }] },
    { id: 'j-8814', type: 'knowledge.index', tenant: 'Northwind', workspace: 'Legal', state: 'failed', progress: 18, attempts: 3, created: '13:20', started: '13:21', ageMin: 50, duration: '2 min', node: 'api-1', payload: ['kbId', 'documentIds', 'reason'], message: 'embedding chunk 360 of 2,000', error: 'gateway: profile knowledge answered 503 after 15 s in the queue (pool mac-studio, model gemma4:12b evicted); 3 attempts', trace: '5c6d7e8f9a0b4c1d2e3f4a5b6c7d8e9f', events: [{ title: 'queued', meta: '13:20:05', tone: '' }, { title: 'claimed by api-1', meta: '13:21:00', tone: 'info' }, { title: 'attempt 1 failed', text: 'gateway 503', meta: '13:23:10', tone: 'warn' }, { title: 'attempt 2 failed', text: 'gateway 503', meta: '13:25:40', tone: 'warn' }, { title: 'attempt 3 failed', text: 'gave up; job.failed published, exprsn_jobs{state="failed"} +1', meta: '13:28:12', tone: 'danger' }] },
    { id: 'j-8812', type: 'pki.acme.validate', tenant: 'Northwind', workspace: '', state: 'failed', progress: 0, attempts: 1, created: '12:40', started: '12:40', ageMin: 90, duration: '31 s', node: 'api-2', payload: ['orderId', 'challenge'], message: null, error: 'http-01: files.northwind.local answered 404 for the token at /.well-known/acme-challenge', trace: '6d7e8f9a0b1c4d2e3f4a5b6c7d8e9f0a', events: [{ title: 'queued', meta: '12:40:00', tone: '' }, { title: 'failed', text: '404 from the challenge path', meta: '12:40:31', tone: 'danger' }] },
    { id: 'j-8809', type: 'plugin.invoke', tenant: 'Northwind', workspace: 'Finance Ops', state: 'failed', progress: 0, attempts: 3, created: '13:26', started: '13:26', ageMin: 44, duration: '5 min', node: 'api-1', payload: ['pluginId', 'eventId', 'chain'], message: null, error: 'webhook refused: host hooks.contoso.example is not in the tenant\'s allowed hosts (422)', trace: '7e8f9a0b1c2d4e3f4a5b6c7d8e9f0a1b', events: [{ title: 'queued', meta: '13:26:00', tone: '' }, { title: 'attempt 3 refused', meta: '13:31:40', tone: 'danger' }] },
    { id: 'j-8805', type: 'ops.backup.create', tenant: 'platform', workspace: '', state: 'succeeded', progress: 100, attempts: 1, created: '18 Sep 23:00', started: '18 Sep 23:00', ageMin: 910, duration: '6 min 20 s', node: 'api-1', payload: ['stores', 'retain'], message: 'postgres 48 GiB, blobs delta 2.1 GiB', error: null, trace: '8f9a0b1c2d3e4f4a5b6c7d8e9f0a1b2c', events: [{ title: 'queued', meta: '23:00:00', tone: '' }, { title: 'succeeded', text: 'backup b-2026-09-18 written; RPO watch reset', meta: '23:06:20', tone: 'ok' }] },
    { id: 'j-8801', type: 'image.generate', tenant: 'Northwind', workspace: 'Field Sales', state: 'succeeded', progress: 100, attempts: 1, created: '13:52', started: '13:52', ageMin: 18, duration: '12 s', node: 'images-1', payload: ['requestId', 'preset'], message: null, error: null, trace: '9a0b1c2d3e4f4a5b6c7d8e9f0a1b2c3d', events: [{ title: 'queued', meta: '13:52:00', tone: '' }, { title: 'succeeded', text: 'safety check passed', meta: '13:52:12', tone: 'ok' }] },
    { id: 'j-8797', type: 'training.tick', tenant: 'Northwind', workspace: 'Finance Ops', state: 'preempted', progress: 40, attempts: 1, created: '11:30', started: '11:30', ageMin: 160, duration: '2 h', node: 'trainer-gpu-1', payload: ['jobId'], message: 'checkpoint at step 1,800', error: null, trace: 'a0b1c2d3e4f54a6b7c8d9e0f1a2b3c4d', events: [{ title: 'running', meta: '11:30', tone: 'info' }, { title: 'preempted', text: 'a high-priority job took the GPUs; checkpoint kept', meta: '13:30', tone: 'warn' }] },
    { id: 'j-8790', type: 'users.import', tenant: 'Northwind', workspace: '', state: 'cancelled', progress: 10, attempts: 1, created: '17 Sep 09:12', started: '17 Sep 09:12', ageMin: 3000, duration: '40 s', node: 'api-1', payload: ['importId', 'dryRun'], message: null, error: null, trace: 'b1c2d3e4f5a64b7c8d9e0f1a2b3c4d5e', events: [{ title: 'running', meta: '09:12', tone: 'info' }, { title: 'cancelled by Jonas Lindqvist', text: 'wrong file', meta: '09:13', tone: 'warn' }] }
  ];
  const SCHEDULES0 = () => [
    { name: 'audit.checkpoint', every: 'AUDIT_CHECKPOINT_MINUTES (15 min)', setting: 'AUDIT_CHECKPOINT_MINUTES', last: '14:00', next: 'in 5 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Writes a checkpoint of each tenant\'s audit chain, so a verification can start from it.' },
    { name: 'directory.sync', every: 'DIRECTORY_SYNC_MINUTES (30 min)', setting: 'DIRECTORY_SYNC_MINUTES', last: '13:45', next: 'in 5 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Links directory users and groups into the users table for every tenant with a directory store.' },
    { name: 'guardrails.sweep', every: '2 min', setting: null, last: '14:08', next: 'in 1 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Escalates flags past their timers and expires holds.' },
    { name: 'mcp.poll', every: 'MCP_POLL_MINUTES (10 min)', setting: 'MCP_POLL_MINUTES', last: '14:05', next: 'in 5 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Re-reads the tool lists of every MCP server and marks the ones that changed.' },
    { name: 'knowledge.sync-due', every: '5 min', setting: null, last: '14:10', next: 'in 5 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Queues knowledge.sync for every source whose schedule is due.' },
    { name: 'memory.purge', every: '60 min', setting: null, last: '14:00', next: 'in 50 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Removes memories past their retention and ones their owner deleted.' },
    { name: 'chat.retention', every: 'CHAT_RETENTION_SWEEP_MINUTES (60 min)', setting: 'CHAT_RETENTION_SWEEP_MINUTES', last: '13:30', next: 'in 20 min', result: 'ok, 412 conversations', targets: 'every active tenant', paused: false, description: 'Applies the tenant, workspace and user retention rules to conversations.' },
    { name: 'chat.sweep', every: '15 min', setting: null, last: '14:00', next: 'in 5 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Finishes streams whose lease expired, so a client can resume from any instance.' },
    { name: 'training.tick', every: 'TRAINING_TICK_SECONDS (30 s)', setting: 'TRAINING_TICK_SECONDS', last: '14:09:40', next: 'in 20 s', result: 'ok', targets: 'every active tenant', paused: false, description: 'Advances training jobs through windows, pre-emption and checkpoints.' },
    { name: 'zones.health', every: 'ZONE_HEALTH_MINUTES (5 min)', setting: 'ZONE_HEALTH_MINUTES', last: '14:07', next: 'in 2 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Checks every zone endpoint and marks unhealthy members on the Zones map.' },
    { name: 'zones.cluster.drift', every: 'ZONES_APPLY_DRIFT_MINUTES (15 min)', setting: 'ZONES_APPLY_DRIFT_MINUTES', last: '13:59', next: 'in 4 min', result: 'drift: data', targets: 'platform', paused: false, description: 'Compares each NetworkPolicy applied in-cluster with what was applied; drift is audited and notified.' },
    { name: 'ops.backup.create', every: 'PLATFORM_BACKUP_MINUTES (24 h)', setting: 'PLATFORM_BACKUP_MINUTES', last: '18 Sep 23:00', next: 'today 23:00', result: 'ok, 6 min 20 s', targets: 'platform', paused: false, description: 'The scheduled backup of every store.' },
    { name: 'ops.backup.drill', every: 'PLATFORM_DRILL_MINUTES (7 d)', setting: 'PLATFORM_DRILL_MINUTES', last: '14 Sep 02:00', next: '21 Sep 02:00', result: 'ok, 3 h 10 min', targets: 'platform', paused: false, description: 'Restores the last backup into the drill namespace and measures each step against the RTO.' },
    { name: 'ops.backup.watch', every: '5 min', setting: 'PLATFORM_BACKUP_RPO_MINUTES', last: '14:05', next: 'in 0 min', result: 'RPO missed: MinIO', targets: 'platform', paused: false, description: 'Raises a platform alert when a store is past its RPO.' },
    { name: 'ops.cert.sweep', every: 'ACME_CHECK_MINUTES (60 min)', setting: 'ACME_CHECK_MINUTES', last: '13:40', next: 'in 30 min', result: 'ok, 3 expiring', targets: 'platform', paused: false, description: 'Renews certificates within ACME_RENEW_DAYS of expiry and runs their push hooks.' },
    { name: 'ops.mirror.check', every: 'PLATFORM_MIRROR_CHECK_MINUTES (30 min)', setting: 'PLATFORM_MIRROR_CHECK_MINUTES', last: '13:55', next: 'in 15 min', result: 'ok', targets: 'platform', paused: false, description: 'Probes every mirror address and marks stale vulnerability data.' },
    { name: 'federation.keys', every: '60 min', setting: 'OIDC_KEY_ROTATION_DAYS', last: '14:00', next: 'in 50 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Rotates OIDC signing keys on schedule and keeps the overlap.' },
    { name: 'federation.metadata', every: 'FEDERATION_METADATA_REFRESH_HOURS (24 h)', setting: 'FEDERATION_METADATA_REFRESH_HOURS', last: '18 Sep 03:00', next: 'today 03:00', result: 'ok', targets: 'every active tenant', paused: false, description: 'Refreshes upstream OIDC and SAML metadata from their sources.' },
    { name: 'federation.purge', every: '60 min', setting: null, last: '14:00', next: 'in 50 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Deletes expired codes, device codes and nonces.' },
    { name: 'billing.close', every: 'BILLING_CLOSE_MINUTES (60 min)', setting: 'BILLING_CLOSE_MINUTES', last: '14:00', next: 'in 50 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Closes usage periods and reconciles them with Stripe when configured.' },
    { name: 'agents.schedules', every: 'AGENT_SCHEDULE_TICK_SECONDS (60 s)', setting: 'AGENT_SCHEDULE_TICK_SECONDS', last: '14:09', next: 'in 1 min', result: 'ok, 2 runs started', targets: 'every active tenant', paused: false, description: 'Starts scheduled agent runs that are due.' },
    { name: 'apps.schedules', every: 'APPS_SCHEDULE_TICK_SECONDS (60 s)', setting: 'APPS_SCHEDULE_TICK_SECONDS', last: '14:09', next: 'in 1 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Fires schedule triggers of low-code apps.' },
    { name: 'pki.crl', every: 'PKI_CRL_MINUTES (60 min)', setting: 'PKI_CRL_MINUTES', last: '13:30', next: 'in 20 min', result: 'ok, 4 issuers', targets: 'every active tenant', paused: false, description: 'Publishes a CRL for every live issuer.' },
    { name: 'pki.expiry', every: 'PKI_EXPIRY_SWEEP_MINUTES (6 h)', setting: 'PKI_EXPIRY_SWEEP_MINUTES', last: '12:00', next: 'in 4 h', result: 'ok, 2 notices', targets: 'every active tenant', paused: false, description: 'Notifies owners at PKI_EXPIRY_NOTICE_DAYS before a certificate expires.' },
    { name: 'files.purge', every: 'FILES_PURGE_MINUTES (6 h)', setting: 'FILES_PURGE_MINUTES', last: '12:00', next: 'in 4 h', result: 'ok, 318 purged', targets: 'every active tenant', paused: false, description: 'Deletes trashed files past FILES_TRASH_DAYS and their blobs.' },
    { name: 'channels.imap-poll', every: 'CHANNELS_IMAP_POLL_SECONDS (60 s)', setting: 'CHANNELS_IMAP_POLL_SECONDS', last: '14:09', next: 'in 1 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Queues a poll for every email channel.' },
    { name: 'channels.retention', every: 'CHANNELS_RETENTION_SWEEP_MINUTES (60 min)', setting: 'CHANNELS_RETENTION_SWEEP_MINUTES', last: '13:30', next: 'in 20 min', result: 'ok', targets: 'every active tenant', paused: false, description: 'Purges customer sessions past each channel\'s retention.' }
  ];
  // Live (1.6.0, B-4203): the domains that keep a dead-letter queue: moderation jobs (B-1905) and workflow runs (B-3906).
  const DEAD0 = () => [
    { id: 'dl-1', source: 'Moderation dead-letter queue', item: 'job 01J8Z…K2, moderation.provider', reason: 'Perspective-compatible provider timed out 3 times (MODERATION_PROVIDER_TIMEOUT_MS)', attempts: 3, first: '19 Sep 11:02', last: '19 Sep 11:10', type: 'moderation', go: ['moderation', { tab: 'deadletters' }], goLabel: 'Moderation', audit: 'moderation.job.redriven' },
    { id: 'dl-2', source: 'Workflow run', item: 'invoice-approval, run 01J8Y…7Q, step post-to-erp', reason: 'webhook step refused: hooks.contoso.example is not in the tenant\'s allowed hosts (422)', attempts: 3, first: '19 Sep 13:26', last: '19 Sep 13:31', type: 'workflow run', go: ['workflows', {}], goLabel: 'Workflows', audit: 'workflow.dead_letter.redriven' },
    { id: 'dl-3', source: 'Workflow run', item: 'onboarding-pack, run 01J8X…3M, step make-account', reason: 'directory answered 503 three times', attempts: 3, first: '19 Sep 12:15', last: '19 Sep 12:16', type: 'workflow run', go: ['workflows', {}], goLabel: 'Workflows', audit: 'workflow.dead_letter.redriven' }
  ];
  // Live (1.6.0, B-4203): the namespaces the server reads through the tenant cache.
  const CACHE0 = () => [
    { ns: 'plugins', tier: 'medium', ttl: 'CACHE_TTL_MEDIUM_SECONDS (300 s)', requests: 31400, hits: 30110, inv: { local: 14, bus: 9 }, entries: 1 },
    { ns: 'sanctions', tier: 'short', ttl: 'CACHE_TTL_SHORT_SECONDS (30 s)', requests: 212800, hits: 171000, inv: { local: 120, bus: 96 }, entries: 184 },
    { ns: 'workflow-triggers', tier: 'medium', ttl: 'CACHE_TTL_MEDIUM_SECONDS (300 s)', requests: 9800, hits: 9310, inv: { local: 6, bus: 6 }, entries: 1 }
  ];
  const STATE_KIND = { queued: 'info', running: 'info', succeeded: 'ok', failed: 'danger', cancelled: 'warn', preempted: 'warn' };
  const WINDOW_MIN = { '1h': 60, '24h': 1440, '7d': 10080 };
  const ms = (n) => n >= 60000 ? (n / 60000).toFixed(n >= 600000 ? 0 : 1) + ' min' : n >= 1000 ? (n / 1000).toFixed(n >= 10000 ? 0 : 1) + ' s' : n + ' ms';
  const pct = (a, b) => b ? (100 * a / b).toFixed(1) + ' %' : '—';
  const num = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
  const init = (st) => {
    if (st.types) return;
    st.types = TYPES0(); st.jobs = JOBS0(); st.schedules = SCHEDULES0(); st.dead = DEAD0(); st.cache = CACHE0();
    st.tab = 'queues'; st.backend = 'redis'; st.cacheStore = 'redis'; st.tracing = true; st.instances = 2;
    st.selType = 'webhook.deliver'; st.typeQuery = ''; st.domain = 'all';
    st.selJob = 'j-8821'; st.jobState = 'all'; st.jobType = 'all'; st.window = '24h'; st.jobQuery = '';
    st.selSched = 'audit.checkpoint'; st.selDead = 'dl-1'; st.selNs = 'sanctions';
    st.backlog = false; st.behind = false; st.nextId = 8822;
  };
  const backendLabel = (st) => st.backend === 'redis' ? 'BullMQ on Redis' : 'database polling';
  const windowLabel = { '1h': 'last hour', '24h': 'last 24 h', '7d': 'last 7 days' };

  App.register({
    id: 'jobs', title: 'Jobs and queues', section: 'admin', crumb: ['Admin', 'Jobs and queues'],
    summary: 'Every queue, job and schedule; failed work, dead letters and the tenant cache',
    commands: [
      { label: 'Retry failed jobs', sub: 'Jobs and queues', run(app) { const s = app.stateFor('jobs'); init(s); s.tab = 'jobs'; s.jobState = 'failed'; s.openRetryAll = true; app.render(); } },
      { label: 'Run a schedule now', sub: 'Jobs and queues', run(app) { const s = app.stateFor('jobs'); init(s); s.tab = 'schedules'; s.openRunNow = true; app.render(); } }
    ],
    states: [
      { title: 'Queue backlog growing', tone: 'warn', text: 'webhook.deliver has 212 queued and the oldest has waited 18 min: one target\'s breaker is open and every delivery to it fails fast. The notice links to Dead letters.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'queues'; st.backlog = true; st.selType = 'webhook.deliver'; const t = st.types.find((x) => x.type === 'webhook.deliver'); t.queued = 212; t.oldest = 18; t.failed24 = 41; t.series = [3, 4, 9, 20, 48, 90, 160, 212]; ctx.rerender(); } },
      { title: 'Job failed with trace', tone: 'danger', text: 'A knowledge.index job gave up after three gateway 503s. The inspector shows the error, the payload keys and the trace id; Open trace goes to the collector.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'jobs'; st.jobState = 'all'; st.jobType = 'all'; st.jobQuery = ''; st.selJob = 'j-8814'; ctx.rerender(); } },
      { title: 'Instance behind claims no jobs', tone: 'info', text: 'api-2 is behind the schema (032_dav pending) and claims nothing until the database matches its build; api-1 carries every queue. The notice links to Overview.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'queues'; st.behind = true; ctx.rerender(); } },
      { title: 'Dead letter redriven', tone: 'ok', text: 'The moderation dead letter is redriven: it leaves Dead letters and appears in Jobs as queued, with a toast and an audit event.', apply(ctx) { init(ctx.state); const st = ctx.state; const d = st.dead.find((x) => x.id === 'dl-1'); if (d) redrive(st, d); st.tab = 'jobs'; st.jobState = 'all'; st.jobType = 'all'; st.jobQuery = ''; ctx.rerender(); ctx.toast('Redriven as job j-' + (st.nextId - 1) + ' (queued). Audited moderation.job.redriven.', 'ok'); } },
      { title: 'Database polling backend', tone: 'neutral', text: 'A single-node install: JOB_QUEUE=database, CACHE_STORE=memory, no tracing endpoint. The backend pill, the cache store and the per-instance notice change; Open trace is disabled.', apply(ctx) { init(ctx.state); const st = ctx.state; st.backend = 'db'; st.cacheStore = 'memory'; st.tracing = false; st.tab = 'queues'; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state; init(st);
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }
      if (ctx.params.id) { const j = st.jobs.find((x) => x.id === ctx.params.id || x.trace === ctx.params.id); if (j) { st.tab = 'jobs'; st.selJob = j.id; st.jobState = 'all'; st.jobType = 'all'; } delete ctx.params.id; }
      const queued = st.jobs.filter((j) => j.state === 'queued').length, running = st.jobs.filter((j) => j.state === 'running').length, failed = st.jobs.filter((j) => j.state === 'failed').length;
      const paused = st.types.filter((t) => t.paused).length;
      const tabs = UI.tabs([{ id: 'queues', label: 'Queues', count: st.types.length }, { id: 'jobs', label: 'Jobs', count: queued + running }, { id: 'schedules', label: 'Schedules', count: st.schedules.length }, { id: 'deadletters', label: 'Dead letters', count: st.dead.length }, { id: 'cache', label: 'Cache' }], st.tab);
      let body = '', insp = '';

      // ---------------- Queues ----------------
      if (st.tab === 'queues') {
        const q = st.typeQuery.toLowerCase();
        const rows = st.types.filter((t) => (st.domain === 'all' || t.domain === st.domain) && (!q || (t.type + ' ' + t.domain + ' ' + t.description).toLowerCase().includes(q)));
        if (!rows.some((t) => t.type === st.selType)) st.selType = rows.length ? rows[0].type : null;
        const sel = st.types.find((t) => t.type === st.selType);
        body += (st.backlog ? UI.notice('<b>webhook.deliver is backing up:</b> 212 queued, the oldest for 18 min. The breaker for bots.northwind.local is open until 14:22, so every delivery to it fails fast and is retried with backoff. Deliveries to other targets are unaffected.', 'warn', UI.btn('Open dead letters', { size: 'sm', attrs: 'data-godead' })) : '')
          + (st.behind ? UI.notice('<b>api-2 claims no jobs</b> while it is behind the schema (migration 032_dav pending, /readyz checks.schema). api-1 carries every queue until the database matches both builds.', 'info', UI.btn('Open Overview', { size: 'sm', attrs: 'data-gooverview' })) : '')
          + '<div class="toolbar">' + UI.search('Filter by type, domain, description', 'data-typesearch', st.typeQuery)
          + '<span class="relative">' + UI.btn(st.domain === 'all' ? 'Domain' : 'Domain: ' + st.domain, { size: 'sm', icon: 'filter', attrs: 'data-menu="domain"', cls: st.domain !== 'all' ? 'active' : '' }) + '</span>'
          + UI.pill(backendLabel(st), st.backend === 'redis' ? 'info' : 'outline') + (paused ? UI.pill(paused + ' paused', 'warn') : '') + '<span class="muted right" style="font-size:12px">' + rows.length + ' types, JOB_CONCURRENCY ' + (st.backend === 'redis' ? '8' : '4') + ' per instance, ' + (st.behind ? '1 of 2 instances claiming' : st.instances + ' instances claiming') + '</span></div>'
          + UI.table(['Type', 'Domain', { label: 'Queued', right: true }, { label: 'Running', right: true }, 'Oldest queued', { label: 'Failed 24 h', right: true }, { label: 'p95', right: true }, 'Timeout', 'State'], rows.map((t) => ({ cells: ['<span class="mono" style="font-weight:600">' + esc(t.type) + '</span>', esc(t.domain), '<span class="num">' + num(t.queued) + '</span>', '<span class="num">' + t.running + '</span>', t.oldest ? (t.oldest >= 15 ? '<span style="color:var(--warn-fg)">' + t.oldest + ' min</span>' : t.oldest + ' min') : '<span class="muted">—</span>', '<span class="num' + (t.failed24 >= 10 ? '" style="color:var(--danger-fg)' : '') + '">' + t.failed24 + '</span>', '<span class="num">' + ms(t.p95) + '</span>', '<span class="mono" style="font-size:11px">' + esc(t.timeout) + '</span>', UI.pill(t.paused ? 'paused' : 'active', t.paused ? 'warn' : 'ok')], attrs: 'data-type="' + esc(t.type) + '"', selected: t.type === st.selType })), { minWidth: '1040px', emptyTitle: 'No types match', emptyText: 'Clear the filter or pick another domain.' })
          + '<span class="muted" style="font-size:12px">One queue, one table: every job type is a handler registered on the JobQueue (' + esc(backendLabel(st)) + '); the scheduler queues the recurring ones. A paused type keeps queuing and stops claiming. Oldest queued is exprsn_jobs_oldest_queued_seconds per type.</span>';
        if (sel) {
          const last = st.jobs.filter((j) => j.type === sel.type).slice(0, 5);
          insp = '<div class="hstack"><div class="eyebrow grow">Job type</div>' + UI.pill(sel.paused ? 'paused' : 'active', sel.paused ? 'warn' : 'ok') + '</div><div class="mono" style="font-size:15px;font-weight:600">' + esc(sel.type) + '</div><div class="fg2" style="font-size:12px">' + esc(sel.description) + '</div>'
            + UI.kv([['Domain', esc(sel.domain)], ['Timeout', '<span class="mono">' + esc(sel.timeout) + '</span>'], ['Concurrency', '<span class="mono">JOB_CONCURRENCY ' + (st.backend === 'redis' ? '8' : '4') + '</span>'], ['Queued, running', num(sel.queued) + ', ' + sel.running], ['Failed 24 h', String(sel.failed24)]], 2)
            + '<div class="eyebrow">Duration</div><div class="hstack"><div class="grow"><div class="kv" style="--cols:2"><div><div class="k">p50</div><div class="v num">' + ms(sel.p50) + '</div></div><div><div class="k">p95</div><div class="v num">' + ms(sel.p95) + '</div></div></div></div>' + UI.spark(sel.series, sel.series.length - 1) + '</div><span class="muted" style="font-size:11px">Queued per 3 h over the last day, latest right.</span>'
            + '<div class="eyebrow">Last five jobs</div>' + (last.length ? UI.table(['Job', 'State', 'When'], last.map((j) => ['<a href="#" class="mono" data-openjob="' + esc(j.id) + '">' + esc(j.id) + '</a>', UI.pill(j.state, STATE_KIND[j.state]), esc(j.created)]), { clickable: false, minWidth: '0', cls: 'bare' }) : '<span class="muted" style="font-size:12px">No jobs of this type in the window.</span>')
            + '<div class="hstack wrap gap6">' + (sel.paused ? UI.btn('Resume', { kind: 'primary', size: 'sm', icon: 'play', attrs: 'data-resumetype' }) : UI.btn('Pause type', { size: 'sm', icon: 'pause', attrs: 'data-pausetype' })) + UI.btn('Retry all failed', { size: 'sm', icon: 'refresh', attrs: 'data-retrytype', disabled: !sel.failed24 }) + UI.btn('Jobs of this type', { size: 'sm', kind: 'ghost', attrs: 'data-jobsfor="' + esc(sel.type) + '"' }) + '</div>'
            + '<span class="muted" style="font-size:12px">Audit entries: jobs.type.paused, jobs.type.resumed, jobs.retried.</span>';
        }
      }
      // ---------------- Jobs ----------------
      if (st.tab === 'jobs') {
        const q = st.jobQuery.toLowerCase(); const lim = WINDOW_MIN[st.window];
        const rows = st.jobs.filter((j) => (st.jobState === 'all' || j.state === st.jobState) && (st.jobType === 'all' || j.type === st.jobType) && j.ageMin <= lim && (!q || (j.id + ' ' + j.trace + ' ' + j.type).toLowerCase().includes(q)));
        if (!rows.some((j) => j.id === st.selJob)) st.selJob = rows.length ? rows[0].id : null;
        const sel = st.jobs.find((j) => j.id === st.selJob);
        body += '<div class="toolbar">' + UI.search('Job id or trace id', 'data-jobsearch', st.jobQuery)
          + '<span class="relative">' + UI.btn(st.jobState === 'all' ? 'State' : 'State: ' + st.jobState, { size: 'sm', icon: 'filter', attrs: 'data-menu="jobstate"', cls: st.jobState !== 'all' ? 'active' : '' }) + '</span>'
          + '<span class="relative">' + UI.btn(st.jobType === 'all' ? 'Type' : 'Type: ' + st.jobType, { size: 'sm', icon: 'filter', attrs: 'data-menu="jobtype"', cls: st.jobType !== 'all' ? 'active' : '' }) + '</span>'
          + UI.seg([{ id: '1h', label: '1 h' }, { id: '24h', label: '24 h' }, { id: '7d', label: '7 d' }], st.window, 'data-window') + UI.btn('Retry failed', { size: 'sm', icon: 'refresh', attrs: 'data-retryall', disabled: !failed }) + '<span class="muted right" style="font-size:12px">' + rows.length + ' shown, ' + queued + ' queued, ' + running + ' running, ' + failed + ' failed in the ' + windowLabel[st.window] + '</span></div>'
          + UI.table(['Job', 'Type', 'Tenant and workspace', 'State', 'Progress', { label: 'Attempts', right: true }, 'Created', 'Started', 'Duration', 'Node'], rows.map((j) => ({ cells: ['<span class="mono" style="font-weight:600">' + esc(j.id) + '</span>', '<span class="mono" style="font-size:12px">' + esc(j.type) + '</span>', esc(j.tenant) + (j.workspace ? ' <span class="muted">/ ' + esc(j.workspace) + '</span>' : ''), UI.pill(j.state, STATE_KIND[j.state]), j.state === 'running' || j.state === 'preempted' || j.state === 'failed' ? '<div style="min-width:90px">' + UI.meter('', j.progress + ' %', j.progress, j.state === 'failed' ? 'danger' : j.state === 'preempted' ? 'warn' : 'accent') + '</div>' : j.state === 'succeeded' ? '<span class="muted">done</span>' : '<span class="muted">—</span>', '<span class="num">' + j.attempts + '</span>', esc(j.created), esc(j.started || '—'), esc(j.duration || '—'), j.node ? '<span class="mono" style="font-size:12px">' + esc(j.node) + '</span>' : '<span class="muted">—</span>'], attrs: 'data-job="' + esc(j.id) + '"', selected: j.id === st.selJob })), { minWidth: '1040px', emptyTitle: 'No jobs match', emptyText: 'Widen the window or clear the filters.' })
          + '<span class="muted" style="font-size:12px">Jobs carry their tenant and the principal that started them; a tenant admin sees the tenant\'s jobs, a system admin every tenant\'s. Payloads are shown as keys only. Progress is what the worker reports.</span>';
        if (sel) {
          insp = '<div class="hstack"><div class="eyebrow grow">Job</div>' + UI.pill(sel.state, STATE_KIND[sel.state]) + '</div><div class="mono" style="font-size:15px;font-weight:600">' + esc(sel.id) + '</div><div class="mono fg2" style="font-size:12px">' + esc(sel.type) + '</div>'
            + UI.kv([['Tenant', esc(sel.tenant) + (sel.workspace ? ', ' + esc(sel.workspace) : '')], ['Attempts', String(sel.attempts)], ['Created', esc(sel.created)], ['Started', esc(sel.started || 'not yet')], ['Duration', esc(sel.duration || '—')], ['Node', esc(sel.node || 'not claimed')]], 2)
            + '<div class="eyebrow">Payload keys</div><div class="hstack wrap gap4">' + sel.payload.map((k) => '<span class="pill outline mono">' + esc(k) + '</span>').join('') + '</div><span class="muted" style="font-size:11px">Values are never shown here: they can carry tenant content.</span>'
            + (sel.message ? UI.kv([['Message', esc(sel.message)]], 1) : '')
            + (sel.error ? UI.problem('Failed after ' + sel.attempts + (sel.attempts === 1 ? ' attempt' : ' attempts'), sel.error, sel.trace) : '')
            + '<div class="eyebrow">Trace</div>' + (st.tracing ? '<div class="hstack gap6"><span class="mono" style="font-size:11px;overflow-wrap:anywhere">' + esc(sel.trace) + '</span>' + UI.iconbtn('copy', 'Copy trace id', { cls: 'sm ghost', attrs: 'data-copytrace' }) + '</div><span class="muted" style="font-size:11px">Look it up in the collector at OTEL_EXPORTER_OTLP_ENDPOINT.</span>' : '<span class="muted" style="font-size:12px">Tracing is off: OTEL_EXPORTER_OTLP_ENDPOINT is unset.</span>')
            + '<div class="eyebrow">Progress</div>' + UI.timeline(sel.events.map((e) => ({ title: esc(e.title), text: e.text ? esc(e.text) : '', meta: esc(e.meta), tone: e.tone })))
            + '<div class="hstack wrap gap6">' + (sel.state === 'queued' || sel.state === 'running' ? UI.btn('Cancel', { kind: 'danger', size: 'sm', icon: 'stop', attrs: 'data-canceljob' }) : '') + (sel.state === 'failed' || sel.state === 'cancelled' || sel.state === 'preempted' ? UI.btn(sel.state === 'preempted' ? 'Resume' : 'Retry', { kind: 'primary', size: 'sm', icon: 'refresh', attrs: 'data-retryjob' }) : '') + UI.btn('Type', { size: 'sm', kind: 'ghost', attrs: 'data-opentype="' + esc(sel.type) + '"' }) + '</div>'
            + '<span class="muted" style="font-size:12px">Audit entries: jobs.cancelled, jobs.retried. job.progress reaches the starter\'s sockets.</span>';
        }
      }
      // ---------------- Schedules ----------------
      if (st.tab === 'schedules') {
        const rows = st.schedules;
        const sel = rows.find((s) => s.name === st.selSched) || rows[0];
        body += '<div class="toolbar">' + UI.pill(rows.filter((s) => !s.paused).length + ' running', 'ok') + (rows.some((s) => s.paused) ? UI.pill(rows.filter((s) => s.paused).length + ' paused', 'warn') : '') + '<span class="muted right" style="font-size:12px">The Scheduler queues each once per bucket; two instances never run the same bucket twice.</span></div>'
          + UI.table(['Schedule', 'Every', 'Last run', 'Next run', 'Last result', 'Targets', 'State'], rows.map((s) => ({ cells: ['<span class="mono" style="font-weight:600">' + esc(s.name) + '</span>', '<span class="mono" style="font-size:11px">' + esc(s.every) + '</span>', esc(s.last), s.paused ? '<span class="muted">paused</span>' : esc(s.next), /missed|drift/.test(s.result) ? '<span style="color:var(--warn-fg)">' + esc(s.result) + '</span>' : esc(s.result), esc(s.targets), UI.pill(s.paused ? 'paused' : 'scheduled', s.paused ? 'warn' : 'ok')], attrs: 'data-sched="' + esc(s.name) + '"', selected: s.name === sel.name })), { minWidth: '980px' })
          + '<span class="muted" style="font-size:12px">Recurring work is recorded in the default tenant\'s audit chain with actor.service platform-ops; tenant schedules run as the tenant.</span>';
        if (sel) {
          insp = '<div class="hstack"><div class="eyebrow grow">Schedule</div>' + UI.pill(sel.paused ? 'paused' : 'scheduled', sel.paused ? 'warn' : 'ok') + '</div><div class="mono" style="font-size:15px;font-weight:600">' + esc(sel.name) + '</div><div class="fg2" style="font-size:12px">' + esc(sel.description) + '</div>'
            + UI.kv([['Every', '<span class="mono" style="font-size:11px">' + esc(sel.every) + '</span>'], ['Targets', esc(sel.targets)], ['Last run', esc(sel.last)], ['Next run', sel.paused ? 'paused' : esc(sel.next)], ['Last result', esc(sel.result)], ['Period set by', sel.setting ? '<a href="#" class="mono" data-gosetting="' + esc(sel.setting) + '" style="font-size:11px">' + esc(sel.setting) + '</a>' : '<span class="muted">fixed in code</span>']], 2)
            + '<div class="eyebrow">Last five runs</div>' + UI.table(['When', 'Result', 'Took'], [[esc(sel.last), esc(sel.result), '1.2 s'], ['one period earlier', 'ok', '1.1 s'], ['two periods earlier', 'ok', '1.4 s'], ['three periods earlier', 'ok', '1.0 s'], ['four periods earlier', 'ok', '1.3 s']], { clickable: false, minWidth: '0', cls: 'bare' })
            + '<div class="hstack wrap gap6">' + UI.btn('Run now', { kind: 'primary', size: 'sm', icon: 'play', attrs: 'data-runnow' }) + (sel.paused ? UI.btn('Resume', { size: 'sm', attrs: 'data-resumesched' }) : UI.btn('Pause', { size: 'sm', icon: 'pause', attrs: 'data-pausesched' })) + '</div>'
            + '<span class="muted" style="font-size:12px">Audit entries: jobs.schedule.run, jobs.schedule.paused, jobs.schedule.resumed.</span>';
        }
      }
      // ---------------- Dead letters ----------------
      if (st.tab === 'deadletters') {
        const rows = st.dead;
        if (!rows.some((d) => d.id === st.selDead)) st.selDead = rows.length ? rows[0].id : null;
        const sel = rows.find((d) => d.id === st.selDead);
        body += '<div class="toolbar"><span class="muted" style="font-size:12px">Everything that gave up, from every domain. Redrive queues it again as a job; discard records why it was dropped.</span></div>'
          + UI.table(['Source', 'Item', 'Reason', { label: 'Attempts', right: true }, 'First failed', 'Last failed', { label: '', right: true }], rows.map((d) => ({ cells: ['<span style="font-weight:600">' + esc(d.source) + '</span>', '<span class="mono" style="font-size:12px">' + esc(d.item) + '</span>', '<span class="fg2" style="font-size:12px">' + esc(d.reason) + '</span>', '<span class="num">' + d.attempts + '</span>', esc(d.first), esc(d.last), UI.btn('Redrive', { size: 'xs', attrs: 'data-redrive="' + esc(d.id) + '"' }) + ' ' + UI.btn('Discard', { size: 'xs', kind: 'danger', attrs: 'data-discard="' + esc(d.id) + '"' })], attrs: 'data-dead="' + esc(d.id) + '"', selected: d.id === st.selDead })), { minWidth: '1040px', emptyTitle: 'No dead letters', emptyText: 'Nothing has given up in the window.' });
        if (sel) {
          insp = '<div class="eyebrow">Dead letter</div><div style="font-size:15px;font-weight:600">' + esc(sel.source) + '</div><div class="mono fg2" style="font-size:12px">' + esc(sel.item) + '</div>'
            + UI.kv([['Reason', esc(sel.reason)], ['Attempts', String(sel.attempts)], ['First failed', esc(sel.first)], ['Last failed', esc(sel.last)], ['Redrives as', '<span class="mono">' + esc(sel.type) + '</span>']], 1)
            + '<div class="hstack wrap gap6">' + UI.btn('Redrive', { kind: 'primary', size: 'sm', icon: 'refresh', attrs: 'data-redrive="' + esc(sel.id) + '"' }) + UI.btn('Discard', { kind: 'danger', size: 'sm', icon: 'trash', attrs: 'data-discard="' + esc(sel.id) + '"' }) + UI.btn('Open in ' + sel.goLabel, { size: 'sm', kind: 'ghost', attrs: 'data-godomain="' + esc(sel.id) + '"' }) + '</div>'
            + '<span class="muted" style="font-size:12px">Audit entries: ' + esc(sel.audit) + ', jobs.deadletter.discarded.</span>';
        }
      }
      // ---------------- Cache ----------------
      if (st.tab === 'cache') {
        const total = st.cache.reduce((a, c) => a + c.requests, 0), hits = st.cache.reduce((a, c) => a + c.hits, 0), entries = st.cache.reduce((a, c) => a + c.entries, 0), invL = st.cache.reduce((a, c) => a + c.inv.local, 0), invB = st.cache.reduce((a, c) => a + c.inv.bus, 0);
        const sel = st.cache.find((c) => c.ns === st.selNs);
        body += (st.cacheStore === 'memory' && st.instances > 1 ? UI.notice('<b>CACHE_STORE is memory on ' + st.instances + ' instances:</b> each keeps its own cache (CACHE_MAX_ENTRIES, least recently used first) and invalidations travel over the bus, so a write on one instance clears the entry on the other within the bus delay.', 'info') : '')
          + '<div class="stats">' + UI.stat(esc(st.cacheStore === 'redis' ? 'Redis' : 'memory'), 'Store', st.cacheStore === 'redis' ? 'shared, REDIS_URL' : 'per instance') + UI.stat(num(entries), 'Entries', st.cacheStore === 'redis' ? 'across the tenant' : 'on this instance') + UI.stat(pct(hits, total), 'Hit rate', 'last 24 h, ' + num(total) + ' reads') + UI.stat(num(invL + invB), 'Invalidations', num(invL) + ' local, ' + num(invB) + ' from the bus') + '</div>'
          + UI.table(['Namespace', 'Tier', 'TTL', { label: 'Requests', right: true }, { label: 'Hit rate', right: true }, { label: 'Invalidations', right: true }, { label: 'Entries', right: true }, { label: '', right: true }], st.cache.map((c) => ({ cells: ['<span style="font-weight:600">' + esc(c.ns) + '</span>', UI.pill(c.tier, c.tier === 'short' ? 'info' : c.tier === 'long' ? 'outline' : ''), '<span class="mono" style="font-size:11px">' + esc(c.ttl) + '</span>', '<span class="num">' + num(c.requests) + '</span>', '<span class="num' + (c.hits / c.requests < 0.85 ? '" style="color:var(--warn-fg)' : '') + '">' + pct(c.hits, c.requests) + '</span>', '<span class="num">' + (c.inv.local + c.inv.bus) + '</span>', '<span class="num">' + num(c.entries) + '</span>', UI.btn('Invalidate', { size: 'xs', attrs: 'data-invalidate="' + esc(c.ns) + '"' })], attrs: 'data-ns="' + esc(c.ns) + '"', selected: c.ns === st.selNs })), { minWidth: '940px' })
          + '<span class="muted" style="font-size:12px">The tenant cache (B-2102) keys on tenant, namespace and key; a miss runs the loader once and concurrent misses wait for it. Counted in exprsn_cache_requests_total and exprsn_cache_invalidations_total.</span>';
        if (sel) {
          insp = '<div class="eyebrow">Namespace</div><div style="font-size:15px;font-weight:600">' + esc(sel.ns) + '</div>'
            + UI.kv([['Tier', esc(sel.tier)], ['TTL', '<span class="mono" style="font-size:11px">' + esc(sel.ttl) + '</span>'], ['Requests', num(sel.requests)], ['Hit rate', pct(sel.hits, sel.requests)], ['Invalidations', sel.inv.local + ' local, ' + sel.inv.bus + ' from the bus'], ['Entries', num(sel.entries)]], 2)
            + (sel.hits / sel.requests < 0.85 ? UI.notice('Hit rate below 85 %: a short tier with frequent writes. Lengthening CACHE_TTL_SHORT_SECONDS trades freshness for load.', 'warn') : '')
            + '<div>' + UI.btn('Invalidate namespace', { size: 'sm', icon: 'refresh', attrs: 'data-invalidate="' + esc(sel.ns) + '"' }) + '</div>'
            + '<span class="muted" style="font-size:12px">Invalidation is broadcast over the bus; every instance drops its entries. Audited jobs.cache.invalidated.</span>';
        }
      }

      root.innerHTML = '<style>#main > .page > *{flex-shrink:0}#main .jobs-insp .kv .v{font-size:12px}#main .jobs-insp .meter{min-width:0}#main .page td .num{white-space:nowrap}</style>'
        + '<div class="page">' + UI.pagehead('Jobs and queues', 'Every queue, job and schedule on the one JobQueue; the work that gave up, and the tenant cache.', UI.pill(backendLabel(st), st.backend === 'redis' ? 'info' : 'outline') + UI.btn('Run a schedule', { attrs: 'data-goschedules' }) + UI.btn('Retry failed jobs', { kind: 'primary', icon: 'refresh', attrs: 'data-retryall', disabled: !failed }))
        + tabs + body + '</div>'
        + (insp ? '<aside class="inspector w360 jobs-insp" aria-label="Inspector">' + insp + '</aside>' : '');

      // ---- events ----
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-goschedules]', () => { st.tab = 'schedules'; ctx.rerender(); });
      ctx.on('click', '[data-godead]', () => { st.tab = 'deadletters'; st.selDead = 'dl-2'; ctx.rerender(); });
      ctx.on('click', '[data-gooverview]', () => ctx.navigate('overview'));
      ctx.on('click', '[data-gosetting]', (e, t) => { e.preventDefault(); ctx.navigate('configuration', { q: t.dataset.gosetting }); });
      ctx.on('click', '[data-menu]', (e, t) => {
        const k = t.dataset.menu;
        if (k === 'domain') menu(ctx, t, [['all', 'Every domain']].concat(DOMAINS.map((d) => [d, d])), st.domain, (v) => { st.domain = v; ctx.rerender(); });
        if (k === 'jobstate') menu(ctx, t, [['all', 'Every state'], ['queued', 'Queued'], ['running', 'Running'], ['succeeded', 'Succeeded'], ['failed', 'Failed'], ['cancelled', 'Cancelled'], ['preempted', 'Preempted']], st.jobState, (v) => { st.jobState = v; ctx.rerender(); });
        if (k === 'jobtype') menu(ctx, t, [['all', 'Every type']].concat(st.types.map((x) => [x.type, x.type])), st.jobType, (v) => { st.jobType = v; ctx.rerender(); });
      });
      const refocus = (selector) => { const i = ctx.$(selector); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } };
      ctx.on('input', '[data-typesearch]', (e, t) => { st.typeQuery = t.value; ctx.rerender(); refocus('[data-typesearch]'); });
      ctx.on('input', '[data-jobsearch]', (e, t) => { st.jobQuery = t.value; ctx.rerender(); refocus('[data-jobsearch]'); });
      ctx.on('click', '[data-window] [data-seg]', (e, t) => { st.window = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', 'tr[data-type]', (e, t) => { st.selType = t.dataset.type; ctx.rerender(); });
      ctx.on('click', 'tr[data-job]', (e, t) => { st.selJob = t.dataset.job; ctx.rerender(); });
      ctx.on('click', 'tr[data-sched]', (e, t) => { st.selSched = t.dataset.sched; ctx.rerender(); });
      ctx.on('click', 'tr[data-dead]', (e, t) => { if (e.target.closest('button')) return; st.selDead = t.dataset.dead; ctx.rerender(); });
      ctx.on('click', 'tr[data-ns]', (e, t) => { if (e.target.closest('button')) return; st.selNs = t.dataset.ns; ctx.rerender(); });
      ctx.on('click', '[data-openjob]', (e, t) => { e.preventDefault(); st.tab = 'jobs'; st.selJob = t.dataset.openjob; st.jobState = 'all'; st.jobType = 'all'; st.window = '7d'; st.jobQuery = ''; ctx.rerender(); });
      ctx.on('click', '[data-jobsfor]', (e, t) => { st.tab = 'jobs'; st.jobType = t.dataset.jobsfor; st.jobState = 'all'; st.window = '7d'; ctx.rerender(); });
      ctx.on('click', '[data-opentype]', (e, t) => { st.tab = 'queues'; st.selType = t.dataset.opentype; st.domain = 'all'; st.typeQuery = ''; ctx.rerender(); });

      // queues
      const selType = st.types.find((x) => x.type === st.selType);
      ctx.on('click', '[data-pausetype]', () => ctx.confirm({ title: 'Pause ' + esc(selType.type), tone: 'warn', tag: 'stops claiming', body: '<p class="fg2" style="margin:0">Jobs of this type keep being queued and none is claimed until it is resumed; running ones finish. Every instance honours the pause within one poll.</p>' + UI.field('Reason', UI.input('', { attrs: 'data-reason' })), kv: [['Queued now', num(selType.queued)], ['Running', String(selType.running)]], ok: 'Pause' }).then((ok) => { if (!ok) return; selType.paused = true; ctx.rerender(); ctx.toast(esc(selType.type) + ' paused. Audited jobs.type.paused.', 'warn'); }));
      ctx.on('click', '[data-resumetype]', () => { selType.paused = false; ctx.rerender(); ctx.toast(esc(selType.type) + ' resumed; claiming starts at the next poll. Audited jobs.type.resumed.', 'ok'); });
      ctx.on('click', '[data-retrytype]', () => ctx.confirm({ title: 'Retry failed ' + esc(selType.type) + ' jobs', tone: 'info', body: '<p class="fg2" style="margin:0">Every failed job of this type in the last 24 h is queued again with its payload and a fresh attempt count.</p>', kv: [['Failed 24 h', String(selType.failed24)]], ok: 'Retry ' + selType.failed24 }).then((ok) => { if (!ok) return; const n = selType.failed24; st.jobs.forEach((j) => { if (j.type === selType.type && j.state === 'failed') { j.state = 'queued'; j.attempts = 0; j.node = ''; j.started = null; j.duration = ''; j.error = null; j.events.push({ title: 'queued again by Mara Okafor', meta: '14:10', tone: 'info' }); } }); selType.queued += n; selType.failed24 = 0; ctx.rerender(); ctx.toast(n + ' ' + esc(selType.type) + (n === 1 ? ' job' : ' jobs') + ' queued again. Audited jobs.retried.', 'ok'); }));

      // jobs
      const selJob = st.jobs.find((x) => x.id === st.selJob);
      ctx.on('click', '[data-copytrace]', () => { try { navigator.clipboard.writeText(selJob.trace); } catch (e) { /* no clipboard */ } ctx.toast('Trace id copied.'); });
      ctx.on('click', '[data-canceljob]', () => ctx.confirm({ title: 'Cancel ' + esc(selJob.id), tone: 'danger', tag: 'after the current step', body: '<p class="fg2" style="margin:0">A queued job is dropped at once; a running one stops after its current step and keeps any checkpoint. The starter is told over their sockets.</p>' + UI.field('Reason', UI.input('', { attrs: 'data-reason' })), kv: [['Type', esc(selJob.type)], ['Progress', selJob.progress + ' %']], ok: 'Cancel job', cancel: 'Keep running' }).then((ok) => { if (!ok) return; selJob.state = 'cancelled'; selJob.events.push({ title: 'cancelled by Mara Okafor', meta: '14:10', tone: 'warn' }); const t = st.types.find((x) => x.type === selJob.type); if (t) { if (selJob.started) t.running = Math.max(0, t.running - 1); else t.queued = Math.max(0, t.queued - 1); } ctx.rerender(); ctx.toast(esc(selJob.id) + ' cancelled. Audited jobs.cancelled.', 'warn'); }));
      ctx.on('click', '[data-retryjob]', () => ctx.confirm({ title: (selJob.state === 'preempted' ? 'Resume ' : 'Retry ') + esc(selJob.id), tone: 'info', body: '<p class="fg2" style="margin:0">' + (selJob.state === 'preempted' ? 'Continues from the last checkpoint when GPUs are free.' : 'Queues the job again with the same payload and a fresh attempt count; the failed attempts stay in its history.') + '</p>', kv: [['Type', esc(selJob.type)], ['Attempts so far', String(selJob.attempts)]], ok: selJob.state === 'preempted' ? 'Resume' : 'Retry' }).then((ok) => { if (!ok) return; selJob.state = 'queued'; selJob.attempts = 0; selJob.node = ''; selJob.started = null; selJob.duration = ''; selJob.error = null; selJob.ageMin = 0; selJob.events.push({ title: 'queued again by Mara Okafor', meta: '14:10', tone: 'info' }); const t = st.types.find((x) => x.type === selJob.type); if (t) { t.queued += 1; if (t.failed24) t.failed24 -= 1; } ctx.rerender(); ctx.toast(esc(selJob.id) + ' queued again. Audited jobs.retried.', 'ok'); }));
      const retryAll = () => { const failedJobs = st.jobs.filter((j) => j.state === 'failed'); if (!failedJobs.length) { ctx.toast('No failed jobs in the window.'); return; } ctx.confirm({ title: 'Retry ' + failedJobs.length + ' failed jobs', tone: 'info', body: '<p class="fg2" style="margin:0">Each is queued again with its payload and a fresh attempt count. Jobs whose cause is still there (a host outside the allowed list, a 404 challenge) will fail again and say so.</p>', kv: [['Types', esc(Array.from(new Set(failedJobs.map((j) => j.type))).join(', '))]], ok: 'Retry all' }).then((ok) => { if (!ok) return; failedJobs.forEach((j) => { j.state = 'queued'; j.attempts = 0; j.node = ''; j.started = null; j.duration = ''; j.error = null; j.ageMin = 0; j.events.push({ title: 'queued again by Mara Okafor', meta: '14:10', tone: 'info' }); const t = st.types.find((x) => x.type === j.type); if (t) { t.queued += 1; t.failed24 = Math.max(0, t.failed24 - 1); } }); st.tab = 'jobs'; st.jobState = 'all'; ctx.rerender(); ctx.toast(failedJobs.length + ' jobs queued again. Audited jobs.retried.', 'ok'); }); };
      ctx.on('click', '[data-retryall]', retryAll);
      if (st.openRetryAll) { st.openRetryAll = false; setTimeout(retryAll, 50); }

      // schedules
      const selSched = st.schedules.find((x) => x.name === st.selSched) || st.schedules[0];
      const runNow = () => ctx.confirm({ title: 'Run ' + esc(selSched.name) + ' now', tone: 'info', body: '<p class="fg2" style="margin:0">Queues one run outside its bucket for ' + esc(selSched.targets) + '. The next scheduled run is unchanged.</p>', kv: [['Targets', esc(selSched.targets)], ['Next scheduled', esc(selSched.next)]], ok: 'Run now' }).then((ok) => { if (!ok) return; selSched.last = '14:10'; selSched.result = 'ok, run by Mara Okafor'; const t = st.types.find((x) => x.type === selSched.name); if (t) t.queued += 1; ctx.rerender(); ctx.toast(esc(selSched.name) + ' queued for ' + esc(selSched.targets) + '. Audited jobs.schedule.run.', 'ok'); });
      ctx.on('click', '[data-runnow]', runNow);
      if (st.openRunNow) { st.openRunNow = false; setTimeout(runNow, 50); }
      ctx.on('click', '[data-pausesched]', () => ctx.confirm({ title: 'Pause ' + esc(selSched.name), tone: 'warn', tag: 'skips buckets', body: '<p class="fg2" style="margin:0">No run is queued until it is resumed; the buckets it misses are not caught up. Alerts that depend on it (RPO, drift, expiry) go quiet too.</p>' + UI.field('Reason', UI.input('', { attrs: 'data-reason' })), ok: 'Pause' }).then((ok) => { if (!ok) return; selSched.paused = true; ctx.rerender(); ctx.toast(esc(selSched.name) + ' paused. Audited jobs.schedule.paused.', 'warn'); }));
      ctx.on('click', '[data-resumesched]', () => { selSched.paused = false; selSched.next = 'at the next bucket'; ctx.rerender(); ctx.toast(esc(selSched.name) + ' resumed. Audited jobs.schedule.resumed.', 'ok'); });

      // dead letters
      ctx.on('click', '[data-redrive]', (e, t) => { const d = st.dead.find((x) => x.id === t.dataset.redrive); if (!d) return; ctx.confirm({ title: 'Redrive ' + esc(d.item.split(',')[0]), tone: 'info', body: '<p class="fg2" style="margin:0">Queues a new <span class="mono">' + esc(d.type) + '</span> job with the original payload. If the cause is still there it fails again and comes back here with one more attempt counted.</p>', kv: [['Source', esc(d.source)], ['Attempts so far', String(d.attempts)]], ok: 'Redrive' }).then((ok) => { if (!ok) return; redrive(st, d); st.tab = 'jobs'; st.jobState = 'all'; st.jobType = 'all'; st.jobQuery = ''; ctx.rerender(); ctx.toast('Redriven as job j-' + (st.nextId - 1) + ' (queued). Audited ' + esc(d.audit) + '.', 'ok'); }); });
      ctx.on('click', '[data-discard]', (e, t) => { const d = st.dead.find((x) => x.id === t.dataset.discard); if (!d) return; ctx.confirm({ title: 'Discard ' + esc(d.item.split(',')[0]), tone: 'danger', tag: 'destructive', body: '<p class="fg2" style="margin:0">The item is dropped for good; the reason, the attempts and your note stay in the audit chain. For a moderation item the flag stays open for a reviewer.</p>' + UI.field('Reason', UI.input('', { attrs: 'data-reason' })), kv: [['Source', esc(d.source)]], ok: 'Discard' }).then((ok) => { if (!ok) return; st.dead = st.dead.filter((x) => x.id !== d.id); ctx.rerender(); ctx.toast('Discarded. Audited jobs.deadletter.discarded.', 'danger'); }); });
      ctx.on('click', '[data-godomain]', (e, t) => { const d = st.dead.find((x) => x.id === t.dataset.godomain); if (d) ctx.navigate(d.go[0], d.go[1]); });

      // cache
      ctx.on('click', '[data-invalidate]', (e, t) => { const c = st.cache.find((x) => x.ns === t.dataset.invalidate); if (!c) return; ctx.confirm({ title: 'Invalidate ' + esc(c.ns), tone: 'info', tag: 'broadcast', body: '<p class="fg2" style="margin:0">Drops every entry of the namespace for this tenant and publishes the invalidation on the bus, so every instance drops its own. The next read runs the loader once.</p>', kv: [['Entries', num(c.entries)], ['Store', st.cacheStore === 'redis' ? 'Redis, shared' : 'memory, per instance']], ok: 'Invalidate' }).then((ok) => { if (!ok) return; c.inv.local += 1; c.inv.bus += st.instances - 1; c.entries = 0; st.selNs = c.ns; ctx.rerender(); ctx.toast(esc(c.ns) + ' invalidated on every instance. Audited jobs.cache.invalidated.', 'ok'); }); });
    }
  });

  function redrive(st, d) {
    const id = 'j-' + st.nextId++;
    st.jobs.unshift({ id, type: d.type === 'firehose' ? 'firehose' : d.type, tenant: 'Northwind', workspace: d.type === 'moderation' ? 'Finance Ops' : '', state: 'queued', progress: 0, attempts: 0, created: '14:10', started: null, ageMin: 0, duration: '', node: '', payload: d.type === 'moderation' ? ['flagId', 'providerId'] : d.type === 'webhook.deliver' ? ['webhookId', 'eventId'] : d.type === 'plugin.invoke' ? ['pluginId', 'eventId', 'chain'] : d.type === 'channels.send' ? ['sessionId', 'messageId'] : ['workflowId', 'runId', 'fromStep'], message: 'redriven from the dead-letter queue by Mara Okafor', error: null, trace: Math.random().toString(16).slice(2, 10) + 'c0ffee4a5b6c7d8e9f0a1b2c3d4e', events: [{ title: 'redriven from ' + d.source, text: 'attempt ' + (d.attempts + 1) + ' of the original item', meta: '14:10:00', tone: 'info' }] });
    st.dead = st.dead.filter((x) => x.id !== d.id); st.selJob = id;
    const t = st.types.find((x) => x.type === d.type); if (t) t.queued += 1;
  }
})();
