(function () {
  const { UI, esc } = App;

  // ---- demo data: Northwind, Finance Ops, signed in as Mara Okafor ----
  const ME = 'Mara Okafor';
  const PEOPLE = [
    { id: 'u-priya', name: 'Priya Nair', user: 'pnair', ws: ['Finance Ops'], clearance: 'restricted' },
    { id: 'u-tomasz', name: 'Tomasz Weber', user: 'tweber', ws: ['Finance Ops'], clearance: 'internal' },
    { id: 'u-jonas', name: 'Jonas Lindqvist', user: 'jlindqvist', ws: ['Finance Ops', 'People Ops'], clearance: 'confidential' },
    { id: 'u-aisha', name: 'Aisha Bello', user: 'abello', ws: ['People Ops'], clearance: 'confidential' },
    { id: 'u-felix', name: 'Felix Brandt', user: 'fbrandt', ws: ['Finance Ops'], clearance: 'confidential' },
    { id: 'u-lena', name: 'Lena Hoffmann', user: 'lhoffmann', ws: ['Finance Ops', 'Field Sales'], clearance: 'confidential' },
    { id: 'u-samir', name: 'Samir Haddad', user: 'shaddad', ws: ['Field Sales'], clearance: 'internal' },
    { id: 'u-noor', name: 'Noor Rahimi', user: 'nrahimi', ws: ['People Ops', 'Finance Ops'], clearance: 'internal' }
  ];
  const person = (id) => PEOPLE.find((p) => p.id === id);
  const CEILING = { 'Finance Ops': 'confidential', 'People Ops': 'internal', 'Field Sales': 'internal' };
  const LEVEL = { public: 1, internal: 2, confidential: 3, restricted: 4 };

  const baseConvos = () => [
    { id: 'c-priya', kind: 'direct', with: 'u-priya', label: 'confidential', unread: 2, muted: false, notify: 'all', last: 'today 14:02', role: 'member', members: ['u-priya'] },
    { id: 'c-close', kind: 'group', title: 'Q3 close room', ws: 'Finance Ops', label: 'confidential', unread: 1, muted: false, notify: 'all', last: 'today 13:47', role: 'owner', members: ['u-priya', 'u-tomasz', 'u-felix', 'u-noor'], roles: { 'u-priya': 'admin', 'u-tomasz': 'member', 'u-felix': 'member', 'u-noor': 'member' } },
    { id: 'c-vendors', kind: 'group', title: 'Vendor renewals', ws: 'Finance Ops', label: 'internal', unread: 0, muted: false, notify: 'mentions', last: '18 Sep 17:20', role: 'admin', members: ['u-jonas', 'u-lena', 'u-tomasz'], roles: { 'u-jonas': 'owner', 'u-lena': 'member', 'u-tomasz': 'member' } },
    { id: 'c-tomasz', kind: 'direct', with: 'u-tomasz', label: 'internal', unread: 0, muted: true, mutedUntil: '20 Sep 09:00', notify: 'all', last: '17 Sep 09:12', role: 'member', members: ['u-tomasz'] },
    { id: 'c-lena', kind: 'direct', with: 'u-lena', label: 'confidential', unread: 0, muted: false, notify: 'none', last: '12 Sep 16:40', role: 'member', members: ['u-lena'] }
  ];
  const baseMessages = () => ({
    'c-close': [
      { id: 'm1', author: 'u-priya', body: 'Accruals are in. Two card lines still have no ledger match; I put them in the reconciliation sheet.', at: 'today 11:02', reactions: [{ kind: 'insightful', count: 2, mine: true }], pinned: true, pinnedBy: ME, attachments: [{ fileId: 'f-recon', name: 'card-reconciliation-q3.xlsx', type: 'Excel', size: '212 KB', state: 'ready' }] },
      { id: 'm2', author: 'u-tomasz', body: 'The Lisbon programme overran by 60.5% against its allocation, not 71%. The calc step is attached to the conversation.', at: 'today 11:40', replyTo: 'm1', reactions: [{ kind: 'like', count: 3, mine: false }], replyCount: 2, thread: [
        { id: 'm2a', author: 'u-felix', body: 'Which inputs did the calc use, the approved exception or the original budget?', at: 'today 11:52' },
        { id: 'm2b', author: 'u-tomasz', body: 'The approved exception, 38,000 EUR. Without it the figure is 71%.', at: 'today 11:58' }] },
      { id: 'm3', author: 'me', body: 'Thanks both. I will take the 60.5% figure into the board pack and cite the calc result.', at: 'today 12:05', edited: true, editedAt: 'today 12:06', reactions: [] },
      { id: 'm4', author: 'u-noor', body: null, state: 'hidden', at: 'today 12:30', hiddenFor: 'blocked' },
      { id: 'm5', author: 'u-felix', body: 'Forwarding the supplier note from the vendor room so we have it here.', at: 'today 13:20', forwardedFrom: 'Vendor renewals', reactions: [], attachments: [{ fileId: 'f-note', name: 'fabrikam-renewal-note.pdf', type: 'PDF', size: '88 KB', state: 'pending' }] },
      { id: 'm6', author: 'u-priya', body: null, state: 'deleted', at: 'today 13:41' },
      { id: 'm7', author: 'u-priya', body: 'Draft pack is in Files under Finance Ops / Board / Q3. Comments by Monday 12:00 please.', at: 'today 13:47', reactions: [{ kind: 'celebrate', count: 1, mine: false }] }
    ],
    'c-priya': [
      { id: 'p1', author: 'u-priya', body: 'Can you look at F-2291 before the 15:00 call? The numeric grounding rule fired on the board figure.', at: 'today 13:58', reactions: [] },
      { id: 'p2', author: 'u-priya', body: 'The flag is in your queue. The span is the 71% line.', at: 'today 14:02', reactions: [] }
    ],
    'c-vendors': [
      { id: 'v1', author: 'u-jonas', body: 'Fabrikam renewal lands 1 Oct. Service credits cap at 12.5% in the 2025 MSA.', at: '18 Sep 16:55', reactions: [{ kind: 'like', count: 2, mine: true }], pinned: true, pinnedBy: 'Jonas Lindqvist' },
      { id: 'v2', author: 'u-lena', body: 'The Contracts KB has the 2025 version indexed now; the 2024 chunk was retired.', at: '18 Sep 17:20', reactions: [] }
    ],
    'c-tomasz': [{ id: 't1', author: 'u-tomasz', body: 'Travel export is in quarantine; the IBAN rule held it.', at: '17 Sep 09:12', reactions: [] }],
    'c-lena': [{ id: 'l1', author: 'u-lena', body: 'Folder "Board / Q3" is now a knowledge source. Chat cites the pack by path.', at: '12 Sep 16:40', reactions: [] }]
  });
  const REACTIONS = ['like', 'celebrate', 'support', 'insightful', 'funny'];
  const basePosts = () => [
    { id: 'po1', ws: 'Finance Ops', author: 'u-priya', body: 'Q3 close checklist is published. Owners, tick your lines by Thursday. #q3-close #finance', label: 'confidential', state: 'published', tags: ['q3-close', 'finance'], counts: { comments: 3, reposts: 1, reactions: { like: 6, celebrate: 2, support: 0, insightful: 1, funny: 0 } }, mine: { reactions: ['like'], bookmarked: true, reposted: false }, at: 'today 09:10', media: [], comments: [
      { id: 'cm1', author: 'u-tomasz', body: 'Travel lines done.', at: 'today 09:40' }, { id: 'cm2', author: 'u-felix', body: 'Cards by tomorrow.', at: 'today 10:02' }, { id: 'cm3', author: 'u-priya', body: 'Thanks, noted.', at: 'today 10:05', parentId: 'cm2' }] },
    { id: 'po2', ws: 'Finance Ops', author: 'u-felix', body: 'The video-to-notes workflow v3 is published to Finance Ops. It writes summaries into the Meetings app. #workflows', label: 'internal', state: 'published', tags: ['workflows'], counts: { comments: 0, reposts: 0, reactions: { like: 2, celebrate: 1, support: 0, insightful: 3, funny: 0 } }, mine: { reactions: [], bookmarked: false, reposted: false }, at: 'today 08:20', media: [{ fileId: 'f-wf', name: 'workflow-v3.png', type: 'PNG', available: true }], comments: [] },
    { id: 'po3', ws: 'Finance Ops', group: 'Audit readiness', author: 'u-jonas', body: 'Group feed: the auditors arrive 6 Oct. Evidence folders are frozen on 3 Oct. #audit', label: 'confidential', state: 'published', tags: ['audit'], counts: { comments: 1, reposts: 0, reactions: { like: 4, celebrate: 0, support: 2, insightful: 0, funny: 0 } }, mine: { reactions: ['support'], bookmarked: false, reposted: false }, at: '18 Sep 15:30', media: [], comments: [{ id: 'cm4', author: 'u-lena', body: 'Knowledge sources frozen the same day.', at: '18 Sep 15:50' }] },
    { id: 'po4', ws: 'Finance Ops', author: 'u-tomasz', body: 'Reposting Priya\'s checklist for the Lisbon team.', label: 'confidential', state: 'published', repostOf: 'po1', tags: [], counts: { comments: 0, reposts: 0, reactions: { like: 1, celebrate: 0, support: 0, insightful: 0, funny: 0 } }, mine: { reactions: [], bookmarked: false, reposted: false }, at: '18 Sep 12:00', media: [], comments: [] },
    { id: 'po5', ws: 'Finance Ops', author: 'u-lena', body: 'Reminder: the 2024 MSA chunk is retired from Contracts KB. Cite the 2025 version. #finance', label: 'internal', state: 'published', tags: ['finance'], counts: { comments: 0, reposts: 2, reactions: { like: 3, celebrate: 0, support: 0, insightful: 2, funny: 1 } }, mine: { reactions: [], bookmarked: true, reposted: true }, at: '17 Sep 10:15', media: [], comments: [] },
    { id: 'po6', ws: 'Finance Ops', author: 'u-noor', body: null, label: 'internal', state: 'hidden', hiddenFor: 'blocked', tags: [], counts: { comments: 0, reposts: 0, reactions: {} }, mine: { reactions: [], bookmarked: false, reposted: false }, at: '17 Sep 09:00', media: [], comments: [] }
  ];
  const baseDigests = () => [
    { id: 'd1', ws: 'Finance Ops', week: '7 Sep to 14 Sep', label: 'internal', state: 'ready', profile: 'analyst', posts: [{ id: 'po5', score: 13 }, { id: 'po2', score: 9 }], summary: 'The week centred on the Q3 close. Lena Hoffmann retired the 2024 MSA chunk [1]; Felix Brandt published workflow v3, which now writes meeting summaries into the Meetings app [2].' },
    { id: 'd2', ws: 'Finance Ops', week: '31 Aug to 7 Sep', label: 'internal', state: 'empty', posts: [] },
    { id: 'd3', ws: 'Finance Ops', week: '24 Aug to 31 Aug', label: 'internal', state: 'failed', error: 'profile analyst: 503 model unavailable', posts: [{ id: 'po1', score: 14 }] }
  ];
  const baseSocial = () => ({
    contactRule: 'workspace',
    blocks: [{ id: 'u-noor', at: '16 Sep 18:02' }],
    mutes: [{ id: 'u-samir', expiresAt: '26 Sep 09:00', at: '19 Sep 09:00' }],
    following: ['u-priya', 'u-felix', 'u-lena', 'u-jonas'],
    followers: ['u-priya', 'u-tomasz', 'u-felix'],
    lists: [{ id: 'l1', name: 'Close team', description: 'Everyone on the Q3 close', members: ['u-priya', 'u-tomasz', 'u-felix'] }, { id: 'l2', name: 'Admins', description: '', members: ['u-jonas', 'u-aisha'] }]
  });
  const nameOf = (id) => id === 'me' ? ME : (person(id) || {}).name || id;

  App.register({
    id: 'messages', title: 'Messages and feed', summary: 'Direct and group conversations, threads, reactions and pins; the workspace feed, digests and trending; blocks, mutes, follows and lists', crumb: ['Messages and feed'],
    label: (st) => { if (st.view === 'messages') { const c = (st.convos || []).find((x) => x.id === st.convo); return c ? c.label : null; } return st.view === 'feed' ? 'internal' : null; },
    commands: [
      { label: 'New conversation', sub: 'Messages and feed', run(app) { const s = app.stateFor('messages'); s.view = 'messages'; s.openNew = true; app.render(); } },
      { label: 'Write a post', sub: 'Messages and feed', run(app) { const s = app.stateFor('messages'); s.view = 'feed'; s.feedSeg = 'ws'; app.render(); } }
    ],
    states: [
      { title: 'Blocked user never appears', tone: 'info', text: 'Noor Rahimi is blocked. Her messages, posts, typing and presence are left out for you on every instance; she only reads "does not accept messages from you".', apply(ctx) { const st = ctx.state; st.view = 'messages'; st.convo = 'c-close'; st.showBlockNote = true; ctx.rerender(); } },
      { title: 'Post held for review', tone: 'warn', text: 'A require-approval guardrail held the post: 202, visible only to its author, with a hold flag in the Flags queue.', apply(ctx) { const st = ctx.state; st.view = 'feed'; st.feedSeg = 'ws'; if (!st.posts.some((p) => p.id === 'po-held')) st.posts.unshift({ id: 'po-held', ws: 'Finance Ops', author: 'me', body: 'Draft board figures: travel overran 60.5% against allocation; IBAN DE89 3704 0044 0532 0130 00 appears on two unmatched lines.', label: 'confidential', state: 'held', flag: 'F-2298', tags: [], counts: { comments: 0, reposts: 0, reactions: {} }, mine: { reactions: [], bookmarked: false, reposted: false }, at: 'just now', media: [], comments: [] }); ctx.rerender(); ctx.toast('Post held for review (202). Only you can see it until a reviewer decides F-2298.', 'warn', 5000); } },
      { title: 'Contact rule refuses', tone: 'danger', text: 'Starting a conversation with someone whose rule or block excludes you is 403 with step contact, the same words either way.', apply(ctx) { const st = ctx.state; st.view = 'messages'; st.openNew = true; st.newKind = 'direct'; st.newTarget = 'u-aisha'; st.newProblem = 'contact'; ctx.rerender(); } },
      { title: 'Semantic search unavailable', tone: 'warn', text: 'Without MESSAGING_EMBED_MODEL, semantic and hybrid modes answer 409 and the default is keyword.', apply(ctx) { const st = ctx.state; st.view = 'messages'; st.convo = 'c-close'; st.noEmbed = true; st.openSearch = true; st.searchMode = 'semantic'; ctx.rerender(); } },
      { title: 'Attachment in quarantine', tone: 'warn', text: 'A file whose current version has not passed its scan cannot be attached: 409 until the file.scan job finishes.', apply(ctx) { const st = ctx.state; st.view = 'messages'; st.convo = 'c-close'; st.attachProblem = true; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      if (!st.convos) { st.convos = baseConvos(); st.messages = baseMessages(); st.posts = basePosts(); st.digests = baseDigests(); st.social = baseSocial(); st.digestEnabled = true; st.digestProfile = 'analyst'; }
      st.view = st.view || 'messages'; st.filter = st.filter || 'all'; st.q = st.q || ''; st.feedSeg = st.feedSeg || 'home'; st.peopleTab = st.peopleTab || 'blocks'; st.inspTab = st.inspTab || 'people';
      if (ctx.params.convo) { st.view = 'messages'; st.convo = ctx.params.convo; delete ctx.params.convo; }
      if (ctx.params.post) { st.view = 'feed'; st.feedSeg = 'ws'; st.focusPost = ctx.params.post; delete ctx.params.post; }
      if (ctx.params.tag) { st.view = 'feed'; st.feedSeg = 'tag'; st.tag = ctx.params.tag; delete ctx.params.tag; }

      const nav = '<div class="hstack" style="margin-bottom:4px">' + UI.seg([{ id: 'messages', label: 'Messages' }, { id: 'feed', label: 'Feed' }, { id: 'people', label: 'People' }], st.view, 'data-view') + '</div>';
      const body = st.view === 'messages' ? renderMessages(ctx, st) : st.view === 'feed' ? renderFeed(ctx, st) : renderPeople(ctx, st);
      const tail = '<div style="margin-top:auto;padding-top:12px"><div class="eyebrow" style="margin-bottom:8px">States to design from this page</div>' + UI.states(this.states) + '</div>';

      root.innerHTML = '<style>'
        + '#main .messages-list{display:flex;flex-direction:column;gap:2px}'
        + '#main .messages-thread{display:flex;flex-direction:column;gap:10px;max-width:760px}'
        + '#main .messages-msg{display:flex;flex-direction:column;gap:4px;padding:8px 10px;border-radius:8px}#main .messages-msg:hover{background:var(--sel)}#main .messages-msg.mine{background:var(--accent-tint)}#main .messages-msg .mactions{opacity:0;display:flex;gap:4px;flex-wrap:wrap}#main .messages-msg:hover .mactions{opacity:1}'
        + '#main .messages-meta{display:flex;gap:8px;align-items:center;font-size:12px;color:var(--muted);flex-wrap:wrap}#main .messages-body{font-size:14px;line-height:1.5}'
        + '#main .messages-quote{border-left:2px solid var(--line2);padding:2px 8px;font-size:12px;color:var(--fg2);margin-bottom:2px}'
        + '#main .messages-tomb{font-size:12px;color:var(--muted);font-style:italic;padding:6px 10px;border:1px dashed var(--line);border-radius:6px}'
        + '#main .messages-att{display:inline-flex;align-items:center;gap:6px;padding:4px 8px;border:1px solid var(--line);border-radius:6px;font-size:12px;background:var(--panel)}'
        + '#main .messages-composer{border:1px solid var(--line);border-radius:8px;background:var(--panel);padding:10px;display:flex;flex-direction:column;gap:8px}#main .messages-composer textarea{min-height:56px}'
        + '#main .messages-post{display:flex;flex-direction:column;gap:8px;padding:14px;border:1px solid var(--line);border-radius:8px;background:var(--panel)}#main .messages-post.held{border-color:var(--warn-fg)}#main .messages-post .pactions{display:flex;gap:4px;flex-wrap:wrap;align-items:center}'
        + '#main .messages-comment{padding:6px 10px;border-left:2px solid var(--line);font-size:13px}#main .messages-comment.reply{margin-left:18px}'
        + '#main .messages-tag{color:var(--accent);text-decoration:none;font-weight:600}'
        + '#main .messages-presence{font-size:12px;color:var(--muted);min-height:16px}'
        + '</style>' + body.replace('%NAV%', nav).replace('%TAIL%', tail);

      ctx.on('click', '[data-view]', (e, t) => { const b = e.target.closest('[data-seg]'); if (b) { st.view = b.dataset.seg; ctx.rerender(); } });
      ctx.on('click', '.state-card', (e, t) => ctx.app.applyState(+t.dataset.state));
      wireMessages(ctx, st); wireFeed(ctx, st); wirePeople(ctx, st);
    }
  });

  // ---------------- Messages ----------------
  function convoTitle(c) { return c.kind === 'direct' ? nameOf(c.with) : c.title; }
  function renderMessages(ctx, st) {
    const convos = st.convos.filter((c) => (st.filter === 'all' || (st.filter === 'unread' ? c.unread > 0 : c.kind === st.filter)) && (!st.q || convoTitle(c).toLowerCase().includes(st.q.toLowerCase())));
    if (!st.convo || !st.convos.some((c) => c.id === st.convo)) st.convo = convos.length ? convos[0].id : null;
    const c = st.convos.find((x) => x.id === st.convo);
    const list = '<div class="leftpane w320"><div class="hstack"><div class="eyebrow grow">Conversations</div>' + UI.btn('New', { size: 'sm', icon: 'plus', attrs: 'data-newconvo' }) + '</div>'
      + UI.search('Search conversations', 'data-cq', st.q)
      + '<div class="hstack gap6">' + UI.seg([{ id: 'all', label: 'All' }, { id: 'direct', label: 'Direct' }, { id: 'group', label: 'Group' }, { id: 'unread', label: 'Unread' }], st.filter, 'data-cfilter') + '</div>'
      + '<div class="messages-list">' + convos.map((x) => UI.listItem(esc(convoTitle(x)) + (x.muted ? ' <span class="muted" style="font-size:11px">muted</span>' : ''), esc((x.kind === 'group' ? x.ws + ', ' + (x.members.length + 1) + ' people' : 'direct') + ', ' + x.last), { active: x.id === st.convo, attrs: 'data-convo="' + x.id + '"', right: (x.unread ? UI.pill(String(x.unread), 'accent') : '') + UI.label(x.label, { sm: true }) })).join('') + (convos.length ? '' : UI.empty('No conversations match', 'Clear the filter or search.')) + '</div></div>';
    if (!c) return '<div class="page">%NAV%' + UI.pagehead('Messages', 'No conversation selected.') + UI.empty('Nothing here yet', 'Start a conversation with someone who shares a workspace with you.', UI.btn('New conversation', { kind: 'primary', attrs: 'data-newconvo' })) + '%TAIL%</div>';
    const msgs = st.messages[c.id] || [];
    const blockedLeftOut = msgs.filter((m) => m.hiddenFor === 'blocked').length;
    const sub = c.kind === 'direct' ? 'Direct conversation with ' + esc(nameOf(c.with)) + '. Both of you share Finance Ops; the label is the highest shared ceiling.' : esc(c.ws) + ', ' + (c.members.length + 1) + ' people, you are ' + esc(c.role) + '. Members read from the moment they were added.';
    const head = UI.pagehead(convoTitle(c), sub, UI.label(c.label) + UI.btn('Search', { icon: 'search', size: 'sm', attrs: 'data-msearch' }) + UI.btn('Summary', { icon: 'brain', size: 'sm', attrs: 'data-summary' }) + UI.btn('Digest', { size: 'sm', attrs: 'data-digest' }) + UI.btn('Mark read', { kind: 'ghost', size: 'sm', attrs: 'data-markread', disabled: !c.unread }));
    const notices = (st.showBlockNote && blockedLeftOut ? UI.notice('<b>' + blockedLeftOut + ' message from a blocked person is left out.</b> You blocked Noor Rahimi on 16 Sep. Her messages, reactions, receipts, typing and presence never reach your sockets on any instance; she sees this conversation without yours and reads only "does not accept messages from you". <a href="#" data-gopeople>Manage blocks</a>', 'info', UI.btn('Hide', { kind: 'ghost', size: 'sm', attrs: 'data-hideblock' })) : '')
      + (st.attachProblem ? UI.problem('Attachment refused (409)', 'fabrikam-renewal-note.pdf is still in quarantine: version 1 is scanned by the file.scan job (type check, text classifier, ClamAV). Attach it when its state is ready, or pick another file.', '9e1c4a0f22b64d8fa1e6c3b7d5f20a11') + '<div>' + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearattach' }) + '</div>' : '')
      + (st.sendProblem ? UI.problem('Message refused by a guardrail (422, step guardrails)', 'PII-IBAN in Finance baseline v12 blocked the text at the user-input checkpoint. Nothing was sent or stored. Remove the account number or send it through the file store with the confidential label.', '4bf92f3577b34da6a3ce929d0e0e4736') + '<div>' + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearsend' }) + '</div>' : '')
      + (st.lastSummary ? UI.panel(st.lastSummary.kind === 'digest' ? 'Catch-up digest' : 'Summary', '<div class="serif" style="font-size:15px;line-height:1.5">' + st.lastSummary.text + '</div><div class="muted" style="font-size:12px">Profile ' + esc(st.lastSummary.profile) + ', ' + st.lastSummary.n + ' messages you can see were numbered and sent. Citations name only those; the answer passed the model-output checkpoint.</div>', { actions: UI.btn('Close', { kind: 'ghost', size: 'xs', attrs: 'data-closesummary' }) }) : '');
    const thread = '<div class="messages-thread">' + msgs.map((m) => renderMsg(c, m, st)).join('') + '</div>';
    const typing = c.kind === 'group' ? 'Tomasz Weber is typing. Priya Nair and Felix Brandt are online. Read by Priya Nair and Felix Brandt up to 13:47.' : c.with === 'u-priya' ? 'Priya Nair is online. Read up to 14:02.' : nameOf(c.with) + ' was last seen ' + esc(c.last) + '.';
    const composer = '<div class="messages-composer">' + (st.replyTo ? '<div class="messages-quote hstack"><span class="grow">Replying to ' + esc(nameOf((msgs.find((m) => m.id === st.replyTo) || {}).author || '')) + '</span>' + UI.iconbtn('x', 'Cancel reply', { attrs: 'data-cancelreply', cls: 'sm ghost' }) + '</div>' : '')
      + UI.textarea(st.draft || '', { placeholder: 'Message ' + convoTitle(c) + '. Up to 10,000 characters; screened at the user-input checkpoint.', attrs: 'data-draft', rows: 2 })
      + '<div class="hstack wrap"><span class="hstack gap6">' + UI.btn('Attach from Files', { size: 'sm', icon: 'attach', attrs: 'data-attach' }) + (st.pendingAttach ? '<span class="messages-att">' + UI.icon('attach', 12) + esc(st.pendingAttach) + UI.iconbtn('x', 'Remove', { attrs: 'data-unattach', cls: 'sm ghost' }) + '</span>' : '') + '</span><span class="grow"></span><span class="muted" style="font-size:12px">@username mentions notify people whose rule is mentions</span>' + UI.btn('Send', { kind: 'primary', size: 'sm', icon: 'send', attrs: 'data-send' }) + '</div></div>';
    const insp = renderInspector(c, msgs, st);
    return list + '<div class="page">%NAV%' + head + notices + thread + '<div class="messages-presence">' + typing + '</div>' + composer + '%TAIL%</div><aside class="inspector w360" aria-label="Conversation details">' + insp + '</aside>';
  }
  function renderMsg(c, m, st) {
    if (m.state === 'deleted') return '<div class="messages-tomb">Message deleted by ' + esc(nameOf(m.author)) + ', ' + esc(m.at) + '. The body, attachments, terms and reactions are gone; the row stays as a tombstone.</div>';
    if (m.state === 'hidden') return m.hiddenFor === 'blocked' ? '' : '<div class="messages-tomb">Message hidden by moderation, ' + esc(m.at) + '.</div>';
    const mine = m.author === 'me';
    const canDelete = mine || c.role === 'owner' || c.role === 'admin';
    const quoted = m.replyTo ? (st.messages[c.id] || []).find((x) => x.id === m.replyTo) : null;
    return '<div class="messages-msg' + (mine ? ' mine' : '') + '" data-msg="' + m.id + '">'
      + (quoted ? '<div class="messages-quote">' + esc(nameOf(quoted.author)) + ': ' + esc((quoted.body || '').slice(0, 90)) + (quoted.body && quoted.body.length > 90 ? '…' : '') + '</div>' : '')
      + (m.forwardedFrom ? '<div class="muted" style="font-size:11px">Forwarded from ' + esc(m.forwardedFrom) + '</div>' : '')
      + '<div class="messages-meta"><b style="color:var(--fg)">' + esc(nameOf(m.author)) + '</b><span>' + esc(m.at) + '</span>' + (m.edited ? '<span>edited ' + esc(m.editedAt || '') + '</span>' : '') + (m.pinned ? UI.pill('pinned', 'accent') : '') + '</div>'
      + '<div class="messages-body">' + esc(m.body) + '</div>'
      + ((m.attachments || []).length ? '<div class="hstack wrap gap6">' + m.attachments.map((a) => '<a href="#" class="messages-att" data-gofile="' + esc(a.fileId) + '" title="Open in Files">' + UI.icon('attach', 12) + esc(a.name) + ' <span class="muted">' + esc(a.type) + ', ' + esc(a.size) + '</span>' + (a.state === 'pending' ? UI.pill('scanning', 'warn') : '') + '</a>').join('') + '</div>' : '')
      + '<div class="hstack wrap gap6">' + (m.reactions || []).filter((r) => r.count).map((r) => UI.chip(esc(r.kind) + ' ' + r.count, r.mine, 'data-react="' + m.id + '" data-kind="' + r.kind + '"')).join('') + (m.replyCount ? UI.btn(m.replyCount + ' replies', { kind: 'ghost', size: 'xs', attrs: 'data-thread="' + m.id + '"' }) : '') + '</div>'
      + '<div class="mactions">' + REACTIONS.map((k) => UI.btn(k, { kind: 'ghost', size: 'xs', attrs: 'data-react="' + m.id + '" data-kind="' + k + '"' })).join('') + UI.btn('Reply', { kind: 'ghost', size: 'xs', attrs: 'data-reply="' + m.id + '"' }) + UI.btn('Thread', { kind: 'ghost', size: 'xs', attrs: 'data-thread="' + m.id + '"' }) + UI.btn(m.pinned ? 'Unpin' : 'Pin', { kind: 'ghost', size: 'xs', attrs: 'data-pin="' + m.id + '"' }) + UI.btn('Forward', { kind: 'ghost', size: 'xs', attrs: 'data-forward="' + m.id + '"' }) + (mine ? UI.btn('Edit', { kind: 'ghost', size: 'xs', attrs: 'data-edit="' + m.id + '"' }) : UI.btn('Report', { kind: 'ghost', size: 'xs', attrs: 'data-report="' + m.id + '"' })) + (canDelete ? UI.btn('Delete', { kind: 'ghost', size: 'xs', attrs: 'data-del="' + m.id + '"' }) : '') + '</div></div>';
  }
  function renderInspector(c, msgs, st) {
    const tabs = UI.tabs([{ id: 'people', label: 'People', count: c.members.length + 1 }, { id: 'pins', label: 'Pins', count: msgs.filter((m) => m.pinned).length }, { id: 'settings', label: 'Settings' }], st.inspTab, 'data-insptabs');
    let body = '';
    if (st.inspTab === 'people') {
      const rows = [{ id: 'me', role: c.role, seen: 'now' }].concat(c.members.map((id) => ({ id, role: c.kind === 'direct' ? 'member' : (c.roles || {})[id] || 'member', seen: id === 'u-priya' ? 'now' : id === 'u-noor' ? '' : '2 h ago' })));
      body = '<div class="vstack gap6">' + rows.map((r) => '<div class="hstack" style="padding:6px 0;border-bottom:1px solid var(--line)"><span class="grow"><b>' + esc(nameOf(r.id)) + '</b>' + (r.id === 'me' ? ' <span class="muted">(you)</span>' : '') + '<br><span class="muted" style="font-size:12px">' + (r.id === 'me' ? 'mokafor' : esc(person(r.id).user)) + (r.seen ? ', last seen ' + esc(r.seen) : '') + (st.social.blocks.some((b) => b.id === r.id) ? ', blocked by you' : '') + '</span></span>' + UI.pill(r.role, r.role === 'owner' ? 'accent' : r.role === 'admin' ? 'info' : 'outline') + (r.id !== 'me' && c.kind === 'group' && (c.role === 'owner' || c.role === 'admin') ? '<span class="relative">' + UI.iconbtn('dots', 'Member actions', { attrs: 'data-member="' + r.id + '"', cls: 'sm ghost' }) + '</span>' : '') + '</div>').join('') + '</div>'
        + (c.kind === 'group' && (c.role === 'owner' || c.role === 'admin') ? '<div style="margin-top:8px">' + UI.btn('Add member', { size: 'sm', icon: 'plus', attrs: 'data-addmember' }) + '</div><div class="muted" style="font-size:12px;margin-top:6px">Everyone must be a member of ' + esc(c.ws) + ' now and cleared for ' + esc(c.label) + '. A conversation keeps at least one owner.</div>' : c.kind === 'direct' ? '<div class="muted" style="font-size:12px;margin-top:8px">One direct conversation per pair. Either of you may pin. Relation: <a href="#" data-gopeople>' + (st.social.following.includes(c.with) ? 'following' : 'not following') + '</a>.</div>' : '');
    } else if (st.inspTab === 'pins') {
      const pins = msgs.filter((m) => m.pinned);
      body = pins.length ? '<div class="vstack gap6">' + pins.map((m) => '<div class="panel" style="padding:8px 10px"><div class="muted" style="font-size:12px">' + esc(nameOf(m.author)) + ', ' + esc(m.at) + ', pinned by ' + esc(m.pinnedBy || ME) + '</div><div style="font-size:13px">' + esc(m.body) + '</div><div style="margin-top:4px">' + UI.btn('Unpin', { kind: 'ghost', size: 'xs', attrs: 'data-pin="' + m.id + '"' }) + '</div></div>').join('') + '</div>' : UI.empty('No pins', c.kind === 'direct' ? 'Either of you can pin a message.' : 'Owners and admins pin messages for everyone.');
    } else {
      body = '<div class="vstack gap12">' + UI.field('Notify me', UI.select([{ value: 'all', label: 'Every message' }, { value: 'mentions', label: 'Mentions of @mokafor only' }, { value: 'none', label: 'Nothing' }], c.notify, 'data-notify'), 'Notifications name the sender, never the text or the title.')
        + UI.toggle('Muted' + (c.muted && c.mutedUntil ? ' until ' + c.mutedUntil : ''), c.muted, 'data-mute')
        + (c.muted ? '' : '<div class="hstack gap6">' + UI.btn('Mute 1 h', { size: 'xs', attrs: 'data-mutefor="60"' }) + UI.btn('Mute until tomorrow', { size: 'xs', attrs: 'data-mutefor="900"' }) + '</div>')
        + UI.kv([['Kind', esc(c.kind)], ['Label', UI.label(c.label, { sm: true })], ['Workspace', esc(c.ws || 'shared workspaces')], ['Your role', esc(c.role)], ['Sealed at rest', 'tenant key, no end-to-end encryption, so search, summaries and moderation work']], 1)
        + (c.kind === 'group' && (c.role === 'owner' || c.role === 'admin') ? UI.btn('Rename', { size: 'sm', attrs: 'data-rename' }) : '')
        + (c.role === 'owner' ? UI.btn('Delete conversation', { kind: 'danger', size: 'sm', attrs: 'data-delconvo' }) : UI.btn('Leave conversation', { size: 'sm', attrs: 'data-leave' })) + '</div>';
    }
    return '<div class="eyebrow">Conversation</div>' + tabs + '<div style="margin-top:8px">' + body + '</div>';
  }
  function wireMessages(ctx, st) {
    const c = st.convos.find((x) => x.id === st.convo); const msgs = c ? (st.messages[c.id] || []) : [];
    const findMsg = (id) => { for (const m of msgs) { if (m.id === id) return m; } return null; };
    ctx.on('click', '[data-cfilter] [data-seg]', (e, t) => { st.filter = t.dataset.seg; ctx.rerender(); });
    ctx.on('input', '[data-cq]', (e, t) => { st.q = t.value; const list = ctx.$('.messages-list'); if (!list) return; ctx.rerender(); const i = ctx.$('[data-cq]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } });
    ctx.on('click', '[data-convo]', (e, t) => { st.convo = t.dataset.convo; st.replyTo = null; st.lastSummary = null; ctx.rerender(); });
    ctx.on('click', '[data-insptabs] [data-tab]', (e, t) => { st.inspTab = t.dataset.tab; ctx.rerender(); });
    ctx.on('click', '[data-gopeople]', (e) => { e.preventDefault(); st.view = 'people'; ctx.rerender(); });
    ctx.on('click', '[data-hideblock]', () => { st.showBlockNote = false; ctx.rerender(); });
    ctx.on('click', '[data-clearattach]', () => { st.attachProblem = false; ctx.rerender(); });
    ctx.on('click', '[data-clearsend]', () => { st.sendProblem = false; ctx.rerender(); });
    ctx.on('click', '[data-closesummary]', () => { st.lastSummary = null; ctx.rerender(); });
    ctx.on('click', '[data-gofile]', (e, t) => { e.preventDefault(); ctx.navigate('files', { file: t.dataset.gofile }); });
    ctx.on('click', '[data-markread]', () => { c.unread = 0; ctx.rerender(); ctx.toast('Read mark moved to ' + esc(msgs[msgs.length - 1].id) + '. Reading also counts as delivered.', 'ok'); });
    ctx.on('input', '[data-draft]', (e, t) => { st.draft = t.value; });
    ctx.on('click', '[data-cancelreply]', () => { st.replyTo = null; ctx.rerender(); });
    ctx.on('click', '[data-reply]', (e, t) => { st.replyTo = t.dataset.reply; ctx.rerender(); const ta = ctx.$('[data-draft]'); if (ta) ta.focus(); });
    ctx.on('click', '[data-unattach]', () => { st.pendingAttach = null; ctx.rerender(); });
    ctx.on('click', '[data-attach]', () => ctx.modal({ title: 'Attach from Files', body: UI.notice('Only files you can read in ' + esc(c.ws || 'a shared workspace') + ' whose current version passed its scan, labelled at most ' + esc(c.label) + '. Everyone reads it through the file store.', 'info') + UI.table(['File', 'Workspace', 'Label', 'Scan'], [{ cells: ['card-reconciliation-q3.xlsx', 'Finance Ops', UI.label('confidential', { sm: true }), UI.pill('ready')], attrs: 'data-pick="card-reconciliation-q3.xlsx" data-state="ready"' }, { cells: ['fabrikam-renewal-note.pdf', 'Finance Ops', UI.label('internal', { sm: true }), UI.pill('quarantined', 'warn')], attrs: 'data-pick="fabrikam-renewal-note.pdf" data-state="pending"' }, { cells: ['board-pack-q3-draft.pdf', 'Finance Ops', UI.label('restricted', { sm: true }), UI.pill('ready')], attrs: 'data-pick="board-pack-q3-draft.pdf" data-state="label"' }], { minWidth: '0' }), actions: UI.btn('Cancel', { attrs: 'data-close' }), onMount(m) { m.querySelectorAll('[data-pick]').forEach((r) => r.addEventListener('click', () => { App.closeOverlay(); const s = r.dataset.state; if (s === 'pending') { st.attachProblem = true; ctx.rerender(); return; } if (s === 'label') { ctx.toast('board-pack-q3-draft.pdf is restricted, above this conversation\'s label (422). Raise the label or pick another file.', 'danger', 5000); return; } st.pendingAttach = r.dataset.pick; ctx.rerender(); })); } }));
    ctx.on('click', '[data-send]', () => {
      const text = (st.draft || '').trim(); if (!text && !st.pendingAttach) { ctx.toast('Write a message or attach a file first.'); return; }
      if (/\b[A-Z]{2}\d{2}[ \d]{12,}/.test(text)) { st.sendProblem = true; ctx.rerender(); return; }
      const m = { id: 'm' + Date.now(), author: 'me', body: text || 'Attachment', at: 'just now', reactions: [], replyTo: st.replyTo || undefined, attachments: st.pendingAttach ? [{ fileId: 'f-new', name: st.pendingAttach, type: 'Excel', size: '212 KB', state: 'ready' }] : [] };
      msgs.push(m); c.last = 'just now'; st.draft = ''; st.replyTo = null; st.pendingAttach = null; ctx.rerender();
      ctx.toast('Sent. Screened at user-input, sealed with the tenant key; ' + (c.kind === 'group' ? c.members.length : 1) + ' people notified unless muted or in a block.', 'ok');
    });
    ctx.on('click', '[data-react]', (e, t) => { const m = findMsg(t.dataset.react); const k = t.dataset.kind; let r = m.reactions.find((x) => x.kind === k); if (!r) { r = { kind: k, count: 0, mine: false }; m.reactions.push(r); } if (r.mine) { r.mine = false; r.count -= 1; } else { r.mine = true; r.count += 1; } ctx.rerender(); });
    ctx.on('click', '[data-pin]', (e, t) => { const m = findMsg(t.dataset.pin); if (c.kind === 'group' && c.role === 'member') { ctx.toast('Only owners and admins pin in a group conversation (403, step conversation-role, right pin).', 'danger'); return; } m.pinned = !m.pinned; m.pinnedBy = ME; ctx.rerender(); ctx.toast(m.pinned ? 'Pinned for everyone in the conversation.' : 'Unpinned.', 'ok'); });
    ctx.on('click', '[data-edit]', (e, t) => { const m = findMsg(t.dataset.edit); ctx.modal({ title: 'Edit message', body: UI.field('Message', UI.textarea(m.body, { attrs: 'data-ebody', rows: 3 }), 'Screened again at user-input. Audited with the edit number and length, never the text.'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-esave' }), onMount(mm) { mm.querySelector('[data-esave]').addEventListener('click', () => { m.body = mm.querySelector('[data-ebody]').value; m.edited = true; m.editedAt = 'just now'; App.closeOverlay(); ctx.rerender(); ctx.toast('Message edited.', 'ok'); }); } }); });
    ctx.on('click', '[data-del]', async (e, t) => { const m = findMsg(t.dataset.del); const ok = await ctx.confirm({ title: 'Delete message', tag: 'tombstone', tone: 'danger', body: '<p class="fg2" style="margin:0">The body, attachments, keyword terms, vector and reactions are deleted. The row stays as a tombstone and the audit entry records the author and edit count, never the text.</p>', kv: [['Author', nameOf(m.author)], ['Sent', m.at]], ok: 'Delete' }); if (!ok) return; m.state = 'deleted'; m.pinned = false; ctx.rerender(); ctx.toast('Message deleted. messaging.message.deleted written.', 'warn'); });
    ctx.on('click', '[data-forward]', (e, t) => { const m = findMsg(t.dataset.forward); const targets = st.convos.filter((x) => x.id !== c.id); ctx.modal({ title: 'Forward message', body: '<div class="messages-quote">' + esc(nameOf(m.author)) + ': ' + esc(m.body) + '</div>' + UI.field('To conversation', UI.select(targets.map((x) => ({ value: x.id, label: convoTitle(x) + ' (' + x.label + ')' })), targets[0].id, 'data-fto'), 'A message above the target\'s label is refused (422). Attachments are checked again against the target workspace.'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Forward', { kind: 'primary', attrs: 'data-fgo' }), onMount(mm) { mm.querySelector('[data-fgo]').addEventListener('click', () => { const to = st.convos.find((x) => x.id === mm.querySelector('[data-fto]').value); App.closeOverlay(); if (LEVEL[c.label] > LEVEL[to.label]) { ctx.toast('Refused (422): this message is ' + esc(c.label) + ', ' + esc(convoTitle(to)) + ' is ' + esc(to.label) + '. The audience never widens.', 'danger', 5000); return; } (st.messages[to.id] = st.messages[to.id] || []).push({ id: 'f' + Date.now(), author: 'me', body: m.body, at: 'just now', reactions: [], forwardedFrom: convoTitle(c), attachments: m.attachments }); to.last = 'just now'; ctx.toast('Forwarded to ' + esc(convoTitle(to)) + '.', 'ok'); ctx.rerender(); }); } }); });
    ctx.on('click', '[data-report]', (e, t) => { const m = findMsg(t.dataset.report); ctx.modal({ title: 'Report message', body: UI.field('Reason', UI.select(['Harassment', 'Spam', 'Confidential data shared', 'Other'], 'Harassment')) + UI.field('Note', UI.textarea('', { rows: 2, placeholder: 'What should the reviewer look at?' })) + UI.notice('Files a report flag (type dm-message) in the workspace queue, checkpoint user-report. A hidden message shows to the conversation as a tombstone and leaves search.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Report', { kind: 'primary', attrs: 'data-rgo' }), onMount(mm) { mm.querySelector('[data-rgo]').addEventListener('click', () => { App.closeOverlay(); ctx.toast('Reported as F-2299 (dm-message). <a href="#/moderation?flag=F-2299" style="color:inherit">Open in Moderation</a>', 'ok', 5000); }); } }); });
    ctx.on('click', '[data-thread]', (e, t) => { const m = findMsg(t.dataset.thread); const replies = m.thread || []; ctx.drawer({ title: 'Thread', body: '<div class="messages-quote" style="margin-bottom:8px">' + esc(nameOf(m.author)) + ', ' + esc(m.at) + '<br>' + esc(m.body) + '</div><div class="vstack gap6" id="messages-thread-list">' + (replies.length ? replies.map((r) => '<div class="messages-comment"><b>' + esc(nameOf(r.author)) + '</b> <span class="muted" style="font-size:12px">' + esc(r.at) + '</span><br>' + esc(r.body) + '</div>').join('') : '<div class="muted" style="font-size:12px">No replies yet. Threads are one level deep.</div>') + '</div>' + UI.field('Reply in thread', UI.textarea('', { attrs: 'data-tbody', rows: 2 })), actions: UI.btn('Close', { attrs: 'data-close' }) + UI.btn('Reply', { kind: 'primary', attrs: 'data-tsend' }), onMount(d) { d.querySelector('[data-tsend]').addEventListener('click', () => { const v = d.querySelector('[data-tbody]').value.trim(); if (!v) return; m.thread = (m.thread || []).concat([{ id: 'r' + Date.now(), author: 'me', body: v, at: 'just now' }]); m.replyCount = m.thread.length; App.closeOverlay(); ctx.rerender(); ctx.toast('Reply posted in the thread.', 'ok'); }); } }); });
    ctx.on('click', '[data-member]', (e, t) => openMenu(ctx, t, [['admin', 'Make admin'], ['member', 'Make member'], ['owner', 'Make owner'], ['remove', 'Remove from conversation']], (c.roles || {})[t.dataset.member], async (v) => { const id = t.dataset.member; if (v === 'remove') { const ok = await ctx.confirm({ title: 'Remove ' + esc(nameOf(id)), tone: 'danger', body: '<p class="fg2" style="margin:0">Their sockets leave the room at once and the conversation disappears for them.</p>', ok: 'Remove' }); if (!ok) return; c.members = c.members.filter((x) => x !== id); } else { if (v === 'owner' && c.role !== 'owner') { ctx.toast('Only an owner grants owner or admin (403, step conversation-role).', 'danger'); return; } c.roles[id] = v; } ctx.rerender(); ctx.toast(v === 'remove' ? esc(nameOf(id)) + ' removed.' : esc(nameOf(id)) + ' is now ' + v + '.', 'ok'); }));
    ctx.on('click', '[data-addmember]', () => { const cands = PEOPLE.filter((p) => !c.members.includes(p.id)); ctx.modal({ title: 'Add member', body: UI.field('Person', UI.select(cands.map((p) => ({ value: p.id, label: p.name + ' (' + p.ws.join(', ') + ', ' + p.clearance + ')' })), cands[0].id, 'data-am')) + UI.field('Role', UI.select(['member', 'admin'], 'member', 'data-amrole')) + UI.notice('Must be a member of ' + esc(c.ws) + ' now (422, step workspace), cleared for ' + esc(c.label) + ' (422, step clearance) and accept you under their contact rule (403, step contact). They read messages from now on.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Add', { kind: 'primary', attrs: 'data-amgo' }), onMount(mm) { mm.querySelector('[data-amgo]').addEventListener('click', () => { const p = person(mm.querySelector('[data-am]').value); App.closeOverlay(); if (!p.ws.includes(c.ws)) { ctx.toast('Refused (422, step workspace): ' + esc(p.name) + ' is not a member of ' + esc(c.ws) + '.', 'danger', 5000); return; } if (LEVEL[p.clearance] < LEVEL[c.label]) { ctx.toast('Refused (422, step clearance): ' + esc(p.name) + ' is cleared to ' + esc(p.clearance) + ', the conversation is ' + esc(c.label) + '.', 'danger', 5000); return; } c.members.push(p.id); c.roles[p.id] = mm.querySelector('[data-amrole]').value; ctx.rerender(); ctx.toast(esc(p.name) + ' added. They read from now on.', 'ok'); }); } }); });
    ctx.on('change', '[data-notify]', (e, t) => { c.notify = t.value; ctx.toast('Notification rule saved: ' + t.value + '.', 'ok'); });
    ctx.on('click', '[data-mute]', () => { c.muted = !c.muted; c.mutedUntil = null; ctx.rerender(); ctx.toast(c.muted ? 'Muted until you unmute.' : 'Unmuted.', 'ok'); });
    ctx.on('click', '[data-mutefor]', (e, t) => { c.muted = true; c.mutedUntil = t.dataset.mutefor === '60' ? 'today 15:30' : '20 Sep 09:00'; ctx.rerender(); ctx.toast('Muted until ' + c.mutedUntil + '.', 'ok'); });
    ctx.on('click', '[data-rename]', () => ctx.modal({ title: 'Rename conversation', body: UI.field('Title', UI.input(c.title, { attrs: 'data-rt' })), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-rgo' }), onMount(mm) { mm.querySelector('[data-rgo]').addEventListener('click', () => { c.title = mm.querySelector('[data-rt]').value || c.title; App.closeOverlay(); ctx.rerender(); ctx.toast('Renamed.', 'ok'); }); } }));
    ctx.on('click', '[data-delconvo]', async () => { const ok = await ctx.confirm({ title: 'Delete conversation', tag: 'irreversible', tone: 'danger', body: '<p class="fg2" style="margin:0">The conversation is deleted and every message body, term and vector removed for all ' + (c.members.length + 1) + ' people.</p>', kv: [['Conversation', convoTitle(c)], ['Messages', String(msgs.length)]], ok: 'Delete' }); if (!ok) return; st.convos = st.convos.filter((x) => x.id !== c.id); st.convo = null; ctx.rerender(); ctx.toast('Conversation deleted.', 'warn'); });
    ctx.on('click', '[data-leave]', async () => { const ok = await ctx.confirm({ title: 'Leave conversation', tone: 'danger', body: '<p class="fg2" style="margin:0">You stop receiving messages at once. The last owner cannot leave (409).</p>', ok: 'Leave' }); if (!ok) return; st.convos = st.convos.filter((x) => x.id !== c.id); st.convo = null; ctx.rerender(); ctx.toast('You left ' + esc(convoTitle(c)) + '.', 'ok'); });
    ctx.on('click', '[data-summary]', () => ctx.modal({ title: 'Summarise conversation', body: UI.field('Profile', UI.select(['analyst', 'fast', 'chat-default'], 'analyst', 'data-sp')) + UI.field('Scope', UI.select([{ value: 'recent', label: 'Latest messages (up to 200)' }, { value: 'thread', label: 'Thread of m2 (Lisbon overrun)' }], 'recent', 'data-ss')) + UI.notice('Needs inference:invoke. Only messages you can see are numbered and sent; citations that name anything else are removed. The answer passes model-output.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Summarise', { kind: 'primary', attrs: 'data-sgo' }), onMount(mm) { mm.querySelector('[data-sgo]').addEventListener('click', () => { const p = mm.querySelector('[data-sp]').value; App.closeOverlay(); if (p === 'fast') { ctx.rerender(); ctx.toast('503: profile fast has no pool with free slots. Try again or pick another profile.', 'danger', 5000); return; } st.lastSummary = { kind: 'summary', profile: p, n: msgs.filter((m) => m.body).length, text: 'Priya Nair posted the accruals and the reconciliation sheet <a href="#" data-cite="m1">[1]</a>. Tomasz Weber corrected the Lisbon overrun to 60.5% with the approved exception <a href="#" data-cite="m2">[2]</a>; Mara Okafor will cite the calc result in the board pack <a href="#" data-cite="m3">[3]</a>. The draft pack is in Files, comments due Monday 12:00 <a href="#" data-cite="m7">[4]</a>.' }; ctx.rerender(); }); } }));
    ctx.on('click', '[data-digest]', () => { st.lastSummary = { kind: 'digest', profile: 'analyst', n: c.unread, text: c.unread ? 'Since your read mark: Priya Nair placed the flag F-2291 in your queue and asks for a look before the 15:00 call <a href="#" data-cite="p2">[1]</a>.' : 'Nothing from others after your read mark. summary: null.' }; ctx.rerender(); });
    ctx.on('click', '[data-cite]', (e, t) => { e.preventDefault(); const el = ctx.$('[data-msg="' + t.dataset.cite + '"]'); if (el) { el.scrollIntoView({ block: 'center' }); el.style.outline = '2px solid var(--accent)'; setTimeout(() => { el.style.outline = ''; }, 1200); } });
    ctx.on('click', '[data-msearch]', () => openSearch(ctx, st, c, msgs));
    if (st.openSearch) { st.openSearch = false; setTimeout(() => openSearch(ctx, st, c, msgs), 0); }
    ctx.on('click', '[data-newconvo]', () => openNew(ctx, st));
    if (st.openNew) { st.openNew = false; setTimeout(() => openNew(ctx, st), 0); }
  }
  function openSearch(ctx, st, c, msgs) {
    const mode = st.searchMode || 'keyword';
    const results = (q, m) => msgs.filter((x) => x.body && x.body.toLowerCase().includes(q.toLowerCase())).map((x, i) => ({ m: x, fused: (0.92 - i * 0.11).toFixed(2), kw: (0.88 - i * 0.1).toFixed(2), sem: m === 'keyword' ? '' : (0.81 - i * 0.07).toFixed(2) }));
    ctx.drawer({ title: 'Search in ' + esc(convoTitle(c)), body: UI.search('Search messages you can see', 'data-sq', st.searchQ || '') + '<div style="margin:8px 0">' + UI.seg([{ id: 'keyword', label: 'Keyword' }, { id: 'semantic', label: 'Semantic' }, { id: 'hybrid', label: 'Hybrid' }], mode, 'data-smode') + '</div><div id="messages-sres">' + (st.noEmbed && mode !== 'keyword' ? UI.problem('Semantic search unavailable (409)', 'MESSAGING_EMBED_MODEL names no approved embedding model, so semantic and hybrid modes are refused and the default is keyword. Approve an embedding model in Models and set the variable.', '7d3e1f5a9c0b4e2d8a6f1c3b5d7e9f02') : '<div class="muted" style="font-size:12px">Over messages since you joined, not deleted or hidden, none from people in a block with you. Keyword ranks by keyed-hash terms; semantic by embeddings; hybrid fuses both by reciprocal rank.</div>') + '</div>', actions: UI.btn('Close', { attrs: 'data-close' }), onMount(d) {
      const draw = () => { const q = d.querySelector('[data-sq]').value; st.searchQ = q; const out = d.querySelector('#messages-sres'); const md = st.searchMode || 'keyword'; if (st.noEmbed && md !== 'keyword') { out.innerHTML = UI.problem('Semantic search unavailable (409)', 'MESSAGING_EMBED_MODEL names no approved embedding model, so semantic and hybrid modes are refused and the default is keyword.', '7d3e1f5a9c0b4e2d8a6f1c3b5d7e9f02'); return; } if (!q) return; const rs = results(q, md); out.innerHTML = rs.length ? UI.table(['Message', 'Score'], rs.map((r) => ({ cells: ['<b>' + esc(nameOf(r.m.author)) + '</b> <span class="muted">' + esc(r.m.at) + '</span><br>' + esc(r.m.body), '<span class="mono">fused ' + r.fused + (md !== 'semantic' ? ', keyword ' + r.kw : '') + (r.sem ? ', semantic ' + r.sem : '') + '</span>'], attrs: 'data-sgo="' + r.m.id + '"' })), { minWidth: '0' }) : UI.empty('No matches', 'Try another word or mode.'); out.querySelectorAll('[data-sgo]').forEach((row) => row.addEventListener('click', () => { App.closeOverlay(); const el = ctx.$('[data-msg="' + row.dataset.sgo + '"]'); if (el) el.scrollIntoView({ block: 'center' }); })); };
      d.querySelector('[data-sq]').addEventListener('input', draw);
      d.querySelector('[data-smode]').addEventListener('click', (e) => { const b = e.target.closest('[data-seg]'); if (!b) return; st.searchMode = b.dataset.seg; d.querySelectorAll('[data-smode] button').forEach((x) => x.classList.toggle('active', x.dataset.seg === b.dataset.seg)); draw(); });
      if (st.searchQ) draw();
    } });
  }
  function openNew(ctx, st) {
    const kind = st.newKind || 'direct';
    const wsPeople = (ws) => PEOPLE.filter((p) => p.ws.includes(ws));
    const body = UI.seg([{ id: 'direct', label: 'Direct' }, { id: 'group', label: 'Group' }], kind, 'data-nk') + '<div id="messages-newform">' + newForm(st, kind) + '</div>';
    ctx.modal({ title: 'New conversation', cls: 'wide', body, actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(kind === 'direct' ? 'Start' : 'Create', { kind: 'primary', attrs: 'data-ngo' }), onMount(m) {
      const redraw = () => { m.querySelector('#messages-newform').innerHTML = newForm(st, st.newKind || 'direct'); m.querySelector('[data-ngo]').textContent = (st.newKind || 'direct') === 'direct' ? 'Start' : 'Create'; };
      m.querySelector('[data-nk]').addEventListener('click', (e) => { const b = e.target.closest('[data-seg]'); if (!b) return; st.newKind = b.dataset.seg; st.newProblem = null; m.querySelectorAll('[data-nk] button').forEach((x) => x.classList.toggle('active', x.dataset.seg === b.dataset.seg)); redraw(); });
      m.querySelector('[data-ngo]').addEventListener('click', () => {
        const k = st.newKind || 'direct';
        if (k === 'direct') {
          const id = m.querySelector('[data-nt]').value; const p = person(id);
          if (id === 'u-aisha' || id === 'u-samir' || st.social.blocks.some((b) => b.id === id)) { st.newTarget = id; st.newProblem = 'contact'; redraw(); return; }
          const ex = st.convos.find((x) => x.kind === 'direct' && x.with === id);
          App.closeOverlay(); st.newProblem = null;
          if (ex) { st.convo = ex.id; ctx.rerender(); ctx.toast('You already have a direct conversation with ' + esc(p.name) + ' (200, the existing one).'); return; }
          const shared = p.ws.filter((w) => ['Finance Ops', 'People Ops', 'Field Sales'].includes(w)); const label = shared.map((w) => CEILING[w]).sort((a, b) => LEVEL[b] - LEVEL[a])[0] || 'internal';
          const nc = { id: 'c-' + id, kind: 'direct', with: id, label, unread: 0, muted: false, notify: 'all', last: 'just now', role: 'member', members: [id] }; st.convos.unshift(nc); st.messages[nc.id] = []; st.convo = nc.id; ctx.rerender(); ctx.toast('Direct conversation with ' + esc(p.name) + ' started (201).', 'ok');
        } else {
          const ws = m.querySelector('[data-nws]').value; const title = m.querySelector('[data-ntitle]').value || 'Untitled'; const label = m.querySelector('[data-nlabel]').value; const members = Array.prototype.slice.call(m.querySelectorAll('[data-nm]:checked')).map((x) => x.value);
          if (LEVEL[label] > LEVEL[CEILING[ws]]) { st.newProblem = 'ceiling'; st.newWs = ws; st.newLabel = label; redraw(); return; }
          const low = members.map(person).find((p) => LEVEL[p.clearance] < LEVEL[label]); if (low) { st.newProblem = 'clearance:' + low.name; redraw(); return; }
          if (!members.length) { ctx.toast('Pick at least one member.'); return; }
          App.closeOverlay(); st.newProblem = null;
          const nc = { id: 'c-g' + Date.now(), kind: 'group', title, ws, label, unread: 0, muted: false, notify: 'all', last: 'just now', role: 'owner', members, roles: members.reduce((o, x) => { o[x] = 'member'; return o; }, {}) }; st.convos.unshift(nc); st.messages[nc.id] = []; st.convo = nc.id; ctx.rerender(); ctx.toast('Group conversation created (201). You are the owner.', 'ok');
        }
      });
    } });
    function newForm(s, k) {
      if (k === 'direct') {
        return '<div class="vstack gap12" style="margin-top:8px">' + UI.field('Person', UI.select(PEOPLE.map((p) => ({ value: p.id, label: p.name + ' (' + p.ws.join(', ') + ')' })), s.newTarget || 'u-jonas', 'data-nt'), 'Someone who shares a workspace with you now. One direct conversation per pair.')
          + (s.newProblem === 'contact' ? UI.problem('Cannot start this conversation (403, step contact)', nameOf(s.newTarget) + ' does not accept messages from you. Their contact rule (workspace, following or nobody) or a block decides this; the words are the same either way, so a blocked person is never told.', 'c0ffee1234567890abcdef1234567890') : UI.notice('Contact rules: workspace (anyone sharing a workspace, the default), following (only people they follow) or nobody. Yours is <b>' + esc(s.social.contactRule) + '</b>; change it under People.', 'info')) + '</div>';
      }
      const ws = s.newWs || 'Finance Ops'; const ppl = wsPeople(ws);
      return '<div class="formgrid" style="margin-top:8px">' + UI.field('Workspace', UI.select(['Finance Ops', 'People Ops', 'Field Sales'], ws, 'data-nws'), 'Everyone must be a member of it now.') + UI.field('Title', UI.input(s.newTitle || '', { placeholder: 'Q3 board pack', attrs: 'data-ntitle' })) + UI.field('Label', UI.select(['public', 'internal', 'confidential', 'restricted'], s.newLabel || CEILING[ws], 'data-nlabel'), 'At most the workspace ceiling, ' + esc(CEILING[ws]) + '.') + '</div>'
        + UI.field('Members (up to MESSAGING_MAX_MEMBERS)', '<div class="vstack gap4">' + ppl.map((p) => UI.check(p.name + ', ' + p.clearance, ['u-priya', 'u-felix'].includes(p.id), 'data-nm value="' + p.id + '"')).join('') + '</div>')
        + (s.newProblem === 'ceiling' ? UI.problem('Label above the workspace ceiling (422)', s.newLabel + ' is above ' + ws + '\'s ceiling of ' + CEILING[ws] + '.', 'd1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6') : s.newProblem && s.newProblem.indexOf('clearance:') === 0 ? UI.problem('Member not cleared (422, step clearance)', s.newProblem.slice(10) + ' is not cleared for this label.', 'd1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6') : '');
    }
  }

  // ---------------- Feed ----------------
  const score = (p) => Object.keys(p.counts.reactions || {}).reduce((n, k) => n + p.counts.reactions[k], 0) + 2 * p.counts.comments + 3 * p.counts.reposts;
  function renderFeed(ctx, st) {
    const seg = UI.seg([{ id: 'home', label: 'Home' }, { id: 'ws', label: 'Finance Ops' }, { id: 'groups', label: 'Groups' }, { id: 'bookmarks', label: 'Bookmarks' }, { id: 'tag', label: st.tag ? '#' + st.tag : 'Tag' }, { id: 'trending', label: 'Trending' }], st.feedSeg, 'data-fseg');
    const vis = st.posts.filter((p) => p.state !== 'hidden' || p.hiddenFor !== 'blocked');
    let posts; let title; let sub;
    const following = st.social.following; const muted = st.social.mutes.map((m) => m.id);
    if (st.feedSeg === 'home') { posts = vis.filter((p) => (p.author === 'me' || following.includes(p.author)) && !muted.includes(p.author)); title = 'Home'; sub = 'Your posts and those of the ' + following.length + ' people you follow, in every workspace and group you may read, minus muted people.'; }
    else if (st.feedSeg === 'ws') { posts = vis.filter((p) => !p.group); title = 'Finance Ops'; sub = 'The workspace feed: posts not targeted at a group. Internal by default, at most the workspace ceiling.'; }
    else if (st.feedSeg === 'groups') { posts = vis.filter((p) => p.group); title = 'Group feeds'; sub = 'Posts targeted at groups you read. A private group\'s posts never reach the workspace feed. <a href="#" data-gogroups>Groups and events</a>'; }
    else if (st.feedSeg === 'bookmarks') { posts = vis.filter((p) => p.mine.bookmarked); title = 'Bookmarks'; sub = 'Most recently saved first. Posts you can no longer see are left out.'; }
    else if (st.feedSeg === 'tag') { posts = vis.filter((p) => st.tag && p.tags.includes(st.tag)); title = st.tag ? '#' + st.tag : 'Pick a tag'; sub = 'Posts with the hashtag, any case, in all your workspaces.'; }
    else { posts = []; title = 'Trending'; sub = 'From the last feed.trending run, counting only posts at labels you are cleared for.'; }
    posts = posts.slice().sort((a, b) => st.feedSort === 'top' ? score(b) - score(a) : 0);
    const held = st.posts.filter((p) => p.state === 'held');
    const composer = st.feedSeg === 'ws' || st.feedSeg === 'home' || st.feedSeg === 'groups' ? '<div class="messages-composer">' + UI.textarea(st.postDraft || '', { placeholder: 'Post to ' + (st.feedSeg === 'groups' ? 'Audit readiness (group)' : 'Finance Ops') + '. Hashtags are extracted when published. Up to FEED_POST_MAX_CHARS.', attrs: 'data-pdraft', rows: 2 }) + '<div class="hstack wrap">' + UI.select(st.feedSeg === 'groups' ? ['Audit readiness (group)', 'Close team (group)'] : ['Finance Ops (workspace)', 'Audit readiness (group)'], null, 'data-ptarget aria-label="Target"') + UI.select(['internal', 'confidential'], st.postLabel || 'internal', 'data-plabel aria-label="Label"') + UI.btn('Media from Files', { size: 'sm', icon: 'attach', attrs: 'data-pmedia' }) + (st.pendingMedia ? '<span class="messages-att">' + esc(st.pendingMedia) + UI.iconbtn('x', 'Remove', { attrs: 'data-unmedia', cls: 'sm ghost' }) + '</span>' : '') + '<span class="grow"></span>' + UI.btn('Post', { kind: 'primary', size: 'sm', icon: 'send', attrs: 'data-post' }) + '</div></div>' : '';
    const toolbar = '<div class="toolbar">' + (st.feedSeg !== 'trending' ? '<span class="relative">' + UI.btn(st.feedSort === 'top' ? 'Sort: most engaged' : 'Sort: newest', { size: 'sm', icon: 'sort', attrs: 'data-fsort' }) + '</span>' : '') + '<span class="muted right" style="font-size:12px">' + posts.length + ' posts' + (held.length ? ', ' + held.length + ' held' : '') + '</span></div>';
    let main;
    if (st.feedSeg === 'trending') {
      const tags = [{ tag: 'q3-close', posts: 14, people: 7 }, { tag: 'finance', posts: 11, people: 6 }, { tag: 'audit', posts: 6, people: 4 }, { tag: 'workflows', posts: 5, people: 3 }, { tag: 'lisbon', posts: 3, people: 2 }];
      main = UI.panel('Trending in Finance Ops', UI.table(['Tag', { label: 'Posts', right: true }, { label: 'People', right: true }], tags.map((t) => ({ cells: ['<a href="#" class="messages-tag" data-gotag="' + t.tag + '">#' + esc(t.tag) + '</a>', '<span class="num">' + t.posts + '</span>', '<span class="num">' + t.people + '</span>'], attrs: 'data-gotag="' + t.tag + '"' })), { minWidth: '0' }) + '<div class="muted" style="font-size:12px">Computed today 13:30 over the last FEED_TRENDING_HOURS (48). Group posts are left out.</div>');
    } else {
      main = posts.length ? posts.map((p) => renderPost(p, st)).join('') + '<div style="text-align:center">' + UI.btn('Load more', { kind: 'ghost', size: 'sm', attrs: 'data-loadmore' }) + '</div>' : UI.empty(st.feedSeg === 'tag' && !st.tag ? 'Pick a tag' : 'Nothing here', st.feedSeg === 'tag' ? 'Open a hashtag from a post or Trending.' : st.feedSeg === 'bookmarks' ? 'Bookmark a post to find it here.' : 'Follow people to fill your home feed.');
    }
    const digests = UI.panel('Weekly digests, Finance Ops', '<div class="vstack gap6">' + st.digests.map((d) => '<div class="hstack" style="padding:6px 0;border-bottom:1px solid var(--line)"><span class="grow"><b>' + esc(d.week) + '</b> <span class="muted" style="font-size:12px">' + d.posts.length + ' posts</span></span>' + UI.pill(d.state, d.state === 'ready' ? 'ok' : d.state === 'failed' ? 'danger' : '') + UI.btn('Open', { kind: 'ghost', size: 'xs', attrs: 'data-digestopen="' + d.id + '"' }) + '</div>').join('') + '</div><div class="divider"></div>' + UI.toggle('Digest enabled', st.digestEnabled, 'data-dtoggle') + UI.field('Digest profile', UI.select([{ value: '', label: 'none (falls back to FEED_DIGEST_PROFILE)' }, 'analyst', 'chat-default'], st.digestProfile, 'data-dprofile'), 'feed:manage. Ranked by reactions + 2 × comments + 3 × reposts; the summary passes model-output.') + UI.btn('Run digest now', { size: 'sm', attrs: 'data-drun' }), { cls: '' });
    const relations = UI.panel('Who you see', UI.kv([['Following', String(following.length)], ['Followers', String(st.social.followers.length)], ['Blocked', String(st.social.blocks.length)], ['Muted', String(st.social.mutes.length)]], 2) + '<div class="muted" style="font-size:12px">A block hides the other person\'s posts, comments and reposts in every feed; a mute removes them from Home only. <a href="#" data-gopeople>Manage</a></div>');
    return '<div class="page">%NAV%' + UI.pagehead(title, sub, UI.label('internal') + UI.btn('Report a post', { kind: 'ghost', size: 'sm', attrs: 'data-reporthint' })) + seg + composer + toolbar + '<div class="vstack gap12">' + main + '</div>%TAIL%</div><aside class="inspector w360" aria-label="Feed details">' + digests + relations + '</aside>';
  }
  function renderPost(p, st) {
    const orig = p.repostOf ? st.posts.find((x) => x.id === p.repostOf) : null;
    const total = Object.keys(p.counts.reactions || {}).reduce((n, k) => n + p.counts.reactions[k], 0);
    const body = (t) => esc(t).replace(/#([a-z0-9-]+)/g, '<a href="#" class="messages-tag" data-gotag="$1">#$1</a>');
    const focus = st.focusPost === p.id ? ' style="outline:2px solid var(--accent)"' : '';
    return '<article class="messages-post' + (p.state === 'held' ? ' held' : '') + '" data-post="' + p.id + '"' + focus + '>'
      + '<div class="messages-meta"><b style="color:var(--fg)">' + esc(nameOf(p.author)) + '</b><span>' + esc(p.at) + '</span>' + (p.group ? UI.pill(p.group, 'outline') : '') + UI.label(p.label, { sm: true }) + (p.state === 'held' ? UI.pill('held for review', 'warn') : p.state === 'rejected' ? UI.pill('rejected', 'danger') : '') + (p.editedAt ? '<span>edited</span>' : '') + '</div>'
      + (p.state === 'held' ? UI.notice('<b>Held for review (202).</b> A require-approval rule held this post at user-input. Only you can see it until a reviewer decides <a href="#/flags?id=' + esc(p.flag) + '" style="color:inherit">' + esc(p.flag) + '</a>; approved publishes it, rejected withdraws it. It takes no comments or reactions while it waits (409).', 'warn') : '')
      + (p.body ? '<div class="messages-body">' + body(p.body) + '</div>' : '')
      + (orig ? '<div class="messages-quote"><b>' + esc(nameOf(orig.author)) + '</b>, ' + esc(orig.at) + ' ' + UI.label(orig.label, { sm: true }) + '<br>' + body(orig.body || '') + '</div>' : p.repostOf ? '<div class="messages-tomb">The original is blocked, gone or out of reach (original: null).</div>' : '')
      + (p.media.length ? '<div class="hstack wrap gap6">' + p.media.map((m) => '<a href="#" class="messages-att" data-gofile="' + esc(m.fileId) + '">' + UI.icon('images', 12) + esc(m.name) + (m.available ? '' : UI.pill('unavailable', 'warn')) + '</a>').join('') + '</div>' : '')
      + (p.state === 'published' ? '<div class="pactions">' + REACTIONS.map((k) => UI.chip(esc(k) + (p.counts.reactions[k] ? ' ' + p.counts.reactions[k] : ''), p.mine.reactions.includes(k), 'data-preact="' + p.id + '" data-kind="' + k + '"')).join('') + '<span class="muted" style="font-size:12px">' + total + ' reactions, ' + p.counts.comments + ' comments, ' + p.counts.reposts + ' reposts</span></div>'
      + '<div class="pactions">' + UI.btn('Comment', { kind: 'ghost', size: 'xs', attrs: 'data-pcomment="' + p.id + '"' }) + '<span class="relative">' + UI.btn(p.mine.reposted ? 'Reposted' : 'Repost', { kind: 'ghost', size: 'xs', attrs: 'data-prepost="' + p.id + '"', cls: p.mine.reposted ? 'active' : '' }) + '</span>' + UI.btn(p.mine.bookmarked ? 'Bookmarked' : 'Bookmark', { kind: 'ghost', size: 'xs', attrs: 'data-pbookmark="' + p.id + '"', cls: p.mine.bookmarked ? 'active' : '' }) + (p.author === 'me' ? UI.btn('Edit', { kind: 'ghost', size: 'xs', attrs: 'data-pedit="' + p.id + '"' }) : UI.btn('Report', { kind: 'ghost', size: 'xs', attrs: 'data-preport="' + p.id + '"' })) + UI.btn('Delete', { kind: 'ghost', size: 'xs', attrs: 'data-pdel="' + p.id + '"', title: p.author === 'me' ? 'Your post' : 'feed:manage in Finance Ops' }) + '</div>' : '<div class="pactions">' + UI.btn('Delete', { kind: 'ghost', size: 'xs', attrs: 'data-pdel="' + p.id + '"' }) + '</div>')
      + (p.comments.length ? '<div class="vstack gap4">' + p.comments.map((cm) => '<div class="messages-comment' + (cm.parentId ? ' reply' : '') + '"><b>' + esc(nameOf(cm.author)) + '</b> <span class="muted" style="font-size:12px">' + esc(cm.at) + '</span> ' + UI.btn('Reply', { kind: 'ghost', size: 'xs', attrs: 'data-pcomment="' + p.id + '" data-parent="' + cm.id + '"' }) + '<br>' + esc(cm.body) + '</div>').join('') + '</div>' : '')
      + '</article>';
  }
  function wireFeed(ctx, st) {
    const post = (id) => st.posts.find((p) => p.id === id);
    ctx.on('click', '[data-fseg] [data-seg]', (e, t) => { st.feedSeg = t.dataset.seg; st.focusPost = null; ctx.rerender(); });
    ctx.on('click', '[data-gotag]', (e, t) => { e.preventDefault(); st.tag = t.dataset.gotag; st.feedSeg = 'tag'; ctx.rerender(); });
    ctx.on('click', '[data-gogroups]', (e) => { e.preventDefault(); ctx.navigate('groups'); });
    ctx.on('click', '[data-fsort]', (e, t) => openMenu(ctx, t, [['new', 'Newest first'], ['top', 'Most engaged']], st.feedSort || 'new', (v) => { st.feedSort = v; ctx.rerender(); }));
    ctx.on('click', '[data-loadmore]', () => ctx.toast('nextCursor is null: you have reached the end of this feed.'));
    ctx.on('click', '[data-reporthint]', () => ctx.toast('Use Report on a post. It files a feed-post flag in the workspace queue.'));
    ctx.on('input', '[data-pdraft]', (e, t) => { st.postDraft = t.value; });
    ctx.on('change', '[data-plabel]', (e, t) => { st.postLabel = t.value; });
    ctx.on('click', '[data-unmedia]', () => { st.pendingMedia = null; ctx.rerender(); });
    ctx.on('click', '[data-pmedia]', () => ctx.modal({ title: 'Media from Files', body: UI.notice('Up to 10 files from the post\'s workspace that passed quarantine. A file raises the post\'s label to its own.', 'info') + UI.table(['File', 'Label', 'Scan'], [{ cells: ['workflow-v3.png', UI.label('internal', { sm: true }), UI.pill('ready')], attrs: 'data-pick="workflow-v3.png" data-ok="1"' }, { cells: ['fabrikam-renewal-note.pdf', UI.label('internal', { sm: true }), UI.pill('quarantined', 'warn')], attrs: 'data-pick="fabrikam-renewal-note.pdf"' }], { minWidth: '0' }), actions: UI.btn('Cancel', { attrs: 'data-close' }), onMount(m) { m.querySelectorAll('[data-pick]').forEach((r) => r.addEventListener('click', () => { App.closeOverlay(); if (!r.dataset.ok) { ctx.toast('409: fabrikam-renewal-note.pdf is still pending its scan. Attach it when it is ready.', 'danger', 5000); return; } st.pendingMedia = r.dataset.pick; ctx.rerender(); })); } }));
    ctx.on('click', '[data-post]', () => { const text = (st.postDraft || '').trim(); if (!text && !st.pendingMedia) { ctx.toast('Text or media are needed (422).'); return; } const target = ctx.$('[data-ptarget]').value; const held = /\b[A-Z]{2}\d{2}[ \d]{12,}|\bboard figures\b/i.test(text); const tags = (text.match(/#([a-z0-9-]+)/gi) || []).map((t) => t.slice(1).toLowerCase()); const np = { id: 'po' + Date.now(), ws: 'Finance Ops', group: /group/.test(target) ? target.replace(' (group)', '') : undefined, author: 'me', body: text, label: st.postLabel || 'internal', state: held ? 'held' : 'published', flag: held ? 'F-2298' : undefined, tags, counts: { comments: 0, reposts: 0, reactions: { like: 0, celebrate: 0, support: 0, insightful: 0, funny: 0 } }, mine: { reactions: [], bookmarked: false, reposted: false }, at: 'just now', media: st.pendingMedia ? [{ fileId: 'f-m', name: st.pendingMedia, type: 'PNG', available: true }] : [], comments: [] }; st.posts.unshift(np); st.postDraft = ''; st.pendingMedia = null; ctx.rerender(); ctx.toast(held ? 'Held for review (202). A hold flag F-2298 is in the Flags queue; only you see the post.' : 'Published (201). ' + tags.length + ' hashtags extracted; your followers\' home rooms were notified.', held ? 'warn' : 'ok', 5000); });
    ctx.on('click', '[data-preact]', (e, t) => { const p = post(t.dataset.preact); const k = t.dataset.kind; if (p.state !== 'published') { ctx.toast('409: a post waiting for review takes no reactions.', 'danger'); return; } if (p.mine.reactions.includes(k)) { p.mine.reactions = p.mine.reactions.filter((x) => x !== k); p.counts.reactions[k] -= 1; } else { p.mine.reactions.push(k); p.counts.reactions[k] = (p.counts.reactions[k] || 0) + 1; } ctx.rerender(); });
    ctx.on('click', '[data-pbookmark]', (e, t) => { const p = post(t.dataset.pbookmark); p.mine.bookmarked = !p.mine.bookmarked; ctx.rerender(); ctx.toast(p.mine.bookmarked ? 'Bookmarked.' : 'Bookmark removed.', 'ok'); });
    ctx.on('click', '[data-prepost]', (e, t) => { const p = post(t.dataset.prepost); openMenu(ctx, t, [['plain', p.mine.reposted ? 'Take back plain repost' : 'Repost'], ['quote', 'Repost with text']], null, (v) => { if (v === 'plain') { p.mine.reposted = !p.mine.reposted; p.counts.reposts += p.mine.reposted ? 1 : -1; if (p.mine.reposted) st.posts.unshift({ id: 'rp' + Date.now(), ws: p.ws, group: p.group, author: 'me', body: null, label: p.label, state: 'published', repostOf: p.repostOf || p.id, tags: [], counts: { comments: 0, reposts: 0, reactions: {} }, mine: { reactions: [], bookmarked: false, reposted: false }, at: 'just now', media: [], comments: [] }); else st.posts = st.posts.filter((x) => !(x.repostOf === p.id && x.author === 'me' && !x.body)); ctx.rerender(); ctx.toast(p.mine.reposted ? 'Reposted into ' + esc(p.group || p.ws) + '. It carries the original\'s label; the audience never widens.' : 'Repost taken back.', 'ok'); } else ctx.modal({ title: 'Repost with text', body: UI.field('Your text', UI.textarea('', { attrs: 'data-qt', rows: 2 }), 'A post of its own: guardrails and holds apply.') + '<div class="messages-quote">' + esc(nameOf(p.author)) + ': ' + esc(p.body) + '</div>', actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Post', { kind: 'primary', attrs: 'data-qgo' }), onMount(m) { m.querySelector('[data-qgo]').addEventListener('click', () => { const v = m.querySelector('[data-qt]').value.trim(); App.closeOverlay(); if (!v) return; p.counts.reposts += 1; st.posts.unshift({ id: 'rq' + Date.now(), ws: p.ws, group: p.group, author: 'me', body: v, label: p.label, state: 'published', repostOf: p.id, tags: [], counts: { comments: 0, reposts: 0, reactions: { like: 0, celebrate: 0, support: 0, insightful: 0, funny: 0 } }, mine: { reactions: [], bookmarked: false, reposted: false }, at: 'just now', media: [], comments: [] }); ctx.rerender(); ctx.toast('Published (201).', 'ok'); }); } }); }); });
    ctx.on('click', '[data-pcomment]', (e, t) => { const p = post(t.dataset.pcomment); const parent = t.dataset.parent; if (p.state === 'held') { ctx.toast('409: a post waiting for review takes no comments.', 'danger'); return; } ctx.modal({ title: parent ? 'Reply to comment' : 'Comment', body: (parent ? '<div class="messages-quote">' + esc((p.comments.find((c) => c.id === parent) || {}).body || '') + '</div>' : '') + UI.field('Comment', UI.textarea('', { attrs: 'data-cb', rows: 2 }), 'Comments do not wait for review: a hold refuses them (422). Oldest first; threads from parentId.'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Post comment', { kind: 'primary', attrs: 'data-cgo' }), onMount(m) { m.querySelector('[data-cgo]').addEventListener('click', () => { const v = m.querySelector('[data-cb]').value.trim(); App.closeOverlay(); if (!v) return; p.comments.push({ id: 'cm' + Date.now(), author: 'me', body: v, at: 'just now', parentId: parent || undefined }); p.counts.comments += 1; ctx.rerender(); ctx.toast('Comment posted (201). feed.comment.created audited.', 'ok'); }); } }); });
    ctx.on('click', '[data-pedit]', (e, t) => { const p = post(t.dataset.pedit); ctx.modal({ title: 'Edit post', body: UI.field('Text', UI.textarea(p.body, { attrs: 'data-eb', rows: 3 }), 'Checked again; a hold refuses the edit. The post is re-tagged and editedAt set.'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-ego' }), onMount(m) { m.querySelector('[data-ego]').addEventListener('click', () => { p.body = m.querySelector('[data-eb]').value; p.tags = (p.body.match(/#([a-z0-9-]+)/gi) || []).map((x) => x.slice(1).toLowerCase()); p.editedAt = 'just now'; App.closeOverlay(); ctx.rerender(); ctx.toast('Post edited.', 'ok'); }); } }); });
    ctx.on('click', '[data-pdel]', async (e, t) => { const p = post(t.dataset.pdel); const ok = await ctx.confirm({ title: 'Delete post', tag: p.author === 'me' ? 'your post' : 'feed:manage', tone: 'danger', body: '<p class="fg2" style="margin:0">' + (p.author === 'me' ? 'Deletes your post with its comments and reposts.' : 'As a holder of feed:manage in Finance Ops you remove anyone\'s post. The author is notified; audited feed.post.deleted.') + '</p>', kv: [['Author', nameOf(p.author)], ['Posted', p.at]], ok: 'Delete' }); if (!ok) return; st.posts = st.posts.filter((x) => x.id !== p.id); ctx.rerender(); ctx.toast('Post deleted. Comments, reactions and reposts on it are now refused (409).', 'warn'); });
    ctx.on('click', '[data-preport]', (e, t) => { const p = post(t.dataset.preport); ctx.modal({ title: 'Report post', body: UI.field('Reason', UI.select(['Harassment', 'Spam', 'Confidential data shared', 'Other'], 'Spam')) + UI.notice('Files a feed-post flag in ' + esc(p.ws) + '\'s queue. A reviewer\'s hide removes it from every feed; an upheld appeal restores it.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Report', { kind: 'primary', attrs: 'data-rgo' }), onMount(m) { m.querySelector('[data-rgo]').addEventListener('click', () => { App.closeOverlay(); ctx.toast('Reported as F-2300 (feed-post). <a href="#/moderation?flag=F-2300" style="color:inherit">Open in Moderation</a>', 'ok', 5000); }); } }); });
    ctx.on('click', '[data-digestopen]', (e, t) => { const d = st.digests.find((x) => x.id === t.dataset.digestopen); ctx.drawer({ title: 'Digest, ' + esc(d.week), body: UI.kv([['State', UI.pill(d.state, d.state === 'ready' ? 'ok' : d.state === 'failed' ? 'danger' : '')], ['Label', UI.label(d.label, { sm: true })], ['Profile', esc(d.profile || 'FEED_DIGEST_PROFILE')]], 3) + (d.state === 'failed' ? UI.notice('<b>Summary failed.</b> ' + esc(d.error) + '. The ranked list is kept.', 'danger') : '') + (d.summary ? '<div class="serif" style="font-size:15px;line-height:1.5;margin:8px 0">' + esc(d.summary) + '</div>' : d.state === 'empty' ? UI.empty('No posts that week', 'A week without posts is empty.') : '') + (d.posts.length ? UI.table(['#', 'Post', { label: 'Score', right: true }], d.posts.map((x, i) => { const p = st.posts.find((y) => y.id === x.id); return [String(i + 1), p ? '<b>' + esc(nameOf(p.author)) + '</b>: ' + esc((p.body || '').slice(0, 80)) : '<span class="muted">post no longer visible (null)</span>', '<span class="num">' + x.score + '</span>']; }), { minWidth: '0', clickable: false }) : ''), actions: UI.btn('Close', { attrs: 'data-close' }) }); });
    ctx.on('click', '[data-dtoggle]', () => { st.digestEnabled = !st.digestEnabled; ctx.rerender(); ctx.toast('feed.settings.updated: digestEnabled ' + st.digestEnabled + '.', 'ok'); });
    ctx.on('change', '[data-dprofile]', (e, t) => { st.digestProfile = t.value; ctx.toast(t.value ? 'Digest profile set to ' + esc(t.value) + '.' : 'Digest profile cleared; falls back to FEED_DIGEST_PROFILE.', 'ok'); });
    ctx.on('click', '[data-drun]', () => { if (!st.digestProfile && !st.digestEnabled) { ctx.toast('409: no digest profile resolves for Finance Ops.', 'danger'); return; } st.digests.unshift({ id: 'd' + Date.now(), ws: 'Finance Ops', week: '12 Sep to 19 Sep (last seven days)', label: 'internal', state: 'ready', profile: st.digestProfile || 'analyst', posts: st.posts.filter((p) => p.state === 'published' && !p.group && p.body).slice(0, 3).map((p) => ({ id: p.id, score: score(p) })), summary: 'Requested now: the Q3 close checklist drew the most engagement; the workflow v3 announcement and the MSA reminder follow.' }); ctx.rerender(); ctx.toast('Digest queued (202, job feed.digest). Members cleared for internal are notified when it is ready.', 'ok'); });
    ctx.on('click', '[data-gofile]', (e, t) => { e.preventDefault(); ctx.navigate('files', { file: t.dataset.gofile }); });
  }

  // ---------------- People (social relations) ----------------
  function renderPeople(ctx, st) {
    const s = st.social;
    const tabs = UI.tabs([{ id: 'blocks', label: 'Blocks', count: s.blocks.length }, { id: 'mutes', label: 'Mutes', count: s.mutes.length }, { id: 'following', label: 'Following', count: s.following.length }, { id: 'followers', label: 'Followers', count: s.followers.length }, { id: 'lists', label: 'Lists', count: s.lists.length }], st.peopleTab, 'data-ptabs');
    let body;
    if (st.peopleTab === 'blocks') body = UI.notice('A block works both ways: neither of you can start a conversation with or message the other; each other\'s messages, posts, typing, presence and receipts are left out; follows end both ways. The blocked person is never told and reads "does not accept messages from you".', 'info') + UI.table(['Person', 'Blocked', { label: '', right: true }], s.blocks.map((b) => [esc(nameOf(b.id)) + ' <span class="muted mono">' + esc(person(b.id).user) + '</span>', esc(b.at), UI.btn('Unblock', { size: 'sm', attrs: 'data-unblock="' + b.id + '"' })]), { clickable: false, minWidth: '0', emptyTitle: 'Nobody blocked' }) + '<div>' + UI.btn('Block someone', { size: 'sm', attrs: 'data-block' }) + '</div>';
    else if (st.peopleTab === 'mutes') body = UI.notice('A mute is one-way and private: the muted person\'s posts leave your home feed and their messages notify you of nothing.', 'info') + UI.table(['Person', 'Until', 'Muted', { label: '', right: true }], s.mutes.map((m) => [esc(nameOf(m.id)), esc(m.expiresAt || 'you unmute'), esc(m.at), UI.btn('Unmute', { size: 'sm', attrs: 'data-unmute="' + m.id + '"' })]), { clickable: false, minWidth: '0', emptyTitle: 'Nobody muted' }) + '<div>' + UI.btn('Mute someone', { size: 'sm', attrs: 'data-mutesomeone' }) + '</div>';
    else if (st.peopleTab === 'following') body = UI.table(['Person', 'Workspaces', 'Since', { label: '', right: true }], s.following.map((id) => [esc(nameOf(id)), esc(person(id).ws.join(', ')), '2 Sep', UI.btn('Unfollow', { size: 'sm', attrs: 'data-unfollow="' + id + '"' })]), { clickable: false, minWidth: '0' }) + '<div>' + UI.btn('Follow someone', { size: 'sm', attrs: 'data-follow' }) + '</div><div class="muted" style="font-size:12px">Follows must share a workspace with you (else 404, as if unknown). Someone in a block with you cannot be followed.</div>';
    else if (st.peopleTab === 'followers') body = UI.table(['Person', 'Workspaces', 'Follows you since', { label: '', right: true }], s.followers.map((id) => [esc(nameOf(id)), esc(person(id).ws.join(', ')), '5 Sep', s.following.includes(id) ? UI.pill('mutual', 'ok') : UI.btn('Follow back', { size: 'sm', attrs: 'data-followid="' + id + '"' })]), { clickable: false, minWidth: '0' });
    else { const sel = s.lists.find((l) => l.id === st.list) || s.lists[0]; body = '<div class="cols"><div style="flex:1">' + UI.table(['List', 'People', 'Description'], s.lists.map((l) => ({ cells: [esc(l.name), String(l.members.length), esc(l.description || '')], attrs: 'data-list="' + l.id + '"', selected: sel && sel.id === l.id })), { minWidth: '0' }) + '<div>' + UI.btn('New list', { size: 'sm', icon: 'plus', attrs: 'data-newlist' }) + '</div></div>' + (sel ? '<div style="flex:1">' + UI.panel(sel.name, '<div class="vstack gap4">' + sel.members.map((id) => '<div class="hstack"><span class="grow">' + esc(nameOf(id)) + '</span>' + UI.iconbtn('x', 'Remove', { attrs: 'data-listrm="' + id + '"', cls: 'sm ghost' }) + '</div>').join('') + '</div><div class="hstack gap6" style="margin-top:8px">' + UI.btn('Add person', { size: 'sm', attrs: 'data-listadd' }) + UI.btn('Rename', { size: 'sm', kind: 'ghost', attrs: 'data-listrename' }) + UI.btn('Delete list', { size: 'sm', kind: 'danger', attrs: 'data-listdel' }) + UI.btn('Open as feed', { size: 'sm', kind: 'ghost', attrs: 'data-listfeed' }) + '</div><div class="muted" style="font-size:12px;margin-top:6px">Up to 1,000 people, 100 lists. Someone outside your workspaces is 404; a blocked person 409.</div>') + '</div>' : '') + '</div>'; }
    const rule = UI.panel('Contact rule', '<div class="vstack gap6">' + UI.seg([{ id: 'workspace', label: 'Anyone sharing a workspace' }, { id: 'following', label: 'Only people I follow' }, { id: 'nobody', label: 'Nobody' }], s.contactRule, 'data-rule') + '<span class="muted" style="font-size:12px">Who may start a conversation with you or add you to one. Refusals read "does not accept messages from you", the same words as a block. Also under <a href="#" data-gosettings>Settings</a>.</span></div>');
    return '<div class="page">%NAV%' + UI.pagehead('People', 'Your blocks, mutes, follows, followers and lists. Messaging and the feed both enforce them; limits per user: 5,000 blocks, mutes and follows, 100 lists.') + rule + tabs + '<div class="vstack gap12">' + body + '</div>%TAIL%</div>';
  }
  function wirePeople(ctx, st) {
    const s = st.social;
    const pickPerson = (title, exclude, hint, onPick) => { const cands = PEOPLE.filter((p) => !exclude.includes(p.id)); ctx.modal({ title, body: UI.field('Person', UI.select(cands.map((p) => ({ value: p.id, label: p.name + ' (' + p.ws.join(', ') + ')' })), cands[0].id, 'data-pp'), hint), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(title, { kind: 'primary', attrs: 'data-ppgo' }), onMount(m) { m.querySelector('[data-ppgo]').addEventListener('click', () => { const v = m.querySelector('[data-pp]').value; App.closeOverlay(); onPick(v); }); } }); };
    ctx.on('click', '[data-ptabs] [data-tab]', (e, t) => { st.peopleTab = t.dataset.tab; ctx.rerender(); });
    ctx.on('click', '[data-rule] [data-seg]', (e, t) => { s.contactRule = t.dataset.seg; ctx.rerender(); ctx.toast('Contact rule saved: ' + t.dataset.seg + '. Audited social.contact-rule.updated.', 'ok'); });
    ctx.on('click', '[data-gosettings]', (e) => { e.preventDefault(); ctx.navigate('settings'); });
    ctx.on('click', '[data-unblock]', (e, t) => { s.blocks = s.blocks.filter((b) => b.id !== t.dataset.unblock); ctx.rerender(); ctx.toast(esc(nameOf(t.dataset.unblock)) + ' unblocked. Follows do not come back on their own.', 'ok'); });
    ctx.on('click', '[data-block]', () => pickPerson('Block', s.blocks.map((b) => b.id), 'Anyone active in the tenant. Ends follows both ways; they are not told.', async (id) => { const ok = await ctx.confirm({ title: 'Block ' + esc(nameOf(id)), tone: 'danger', body: '<p class="fg2" style="margin:0">Neither of you can message the other; their messages, posts, typing and presence are left out for you on every instance. They read only "does not accept messages from you".</p>', ok: 'Block' }); if (!ok) return; s.blocks.unshift({ id, at: 'just now' }); s.following = s.following.filter((x) => x !== id); s.followers = s.followers.filter((x) => x !== id); ctx.rerender(); ctx.toast(esc(nameOf(id)) + ' blocked (201).', 'warn'); }));
    ctx.on('click', '[data-unmute]', (e, t) => { s.mutes = s.mutes.filter((m) => m.id !== t.dataset.unmute); ctx.rerender(); ctx.toast('Unmuted.', 'ok'); });
    ctx.on('click', '[data-mutesomeone]', () => { const cands = PEOPLE.filter((p) => !s.mutes.some((m) => m.id === p.id)); ctx.modal({ title: 'Mute', body: UI.field('Person', UI.select(cands.map((p) => ({ value: p.id, label: p.name })), cands[0].id, 'data-mp')) + UI.field('For', UI.select([{ value: '60', label: '1 hour' }, { value: '1440', label: '1 day' }, { value: '10080', label: '1 week' }, { value: '', label: 'Until I unmute' }], '10080', 'data-mm'), 'At most a year. Muting again sets the new end.'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Mute', { kind: 'primary', attrs: 'data-mgo' }), onMount(m) { m.querySelector('[data-mgo]').addEventListener('click', () => { const id = m.querySelector('[data-mp]').value; const mins = m.querySelector('[data-mm]').value; App.closeOverlay(); s.mutes.unshift({ id, expiresAt: mins === '60' ? 'today 15:30' : mins === '1440' ? '20 Sep 14:30' : mins === '10080' ? '26 Sep 14:30' : null, at: 'just now' }); ctx.rerender(); ctx.toast(esc(nameOf(id)) + ' muted (201). Private; they are not told.', 'ok'); }); } }); });
    ctx.on('click', '[data-unfollow]', (e, t) => { s.following = s.following.filter((x) => x !== t.dataset.unfollow); ctx.rerender(); ctx.toast('Unfollowed.', 'ok'); });
    ctx.on('click', '[data-followid]', (e, t) => { s.following.push(t.dataset.followid); ctx.rerender(); ctx.toast('Following ' + esc(nameOf(t.dataset.followid)) + ' (201).', 'ok'); });
    ctx.on('click', '[data-follow]', () => pickPerson('Follow', s.following, 'Must share a workspace with you.', (id) => { if (s.blocks.some((b) => b.id === id)) { ctx.toast('409: you blocked ' + esc(nameOf(id)) + '. Unblock first.', 'danger'); return; } const p = person(id); if (!p.ws.some((w) => ['Finance Ops', 'People Ops', 'Field Sales'].includes(w))) { ctx.toast('404: no shared workspace.', 'danger'); return; } s.following.push(id); ctx.rerender(); ctx.toast('Following ' + esc(p.name) + ' (201). Their posts join your home feed.', 'ok'); }));
    ctx.on('click', '[data-list]', (e, t) => { st.list = t.dataset.list; ctx.rerender(); });
    ctx.on('click', '[data-newlist]', () => ctx.modal({ title: 'New list', body: UI.field('Name', UI.input('', { attrs: 'data-ln', placeholder: 'Lisbon team' }), 'A name you already use, any case, is 409.') + UI.field('Description', UI.input('', { attrs: 'data-ld' })), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Create', { kind: 'primary', attrs: 'data-lgo' }), onMount(m) { m.querySelector('[data-lgo]').addEventListener('click', () => { const n = m.querySelector('[data-ln]').value.trim(); if (!n) return; App.closeOverlay(); if (s.lists.some((l) => l.name.toLowerCase() === n.toLowerCase())) { ctx.toast('409: you already have a list named ' + esc(n) + '.', 'danger'); return; } const l = { id: 'l' + Date.now(), name: n, description: m.querySelector('[data-ld]').value, members: [] }; s.lists.push(l); st.list = l.id; ctx.rerender(); ctx.toast('List created (201).', 'ok'); }); } }));
    const sel = () => s.lists.find((l) => l.id === st.list) || s.lists[0];
    ctx.on('click', '[data-listrm]', (e, t) => { const l = sel(); l.members = l.members.filter((x) => x !== t.dataset.listrm); ctx.rerender(); });
    ctx.on('click', '[data-listadd]', () => { const l = sel(); pickPerson('Add to list', l.members, 'Someone outside your workspaces is 404; a blocked person 409.', (id) => { if (s.blocks.some((b) => b.id === id)) { ctx.toast('409: ' + esc(nameOf(id)) + ' is blocked.', 'danger'); return; } l.members.push(id); ctx.rerender(); ctx.toast(esc(nameOf(id)) + ' added to ' + esc(l.name) + '.', 'ok'); }); });
    ctx.on('click', '[data-listrename]', () => { const l = sel(); ctx.modal({ title: 'Rename list', body: UI.field('Name', UI.input(l.name, { attrs: 'data-ln' })) + UI.field('Description', UI.input(l.description, { attrs: 'data-ld' })), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-lgo' }), onMount(m) { m.querySelector('[data-lgo]').addEventListener('click', () => { l.name = m.querySelector('[data-ln]').value || l.name; l.description = m.querySelector('[data-ld]').value; App.closeOverlay(); ctx.rerender(); ctx.toast('List saved.', 'ok'); }); } }); });
    ctx.on('click', '[data-listdel]', async () => { const l = sel(); const ok = await ctx.confirm({ title: 'Delete list', tone: 'danger', body: '<p class="fg2" style="margin:0">Deletes ' + esc(l.name) + '. Nobody is told; the people stay followed.</p>', ok: 'Delete' }); if (!ok) return; s.lists = s.lists.filter((x) => x.id !== l.id); st.list = null; ctx.rerender(); ctx.toast('List deleted.', 'warn'); });
    ctx.on('click', '[data-listfeed]', () => { const l = sel(); st.view = 'feed'; st.feedSeg = 'home'; ctx.rerender(); ctx.toast('GET /api/feed/lists/' + esc(l.id) + ': the posts of the ' + l.members.length + ' people on ' + esc(l.name) + '. Shown here as Home for the prototype.'); });
  }

  function openMenu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative') || anchor.parentElement; const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    host.classList.add('relative');
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + it[0] + '" class="' + (it[0] === active ? 'on' : '') + '">' + it[1] + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
})();
