(function () {
  const { UI, esc } = App;

  // ---- example data: Northwind tenant, the reviewer's workspaces (Finance Ops, People Ops, Field Sales) ----
  const SEV_RANK = { high: 0, medium: 1, low: 2 };
  const OBJECT_TYPES = ['conversation', 'message', 'knowledge-document', 'media-asset', 'image', 'feed-post', 'feed-comment', 'dm-message', 'group-post', 'group', 'group-event', 'record', 'channel-session', 'channel-message', 'atproto-post'];
  const queues0 = () => [
    { id: 'q-finance', name: 'Finance Ops review', workspace: 'Finance Ops', rules: ['numeric-grounding', 'export-iban', 'injection-ctx'], labels: ['internal', 'confidential'], kinds: ['guard', 'report', 'hold'], priority: 10, sla: 60, escalateTo: 'tenant', escSla: 120, enabled: true },
    { id: 'q-social', name: 'Posts and messages', workspace: 'Finance Ops', rules: [], labels: [], kinds: ['feed-post', 'feed-comment', 'dm-message', 'group-post'], priority: 20, sla: 240, escalateTo: 'workspace', escSla: 240, enabled: true },
    { id: 'q-channels', name: 'Customer channels', workspace: 'Field Sales', rules: [], labels: ['public', 'internal'], kinds: ['channel-message', 'channel-session', 'hold'], priority: 30, sla: 30, escalateTo: 'tenant', escSla: 60, enabled: true },
    { id: 'q-atproto', name: 'Firehose labels', workspace: 'People Ops', rules: [], labels: ['public'], kinds: ['atproto-post', 'atproto-label'], priority: 40, sla: 1440, escalateTo: 'platform', escSla: 1440, enabled: false }
  ];
  const qflags0 = () => [
    { id: 'F-2291', queue: 'q-finance', kind: 'guard', type: 'message', objectId: 'm-88c1', rule: 'Numeric grounding', sev: 'high', left: 12, of: 60, label: 'confidential', owner: 'Tomasz Weber', when: '19 Sep 14:02', hideable: true },
    { id: 'F-2288', queue: 'q-finance', kind: 'guard', type: 'conversation', objectId: 'c4', rule: 'PII-IBAN', sev: 'high', left: 48, of: 60, label: 'confidential', owner: 'Mara Okafor', when: '19 Sep 13:26', hideable: true },
    { id: 'F-2290', queue: 'q-finance', kind: 'report', type: 'message', objectId: 'm-91f0', rule: 'User report', sev: 'medium', left: 180, of: 240, label: 'internal', owner: 'chat-default for T. Weber', when: '19 Sep 11:40', hideable: true },
    { id: 'F-2279', queue: 'q-finance', kind: 'guard', type: 'knowledge-document', objectId: 'kd-fabrikam-msa-2025', rule: 'Prompt injection', sev: 'high', left: -20, of: 60, label: 'internal', owner: 'Lena Hoffmann (curator)', when: '19 Sep 12:52', escalated: 'tenant', escLeft: 100, hideable: true },
    { id: 'F-2302', queue: 'q-social', kind: 'report', type: 'feed-post', objectId: 'p-4a19', rule: 'User report', sev: 'medium', left: 200, of: 240, label: 'internal', owner: 'Samir Haddad', when: '19 Sep 10:15', hideable: true },
    { id: 'F-2303', queue: 'q-social', kind: 'hold', type: 'feed-post', objectId: 'p-4b02', rule: 'Hold at user-input (require-approval)', sev: 'low', left: 220, of: 240, label: 'internal', owner: 'Noor Rahimi', when: '19 Sep 13:58', hideable: false },
    { id: 'F-2305', queue: 'q-channels', kind: 'hold', type: 'channel-message', objectId: 'cm-7710', rule: 'Review mode: escalated', sev: 'medium', left: 14, of: 30, label: 'public', owner: 'Returns desk (chat)', when: '19 Sep 14:21', hideable: false },
    { id: 'F-2306', queue: 'q-channels', kind: 'guard', type: 'channel-message', objectId: 'cm-7702', rule: 'PII-IBAN', sev: 'high', left: -5, of: 30, label: 'public', owner: 'Returns desk (chat)', when: '19 Sep 13:49', hideable: true },
    { id: 'F-2299', queue: 'q-atproto', kind: 'report', type: 'atproto-post', objectId: 'at://did:plc:4x9…/app.bsky.feed.post/3kz', rule: '!warn from trusted labeler', sev: 'medium', left: 900, of: 1440, label: 'public', owner: 'Brand watch subscription', when: '18 Sep 22:10', hideable: false }
  ];
  const reports0 = () => [
    { flag: 'F-2290', reporter: 'Tomasz Weber', type: 'message', objectId: 'm-91f0', reason: 'Wrong or unsupported figure', note: 'figure looks wrong', sev: 'medium', due: '19 Sep 15:40', duplicate: false, workspace: 'Finance Ops', state: 'open' },
    { flag: 'F-2302', reporter: 'Felix Brandt', type: 'feed-post', objectId: 'p-4a19', reason: 'Harassment', note: 'Names a colleague and ridicules them', sev: 'medium', due: '19 Sep 14:15', duplicate: false, workspace: 'Finance Ops', state: 'open' },
    { flag: 'F-2302', reporter: 'Lena Hoffmann', type: 'feed-post', objectId: 'p-4a19', reason: 'Harassment', note: '', sev: 'medium', due: '19 Sep 14:15', duplicate: true, workspace: 'Finance Ops', state: 'open' },
    { flag: 'F-2299', reporter: 'Brand watch subscription', type: 'atproto-post', objectId: 'at://did:plc:4x9…/3kz', reason: 'Label !warn received', note: 'From did:plc:ar7vlabeler', sev: 'medium', due: '20 Sep 13:10', duplicate: false, workspace: 'People Ops', state: 'open' },
    { flag: 'F-2284', reporter: 'Noor Rahimi', type: 'dm-message', objectId: 'dm-3301', reason: 'Spam', note: 'Repeated link to an outside site', sev: 'low', due: '18 Sep 12:00', duplicate: false, workspace: 'People Ops', state: 'dismissed' }
  ];
  const appeals0 = () => [
    { ref: 'A-3', kind: 'action', actionId: 'act-41', subject: 'message m-77a2', appellant: 'Tomasz Weber', filedBy: 'Tomasz Weber', label: 'confidential', state: 'pending', filed: '19 Sep 09:12', statement: 'The IBAN in the message is the one on our own supplier record, which Finance Ops holds anyway. The message was a question about a card line, not an export.', decidedBy: 'Priya Nair', decisionWhen: '18 Sep 17:02', decisionReason: 'PII-IBAN at model-output' },
    { ref: 'A-4', kind: 'sanction', sanctionId: 'S-12', subject: 'suspension of Samir Haddad, 7 days', appellant: 'Samir Haddad', filedBy: 'Priya Nair (for the user)', label: 'internal', state: 'reviewing', reviewer: 'Priya Nair', filed: '18 Sep 16:40', statement: 'I posted the pricing sheet to the Field Sales feed, not outside the company. I did not know it carried the confidential label.', decidedBy: 'Jonas Lindqvist', decisionWhen: '18 Sep 15:55', decisionReason: 'Shared a confidential file in an internal feed' },
    { ref: 'A-5', kind: 'action', actionId: 'act-44', subject: 'dm-message dm-3290', appellant: 'Noor Rahimi', filedBy: 'Noor Rahimi', label: 'internal', state: 'pending', filed: '19 Sep 12:05', statement: 'The message was a quote from a customer email that I was asking a colleague about.', decidedBy: 'Mara Okafor', decisionWhen: '19 Sep 11:30', decisionReason: 'Secrets detector: an API key in the text' },
    { ref: 'A-6', kind: 'action', actionId: 'act-39', subject: 'media-asset (redacted)', appellant: '(redacted)', filedBy: '(redacted)', label: 'restricted', state: 'pending', filed: '19 Sep 08:30', statement: null, decidedBy: '(redacted)', decisionWhen: '18 Sep', decisionReason: '(redacted)' },
    { ref: 'A-2', kind: 'action', actionId: 'act-37', subject: 'feed-post p-3b10', appellant: 'Noor Rahimi', filedBy: 'Noor Rahimi', label: 'internal', state: 'denied', filed: '17 Sep 10:02', decided: '17 Sep 15:20', decidedAppealBy: 'Mara Okafor', note: 'The post repeated the claim after the correction.', statement: 'The post was accurate when written.', decidedBy: 'Priya Nair', decisionWhen: '16 Sep', decisionReason: 'Misleading figure (report)' },
    { ref: 'A-1', kind: 'action', actionId: 'act-33', subject: 'knowledge-document kd-travel-policy-2024', appellant: 'Lena Hoffmann', filedBy: 'Lena Hoffmann', label: 'internal', state: 'upheld', filed: '15 Sep 09:00', decided: '15 Sep 13:10', decidedAppealBy: 'Mara Okafor', note: 'The matched text was a quoted example, not an instruction.', effects: { restored: true, flagReopened: 'F-2241', labelsNegated: 2 }, statement: 'The document quotes an injection example in its training section.', decidedBy: 'guardrail', decisionWhen: '14 Sep', decisionReason: 'Prompt injection at context' }
  ];
  const actions0 = () => [
    { id: 'act-44', type: 'dm-message', objectId: 'dm-3290', workspace: 'People Ops', owner: 'Noor Rahimi', flag: 'F-2296', state: 'applied', source: 'reviewer', by: 'Mara Okafor', reason: 'Secrets detector: an API key in the text', when: '19 Sep 11:30', appeal: 'A-5' },
    { id: 'act-43', type: 'channel-message', objectId: 'cm-7702', workspace: 'Field Sales', owner: 'Returns desk (chat)', flag: 'F-2306', state: 'applied', source: 'guardrail', by: 'guardrail block', reason: 'PII-IBAN at user-input', when: '19 Sep 13:49' },
    { id: 'act-42', type: 'feed-post', objectId: 'p-3f77', workspace: 'Finance Ops', owner: 'Samir Haddad', flag: 'F-2293', state: 'applied', source: 'provider', by: 'Perspective-compatible (enforce)', reason: 'toxicity 0.91 above threshold 0.85', when: '19 Sep 07:12' },
    { id: 'act-41', type: 'message', objectId: 'm-77a2', workspace: 'Finance Ops', owner: 'Tomasz Weber', flag: 'F-2280', state: 'applied', source: 'reviewer', by: 'Priya Nair', reason: 'PII-IBAN at model-output', when: '18 Sep 17:02', appeal: 'A-3' },
    { id: 'act-39', type: 'media-asset', objectId: '(redacted)', workspace: 'Finance Ops', owner: '(redacted)', flag: '(redacted)', state: 'applied', source: 'reviewer', by: '(redacted)', reason: '(redacted)', when: '18 Sep', appeal: 'A-6', restricted: true },
    { id: 'act-37', type: 'feed-post', objectId: 'p-3b10', workspace: 'People Ops', owner: 'Noor Rahimi', flag: 'F-2270', state: 'applied', source: 'reviewer', by: 'Priya Nair', reason: 'Misleading figure (report)', when: '16 Sep 14:40', appeal: 'A-2' },
    { id: 'act-33', type: 'knowledge-document', objectId: 'kd-travel-policy-2024', workspace: 'Finance Ops', owner: 'Lena Hoffmann', flag: 'F-2241', state: 'reversed', source: 'guardrail', by: 'guardrail block', reason: 'Prompt injection at context', when: '14 Sep 10:20', reversedBy: 'Mara Okafor (appeal A-1)', reversedAt: '15 Sep 13:10', appeal: 'A-1' }
  ];
  const sanctions0 = () => [
    { id: 'S-12', user: 'Samir Haddad', kind: 'suspend', reason: 'Shared a confidential file in an internal feed', flag: 'F-2287', state: 'active', starts: '18 Sep 15:55', ends: '25 Sep 15:55', by: 'Jonas Lindqvist', sessions: 2, appeal: 'A-4' },
    { id: 'S-11', user: 'Noor Rahimi', kind: 'warn', reason: 'Repeated reposting of a corrected figure', flag: 'F-2270', state: 'active', starts: '16 Sep 14:45', ends: null, by: 'Priya Nair', sessions: 0 },
    { id: 'S-10', user: 'svc-close-bot (service account)', kind: 'ban', reason: 'Credential found in posted content; owner unreachable', flag: 'F-2254', state: 'active', starts: '12 Sep 09:10', ends: null, by: 'Mara Okafor', sessions: 1 },
    { id: 'S-9', user: 'Felix Brandt', kind: 'suspend', reason: 'Bulk export attempts above clearance', flag: 'F-2231', state: 'expired', starts: '3 Sep 11:00', ends: '10 Sep 11:00', by: 'Jonas Lindqvist', sessions: 3 },
    { id: 'S-8', user: 'Tomasz Weber', kind: 'warn', reason: 'Guardrail bypass attempt in chat', flag: 'F-2199', state: 'lifted', starts: '28 Aug 16:20', ends: '29 Aug 09:00', by: 'Priya Nair', endedBy: 'Jonas Lindqvist', endReason: 'Issued to the wrong account', sessions: 0 }
  ];
  const providers0 = () => [
    { id: 'pv-1', name: 'Perspective-compatible', kind: 'json', url: 'https://moderation.northwind-partner.example/v1/score', hasSecret: true, zone: 'external', mode: 'enforce', enabled: true, types: ['feed-post', 'feed-comment', 'dm-message', 'group-post'], threshold: 0.85, verdicts: 1182, flagged: 41, p95: 410 },
    { id: 'pv-2', name: 'OpenAI moderation (trial)', kind: 'openai', url: 'https://api.openai.com/v1/moderations', hasSecret: true, zone: 'external', mode: 'shadow', enabled: false, types: ['message', 'feed-post'], threshold: 0.7, verdicts: 318, flagged: 9, p95: 880 }
  ];
  const verdicts0 = {
    'pv-1': [
      { id: 'v-9931', type: 'feed-post', objectId: 'p-3f77', mode: 'enforce', flagged: true, cats: 'toxicity, insult', score: 0.91, acted: true, flag: 'F-2293', ms: 388, when: '19 Sep 07:12' },
      { id: 'v-9930', type: 'dm-message', objectId: 'dm-3312', mode: 'enforce', flagged: false, cats: '', score: 0.08, acted: false, flag: null, ms: 402, when: '19 Sep 07:10' },
      { id: 'v-9918', type: 'feed-comment', objectId: 'cm-2201', mode: 'enforce', flagged: true, cats: 'profanity', score: 0.86, acted: true, flag: 'F-2289', ms: 455, when: '18 Sep 19:44' },
      { id: 'v-9902', type: 'group-post', objectId: 'gp-510', mode: 'shadow', flagged: true, cats: 'identity attack', score: 0.88, acted: false, flag: null, ms: 371, when: '17 Sep 09:02' }
    ],
    'pv-2': [
      { id: 'v-7710', type: 'message', objectId: 'm-88c1', mode: 'shadow', flagged: false, cats: '', score: 0.12, acted: false, flag: null, ms: 912, when: '12 Sep 14:00' },
      { id: 'v-7703', type: 'feed-post', objectId: 'p-3a01', mode: 'shadow', flagged: true, cats: 'harassment', score: 0.74, acted: false, flag: null, ms: 1210, when: '11 Sep 10:31' }
    ]
  };
  const dead0 = () => [
    { id: 'dl-1', job: 'job-5f3a1c', type: 'moderation.provider', provider: 'Perspective-compatible', error: 'ETIMEDOUT after 10,000 ms (attempt 5 of 5)', attempts: 5, state: 'open', failed: '19 Sep 06:58', object: 'feed-post p-3f70' },
    { id: 'dl-2', job: 'job-5f39e0', type: 'moderation.provider', provider: 'Perspective-compatible', error: 'HTTP 502 from upstream', attempts: 5, state: 'open', failed: '18 Sep 23:14', object: 'dm-message dm-3301' },
    { id: 'dl-3', job: 'job-5f2c77', type: 'moderation.provider', provider: 'OpenAI moderation (trial)', error: 'HTTP 401 invalid_api_key', attempts: 3, state: 'redriven', failed: '12 Sep 14:02', redrivenBy: 'Jonas Lindqvist', redrivenAt: '12 Sep 15:10', redriveJob: 'job-5f2d01', object: 'message m-88c1' }
  ];

  const timeText = (left) => left < 0 ? 'overdue ' + (-left) + ' min' : left >= 1440 ? Math.round(left / 1440) + ' d left' : left >= 120 ? Math.round(left / 60) + ' h left' : left + ' min left';
  const sevPill = (s) => UI.pill(s, s === 'high' ? 'danger' : s === 'medium' ? 'warn' : '');
  const tabsDef = (st) => [
    { id: 'queues', label: 'Queues', count: st.qflags.length }, { id: 'reports', label: 'Reports', count: st.reports.filter((r) => r.state === 'open').length }, { id: 'appeals', label: 'Appeals', count: st.appeals.filter((a) => a.state === 'pending' || a.state === 'reviewing').length },
    { id: 'actions', label: 'Actions' }, { id: 'sanctions', label: 'Sanctions', count: st.sanctions.filter((s) => s.state === 'active').length }, { id: 'providers', label: 'Providers' }, { id: 'dead', label: 'Dead letters', count: st.dead.filter((d) => d.state === 'open').length }
  ];

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
  const small = (t) => '<span class="muted" style="font-size:12px">' + t + '</span>';

  App.register({
    id: 'moderation', title: 'Moderation', section: 'admin', crumb: ['Admin', 'Moderation'],
    summary: 'Routed queues with SLA timers, reports, appeals, sanctions, external providers, dead-letter queue',
    label: (st) => { if (st.tab === 'appeals' && st.appealSel) { const a = (st.appeals || []).find((x) => x.ref === st.appealSel); return a ? a.label : null; } if (st.tab === 'queues' && st.flagSel) { const f = (st.qflags || []).find((x) => x.id === st.flagSel); return f ? f.label : null; } return null; },
    commands: [
      { label: 'Review the next appeal', sub: 'Moderation', run(app) { const s = app.stateFor('moderation'); s.tab = 'appeals'; const a = (s.appeals || appeals0()).find((x) => x.state === 'pending'); if (a) s.appealSel = a.ref; app.render(); } },
      { label: 'Issue a sanction', sub: 'Moderation', run(app) { const s = app.stateFor('moderation'); s.tab = 'sanctions'; s.openSanction = true; app.render(); } }
    ],
    states: [
      { title: 'Appeal upheld restores the object', tone: 'ok', text: 'Upholding an appeal on an action restores the object, reopens its flag with a fresh timer and negates the AT-Protocol labels made from it.', apply(ctx) { const st = ctx.state; st.tab = 'appeals'; const a = st.appeals.find((x) => x.ref === 'A-3'); if (a) { a.state = 'upheld'; a.decided = 'just now'; a.decidedAppealBy = 'Mara Okafor'; a.note = 'The IBAN belongs to a supplier record the workspace already holds.'; a.effects = { restored: true, flagReopened: 'F-2280', labelsNegated: 0 }; const act = st.actions.find((x) => x.id === a.actionId); if (act) { act.state = 'reversed'; act.reversedBy = 'Mara Okafor (appeal A-3)'; act.reversedAt = 'just now'; } } st.appealSel = 'A-3'; st.appealResult = 'A-3'; ctx.rerender(); } },
      { title: 'Independence refused', tone: 'danger', text: 'Whoever took the decision under appeal, and the appellant, cannot review it: 403 with step independence.', apply(ctx) { const st = ctx.state; st.tab = 'appeals'; st.appealSel = 'A-5'; st.independence = 'A-5'; ctx.rerender(); } },
      { title: 'Timer escalated to tenant', tone: 'warn', text: 'A routed flag past its queue SLA moves to the escalation level with a fresh timer and that level is notified.', apply(ctx) { const st = ctx.state; st.tab = 'queues'; st.queueSel = 'q-finance'; st.flagSel = 'F-2279'; st.escalatedNote = true; st.flagSort = 'time'; ctx.rerender(); ctx.toast('F-2279 escalated to the tenant level with a fresh 120 min timer. Tenant moderation admins notified.', 'warn', 5000); } },
      { title: 'Providers disabled', tone: 'info', text: 'Without MODERATION_EXTERNAL_PROVIDERS every provider route answers 403 with step disabled. The list is read-only and nothing is queued.', apply(ctx) { const st = ctx.state; st.tab = 'providers'; st.providersEnabled = false; ctx.rerender(); } },
      { title: 'Dead letter redriven', tone: 'neutral', text: 'A redrive queues the job again with its sealed payload; a second redrive is 409.', apply(ctx) { const st = ctx.state; st.tab = 'dead'; const d = st.dead.find((x) => x.id === 'dl-1'); if (d && d.state === 'open') { d.state = 'redriven'; d.redrivenBy = 'Mara Okafor'; d.redrivenAt = 'just now'; d.redriveJob = 'job-6a01b9'; } st.redriveNote = 'dl-1'; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      if (!st.queues) { st.queues = queues0(); st.qflags = qflags0(); st.reports = reports0(); st.appeals = appeals0(); st.actions = actions0(); st.sanctions = sanctions0(); st.providers = providers0(); st.verdicts = verdicts0; st.dead = dead0(); st.providersEnabled = true; }
      st.tab = st.tab || 'queues'; st.queueSel = st.queueSel || 'q-finance'; st.flagSort = st.flagSort || 'time'; st.flagKind = st.flagKind || 'all'; st.flagType = st.flagType || 'all';
      st.actType = st.actType || 'all'; st.actState = st.actState || 'all'; st.actSource = st.actSource || 'all'; st.sancState = st.sancState || 'all'; st.reportState = st.reportState || 'open';
      if (ctx.params.appeal) { st.tab = 'appeals'; st.appealSel = ctx.params.appeal; delete ctx.params.appeal; }
      if (ctx.params.queue) { st.tab = 'queues'; st.queueSel = ctx.params.queue; delete ctx.params.queue; }
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }

      const overdueAll = st.qflags.filter((f) => f.left < 0).length;
      const head = UI.pagehead('Moderation', 'Checks, reports and provider verdicts end in flags; this screen routes them, decides appeals and keeps sanctions. Every decision is written to the audit chain.', (overdueAll ? UI.pill(overdueAll + ' overdue', 'danger') : '') + UI.btn('Open Flags queue', { kind: 'ghost', size: 'sm', attrs: 'data-goflags' }));
      const tabs = UI.tabs(tabsDef(st), st.tab);
      let body = '', aside = '';

      // ---------------- Queues ----------------
      if (st.tab === 'queues') {
        const q = st.queues.find((x) => x.id === st.queueSel) || st.queues[0]; st.queueSel = q.id;
        const qrows = st.queues.slice().sort((a, b) => a.priority - b.priority).map((x) => {
          const fl = st.qflags.filter((f) => f.queue === x.id);
          return { cells: ['<b>' + esc(x.name) + '</b>', esc(x.workspace), '<span class="num">' + x.priority + '</span>', x.rules.length ? '<span class="mono">' + esc(x.rules.join(', ')) + '</span>' : small('any'), x.labels.length ? x.labels.map((l) => UI.label(l, { sm: true })).join(' ') : small('any'), x.kinds.length ? x.kinds.map((k) => UI.pill(k, 'outline')).join(' ') : small('any'), '<span class="num">' + x.sla + ' min</span>', esc(x.escalateTo) + small(', ' + x.escSla + ' min'), x.enabled ? UI.pill('enabled', 'ok') : UI.pill('disabled', ''), '<span class="num">' + fl.length + (fl.some((f) => f.left < 0) ? ' ' + UI.pill(fl.filter((f) => f.left < 0).length + ' overdue', 'danger') : '') + '</span>'], attrs: 'data-queue="' + x.id + '"', selected: x.id === q.id };
        });
        let fl = st.qflags.filter((f) => f.queue === q.id).filter((f) => st.flagKind === 'all' || f.kind === st.flagKind).filter((f) => st.flagType === 'all' || f.type === st.flagType);
        fl = fl.slice().sort((a, b) => st.flagSort === 'severity' ? (SEV_RANK[a.sev] - SEV_RANK[b.sev]) || (a.left - b.left) : st.flagSort === 'newest' ? b.when.localeCompare(a.when) : a.left - b.left);
        if (!st.flagSel || !fl.some((f) => f.id === st.flagSel)) st.flagSel = fl.length ? fl[0].id : null;
        const sel = st.qflags.find((f) => f.id === st.flagSel) || null;
        const types = ['all'].concat(OBJECT_TYPES.filter((t) => st.qflags.some((f) => f.queue === q.id && f.type === t)));
        body = UI.notice('<b>Routing.</b> A new flag goes to the first enabled queue (lowest priority number) whose workspace, rules, labels and kinds all match; its timer becomes the queue\'s SLA. Past the SLA, the sweep escalates it to the queue\'s escalation level with a fresh timer and notifies that level. A deleted queue leaves its flags unrouted.', 'info')
          + UI.panel('Review queues', UI.table(['Queue', 'Workspace', { label: 'Priority', right: true }, 'Rules', 'Labels', 'Kinds', { label: 'SLA', right: true }, 'Escalates to', 'State', { label: 'Open', right: true }], qrows, { minWidth: '1080px' }), { actions: UI.btn('New queue', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newqueue' }) + UI.btn('Edit', { size: 'sm', attrs: 'data-editqueue' }) + UI.btn(q.enabled ? 'Disable' : 'Enable', { size: 'sm', attrs: 'data-togglequeue' }) + UI.btn('Delete', { kind: 'ghost', size: 'sm', attrs: 'data-delqueue' }) })
          + (st.escalatedNote && q.id === 'q-finance' ? UI.notice('<b>F-2279 escalated.</b> It passed the 60 min SLA of Finance Ops review and now sits at the tenant level with a 120 min timer. Tenant moderation admins were notified (event flag.escalated, audit moderation.queue.escalated).', 'warn', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearesc' })) : '')
          + UI.panel('Flags in ' + q.name, '<div class="toolbar"><span class="relative">' + UI.btn(st.flagKind === 'all' ? 'Kind' : 'Kind: ' + st.flagKind, { size: 'sm', icon: 'filter', attrs: 'data-kindmenu', cls: st.flagKind === 'all' ? '' : 'active' }) + '</span><span class="relative">' + UI.btn(st.flagType === 'all' ? 'Object type' : 'Type: ' + st.flagType, { size: 'sm', icon: 'filter', attrs: 'data-typemenu', cls: st.flagType === 'all' ? '' : 'active' }) + '</span><span class="relative">' + UI.btn({ time: 'Least time left', severity: 'By severity', newest: 'Newest first' }[st.flagSort], { size: 'sm', icon: 'sort', attrs: 'data-sortmenu' }) + '</span>' + small(fl.length + ' of ' + st.qflags.filter((f) => f.queue === q.id).length + ' flags, ' + st.qflags.filter((f) => f.queue === q.id && f.left < 0).length + ' overdue, ' + st.qflags.filter((f) => f.queue === q.id && f.escalated).length + ' escalated') + '</div>'
            + UI.table(['Flag', 'Kind', 'Object', 'Rule or reason', 'Severity', 'Timer', 'Label', 'Owner'], fl.map((f) => ({ cells: ['<span class="mono">' + esc(f.id) + '</span>', UI.pill(f.kind, 'outline'), '<span class="mono">' + esc(f.type) + '</span> ' + small(esc(f.objectId)), esc(f.rule), sevPill(f.sev), (f.left < 0 ? '<span style="color:var(--danger-fg)">' + esc(timeText(f.left)) + '</span>' : esc(timeText(f.left))) + (f.escalated ? ' ' + UI.pill('escalated: ' + f.escalated, 'warn') : ''), UI.label(f.label, { sm: true }), esc(f.owner)], attrs: 'data-flag="' + f.id + '"', selected: f.id === st.flagSel })), { minWidth: '900px', emptyTitle: 'No flags match', emptyText: 'Clear the kind and type filters, or pick another queue.' }));
        aside = '<aside class="inspector w360">' + (sel ? '<div class="hstack"><div class="eyebrow grow">Selected flag</div>' + UI.label(sel.label, { sm: true }) + '</div><div class="mod-title mono">' + esc(sel.id) + '</div><div class="fg2">' + esc(sel.rule) + '</div>'
          + UI.kv([['Kind', esc(sel.kind) + ' at ' + esc(sel.kind === 'report' ? 'user-report' : sel.kind === 'hold' ? (sel.type === 'channel-message' ? 'channel-review' : 'user-input') : 'model-output')], ['Object', '<span class="mono">' + esc(sel.type) + '</span><br>' + small(esc(sel.objectId))], ['Owner', esc(sel.owner)], ['Severity', sevPill(sel.sev)], ['Timer', sel.left < 0 ? '<span style="color:var(--danger-fg)">overdue by ' + (-sel.left) + ' min</span>' : sel.left + ' of ' + sel.of + ' min'], ['Escalation', sel.escalated ? esc(sel.escalated) + ' level, ' + sel.escLeft + ' min left' : 'none, escalates to ' + esc(q.escalateTo) + ' after ' + q.sla + ' min'], ['Created', esc(sel.when)]], 1)
          + '<div class="vstack gap6" style="margin-top:8px">' + UI.btn('Hide object', { kind: 'primary', attrs: 'data-hide', disabled: !sel.hideable, title: sel.hideable ? '' : 'Flags that point at no registered object are 409' }) + UI.btn('Open in Flags', { attrs: 'data-openflag="' + sel.id + '"' }) + UI.btn('Rule in Guardrails', { kind: 'ghost', attrs: 'data-gorule' }) + '</div>'
          + (sel.hideable ? '' : small('This flag points at no object that can be hidden (a hold, or an outside post). Decide it in Flags.')) : UI.empty('No flag selected', 'Pick a row to see its timer and actions.')) + '</aside>';
      }

      // ---------------- Reports ----------------
      if (st.tab === 'reports') {
        const rows = st.reports.filter((r) => st.reportState === 'all' || r.state === st.reportState);
        body = UI.panel('Reports', '<div class="toolbar">' + UI.seg([{ id: 'open', label: 'Open' }, { id: 'dismissed', label: 'Dismissed' }, { id: 'all', label: 'All' }], st.reportState, 'data-reportseg') + small('A member reports an object they can see; it files a report flag at the user-report checkpoint in the object\'s workspace. The same reporter reporting again while the flag is open gets it back as a duplicate.') + '</div>'
          + UI.table(['Flag', 'Reporter', 'Object', 'Reason', 'Note', 'Severity', 'Due', 'Workspace', ''], rows.map((r) => ({ cells: ['<span class="mono">' + esc(r.flag) + '</span>' + (r.duplicate ? ' ' + UI.pill('duplicate', '') : ''), esc(r.reporter), '<span class="mono">' + esc(r.type) + '</span> ' + small(esc(r.objectId)), esc(r.reason), r.note ? '<span class="serif">' + esc(r.note) + '</span>' : small('none'), sevPill(r.sev), esc(r.due), esc(r.workspace), r.state === 'open' ? UI.btn('Open flag', { size: 'xs', attrs: 'data-openflag="' + r.flag + '"' }) : UI.pill('dismissed', '')] })), { clickable: false, minWidth: '960px', emptyTitle: 'No reports', emptyText: 'Nothing was reported in this state.' }), { actions: UI.btn('File a report', { size: 'sm', attrs: 'data-newreport' }) });
      }

      // ---------------- Appeals ----------------
      if (st.tab === 'appeals') {
        const list = st.appeals.slice().sort((a, b) => ({ pending: 0, reviewing: 1, upheld: 2, denied: 2 }[a.state] - { pending: 0, reviewing: 1, upheld: 2, denied: 2 }[b.state]));
        if (!st.appealSel || !st.appeals.some((a) => a.ref === st.appealSel)) st.appealSel = list[0].ref;
        const a = st.appeals.find((x) => x.ref === st.appealSel);
        const restricted = a.label === 'restricted';
        const statePill = (s) => UI.pill(s, s === 'pending' ? 'warn' : s === 'reviewing' ? 'info' : s === 'upheld' ? 'ok' : 'danger');
        body = UI.panel('Appeals', UI.table(['Appeal', 'Kind', 'Subject', 'Appellant', 'Filed by', 'Label', 'State', 'Filed'], list.map((x) => ({ cells: ['<span class="mono">' + esc(x.ref) + '</span>', esc(x.kind), esc(x.subject), esc(x.appellant), esc(x.filedBy), UI.label(x.label, { sm: true }), statePill(x.state) + (x.state === 'reviewing' ? ' ' + small(esc(x.reviewer)) : ''), esc(x.filed)], attrs: 'data-appeal="' + x.ref + '"', selected: x.ref === a.ref })), { minWidth: '860px' }), { actions: UI.btn('Record an appeal for someone', { size: 'sm', attrs: 'data-recordappeal' }) })
          + (st.independence === a.ref ? UI.problem('Independence refused', 'You took the decision under appeal (' + a.decisionReason + ', ' + a.decisionWhen + '), so you cannot review ' + a.ref + '. Another reviewer in ' + (a.label === 'confidential' ? 'Finance Ops' : 'People Ops') + ' with clearance for ' + a.label + ' must take it. The refusal is 403 with step independence.', '7c1e4b2a9d0f4e6b8a3c5d7e9f1b2c4d') : '')
          + (st.appealResult === a.ref && a.effects ? UI.notice('<b>' + esc(a.ref) + ' upheld.</b> Effects: object restored (moderation.action.reversed)' + (a.effects.flagReopened ? ', flag <a href="#" data-openflag="' + esc(a.effects.flagReopened) + '">' + esc(a.effects.flagReopened) + '</a> reopened with a fresh timer (flag.reopened)' : '') + ', ' + a.effects.labelsNegated + ' AT-Protocol label' + (a.effects.labelsNegated === 1 ? '' : 's') + ' negated (atproto.label.negated). The appellant has been notified.', 'ok', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearresult' })) : '')
          + (st.appealResult === a.ref && a.sanctionEnded ? UI.notice('<b>' + esc(a.ref) + ' upheld.</b> Sanction ' + esc(a.sanctionId) + ' ended as reversed; the user\'s sign-in works again. The user has been notified.', 'ok', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearresult' })) : '');
        aside = '<aside class="inspector w360"><div class="hstack"><div class="eyebrow grow">Appeal ' + esc(a.ref) + '</div>' + statePill(a.state) + '</div>'
          + '<div class="mod-title">' + esc(a.subject) + '</div>'
          + UI.kv([['Kind', esc(a.kind) + (a.kind === 'action' ? ' (hide)' : '')], ['Appellant', esc(a.appellant)], ['Filed by', esc(a.filedBy)], ['Decision under appeal', esc(a.decisionReason) + '<br>' + small('by ' + esc(a.decidedBy) + ', ' + esc(a.decisionWhen))], ['Label', UI.label(a.label, { sm: true })], ['Filed', esc(a.filed)]].concat(a.state === 'upheld' || a.state === 'denied' ? [['Decided', esc(a.decided) + ' by ' + esc(a.decidedAppealBy)], ['Note', esc(a.note || '')]] : []), 1)
          + '<div class="eyebrow" style="margin-top:8px">Statement</div>' + (restricted ? '<div class="mod-redacted">Withheld: the appeal is labelled restricted and your clearance is confidential. Only a reviewer cleared for restricted may read and decide it.</div>' : '<div class="serif mod-statement">' + esc(a.statement) + '</div>')
          + '<div class="vstack gap6" style="margin-top:10px">' + (a.state === 'pending' ? UI.btn('Review (claim)', { kind: 'primary', attrs: 'data-review', disabled: restricted }) : '') + (a.state === 'reviewing' ? UI.btn('Uphold', { kind: 'primary', attrs: 'data-decide="upheld"', disabled: restricted }) + UI.btn('Deny', { kind: 'danger', attrs: 'data-decide="denied"', disabled: restricted }) : '') + (a.actionId ? UI.btn('Show the action', { kind: 'ghost', attrs: 'data-goaction="' + esc(a.actionId) + '"' }) : '') + (a.sanctionId ? UI.btn('Show the sanction', { kind: 'ghost', attrs: 'data-gosanction="' + esc(a.sanctionId) + '"' }) : '') + '</div>'
          + (a.state === 'reviewing' && a.reviewer !== 'Mara Okafor' ? small('Claimed by ' + esc(a.reviewer) + '. Deciding while someone else reviews is 409.') : '')
          + '</aside>';
      }

      // ---------------- Actions ----------------
      if (st.tab === 'actions') {
        const rows = st.actions.filter((x) => (st.actType === 'all' || x.type === st.actType) && (st.actState === 'all' || x.state === st.actState) && (st.actSource === 'all' || x.source === st.actSource));
        body = UI.panel('Actions', '<div class="toolbar"><span class="relative">' + UI.btn(st.actType === 'all' ? 'Object type' : 'Type: ' + st.actType, { size: 'sm', icon: 'filter', attrs: 'data-acttype', cls: st.actType === 'all' ? '' : 'active' }) + '</span>' + UI.seg([{ id: 'all', label: 'All' }, { id: 'applied', label: 'Applied' }, { id: 'reversed', label: 'Reversed' }], st.actState, 'data-actstate') + UI.seg([{ id: 'all', label: 'Any source' }, { id: 'reviewer', label: 'Reviewer' }, { id: 'guardrail', label: 'Guardrail' }, { id: 'provider', label: 'Provider' }], st.actSource, 'data-actsource') + small(rows.length + ' of ' + st.actions.length) + '</div>'
          + UI.table(['Action', 'Object', 'Workspace', 'Owner', 'Flag', 'Source', 'Reason', 'State', 'When', 'Appeal'], rows.map((x) => ({ cells: ['<span class="mono">' + esc(x.id) + '</span>', '<span class="mono">' + esc(x.type) + '</span> ' + small(esc(x.objectId)), esc(x.workspace), esc(x.owner), x.restricted ? small('(redacted)') : '<a href="#" data-openflag="' + esc(x.flag) + '">' + esc(x.flag) + '</a>', UI.pill(x.source, 'outline') + ' ' + small(esc(x.by)), esc(x.reason), x.state === 'reversed' ? UI.pill('reversed', 'ok') + ' ' + small(esc(x.reversedBy)) : UI.pill('applied', 'warn'), esc(x.when), x.appeal ? '<a href="#" data-goappeal="' + esc(x.appeal) + '">' + esc(x.appeal) + '</a>' : small('none')], attrs: 'data-action="' + x.id + '"', selected: st.actionSel === x.id })), { minWidth: '1100px', emptyTitle: 'No actions match', emptyText: 'Widen the filters.' })
          + small('An action hides the object behind an open or confirmed flag; the owner is notified and may appeal once per action. Reversal comes only from an upheld appeal.'));
      }

      // ---------------- Sanctions ----------------
      if (st.tab === 'sanctions') {
        const rows = st.sanctions.filter((s) => st.sancState === 'all' || s.state === st.sancState);
        const kindPill = (k) => UI.pill(k, k === 'ban' ? 'danger' : k === 'suspend' ? 'warn' : '');
        body = UI.notice('<b>Step-up.</b> Issuing or lifting a sanction needs a browser session with a recent sign-in (within 5 min). A suspension or ban revokes the user\'s sessions at once and refuses every credential with 403 step sanction; a warning only notifies.', 'info')
          + UI.panel('Sanctions', '<div class="toolbar">' + UI.seg([{ id: 'all', label: 'All' }, { id: 'active', label: 'Active' }, { id: 'expired', label: 'Expired' }, { id: 'lifted', label: 'Lifted' }, { id: 'reversed', label: 'Reversed' }], st.sancState, 'data-sancstate') + '</div>'
            + UI.table(['Sanction', 'User', 'Kind', 'Reason', 'Flag', 'Starts', 'Ends', 'By', 'State', ''], rows.map((s) => ({ cells: ['<span class="mono">' + esc(s.id) + '</span>', esc(s.user), kindPill(s.kind), esc(s.reason), '<a href="#" data-openflag="' + esc(s.flag) + '">' + esc(s.flag) + '</a>', esc(s.starts), s.ends ? esc(s.ends) : small(s.kind === 'ban' ? 'until lifted' : 'none'), esc(s.by) + (s.sessions ? '<br>' + small(s.sessions + ' session' + (s.sessions === 1 ? '' : 's') + ' revoked') : ''), UI.pill(s.state, s.state === 'active' ? 'warn' : s.state === 'reversed' || s.state === 'lifted' ? 'ok' : '') + (s.endReason ? '<br>' + small(esc(s.endReason)) : ''), s.state === 'active' ? UI.btn('Lift', { size: 'xs', attrs: 'data-lift="' + s.id + '"' }) : (s.appeal ? '<a href="#" data-goappeal="' + esc(s.appeal) + '">' + esc(s.appeal) + '</a>' : '')] })), { clickable: false, minWidth: '1000px', emptyTitle: 'No sanctions', emptyText: 'Nothing in this state.' }), { actions: UI.btn('Issue sanction', { kind: 'primary', size: 'sm', attrs: 'data-newsanction' }) });
      }

      // ---------------- Providers ----------------
      if (st.tab === 'providers') {
        const off = !st.providersEnabled;
        body = (off ? UI.problem('External providers are off', 'MODERATION_EXTERNAL_PROVIDERS is not set on this deployment, so every provider route answers 403 with step disabled. Providers can be listed but not created, changed or enabled, and no verdict job is queued. Set the variable and restart to turn them on.', '9a4d2f0b7c3e4a1f8b6d0e2c4a6f8b1d') : UI.notice('<b>Zones.</b> A provider only runs in a zone whose egress reaches outside the site (an allow-list with a public range, or the external zone), never with ZONES_AIR_GAPPED. Created disabled and in shadow; enforce files the object\'s flag and hides a registered object on a flagged verdict.', 'info', UI.btn('Zones', { kind: 'ghost', size: 'sm', attrs: 'data-gozones' })))
          + UI.panel('External providers', UI.table(['Provider', 'Kind', 'URL', 'Secret', 'Zone', 'Mode', 'Object types', { label: 'Threshold', right: true }, 'State', { label: 'Verdicts', right: true }, ''], st.providers.map((p) => ({ cells: ['<b>' + esc(p.name) + '</b>', '<span class="mono">' + esc(p.kind) + '</span>', '<span class="mono">' + esc(p.url.replace(/^https?:\/\//, '').split('/')[0]) + '</span>' + small('/' + esc(p.url.split('/').slice(3).join('/'))), p.hasSecret ? UI.pill('stored, sealed', 'ok') : UI.pill('none', ''), '<span class="mono">' + esc(p.zone) + '</span>', UI.pill(p.mode, p.mode === 'enforce' ? 'danger' : 'warn'), p.types.map((t) => UI.pill(t, 'outline')).join(' '), '<span class="num">' + p.threshold.toFixed(2) + '</span>', p.enabled ? UI.pill('enabled', 'ok') : UI.pill('disabled', ''), '<span class="num">' + p.verdicts.toLocaleString() + '</span>' + small(', ' + p.flagged + ' flagged, p95 ' + p.p95 + ' ms'), '<span class="hstack gap6" style="justify-content:flex-end">' + UI.btn('Verdicts', { size: 'xs', attrs: 'data-verdicts="' + p.id + '"' }) + UI.btn('Edit', { size: 'xs', attrs: 'data-editprov="' + p.id + '"', disabled: off }) + UI.btn(p.enabled ? 'Disable' : 'Enable', { size: 'xs', attrs: 'data-toggleprov="' + p.id + '"', disabled: off }) + UI.btn(p.mode === 'shadow' ? 'Enforce' : 'Shadow', { size: 'xs', kind: 'ghost', attrs: 'data-modeprov="' + p.id + '"', disabled: off }) + '</span>'] })), { clickable: false, minWidth: '1180px' }), { actions: UI.btn('Add provider', { kind: 'primary', size: 'sm', icon: 'plus', attrs: 'data-newprov', disabled: off }) })
          + small('Wire formats: json (POST {input, type} answers {flagged, score?, categories?}) and openai (the OpenAI moderation shape). The key goes as Authorization: Bearer and is stored sealed, never shown. A failed call retries, then lands in the dead-letter queue.');
      }

      // ---------------- Dead letters ----------------
      if (st.tab === 'dead') {
        body = UI.panel('Dead-letter queue', UI.table(['Entry', 'Job', 'Type', 'Provider', 'Object', 'Error', { label: 'Attempts', right: true }, 'Failed', 'State', ''], st.dead.map((d) => ({ cells: ['<span class="mono">' + esc(d.id) + '</span>', '<span class="mono">' + esc(d.job) + '</span>', '<span class="mono">' + esc(d.type) + '</span>', esc(d.provider), esc(d.object), '<span class="mono" style="font-size:12px">' + esc(d.error) + '</span>', '<span class="num">' + d.attempts + '</span>', esc(d.failed), d.state === 'open' ? UI.pill('open', 'danger') : UI.pill('redriven', 'ok') + '<br>' + small('by ' + esc(d.redrivenBy) + ', ' + esc(d.redrivenAt) + ', <span class="mono">' + esc(d.redriveJob) + '</span>'), UI.btn('Redrive', { size: 'xs', kind: d.state === 'open' ? 'primary' : '', attrs: 'data-redrive="' + d.id + '"', title: d.state === 'open' ? '' : 'Already redriven: 409' })] })), { clickable: false, minWidth: '1100px', emptyTitle: 'Nothing dead-lettered', emptyText: 'Every moderation job finished within its attempts.' }))
          + (st.redriveNote ? UI.notice('<b>' + esc(st.redriveNote) + ' redriven.</b> The job was queued again with its payload; the texts in it stay sealed. Audit moderation.job.redriven written. A second redrive answers 409.', 'ok', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearredrive' })) : '')
          + (st.redriveConflict ? UI.problem('Already redriven', st.redriveConflict + ' was redriven once; a second redrive is refused with 409. Follow the new job instead.', '3e8a1c6f2b9d4e0a7c5f1b3d9e2a4c6f') : '')
          + small('Moderation jobs (moderation.provider) that failed their last attempt land here, audited as moderation.job.dead_lettered. <a href="#" data-goaudit>Open the audit chain</a>.');
      }

      root.innerHTML = '<style>'
        + '#main > .page > *{flex-shrink:0}'
        + '#main .mod-title{font-size:16px;font-weight:600;margin:4px 0 2px}#main .dt td > .mono:first-child{white-space:nowrap}'
        + '#main .mod-statement{font-size:14px;line-height:1.5;padding:8px 10px;background:var(--panel2);border-radius:6px}'
        + '#main .mod-redacted{display:inline-block;padding:6px 10px;background:var(--sel);color:var(--muted);font-size:13px;border-radius:4px}'
        + '#main .inspector .kv .v{overflow-wrap:anywhere}'
        + '</style>'
        + '<div class="page">' + head + tabs + body
        + '</div>' + aside;

      // ---- events ----
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-goflags]', () => ctx.navigate('flags'));
      ctx.on('click', '[data-openflag]', (e, t) => { e.preventDefault(); ctx.navigate('flags', { id: t.dataset.openflag }); });
      ctx.on('click', '[data-gorule]', () => ctx.navigate('guardrails'));
      ctx.on('click', '[data-gozones]', () => ctx.navigate('zones'));
      ctx.on('click', '[data-goaudit]', (e) => { e.preventDefault(); ctx.navigate('usage-audit'); });
      ctx.on('click', '[data-goappeal]', (e, t) => { e.preventDefault(); st.tab = 'appeals'; st.appealSel = t.dataset.goappeal; ctx.rerender(); });
      ctx.on('click', '[data-goaction]', (e, t) => { st.tab = 'actions'; st.actionSel = t.dataset.goaction; st.actType = 'all'; st.actState = 'all'; st.actSource = 'all'; ctx.rerender(); });
      ctx.on('click', '[data-gosanction]', () => { st.tab = 'sanctions'; st.sancState = 'all'; ctx.rerender(); });
      // queues
      ctx.on('click', 'tr[data-queue]', (e, t) => { st.queueSel = t.dataset.queue; st.flagSel = null; ctx.rerender(); });
      ctx.on('click', 'tr[data-flag]', (e, t) => { st.flagSel = t.dataset.flag; ctx.rerender(); });
      ctx.on('click', '[data-kindmenu]', (e, t) => menu(ctx, t, [['all', 'All kinds'], ['guard', 'Guard'], ['report', 'Report'], ['hold', 'Hold'], ['reviewer', 'Reviewer']], st.flagKind, (v) => { st.flagKind = v; ctx.rerender(); }));
      ctx.on('click', '[data-typemenu]', (e, t) => { const q = st.queueSel; const types = ['all'].concat(OBJECT_TYPES.filter((x) => st.qflags.some((f) => f.queue === q && f.type === x))); menu(ctx, t, types.map((x) => [x, x === 'all' ? 'All object types' : x]), st.flagType, (v) => { st.flagType = v; ctx.rerender(); }); });
      ctx.on('click', '[data-sortmenu]', (e, t) => menu(ctx, t, [['time', 'Least time left'], ['severity', 'By severity'], ['newest', 'Newest first']], st.flagSort, (v) => { st.flagSort = v; ctx.rerender(); }));
      ctx.on('click', '[data-clearesc]', () => { st.escalatedNote = false; ctx.rerender(); });
      ctx.on('click', '[data-newqueue]', () => queueModal(ctx, null));
      ctx.on('click', '[data-editqueue]', () => queueModal(ctx, st.queues.find((x) => x.id === st.queueSel)));
      ctx.on('click', '[data-togglequeue]', () => { const q = st.queues.find((x) => x.id === st.queueSel); q.enabled = !q.enabled; ctx.rerender(); ctx.toast(esc(q.name) + (q.enabled ? ' enabled. New matching flags route here.' : ' disabled. New flags skip it; its open flags stay.'), q.enabled ? 'ok' : 'warn'); });
      ctx.on('click', '[data-delqueue]', async () => { const q = st.queues.find((x) => x.id === st.queueSel); const n = st.qflags.filter((f) => f.queue === q.id).length; const ok = await ctx.confirm({ title: 'Delete queue', tag: 'flags become unrouted', tone: 'danger', body: '<p style="margin:0" class="fg2">The queue is removed and its ' + n + ' open flag' + (n === 1 ? '' : 's') + ' become unrouted: they keep their timers but no SLA escalation applies until another queue matches them. Audited as moderation.queue.deleted.</p>', kv: [['Queue', q.name], ['Workspace', q.workspace], ['Open flags', String(n)]], ok: 'Delete' }); if (!ok) return; st.queues = st.queues.filter((x) => x.id !== q.id); st.qflags = st.qflags.filter((f) => f.queue !== q.id); st.queueSel = null; ctx.rerender(); ctx.toast(esc(q.name) + ' deleted. ' + n + ' flags are unrouted.', 'warn'); });
      ctx.on('click', '[data-hide]', async () => { const f = st.qflags.find((x) => x.id === st.flagSel); if (!f) return; const ok = await ctx.confirm({ title: 'Hide object', tag: 'notifies the owner', tone: 'danger', body: '<p style="margin:0" class="fg2">Hides <span class="mono">' + esc(f.type) + ' ' + esc(f.objectId) + '</span> behind this flag (an open flag is confirmed first). The owner is notified and may appeal once. Audited as moderation.action.applied.</p>' + UI.field('Reason', UI.textarea(f.rule + ' at the ' + (f.kind === 'report' ? 'user-report' : 'model-output') + ' checkpoint', { rows: 2 })), kv: [['Flag', f.id], ['Object', f.type + ' ' + f.objectId], ['Owner', f.owner]], ok: 'Hide' }); if (!ok) return; const id = 'act-' + (45 + st.actions.length); st.actions.unshift({ id, type: f.type, objectId: f.objectId, workspace: st.queues.find((q) => q.id === f.queue).workspace, owner: f.owner, flag: f.id, state: 'applied', source: 'reviewer', by: 'Mara Okafor', reason: f.rule, when: 'just now' }); st.qflags = st.qflags.filter((x) => x.id !== f.id); st.flagSel = null; ctx.rerender(); ctx.toast(esc(f.id) + ' confirmed and the object hidden as ' + id + '. The owner has been notified.', 'ok'); });
      // reports
      ctx.on('click', '[data-reportseg] [data-seg]', (e, t) => { st.reportState = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-newreport]', () => ctx.modal({ title: 'File a report', body: '<div class="formgrid">' + UI.field('Object type', UI.select(OBJECT_TYPES, 'feed-post', 'data-rtype')) + UI.field('Object id', UI.input('', { placeholder: 'p-4c20', attrs: 'data-rid' })) + UI.field('Reason', UI.select(['Harassment', 'Spam', 'Wrong or unsupported figure', 'Sensitive data', 'Other'], 'Harassment', 'data-rreason')) + UI.field('Severity', UI.select(['high', 'medium', 'low'], 'medium', 'data-rsev')) + '</div>' + UI.field('Note', UI.textarea('', { rows: 2, placeholder: 'What should the reviewer look at?', attrs: 'data-rnote' })) + UI.notice('Only an object you can see, within your clearance; anything else is the same 404. The report files a flag in the object\'s workspace queue.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Report', { kind: 'primary', attrs: 'data-doreport' }), onMount(m) { m.querySelector('[data-doreport]').addEventListener('click', () => { const type = m.querySelector('[data-rtype]').value, id = m.querySelector('[data-rid]').value.trim() || 'p-4c20'; const dup = st.reports.find((r) => r.type === type && r.objectId === id && r.state === 'open' && r.reporter === 'Mara Okafor'); App.closeOverlay(); if (dup) { ctx.toast('You already reported ' + esc(type) + ' ' + esc(id) + ': flag ' + esc(dup.flag) + ' is still open (duplicate: true).', 'warn'); return; } const flag = 'F-23' + (10 + st.reports.length); st.reports.unshift({ flag, reporter: 'Mara Okafor', type, objectId: id, reason: m.querySelector('[data-rreason]').value, note: m.querySelector('[data-rnote]').value, sev: m.querySelector('[data-rsev]').value, due: '19 Sep 18:30', duplicate: false, workspace: 'Finance Ops', state: 'open' }); st.qflags.push({ id: flag, queue: 'q-social', kind: 'report', type, objectId: id, rule: 'User report', sev: m.querySelector('[data-rsev]').value, left: 240, of: 240, label: 'internal', owner: 'unknown until resolved', when: 'just now', hideable: true }); st.reportState = 'open'; ctx.rerender(); ctx.toast('Reported as ' + flag + ' in Posts and messages. Audit moderation.reported written.', 'ok'); }); } }));
      // appeals
      ctx.on('click', 'tr[data-appeal]', (e, t) => { st.appealSel = t.dataset.appeal; ctx.rerender(); });
      ctx.on('click', '[data-clearresult]', () => { st.appealResult = null; ctx.rerender(); });
      ctx.on('click', '[data-review]', () => { const a = st.appeals.find((x) => x.ref === st.appealSel); if (a.decidedBy === 'Mara Okafor' || a.appellant === 'Mara Okafor') { st.independence = a.ref; ctx.rerender(); return; } a.state = 'reviewing'; a.reviewer = 'Mara Okafor'; st.independence = null; ctx.rerender(); ctx.toast(esc(a.ref) + ' claimed. Audited as moderation.appeal.reviewing.', 'ok'); });
      ctx.on('click', '[data-decide]', async (e, t) => { const a = st.appeals.find((x) => x.ref === st.appealSel); const d = t.dataset.decide; if (a.reviewer && a.reviewer !== 'Mara Okafor') { ctx.toast(esc(a.reviewer) + ' is reviewing ' + esc(a.ref) + '. Deciding now is 409.', 'warn'); return; } const ok = await ctx.confirm({ title: (d === 'upheld' ? 'Uphold ' : 'Deny ') + a.ref, tag: d === 'upheld' ? (a.kind === 'action' ? 'restores the object' : 'ends the sanction') : 'keeps the decision', tone: d === 'upheld' ? 'info' : 'danger', body: '<p style="margin:0" class="fg2">' + (d === 'upheld' ? (a.kind === 'action' ? 'The object is restored to its previous state, its flag reopened with a fresh timer and the AT-Protocol labels made from the flag negated.' : 'The sanction ends as reversed and the user can sign in again.') : 'The decision under appeal stands. The appellant is told, without the reviewer\'s name.') + '</p>' + UI.field('Note to the appellant', UI.textarea('', { rows: 2, attrs: 'data-dnote' })), kv: [['Appeal', a.ref], ['Subject', a.subject], ['Appellant', a.appellant]], ok: d === 'upheld' ? 'Uphold' : 'Deny' }); if (!ok) return; a.state = d; a.decided = 'just now'; a.decidedAppealBy = 'Mara Okafor'; a.note = a.note || (d === 'upheld' ? 'Upheld on review.' : 'Denied on review.'); if (d === 'upheld') { if (a.kind === 'action') { a.effects = { restored: true, flagReopened: (st.actions.find((x) => x.id === a.actionId) || {}).flag || null, labelsNegated: a.ref === 'A-3' ? 0 : 1 }; const act = st.actions.find((x) => x.id === a.actionId); if (act) { act.state = 'reversed'; act.reversedBy = 'Mara Okafor (appeal ' + a.ref + ')'; act.reversedAt = 'just now'; } } else { a.sanctionEnded = true; const s = st.sanctions.find((x) => x.id === a.sanctionId); if (s) { s.state = 'reversed'; s.endedBy = 'appeal ' + a.ref; s.endReason = 'Appeal upheld'; } } st.appealResult = a.ref; } ctx.rerender(); ctx.toast(esc(a.ref) + ' ' + d + '. Audited as moderation.appeal.' + d + '; the appellant is notified.', d === 'upheld' ? 'ok' : ''); });
      ctx.on('click', '[data-recordappeal]', () => ctx.modal({ title: 'Record an appeal for someone', body: UI.field('For user', UI.select(['Samir Haddad (suspended, cannot sign in)', 'svc-close-bot (banned service account)'], 'Samir Haddad (suspended, cannot sign in)')) + UI.field('Against', UI.select(['Sanction S-12: suspension, 7 days', 'Action act-42: feed-post p-3f77 hidden'], 'Action act-42: feed-post p-3f77 hidden', 'data-against')) + UI.field('Statement (as given by the user)', UI.textarea('', { rows: 3, attrs: 'data-stmt' })) + UI.notice('One open appeal per action or sanction; a second is 409. The statement is sealed with the tenant key.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Record', { kind: 'primary', attrs: 'data-dorecord' }), onMount(m) { m.querySelector('[data-dorecord]').addEventListener('click', () => { const against = m.querySelector('[data-against]').value; App.closeOverlay(); if (against.startsWith('Sanction') && st.appeals.some((x) => x.sanctionId === 'S-12' && (x.state === 'pending' || x.state === 'reviewing'))) { ctx.toast('S-12 already has an open appeal (A-4). 409.', 'warn'); return; } const ref = 'A-' + (7 + st.appeals.length - 6); st.appeals.unshift({ ref, kind: 'action', actionId: 'act-42', subject: 'feed-post p-3f77', appellant: 'Samir Haddad', filedBy: 'Mara Okafor (for the user)', label: 'internal', state: 'pending', filed: 'just now', statement: m.querySelector('[data-stmt]').value || 'Recorded by a reviewer on the user\'s behalf.', decidedBy: 'Perspective-compatible (enforce)', decisionWhen: '19 Sep 07:12', decisionReason: 'toxicity 0.91 above threshold 0.85' }); st.appealSel = ref; ctx.rerender(); ctx.toast(ref + ' recorded for Samir Haddad. Audited as moderation.appeal.submitted.', 'ok'); }); } }));
      // actions
      ctx.on('click', '[data-acttype]', (e, t) => menu(ctx, t, [['all', 'All object types']].concat(OBJECT_TYPES.filter((x) => st.actions.some((a) => a.type === x)).map((x) => [x, x])), st.actType, (v) => { st.actType = v; ctx.rerender(); }));
      ctx.on('click', '[data-actstate] [data-seg]', (e, t) => { st.actState = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-actsource] [data-seg]', (e, t) => { st.actSource = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', 'tr[data-action]', (e, t) => { st.actionSel = t.dataset.action; ctx.rerender(); });
      // sanctions
      ctx.on('click', '[data-sancstate] [data-seg]', (e, t) => { st.sancState = t.dataset.seg; ctx.rerender(); });
      ctx.on('click', '[data-lift]', async (e, t) => { const s = st.sanctions.find((x) => x.id === t.dataset.lift); const ok = await ctx.confirm({ title: 'Lift ' + s.id, tag: 'step-up', tone: 'info', body: '<p style="margin:0" class="fg2">Ends the ' + esc(s.kind) + ' now. ' + (s.kind === 'warn' ? 'The user is told the warning no longer stands.' : 'The user can sign in again at once.') + ' Audited as moderation.sanction.lifted.</p>' + UI.field('Reason', UI.input('', { placeholder: 'Why it ends early' })), kv: [['User', s.user], ['Kind', s.kind], ['Issued by', s.by]], ok: 'Lift' }); if (!ok) return; s.state = 'lifted'; s.endedBy = 'Mara Okafor'; s.endReason = 'Lifted on review'; s.ends = 'just now'; ctx.rerender(); ctx.toast(esc(s.id) + ' lifted. ' + esc(s.user) + ' has been notified.', 'ok'); });
      ctx.on('click', '[data-newsanction]', () => sanctionModal(ctx));
      if (st.openSanction) { st.openSanction = false; setTimeout(() => sanctionModal(ctx), 50); }
      // providers
      ctx.on('click', '[data-newprov]', () => providerModal(ctx, null));
      ctx.on('click', '[data-editprov]', (e, t) => providerModal(ctx, st.providers.find((p) => p.id === t.dataset.editprov)));
      ctx.on('click', '[data-toggleprov]', async (e, t) => { const p = st.providers.find((x) => x.id === t.dataset.toggleprov); if (!p.enabled) { const ok = await ctx.confirm({ title: 'Enable ' + p.name, tag: p.mode, tone: p.mode === 'enforce' ? 'danger' : 'info', body: '<p style="margin:0" class="fg2">Each check of ' + esc(p.types.join(', ')) + ' queues a moderation.provider job with the text sealed in the payload. ' + (p.mode === 'enforce' ? 'In enforce mode a flagged verdict files the object\'s flag and hides a registered object.' : 'In shadow mode the verdict is recorded and nothing else happens.') + ' The zone is checked again now.</p>', kv: [['Zone', p.zone], ['Threshold', p.threshold.toFixed(2)]], ok: 'Enable' }); if (!ok) return; } p.enabled = !p.enabled; ctx.rerender(); ctx.toast(esc(p.name) + (p.enabled ? ' enabled.' : ' disabled. Queued jobs still finish.'), p.enabled ? 'ok' : ''); });
      ctx.on('click', '[data-modeprov]', async (e, t) => { const p = st.providers.find((x) => x.id === t.dataset.modeprov); const to = p.mode === 'shadow' ? 'enforce' : 'shadow'; const ok = await ctx.confirm({ title: 'Switch ' + p.name + ' to ' + to, tag: to, tone: to === 'enforce' ? 'danger' : 'info', body: '<p style="margin:0" class="fg2">' + (to === 'enforce' ? 'From now on a flagged verdict files or reuses the object\'s flag, hides a registered object and is audited as moderation.provider.enforced. Check the shadow verdicts first.' : 'Verdicts are recorded only; nothing is flagged or hidden.') + '</p>', kv: [['Shadow verdicts so far', p.verdicts + ', ' + p.flagged + ' flagged']], ok: 'Switch' }); if (!ok) return; p.mode = to; ctx.rerender(); ctx.toast(esc(p.name) + ' now in ' + to + ' mode.', to === 'enforce' ? 'warn' : 'ok'); });
      ctx.on('click', '[data-verdicts]', (e, t) => { const p = st.providers.find((x) => x.id === t.dataset.verdicts); const v = st.verdicts[p.id] || []; ctx.drawer({ title: 'Verdicts: ' + esc(p.name), body: UI.kv([['Mode now', UI.pill(p.mode, p.mode === 'enforce' ? 'danger' : 'warn')], ['Threshold', p.threshold.toFixed(2)], ['Verdicts', p.verdicts.toLocaleString() + ', ' + p.flagged + ' flagged'], ['Latency p95', p.p95 + ' ms']], 2) + UI.table(['Verdict', 'Object', 'Mode', 'Flagged', 'Categories', { label: 'Score', right: true }, 'Acted', { label: 'ms', right: true }, 'When'], v.map((x) => [ '<span class="mono">' + esc(x.id) + '</span>', '<span class="mono">' + esc(x.type) + '</span> ' + small(esc(x.objectId)), UI.pill(x.mode, x.mode === 'enforce' ? 'danger' : 'warn'), x.flagged ? UI.pill('flagged', 'danger') : UI.pill('clear', 'ok'), esc(x.cats || '') || small('none'), '<span class="num">' + x.score.toFixed(2) + '</span>', x.acted ? '<a href="#" data-openflag="' + esc(x.flag) + '">' + esc(x.flag) + '</a>' : small(x.flagged ? 'shadow, not acted' : 'no'), '<span class="num">' + x.ms + '</span>', esc(x.when)]), { clickable: false, minWidth: '0' }), actions: UI.btn('Close', { attrs: 'data-close' }) }); });
      // dead letters
      ctx.on('click', '[data-redrive]', async (e, t) => { const d = st.dead.find((x) => x.id === t.dataset.redrive); if (d.state === 'redriven') { st.redriveConflict = d.id; st.redriveNote = null; ctx.rerender(); return; } const ok = await ctx.confirm({ title: 'Redrive ' + d.id, tag: 'queues the job again', tone: 'info', body: '<p style="margin:0" class="fg2">The job runs again with its stored payload; the texts in it stay sealed. If the provider is still down it will land here again after its attempts.</p>', kv: [['Job', d.job], ['Provider', d.provider], ['Last error', d.error]], ok: 'Redrive' }); if (!ok) return; d.state = 'redriven'; d.redrivenBy = 'Mara Okafor'; d.redrivenAt = 'just now'; d.redriveJob = 'job-6a0' + Math.floor(Math.random() * 900 + 100); st.redriveNote = d.id; st.redriveConflict = null; ctx.rerender(); ctx.toast(esc(d.id) + ' redriven as ' + esc(d.redriveJob) + '.', 'ok'); });
      ctx.on('click', '[data-clearredrive]', () => { st.redriveNote = null; ctx.rerender(); });
    }
  });

  function queueModal(ctx, q) {
    const st = ctx.state; const isNew = !q;
    const v = q || { name: '', workspace: 'Finance Ops', rules: [], labels: [], kinds: [], priority: 50, sla: 60, escalateTo: 'tenant', escSla: 120, enabled: true };
    ctx.modal({ title: isNew ? 'New review queue' : 'Edit ' + esc(v.name), cls: 'wide',
      body: '<div class="formgrid">' + UI.field('Name', UI.input(v.name, { attrs: 'data-qname', placeholder: 'Finance Ops review' })) + UI.field('Workspace', UI.select(['Finance Ops', 'People Ops', 'Field Sales', 'Any workspace'], v.workspace, 'data-qws')) + UI.field('Priority', UI.input(String(v.priority), { type: 'number', attrs: 'data-qprio' }), 'Lower numbers are tried first') + UI.field('SLA (minutes)', UI.input(String(v.sla), { type: 'number', attrs: 'data-qsla' })) + UI.field('Escalates to', UI.select(['workspace', 'tenant', 'platform'], v.escalateTo, 'data-qesc')) + UI.field('Escalation SLA (minutes)', UI.input(String(v.escSla), { type: 'number', attrs: 'data-qescsla' })) + '</div>'
        + UI.field('Rules (ids or names, comma separated; empty matches any)', UI.input(v.rules.join(', '), { attrs: 'data-qrules', placeholder: 'numeric-grounding, export-iban' }))
        + UI.field('Labels', '<div class="hstack wrap gap6">' + ['public', 'internal', 'confidential', 'restricted'].map((l) => UI.chip(UI.label(l, { sm: true }), v.labels.includes(l), 'data-qlabel="' + l + '"')).join('') + '</div>', 'Empty matches any label')
        + UI.field('Kinds (flag kind, object type or checkpoint)', UI.input(v.kinds.join(', '), { attrs: 'data-qkinds', placeholder: 'guard, report, hold, feed-post' }))
        + UI.toggle('Enabled', v.enabled, 'data-qenabled'),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(isNew ? 'Create queue' : 'Save', { kind: 'primary', attrs: 'data-qsave' }),
      onMount(m) {
        m.querySelectorAll('[data-qlabel]').forEach((c) => c.addEventListener('click', () => c.classList.toggle('on')));
        m.querySelector('[data-qsave]').addEventListener('click', () => {
          const name = m.querySelector('[data-qname]').value.trim(); if (!name) { ctx.toast('A queue needs a name.', 'warn'); return; }
          if (st.queues.some((x) => x.name.toLowerCase() === name.toLowerCase() && x !== q)) { ctx.toast('A queue named ' + esc(name) + ' exists: 409.', 'danger'); return; }
          const split = (s) => s.split(',').map((x) => x.trim()).filter(Boolean);
          const next = { name, workspace: m.querySelector('[data-qws]').value, priority: +m.querySelector('[data-qprio]').value || 50, sla: +m.querySelector('[data-qsla]').value || 60, escalateTo: m.querySelector('[data-qesc]').value, escSla: +m.querySelector('[data-qescsla]').value || 120, rules: split(m.querySelector('[data-qrules]').value), labels: Array.from(m.querySelectorAll('[data-qlabel].on')).map((c) => c.dataset.qlabel), kinds: split(m.querySelector('[data-qkinds]').value), enabled: m.querySelector('[data-qenabled]').classList.contains('on') };
          App.closeOverlay();
          if (isNew) { next.id = 'q-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-'); st.queues.push(next); st.queueSel = next.id; } else Object.assign(q, next);
          ctx.rerender(); ctx.toast((isNew ? 'Queue created. ' : 'Queue saved. ') + 'Audited as moderation.queue.' + (isNew ? 'created' : 'updated') + '.', 'ok');
        });
      } });
  }

  function sanctionModal(ctx) {
    const st = ctx.state;
    ctx.modal({ title: 'Issue sanction', body: UI.notice('Needs a recent sign-in (step-up). Not yourself; an administrator (a role that requires MFA) only by a tenant admin, a system admin only by a system admin.', 'info')
      + '<div class="formgrid">' + UI.field('User', UI.select(['Tomasz Weber (member)', 'Felix Brandt (workflow admin)', 'Noor Rahimi (member, People Ops)', 'Jonas Lindqvist (tenant admin)', 'Mara Okafor (you)'], 'Tomasz Weber (member)', 'data-suser')) + UI.field('Kind', UI.select(['warn', 'suspend', 'ban'], 'warn', 'data-skind')) + UI.field('Duration (minutes)', UI.input('', { type: 'number', attrs: 'data-sdur', placeholder: 'required for suspend' })) + UI.field('Flag', UI.select(['F-2291', 'F-2288', 'F-2290', 'none'], 'F-2291', 'data-sflag')) + '</div>' + UI.field('Reason', UI.textarea('', { rows: 2, attrs: 'data-sreason' })),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Issue', { kind: 'primary', attrs: 'data-sissue' }),
      onMount(m) { m.querySelector('[data-sissue]').addEventListener('click', () => {
        const user = m.querySelector('[data-suser]').value, kind = m.querySelector('[data-skind]').value, dur = +m.querySelector('[data-sdur]').value, reason = m.querySelector('[data-sreason]').value.trim();
        if (user.includes('(you)')) { ctx.toast('You cannot sanction yourself: 422 step self.', 'danger'); return; }
        if (user.includes('tenant admin')) { ctx.toast('An administrator can be sanctioned only by a tenant admin: 403 step role.', 'danger'); return; }
        if (kind === 'suspend' && !dur) { ctx.toast('A suspension needs a duration.', 'warn'); return; }
        if (!reason) { ctx.toast('A reason is required; the user reads it.', 'warn'); return; }
        App.closeOverlay();
        const id = 'S-' + (13 + st.sanctions.filter((s) => +s.id.slice(2) >= 13).length);
        st.sanctions.unshift({ id, user: user.replace(/\s*\(.*\)$/, ''), kind, reason, flag: m.querySelector('[data-sflag]').value, state: 'active', starts: 'just now', ends: kind === 'suspend' ? 'in ' + (dur >= 1440 ? Math.round(dur / 1440) + ' d' : dur + ' min') : null, by: 'Mara Okafor', sessions: kind === 'warn' ? 0 : 2 });
        st.sancState = 'all'; ctx.rerender();
        ctx.toast(id + ' issued: ' + kind + ' for ' + esc(user.replace(/\s*\(.*\)$/, '')) + (kind === 'warn' ? '. Notified.' : '. 2 sessions revoked; sign-in refused until it ends.'), kind === 'warn' ? 'ok' : 'warn');
      }); } });
  }

  function providerModal(ctx, p) {
    const st = ctx.state; const isNew = !p;
    const v = p || { name: '', kind: 'json', url: '', zone: 'external', mode: 'shadow', types: ['feed-post'], threshold: 0.8 };
    ctx.modal({ title: isNew ? 'Add provider' : 'Edit ' + esc(v.name), cls: 'wide',
      body: '<div class="formgrid">' + UI.field('Name', UI.input(v.name, { attrs: 'data-pname' })) + UI.field('Kind', UI.select(['json', 'openai'], v.kind, 'data-pkind')) + UI.field('URL', UI.input(v.url, { attrs: 'data-purl', placeholder: 'https://moderation.example/v1/score' }), 'Passes the service URL checks; a metadata or link-local address is 422 step url') + UI.field('Secret (Authorization: Bearer)', UI.input('', { type: 'password', placeholder: isNew ? 'stored sealed, never shown' : 'leave blank to keep', attrs: 'data-psecret' })) + UI.field('Zone', UI.select(['external', 'office', 'vpn', 'build (air-gapped)'], v.zone, 'data-pzone'), 'Egress must reach outside the site') + UI.field('Threshold', UI.input(String(v.threshold), { type: 'number', attrs: 'data-pthr' })) + '</div>'
        + UI.field('Object types', '<div class="hstack wrap gap6">' + ['message', 'conversation', 'feed-post', 'feed-comment', 'dm-message', 'group-post', 'channel-message', 'knowledge-document'].map((t) => UI.chip(esc(t), v.types.includes(t), 'data-ptype="' + t + '"')).join('') + '</div>')
        + UI.field('Mode', UI.seg([{ id: 'shadow', label: 'Shadow' }, { id: 'enforce', label: 'Enforce' }], v.mode, 'data-pmode'))
        + (isNew ? UI.notice('Created disabled and in shadow mode; enable it from the list once its verdicts look right.', 'info') : ''),
      actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn(isNew ? 'Add' : 'Save', { kind: 'primary', attrs: 'data-psave' }),
      onMount(m) {
        m.querySelectorAll('[data-ptype]').forEach((c) => c.addEventListener('click', () => c.classList.toggle('on')));
        m.querySelector('[data-pmode]').addEventListener('click', (e) => { const b = e.target.closest('[data-seg]'); if (!b) return; m.querySelectorAll('[data-pmode] [data-seg]').forEach((x) => x.classList.toggle('active', x === b)); });
        m.querySelector('[data-psave]').addEventListener('click', () => {
          const zone = m.querySelector('[data-pzone]').value, url = m.querySelector('[data-purl]').value.trim(), name = m.querySelector('[data-pname]').value.trim();
          if (!name || !url) { ctx.toast('Name and URL are required.', 'warn'); return; }
          if (/169\.254\.|metadata|localhost|127\./.test(url)) { ctx.toast('URL refused by the service address checks: 422 step url.', 'danger'); return; }
          if (zone.startsWith('build')) { ctx.toast('Zone build is air-gapped; a provider needs egress outside the site: 403 step zone.', 'danger'); return; }
          const next = { name, kind: m.querySelector('[data-pkind]').value, url, zone: zone.split(' ')[0], threshold: +m.querySelector('[data-pthr]').value || 0.8, types: Array.from(m.querySelectorAll('[data-ptype].on')).map((c) => c.dataset.ptype), hasSecret: isNew ? !!m.querySelector('[data-psecret]').value : (p.hasSecret || !!m.querySelector('[data-psecret]').value) };
          App.closeOverlay();
          if (isNew) { Object.assign(next, { id: 'pv-' + (st.providers.length + 1), mode: 'shadow', enabled: false, verdicts: 0, flagged: 0, p95: 0 }); st.providers.push(next); } else { next.mode = m.querySelector('[data-pmode] .active').dataset.seg; Object.assign(p, next); }
          ctx.rerender(); ctx.toast((isNew ? 'Provider added, disabled, in shadow mode. ' : 'Provider saved. ') + 'Audited with the host only.', 'ok');
        });
      } });
  }
})();
