(function () {
  const { UI, esc } = App;

  // ---- example data: plugins, the event catalogue and plugin runs (Sprints 24c, 25d) ----
  const CAPABILITIES = [
    { name: 'read:events', risk: 'low', description: 'Receive the events the manifest subscribes to' }, { name: 'read:records', risk: 'low', description: 'Read low-code app records (record.* events)' }, { name: 'read:files', risk: 'low', description: 'Read file-store metadata (file.* events)' }, { name: 'read:groups', risk: 'low', description: 'Read groups and events (group.* events)' }, { name: 'read:messages', risk: 'low', description: 'Receive message.* events' }, { name: 'read:posts', risk: 'low', description: 'Receive post.* events' },
    { name: 'emit:log', risk: 'low', description: 'Write to the plugin\'s own log' }, { name: 'emit:audit', risk: 'low', description: 'Write plugin.audited entries to the audit chain' }, { name: 'emit:notification', risk: 'low', description: 'Send in-app notifications' }, { name: 'emit:flag', risk: 'low', description: 'Raise a report flag for human review' },
    { name: 'call:webhook', risk: 'high', description: 'Deliver to an outbound webhook (allowed hosts apply)' }, { name: 'call:workflow', risk: 'high', description: 'Start a published workflow as the installer' }, { name: 'write:records', risk: 'high', description: 'Create and change app records' }, { name: 'write:posts', risk: 'high', description: 'Publish feed posts' }
  ];
  const RISK = {}; CAPABILITIES.forEach((c) => { RISK[c.name] = c.risk; });
  const PLUGINS0 = () => [
    { id: 'pl-1', key: 'flag-escalation-notifier', name: 'Flag escalation notifier', version: '1.4.2', kind: 'declarative', publisher: 'Northwind platform team', state: 'enabled', events: ['flag.escalated', 'flag.created'], capabilities: ['read:events', 'emit:notification', 'emit:audit'], optionalCapabilities: ['call:webhook'], granted: ['read:events', 'emit:notification', 'emit:audit'], maxLabel: 'confidential', configured: true, manifestHash: 'sha256:8d1f…c04a', installedBy: 'Jonas Lindqvist', stateChangedAt: '02 Sep 2026', createdAt: '14 Jun 2026', source: 'inline', description: 'Tells the workspace guardrail admins when a high-severity flag is escalated, and audits each notice.',
      actions: [{ type: 'notify', on: 'flag.escalated', with: { title: 'Flag {{event.data.ref}} escalated', roles: ['guardrail-admin'] } }, { type: 'audit', on: 'flag.escalated', with: { message: 'escalation noticed' } }, { type: 'webhook', on: 'flag.created', with: { url: '{{config.webhookUrl}}' } }], config: { schema: { webhookUrl: 'string (uri)' } },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '1.3.0', actor: 'Jonas Lindqvist', reason: 'initial install', at: '14 Jun 2026 10:02' }, { event: 'enable', from: 'installed', to: 'enabled', version: '1.3.0', actor: 'Jonas Lindqvist', reason: '', at: '14 Jun 2026 10:05' }, { event: 'grants', from: 'enabled', to: 'enabled', version: '1.3.0', actor: 'Mara Okafor', reason: 'added emit:audit', at: '30 Jul 2026 15:41' }, { event: 'install', from: 'enabled', to: 'enabled', version: '1.4.2', actor: 'Jonas Lindqvist', reason: 'upgrade', at: '02 Sep 2026 09:12' }] },
    { id: 'pl-2', key: 'erp-record-sync', name: 'ERP record sync', version: '0.9.1', kind: 'script', publisher: 'Northwind finance platform', state: 'enabled', events: ['record.*'], capabilities: ['read:records', 'write:records', 'emit:log'], optionalCapabilities: ['call:workflow'], granted: ['read:records', 'write:records', 'emit:log', 'call:workflow'], maxLabel: 'confidential', configured: true, manifestHash: 'sha256:33ab…9e71', installedBy: 'Felix Brandt', stateChangedAt: '11 Sep 2026', createdAt: '28 Aug 2026', source: 'bundle', bundle: { id: 'b-2026-36', name: 'finance-plugins-2026-36', digest: 'sha256:5e0c…a8d1', signer: 'northwind-release', promotedAt: '27 Aug 2026' }, description: 'Mirrors invoice records into the ERP through the broker; starts the erp-reconcile workflow when a record is paid.',
      script: { entry: 'onRecord', language: 'javascript', bytes: 4812 }, config: { schema: { entity: 'string', workflow: 'string' } },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '0.9.0', actor: 'Felix Brandt', reason: 'from bundle finance-plugins-2026-36', at: '28 Aug 2026 11:20' }, { event: 'grants', from: 'installed', to: 'installed', version: '0.9.0', actor: 'Felix Brandt', reason: 'granted write:records and call:workflow (high risk)', at: '28 Aug 2026 11:24' }, { event: 'enable', from: 'installed', to: 'enabled', version: '0.9.0', actor: 'Felix Brandt', reason: '', at: '28 Aug 2026 11:25' }, { event: 'install', from: 'enabled', to: 'enabled', version: '0.9.1', actor: 'Felix Brandt', reason: 'bundle 2026-36 patch', at: '11 Sep 2026 08:30' }] },
    { id: 'pl-3', key: 'slack-bridge', name: 'Slack bridge', version: '2.1.0', kind: 'webhook', publisher: 'Contoso Tools', state: 'disabled', events: ['job.*', 'approval.requested'], capabilities: ['read:events', 'call:webhook'], optionalCapabilities: [], granted: ['read:events'], maxLabel: 'internal', configured: true, manifestHash: 'sha256:a7c2…1f30', installedBy: 'Mara Okafor', stateChangedAt: '15 Sep 2026', createdAt: '03 Jul 2026', source: 'inline', description: 'Posts job states and approval requests to a Slack channel over its webhook URL.',
      webhook: { url: 'https://hooks.slack.example/services/T0/B1/x' }, config: { schema: {} },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '2.1.0', actor: 'Mara Okafor', reason: '', at: '03 Jul 2026 16:10' }, { event: 'grants', from: 'installed', to: 'installed', version: '2.1.0', actor: 'Mara Okafor', reason: 'granted call:webhook', at: '03 Jul 2026 16:11' }, { event: 'enable', from: 'installed', to: 'enabled', version: '2.1.0', actor: 'Mara Okafor', reason: '', at: '03 Jul 2026 16:12' }, { event: 'grants', from: 'enabled', to: 'disabled', version: '2.1.0', actor: 'Jonas Lindqvist', reason: 'call:webhook withdrawn: hooks.slack.example left the allowed hosts', at: '15 Sep 2026 09:40' }] },
    { id: 'pl-4', key: 'file-upload-flagger', name: 'File upload flagger', version: '1.0.0', kind: 'declarative', publisher: 'Northwind platform team', state: 'installed', events: ['file.uploaded', 'file.updated'], capabilities: ['read:files', 'emit:flag', 'emit:log'], optionalCapabilities: [], granted: ['read:files', 'emit:log'], maxLabel: 'internal', configured: false, manifestHash: 'sha256:0b9e…77d2', installedBy: 'Lena Hoffmann', stateChangedAt: '18 Sep 2026', createdAt: '18 Sep 2026', source: 'inline', description: 'Raises a flag for human review when a spreadsheet lands in a shared folder.',
      actions: [{ type: 'flag', on: 'file.uploaded', with: { reason: 'spreadsheet in shared folder', severity: 'low' } }, { type: 'log', on: 'file.updated', with: { message: 'new version of {{event.data.id}}' } }], config: { schema: {} },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '1.0.0', actor: 'Lena Hoffmann', reason: '', at: '18 Sep 2026 14:50' }] },
    { id: 'pl-5', key: 'weekly-digest-poster', name: 'Weekly digest poster', version: '0.3.0', kind: 'script', publisher: 'Northwind people ops', state: 'installed', events: ['post.*'], capabilities: ['read:posts', 'write:posts'], optionalCapabilities: [], granted: ['read:posts'], maxLabel: 'internal', configured: true, manifestHash: 'sha256:c41d…02be', installedBy: 'Noor Rahimi', stateChangedAt: '16 Sep 2026', createdAt: '16 Sep 2026', source: 'inline', description: 'Posts the feed digest to the workspace feed. Pasted inline, so it cannot be enabled while PLUGINS_REQUIRE_SIGNED is scripts.',
      script: { entry: 'onDigest', language: 'python', bytes: 2210 }, config: { schema: { workspace: 'string' } },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '0.3.0', actor: 'Noor Rahimi', reason: '', at: '16 Sep 2026 12:02' }] },
    { id: 'pl-6', key: 'legacy-audit-mirror', name: 'Legacy audit mirror', version: '1.2.0', kind: 'webhook', publisher: 'Northwind platform team', state: 'removed', events: ['*'], capabilities: ['read:events', 'call:webhook'], optionalCapabilities: [], granted: [], maxLabel: 'internal', configured: false, manifestHash: 'sha256:e2f0…6a19', installedBy: 'Jonas Lindqvist', stateChangedAt: '20 Aug 2026', createdAt: '02 Feb 2026', source: 'inline', description: 'Mirrored audit actions to the old SIEM relay. Replaced by the SIEM export.', webhook: { url: 'https://siem-relay.northwind.local/ingest' }, config: { schema: {} },
      transitions: [{ event: 'install', from: null, to: 'installed', version: '1.2.0', actor: 'Jonas Lindqvist', reason: '', at: '02 Feb 2026 09:00' }, { event: 'enable', from: 'installed', to: 'enabled', version: '1.2.0', actor: 'Jonas Lindqvist', reason: '', at: '02 Feb 2026 09:01' }, { event: 'remove', from: 'enabled', to: 'removed', version: '1.2.0', actor: 'Jonas Lindqvist', reason: 'SIEM export replaces it', at: '20 Aug 2026 17:30' }] }
  ];
  const AVAILABLE0 = () => [
    { bundle: { id: 'b-2026-36', name: 'finance-plugins-2026-36', digest: 'sha256:5e0c…a8d1', signer: 'northwind-release', promotedAt: '27 Aug 2026' }, path: 'plugins/erp-record-sync.json', sha256: 'sha256:33ab…9e71', manifest: { key: 'erp-record-sync', name: 'ERP record sync', version: '0.9.1', kind: 'script', capabilities: ['read:records', 'write:records', 'emit:log'] }, problem: null, installed: true },
    { bundle: { id: 'b-2026-36', name: 'finance-plugins-2026-36', digest: 'sha256:5e0c…a8d1', signer: 'northwind-release', promotedAt: '27 Aug 2026' }, path: 'plugins/ledger-close-checker.json', sha256: 'sha256:9a01…4ce3', manifest: { key: 'ledger-close-checker', name: 'Ledger close checker', version: '1.0.0', kind: 'script', capabilities: ['read:records', 'emit:flag', 'emit:notification'] }, problem: null },
    { bundle: { id: 'b-2026-38', name: 'platform-plugins-2026-38', digest: 'sha256:7d44…0b2f', signer: 'northwind-release', promotedAt: '17 Sep 2026' }, path: 'plugins/digest-poster.json', sha256: 'sha256:c41d…02be', manifest: { key: 'weekly-digest-poster', name: 'Weekly digest poster', version: '0.3.1', kind: 'script', capabilities: ['read:posts', 'write:posts'] }, problem: null },
    { bundle: { id: 'b-2026-38', name: 'platform-plugins-2026-38', digest: 'sha256:7d44…0b2f', signer: 'northwind-release', promotedAt: '17 Sep 2026' }, path: 'plugins/broken.json', sha256: 'sha256:1111…ffff', manifest: null, problem: 'manifest: capabilities[1] "call:shell" is not in the vocabulary' }
  ];
  const CATALOGUE = { version: 4, envelope: '{id, type, tenant, label, createdAt, data}', groups: [
    { pattern: 'job.*', description: 'Job lifecycle: queued, started, progress, succeeded, failed, cancelled' }, { pattern: 'flag.*', description: 'Guard flags: created, confirmed, dismissed, escalated, reopened' }, { pattern: 'approval.*', description: 'Approvals waiting on a person' }, { pattern: 'plugin.*', description: 'Plugin lifecycle and refusals' }, { pattern: 'record.*', description: 'Low-code app records' }, { pattern: 'file.*', description: 'File store' }, { pattern: 'group.*', description: 'Groups and events' }, { pattern: 'message.*', description: 'Messaging (ids only)' }, { pattern: 'post.*', description: 'Workspace feed' }, { pattern: 'channel.*', description: 'Customer-service channels (ids only)' }, { pattern: 'atproto.*', description: 'AT-Protocol identities, labels and firehose' }, { pattern: 'audit', description: 'Every other audit action, data is the audit entry' }
  ], types: [
    { type: 'job.succeeded', group: 'job.*', version: 1, since: '1.1.0', status: 'emitted', description: 'A job finished', schema: { jobId: 'string', kind: 'string', durationMs: 'integer', result: 'object' } }, { type: 'job.failed', group: 'job.*', version: 1, since: '1.1.0', status: 'emitted', description: 'A job failed its last attempt', schema: { jobId: 'string', kind: 'string', error: 'string', attempts: 'integer' } },
    { type: 'flag.created', group: 'flag.*', version: 2, since: '1.1.0', status: 'emitted', description: 'A guard flag was raised', schema: { id: 'string', ref: 'string (F-12)', severity: 'low | medium | high', checkpoint: 'string', workspaceId: 'string', dueAt: 'date-time' } }, { type: 'flag.confirmed', group: 'flag.*', version: 2, since: '1.1.0', status: 'emitted', description: 'A reviewer confirmed a flag (also delivered as its audit action; told apart by data.hash)', schema: { id: 'string', ref: 'string', by: 'string' } }, { type: 'flag.escalated', group: 'flag.*', version: 1, since: '1.1.0', status: 'emitted', description: 'A flag passed its timer or was escalated by hand', schema: { id: 'string', ref: 'string', to: 'workspace | tenant | platform', slaMinutes: 'integer' } }, { type: 'flag.reopened', group: 'flag.*', version: 1, since: '1.4.0', status: 'emitted', description: 'An upheld appeal reopened a flag with a fresh timer', schema: { id: 'string', ref: 'string', appealRef: 'string' } },
    { type: 'approval.requested', group: 'approval.*', version: 1, since: '1.1.0', status: 'emitted', description: 'A workflow or agent step waits for a person', schema: { runId: 'string', step: 'string', approvers: 'string[]' } },
    { type: 'plugin.changed', group: 'plugin.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A plugin changed state or grants', schema: { pluginId: 'string', key: 'string', from: 'string', to: 'string' } },
    { type: 'record.created', group: 'record.*', version: 1, since: '1.4.0', status: 'emitted', description: 'An app record was created', schema: { app: 'string', entity: 'string', id: 'string', state: 'string', label: 'string' } }, { type: 'record.updated', group: 'record.*', version: 1, since: '1.4.0', status: 'emitted', description: 'Fields of a record changed', schema: { app: 'string', entity: 'string', id: 'string', fields: 'string[]' } }, { type: 'record.transitioned', group: 'record.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A record moved along its state machine', schema: { id: 'string', from: 'string', to: 'string' } },
    { type: 'file.uploaded', group: 'file.*', version: 1, since: '1.4.0', status: 'emitted', description: 'Version 1 of a file passed quarantine', schema: { id: 'string', workspaceId: 'string', folderId: 'string', type: 'string', size: 'integer', label: 'string' } }, { type: 'file.shared', group: 'file.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A file was shared', schema: { id: 'string', with: 'user | group | workspace | link' } },
    { type: 'group.event.cancelled', group: 'group.*', version: 1, since: '1.4.0', status: 'emitted', description: 'An event was cancelled; attendees notified', schema: { groupId: 'string', eventId: 'string', notified: 'integer' } },
    { type: 'message.sent', group: 'message.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A message was sent (ids only, never text)', schema: { conversationId: 'string', messageId: 'string', authorId: 'string' } },
    { type: 'post.created', group: 'post.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A feed post was published', schema: { id: 'string', workspaceId: 'string', groupId: 'string | null', authorId: 'string', label: 'string' } }, { type: 'post.held', group: 'post.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A post waits for review', schema: { id: 'string', flagRef: 'string' } },
    { type: 'channel.reply.held', group: 'channel.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A channel reply waits for a reviewer', schema: { channelId: 'string', sessionId: 'string', messageId: 'string' } },
    { type: 'atproto.firehose.started', group: 'atproto.*', version: 1, since: '1.4.0', status: 'emitted', description: 'A firehose subscription was started', schema: { id: 'string', protocol: 'jetstream | subscribe-repos' } },
    { type: 'group.member.banned', group: 'group.*', version: 1, since: '1.5.0', status: 'reserved', description: 'Reserved until group bans ship', schema: {} }, { type: 'post.repinned', group: 'post.*', version: 1, since: '1.5.0', status: 'reserved', description: 'Reserved', schema: {} }
  ] };
  const INVOCATIONS0 = () => [
    { id: 'inv-9021', plugin: 'erp-record-sync', event: 'record.transitioned', eventId: 'ev-77a1', label: 'confidential', state: 'succeeded', attempts: 1, chain: ['erp-record-sync'], outcome: { calls: [{ api: 'records.read', status: 200 }, { api: 'workflow', status: 202 }, { api: 'log', status: 200 }], exitCode: 0, timedOut: false, durationMs: 1840, returned: '{"synced":true}' }, createdAt: '19 Sep 14:02', startedAt: '19 Sep 14:02', finishedAt: '19 Sep 14:02', logs: [{ level: 'info', message: 'record INV-2291 moved approved → paid', at: '14:02:11' }, { level: 'info', message: 'started workflow erp-reconcile v4 as run r-8812', at: '14:02:12' }] },
    { id: 'inv-9020', plugin: 'flag-escalation-notifier', event: 'flag.escalated', eventId: 'ev-77a0', label: 'confidential', state: 'succeeded', attempts: 1, chain: ['flag-escalation-notifier'], outcome: { actions: [{ type: 'notify', ok: true }, { type: 'audit', ok: true }] }, createdAt: '19 Sep 13:55', startedAt: '19 Sep 13:55', finishedAt: '19 Sep 13:55', logs: [{ level: 'info', message: 'notified 2 guardrail admins about F-2279', at: '13:55:02' }] },
    { id: 'inv-9018', plugin: 'flag-escalation-notifier', event: 'flag.created', eventId: 'ev-779c', label: 'internal', state: 'failed', attempts: 3, chain: ['flag-escalation-notifier'], outcome: { actions: [{ type: 'webhook', ok: false, status: 422, error: 'host hooks.contoso.example is not in the tenant\'s allowed hosts' }] }, createdAt: '19 Sep 13:26', startedAt: '19 Sep 13:26', finishedAt: '19 Sep 13:31', logs: [{ level: 'error', message: 'webhook refused: outbound host check failed (422)', at: '13:26:40' }, { level: 'error', message: 'attempt 2 refused', at: '13:28:40' }, { level: 'error', message: 'attempt 3 refused; giving up', at: '13:31:40' }] },
    { id: 'inv-9015', plugin: 'erp-record-sync', event: 'record.updated', eventId: 'ev-7791', label: 'confidential', state: 'failed', attempts: 1, chain: ['erp-record-sync'], outcome: { calls: [{ api: 'records.read', status: 200 }, { api: 'records.write', status: 403 }], exitCode: 1, timedOut: false, durationMs: 620, returned: null }, createdAt: '19 Sep 12:48', startedAt: '19 Sep 12:48', finishedAt: '19 Sep 12:48', logs: [{ level: 'error', message: 'records.write refused: label restricted is above the plugin\'s maxLabel confidential (403)', at: '12:48:09' }] },
    { id: 'inv-9009', plugin: 'erp-record-sync', event: 'record.updated', eventId: 'ev-7780', label: 'confidential', state: 'cancelled', attempts: 1, chain: ['erp-record-sync', 'erp-record-sync'], outcome: null, error: 'dropped: loop (the event was caused by this plugin\'s own write)', createdAt: '19 Sep 12:48', startedAt: null, finishedAt: '19 Sep 12:48', logs: [] },
    { id: 'inv-9002', plugin: 'erp-record-sync', event: 'record.created', eventId: 'ev-7772', label: 'confidential', state: 'running', attempts: 1, chain: ['erp-record-sync'], outcome: null, createdAt: '19 Sep 14:05', startedAt: '19 Sep 14:05', finishedAt: null, logs: [{ level: 'info', message: 'handler onRecord started in sandbox c-4f1a (podman, no network)', at: '14:05:01' }] },
    { id: 'inv-8998', plugin: 'flag-escalation-notifier', event: 'flag.escalated', eventId: 'ev-7760', label: 'confidential', state: 'queued', attempts: 0, chain: ['flag-escalation-notifier'], outcome: null, createdAt: '19 Sep 14:06', startedAt: null, finishedAt: null, logs: [] }
  ];
  const DROPPED = { rate: 12, loop: 3, depth: 0, throttledPlugin: 'erp-record-sync' };
  const WEBHOOKS = ['wh-12 siem-export (siem.northwind.local)', 'wh-15 finance-ops-bot (bots.northwind.local)', 'wh-21 plugin:flag-escalation-notifier:8d1f'];
  const stateKind = (s) => s === 'enabled' ? 'ok' : s === 'disabled' ? 'warn' : s === 'removed' ? 'danger' : s === 'installed' ? 'info' : '';
  const invKind = (s) => s === 'succeeded' ? 'ok' : s === 'failed' ? 'danger' : s === 'cancelled' ? 'warn' : 'info';
  const missing = (p) => p.capabilities.filter((c) => !p.granted.includes(c));

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
  const init = (st) => {
    if (st.plugins) return;
    st.plugins = PLUGINS0(); st.available = AVAILABLE0(); st.invocations = INVOCATIONS0();
    st.tab = 'plugins'; st.sel = 'pl-1'; st.query = ''; st.stateFilter = 'all'; st.kindFilter = 'all'; st.showRemoved = false; st.catQuery = ''; st.catGroup = 'all'; st.selType = 'flag.escalated'; st.invState = 'all'; st.invPlugin = 'all'; st.requireSigned = 'scripts'; st.problem = null;
  };
  const transitionNote = (p, ev, from, to, reason) => p.transitions.push({ event: ev, from, to, version: p.version, actor: 'Mara Okafor', reason: reason || '', at: 'just now' });

  App.register({
    id: 'plugins', title: 'Plugins and events', section: 'admin', crumb: ['Admin', 'Plugins and events'],
    summary: 'The event catalogue, plugin manifests, grants, lifecycle and runs',
    commands: [
      { label: 'Install a plugin', sub: 'Plugins and events', run(app) { const s = app.stateFor('plugins'); init(s); s.tab = 'install'; app.render(); } },
      { label: 'Replay events to a webhook', sub: 'Plugins and events', run(app) { const s = app.stateFor('plugins'); init(s); s.tab = 'catalogue'; s.openReplay = true; app.render(); } }
    ],
    states: [
      { title: 'Required capability missing', tone: 'danger', text: 'Enable answers 409 with missing when a required capability is not granted. File upload flagger asks for emit:flag, which nobody granted yet.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'plugins'; st.sel = 'pl-4'; st.problem = { kind: 'missing', plugin: 'pl-4', missing: ['emit:flag'] }; ctx.rerender(); } },
      { title: 'Grant revoked disables plugin', tone: 'warn', text: 'Replacing the grants of an enabled plugin without a required capability disables it at once (grants transition from enabled to disabled, audited plugin.grants.updated with before, after, added, removed, highRisk).', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'plugins'; st.sel = 'pl-1'; const p = st.plugins.find((x) => x.id === 'pl-1'); if (p.state === 'enabled') { p.granted = p.granted.filter((c) => c !== 'emit:notification'); p.state = 'disabled'; p.stateChangedAt = 'just now'; transitionNote(p, 'grants', 'enabled', 'disabled', 'emit:notification withdrawn; a required capability'); ctx.rerender(); ctx.toast('flag-escalation-notifier disabled: it lost the required capability emit:notification.', 'warn', 5000); } else ctx.rerender(); } },
      { title: 'Script plugin needs a signed bundle', tone: 'warn', text: 'With PLUGINS_REQUIRE_SIGNED=scripts (the default) a script plugin pasted inline can be installed but not enabled (409). The same manifest in a promoted import bundle passes.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'plugins'; st.sel = 'pl-5'; st.problem = { kind: 'unsigned', plugin: 'pl-5' }; ctx.rerender(); } },
      { title: 'Invocation failed and loop dropped', tone: 'danger', text: 'A record.updated caused by the plugin\'s own write carries the plugin in its chain and is never delivered to it (exprsn_plugin_dropped_total reason loop). The write refused for a restricted record failed its invocation.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'runs'; st.invState = 'all'; st.invPlugin = 'erp-record-sync'; st.selInv = 'inv-9009'; ctx.rerender(); } },
      { title: 'Webhook host refused', tone: 'danger', text: 'A webhook action to a host outside the tenant\'s allowed hosts is 422 at install, at enable and at every attempt. Three attempts failed, the delivery is counted and the breaker is open.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'runs'; st.invState = 'failed'; st.invPlugin = 'all'; st.selInv = 'inv-9018'; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state; init(st);
      if (ctx.params.id) { const p = st.plugins.find((x) => x.id === ctx.params.id || x.key === ctx.params.id); if (p) { st.tab = 'plugins'; st.sel = p.id; } delete ctx.params.id; }
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }
      const enabled = st.plugins.filter((p) => p.state === 'enabled').length;
      const tabs = UI.tabs([{ id: 'plugins', label: 'Plugins', count: st.plugins.filter((p) => p.state !== 'removed').length }, { id: 'install', label: 'Install' }, { id: 'catalogue', label: 'Event catalogue', count: CATALOGUE.types.length }, { id: 'runs', label: 'Runs', count: st.invocations.filter((i) => i.state === 'running' || i.state === 'queued').length }], st.tab);
      let body = '', insp = '';

      // ---------------- Plugins ----------------
      if (st.tab === 'plugins') {
        const q = st.query.toLowerCase();
        const rows = st.plugins.filter((p) => (st.showRemoved || p.state !== 'removed') && (st.stateFilter === 'all' || p.state === st.stateFilter) && (st.kindFilter === 'all' || p.kind === st.kindFilter) && (!q || (p.key + ' ' + p.name + ' ' + p.publisher + ' ' + p.description).toLowerCase().includes(q)));
        if (!rows.some((p) => p.id === st.sel)) st.sel = rows.length ? rows[0].id : null;
        const sel = st.plugins.find((p) => p.id === st.sel);
        body += (st.problem && st.problem.kind === 'missing' ? UI.problem('Cannot enable: required capability not granted', 'POST /admin/plugins/' + (st.plugins.find((p) => p.id === st.problem.plugin) || {}).key + '/enable answered 409 with missing: ' + st.problem.missing.join(', ') + '. Grant it in the inspector (it is low risk) and enable again.', '3e9f2a1b7c8d4e5f9a0b1c2d3e4f5a6b') + '<div>' + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearproblem' }) + '</div>' : '')
          + (st.problem && st.problem.kind === 'unsigned' ? UI.problem('Cannot enable: script plugins must come from a signed bundle', 'PLUGINS_REQUIRE_SIGNED is ' + st.requireSigned + ': weekly-digest-poster was pasted inline, so enable is 409. Install it from the promoted bundle platform-plugins-2026-38 (Install tab) instead; the bundle has version 0.3.1 of it.', '5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d') + '<div>' + UI.btn('Open the bundle', { size: 'sm', attrs: 'data-gobundle' }) + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearproblem' }) + '</div>' : '')
          + '<div class="toolbar">' + UI.search('Filter by key, name, publisher', 'data-search', st.query)
          + '<span class="relative">' + UI.btn(st.stateFilter === 'all' ? 'State' : 'State: ' + st.stateFilter, { size: 'sm', icon: 'filter', attrs: 'data-menu="state"', cls: st.stateFilter !== 'all' ? 'active' : '' }) + '</span>'
          + '<span class="relative">' + UI.btn(st.kindFilter === 'all' ? 'Kind' : 'Kind: ' + st.kindFilter, { size: 'sm', icon: 'filter', attrs: 'data-menu="kind"', cls: st.kindFilter !== 'all' ? 'active' : '' }) + '</span>'
          + UI.check('Show removed', st.showRemoved, 'data-showremoved') + '<span class="muted right" style="font-size:12px">' + rows.length + ' shown, ' + enabled + ' enabled</span></div>'
          + UI.table(['Plugin', 'Version', 'Kind', 'Publisher', 'State', 'Capabilities', 'Max label', 'Source', 'Changed'], rows.map((p) => { const miss = missing(p); return { cells: ['<div style="font-weight:600">' + esc(p.name) + '</div><div class="mono muted" style="font-size:11px">' + esc(p.key) + '</div>', '<span class="mono">' + esc(p.version) + '</span>', esc(p.kind), esc(p.publisher), UI.pill(p.state, stateKind(p.state)), p.granted.map((c) => UI.pill(c, RISK[c] === 'high' ? 'accent' : 'outline')).join(' ') + (miss.length ? ' ' + miss.map((c) => UI.pill('missing ' + c, 'warn')).join(' ') : ''), UI.label(p.maxLabel, { sm: true }), p.source === 'bundle' ? '<span title="' + esc(p.bundle.name) + '">bundle</span>' : 'inline', esc(p.stateChangedAt)], attrs: 'data-plugin="' + p.id + '"', selected: p.id === st.sel }; }), { minWidth: '1000px', emptyTitle: 'No plugins match', emptyText: 'Clear the filters, or install one from the Install tab.' })
          + '<span class="muted" style="font-size:12px">A plugin is data: a manifest and the capabilities granted to it. Nothing in a manifest is loaded into the server; declarative actions and script handlers run from events as jobs, scripts in the sandbox. Plugins above your clearance are left out.</span>';
        if (sel) {
          const miss = missing(sel);
          insp = '<div class="hstack"><div class="eyebrow grow">Selected plugin</div>' + UI.pill(sel.state, stateKind(sel.state)) + '</div><div style="font-size:15px;font-weight:600">' + esc(sel.name) + '</div><div class="mono muted" style="font-size:11px">' + esc(sel.key) + ' ' + esc(sel.version) + ', ' + esc(sel.manifestHash) + '</div><div class="fg2" style="font-size:12px">' + esc(sel.description) + '</div>'
            + UI.kv([['Kind', esc(sel.kind) + (sel.script ? ', ' + esc(sel.script.language) + ' entry ' + esc(sel.script.entry) + ' (' + sel.script.bytes + ' bytes)' : sel.webhook ? ', ' + esc(sel.webhook.url.replace(/^https?:\/\//, '').split('/')[0]) : '')], ['Publisher', esc(sel.publisher)], ['Events', sel.events.map((e) => '<span class="mono">' + esc(e) + '</span>').join(', ')], ['Max label', UI.label(sel.maxLabel, { sm: true })], ['Source', sel.source === 'bundle' ? 'bundle <span class="mono">' + esc(sel.bundle.name) + '</span>, signer ' + esc(sel.bundle.signer) : 'inline manifest'], ['Installed', esc(sel.createdAt) + ' by ' + esc(sel.installedBy)], ['Config', sel.configured ? 'sealed, ' + Object.keys(sel.config.schema).length + ' fields' : Object.keys(sel.config.schema).length ? '<span style="color:var(--warn-fg)">not configured</span>' : 'none']], 1)
            + (miss.length && sel.state !== 'removed' ? UI.notice('<b>Required and not granted:</b> ' + miss.map((c) => '<span class="mono">' + esc(c) + '</span>').join(', ') + '. Enable is refused (409) until granted.', 'warn') : '')
            + (sel.kind === 'script' && sel.source !== 'bundle' && sel.state !== 'removed' ? UI.notice('Script plugins need a signed bundle while PLUGINS_REQUIRE_SIGNED is <span class="mono">' + esc(st.requireSigned) + '</span>; this one was pasted inline.', 'warn') : '')
            + '<div class="hstack"><div class="eyebrow grow">Grants</div><span class="muted" style="font-size:11px">high risk marked</span></div><div class="vstack gap4" data-grants>' + sel.capabilities.concat(sel.optionalCapabilities).map((c) => '<div class="hstack">' + UI.check(c + (sel.optionalCapabilities.includes(c) ? ' (optional)' : ''), sel.granted.includes(c), 'data-grant="' + c + '"' + (sel.state === 'removed' ? ' disabled' : '')) + (RISK[c] === 'high' ? UI.pill('high risk', 'danger') : '') + '</div>').join('') + '</div>'
            + '<div class="hstack gap6">' + UI.btn('Save grants', { size: 'sm', attrs: 'data-savegrants', disabled: sel.state === 'removed' }) + '<span class="muted" style="font-size:11px">An enabled plugin that loses a required grant is disabled.</span></div>'
            + (sel.actions ? '<div class="eyebrow">Actions</div>' + UI.table(['On', 'Action', 'Capability'], sel.actions.map((a) => ['<span class="mono">' + esc(a.on) + '</span>', esc(a.type) + ' <span class="muted" style="font-size:11px">' + esc(JSON.stringify(a.with)).slice(0, 48) + '</span>', '<span class="mono">' + esc({ log: 'emit:log', audit: 'emit:audit', notify: 'emit:notification', flag: 'emit:flag', webhook: 'call:webhook', workflow: 'call:workflow' }[a.type]) + '</span>' + (sel.granted.includes({ log: 'emit:log', audit: 'emit:audit', notify: 'emit:notification', flag: 'emit:flag', webhook: 'call:webhook', workflow: 'call:workflow' }[a.type]) ? '' : ' ' + UI.pill('refused when run', 'warn'))]), { clickable: false, minWidth: '0', cls: 'bare' }) : '')
            + '<div class="hstack wrap gap6">' + (sel.state === 'installed' || sel.state === 'disabled' ? UI.btn('Enable', { kind: 'primary', size: 'sm', icon: 'play', attrs: 'data-enable' }) : '') + (sel.state === 'enabled' ? UI.btn('Disable', { size: 'sm', icon: 'pause', attrs: 'data-disable' }) : '') + (sel.state !== 'removed' ? UI.btn('Configure', { size: 'sm', attrs: 'data-configure', disabled: !Object.keys(sel.config.schema).length }) + UI.btn('Runs', { size: 'sm', attrs: 'data-runsfor="' + esc(sel.key) + '"' }) + UI.btn('Remove', { kind: 'danger', size: 'sm', attrs: 'data-remove' }) : UI.btn('Reinstall', { kind: 'primary', size: 'sm', attrs: 'data-reinstall' })) + '</div>'
            + '<div class="eyebrow">Transitions</div>' + UI.timeline(sel.transitions.slice().reverse().map((t) => ({ title: esc(t.event) + (t.from ? ' <span class="muted">' + esc(t.from) + ' → ' + esc(t.to) + '</span>' : ' <span class="muted">→ ' + esc(t.to) + '</span>'), text: esc(t.actor) + (t.reason ? ', ' + esc(t.reason) : '') + ', v' + esc(t.version), meta: esc(t.at), tone: t.to === 'enabled' ? 'ok' : t.to === 'removed' ? 'danger' : t.to === 'disabled' ? 'warn' : '' })))
            + '<span class="muted" style="font-size:12px"><a href="#" data-goaudit>Audit entries</a>: plugin.installed, .enabled, .disabled, .removed, .grants.updated.</span>';
        }
      }
      // ---------------- Install ----------------
      if (st.tab === 'install') {
        body += '<div class="grid2">' + UI.panel('Install from a manifest', '<p class="fg2" style="margin:0;font-size:13px">Paste a manifest. Validate reports every problem (422) or the summary; install grants the low-risk capabilities it asks for, high-risk ones only when you name them.</p>' + UI.textarea(st.manifestText || '{\n  "key": "ledger-close-checker",\n  "name": "Ledger close checker",\n  "version": "1.0.0",\n  "kind": "declarative",\n  "events": ["record.transitioned"],\n  "capabilities": ["read:records", "emit:flag", "emit:notification"],\n  "actions": [{ "type": "flag", "on": "record.transitioned", "with": { "severity": "medium", "reason": "ledger closed with open items" } }]\n}', { rows: 9, attrs: 'data-manifest' }) + '<div class="hstack wrap gap6">' + UI.btn('Validate', { size: 'sm', attrs: 'data-validate' }) + UI.btn('Install', { kind: 'primary', size: 'sm', attrs: 'data-install' }) + '</div>' + (st.validation ? (st.validation.valid ? UI.notice('<b>Valid.</b> ' + esc(st.validation.summary), 'ok') : UI.problem('Manifest refused (422)', st.validation.errors.join(' '), '9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f')) : '') + '<span class="muted" style="font-size:12px">PLUGINS_REQUIRE_SIGNED is <span class="mono">' + esc(st.requireSigned) + '</span>: script plugins are installed only from bundles' + (st.requireSigned === 'all' ? ', and so is everything else' : '') + '.</span>')
          + UI.panel('Capability vocabulary', UI.table(['Capability', 'Risk', 'What it allows'], CAPABILITIES.map((c) => ['<span class="mono">' + esc(c.name) + '</span>', UI.pill(c.risk, c.risk === 'high' ? 'danger' : 'ok'), esc(c.description)]), { clickable: false, minWidth: '0', cls: 'bare' }) + '<span class="muted" style="font-size:12px">A closed vocabulary; a manifest naming anything else is refused. Brokered calls (records.read, files.read, groups.read, posts.write…) map to the same capabilities.</span>') + '</div>'
          + UI.panel('Available in promoted import bundles', UI.table(['Bundle', 'Signer', 'Promoted', 'File', 'Plugin', 'Capabilities', { label: '', right: true }], st.available.map((a, i) => [esc(a.bundle.name) + ' <span class="mono muted" style="font-size:11px">' + esc(a.bundle.digest) + '</span>', esc(a.bundle.signer), esc(a.bundle.promotedAt), '<span class="mono" style="font-size:12px">' + esc(a.path) + '</span>', a.manifest ? esc(a.manifest.name) + ' <span class="mono muted" style="font-size:11px">' + esc(a.manifest.version) + ', ' + esc(a.manifest.kind) + '</span>' : UI.pill('refused', 'danger') + ' <span class="muted" style="font-size:12px">' + esc(a.problem) + '</span>', a.manifest ? a.manifest.capabilities.map((c) => UI.pill(c, RISK[c] === 'high' ? 'accent' : 'outline')).join(' ') : '', a.manifest ? (a.installed || st.plugins.some((p) => p.key === a.manifest.key && p.state !== 'removed' && p.version === a.manifest.version) ? UI.pill('installed', 'ok') : UI.btn(st.plugins.some((p) => p.key === a.manifest.key && p.state !== 'removed') ? 'Upgrade' : 'Install', { kind: 'primary', size: 'xs', attrs: 'data-import="' + i + '"' })) : '']), { clickable: false, minWidth: '900px' }) + '<span class="muted" style="font-size:12px">Each import reads the file again from the stored transfer and checks the transfer\'s digest, the signature against the signer keys registered now (a key revoked since fails it) and the file\'s sha256 against the signed manifest. A bundle not promoted or failing these checks is 409 Bundle refused. <a href="#" data-goplatform>Bundles are managed in Platform</a>.</span>', { attrs: 'data-bundles' })
          + (st.bundleRefused ? UI.problem('Bundle refused (409)', st.bundleRefused, '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d') + '<div>' + UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clearrefused' }) + '</div>' : '');
      }
      // ---------------- Catalogue ----------------
      if (st.tab === 'catalogue') {
        const q = st.catQuery.toLowerCase();
        const types = CATALOGUE.types.filter((t) => (st.catGroup === 'all' || t.group === st.catGroup) && (!q || (t.type + ' ' + t.description).toLowerCase().includes(q)));
        const selT = CATALOGUE.types.find((t) => t.type === st.selType);
        body += UI.panel('Catalogue version ' + CATALOGUE.version, '<div class="hstack wrap"><span class="fg2 grow" style="font-size:13px">Envelope of every delivery: <span class="mono">' + esc(CATALOGUE.envelope) + '</span>; <span class="mono">schema</span> is the JSON Schema of <span class="mono">data</span>. The version moves when a type is added or changes; a type\'s own version only when its data changes incompatibly. ETag and 304 on If-None-Match.</span>' + UI.btn('Replay events', { size: 'sm', icon: 'refresh', attrs: 'data-replay' }) + UI.btn('Webhooks', { kind: 'ghost', size: 'sm', attrs: 'data-gowebhooks' }) + '</div>'
          + '<div class="hstack wrap gap6">' + UI.chip('All groups', st.catGroup === 'all', 'data-group="all"') + CATALOGUE.groups.map((g) => UI.chip('<span class="mono">' + esc(g.pattern) + '</span>', st.catGroup === g.pattern, 'data-group="' + esc(g.pattern) + '" title="' + esc(g.description) + '"')).join('') + '</div>')
          + '<div class="plugins-cat"><div class="vstack gap12">' + '<div class="toolbar">' + UI.search('Filter types', 'data-catsearch', st.catQuery) + '<span class="muted right" style="font-size:12px">' + types.length + ' of ' + CATALOGUE.types.length + ' named types; every other audit action is delivered with the audit entry as data</span></div>'
          + UI.table(['Type', 'Group', 'Version', 'Since', 'Status', 'Description'], types.map((t) => ({ cells: ['<span class="mono">' + esc(t.type) + '</span>', '<span class="mono muted" style="font-size:12px">' + esc(t.group) + '</span>', '<span class="num">' + t.version + '</span>', esc(t.since), UI.pill(t.status, t.status === 'emitted' ? 'ok' : ''), esc(t.description)], attrs: 'data-type="' + esc(t.type) + '"', selected: t.type === st.selType })), { minWidth: '720px', emptyTitle: 'No types match' }) + '</div>'
          + (selT ? UI.panel('Schema of ' + selT.type, UI.kv([['Group', '<span class="mono">' + esc(selT.group) + '</span>'], ['Status', UI.pill(selT.status, selT.status === 'emitted' ? 'ok' : '')], ['Version', String(selT.version)], ['Since', esc(selT.since)]], 2) + UI.code(JSON.stringify({ type: 'object', properties: selT.schema, required: Object.keys(selT.schema) }, null, 2), 'json') + '<span class="muted" style="font-size:12px">A mismatch between an emitted event and this schema is still delivered, counted in exprsn_event_schema_violations_total{type} and logged. Subscribed by: ' + esc(st.plugins.filter((p) => p.state === 'enabled' && p.events.some((e) => e === selT.type || (e.endsWith('*') && selT.type.startsWith(e.slice(0, -1))) || e === '*')).map((p) => p.key).join(', ') || 'no enabled plugin') + '.</span>') : '') + '</div>';
      }
      // ---------------- Runs ----------------
      if (st.tab === 'runs') {
        const rows = st.invocations.filter((i) => (st.invState === 'all' || i.state === st.invState) && (st.invPlugin === 'all' || i.plugin === st.invPlugin));
        if (!rows.some((i) => i.id === st.selInv)) st.selInv = rows.length ? rows[0].id : null;
        const sel = st.invocations.find((i) => i.id === st.selInv);
        body += '<div class="stats">' + UI.stat(String(st.invocations.filter((i) => i.state === 'succeeded').length), 'succeeded today', 'exprsn_plugin_invocations_total{result="succeeded"}') + UI.stat('<span style="color:var(--danger-fg)">' + st.invocations.filter((i) => i.state === 'failed').length + '</span>', 'failed', 'last: ' + esc((st.invocations.find((i) => i.state === 'failed') || {}).plugin || '')) + UI.stat(String(DROPPED.rate), 'dropped: rate', esc(DROPPED.throttledPlugin) + ' over PLUGIN_RATE_PER_MINUTE; audited plugin.throttled once a window') + UI.stat(String(DROPPED.loop), 'dropped: loop', 'events caused by the plugin\'s own work') + UI.stat(String(DROPPED.depth), 'dropped: depth', 'chains at PLUGIN_MAX_DEPTH') + '</div>'
          + '<div class="toolbar"><span class="relative">' + UI.btn(st.invState === 'all' ? 'State' : 'State: ' + st.invState, { size: 'sm', icon: 'filter', attrs: 'data-menu="inv"', cls: st.invState !== 'all' ? 'active' : '' }) + '</span><span class="relative">' + UI.btn(st.invPlugin === 'all' ? 'Plugin' : 'Plugin: ' + st.invPlugin, { size: 'sm', icon: 'filter', attrs: 'data-menu="invplugin"', cls: st.invPlugin !== 'all' ? 'active' : '' }) + '</span><span class="muted right" style="font-size:12px">' + rows.length + ' of ' + st.invocations.length + ' invocations, newest first; PLUGIN_CONCURRENCY 2 per plugin across instances</span></div>'
          + UI.table(['Invocation', 'Plugin', 'Event', 'Label', 'State', 'Attempts', 'Chain', 'Outcome', 'Started', 'Finished'], rows.map((i) => ({ cells: ['<span class="mono">' + esc(i.id) + '</span>', '<a href="#" data-openplugin="' + esc(i.plugin) + '">' + esc(i.plugin) + '</a>', '<span class="mono">' + esc(i.event) + '</span> <span class="mono muted" style="font-size:11px">' + esc(i.eventId) + '</span>', UI.label(i.label, { sm: true }), UI.pill(i.state, invKind(i.state)), '<span class="num">' + i.attempts + '</span>', '<span class="num">' + i.chain.length + '</span>' + (i.chain.length > 1 ? ' ' + UI.pill('loop', 'warn') : ''), outcomeCell(i), esc(i.startedAt || ''), esc(i.finishedAt || '')], attrs: 'data-inv="' + i.id + '"', selected: i.id === st.selInv })), { minWidth: '1000px', emptyTitle: 'No invocations match' })
          + '<span class="muted" style="font-size:12px">An event reaches a plugin once. A declarative plugin runs its actions in order (an ungranted one is refused and audited plugin.action.refused; the others still run); a script handler runs in the sandbox and reaches the platform only through the broker with a scoped token (PLUGIN_MAX_CALLS calls, revoked when the handler ends). <a href="#" data-goaudit>Audit</a>.</span>';
        if (sel) insp = invocationPanel(sel);
      }

      root.innerHTML = '<style>'
        + '#main > .page > *{flex-shrink:0}'
        + '#main .plugins-cat{display:grid;gap:14px;grid-template-columns:minmax(0,3fr) minmax(0,2fr)}'
        + '@media (max-width:1100px){#main .plugins-cat{grid-template-columns:1fr}}'
        + '#main .plugins-insp .kv .v{font-size:12px}'
        + '</style>'
        + '<div class="page">' + UI.pagehead('Plugins and events', 'The event catalogue every webhook and plugin delivery follows, the tenant\'s plugins with their grants and lifecycle, and their runs.', UI.pill(enabled + ' enabled', 'ok') + UI.btn('Install plugin', { kind: 'primary', icon: 'plus', attrs: 'data-goinstall' }))
        + tabs + body
        + '</div>'
        + (insp ? '<aside class="inspector w360 plugins-insp" aria-label="Inspector">' + insp + '</aside>' : '');

      // ---- events ----
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-goinstall]', () => { st.tab = 'install'; ctx.rerender(); });
      ctx.on('click', '[data-gobundle]', () => { st.tab = 'install'; st.problem = null; ctx.rerender(); const el = ctx.$('[data-bundles]'); if (el) el.scrollIntoView({ block: 'start' }); });
      ctx.on('click', '[data-goplatform]', (e) => { e.preventDefault(); ctx.navigate('platform'); });
      ctx.on('click', '[data-goaudit]', (e) => { e.preventDefault(); ctx.navigate('usage-audit'); });
      ctx.on('click', '[data-gowebhooks]', () => ctx.navigate('tenants'));
      ctx.on('click', 'tr[data-plugin]', (e, t) => { st.sel = t.dataset.plugin; st.problem = null; ctx.rerender(); });
      ctx.on('click', 'tr[data-type]', (e, t) => { st.selType = t.dataset.type; ctx.rerender(); });
      ctx.on('click', 'tr[data-inv]', (e, t) => { if (e.target.closest('a')) return; st.selInv = t.dataset.inv; ctx.rerender(); });
      ctx.on('click', '[data-openplugin]', (e, t) => { e.preventDefault(); const p = st.plugins.find((x) => x.key === t.dataset.openplugin); if (p) { st.tab = 'plugins'; st.sel = p.id; st.stateFilter = 'all'; st.kindFilter = 'all'; st.query = ''; ctx.rerender(); } });
      ctx.on('click', '[data-runsfor]', (e, t) => { st.tab = 'runs'; st.invPlugin = t.dataset.runsfor; st.invState = 'all'; ctx.rerender(); });
      ctx.on('input', '[data-search]', (e, t) => { st.query = t.value; ctx.rerender(); const i = ctx.$('[data-search]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } });
      ctx.on('input', '[data-catsearch]', (e, t) => { st.catQuery = t.value; ctx.rerender(); const i = ctx.$('[data-catsearch]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } });
      ctx.on('change', '[data-showremoved]', (e, t) => { st.showRemoved = t.checked; ctx.rerender(); });
      ctx.on('click', '[data-group]', (e, t) => { st.catGroup = t.dataset.group; ctx.rerender(); });
      ctx.on('click', '[data-clearproblem]', () => { st.problem = null; ctx.rerender(); });
      ctx.on('click', '[data-clearrefused]', () => { st.bundleRefused = null; ctx.rerender(); });
      ctx.on('click', '[data-menu]', (e, t) => {
        const k = t.dataset.menu;
        if (k === 'state') menu(ctx, t, [['all', 'Every state'], ['installed', 'Installed'], ['enabled', 'Enabled'], ['disabled', 'Disabled'], ['removed', 'Removed']], st.stateFilter, (v) => { st.stateFilter = v; if (v === 'removed') st.showRemoved = true; ctx.rerender(); });
        if (k === 'kind') menu(ctx, t, [['all', 'Every kind'], ['declarative', 'Declarative'], ['webhook', 'Webhook'], ['script', 'Script']], st.kindFilter, (v) => { st.kindFilter = v; ctx.rerender(); });
        if (k === 'inv') menu(ctx, t, [['all', 'Every state'], ['queued', 'Queued'], ['running', 'Running'], ['succeeded', 'Succeeded'], ['failed', 'Failed'], ['cancelled', 'Cancelled']], st.invState, (v) => { st.invState = v; ctx.rerender(); });
        if (k === 'invplugin') menu(ctx, t, [['all', 'Every plugin']].concat(st.plugins.filter((p) => p.state !== 'removed').map((p) => [p.key, p.key])), st.invPlugin, (v) => { st.invPlugin = v; ctx.rerender(); });
      });

      // plugin lifecycle
      const sel = st.plugins.find((p) => p.id === st.sel);
      ctx.on('click', '[data-enable]', () => {
        const miss = missing(sel);
        if (miss.length) { st.problem = { kind: 'missing', plugin: sel.id, missing: miss }; ctx.rerender(); return; }
        if (sel.kind === 'script' && sel.source !== 'bundle' && st.requireSigned !== 'none') { st.problem = { kind: 'unsigned', plugin: sel.id }; ctx.rerender(); return; }
        if (sel.kind === 'webhook' && sel.webhook && /slack\.example/.test(sel.webhook.url) && sel.granted.includes('call:webhook')) { ctx.toast('422: hooks.slack.example is not in the tenant\'s allowed hosts. Add it in Tenants, then enable.', 'danger', 5000); return; }
        ctx.confirm({ title: 'Enable ' + esc(sel.name), tone: 'info', body: '<p class="fg2" style="margin:0">Events it subscribes to (' + esc(sel.events.join(', ')) + ') at or below ' + esc(sel.maxLabel) + ' reach it as jobs from now on, with the grants it holds.</p>' + UI.field('Reason (optional)', UI.input('', { attrs: 'data-reason' })), ok: 'Enable' }).then((ok) => { if (!ok) return; transitionNote(sel, 'enable', sel.state, 'enabled'); sel.state = 'enabled'; sel.stateChangedAt = 'just now'; st.problem = null; ctx.rerender(); ctx.toast(esc(sel.key) + ' enabled. Audited plugin.enabled; plugin.changed published on the bus.', 'ok'); });
      });
      ctx.on('click', '[data-disable]', () => ctx.confirm({ title: 'Disable ' + esc(sel.name), tone: 'warn', tag: 'stops deliveries', body: '<p class="fg2" style="margin:0">Running invocations finish; nothing new is delivered. Grants and config are kept.</p>' + UI.field('Reason (optional)', UI.input('', { attrs: 'data-reason' })), ok: 'Disable' }).then((ok) => { if (!ok) return; transitionNote(sel, 'disable', 'enabled', 'disabled'); sel.state = 'disabled'; sel.stateChangedAt = 'just now'; ctx.rerender(); ctx.toast(esc(sel.key) + ' disabled. Audited plugin.disabled.', 'warn'); }));
      ctx.on('click', '[data-remove]', () => ctx.confirm({ title: 'Remove ' + esc(sel.name), tone: 'danger', tag: 'removed', body: '<p class="fg2" style="margin:0">The plugin becomes removed (204): its webhooks named plugin:' + esc(sel.key) + ':… are removed, its config stays sealed until reinstall. Reinstalling keeps the id with a new manifest.</p>' + UI.field('Reason', UI.input('', { attrs: 'data-reason' })), ok: 'Remove' }).then((ok) => { if (!ok) return; transitionNote(sel, 'remove', sel.state, 'removed'); sel.state = 'removed'; sel.granted = []; sel.stateChangedAt = 'just now'; st.showRemoved = true; ctx.rerender(); ctx.toast(esc(sel.key) + ' removed. Audited plugin.removed.', 'danger'); }));
      ctx.on('click', '[data-reinstall]', () => { transitionNote(sel, 'install', 'removed', 'installed', 'reinstall'); sel.state = 'installed'; sel.granted = sel.capabilities.filter((c) => RISK[c] === 'low'); sel.stateChangedAt = 'just now'; ctx.rerender(); ctx.toast(esc(sel.key) + ' reinstalled with the same id; low-risk grants restored. Audited plugin.reinstalled.', 'ok'); });
      ctx.on('click', '[data-savegrants]', () => {
        const next = ctx.$$('[data-grant]').filter((c) => c.checked).map((c) => c.dataset.grant);
        const added = next.filter((c) => !sel.granted.includes(c)), removed = sel.granted.filter((c) => !next.includes(c));
        if (!added.length && !removed.length) { ctx.toast('Grants unchanged.'); return; }
        const high = added.filter((c) => RISK[c] === 'high');
        const apply = () => { const before = sel.state; sel.granted = next; const miss = missing(sel); let note = ''; if (sel.state === 'enabled' && miss.length) { sel.state = 'disabled'; sel.stateChangedAt = 'just now'; note = ' It lost required ' + miss.join(', ') + ' and is disabled.'; } transitionNote(sel, 'grants', before, sel.state, (added.length ? 'added ' + added.join(', ') : '') + (removed.length ? (added.length ? '; ' : '') + 'removed ' + removed.join(', ') : '')); st.problem = null; ctx.rerender(); ctx.toast('Grants saved for ' + esc(sel.key) + '. Audited plugin.grants.updated (added ' + added.length + ', removed ' + removed.length + ', highRisk ' + high.length + ').' + note, note ? 'warn' : 'ok', 5000); };
        if (high.length) ctx.confirm({ title: 'Grant high-risk capabilities', tag: 'high risk', tone: 'danger', body: '<p class="fg2" style="margin:0">' + esc(sel.name) + ' would hold ' + high.map((c) => '<span class="mono">' + esc(c) + '</span>').join(', ') + '. Webhook calls stay inside the tenant\'s allowed hosts; workflows run as the installer; record and post writes are audited to the plugin.</p>', kv: [['Plugin', esc(sel.key)], ['Publisher', esc(sel.publisher)]], ok: 'Grant' }).then((ok) => { if (ok) apply(); }); else apply();
      });
      ctx.on('click', '[data-configure]', () => ctx.modal({ title: 'Configure ' + esc(sel.name), body: '<p class="fg2" style="margin:0">Checked against the manifest\'s config.schema (422 on a mismatch) and sealed with the tenant key. Strings in actions may read it as {{config.&lt;field&gt;}}.</p><div class="formgrid">' + Object.keys(sel.config.schema).map((k) => UI.field(k, UI.input(sel.configured ? '••••••••' : '', { attrs: 'data-cfg="' + esc(k) + '"', placeholder: esc(sel.config.schema[k]) }))).join('') + '</div>', actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save', { kind: 'primary', attrs: 'data-cfgsave' }), onMount(m) { m.querySelector('[data-cfgsave]').addEventListener('click', () => { sel.configured = true; App.closeOverlay(); ctx.rerender(); ctx.toast('Config sealed and saved for ' + esc(sel.key) + '.', 'ok'); }); } }));

      // install
      ctx.on('click', '[data-validate]', () => { st.manifestText = ctx.$('[data-manifest]').value; st.validation = validate(st.manifestText); ctx.rerender(); });
      ctx.on('click', '[data-install]', () => {
        st.manifestText = ctx.$('[data-manifest]').value; const v = validate(st.manifestText); st.validation = v; if (!v.valid) { ctx.rerender(); return; }
        const m = v.manifest;
        if (st.plugins.some((p) => p.key === m.key && p.state !== 'removed')) { ctx.toast('409: ' + esc(m.key) + ' is installed and not removed. Remove it first, or install the new version over it from a bundle.', 'danger', 5000); return; }
        const low = (m.capabilities || []).filter((c) => RISK[c] === 'low'); const high = (m.capabilities || []).filter((c) => RISK[c] === 'high');
        ctx.confirm({ title: 'Install ' + esc(m.name || m.key), tone: 'info', body: '<p class="fg2" style="margin:0">Grants default to the low-risk capabilities it asks for (' + esc(low.join(', ') || 'none') + ').' + (high.length ? ' High-risk ones (' + esc(high.join(', ')) + ') stay ungranted until you name them in the inspector.' : '') + '</p><div class="formgrid">' + UI.field('Max label', UI.select(['public', 'internal', 'confidential'], 'internal', 'data-imaxlabel'), 'Events above it never reach the plugin; at most your clearance') + UI.field('Reason (optional)', UI.input('', { attrs: 'data-ireason' })) + '</div>', kv: [['Key', esc(m.key)], ['Kind', esc(m.kind)], ['Events', esc((m.events || []).join(', '))]], ok: 'Install' }).then((ok) => {
          if (!ok) return;
          const p = { id: 'pl-' + (st.plugins.length + 1), key: m.key, name: m.name || m.key, version: m.version, kind: m.kind, publisher: m.publisher || 'unknown publisher', state: 'installed', events: m.events || [], capabilities: m.capabilities || [], optionalCapabilities: m.optionalCapabilities || [], granted: low, maxLabel: (document.querySelector('[data-imaxlabel]') || {}).value || 'internal', configured: !m.config, manifestHash: 'sha256:' + Math.random().toString(16).slice(2, 6) + '…' + Math.random().toString(16).slice(2, 6), installedBy: 'Mara Okafor', stateChangedAt: 'just now', createdAt: 'just now', source: 'inline', description: m.description || '', actions: m.actions, webhook: m.webhook, script: m.script ? { entry: m.script.entry, language: m.script.language || 'javascript', bytes: (m.script.source || '').length } : undefined, config: { schema: (m.config && m.config.schema) || {} }, transitions: [{ event: 'install', from: null, to: 'installed', version: m.version, actor: 'Mara Okafor', reason: '', at: 'just now' }] };
          st.plugins.push(p); st.tab = 'plugins'; st.sel = p.id; st.validation = null; st.stateFilter = 'all'; st.kindFilter = 'all'; st.query = ''; ctx.rerender(); ctx.toast(esc(p.key) + ' installed (201) with ' + low.length + ' low-risk grants. Audited plugin.installed. Enable it when ready.', 'ok', 5000);
        });
      });
      ctx.on('click', '[data-import]', (e, t) => {
        const a = st.available[+t.dataset.import];
        if (a.bundle.id === 'b-2026-38' && a.manifest.key === 'weekly-digest-poster' && st.signerRevoked) { st.bundleRefused = 'Bundle ' + a.bundle.name + ': the signature no longer verifies against the signer keys registered now (key northwind-release was revoked since promotion). Nothing was installed; audited plugin.import.refused.'; ctx.rerender(); return; }
        ctx.confirm({ title: 'Install ' + esc(a.manifest.name) + ' from ' + esc(a.bundle.name), tone: 'info', body: '<p class="fg2" style="margin:0">The file is read again from the stored transfer; its digest, the bundle signature (signer ' + esc(a.bundle.signer) + ') and the file\'s sha256 against the signed manifest are checked first. A script plugin from a promoted bundle may be enabled.</p>' + UI.field('Max label', UI.select(['public', 'internal', 'confidential'], 'internal', 'data-imaxlabel')), kv: [['Path', esc(a.path)], ['sha256', esc(a.sha256)], ['Capabilities', esc(a.manifest.capabilities.join(', '))]], ok: 'Install' }).then((ok) => {
          if (!ok) return;
          const existing = st.plugins.find((p) => p.key === a.manifest.key && p.state !== 'removed');
          const low = a.manifest.capabilities.filter((c) => RISK[c] === 'low');
          if (existing) { existing.version = a.manifest.version; existing.source = 'bundle'; existing.bundle = a.bundle; existing.manifestHash = a.sha256; transitionNote(existing, 'install', existing.state, existing.state, 'from bundle ' + a.bundle.name); st.sel = existing.id; }
          else { const p = { id: 'pl-' + (st.plugins.length + 1), key: a.manifest.key, name: a.manifest.name, version: a.manifest.version, kind: a.manifest.kind, publisher: 'Northwind platform team', state: 'installed', events: ['record.transitioned'], capabilities: a.manifest.capabilities, optionalCapabilities: [], granted: low, maxLabel: (document.querySelector('[data-imaxlabel]') || {}).value || 'internal', configured: true, manifestHash: a.sha256, installedBy: 'Mara Okafor', stateChangedAt: 'just now', createdAt: 'just now', source: 'bundle', bundle: a.bundle, description: 'Installed from ' + a.bundle.name + '.', script: { entry: 'onClose', language: 'javascript', bytes: 3104 }, config: { schema: {} }, transitions: [{ event: 'install', from: null, to: 'installed', version: a.manifest.version, actor: 'Mara Okafor', reason: 'from bundle ' + a.bundle.name, at: 'just now' }] }; st.plugins.push(p); st.sel = p.id; }
          a.installed = true; st.tab = 'plugins'; st.problem = null; ctx.rerender(); ctx.toast(esc(a.manifest.key) + ' ' + esc(a.manifest.version) + ' installed from ' + esc(a.bundle.name) + '. Audited plugin.installed with source bundle.', 'ok', 5000);
        });
      });

      // catalogue
      ctx.on('click', '[data-fulllog]', () => { const i = st.invocations.find((x) => x.id === st.selInv); if (!i) return; ctx.drawer({ title: 'Log of ' + esc(i.id), body: '<div class="muted" style="font-size:12px">GET /admin/plugins/' + esc(i.plugin) + '/logs?invocation=' + esc(i.id) + ', newest first, opened from the sealed log.</div>' + (i.logs.length ? UI.code(i.logs.slice().reverse().map((l) => l.at + ' ' + l.level.toUpperCase().padEnd(5) + ' ' + l.message).join('\n'), 'log') : UI.empty('No log lines', 'The handler has not written anything yet.')), actions: UI.btn('Close', { attrs: 'data-close' }) }); });
      ctx.on('click', '[data-replay]', () => replayModal(ctx));
      if (st.openReplay) { st.openReplay = false; setTimeout(() => replayModal(ctx), 50); }
    }
  });

  function outcomeCell(i) {
    if (i.error) return '<span style="color:var(--warn-fg);font-size:12px">' + esc(i.error) + '</span>';
    if (!i.outcome) return '<span class="muted">—</span>';
    if (i.outcome.actions) return i.outcome.actions.map((a) => UI.pill(a.type + (a.ok ? '' : ' ' + a.status), a.ok ? 'ok' : 'danger')).join(' ');
    return i.outcome.calls.map((c) => UI.pill(c.api + ' ' + c.status, c.status < 300 ? 'ok' : 'danger')).join(' ') + ' <span class="muted" style="font-size:11px">exit ' + i.outcome.exitCode + ', ' + i.outcome.durationMs + ' ms</span>';
  }
  function invocationPanel(i) {
    return '<div class="hstack"><div class="eyebrow grow">Invocation</div>' + UI.pill(i.state, invKind(i.state)) + '</div><div style="font-size:15px;font-weight:600" class="mono">' + esc(i.id) + '</div>'
      + UI.kv([['Plugin', '<a href="#" data-openplugin="' + esc(i.plugin) + '">' + esc(i.plugin) + '</a>'], ['Event', '<span class="mono">' + esc(i.event) + '</span> ' + esc(i.eventId)], ['Label', UI.label(i.label, { sm: true })], ['Attempts', String(i.attempts)], ['Chain', i.chain.map((c) => '<span class="mono">' + esc(c) + '</span>').join(' → ')], ['Created', esc(i.createdAt)], ['Started', esc(i.startedAt || 'not yet')], ['Finished', esc(i.finishedAt || 'not yet')]], 2)
      + (i.error ? UI.notice('<b>Dropped.</b> ' + esc(i.error) + '. Counted in <span class="mono">exprsn_plugin_dropped_total{reason="loop"}</span>; the chain rule never delivers an event to a plugin that is already behind it.', 'warn') : '')
      + (i.outcome ? '<div class="eyebrow">Outcome</div>' + UI.code(JSON.stringify(i.outcome, null, 2), 'json') : '')
      + '<div class="hstack"><div class="eyebrow grow">Log</div>' + UI.btn('Open full log', { kind: 'ghost', size: 'xs', attrs: 'data-fulllog' }) + '</div>'
      + (i.logs.length ? '<div class="vstack gap4" style="font-size:12px">' + i.logs.map((l) => '<div class="hstack gap6" style="align-items:flex-start">' + UI.pill(l.level, l.level === 'error' ? 'danger' : l.level === 'warn' ? 'warn' : '') + '<span class="mono muted">' + esc(l.at) + '</span><span>' + esc(l.message) + '</span></div>').join('') + '</div>' : '<span class="muted" style="font-size:12px">No log lines yet.</span>')
      + '<span class="muted" style="font-size:12px">Logs are opened from the sealed log; the handler\'s output and return value land here too.</span>';
  }
  function validate(text) {
    let m;
    try { m = JSON.parse(text); } catch (e) { return { valid: false, errors: ['The manifest is not valid JSON: ' + e.message + '.'] }; }
    const errors = []; const known = ['key', 'name', 'version', 'kind', 'description', 'publisher', 'homepage', 'events', 'capabilities', 'optionalCapabilities', 'config', 'actions', 'webhook', 'script'];
    Object.keys(m).forEach((k) => { if (!known.includes(k)) errors.push('Unknown field "' + k + '".'); });
    if (!m.key || !/^[a-z0-9-]{3,64}$/.test(m.key)) errors.push('key must be 3 to 64 lower-case letters, digits and hyphens.');
    if (!m.version || !/^\d+\.\d+\.\d+/.test(m.version)) errors.push('version must be semver.');
    if (!['declarative', 'webhook', 'script'].includes(m.kind)) errors.push('kind must be declarative, webhook or script.');
    (m.capabilities || []).concat(m.optionalCapabilities || []).forEach((c) => { if (!RISK[c]) errors.push('capabilities: "' + c + '" is not in the vocabulary.'); });
    const need = { 'record.': 'read:records', 'file.': 'read:files', 'group.': 'read:groups', 'message.': 'read:messages', 'post.': 'read:posts' };
    (m.events || []).forEach((ev) => { Object.keys(need).forEach((pre) => { if (ev.startsWith(pre) && !(m.capabilities || []).concat(m.optionalCapabilities || []).includes(need[pre])) errors.push('events: "' + ev + '" needs ' + need[pre] + '.'); }); });
    const capOf = { log: 'emit:log', audit: 'emit:audit', notify: 'emit:notification', flag: 'emit:flag', webhook: 'call:webhook', workflow: 'call:workflow' };
    (m.actions || []).forEach((a, i) => { if (!capOf[a.type]) errors.push('actions[' + i + ']: unknown type "' + a.type + '".'); else if (!(m.capabilities || []).concat(m.optionalCapabilities || []).includes(capOf[a.type])) errors.push('actions[' + i + ']: ' + a.type + ' needs ' + capOf[a.type] + ' declared.'); });
    if (m.kind === 'webhook' && !(m.webhook && m.webhook.url)) errors.push('A webhook plugin needs webhook.url.');
    if (m.kind === 'script' && !(m.script && m.script.entry && m.script.source)) errors.push('A script plugin needs script.entry and script.source.');
    if (errors.length) return { valid: false, errors };
    return { valid: true, manifest: m, summary: m.kind + ' plugin ' + m.key + ' ' + m.version + ', ' + (m.events || []).length + ' event subscriptions, ' + (m.capabilities || []).length + ' capabilities (' + (m.capabilities || []).filter((c) => RISK[c] === 'high').length + ' high risk)' + (m.actions ? ', ' + m.actions.length + ' actions' : '') + '.' };
  }
  function replayModal(ctx) {
    ctx.modal({ title: 'Replay events to a webhook', cls: 'wide', body: '<p class="fg2" style="margin:0">As <span class="mono">exprsn-ai events replay</span>: deliveries sends past deliveries again, each its exact body as a new delivery; audit backfills audit-action events from the audit chain that the webhook never received, within its event list and label.</p><div class="formgrid">' + UI.field('Webhook', UI.select(WEBHOOKS, WEBHOOKS[0], 'data-rwh')) + UI.field('Source', UI.select([{ value: 'deliveries', label: 'deliveries: past deliveries again' }, { value: 'audit', label: 'audit: backfill from the audit chain' }], 'deliveries', 'data-rsrc')) + UI.field('Since', UI.input('2026-09-18T00:00', { type: 'datetime-local', attrs: 'data-rsince' })) + UI.field('Until', UI.input('2026-09-19T14:00', { type: 'datetime-local' })) + UI.field('Types (optional)', UI.input('flag.created, flag.escalated', { attrs: 'data-rtypes' })) + UI.field('State (deliveries)', UI.select(['any', 'failed', 'succeeded'], 'failed')) + '</div>' + UI.toggle('Dry run: count only', true, 'data-rdry') + '<div data-rout></div>', actions: UI.btn('Close', { attrs: 'data-close' }) + UI.btn('Run', { kind: 'primary', attrs: 'data-rrun' }), onMount(m) { m.querySelector('[data-rrun]').addEventListener('click', () => { const dry = m.querySelector('[data-rdry]').classList.contains('on'); const src = m.querySelector('[data-rsrc]').value; const n = src === 'audit' ? 38 : 7; m.querySelector('[data-rout]').innerHTML = UI.notice('<b>' + (dry ? 'Dry run: ' : '') + n + ' events ' + (dry ? 'would be ' : '') + 'queued</b> to ' + esc(m.querySelector('[data-rwh]').value) + ' from ' + src + ' since ' + esc(m.querySelector('[data-rsince]').value.replace('T', ' ')) + (dry ? '. Turn the dry run off to deliver them; audited webhook.replayed.' : '. Audited webhook.replayed; deliveries follow the webhook\'s retries and breaker.'), dry ? 'info' : 'ok'); if (!dry) ctx.toast(n + ' replay deliveries queued.', 'ok'); }); } });
  }
})();
