(function () {
  const { UI, esc } = App;

  // ---- nav entry (app.js untouched): after Jobs and queues when present, otherwise before Platform ----
  (function nav() {
    const admin = (App.NAV || []).find((g) => g.group === 'Admin'); if (!admin || admin.items.some((i) => i.id === 'storage')) return;
    const item = { id: 'storage', label: 'Storage', icon: 'upload' };
    const jobs = admin.items.findIndex((i) => i.id === 'jobs'), plat = admin.items.findIndex((i) => i.id === 'platform');
    if (jobs >= 0) admin.items.splice(jobs + 1, 0, item); else if (plat >= 0) admin.items.splice(plat, 0, item); else admin.items.push(item);
  })();

  // ---- example data: stores, usage, quarantine, integrity, purges (Northwind, 19 Sep 2026 14:10) ----
  // sizes are in GiB
  const STORES0 = () => [
    { id: 'blobs', name: 'Blob store', kind: 'S3', location: 'MinIO, bucket exprsn-blobs', used: 1454, capacity: 2048, objects: '2.1 M objects, 3 multipart uploads in flight', health: 'ok', checked: '14:09', settings: ['BLOB_STORE', 'S3_BUCKET', 'S3_ENDPOINT', 'S3_REGION'], detail: '/readyz blobs: ok. HEAD on the bucket answered in 18 ms; the last multipart upload completed 14:06. Writes are streamed (B-411), never held in memory.', growth: [1250, 1262, 1270, 1281, 1290, 1298, 1310, 1322, 1330, 1341, 1350, 1358, 1366, 1372, 1380, 1388, 1395, 1402, 1410, 1416, 1422, 1428, 1433, 1438, 1442, 1446, 1449, 1451, 1453, 1454], verify: true, migrate: true },
    { id: 'db', name: 'Database', kind: 'PostgreSQL 16', location: 'postgres.data.northwind.local:5432, database exprsn_ai', used: 48, capacity: 500, objects: '34 of 100 connections', health: 'ok', checked: '14:09', settings: ['DB_CLIENT', 'DATABASE_URL', 'DB_POOL_MAX'], detail: '/readyz database: ok, migrations: ok (032_dav), schema: ok. The largest tables are audit_events (14 GiB) and app_record_values (9 GiB).', growth: [40, 40, 41, 41, 41, 42, 42, 42, 43, 43, 43, 44, 44, 44, 45, 45, 45, 45, 46, 46, 46, 47, 47, 47, 47, 48, 48, 48, 48, 48] },
    { id: 'vectors', name: 'Vector store', kind: 'pgvector', location: 'in the database, 9 knowledge bases', used: 21, capacity: null, objects: '11.2 M vectors', health: 'ok', checked: '14:09', settings: ['KNOWLEDGE_REPLICATION', 'KNOWLEDGE_REPLICATION_TICK_MS'], detail: 'HNSW indexes on every base; the largest is Support tickets (4.1 M vectors). A re-index runs as knowledge.reindex.', growth: [15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21] },
    { id: 'backups', name: 'Backups', kind: 'S3', location: 'MinIO, bucket exprsn-backups', used: 310, capacity: 1024, objects: '14 kept, last 23:00, RPO 60 min', health: 'ok', checked: '23:04', settings: ['PLATFORM_BACKUP_MINUTES', 'PLATFORM_BACKUP_RETAIN', 'PLATFORM_BACKUP_BLOBS'], detail: 'Consistent backups of the database and the blob store (PLATFORM_BACKUP_BLOBS=true). The last restore drill took 3 h 10 min against an RTO of 4 h.', growth: [240, 245, 250, 250, 255, 260, 262, 265, 268, 270, 272, 275, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 309, 310], link: ['platform', { tab: 'backups' }, 'Open Platform › Backups'] },
    { id: 'media', name: 'Media work directory', kind: 'Filesystem', location: 'MEDIA_WORK_DIR on api-1', used: 12, capacity: 80, objects: 'scratch, 41 jobs in progress or waiting for pickup', health: 'ok', checked: '14:09', settings: ['MEDIA_WORK_DIR', 'MEDIA_MAX_BYTES', 'MEDIA_URL_TTL_SECONDS'], detail: 'Transcodes and transcripts land here before their outputs are sealed into the blob store. Cleared when a job finishes or is cancelled.', growth: [9, 10, 8, 11, 12, 9, 10, 13, 11, 10, 12, 14, 9, 8, 10, 12, 11, 13, 12, 10, 9, 11, 12, 13, 12, 11, 10, 12, 13, 12] },
    { id: 'datasets', name: 'Training datasets', kind: 'Sealed files', location: 'on trainer-gpu-1', used: 86, capacity: 400, objects: '23 datasets, 61 versions', health: 'ok', checked: '14:08', settings: ['TRAINER_URL', 'TRAINER_ARTIFACT_MAX_BYTES'], detail: 'Datasets are sealed with the tenant key and opened only inside the trainer (B-905). Versions are kept while a job or model card references them.', growth: [70, 70, 72, 72, 72, 74, 74, 75, 75, 75, 78, 78, 78, 80, 80, 80, 81, 81, 83, 83, 83, 84, 84, 84, 85, 85, 86, 86, 86, 86] },
    { id: 'models', name: 'Model files', kind: 'Ollama', location: 'on the pools', used: 212, capacity: 1024, objects: '31 models, 48 blobs', health: 'ok', checked: '14:05', settings: ['OLLAMA_MAX_LOADS_PER_10_MIN', 'OLLAMA_LOAD_TIMEOUT_MS'], detail: 'Weights live on each pool\'s instances, pulled through the registry mirror. Placement and eviction are on Pools.', growth: [180, 180, 180, 186, 186, 186, 186, 194, 194, 194, 194, 194, 200, 200, 200, 200, 204, 204, 204, 204, 204, 212, 212, 212, 212, 212, 212, 212, 212, 212], link: ['pools', {}, 'Open Pools'] }
  ];
  const USAGE0 = () => [
    { id: 'finance', workspace: 'Finance Ops', tenant: 'Northwind', label: 'confidential', files: 268, versions: 71, trash: 14, media: 31, knowledge: 22, attachments: 6, quota: 500, growth: [380, 384, 388, 390, 392, 395, 397, 399, 400, 402, 403, 404, 405, 406, 407, 408, 408, 409, 409, 410, 410, 411, 411, 411, 412, 412, 412, 412, 412, 412], users: [['Felix Brandt', 121], ['Mara Okafor', 64], ['Jonas Lindqvist', 48], ['Priya Natarajan', 37], ['Tom Becker', 29]] },
    { id: 'people', workspace: 'People Ops', tenant: 'Northwind', label: 'internal', files: 84, versions: 19, trash: 6, media: 12, knowledge: 9, attachments: 4, quota: 300, growth: [110, 111, 112, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 128, 129, 129, 130, 131, 132, 132, 133, 133, 134], users: [['Noor Rahimi', 41], ['Lena Hoffmann', 33], ['Ida Sørensen', 22], ['Marc Dubois', 20], ['Mara Okafor', 18]] },
    { id: 'sales', workspace: 'Field Sales', tenant: 'Northwind', label: 'internal', files: 141, versions: 22, trash: 9, media: 58, knowledge: 11, attachments: 7, quota: 400, growth: [220, 221, 222, 224, 225, 226, 228, 229, 230, 231, 232, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 244, 245, 246, 246, 247, 247, 248, 248], users: [['Jon Alvarez', 72], ['Lucía Ferreira', 55], ['Sam Whitaker', 40], ['Mara Okafor', 31], ['Elin Berg', 25]] },
    { id: 'legal', workspace: 'Legal', tenant: 'Northwind', label: 'confidential', files: 131, versions: 38, trash: 4, media: 2, knowledge: 14, attachments: 3, quota: 200, growth: [150, 152, 155, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 190, 191, 191, 192, 192], users: [['Hanna Kowalski', 88], ['Felix Brandt', 41], ['Mara Okafor', 30], ['Daniel Osei', 21], ['Ida Sørensen', 12]] },
    { id: 'lab', workspace: 'Platform lab', tenant: 'Contoso', label: 'public', files: 12, versions: 3, trash: 1, media: 20, knowledge: 4, attachments: 1, quota: 100, growth: [30, 30, 31, 31, 32, 33, 33, 34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41], users: [['Jonas Lindqvist', 19], ['Mara Okafor', 11], ['Contoso service account', 8], ['Elin Berg', 2], ['Sam Whitaker', 1]] }
  ];
  const QUAR0 = () => [
    { id: 'q-1', object: 'Q3-forecast-v4.xlsx', kind: 'file version', workspace: 'Finance Ops', size: '2.4 MiB', state: 'scanning', age: '40 s', by: 'Felix Brandt', detail: 'Version 5 of a file; version 4 stays readable until this one passes.' },
    { id: 'q-2', object: 'invoice-batch-0919.zip', kind: 'attachment', workspace: 'Finance Ops', size: '18 MiB', state: 'infected', age: '2 h', by: 'customer channel billing', detail: 'ClamAV: Win.Trojan.Emotet-9873 in payload/inv-2291.xlsm. Never written to the blob store; the sender was flagged for review.' },
    { id: 'q-3', object: 'team-photo.png', kind: 'message attachment', workspace: 'People Ops', size: '6.1 MiB', state: 'type mismatch', age: '3 h', by: 'Noor Rahimi', detail: 'Declared image/png, content is application/x-dosexec. Refused by the type check before the scan.' },
    { id: 'q-4', object: 'all-hands-recording.mov', kind: 'media upload', workspace: 'People Ops', size: '2.3 GiB', state: 'too large', age: '5 h', by: 'Lena Hoffmann', detail: 'Above MEDIA_MAX_BYTES (2 GiB). The upload stopped at the cap; nothing was stored.' },
    { id: 'q-5', object: 'contract-pack-2026-09.pdf', kind: 'file', workspace: 'Legal', size: '412 MiB', state: 'timed out', age: '26 min', by: 'Hanna Kowalski', detail: 'The scan did not answer within the timeout. The file stays in quarantine; Rescan tries again.' },
    { id: 'q-6', object: 'dataset-import-rows.csv', kind: 'app import', workspace: 'Field Sales', size: '91 MiB', state: 'scanning', age: '12 s', by: 'Jon Alvarez', detail: 'An apps.import job waits for the scan before it reads a row.' }
  ];
  const FINDINGS0 = () => [
    { id: 'f-1', finding: 'orphan', object: 'blobs/nw/2026/07/3f9a…c1e2', referencedBy: 'nothing (file version deleted 12 Aug, purge skipped the blob)', size: '38 MiB', found: '03:12' },
    { id: 'f-2', finding: 'orphan', object: 'blobs/nw/2026/08/88d0…4b7f', referencedBy: 'nothing (media output, job cancelled)', size: '1.1 GiB', found: '03:12' },
    { id: 'f-3', finding: 'missing', object: 'blobs/nw/2026/05/0c4e…9a10', referencedBy: 'file version Finance Ops/Board pack 2026-05.pdf v2', size: '9 MiB', found: '03:14' },
    { id: 'f-4', finding: 'missing', object: 'blobs/nw/2026/06/7a21…e0d3', referencedBy: 'knowledge upload People Ops/Handbook 2026.docx', size: '2 MiB', found: '03:14' },
    { id: 'f-5', finding: 'checksum mismatch', object: 'blobs/nw/2026/09/5e0c…a8d1', referencedBy: 'image Field Sales/img-7781', size: '640 KiB', found: '03:15' }
  ];
  const PURGES = [
    { what: 'File trash', policy: 'FILES_TRASH_DAYS = 30', where: ['configuration', { q: 'FILES_TRASH_DAYS' }, 'Configuration'], job: 'files.purge', period: 'every 60 min (FILES_PURGE_MINUTES)', last: '13:30', removed: '41 items, 2.1 GiB', next: '14:30' },
    { what: 'Conversation retention', policy: 'per workspace and user', where: ['tenants', { tab: 'retention' }, 'Tenants › Retention'], job: 'chat.retention', period: 'every 30 min (CHAT_RETENTION_SWEEP_MINUTES)', last: '13:55', removed: '318 messages', next: '14:25' },
    { what: 'Channel retention', policy: 'per channel', where: ['channels', {}, 'Channels'], job: 'channels.retention', period: 'every 60 min (CHANNELS_RETENTION_SWEEP_MINUTES)', last: '13:10', removed: '2 sessions, 1 transcript', next: '14:10' },
    { what: 'Memory purge', policy: 'per workspace memory policy', where: ['memory', {}, 'Memory'], job: 'memory.purge', period: 'every 60 min', last: '13:40', removed: '27 expired facts', next: '14:40' },
    { what: 'Media outputs', policy: 'MEDIA_URL_TTL_SECONDS = 3600 for links; outputs kept with the asset', where: ['configuration', { q: 'MEDIA_URL_TTL_SECONDS' }, 'Configuration'], job: 'media.process', period: 'on completion', last: '14:02', removed: '12 GiB scratch', next: 'with the next job' },
    { what: 'Audit exports', policy: 'downloads expire after 7 days', where: ['usage-audit', {}, 'Usage and audit'], job: 'export.audit', period: 'daily 02:00', last: 'today 02:00', removed: '3 exports', next: 'tomorrow 02:00' },
    { what: 'Backup retention', policy: 'PLATFORM_BACKUP_RETAIN = 14', where: ['platform', { tab: 'backups' }, 'Platform › Backups'], job: 'ops.backup.create', period: 'every 60 min (PLATFORM_BACKUP_MINUTES)', last: '23:00', removed: '1 backup', next: '15:00' },
    { what: 'Knowledge replication snapshots', policy: 'last 3 snapshots per replicated source', where: ['knowledge', {}, 'Knowledge'], job: 'knowledge.sync', period: 'with each sync', last: '13:50', removed: '1 snapshot, 240 MiB', next: '14:20' }
  ];
  const fmt = (gib) => gib >= 1024 ? (gib / 1024).toFixed(2) + ' TiB' : Math.round(gib) + ' GiB';
  const total = (u) => u.files + u.versions + u.trash + u.media + u.knowledge + u.attachments;
  const pct = (a, b) => Math.round((a / b) * 100);
  const tone = (p) => p > 100 ? 'danger' : p > 80 ? 'warn' : '';
  const qKind = (s) => s === 'scanning' ? 'info' : s === 'infected' || s === 'type mismatch' ? 'danger' : 'warn';
  const fKind = (f) => f === 'orphan' ? 'warn' : 'danger';

  function menu(ctx, anchor, items, active, pick) {
    const host = anchor.closest('.relative'); const ex = host.querySelector('.dropdown'); ctx.$$('.dropdown').forEach((d) => d.remove()); if (ex) return;
    const d = document.createElement('div'); d.className = 'dropdown';
    d.innerHTML = items.map((it) => '<button type="button" data-v="' + esc(it[0]) + '" class="' + (it[0] === active ? 'on' : '') + '">' + esc(it[1]) + '</button>').join('');
    host.appendChild(d);
    d.addEventListener('click', (ev) => { const b = ev.target.closest('button'); if (!b) return; d.remove(); pick(b.dataset.v); });
    setTimeout(() => document.addEventListener('click', function off(ev) { if (!d.contains(ev.target)) { d.remove(); document.removeEventListener('click', off); } }), 0);
  }
  const init = (st) => {
    if (st.stores) return;
    st.stores = STORES0(); st.usage = USAGE0(); st.quarantine = QUAR0(); st.findings = FINDINGS0();
    st.tab = 'stores'; st.sel = 'blobs'; st.selUsage = 'finance'; st.usageBy = 'workspace'; st.selQ = 'q-2'; st.qState = 'all'; st.qQuery = '';
    st.clamOk = true; st.fsStore = false; st.verify = null; st.lastVerify = { at: 'today 03:12', checked: '2,104,318', missing: 2, orphans: 2, mismatch: 1, duration: '41 min' }; st.dryRun = null; st.orphansDeleted = false;
  };

  App.register({
    id: 'storage', title: 'Storage', section: 'admin', crumb: ['Admin', 'Storage'],
    summary: 'Blob stores, usage against quotas, quarantine, integrity and purges',
    commands: [
      { label: 'Run an integrity check', sub: 'Storage', run(app) { const s = app.stateFor('storage'); init(s); s.tab = 'integrity'; s.openVerify = true; app.render(); } },
      { label: 'Set a workspace quota', sub: 'Storage', run(app) { const s = app.stateFor('storage'); init(s); s.tab = 'usage'; s.openQuota = true; app.render(); } }
    ],
    states: [
      { title: 'Store nearly full', tone: 'warn', text: 'The blob store is at 93 %. The meter turns amber, a notice names the store, and Platform raises the same alert.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'stores'; st.sel = 'blobs'; st.stores.find((s) => s.id === 'blobs').used = Math.round(0.93 * 2048); ctx.rerender(); } },
      { title: 'ClamAV unreachable', tone: 'danger', text: 'The daemon at CLAMD_HOST does not answer. Uploads stay queued in quarantine and nothing is released unscanned; the queue grows.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'quarantine'; st.clamOk = false; st.quarantine.forEach((q) => { if (q.state === 'scanning') q.age = '38 min'; }); if (!st.quarantine.some((q) => q.id === 'q-7')) st.quarantine.unshift({ id: 'q-7', object: 'payroll-2026-09.csv', kind: 'file', workspace: 'People Ops', size: '820 KiB', state: 'scanning', age: '31 min', by: 'Noor Rahimi', detail: 'Waiting for the scanner. Readable only once ClamAV answers.' }); st.selQ = 'q-7'; ctx.rerender(); } },
      { title: 'Orphans found', tone: 'warn', text: 'The last verification found 1,204 orphans and 3 missing objects. Delete orphans runs a dry run first, then asks for a reason.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'integrity'; st.lastVerify = { at: 'today 03:12', checked: '2,104,318', missing: 3, orphans: 1204, mismatch: 1, duration: '44 min' }; st.orphansDeleted = false; st.dryRun = null; ctx.rerender(); } },
      { title: 'Quota exceeded', tone: 'danger', text: 'Legal is at 104 % of its 200 GiB quota. Uploads to the workspace are refused with 413 until space is freed or the quota raised (B-2403).', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'usage'; st.usageBy = 'workspace'; const u = st.usage.find((x) => x.id === 'legal'); u.files = 147; u.versions = 42; st.selUsage = 'legal'; ctx.rerender(); } },
      { title: 'Filesystem store on one node', tone: 'neutral', text: 'BLOB_STORE=fs keeps objects under BLOB_DIR on one instance. A second instance needs a shared path or an S3 store before it can serve files.', apply(ctx) { init(ctx.state); const st = ctx.state; st.tab = 'stores'; st.sel = 'blobs'; st.fsStore = true; const b = st.stores.find((s) => s.id === 'blobs'); b.kind = 'Filesystem'; b.location = 'BLOB_DIR=/var/lib/exprsn-ai/blobs on api-1'; b.settings = ['BLOB_STORE', 'BLOB_DIR']; b.detail = '/readyz blobs: ok (filesystem /var/lib/exprsn-ai/blobs). Only api-1 can read and write objects; api-2 answers 503 for files until the store is shared.'; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state; init(st);
      if (ctx.params.tab) { st.tab = ctx.params.tab; delete ctx.params.tab; }
      if (ctx.params.workspace) { const u = st.usage.find((x) => x.workspace === ctx.params.workspace || x.id === ctx.params.workspace); if (u) { st.tab = 'usage'; st.selUsage = u.id; } delete ctx.params.workspace; }
      const tabs = UI.tabs([{ id: 'stores', label: 'Stores', count: st.stores.length }, { id: 'usage', label: 'Usage' }, { id: 'quarantine', label: 'Quarantine', count: st.quarantine.length }, { id: 'integrity', label: 'Integrity' }, { id: 'purges', label: 'Purges' }], st.tab);
      let body = '', insp = '';

      // ---------------- Stores ----------------
      if (st.tab === 'stores') {
        const blobs = st.stores.find((s) => s.id === 'blobs'); const bp = pct(blobs.used, blobs.capacity);
        if (!st.stores.some((s) => s.id === st.sel)) st.sel = 'blobs';
        const sel = st.stores.find((s) => s.id === st.sel);
        body += (bp > 90 ? UI.notice('<b>Blob store at ' + bp + ' %.</b> ' + esc(fmt(blobs.used)) + ' of ' + esc(fmt(blobs.capacity)) + ' used; at this rate the bucket is full in about 9 weeks. Platform shows the same alert.', 'warn', UI.btn('Usage by workspace', { size: 'xs', attrs: 'data-tab-go="usage"' })) : '')
          + (st.fsStore ? UI.notice('<b>Filesystem store on one node.</b> BLOB_STORE is <span class="mono">fs</span>; objects live under BLOB_DIR on api-1 only. A second instance needs a shared path or an S3 store.', 'info', UI.btn('BLOB_STORE', { size: 'xs', attrs: 'data-setting="BLOB_STORE"' })) : '')
          + UI.table(['Store', 'Kind', 'Location', { label: 'Used', right: true }, { label: 'Capacity', right: true }, 'Objects', 'Health', 'Checked'], st.stores.map((s) => { const p = s.capacity ? pct(s.used, s.capacity) : null; return { cells: ['<span style="font-weight:600">' + esc(s.name) + '</span>', esc(s.kind), '<span class="mono" style="font-size:12px">' + esc(s.location) + '</span>', '<span class="num" style="white-space:nowrap">' + esc(fmt(s.used)) + '</span>', s.capacity ? '<span class="num" style="white-space:nowrap">' + esc(fmt(s.capacity)) + (p != null ? ' <span class="' + (tone(p) ? '' : 'muted') + '" style="' + (tone(p) ? 'color:var(--' + tone(p) + '-fg)' : '') + '">' + p + ' %</span>' : '') + '</span>' : '<span class="muted">grows with the database</span>', esc(s.objects), UI.pill(s.health, s.health === 'ok' ? 'ok' : 'danger'), esc(s.checked)], attrs: 'data-store="' + s.id + '"', selected: s.id === st.sel }; }), { minWidth: '980px' })
          + '<span class="muted" style="font-size:12px">Health is what <span class="mono">/readyz</span> reports on each instance (<span class="mono">blobs</span>, <span class="mono">database</span>); the other rows come from the owning service. Capacity is what the store told us, or the quota set for it.</span>';
        if (sel) {
          const p = sel.capacity ? pct(sel.used, sel.capacity) : null;
          insp = '<div class="hstack"><div class="eyebrow grow">Selected store</div>' + UI.pill(sel.health, sel.health === 'ok' ? 'ok' : 'danger') + '</div><div style="font-size:15px;font-weight:600">' + esc(sel.name) + '</div><div class="muted" style="font-size:12px">' + esc(sel.kind) + ', ' + esc(sel.location) + '</div>'
            + (p != null ? UI.meter('Used', fmt(sel.used) + ' of ' + fmt(sel.capacity), p, tone(p)) : UI.kv([['Used', esc(fmt(sel.used))]], 1))
            + UI.kv([['Objects', esc(sel.objects)], ['Checked', esc(sel.checked) + ' by api-1']], 1)
            + '<div class="eyebrow">Health detail</div><div class="fg2" style="font-size:12px">' + esc(sel.detail) + '</div>'
            + '<div class="eyebrow">Settings</div><div class="hstack wrap gap6">' + sel.settings.map((k) => '<button type="button" class="chip mono" data-setting="' + esc(k) + '" title="Open in Configuration">' + esc(k) + '</button>').join('') + '</div>'
            + '<div class="hstack"><div class="eyebrow grow">Last 30 days</div><span class="muted" style="font-size:11px">' + esc(fmt(sel.growth[0])) + ' → ' + esc(fmt(sel.growth[sel.growth.length - 1])) + '</span></div>' + UI.spark(sel.growth, sel.growth.length - 1)
            + '<div class="hstack wrap gap6">' + (sel.verify ? UI.btn('Verify now', { kind: 'primary', size: 'sm', icon: 'check', attrs: 'data-verify' }) : '') + (sel.link ? UI.btn(sel.link[2], { size: 'sm', attrs: 'data-link="' + esc(sel.id) + '"' }) : '') + (sel.migrate ? UI.btn('Migrate to another store', { size: 'sm', attrs: 'data-migrate' }) + UI.pill('proposed', 'outline') : '') + '</div>'
            + (sel.id === 'blobs' ? '<span class="muted" style="font-size:12px">Verify runs the integrity check (Integrity tab). Migrate copies every object to a second store as a job and switches reads when it completes; a proposal, see question 16.</span>' : '');
        }
      }
      // ---------------- Usage ----------------
      if (st.tab === 'usage') {
        const rows = st.usage.slice().sort((a, b) => total(b) - total(a));
        if (!rows.some((u) => u.id === st.selUsage)) st.selUsage = rows[0].id;
        const sel = st.usage.find((u) => u.id === st.selUsage);
        const over = st.usage.filter((u) => total(u) > u.quota);
        body += (over.length ? UI.notice('<b>Quota exceeded:</b> ' + over.map((u) => esc(u.workspace) + ' at ' + pct(total(u), u.quota) + ' %').join(', ') + '. Uploads to the workspace answer <span class="mono">413</span> until space is freed or the quota raised.', 'danger', UI.btn('Set quota', { size: 'xs', attrs: 'data-quota="' + esc(over[0].id) + '"' })) : '')
          + '<div class="toolbar">' + UI.seg([{ id: 'workspace', label: 'By workspace' }, { id: 'user', label: 'By user' }, { id: 'kind', label: 'By kind' }], st.usageBy, 'data-usageby') + '<span class="muted right" style="font-size:12px">' + esc(fmt(st.usage.reduce((a, u) => a + total(u), 0))) + ' across ' + st.usage.length + ' workspaces</span></div>';
        if (st.usageBy === 'workspace') {
          body += UI.table(['Workspace', { label: 'Files', right: true }, { label: 'Versions', right: true }, { label: 'Trash', right: true }, { label: 'Media', right: true }, { label: 'Knowledge uploads', right: true }, { label: 'Attachments', right: true }, { label: 'Total', right: true }, { label: 'Quota', right: true }, { label: '', width: '120px' }], rows.map((u) => { const t = total(u), p = pct(t, u.quota); return { cells: ['<span style="font-weight:600">' + esc(u.workspace) + '</span> ' + UI.label(u.label, { sm: true }) + '<div class="muted" style="font-size:11px">' + esc(u.tenant) + '</div>', num(u.files), num(u.versions), num(u.trash), num(u.media), num(u.knowledge), num(u.attachments), '<span class="num" style="font-weight:600">' + esc(fmt(t)) + '</span>', num(u.quota), UI.meter('', p + ' %', p, tone(p))] }; }).map((r, i) => ({ cells: r.cells, attrs: 'data-usage="' + rows[i].id + '"', selected: rows[i].id === st.selUsage })), { minWidth: '820px' });
        } else if (st.usageBy === 'user') {
          const users = {}; st.usage.forEach((u) => u.users.forEach(([n, g]) => { users[n] = users[n] || { gib: 0, ws: [] }; users[n].gib += g; users[n].ws.push(u.workspace); }));
          const list = Object.keys(users).map((n) => ({ n, gib: users[n].gib, ws: users[n].ws })).sort((a, b) => b.gib - a.gib);
          body += UI.table(['User', 'Workspaces', { label: 'Total', right: true }, { label: '', width: '160px' }], list.map((x) => ['<span style="font-weight:600">' + esc(x.n) + '</span>', esc(x.ws.join(', ')), '<span class="num">' + esc(fmt(x.gib)) + '</span>', UI.meter('', pct(x.gib, list[0].gib) + ' % of the largest', pct(x.gib, list[0].gib), '')]), { clickable: false, minWidth: '700px' }) + '<span class="muted" style="font-size:12px">A user\'s files, versions, media, knowledge uploads and attachments in every workspace they belong to. Quotas apply per workspace, not per user (B-2403).</span>';
        } else {
          const kinds = [['Files', 'files'], ['Versions', 'versions'], ['Trash', 'trash'], ['Media', 'media'], ['Knowledge uploads', 'knowledge'], ['Attachments', 'attachments']].map(([l, k]) => ({ l, gib: st.usage.reduce((a, u) => a + u[k], 0) })); const all = kinds.reduce((a, k) => a + k.gib, 0);
          body += UI.table(['Kind', { label: 'Total', right: true }, { label: 'Share', right: true }, { label: '', width: '200px' }], kinds.map((k) => [esc(k.l), '<span class="num">' + esc(fmt(k.gib)) + '</span>', '<span class="num">' + pct(k.gib, all) + ' %</span>', UI.meter('', '', pct(k.gib, all), '')]), { clickable: false, minWidth: '600px' }) + '<span class="muted" style="font-size:12px">Trash counts against the quota until the purge removes it (FILES_TRASH_DAYS). Versions are kept per file; restoring one makes it the current version.</span>';
        }
        if (sel && st.usageBy === 'workspace') {
          const t = total(sel), p = pct(t, sel.quota);
          insp = '<div class="hstack"><div class="eyebrow grow">Selected workspace</div>' + UI.label(sel.label, { sm: true }) + '</div><div style="font-size:15px;font-weight:600">' + esc(sel.workspace) + '</div><div class="muted" style="font-size:12px">' + esc(sel.tenant) + ' tenant</div>'
            + UI.meter('Used', fmt(t) + ' of ' + fmt(sel.quota), p, tone(p)) + (p > 100 ? UI.notice('Uploads are refused with 413. Free space from Files or raise the quota.', 'danger') : p > 80 ? UI.notice('Above 80 %. Members see a warning in Files.', 'warn') : '')
            + '<div class="eyebrow">Top users</div>' + UI.table(['User', { label: 'GiB', right: true }], sel.users.map(([n, g]) => [esc(n), '<span class="num">' + g + '</span>']), { clickable: false, minWidth: '0', cls: 'bare' })
            + '<div class="hstack"><div class="eyebrow grow">Last 30 days</div><span class="muted" style="font-size:11px">' + esc(fmt(sel.growth[0])) + ' → ' + esc(fmt(t)) + '</span></div>' + UI.spark(sel.growth.concat([t]), sel.growth.length)
            + '<div class="hstack wrap gap6">' + UI.btn('Set quota', { kind: 'primary', size: 'sm', attrs: 'data-quota="' + esc(sel.id) + '"' }) + UI.btn('Open Files', { size: 'sm', attrs: 'data-files="' + esc(sel.workspace) + '"' }) + '</div>'
            + '<span class="muted" style="font-size:12px"><a href="#" data-goaudit>Audit entries</a>: files.quota.updated.</span>';
        }
      }
      // ---------------- Quarantine ----------------
      if (st.tab === 'quarantine') {
        const q = st.qQuery.toLowerCase();
        const rows = st.quarantine.filter((x) => (st.qState === 'all' || x.state === st.qState) && (!q || (x.object + ' ' + x.workspace + ' ' + x.kind + ' ' + x.by).toLowerCase().includes(q)));
        if (!rows.some((x) => x.id === st.selQ)) st.selQ = rows.length ? rows[0].id : null;
        const sel = st.quarantine.find((x) => x.id === st.selQ); const scanning = st.quarantine.filter((x) => x.state === 'scanning').length;
        body += (!st.clamOk ? UI.notice('<b>ClamAV is unreachable</b> at <span class="mono">clamd.data.northwind.local:3310</span> since 13:32. Uploads stay queued in quarantine and nothing is released unscanned; ' + scanning + ' objects wait. Rescan works again once the daemon answers.', 'danger', UI.btn('CLAMD_HOST', { size: 'xs', attrs: 'data-setting="CLAMD_HOST"' })) : '')
          + '<div class="grid2">' + UI.panel('Scanner', UI.kv([['Daemon', '<span class="mono">clamd.data.northwind.local:3310</span> <span class="muted">(CLAMD_HOST, CLAMD_PORT)</span>'], ['Reachable', st.clamOk ? UI.pill('yes', 'ok') + ' <span class="muted">answered PING 20 s ago</span>' : UI.pill('no', 'danger') + ' <span class="muted">last answer 13:32</span>'], ['Signature database', st.clamOk ? 'daily.cld 27 744, 19 Sep 2026 06:00' : 'daily.cld 27 744, 19 Sep 2026 06:00 <span style="color:var(--warn-fg)">(unverified)</span>'], ['Scanned today', '<span class="num">1,912</span> objects, 38 GiB'], ['Refused today', '<span class="num">3</span>: 1 infected, 1 type mismatch, 1 too large'], ['Timeouts today', '<span class="num">' + (st.clamOk ? '1' : '14') + '</span>']], 2))
          + UI.panel('How quarantine works', '<div class="fg2" style="font-size:12px">Every upload is streamed to quarantine first: the type check compares the declared type with the content, the size cap applies, then ClamAV scans it. Only a clean object is sealed into the blob store and becomes readable; a refusal never writes to the store and the sender is told why. Scanning objects count against the workspace quota.</div>') + '</div>'
          + '<div class="toolbar">' + UI.search('Filter by object, workspace, sender', 'data-qsearch', st.qQuery) + '<span class="relative">' + UI.btn(st.qState === 'all' ? 'State' : 'State: ' + st.qState, { size: 'sm', icon: 'filter', attrs: 'data-menu="qstate"', cls: st.qState !== 'all' ? 'active' : '' }) + '</span><span class="muted right" style="font-size:12px">' + rows.length + ' shown, ' + scanning + ' scanning</span></div>'
          + UI.table(['Object', 'Kind', 'Workspace', { label: 'Size', right: true }, 'State', 'Age', 'Uploaded by'], rows.map((x) => ({ cells: ['<span class="mono" style="font-size:12px">' + esc(x.object) + '</span>', esc(x.kind), esc(x.workspace), '<span class="num">' + esc(x.size) + '</span>', UI.pill(x.state, qKind(x.state)), esc(x.age), esc(x.by)], attrs: 'data-q="' + x.id + '"', selected: x.id === st.selQ })), { minWidth: '860px', emptyTitle: 'Quarantine is empty', emptyText: 'Nothing is waiting for a scan and nothing was refused in the last 24 hours.' });
        if (sel) {
          insp = '<div class="hstack"><div class="eyebrow grow">Quarantined object</div>' + UI.pill(sel.state, qKind(sel.state)) + '</div><div class="mono" style="font-size:13px;font-weight:600;overflow-wrap:anywhere">' + esc(sel.object) + '</div>'
            + UI.kv([['Kind', esc(sel.kind)], ['Workspace', esc(sel.workspace)], ['Size', esc(sel.size)], ['Age', esc(sel.age)], ['Uploaded by', esc(sel.by)], ['Written to the store', sel.state === 'scanning' ? 'not yet' : 'never']], 2)
            + '<div class="eyebrow">What happened</div><div class="fg2" style="font-size:12px">' + esc(sel.detail) + '</div>'
            + (sel.state === 'scanning' && !st.clamOk ? UI.notice('Waits for the scanner. Rescan is refused (503) while ClamAV is unreachable.', 'danger') : '')
            + '<div class="hstack wrap gap6">' + UI.btn('Rescan', { kind: 'primary', size: 'sm', icon: 'refresh', attrs: 'data-rescan', disabled: !st.clamOk || sel.state === 'scanning' }) + UI.btn('Delete', { kind: 'danger', size: 'sm', icon: 'trash', attrs: 'data-qdelete' }) + (sel.state === 'infected' ? UI.btn('Open the flag', { size: 'sm', attrs: 'data-goflags' }) : '') + '</div>'
            + '<span class="muted" style="font-size:12px">Nothing here can be released by hand; a clean rescan releases it. <a href="#" data-goaudit>Audit entries</a>: file.quarantine.rescanned, file.quarantine.deleted.</span>';
        }
      }
      // ---------------- Integrity ----------------
      if (st.tab === 'integrity') {
        const lv = st.lastVerify; const findings = st.orphansDeleted ? st.findings.filter((f) => f.finding !== 'orphan') : st.findings;
        body += (st.verify ? UI.notice('<b>Verification running</b> as job <span class="mono">' + esc(st.verify.job) + '</span> on api-1: ' + st.verify.step + '. ' + esc(st.verify.progress) + '.', 'info', UI.btn('Open the job', { size: 'xs', attrs: 'data-gojob="' + esc(st.verify.job) + '"' })) : '')
          + (lv.orphans > 100 && !st.orphansDeleted ? UI.notice('<b>' + lv.orphans.toLocaleString('en') + ' orphans and ' + lv.missing + ' missing objects</b> in the last run. Orphans take space nobody can reach; missing objects mean a file version or upload cannot be opened until it is restored from a backup.', 'warn') : '')
          + '<div class="grid2">' + UI.panel('Last verification', UI.kv([['When', esc(lv.at) + ' <span class="muted">(ops.blobs.verify ' + UI.pill('proposed', 'outline') + ')</span>'], ['Duration', esc(lv.duration)], ['Objects checked', '<span class="num">' + esc(lv.checked) + '</span>'], ['Missing', '<span class="num" style="' + (lv.missing ? 'color:var(--danger-fg)' : '') + '">' + lv.missing + '</span> <span class="muted">referenced, not in the store</span>'], ['Orphans', '<span class="num" style="' + (lv.orphans && !st.orphansDeleted ? 'color:var(--warn-fg)' : '') + '">' + (st.orphansDeleted ? 0 : lv.orphans).toLocaleString('en') + '</span> <span class="muted">in the store, referenced by nothing</span>'], ['Checksum mismatches', '<span class="num" style="' + (lv.mismatch ? 'color:var(--danger-fg)' : '') + '">' + lv.mismatch + '</span>']], 2), { actions: UI.btn(st.verify ? 'Running' : 'Run verification', { kind: 'primary', size: 'sm', icon: 'play', attrs: 'data-runverify', disabled: !!st.verify }) })
          + UI.panel('What the check does', '<div class="fg2" style="font-size:12px">Walks every reference (file versions, media outputs, knowledge uploads, attachments, images, backups) and every object in the blob store. A reference without an object is <b>missing</b>; an object without a reference is an <b>orphan</b>; an object whose SHA-256 differs from the sealed manifest is a <b>mismatch</b>. The check never deletes anything; it reports, and the actions below act on the report.</div>' + (st.dryRun ? UI.notice('<b>Dry run:</b> ' + st.dryRun.count.toLocaleString('en') + ' orphans, ' + esc(st.dryRun.size) + ', oldest ' + esc(st.dryRun.oldest) + '. Nothing was deleted. Delete orphans again to confirm with a reason.', 'info') : '')) + '</div>'
          + UI.table(['Finding', 'Object', 'Referenced by', { label: 'Size', right: true }, 'Found', { label: '', right: true }], findings.map((f) => [UI.pill(f.finding, fKind(f.finding)), '<span class="mono" style="font-size:12px">' + esc(f.object) + '</span>', esc(f.referencedBy), '<span class="num">' + esc(f.size) + '</span>', esc(f.found), f.finding === 'orphan' ? UI.btn('Delete', { size: 'xs', kind: 'ghost', attrs: 'data-delorphan="' + esc(f.id) + '"' }) : f.finding === 'missing' ? UI.btn('Restore from backup', { size: 'xs', kind: 'ghost', attrs: 'data-restore' }) : UI.btn('Re-seal from source', { size: 'xs', kind: 'ghost', attrs: 'data-reseal="' + esc(f.id) + '"' })]), { clickable: false, minWidth: '900px', emptyTitle: 'No findings', emptyText: 'The last run found every reference and every object in agreement.' })
          + '<div class="hstack wrap gap6">' + UI.btn(st.dryRun ? 'Delete orphans (confirm)' : 'Delete orphans (dry run)', { size: 'sm', kind: st.dryRun ? 'danger' : undefined, icon: 'trash', attrs: 'data-delorphans', disabled: st.orphansDeleted || !(st.orphansDeleted ? 0 : lv.orphans) }) + UI.btn('Restore missing from backup', { size: 'sm', attrs: 'data-restore', disabled: !lv.missing }) + '<span class="muted" style="font-size:12px">Deleting orphans asks for a reason and is audited as blobs.orphans.deleted (question 10). Restoring opens a drill on Platform.</span></div>';
      }
      // ---------------- Purges ----------------
      if (st.tab === 'purges') {
        body += UI.table(['What', 'Policy set in', 'Job', 'Period', 'Last run', 'Removed', 'Next run'], PURGES.map((p, i) => ['<span style="font-weight:600">' + esc(p.what) + '</span><div class="muted" style="font-size:11px">' + esc(p.policy) + '</div>', '<a href="#" data-purgewhere="' + i + '">' + esc(p.where[2]) + '</a>', '<span class="mono">' + esc(p.job) + '</span>', esc(p.period), esc(p.last), esc(p.removed), esc(p.next)]), { clickable: false, minWidth: '1000px' })
          + UI.notice('Purges run as scheduled jobs on every active tenant. Changing a period means changing the setting named in the row; the policy itself (how long to keep things) is set where the row links. Jobs and queues › Schedules runs one now.', 'info', UI.btn('Open Schedules', { size: 'xs', attrs: 'data-goschedules' }));
      }

      root.innerHTML = '<div class="page">' + UI.pagehead('Storage', 'Blob stores, usage against quotas, quarantine, integrity and purges', UI.btn('Run integrity check', { attrs: 'data-runverify', disabled: !!st.verify }) + UI.btn('Set a workspace quota', { kind: 'primary', attrs: 'data-quota="' + esc(st.selUsage) + '"' })) + tabs + body + '</div>' + (insp ? '<aside class="inspector w360">' + insp + '</aside>' : '');

      // ---- handlers ----
      ctx.on('click', '[data-tab]', (e, t) => { st.tab = t.dataset.tab; ctx.rerender(); });
      ctx.on('click', '[data-tab-go]', (e, t) => { st.tab = t.dataset.tabGo; ctx.rerender(); });
      ctx.on('click', 'tr[data-store]', (e, t) => { st.sel = t.dataset.store; ctx.rerender(); });
      ctx.on('click', 'tr[data-usage]', (e, t) => { st.selUsage = t.dataset.usage; ctx.rerender(); });
      ctx.on('click', 'tr[data-q]', (e, t) => { st.selQ = t.dataset.q; ctx.rerender(); });
      ctx.on('click', '[data-usageby]', (e, t) => { const b = e.target.closest('[data-seg]'); if (b) { st.usageBy = b.dataset.seg; ctx.rerender(); } });
      ctx.on('input', '[data-qsearch] input', (e, t) => { st.qQuery = t.value; const rows = st.quarantine.filter((x) => (st.qState === 'all' || x.state === st.qState) && (!st.qQuery || (x.object + ' ' + x.workspace + ' ' + x.kind + ' ' + x.by).toLowerCase().includes(st.qQuery.toLowerCase()))); ctx.$$('tr[data-q]').forEach((tr) => { tr.style.display = rows.some((x) => x.id === tr.dataset.q) ? '' : 'none'; }); });
      ctx.on('click', '[data-menu="qstate"]', (e, t) => menu(ctx, t, [['all', 'Any state'], ['scanning', 'scanning'], ['infected', 'infected'], ['type mismatch', 'type mismatch'], ['too large', 'too large'], ['timed out', 'timed out']], st.qState, (v) => { st.qState = v; ctx.rerender(); }));
      ctx.on('click', '[data-setting]', (e, t) => { e.preventDefault(); ctx.navigate('configuration', { q: t.dataset.setting }); });
      ctx.on('click', '[data-link]', (e, t) => { const s = st.stores.find((x) => x.id === t.dataset.link); if (s && s.link) ctx.navigate(s.link[0], s.link[1]); });
      ctx.on('click', '[data-files]', (e, t) => ctx.navigate('files', { workspace: t.dataset.files }));
      ctx.on('click', '[data-goflags]', () => ctx.navigate('flags', { q: 'quarantine' }));
      ctx.on('click', '[data-goaudit]', (e) => { e.preventDefault(); ctx.navigate('usage-audit', { tab: 'audit', q: 'files.' }); });
      ctx.on('click', '[data-goschedules]', () => ctx.navigate('jobs', { tab: 'schedules' }));
      ctx.on('click', '[data-gojob]', (e, t) => ctx.navigate('jobs', { tab: 'jobs', q: t.dataset.gojob }));
      ctx.on('click', '[data-purgewhere]', (e, t) => { e.preventDefault(); const p = PURGES[+t.dataset.purgewhere]; ctx.navigate(p.where[0], p.where[1]); });
      ctx.on('click', '[data-restore]', () => ctx.navigate('platform', { tab: 'backups' }));
      const runVerify = () => ctx.confirm({ title: 'Run verification', tag: 'read only', tone: 'info', body: '<p class="fg2" style="margin:0">Walks every reference and every object in the blob store on api-1 as job ops.blobs.verify. Nothing is changed; the findings replace the table below when it finishes. The last run took ' + esc(st.lastVerify.duration) + '.</p>', kv: [['Store', 'MinIO exprsn-blobs'], ['Objects', st.lastVerify.checked]], ok: 'Start' }).then((ok) => {
        if (!ok) return; st.tab = 'integrity'; st.verify = { job: 'j-' + (41200 + Math.floor(Math.random() * 90)), step: 'listing objects', progress: '0 of 2,104,318' }; ctx.rerender(); ctx.toast('Verification started as ' + esc(st.verify.job) + '.', 'ok');
        setTimeout(() => { if (!st.verify) return; st.verify.step = 'comparing references'; st.verify.progress = '1,380,000 of 2,104,318'; if (st.tab === 'integrity') ctx.rerender(); }, 1200);
        setTimeout(() => { if (!st.verify) return; st.verify = null; st.lastVerify = { at: 'just now', checked: '2,104,402', missing: st.lastVerify.missing, orphans: st.orphansDeleted ? 0 : st.lastVerify.orphans, mismatch: st.lastVerify.mismatch, duration: '39 min' }; st.dryRun = null; if (st.tab === 'integrity') ctx.rerender(); ctx.toast('Verification finished: ' + st.lastVerify.missing + ' missing, ' + st.lastVerify.orphans.toLocaleString('en') + ' orphans, ' + st.lastVerify.mismatch + ' mismatch. Audit event written.', st.lastVerify.missing || st.lastVerify.mismatch ? 'warn' : 'ok', 6000); }, 2600);
      });
      ctx.on('click', '[data-verify],[data-runverify]', runVerify);
      if (st.openVerify) { st.openVerify = false; setTimeout(runVerify, 60); }
      ctx.on('click', '[data-migrate]', () => ctx.modal({ title: 'Migrate to another store ' + UI.pill('proposed', 'outline'), body: '<p class="fg2" style="margin:0">A migration copies every object from the current store to a second one as a job (ops.blobs.migrate), verifying each SHA-256 on arrival, while the current store keeps serving. When the copy is complete and verified, reads switch to the new store and writes follow; the old store is kept read-only until an administrator retires it. Nothing in the console runs this yet; question 16 decides whether it should.</p>' + UI.kv([['From', 'MinIO exprsn-blobs (S3)'], ['To', UI.select(['S3: MinIO exprsn-blobs-2', 'S3: object.northwind.local', 'Filesystem: /mnt/blobs (one instance only)'], 'S3: MinIO exprsn-blobs-2', 'disabled')], ['Objects', '2.1 M, 1.42 TiB'], ['Estimated', 'about 6 h at 70 MB/s']], 2), actions: UI.btn('Close', { attrs: 'data-close' }) + UI.btn('Start migration', { kind: 'primary', disabled: true, title: 'Proposed; not wired' }) }));
      const quota = (id) => { const u = st.usage.find((x) => x.id === id) || st.usage[0]; const t = total(u); ctx.modal({ title: 'Set quota for ' + esc(u.workspace), body: '<p class="fg2" style="margin:0">Applies to files, versions, trash, media, knowledge uploads and attachments in the workspace (B-2403). Above it, uploads are refused with <span class="mono">413</span> and members see the reason in Files.</p>' + UI.field('Quota (GiB)', UI.input(String(u.quota), { type: 'number', attrs: 'data-quotaval min="1"' }), 'Used now: ' + fmt(t) + '.') + UI.notice('A quota below the current use refuses every new upload until space is freed; nothing is deleted.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Save quota', { kind: 'primary', attrs: 'data-savequota' }), onMount(m) { m.querySelector('[data-savequota]').addEventListener('click', () => { const v = +m.querySelector('[data-quotaval]').value; if (!v || v < 1) { App.toast('Enter a quota of at least 1 GiB.', 'warn'); return; } u.quota = v; st.tab = 'usage'; st.usageBy = 'workspace'; st.selUsage = u.id; App.closeOverlay(); ctx.rerender(); ctx.toast(esc(u.workspace) + ' quota set to ' + fmt(v) + (t > v ? '; uploads are refused until use falls below it' : '') + '. Audit event written.', t > v ? 'warn' : 'ok', 5000); }); } }); };
      ctx.on('click', '[data-quota]', (e, t) => quota(t.dataset.quota));
      if (st.openQuota) { st.openQuota = false; setTimeout(() => quota(st.selUsage), 60); }
      ctx.on('click', '[data-rescan]', () => { const q = st.quarantine.find((x) => x.id === st.selQ); if (!q) return; ctx.confirm({ title: 'Rescan ' + esc(q.object), tone: 'info', body: '<p class="fg2" style="margin:0">Runs the type check and ClamAV again on the quarantined bytes. A clean result seals the object into the blob store and releases it; a refusal keeps it here with the new reason.</p>', kv: [['Workspace', esc(q.workspace)], ['Size', esc(q.size)]], ok: 'Rescan' }).then((ok) => { if (!ok) return; const prev = q.state; q.state = 'scanning'; q.age = 'just now'; ctx.rerender(); setTimeout(() => { if (prev === 'timed out') { st.quarantine = st.quarantine.filter((x) => x.id !== q.id); st.selQ = st.quarantine[0] && st.quarantine[0].id; ctx.rerender(); ctx.toast(esc(q.object) + ' is clean and was released to ' + esc(q.workspace) + '. Audit event written.', 'ok', 5000); } else { q.state = prev; q.age = 'just now'; q.detail = q.detail + ' Rescan at 14:1' + Math.floor(Math.random() * 9) + ' gave the same result.'; ctx.rerender(); ctx.toast(esc(q.object) + ' refused again: ' + esc(prev) + '.', 'warn', 5000); } }, 1400); }); });
      ctx.on('click', '[data-qdelete]', () => { const q = st.quarantine.find((x) => x.id === st.selQ); if (!q) return; ctx.confirm({ title: 'Delete ' + esc(q.object), tag: 'destructive', tone: 'danger', body: '<p class="fg2" style="margin:0">Removes the quarantined bytes. Nothing was ever written to the blob store, so no file, message or record changes; the uploader keeps the refusal notice.</p>', kv: [['Workspace', esc(q.workspace)], ['State', esc(q.state)]], ok: 'Delete' }).then((ok) => { if (!ok) return; st.quarantine = st.quarantine.filter((x) => x.id !== q.id); st.selQ = st.quarantine[0] && st.quarantine[0].id; ctx.rerender(); ctx.toast(esc(q.object) + ' deleted from quarantine. Audit event written.', 'ok'); }); });
      ctx.on('click', '[data-delorphans]', () => {
        const n = st.lastVerify.orphans;
        if (!st.dryRun) { st.dryRun = { count: n, size: n > 100 ? '1.9 TiB' : '1.1 GiB', oldest: '12 Aug 2026' }; ctx.rerender(); ctx.toast('Dry run: ' + n.toLocaleString('en') + ' orphans would be deleted. Nothing changed.', '', 4000); return; }
        ctx.confirm({ title: 'Delete ' + n.toLocaleString('en') + ' orphans', tag: 'destructive', tone: 'danger', body: '<p class="fg2" style="margin:0">Deletes every object the dry run listed. They are referenced by nothing, so no file, upload or output changes; the space is freed in the store. The reason goes into the audit chain with the list of objects.</p>' + UI.field('Reason', UI.textarea('', { placeholder: 'Why these objects can go', rows: 2, attrs: 'data-reason' })), kv: [['Objects', n.toLocaleString('en')], ['Size', st.dryRun.size]], ok: 'Delete orphans' }).then((ok) => { if (!ok) return; st.orphansDeleted = true; st.dryRun = null; ctx.rerender(); ctx.toast(n.toLocaleString('en') + ' orphans deleted; ' + (n > 100 ? '1.9 TiB' : '1.1 GiB') + ' freed. Audit event blobs.orphans.deleted written.', 'ok', 5000); });
      });
      ctx.on('click', '[data-delorphan]', (e, t) => { const f = st.findings.find((x) => x.id === t.dataset.delorphan); if (!f) return; ctx.confirm({ title: 'Delete orphan', tag: 'destructive', tone: 'danger', body: '<p class="fg2" style="margin:0">Deletes this one object. ' + esc(f.referencedBy) + '.</p>' + UI.field('Reason', UI.textarea('', { placeholder: 'Why this object can go', rows: 2 })), kv: [['Object', '<span class="mono">' + esc(f.object) + '</span>'], ['Size', esc(f.size)]], ok: 'Delete' }).then((ok) => { if (!ok) return; st.findings = st.findings.filter((x) => x.id !== f.id); st.lastVerify.orphans = Math.max(0, st.lastVerify.orphans - 1); ctx.rerender(); ctx.toast('Orphan deleted, ' + esc(f.size) + ' freed. Audit event written.', 'ok'); }); });
      ctx.on('click', '[data-reseal]', (e, t) => { const f = st.findings.find((x) => x.id === t.dataset.reseal); if (!f) return; ctx.confirm({ title: 'Re-seal from source', tone: 'info', body: '<p class="fg2" style="margin:0">Reads the original (the generation job kept its input) and writes a fresh sealed object; the mismatching one is kept aside until the new checksum verifies.</p>', kv: [['Object', '<span class="mono">' + esc(f.object) + '</span>'], ['Referenced by', esc(f.referencedBy)]], ok: 'Re-seal' }).then((ok) => { if (!ok) return; st.findings = st.findings.filter((x) => x.id !== f.id); st.lastVerify.mismatch = Math.max(0, st.lastVerify.mismatch - 1); ctx.rerender(); ctx.toast(esc(f.referencedBy) + ' re-sealed; checksum verified.', 'ok'); }); });
    }
  });
  function num(n) { return '<span class="num">' + n + '</span>'; }
})();
