// Generates the runnable prototype from the sources in css/ and js/:
//   index.html         one self-contained application (all CSS and JS embedded)
//   screens/<id>.html  one self-contained page per screen; links between pages work
//   dist/artifact.html the application without the document skeleton (for hosts that add their own)
// The sources stay the place to edit; run `node build.mjs` after changing them.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(root, p), 'utf8');
const js = (p) => '<script>\n' + read(p).replace(/<\/script>/g, '<\\/script>') + '\n</script>';
const shell = read('shell.html');
const screenFiles = [...shell.matchAll(/<script src="(js\/screens\/[^"]+)"><\/script>/g)].map((m) => m[1]).filter((p) => { if (existsSync(join(root, p))) return true; console.warn('missing', p); return false; });
const css = '<style>\n' + read('css/app.css') + '\n</style>';
const head = shell.replace(/<link rel="stylesheet" href="css\/[^"]+">/, () => css).replace(/<script src="js\/app.js"><\/script>/, () => js('js/app.js')).replace(/\s*<!-- screens -->[\s\S]*?<\/body>/, '\n%SCREENS%\n</body>');
const stamp = '<!-- Generated by build.mjs from css/ and js/. Edit the sources, then run: node build.mjs -->\n';

// 1. index.html — everything
const all = head.replace('%SCREENS%', () => screenFiles.map(js).join('\n'));
writeFileSync(join(root, 'index.html'), stamp + all);
console.log('index.html', (all.length / 1024).toFixed(0), 'KB,', screenFiles.length, 'screens');

// 2. screens/<id>.html — one page per screen
mkdirSync(join(root, 'screens'), { recursive: true });
for (const p of screenFiles) {
  const id = basename(p, '.js');
  const page = head.replace('%SCREENS%', () => '<script>App.fileMode = true; App.defaultRoute = ' + JSON.stringify(id) + ';</script>\n' + js(p)).replace(/<title>[^<]*<\/title>/, () => '<title>' + id + ' · Exprsn-AI</title>');
  writeFileSync(join(root, 'screens', id + '.html'), stamp + page);
}
console.log('screens/', screenFiles.map((p) => basename(p, '.js')).join(', '));

// 3. dist/artifact.html — skeleton-free copy for embedding hosts
mkdirSync(join(root, 'dist'), { recursive: true });
const inner = all.replace(/^[\s\S]*?<head>/, '').replace(/<meta[^>]*>\s*/g, '').replace(/<\/head>\s*<body>/, '').replace(/<\/body>\s*<\/html>\s*$/, '');
writeFileSync(join(root, 'dist', 'artifact.html'), inner);
console.log('dist/artifact.html', (inner.length / 1024).toFixed(0), 'KB');
