(function () {
  const { UI, esc } = App;

  const STAGES = ['Dataset', 'Approval', 'Training', 'Evals', 'GGUF convert', 'Registry draft', 'Model admin approval', 'Canary', 'Approved pools'];
  const JOBS = [
    { id: 'finance-lora-v4', desc: 'LoRA on llama3.1:8b, dataset finance-qa v6, seed 1337', base: 'llama3.1:8b-q5_K_M', dataset: 'finance-qa v6', method: 'LoRA r=16, alpha 32', hw: 'cuda, 2 GPUs, 80 GB each', state: 'running', stage: 2, step: 2030, steps: 3500, epoch: '2 of 3', loss: 0.412, gpuHours: 11.4, priority: 'normal, preemptible', deadline: '22 Sep 06:00', checkpoint: 'step 1,750, 4 min ago', started: '20 Sep 22:05', owner: 'Mara Okafor', series: [2.31, 1.74, 1.38, 1.12, 0.97, 0.88, 0.79, 0.71, 0.66, 0.6, 0.57, 0.53, 0.5, 0.47, 0.45, 0.44, 0.43, 0.42, 0.41] },
    { id: 'finance-lora-v3', desc: 'LoRA on llama3.1:8b, dataset finance-qa v5, seed 1337', base: 'llama3.1:8b-q5_K_M', dataset: 'finance-qa v5', method: 'LoRA r=16, alpha 32', hw: 'cuda, 2 GPUs, 80 GB each', state: 'succeeded', stage: 3, stageTone: 'danger', step: 3500, steps: 3500, epoch: '3 of 3', loss: 0.398, gpuHours: 19.8, priority: 'normal, preemptible', deadline: '15 Sep 06:00', checkpoint: 'final, 14 Sep 03:12', started: '13 Sep 22:00', owner: 'Mara Okafor', series: [2.28, 1.7, 1.35, 1.1, 0.95, 0.86, 0.77, 0.7, 0.64, 0.59, 0.55, 0.52, 0.49, 0.46, 0.44, 0.43, 0.41, 0.4, 0.4], evals: [['Finance QA held-out, exact match', '0.612', '0.781', '0.700', 'pass'], ['Regression set against base', '1.000', '0.974', '0.950', 'pass'], ['Guardrail red-team suite', '0.991', '0.968', '0.980', 'fail']], evalNote: 'Registration is blocked until the red-team suite meets its threshold.' },
    { id: 'weekly refresh', desc: 'Recurring, LoRA on llama3.1:8b, dataset feedback-approved v12', base: 'llama3.1:8b-q5_K_M', dataset: 'feedback-approved v12', method: 'LoRA r=8, alpha 16', hw: 'cuda, 1 GPU', state: 'queued', stage: 1, step: 0, steps: 1200, epoch: '0 of 2', loss: null, gpuHours: 0, priority: 'low, preemptible', deadline: '25 Sep 06:00', checkpoint: 'none', started: 'Thu 24 Sep 22:00, if the dataset version changed', owner: 'scheduler', series: [] },
    { id: 'coder-lora-v1', desc: 'QLoRA on qwen2.5-coder:32b, dataset code-reviews v2, seed 7', base: 'qwen2.5-coder:32b-q4_K_M', dataset: 'code-reviews v2', method: 'QLoRA 4-bit, r=32', hw: 'cuda, 2 GPUs, 80 GB each', state: 'failed', stage: 2, stageTone: 'danger', step: 310, steps: 2800, epoch: '1 of 2', loss: 1.21, gpuHours: 2.1, priority: 'normal, preemptible', deadline: '20 Sep 06:00', checkpoint: 'step 250, 18 Sep 23:40', started: '18 Sep 22:00', owner: 'Sam Reyes', series: [2.6, 2.1, 1.8, 1.55, 1.4, 1.3, 1.21], error: 'CUDA out of memory at step 310: 82.1 GB requested on an 80 GB device. Reduce sequence length or micro-batch, or request 4 GPUs.' },
    { id: 'guard-tune-v2', desc: 'LoRA on llama-guard3:8b, dataset flag-decisions v3, seed 42', base: 'llama-guard3:8b', dataset: 'flag-decisions v3', method: 'LoRA r=8, alpha 16', hw: 'cuda, 1 GPU', state: 'preempted', stage: 2, step: 640, steps: 1600, epoch: '1 of 2', loss: 0.71, gpuHours: 3.4, priority: 'low, preemptible', deadline: '23 Sep 06:00', checkpoint: 'step 640, 19 Sep 05:41', started: '19 Sep 22:00', owner: 'Mara Okafor', series: [1.9, 1.5, 1.2, 1.0, 0.88, 0.8, 0.74, 0.71], note: 'Checkpointed at step 640 when the 06:00 window closed. Resumes from the checkpoint in the next window, not from zero.' },
    { id: 'sales-summaries-v2', desc: 'LoRA on llama3.2:3b, dataset sales-notes v1, seed 1337', base: 'llama3.2:3b-q8_0', dataset: 'sales-notes v1', method: 'LoRA r=8, alpha 16', hw: 'cuda, 1 GPU', state: 'cancelled', stage: 2, step: 900, steps: 2000, epoch: '1 of 2', loss: 0.92, gpuHours: 1.6, priority: 'low, preemptible', deadline: '18 Sep 06:00', checkpoint: 'step 900, 17 Sep 00:30', started: '16 Sep 22:00', owner: 'Sam Reyes', series: [2.2, 1.7, 1.4, 1.2, 1.05, 0.98, 0.92], note: 'Cancelled by the owner at step 900: the dataset was withdrawn after a PII scrub finding.' }
  ];
  const DATASETS = [
    { id: 'finance-qa', ver: 'v6', rows: '18,420', label: 'confidential', source: 'Finance KB Q&A pairs, conversation opt-in (Finance Ops)', pii: '412 masked, report attached', hash: 'sha256:8e3f2a…', splits: '80 / 10 / 10', used: 'finance-lora-v4' },
    { id: 'finance-qa', ver: 'v5', rows: '16,900', label: 'confidential', source: 'Finance KB Q&A pairs', pii: '380 masked', hash: 'sha256:51c0d9…', splits: '80 / 10 / 10', used: 'finance-lora-v3' },
    { id: 'feedback-approved', ver: 'v12', rows: '4,210', label: 'internal', source: 'Ratings and corrections approved by reviewers', pii: '12 masked', hash: 'sha256:c7a41e…', splits: '90 / 5 / 5', used: 'weekly refresh' },
    { id: 'code-reviews', ver: 'v2', rows: '9,880', label: 'internal', source: 'gitlab-onprem merge request comments', pii: '0 masked, emails stripped at source', hash: 'sha256:2b9e70…', splits: '80 / 10 / 10', used: 'coder-lora-v1' },
    { id: 'flag-decisions', ver: 'v3', rows: '2,140', label: 'restricted', source: 'Reviewer decisions from the flag queue', pii: '96 masked', hash: 'sha256:f04d88…', splits: '80 / 10 / 10', used: 'guard-tune-v2' },
    { id: 'sales-notes', ver: 'v1', rows: '6,300', label: 'internal', source: 'Field Sales call notes', pii: 'withdrawn: 1,204 unmasked names found', hash: 'sha256:9a17bc…', splits: '80 / 10 / 10', used: 'sales-summaries-v2 (cancelled)', withdrawn: true }
  ];
  const EVALS = [
    ['finance-lora-v3:8b', 'cuda', 'Finance QA held-out', '0.781', '0.700', 'pass'], ['finance-lora-v3:8b', 'cuda', 'Regression against base', '0.974', '0.950', 'pass'], ['finance-lora-v3:8b', 'cuda', 'Guardrail red-team', '0.968', '0.980', 'fail'],
    ['qwen2.5-coder:32b-q4_K_M', 'cuda', 'Tool-calling conformance', '41 of 44', '44 of 44', 'fail'], ['qwen2.5-coder:32b-q4_K_M', 'cpu', 'Tool-calling conformance', '41 of 44', '44 of 44', 'fail'], ['qwen2.5-coder:32b-q4_K_M', 'cuda', 'HumanEval subset', '0.71', '0.65', 'pass'],
    ['qwen2.5:32b-q4_K_M', 'rocm', 'Regression against cuda output', '0.996', '0.990', 'pass'], ['llama3.1:8b-q5_K_M', 'cpu', 'Guardrail red-team', '0.991', '0.980', 'pass']
  ];

  App.register({
    id: 'training', title: 'Training', summary: 'Datasets, LoRA and QLoRA jobs, evals, GGUF packaging, windows and canary rollout', section: 'admin', crumb: ['Admin', 'Training'],
    commands: [{ label: 'New training job', sub: 'Training', run(app) { app.stateFor('training').openNew = true; app.render(); } }],
    states: [
      { title: 'Preempted and resumed', tone: 'info', text: 'The job was preempted at step 1,750 for interactive load and resumed from the checkpoint, not from zero.', apply(ctx) { ctx.state.tab = 'jobs'; ctx.state.selected = 'finance-lora-v4'; ctx.state.preempted = true; ctx.rerender(); } },
      { title: 'Approval required', tone: 'warn', text: 'The dataset is confidential, so the job waits for an ML admin approval before training starts.', apply(ctx) { ctx.state.tab = 'jobs'; ctx.state.awaiting = true; ctx.state.selected = 'finance-lora-v5'; ctx.rerender(); } },
      { title: 'Eval below threshold', tone: 'danger', text: 'The pipeline stops before registration. The model card records the failing suite.', apply(ctx) { ctx.state.tab = 'jobs'; ctx.state.selected = 'finance-lora-v3'; ctx.rerender(); } },
      { title: 'Window closing', tone: 'neutral', text: '20 minutes before 06:00 the job checkpoints and the gateway reloads pinned models.', apply(ctx) { ctx.state.tab = 'jobs'; ctx.state.selected = 'finance-lora-v4'; ctx.state.windowClosing = true; ctx.rerender(); } }
    ],
    render(root, ctx) {
      const st = ctx.state;
      st.tab = st.tab || 'jobs'; st.selected = st.selected || 'finance-lora-v4'; st.query = st.query || ''; st.stateFilter = st.stateFilter || 'all';
      st.jobs = st.jobs || JSON.parse(JSON.stringify(JOBS)); st.recurring = st.recurring || [{ name: 'weekly refresh', cron: 'Thu 22:00 (0 22 * * 4)', cond: 'only when feedback-approved has a new version', next: '24 Sep 22:00', on: true }];
      st.windows = st.windows || [{ name: 'nights', pool: 'gpu-large-2', when: 'daily 22:00 to 06:00', effect: 'lent to train-1; drained first, pinned models reloaded at 05:40' }, { name: 'weekends', pool: 'gpu-large-2', when: 'Sat 22:00 to Mon 06:00', effect: 'lent to train-1' }, { name: 'dedicated', pool: 'train-1', when: 'always', effect: '4 GPUs reserved for training, Kueue ClusterQueue northwind-train' }];
      if (st.awaiting && !st.jobs.find((j) => j.id === 'finance-lora-v5')) st.jobs.unshift({ id: 'finance-lora-v5', desc: 'LoRA on llama3.1:8b, dataset finance-qa v6, seed 2026', base: 'llama3.1:8b-q5_K_M', dataset: 'finance-qa v6', method: 'LoRA r=16, alpha 32', hw: 'cuda, 2 GPUs, 80 GB each', state: 'queued', stage: 1, step: 0, steps: 3500, epoch: '0 of 3', loss: null, gpuHours: 0, priority: 'normal, preemptible', deadline: '24 Sep 06:00', checkpoint: 'none', started: 'waits for approval', owner: 'Mara Okafor', series: [], awaiting: true });
      const jobs = st.jobs;
      const q = st.query.toLowerCase();
      const rows = jobs.filter((j) => (!q || (j.id + ' ' + j.desc).toLowerCase().includes(q)) && (st.stateFilter === 'all' || j.state === st.stateFilter));
      const job = jobs.find((j) => j.id === st.selected) || jobs[0];
      const counts = {}; jobs.forEach((j) => { counts[j.state] = (counts[j.state] || 0) + 1; });

      const chart = (series) => {
        if (!series.length) return '<div class="muted" style="font-size:12px;padding:8px 0">No steps recorded yet.</div>';
        const w = 600, h = 110, pad = 6; const max = Math.max.apply(null, series), min = 0;
        const pts = series.map((v, i) => [pad + (i / Math.max(1, series.length - 1)) * (w - pad * 2), pad + (1 - (v - min) / (max - min || 1)) * (h - pad * 2)]);
        return '<svg viewBox="0 0 ' + w + ' ' + h + '" width="100%" height="110" preserveAspectRatio="none" aria-label="Training loss">' + [0.25, 0.5, 0.75].map((g) => '<line x1="0" x2="' + w + '" y1="' + (pad + g * (h - pad * 2)) + '" y2="' + (pad + g * (h - pad * 2)) + '" stroke="var(--line2)" stroke-width="1"/>').join('') + '<polyline fill="none" stroke="var(--accent)" stroke-width="2" vector-effect="non-scaling-stroke" points="' + pts.map((p) => p[0].toFixed(1) + ',' + p[1].toFixed(1)).join(' ') + '"/><circle cx="' + pts[pts.length - 1][0].toFixed(1) + '" cy="' + pts[pts.length - 1][1].toFixed(1) + '" r="3" fill="var(--accent)"/></svg>'
          + '<div class="hstack muted" style="font-size:11px;justify-content:space-between"><span>step 0, loss ' + series[0].toFixed(2) + '</span><span>step ' + (series.length === 19 ? '2,030' : String(series.length * 100)) + ', loss ' + series[series.length - 1].toFixed(3) + '</span></div>';
      };
      const stepper = (j) => '<div class="training-stages">' + STAGES.map((s, i) => { const cls = i < j.stage ? 'done' : i === j.stage ? 'cur ' + (j.stageTone || '') : ''; return '<div class="' + cls + '"><i></i><span>' + esc(s) + '</span></div>'; }).join('') + '</div>';
      const stateKind = (s) => ({ running: 'info', succeeded: 'ok', failed: 'danger', cancelled: '', preempted: 'warn', queued: 'outline' }[s] || '');

      const jobActions = (j) => {
        if (j.state === 'running') return UI.btn('Pause', { size: 'sm', attrs: 'data-pause' }) + UI.btn('Cancel', { size: 'sm', kind: 'ghost', attrs: 'data-canceljob' });
        if (j.state === 'queued' && j.awaiting) return UI.btn('Approve to start', { size: 'sm', kind: 'primary', attrs: 'data-approvejob' }) + UI.btn('Cancel', { size: 'sm', kind: 'ghost', attrs: 'data-canceljob' });
        if (j.state === 'queued' || j.state === 'preempted') return UI.btn(j.state === 'preempted' ? 'Resume now' : 'Run now', { size: 'sm', attrs: 'data-resume' }) + UI.btn('Cancel', { size: 'sm', kind: 'ghost', attrs: 'data-canceljob' });
        if (j.state === 'failed' || j.state === 'cancelled') return UI.btn('Retry from checkpoint', { size: 'sm', attrs: 'data-retry' });
        if (j.state === 'succeeded') return UI.btn('Model card', { size: 'sm', attrs: 'data-card' }) + UI.btn('Re-run evals', { size: 'sm', attrs: 'data-rerun' });
        return '';
      };
      const jobNotices = (j) => {
        let h = '';
        if (j.awaiting) h += UI.notice('<b>Approval required.</b> Dataset finance-qa v6 is confidential, so the job waits for an ML admin approval before training starts. GPUs are not reserved until then.', 'warn');
        if (j.error) h += UI.problem('Training failed', j.error, '9d2c7b1e4f0a3c5e8b6d1f2a4c7e9b0d');
        if (j.note) h += UI.notice(esc(j.note), j.state === 'preempted' ? 'info' : '');
        if (j.evalNote) h += UI.notice('<b>Eval below threshold.</b> The pipeline stopped before registration: guardrail red-team suite 0.968 against a threshold of 0.980. The model card records the failing suite.', 'danger', UI.btn('Model card', { size: 'sm', attrs: 'data-card' }));
        if (st.preempted && j.id === 'finance-lora-v4') h += UI.notice('<b>Preempted and resumed.</b> Preempted at step 1,750 at 21:40 for interactive load on gpu-large-2, resumed from the MinIO checkpoint at 22:05, not from zero. 4 minutes of compute were lost.', 'info', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clear="preempted"' }));
        if (st.windowClosing && j.id === 'finance-lora-v4') h += UI.notice('<b>Window closing, 05:40.</b> 20 minutes before 06:00 the job checkpoints to MinIO and the gateway reloads pinned models on gpu-large-2. The job resumes in the next window.', '', UI.btn('Dismiss', { kind: 'ghost', size: 'sm', attrs: 'data-clear="windowClosing"' })).replace('class="notice "', 'class="notice accent"');
        return h;
      };

      let body = '';
      if (st.tab === 'jobs') {
        const pct = job.steps ? Math.round((job.step / job.steps) * 100) : 0;
        body = '<div class="toolbar">' + UI.search('Filter jobs', 'data-search', st.query) + UI.seg([{ id: 'all', label: 'All ' + jobs.length }].concat(['queued', 'running', 'succeeded', 'failed', 'cancelled', 'preempted'].map((s) => ({ id: s, label: s + (counts[s] ? ' ' + counts[s] : '') }))), st.stateFilter, 'data-segs') + '</div>'
          + UI.table(['Job', 'Base', 'Dataset', 'Hardware', 'State', { label: 'Progress', width: '150px' }, 'Started'], rows.map((j) => ({ cells: ['<b>' + esc(j.id) + '</b><div class="muted" style="font-size:11px">' + esc(j.method) + '</div>', '<span class="mono">' + esc(j.base) + '</span>', esc(j.dataset), esc(j.hw), UI.pill(j.state, stateKind(j.state)), '<div class="meter ' + (j.state === 'failed' ? 'danger' : j.state === 'running' ? 'accent' : '') + '" style="min-width:120px"><div class="mrow"><span></span><span class="num">' + (j.steps ? Math.round((j.step / j.steps) * 100) : 0) + '%</span></div><div class="track"><div class="fill" style="width:' + (j.steps ? (j.step / j.steps) * 100 : 0) + '%"></div></div></div>', esc(j.started)], selected: j.id === job.id, attrs: 'data-job="' + esc(j.id) + '"' })), { emptyTitle: 'No jobs match', emptyText: 'Clear the filter or submit a job.' })
          + UI.panel(null, '<div class="hstack wrap" style="align-items:flex-start"><div class="vstack grow" style="gap:2px"><span style="font-size:15px;font-weight:600">' + esc(job.id) + '</span><span class="muted" style="font-size:12px">' + esc(job.desc) + '</span></div><div class="hstack gap6">' + UI.pill(job.state, stateKind(job.state)) + jobActions(job) + '</div></div>'
            + stepper(job)
            + jobNotices(job)
            + '<div class="grid3">' + UI.meter('Steps', job.step.toLocaleString('en-GB') + ' of ' + job.steps.toLocaleString('en-GB'), pct, job.state === 'failed' ? 'danger' : 'accent') + UI.meter('Epoch', job.epoch, (parseInt(job.epoch, 10) / (parseInt(job.epoch.split('of ')[1], 10) || 1)) * 100) + UI.meter('GPU-hours used', job.gpuHours + ' of ' + (job.hw.includes('2 GPUs') ? '24' : '12') + ' max', (job.gpuHours / (job.hw.includes('2 GPUs') ? 24 : 12)) * 100, job.gpuHours > 20 ? 'warn' : '') + '</div>'
            + '<div class="eyebrow">Training loss</div>' + chart(job.series)
            + UI.kv([['Priority', esc(job.priority)], ['Hardware', esc(job.hw)], ['Deadline', esc(job.deadline)], ['Last checkpoint', esc(job.checkpoint)]], 4)
            + '<div class="hstack wrap muted" style="font-size:12px;gap:12px"><span>Owner ' + esc(job.owner) + '</span><span>Tenant Northwind</span><span>Container <span class="mono">trainer:2026.09.1, sha256:5be0…</span></span><span>Progress streams on <span class="mono">train.progress</span></span><span class="right"><a href="#" data-go="pools">Pool health</a></span></div>');
      } else if (st.tab === 'datasets') {
        body = '<div class="toolbar">' + UI.search('Filter datasets', 'data-search', st.query) + '<span class="right">' + UI.btn('Register dataset version', { attrs: 'data-newds' }) + '</span></div>'
          + UI.table(['Dataset', 'Version', 'Rows', 'Label', 'Source', 'PII scrub', 'Hash', 'Used by'], DATASETS.filter((d) => !q || (d.id + ' ' + d.source).toLowerCase().includes(q)).map((d, i) => ({ cells: ['<b>' + esc(d.id) + '</b>', esc(d.ver), esc(d.rows), UI.label(d.label, { sm: true }), esc(d.source), d.withdrawn ? '<span style="color:var(--danger-fg)">' + esc(d.pii) + '</span>' : esc(d.pii), '<span class="mono">' + esc(d.hash) + '</span>', esc(d.used)], attrs: 'data-ds="' + i + '"' })))
          + UI.notice('Datasets are versioned in MinIO with a manifest: row count, hash, label, source and PII-scrub report. Conversation data enters only with tenant opt-in and at or below the target model\'s label ceiling.', 'info');
      } else if (st.tab === 'schedules') {
        const cal = (label, cells) => '<div class="training-cal"><span style="font-size:12px;font-weight:600">' + esc(label) + '</span>' + cells.map((c) => '<div class="cell">' + (c ? '<div class="ev ' + (c[1] || '') + '">' + esc(c[0]) + '</div>' : '') + '</div>').join('') + '</div>';
        body = UI.panel('GPU calendar, week of 21 Sep', '<div class="training-cal head"><span></span>' + ['Mon 21', 'Tue 22', 'Wed 23', 'Thu 24', 'Fri 25', 'Sat 26', 'Sun 27'].map((d) => '<span>' + d + '</span>').join('') + '</div>'
          + cal('train-1', [['finance-lora-v4', 'hot'], ['finance-lora-v4', 'hot'], null, [st.recurring[0].on ? 'weekly refresh' : 'weekly refresh, paused', ''], null, st.windows.length > 3 ? ['new window', ''] : null, null])
          + cal('gpu-large-2', [['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', ''], ['lent 22:00 to 06:00', '']])
          + '<span class="muted" style="font-size:12px">Inference GPUs lent to training are drained first and pinned models are reloaded before the window closes.</span>')
          + '<div class="grid2">'
          + UI.panel('Training windows', UI.table(['Window', 'Pool', 'When', 'Effect'], st.windows.map((w) => [esc(w.name), '<a href="#" data-go="pools">' + esc(w.pool) + '</a>', esc(w.when), esc(w.effect)]), { clickable: false, minWidth: '0' }), { actions: UI.btn('Add window', { size: 'sm', attrs: 'data-addwindow' }) })
          + UI.panel('Recurring jobs', UI.table(['Schedule', 'Cron', 'Condition', 'Next run', ''], st.recurring.map((r, i) => [esc(r.name), '<span class="mono">' + esc(r.cron) + '</span>', esc(r.cond), esc(r.next), UI.toggle(r.on ? 'on' : 'off', r.on, 'data-manual data-rec="' + i + '"')]), { clickable: false, minWidth: '0' }) + '<div class="muted" style="font-size:12px">Queued jobs are ordered by priority, then by each tenant\'s GPU-hour usage. Kueue ClusterQueues with borrowing on Kubernetes; on Compose the scheduler assigns hosts itself.</div>', { actions: UI.btn('Schedule recurring', { size: 'sm', attrs: 'data-recurring' }) })
          + '</div>';
      } else {
        body = '<div class="toolbar">' + UI.search('Filter evals', 'data-search', st.query) + '<span class="right">' + UI.btn('Run evals', { attrs: 'data-runevals' }) + '</span></div>'
          + UI.table(['Model', 'Hardware class', 'Suite', 'Score', 'Threshold', 'Result'], EVALS.filter((e) => !q || (e[0] + ' ' + e[2]).toLowerCase().includes(q)).map((e) => ['<span class="mono">' + esc(e[0]) + '</span>', esc(e[1]), esc(e[2]), esc(e[3]), esc(e[4]), UI.pill(e[5], e[5] === 'pass' ? 'ok' : 'danger')]), { clickable: false })
          + UI.notice('Evals run per hardware class, because quantized kernels can produce slightly different outputs across backends. Pass thresholds are set per tenant; a failing suite stops the pipeline before registration.', 'info');
      }

      const evalJob = job.evals ? job : jobs.find((j) => j.evals);
      const ds = DATASETS.find((d) => (d.id + ' ' + d.ver) === job.dataset) || DATASETS[0];
      const inspector = '<aside class="inspector w360 training-side">'
        + UI.panel('Evals for ' + evalJob.id, (job.evals ? '' : '<div class="muted" style="font-size:12px">' + esc(job.id) + ' has not reached evals. Showing the previous version of the lineage.</div>') + UI.table(['Eval', 'Base', 'This model', 'Threshold', 'Result'], evalJob.evals.map((e) => [esc(e[0]), esc(e[1]), esc(e[2]), esc(e[3]), UI.pill(e[4], e[4] === 'pass' ? 'ok' : 'danger')]), { clickable: false, cls: 'bare', minWidth: '0', attrs: 'style="font-size:12px"' }) + '<span class="muted" style="font-size:12px">' + esc(evalJob.evalNote) + '</span>', { cls: 'pad-sm' })
        + UI.panel('GPU-hours, Northwind, September', UI.meter('Used', '136 of 200', 68) + '<span class="muted" style="font-size:12px">Fair share: queued jobs are ordered by priority, then by usage against this quota.</span>')
        + UI.panel('Dataset ' + ds.id + ' ' + ds.ver, UI.kv([['Rows', esc(ds.rows)], ['Label', UI.label(ds.label, { sm: true })], ['PII scrub', esc(ds.pii)], ['Splits', esc(ds.splits)]], 2) + '<div>' + UI.btn('Manifest', { size: 'sm', attrs: 'data-ds="' + DATASETS.indexOf(ds) + '"' }) + '</div>')
        + '</aside>';

      root.innerHTML = '<style>'
        + '.training-stages{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:6px}.training-stages > div{display:flex;flex-direction:column;gap:5px;font-size:11px;color:var(--muted);font-weight:500}.training-stages i{display:block;height:4px;border-radius:2px;background:var(--line)}.training-stages .done{color:var(--fg)}.training-stages .done i{background:var(--ok-fg)}.training-stages .cur{color:var(--fg);font-weight:700}.training-stages .cur i{background:var(--accent)}.training-stages .cur.danger i{background:var(--danger-fg)}'
        + '.training-cal{display:grid;grid-template-columns:120px repeat(7,minmax(0,1fr));gap:4px;align-items:center}.training-cal.head{font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}.training-cal .cell{height:30px;border-left:1px solid var(--line2);padding:3px 3px 3px 4px}.training-cal .ev{height:24px;display:flex;align-items:center;padding:0 6px;border-radius:4px;background:var(--sel);color:var(--fg2);font-size:11px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.training-cal .ev.hot{background:var(--accent-tint);color:var(--accent)}'
        + '.training-side.inspector{width:420px}.training-side .panel{padding:12px}.training-side table.dt th,.training-side table.dt td{padding:5px 6px;font-size:12px}.training-side table.dt th{white-space:normal}@media (max-width:1100px){.training-side.inspector{width:320px}}@media (max-width:900px){.training-side.inspector{width:100%}}'
        + '</style>'
        + '<div class="page">'
        + UI.pagehead('Training', 'TypeScript orchestrates and governs, Python GPU workers train, Ollama serves only the approved, converted result', UI.btn('Schedule recurring', { attrs: 'data-recurring' }) + UI.btn('Submit job', { kind: 'primary', attrs: 'data-newjob' }))
        + UI.tabs([{ id: 'jobs', label: 'Jobs', count: jobs.length }, { id: 'datasets', label: 'Datasets', count: DATASETS.length }, { id: 'schedules', label: 'Schedules' }, { id: 'evals', label: 'Evals', count: EVALS.length }], st.tab)
        + body
        + '<div><div class="eyebrow" style="margin-bottom:8px">States to design from this page</div>' + UI.states(this.states) + '</div>'
        + '</div>' + inspector;

      // ---- events ----
      ctx.on('click', '.tabs [data-tab]', (e, t) => { st.tab = t.dataset.tab; st.query = ''; ctx.rerender(); });
      ctx.on('click', '[data-segs] [data-seg]', (e, t) => { st.stateFilter = t.dataset.seg; ctx.rerender(); });
      ctx.on('input', '[data-search]', (e, t) => { st.query = t.value; const v = t.value; ctx.rerender(); const i = ctx.$('[data-search]'); i.focus(); i.setSelectionRange(v.length, v.length); });
      ctx.on('click', 'tr.row[data-job]', (e, t) => { st.selected = t.dataset.job; ctx.rerender(); });
      ctx.on('click', '.state-card', (e, t) => ctx.app.applyState(+t.dataset.state));
      ctx.on('click', '[data-go]', (e, t) => { e.preventDefault(); ctx.navigate(t.dataset.go); });
      ctx.on('click', '[data-clear]', (e, t) => { st[t.dataset.clear] = false; ctx.rerender(); });
      ctx.on('click', '[data-rec]', (e, t) => { const r = st.recurring[+t.dataset.rec]; r.on = !r.on; ctx.rerender(); ctx.toast(esc(r.name) + (r.on ? ' enabled.' : ' paused; the next run is skipped.')); });

      ctx.on('click', '[data-pause]', async () => {
        const ok = await ctx.confirm({ title: 'Pause ' + job.id, tag: 'checkpoint', tone: 'warn', body: '<p style="margin:0" class="fg2">The trainer checkpoints to MinIO at the current step and releases both GPUs. The job returns to the queue and resumes from that checkpoint when you run it again.</p>', kv: [['Current step', job.step.toLocaleString('en-GB')], ['GPUs released', '2 on train-1']], ok: 'Pause' });
        if (!ok) return; job.state = 'queued'; job.checkpoint = 'step ' + job.step.toLocaleString('en-GB') + ', just now'; job.note = 'Paused by Mara Okafor at step ' + job.step.toLocaleString('en-GB') + '. Resumes from the checkpoint.'; ctx.rerender(); ctx.toast('<b>' + esc(job.id) + '</b> checkpointed and paused. GPUs released.', 'warn');
      });
      ctx.on('click', '[data-resume]', async () => {
        const ok = await ctx.confirm({ title: (job.state === 'preempted' ? 'Resume ' : 'Run ') + job.id + ' now', tag: 'outside window', tone: 'info', body: '<p style="margin:0" class="fg2">Runs on train-1 now instead of waiting for the next window. Resumes from ' + esc(job.checkpoint) + '. Interactive load can still preempt it.</p>', ok: job.state === 'preempted' ? 'Resume' : 'Run now' });
        if (!ok) return; job.state = 'running'; job.note = null; job.awaiting = false; job.started = 'today, ' + new Date().toTimeString().slice(0, 5); ctx.rerender(); ctx.toast('<b>' + esc(job.id) + '</b> running on train-1 from ' + esc(job.checkpoint) + '.', 'ok');
      });
      ctx.on('click', '[data-approvejob]', async () => {
        const ok = await ctx.confirm({ title: 'Approve ' + job.id + ' to train on confidential data', tag: 'ML admin', tone: 'ok', body: '<p style="margin:0" class="fg2">finance-qa v6 is confidential. Approval records your decision on the model card; the resulting model inherits a confidential ceiling and can only serve profiles at or above it.</p>', kv: [['Dataset', 'finance-qa v6, 18,420 rows'], ['PII scrub', '412 masked, report attached'], ['Tenant opt-in', 'Finance Ops, yes']], ok: 'Approve' });
        if (!ok) return; job.awaiting = false; job.state = 'queued'; job.started = 'next window, 22:00'; job.note = 'Approved by Mara Okafor. Queued for the 22:00 window on train-1.'; st.awaiting = false; ctx.rerender(); ctx.toast('<b>' + esc(job.id) + '</b> approved and queued.', 'ok');
      });
      ctx.on('click', '[data-canceljob]', async () => {
        const ok = await ctx.confirm({ title: 'Cancel ' + job.id, tag: 'destructive', tone: 'danger', body: '<p style="margin:0" class="fg2">The trainer stops after the current step and keeps the last checkpoint. GPU-hours used so far count against the tenant quota.</p>', ok: 'Cancel job' });
        if (!ok) return; job.state = 'cancelled'; job.note = 'Cancelled by Mara Okafor at step ' + job.step.toLocaleString('en-GB') + '.'; ctx.rerender(); ctx.toast('<b>' + esc(job.id) + '</b> cancelled.', '');
      });
      ctx.on('click', '[data-retry]', async () => {
        const ok = await ctx.confirm({ title: 'Retry ' + job.id + ' from checkpoint', tag: 'requeue', tone: 'info', body: '<p style="margin:0" class="fg2">Requeues with the same dataset version, seed and container. Resumes from ' + esc(job.checkpoint) + '.</p>' + (job.error ? UI.field('Change before retry', UI.select(['Request 4 GPUs', 'Halve micro-batch', 'Reduce sequence length to 4,096', 'No change'], 'Request 4 GPUs')) : ''), ok: 'Requeue' });
        if (!ok) return; const oom = !!job.error; job.state = 'queued'; job.error = null; job.note = 'Requeued from ' + job.checkpoint + (oom ? ' with 4 GPUs requested.' : '.'); if (oom) job.hw = 'cuda, 4 GPUs, 80 GB each'; job.started = 'next window, 22:00'; ctx.rerender(); ctx.toast('<b>' + esc(job.id) + '</b> requeued for the next window.', 'ok');
      });
      ctx.on('click', '[data-rerun]', () => ctx.toast('Red-team suite requeued for finance-lora-v3 on cuda. Result posts to this page and by email.', ''));
      ctx.on('click', '[data-card]', () => ctx.drawer({ title: 'Model card, finance-lora-v3:8b', body: '<div class="hstack">' + UI.pill('draft') + UI.label('confidential', { sm: true }) + UI.pill('registration blocked', 'danger') + '</div>' + UI.kv([['Base digest', '<span class="mono">sha256:7d21e6b0…</span>'], ['Dataset version', 'finance-qa v5, sha256:51c0d9…'], ['Code commit', '<span class="mono">a91f3c2</span>'], ['Container digest', '<span class="mono">sha256:5be0…</span>'], ['Hyperparameters', 'LoRA r=16, alpha 32, lr 2e-4, 3 epochs, seed 1337'], ['Eval scores', 'held-out 0.781, regression 0.974, red-team 0.968 (fail, threshold 0.980)'], ['Packaging', 'GGUF Q4_K_M via llama-quantize'], ['Manifest', 'signed with cosign, key northwind-ml']], 1) + UI.notice('The failing red-team suite is recorded on the card. Fix the dataset or adjust the guardrail set, then re-run evals; registration proceeds automatically on a pass.', 'danger'), actions: UI.btn('Open in Models', { attrs: 'data-close data-models' }) + UI.btn('Close', { kind: 'ghost', attrs: 'data-close' }), onMount(d) { d.querySelector('[data-models]').addEventListener('click', () => ctx.navigate('models', { model: 'finance-lora-v3:8b' })); } }));

      ctx.on('click', '[data-ds]', (e, t) => { const d = DATASETS[+t.dataset.ds]; ctx.drawer({ title: 'Dataset ' + esc(d.id) + ' ' + esc(d.ver), body: '<div class="hstack">' + UI.label(d.label, { sm: true }) + (d.withdrawn ? UI.pill('withdrawn', 'danger') : UI.pill('scrubbed', 'ok')) + '</div>' + UI.kv([['Rows', esc(d.rows)], ['Splits', esc(d.splits)], ['Hash', '<span class="mono">' + esc(d.hash) + '</span>'], ['Source', esc(d.source)], ['PII scrub', esc(d.pii)], ['Used by', esc(d.used)], ['Tenant opt-in', d.label === 'confidential' ? 'Finance Ops, recorded 2 Sep' : 'not required'], ['Stored', 'MinIO datasets/' + esc(d.id) + '/' + esc(d.ver) + '/']], 2) + UI.code('dataset: ' + d.id + '\nversion: ' + d.ver + '\nrows: ' + d.rows.replace(',', '') + '\nlabel: ' + d.label + '\nhash: ' + d.hash + '\nscrub:\n  report: pii-report.json\n  masked: ' + d.pii.split(' ')[0], 'manifest'), actions: UI.btn('Download scrub report', { icon: 'download', attrs: 'data-close data-rep' }) + UI.btn('Close', { kind: 'ghost', attrs: 'data-close' }), onMount(dr) { dr.querySelector('[data-rep]').addEventListener('click', () => ctx.toast('pii-report.json exported. Access logged to audit.')); } }); });
      ctx.on('click', '[data-newds]', () => ctx.modal({ title: 'Register dataset version', body: '<div class="formgrid" style="--cols:2">' + UI.field('Dataset', UI.select(['finance-qa', 'feedback-approved', 'code-reviews', 'new dataset'], 'finance-qa')) + UI.field('Version', UI.input('v7', { attrs: 'class="input mono"' }).replace('class="input" ', '')) + UI.field('Label', UI.select(['public', 'internal', 'confidential', 'restricted'], 'confidential')) + UI.field('Source path in MinIO', UI.input('staging/finance-qa/2026-09-20/')) + '</div>' + UI.check('Tenant opt-in recorded for conversation data', true) + UI.notice('Registration runs the PII scrub and hashes the rows. The version becomes usable in jobs once the scrub report is attached.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Register', { kind: 'primary', attrs: 'data-close data-ok' }), onMount(m) { m.querySelector('[data-ok]').addEventListener('click', () => ctx.toast('finance-qa v7 registered; PII scrub running.', 'ok')); } }));

      const newJob = () => {
        const draw = (dsv) => { const d = DATASETS.find((x) => (x.id + ' ' + x.ver) === dsv) || DATASETS[0]; return d.label === 'confidential' || d.label === 'restricted' ? UI.notice('Dataset ' + esc(d.id + ' ' + d.ver) + ' is ' + esc(d.label) + '. The job waits for an ML admin approval before training starts.', 'warn') : UI.notice('Dataset is ' + esc(d.label) + '; no approval step before training.', 'info'); };
        ctx.modal({ title: 'New training job', cls: 'wide', body: '<div class="formgrid" style="--cols:3">' + UI.field('Name', UI.input('finance-lora-v5', { attrs: 'data-n' })) + UI.field('Base model', UI.select(['llama3.1:8b-q5_K_M, approved', 'qwen2.5:32b-q4_K_M, approved', 'qwen2.5-coder:32b-q4_K_M, evaluated', 'llama-guard3:8b, approved'], 'llama3.1:8b-q5_K_M, approved', 'data-b')) + UI.field('Dataset version', UI.select(DATASETS.filter((d) => !d.withdrawn).map((d) => d.id + ' ' + d.ver), 'finance-qa v6', 'data-d')) + UI.field('Method', UI.select(['LoRA r=16, alpha 32', 'QLoRA 4-bit, r=32', 'Full fine-tune'], 'LoRA r=16, alpha 32')) + UI.field('Trainer', UI.select(['Unsloth', 'Axolotl', 'HF TRL/PEFT'], 'Unsloth')) + UI.field('Hardware class', UI.select(['cuda (default)', 'rocm, optional adapter', 'metal MLX, optional adapter'], 'cuda (default)')) + UI.field('GPUs and memory', UI.select(['1 × 80 GB', '2 × 80 GB', '4 × 80 GB'], '2 × 80 GB')) + UI.field('Max duration', UI.input('8 h')) + UI.field('Deadline', UI.input('2026-09-24T06:00', { type: 'datetime-local' })) + UI.field('Priority', UI.select(['low', 'normal', 'high'], 'normal')) + UI.field('Packaging', UI.select(['GGUF Q4_K_M', 'GGUF Q5_K_M', 'GGUF Q8_0', 'keep LoRA adapter on pinned base'], 'GGUF Q4_K_M')) + UI.field('Canary after approval', UI.select(['10% of traffic', '5% of traffic', 'none, flip directly'], '10% of traffic')) + '</div><div class="hstack wrap gap12">' + UI.check('May be preempted by interactive load', true) + UI.check('Checkpoint every 250 steps', true) + UI.check('Record seed and hyperparameters on the model card', true) + '</div><div id="dsnote">' + draw('finance-qa v6') + '</div>', actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Submit job', { kind: 'primary', attrs: 'data-submit' }), onMount(m) {
          m.querySelector('[data-d]').addEventListener('change', (e) => { m.querySelector('#dsnote').innerHTML = draw(e.target.value); });
          m.querySelector('[data-submit]').addEventListener('click', () => {
            const name = (m.querySelector('[data-n]').value || 'finance-lora-v5').trim(); const dsv = m.querySelector('[data-d]').value; const base = m.querySelector('[data-b]').value.split(',')[0]; const d = DATASETS.find((x) => (x.id + ' ' + x.ver) === dsv);
            const needs = d.label === 'confidential' || d.label === 'restricted'; App.closeOverlay();
            st.jobs.unshift({ id: name, desc: 'LoRA on ' + base.split(':')[0] + ':' + base.split(':')[1].split('-')[0] + ', dataset ' + dsv + ', seed 2026', base, dataset: dsv, method: 'LoRA r=16, alpha 32', hw: 'cuda, 2 GPUs, 80 GB each', state: 'queued', stage: needs ? 1 : 2, step: 0, steps: 3500, epoch: '0 of 3', loss: null, gpuHours: 0, priority: 'normal, preemptible', deadline: '24 Sep 06:00', checkpoint: 'none', started: needs ? 'waits for approval' : 'next window, 22:00', owner: 'Mara Okafor', series: [], awaiting: needs });
            st.selected = name; st.tab = 'jobs'; st.stateFilter = 'all'; ctx.rerender(); ctx.toast('<b>' + esc(name) + '</b> submitted. ' + (needs ? 'Waiting for ML admin approval.' : 'Queued for the 22:00 window on train-1.'), needs ? 'warn' : 'ok', 5000);
          });
        } });
      };
      ctx.on('click', '[data-newjob]', newJob);
      if (st.openNew) { st.openNew = false; setTimeout(newJob, 30); }
      ctx.on('click', '[data-recurring]', () => ctx.modal({ title: 'Schedule recurring job', body: '<div class="formgrid" style="--cols:2">' + UI.field('Name', UI.input('nightly guard refresh', { attrs: 'data-n' })) + UI.field('Job template', UI.select(['guard-tune-v2', 'finance-lora-v4', 'weekly refresh'], 'guard-tune-v2')) + UI.field('Cron', UI.input('0 22 * * *', { attrs: 'data-c class="input mono"' }).replace('class="input" ', '')) + UI.field('Run only when', UI.select(['the input dataset version changed', 'always'], 'the input dataset version changed')) + UI.field('Window', UI.select(['nights, gpu-large-2 lent', 'train-1 dedicated', 'weekends'], 'nights, gpu-large-2 lent')) + UI.field('Priority', UI.select(['low', 'normal'], 'low')) + '</div>' + UI.notice('Each run submits a job with the same spec and the newest dataset version. Evals, packaging and registration as a draft run automatically after it, and the owner is notified.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Schedule', { kind: 'primary', attrs: 'data-ok' }), onMount(m) { m.querySelector('[data-ok]').addEventListener('click', () => { const n = m.querySelector('[data-n]').value || 'nightly guard refresh'; const c = m.querySelector('[data-c]').value || '0 22 * * *'; App.closeOverlay(); st.recurring.push({ name: n, cron: c, cond: 'only when the input dataset version changed', next: '21 Sep 22:00', on: true }); st.tab = 'schedules'; ctx.rerender(); ctx.toast('<b>' + esc(n) + '</b> scheduled. Shown under Schedules.', 'ok'); }); } }));
      ctx.on('click', '[data-addwindow]', () => ctx.modal({ title: 'Add training window', body: '<div class="formgrid" style="--cols:2">' + UI.field('Name', UI.input('saturday full day', { attrs: 'data-n' })) + UI.field('Pool to lend', UI.select(['gpu-large-2', 'gpu-large-1', 'gpu-amd'], 'gpu-large-2')) + UI.field('When', UI.input('Sat 06:00 to 22:00', { attrs: 'data-w' })) + UI.field('Reload pinned models', UI.input('20 min before close', { readonly: true })) + '</div>' + UI.notice('The gateway drains and unloads the pool\'s models when the window opens, and reloads pinned models before it closes. analyst and general-8b keep serving from gpu-large-1.', 'info'), actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Add window', { kind: 'primary', attrs: 'data-ok' }), onMount(m) { m.querySelector('[data-ok]').addEventListener('click', () => { const n = m.querySelector('[data-n]').value || 'saturday full day'; const w = m.querySelector('[data-w]').value || 'Sat 06:00 to 22:00'; App.closeOverlay(); st.windows.push({ name: n, pool: 'gpu-large-2', when: w, effect: 'lent to train-1; drained first, pinned models reloaded 20 min before close' }); ctx.rerender(); ctx.toast('Window <b>' + esc(n) + '</b> added. Kueue quota updated.', 'ok'); }); } }));
      ctx.on('click', '[data-runevals]', () => ctx.modal({ title: 'Run evals', body: '<div class="formgrid" style="--cols:2">' + UI.field('Model version', UI.select(['finance-lora-v3:8b', 'qwen2.5-coder:32b-q4_K_M', 'mistral-small:24b-instruct-q4_K_M'], 'finance-lora-v3:8b')) + UI.field('Hardware classes', UI.input('cuda, cpu')) + '</div><div class="vstack gap4">' + UI.check('Task metrics on the held-out split', true) + UI.check('Regression set against the base model', true) + UI.check('Guardrail red-team suite', true) + UI.check('Tool-calling conformance, 44 cases', false) + '</div>', actions: UI.btn('Cancel', { attrs: 'data-close' }) + UI.btn('Queue evals', { kind: 'primary', attrs: 'data-close data-ok' }), onMount(m) { m.querySelector('[data-ok]').addEventListener('click', () => ctx.toast('Evals queued on train-1, low priority. Results post here and to the model card.', 'ok')); } }));
    }
  });
})();
