/*
 * B-2902: the lexicons the PDS validates records against (generated by server/test/gen-lexicons.ts; do not edit).
 *
 * Source: https://github.com/bluesky-social/atproto/tree/a3bf283c1ae1de683ff04872ff022035d21f9efc/lexicons
 * (MIT or Apache-2.0, at your option), fetched 2026-10-05. Only the record types a Bluesky client writes and the definitions they reach are kept,
 * without descriptions. Regenerate with `npx tsx server/test/gen-lexicons.ts [<commit>]`.
 */
import type { LexiconDoc } from './lexicon.js';

export const LEXICON_SOURCE = 'bluesky-social/atproto@a3bf283c1ae1de683ff04872ff022035d21f9efc';

export const LEXICONS: LexiconDoc[] = [
  {
    "lexicon": 1,
    "id": "app.bsky.actor.contentVisibilityDeclaration",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "required": [
            "hideFromAlgorithmicRecommendations"
          ],
          "properties": {
            "hideFromAlgorithmicRecommendations": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.actor.profile",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "properties": {
            "displayName": {
              "type": "string",
              "maxGraphemes": 64,
              "maxLength": 640
            },
            "pronouns": {
              "type": "string",
              "maxGraphemes": 20,
              "maxLength": 200
            },
            "website": {
              "type": "string",
              "format": "uri"
            },
            "avatar": {
              "type": "blob",
              "accept": [
                "image/png",
                "image/jpeg"
              ],
              "maxSize": 1000000
            },
            "banner": {
              "type": "blob",
              "accept": [
                "image/png",
                "image/jpeg"
              ],
              "maxSize": 1000000
            },
            "labels": {
              "type": "union",
              "refs": [
                "com.atproto.label.defs#selfLabels"
              ]
            },
            "joinedViaStarterPack": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            },
            "pinnedPost": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.actor.status",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "required": [
            "status",
            "createdAt"
          ],
          "properties": {
            "status": {
              "type": "string",
              "knownValues": [
                "app.bsky.actor.status#live"
              ]
            },
            "embed": {
              "type": "union",
              "refs": [
                "app.bsky.embed.external"
              ]
            },
            "durationMinutes": {
              "type": "integer",
              "minimum": 1
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.defs",
    "defs": {
      "aspectRatio": {
        "type": "object",
        "required": [
          "width",
          "height"
        ],
        "properties": {
          "width": {
            "type": "integer",
            "minimum": 1
          },
          "height": {
            "type": "integer",
            "minimum": 1
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.external",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "external"
        ],
        "properties": {
          "external": {
            "type": "ref",
            "ref": "#external"
          }
        }
      },
      "external": {
        "type": "object",
        "required": [
          "uri",
          "title",
          "description"
        ],
        "properties": {
          "uri": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "string"
          },
          "thumb": {
            "type": "blob",
            "accept": [
              "image/*"
            ],
            "maxSize": 1000000
          },
          "associatedRefs": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.gallery",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "items"
        ],
        "properties": {
          "items": {
            "type": "array",
            "maxLength": 20,
            "items": {
              "type": "union",
              "refs": [
                "#image"
              ]
            }
          }
        }
      },
      "image": {
        "type": "object",
        "required": [
          "image",
          "alt",
          "aspectRatio"
        ],
        "properties": {
          "image": {
            "type": "blob",
            "accept": [
              "image/*"
            ],
            "maxSize": 2000000
          },
          "alt": {
            "type": "string"
          },
          "aspectRatio": {
            "type": "ref",
            "ref": "app.bsky.embed.defs#aspectRatio"
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.images",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "images"
        ],
        "properties": {
          "images": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "#image"
            },
            "maxLength": 4
          }
        }
      },
      "image": {
        "type": "object",
        "required": [
          "image",
          "alt"
        ],
        "properties": {
          "image": {
            "type": "blob",
            "accept": [
              "image/*"
            ],
            "maxSize": 2000000
          },
          "alt": {
            "type": "string"
          },
          "aspectRatio": {
            "type": "ref",
            "ref": "app.bsky.embed.defs#aspectRatio"
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.record",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "record"
        ],
        "properties": {
          "record": {
            "type": "ref",
            "ref": "com.atproto.repo.strongRef"
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.recordWithMedia",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "record",
          "media"
        ],
        "properties": {
          "record": {
            "type": "ref",
            "ref": "app.bsky.embed.record"
          },
          "media": {
            "type": "union",
            "refs": [
              "app.bsky.embed.images",
              "app.bsky.embed.video",
              "app.bsky.embed.gallery",
              "app.bsky.embed.external"
            ]
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.embed.video",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "video"
        ],
        "properties": {
          "video": {
            "type": "blob",
            "accept": [
              "video/mp4"
            ],
            "maxSize": 300000000
          },
          "captions": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "#caption"
            },
            "maxLength": 20
          },
          "alt": {
            "type": "string"
          },
          "aspectRatio": {
            "type": "ref",
            "ref": "app.bsky.embed.defs#aspectRatio"
          },
          "presentation": {
            "type": "string",
            "knownValues": [
              "default",
              "gif"
            ]
          }
        }
      },
      "caption": {
        "type": "object",
        "required": [
          "lang",
          "file"
        ],
        "properties": {
          "lang": {
            "type": "string",
            "format": "language"
          },
          "file": {
            "type": "blob",
            "accept": [
              "text/vtt"
            ],
            "maxSize": 20000
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.generator",
    "defs": {
      "main": {
        "type": "record",
        "key": "any",
        "record": {
          "type": "object",
          "required": [
            "did",
            "displayName",
            "createdAt"
          ],
          "properties": {
            "did": {
              "type": "string",
              "format": "did"
            },
            "displayName": {
              "type": "string",
              "maxGraphemes": 24,
              "maxLength": 240
            },
            "descriptionFacets": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.richtext.facet"
              }
            },
            "avatar": {
              "type": "blob",
              "accept": [
                "image/png",
                "image/jpeg"
              ],
              "maxSize": 1000000
            },
            "acceptsInteractions": {
              "type": "boolean"
            },
            "labels": {
              "type": "union",
              "refs": [
                "com.atproto.label.defs#selfLabels"
              ]
            },
            "contentMode": {
              "type": "string",
              "knownValues": [
                "app.bsky.feed.defs#contentModeUnspecified",
                "app.bsky.feed.defs#contentModeVideo"
              ]
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.like",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "via": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.post",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "text",
            "createdAt"
          ],
          "properties": {
            "text": {
              "type": "string",
              "maxLength": 3000,
              "maxGraphemes": 300
            },
            "entities": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "#entity"
              }
            },
            "facets": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.richtext.facet"
              }
            },
            "reply": {
              "type": "ref",
              "ref": "#replyRef"
            },
            "embed": {
              "type": "union",
              "refs": [
                "app.bsky.embed.images",
                "app.bsky.embed.video",
                "app.bsky.embed.gallery",
                "app.bsky.embed.external",
                "app.bsky.embed.record",
                "app.bsky.embed.recordWithMedia"
              ]
            },
            "langs": {
              "type": "array",
              "maxLength": 3,
              "items": {
                "type": "string",
                "format": "language"
              }
            },
            "labels": {
              "type": "union",
              "refs": [
                "com.atproto.label.defs#selfLabels"
              ]
            },
            "tags": {
              "type": "array",
              "maxLength": 8,
              "items": {
                "type": "string",
                "maxLength": 640,
                "maxGraphemes": 64
              }
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      },
      "entity": {
        "type": "object",
        "required": [
          "index",
          "type",
          "value"
        ],
        "properties": {
          "index": {
            "type": "ref",
            "ref": "#textSlice"
          },
          "type": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      },
      "replyRef": {
        "type": "object",
        "required": [
          "root",
          "parent"
        ],
        "properties": {
          "root": {
            "type": "ref",
            "ref": "com.atproto.repo.strongRef"
          },
          "parent": {
            "type": "ref",
            "ref": "com.atproto.repo.strongRef"
          }
        }
      },
      "textSlice": {
        "type": "object",
        "required": [
          "start",
          "end"
        ],
        "properties": {
          "start": {
            "type": "integer",
            "minimum": 0
          },
          "end": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.postgate",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "post",
            "createdAt"
          ],
          "properties": {
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "post": {
              "type": "string",
              "format": "at-uri"
            },
            "detachedEmbeddingUris": {
              "type": "array",
              "maxLength": 50,
              "items": {
                "type": "string",
                "format": "at-uri"
              }
            },
            "embeddingRules": {
              "type": "array",
              "maxLength": 5,
              "items": {
                "type": "union",
                "refs": [
                  "#disableRule"
                ]
              }
            }
          }
        }
      },
      "disableRule": {
        "type": "object",
        "properties": {}
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.repost",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "via": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.feed.threadgate",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "post",
            "createdAt"
          ],
          "properties": {
            "post": {
              "type": "string",
              "format": "at-uri"
            },
            "allow": {
              "type": "array",
              "maxLength": 5,
              "items": {
                "type": "union",
                "refs": [
                  "#mentionRule",
                  "#followerRule",
                  "#followingRule",
                  "#listRule"
                ]
              }
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "hiddenReplies": {
              "type": "array",
              "maxLength": 300,
              "items": {
                "type": "string",
                "format": "at-uri"
              }
            }
          }
        }
      },
      "followerRule": {
        "type": "object",
        "properties": {}
      },
      "followingRule": {
        "type": "object",
        "properties": {}
      },
      "listRule": {
        "type": "object",
        "required": [
          "list"
        ],
        "properties": {
          "list": {
            "type": "string",
            "format": "at-uri"
          }
        }
      },
      "mentionRule": {
        "type": "object",
        "properties": {}
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.block",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "did"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.defs",
    "defs": {
      "listPurpose": {
        "type": "string",
        "knownValues": [
          "app.bsky.graph.defs#modlist",
          "app.bsky.graph.defs#curatelist",
          "app.bsky.graph.defs#referencelist"
        ]
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.follow",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "did"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "via": {
              "type": "ref",
              "ref": "com.atproto.repo.strongRef"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.list",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "name",
            "purpose",
            "createdAt"
          ],
          "properties": {
            "purpose": {
              "type": "ref",
              "ref": "app.bsky.graph.defs#listPurpose"
            },
            "name": {
              "type": "string",
              "maxLength": 64,
              "minLength": 1
            },
            "descriptionFacets": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.richtext.facet"
              }
            },
            "avatar": {
              "type": "blob",
              "accept": [
                "image/png",
                "image/jpeg"
              ],
              "maxSize": 1000000
            },
            "labels": {
              "type": "union",
              "refs": [
                "com.atproto.label.defs#selfLabels"
              ]
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.listblock",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "at-uri"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.listitem",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "list",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "did"
            },
            "list": {
              "type": "string",
              "format": "at-uri"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.referencelistoptout",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "at-uri"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.starterpack",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "name",
            "list",
            "createdAt"
          ],
          "properties": {
            "name": {
              "type": "string",
              "maxGraphemes": 50,
              "maxLength": 500,
              "minLength": 1
            },
            "descriptionFacets": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.richtext.facet"
              }
            },
            "list": {
              "type": "string",
              "format": "at-uri"
            },
            "feeds": {
              "type": "array",
              "maxLength": 3,
              "items": {
                "type": "ref",
                "ref": "#feedItem"
              }
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      },
      "feedItem": {
        "type": "object",
        "required": [
          "uri"
        ],
        "properties": {
          "uri": {
            "type": "string",
            "format": "at-uri"
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.graph.verification",
    "defs": {
      "main": {
        "type": "record",
        "key": "tid",
        "record": {
          "type": "object",
          "required": [
            "subject",
            "handle",
            "displayName",
            "createdAt"
          ],
          "properties": {
            "subject": {
              "type": "string",
              "format": "did"
            },
            "handle": {
              "type": "string",
              "format": "handle"
            },
            "displayName": {
              "type": "string"
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.labeler.defs",
    "defs": {
      "labelerPolicies": {
        "type": "object",
        "required": [
          "labelValues"
        ],
        "properties": {
          "labelValues": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "com.atproto.label.defs#labelValue"
            }
          },
          "labelValueDefinitions": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "com.atproto.label.defs#labelValueDefinition"
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.labeler.service",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "required": [
            "policies",
            "createdAt"
          ],
          "properties": {
            "policies": {
              "type": "ref",
              "ref": "app.bsky.labeler.defs#labelerPolicies"
            },
            "labels": {
              "type": "union",
              "refs": [
                "com.atproto.label.defs#selfLabels"
              ]
            },
            "createdAt": {
              "type": "string",
              "format": "datetime"
            },
            "reasonTypes": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "com.atproto.moderation.defs#reasonType"
              }
            },
            "subjectTypes": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "com.atproto.moderation.defs#subjectType"
              }
            },
            "subjectCollections": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "nsid"
              }
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.notification.declaration",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "required": [
            "allowSubscriptions"
          ],
          "properties": {
            "allowSubscriptions": {
              "type": "string",
              "knownValues": [
                "followers",
                "mutuals",
                "none"
              ]
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "app.bsky.richtext.facet",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "index",
          "features"
        ],
        "properties": {
          "index": {
            "type": "ref",
            "ref": "#byteSlice"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "union",
              "refs": [
                "#mention",
                "#link",
                "#tag"
              ]
            }
          }
        }
      },
      "byteSlice": {
        "type": "object",
        "required": [
          "byteStart",
          "byteEnd"
        ],
        "properties": {
          "byteStart": {
            "type": "integer",
            "minimum": 0
          },
          "byteEnd": {
            "type": "integer",
            "minimum": 0
          }
        }
      },
      "link": {
        "type": "object",
        "required": [
          "uri"
        ],
        "properties": {
          "uri": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "mention": {
        "type": "object",
        "required": [
          "did"
        ],
        "properties": {
          "did": {
            "type": "string",
            "format": "did"
          }
        }
      },
      "tag": {
        "type": "object",
        "required": [
          "tag"
        ],
        "properties": {
          "tag": {
            "type": "string",
            "maxLength": 640,
            "maxGraphemes": 64
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "chat.bsky.actor.declaration",
    "defs": {
      "main": {
        "type": "record",
        "key": "literal:self",
        "record": {
          "type": "object",
          "required": [
            "allowIncoming"
          ],
          "properties": {
            "allowIncoming": {
              "type": "string",
              "knownValues": [
                "all",
                "none",
                "following"
              ]
            },
            "allowGroupInvites": {
              "type": "string",
              "knownValues": [
                "all",
                "none",
                "following"
              ]
            }
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "com.atproto.label.defs",
    "defs": {
      "labelValue": {
        "type": "string",
        "knownValues": [
          "!hide",
          "!warn",
          "!no-unauthenticated",
          "porn",
          "sexual",
          "nudity",
          "graphic-media",
          "bot"
        ]
      },
      "labelValueDefinition": {
        "type": "object",
        "required": [
          "identifier",
          "severity",
          "blurs",
          "locales"
        ],
        "properties": {
          "identifier": {
            "type": "string",
            "maxLength": 100,
            "maxGraphemes": 100
          },
          "severity": {
            "type": "string",
            "knownValues": [
              "inform",
              "alert",
              "none"
            ]
          },
          "blurs": {
            "type": "string",
            "knownValues": [
              "content",
              "media",
              "none"
            ]
          },
          "defaultSetting": {
            "type": "string",
            "knownValues": [
              "ignore",
              "warn",
              "hide"
            ],
            "default": "warn"
          },
          "adultOnly": {
            "type": "boolean"
          },
          "locales": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "#labelValueDefinitionStrings"
            }
          }
        }
      },
      "labelValueDefinitionStrings": {
        "type": "object",
        "required": [
          "lang",
          "name",
          "description"
        ],
        "properties": {
          "lang": {
            "type": "string",
            "format": "language"
          },
          "name": {
            "type": "string",
            "maxGraphemes": 64,
            "maxLength": 640
          }
        }
      },
      "selfLabel": {
        "type": "object",
        "required": [
          "val"
        ],
        "properties": {
          "val": {
            "type": "string",
            "maxLength": 128
          }
        }
      },
      "selfLabels": {
        "type": "object",
        "required": [
          "values"
        ],
        "properties": {
          "values": {
            "type": "array",
            "items": {
              "type": "ref",
              "ref": "#selfLabel"
            },
            "maxLength": 10
          }
        }
      }
    }
  },
  {
    "lexicon": 1,
    "id": "com.atproto.moderation.defs",
    "defs": {
      "reasonType": {
        "type": "string",
        "knownValues": [
          "com.atproto.moderation.defs#reasonSpam",
          "com.atproto.moderation.defs#reasonViolation",
          "com.atproto.moderation.defs#reasonMisleading",
          "com.atproto.moderation.defs#reasonSexual",
          "com.atproto.moderation.defs#reasonRude",
          "com.atproto.moderation.defs#reasonOther",
          "com.atproto.moderation.defs#reasonAppeal",
          "tools.ozone.report.defs#reasonAppeal",
          "tools.ozone.report.defs#reasonOther",
          "tools.ozone.report.defs#reasonViolenceAnimal",
          "tools.ozone.report.defs#reasonViolenceThreats",
          "tools.ozone.report.defs#reasonViolenceGraphicContent",
          "tools.ozone.report.defs#reasonViolenceGlorification",
          "tools.ozone.report.defs#reasonViolenceExtremistContent",
          "tools.ozone.report.defs#reasonViolenceTrafficking",
          "tools.ozone.report.defs#reasonViolenceOther",
          "tools.ozone.report.defs#reasonSexualAbuseContent",
          "tools.ozone.report.defs#reasonSexualNCII",
          "tools.ozone.report.defs#reasonSexualDeepfake",
          "tools.ozone.report.defs#reasonSexualAnimal",
          "tools.ozone.report.defs#reasonSexualUnlabeled",
          "tools.ozone.report.defs#reasonSexualOther",
          "tools.ozone.report.defs#reasonChildSafetyCSAM",
          "tools.ozone.report.defs#reasonChildSafetyGroom",
          "tools.ozone.report.defs#reasonChildSafetyPrivacy",
          "tools.ozone.report.defs#reasonChildSafetyHarassment",
          "tools.ozone.report.defs#reasonChildSafetyOther",
          "tools.ozone.report.defs#reasonHarassmentTroll",
          "tools.ozone.report.defs#reasonHarassmentTargeted",
          "tools.ozone.report.defs#reasonHarassmentHateSpeech",
          "tools.ozone.report.defs#reasonHarassmentDoxxing",
          "tools.ozone.report.defs#reasonHarassmentOther",
          "tools.ozone.report.defs#reasonMisleadingBot",
          "tools.ozone.report.defs#reasonMisleadingImpersonation",
          "tools.ozone.report.defs#reasonMisleadingSpam",
          "tools.ozone.report.defs#reasonMisleadingScam",
          "tools.ozone.report.defs#reasonMisleadingElections",
          "tools.ozone.report.defs#reasonMisleadingOther",
          "tools.ozone.report.defs#reasonRuleSiteSecurity",
          "tools.ozone.report.defs#reasonRuleProhibitedSales",
          "tools.ozone.report.defs#reasonRuleBanEvasion",
          "tools.ozone.report.defs#reasonRuleOther",
          "tools.ozone.report.defs#reasonSelfHarmContent",
          "tools.ozone.report.defs#reasonSelfHarmED",
          "tools.ozone.report.defs#reasonSelfHarmStunts",
          "tools.ozone.report.defs#reasonSelfHarmSubstances",
          "tools.ozone.report.defs#reasonSelfHarmOther"
        ]
      },
      "subjectType": {
        "type": "string",
        "knownValues": [
          "account",
          "record",
          "chat"
        ]
      }
    }
  },
  {
    "lexicon": 1,
    "id": "com.atproto.repo.strongRef",
    "defs": {
      "main": {
        "type": "object",
        "required": [
          "uri",
          "cid"
        ],
        "properties": {
          "uri": {
            "type": "string",
            "format": "at-uri"
          },
          "cid": {
            "type": "string",
            "format": "cid"
          }
        }
      }
    }
  }
] as LexiconDoc[];
