import { customRolesOf, isAdminPermission, PERMISSIONS, ROLES, type Permission, type RoleDef } from './permissions.js';
import { ROUTE_PERMISSIONS } from './routes.js';

/*
 * B-3301: the role × permission matrix, generated from the catalogue (`permissions.ts`) and the route permission
 * registry (`routes.ts`, B-3304). The API serves it as JSON or CSV with the tenant's custom roles added;
 * `docs/permissions.md` is the same matrix for the built-in roles, written by `npm run docs:permissions` and checked
 * by the test suite, so the document cannot drift from the code.
 */

const has = (r: RoleDef, p: Permission): boolean => r.permissions === '*' || r.permissions.includes(p);

/**
 * Routes per access kind, from the registry: a route needing several permissions is listed under each; one that
 * accepts any of several is listed under each of them as `anyOf:<permission>`.
 */
export function routesByAccess(): Map<string, string[]> {
  const out = new Map<string, string[]>();
  const add = (k: string, route: string) => out.set(k, [...(out.get(k) ?? []), route]);
  for (const [route, access] of ROUTE_PERMISSIONS) {
    if (typeof access === 'string') add(access, route);
    else if (Array.isArray(access)) for (const p of access as readonly Permission[]) add(p, route);
    else {
      const a = access as { anyOf: readonly Permission[]; all?: readonly Permission[] };
      for (const p of a.all ?? []) add(p, route);
      for (const p of a.anyOf) add(`anyOf:${p}`, route);
    }
  }
  return out;
}

export interface MatrixRole {
  id: string;
  name: string;
  description: string;
  builtIn: boolean;
  requiresMfa: boolean;
  grantableBy: readonly string[];
  version: number | null;
  permissions: Permission[];
}

export interface RoleMatrix {
  /** `routes` require the permission; `anyOfRoutes` accept it as one of several. */
  permissions: { id: Permission; admin: boolean; routes: string[]; anyOfRoutes: string[] }[];
  roles: MatrixRole[];
  /** Routes any signed-in caller may use (handlers may narrow further), and routes with no sign-in at all. */
  authenticatedRoutes: string[];
  publicRoutes: string[];
}

/** The matrix for the built-in roles, and a tenant's custom roles in force when a tenant id is given. */
export function roleMatrix(tenantId?: string): RoleMatrix {
  const routes = routesByAccess();
  const roles: MatrixRole[] = [
    ...ROLES.map((r) => ({ id: r.id, name: r.name, description: r.description, builtIn: true, requiresMfa: r.requiresMfa, grantableBy: r.grantableBy, version: null, permissions: PERMISSIONS.filter((p) => has(r, p)) })),
    ...(tenantId ? customRolesOf(tenantId) : []).map((r) => ({ id: r.id, name: r.name, description: r.description, builtIn: false, requiresMfa: r.requiresMfa, grantableBy: r.grantableBy, version: r.version, permissions: PERMISSIONS.filter((p) => has(r, p)) }))
  ];
  return {
    permissions: PERMISSIONS.map((p) => ({ id: p, admin: isAdminPermission(p), routes: routes.get(p) ?? [], anyOfRoutes: routes.get(`anyOf:${p}`) ?? [] })),
    roles,
    authenticatedRoutes: routes.get('authenticated') ?? [],
    publicRoutes: routes.get('public') ?? []
  };
}

const csvCell = (v: string): string => {
  // Formula injection: a cell starting with = + - @ is prefixed so a spreadsheet shows it as text.
  const safe = /^[=+\-@\t\r]/.test(v) ? `'${v}` : v;
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
};

/** One row per permission, one column per role (`x` where the role grants it), and the number of routes needing it. */
export function matrixCsv(m: RoleMatrix): string {
  const head = ['permission', 'admin', 'routes', ...m.roles.map((r) => r.id)];
  const rows = m.permissions.map((p) => [p.id, p.admin ? 'yes' : 'no', String(p.routes.length + p.anyOfRoutes.length), ...m.roles.map((r) => (r.permissions.includes(p.id) ? 'x' : ''))]);
  return [head, ...rows].map((r) => r.map(csvCell).join(',')).join('\r\n') + '\r\n';
}

/** `docs/permissions.md`: the built-in roles, the matrix and the routes of every permission. */
export function permissionsMarkdown(): string {
  const m = roleMatrix();
  const out: string[] = [];
  out.push('# Permissions');
  out.push('');
  out.push('<!-- Generated by `npm run docs:permissions` from server/src/authz/permissions.ts and server/src/authz/routes.ts. Do not edit by hand: the test suite fails when this file differs from the catalogue. -->');
  out.push('');
  out.push(`The permission catalogue has ${m.permissions.length} permissions and ${m.roles.length} built-in roles. A permission is \`resource:action\`; a role is a set of permissions, and \`system-admin\` holds every one. Tenants add custom roles built only from these permissions (B-3302); \`GET /api/authz/matrix\` shows them alongside the built-in roles. Every request goes through one pipeline in \`server/src/authz/policy.ts\`: role, credential scopes, tenant, clearance, zone ceiling.`);
  out.push('');
  out.push('An admin permission is any permission outside the member baseline: a custom role holding one needs a second admin to approve each version (dual control).');
  out.push('');
  out.push('## Built-in roles');
  out.push('');
  out.push('| Role | Name | Second factor | Granted by | Description |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const r of m.roles) out.push(`| \`${r.id}\` | ${r.name} | ${r.requiresMfa ? 'required' : 'no'} | ${r.grantableBy.map((g) => `\`${g}\``).join(', ')} | ${r.description} |`);
  out.push('');
  out.push('## Role × permission matrix');
  out.push('');
  out.push(`| Permission | Admin | Routes | ${m.roles.map((r) => `\`${r.id}\``).join(' | ')} |`);
  out.push(`| --- | --- | --- | ${m.roles.map(() => '---').join(' | ')} |`);
  for (const p of m.permissions) out.push(`| \`${p.id}\` | ${p.admin ? 'yes' : 'no'} | ${p.routes.length + p.anyOfRoutes.length} | ${m.roles.map((r) => (r.permissions.includes(p.id) ? 'x' : '')).join(' | ')} |`);
  out.push('');
  out.push('## Routes per permission');
  out.push('');
  out.push('From the route permission registry (`server/src/authz/routes.ts`, B-3304): every route the server registers declares the permission it requires, and the test suite fails for a route that does not. A route listed under several permissions requires all of them; one marked "or" accepts any one of the permissions it is listed under. Handlers may narrow further (clearance, ownership, workspace membership).');
  for (const p of m.permissions) {
    out.push('');
    out.push(`### \`${p.id}\``);
    out.push('');
    if (!p.routes.length && !p.anyOfRoutes.length) out.push('No route requires it directly; handlers and services check it.');
    for (const r of p.routes) out.push(`- \`${r}\``);
    for (const r of p.anyOfRoutes) out.push(`- \`${r}\` (or another permission)`);
  }
  out.push('');
  out.push('## Routes for any signed-in caller');
  out.push('');
  out.push('These need a signed-in session or credential and no particular permission; the handler decides what the caller sees (their own account, notifications, jobs, and resources it checks itself).');
  out.push('');
  for (const r of m.authenticatedRoutes) out.push(`- \`${r}\``);
  out.push('');
  out.push('## Public routes');
  out.push('');
  out.push('No sign-in: health checks, sign-in itself, protocol endpoints (OIDC, SAML, ACME, OCSP, AT-Protocol) and links whose signature or token is the credential.');
  out.push('');
  for (const r of m.publicRoutes) out.push(`- \`${r}\``);
  out.push('');
  return out.join('\n');
}
