import type { Permission } from './permissions.js';

/**
 * B-3304: the route permission registry. Every route the server registers is declared here, with what it requires:
 *
 * - a permission, or a list of permissions (all of them are required);
 * - `{ anyOf }`: any one of the permissions suffices (with `all`, those are required as well);
 * - `authenticated`: any signed-in session or credential (the handler decides what the caller sees: their own
 *   account, or resources it checks itself);
 * - `public`: no sign-in (health checks, sign-in, protocol endpoints, signed links whose signature is the credential).
 *
 * `route-registry.test.ts` walks the Express app and fails when a route is missing from this table, when the table
 * names a route the app does not register, or when a route's requirePermission or requireAuth middleware disagrees
 * with its entry. The role matrix (`GET /api/authz/matrix`) and `docs/permissions.md` list the routes per permission
 * from here. New routes: add them by hand, or run `npx tsx server/test/route-registry.ts --write` and review its lines.
 * Paths are in OpenAPI form (`{id}`), as in `docs/openapi.json`.
 */
export type RouteAccess = 'public' | 'authenticated' | Permission | readonly Permission[] | { readonly anyOf: readonly Permission[]; readonly all?: readonly Permission[] };

export const ROUTE_PERMISSIONS: readonly (readonly [string, RouteAccess])[] = [
  ['DELETE /api/admin/atproto/accounts/{id}', 'identity:manage'],
  ['DELETE /api/admin/connections/{id}', 'connections:manage'],
  ['DELETE /api/admin/federation/metadata/{id}', 'identity:manage'],
  ['DELETE /api/admin/federation/saml/sps/{id}', 'identity:manage'],
  ['DELETE /api/admin/group-mappings/{id}', 'identity:manage'],
  ['DELETE /api/admin/guardrails/sets/{id}/draft', 'guardrails:manage'],
  ['DELETE /api/admin/guardrails/sets/{id}/draft/rules/{ruleId}', 'guardrails:manage'],
  ['DELETE /api/admin/identity-providers/{id}', 'identity:manage'],
  ['DELETE /api/admin/instances/{id}', 'pools:manage'],
  ['DELETE /api/admin/mcp-servers/{id}', 'mcp:manage'],
  ['DELETE /api/admin/mcp-servers/{id}/bind/{profileId}', ['mcp:manage', 'profiles:manage']],
  ['DELETE /api/admin/placements/{id}', 'pools:manage'],
  ['DELETE /api/admin/platform/bundles/{id}', 'platform:manage'],
  ['DELETE /api/admin/platform/certificates/{id}', 'platform:manage'],
  ['DELETE /api/admin/platform/certificates/{id}/hooks/{hookId}', 'platform:manage'],
  ['DELETE /api/admin/platform/mirrors/{id}', 'platform:manage'],
  ['DELETE /api/admin/platform/mirrors/{id}/push-target', 'platform:manage'],
  ['DELETE /api/admin/plugins/{id}', 'plugins:manage'],
  ['DELETE /api/admin/pools/{id}', 'pools:manage'],
  ['DELETE /api/admin/profiles/{id}', 'profiles:manage'],
  ['DELETE /api/admin/profiles/{id}/canary', 'profiles:manage'],
  ['DELETE /api/admin/profiles/{id}/eval-sets/{sid}', 'profiles:manage'],
  ['DELETE /api/admin/red-team/suites/{id}', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['DELETE /api/admin/agent-identities/{name}/keys/{kid}', 'agents:manage'],
  ['DELETE /api/admin/sessions/{id}', 'users:manage'],
  ['DELETE /api/admin/social/group-categories/{id}', 'social:manage'],
  ['DELETE /api/admin/social/trending/exclusions/{tag}', 'social:manage'],
  ['DELETE /api/admin/tenants/{tid}/workspaces/{wid}/members/{uid}', 'tenant:manage'],
  ['DELETE /api/admin/webhooks/{id}', 'webhooks:manage'],
  ['DELETE /api/admin/zones/{id}/endpoints/{endpointId}', 'zones:manage'],
  ['DELETE /api/agent-schedules/{id}', { anyOf: ['agents:manage', 'agents:run'] }],
  ['DELETE /api/apps/{app}', 'apps:design'],
  ['DELETE /api/apps/{app}/entities/{entity}', 'apps:design'],
  ['DELETE /api/apps/{app}/entities/{entity}/records/{id}', 'records:write'],
  ['DELETE /api/apps/{app}/forms/{form}', 'apps:design'],
  ['DELETE /api/apps/{app}/triggers/{id}', 'apps:design'],
  ['DELETE /api/atproto/firehose/{id}', 'firehose:manage'],
  ['DELETE /api/atproto/feeds/{id}', 'firehose:manage'],
  ['DELETE /api/atproto/feeds/{id}/publication', 'firehose:manage'],
  ['DELETE /api/atproto/labelers/{id}', 'labels:manage'],
  ['DELETE /api/authz/roles/{id}', 'roles:manage'],
  ['DELETE /api/calendar/feeds/{id}', 'groups:write'],
  ['DELETE /api/channels/{id}', 'channels:manage'],
  ['DELETE /api/conversations/{id}', 'chat:write'],
  ['DELETE /api/conversations/{id}/shares/{shareId}', 'chat:write'],
  ['DELETE /api/feed/comments/{id}', 'feed:write'],
  ['DELETE /api/feed/posts/{id}', 'feed:write'],
  ['DELETE /api/feed/posts/{id}/bookmark', 'feed:write'],
  ['DELETE /api/feed/posts/{id}/reactions/{kind}', 'feed:write'],
  ['DELETE /api/feed/posts/{id}/repost', 'feed:write'],
  ['DELETE /api/files/{id}', 'files:write'],
  ['DELETE /api/files/{id}/shares/{shareId}', 'files:write'],
  ['DELETE /api/files/folders/{id}', 'files:write'],
  ['DELETE /api/group-posts/{id}', 'groups:write'],
  ['DELETE /api/group-requests/{id}', 'groups:write'],
  ['DELETE /api/groups/{id}', 'groups:write'],
  ['DELETE /api/groups/{id}/members/{userId}', 'groups:write'],
  ['DELETE /api/invitations/{id}', 'members:invite'],
  ['DELETE /api/knowledge/bases/{id}', 'knowledge:read'],
  ['DELETE /api/knowledge/bases/{id}/access/{grant}', 'knowledge:read'],
  ['DELETE /api/knowledge/documents/{id}', 'knowledge:read'],
  ['DELETE /api/knowledge/sources/{id}', 'knowledge:read'],
  ['DELETE /api/mcp/servers/{id}/token', 'tools:invoke'],
  ['DELETE /api/me/api-keys/{id}', 'authenticated'],
  ['DELETE /api/me/atproto', 'atproto:link'],
  ['DELETE /api/me/grants/{clientId}', 'authenticated'],
  ['DELETE /api/me/mfa/{id}', 'authenticated'],
  ['DELETE /api/me/sessions/{id}', 'authenticated'],
  ['DELETE /api/me/trusted-devices', 'authenticated'],
  ['DELETE /api/memory/{id}', 'memory:write'],
  ['DELETE /api/messaging/conversations/{id}', 'messages:write'],
  ['DELETE /api/messaging/conversations/{id}/members/{userId}', 'messages:write'],
  ['DELETE /api/messaging/messages/{id}', 'messages:write'],
  ['DELETE /api/messaging/messages/{id}/pin', 'messages:write'],
  ['DELETE /api/messaging/messages/{id}/reactions/{emoji}', 'messages:write'],
  ['DELETE /api/moderation/providers/{id}', 'moderation:manage'],
  ['DELETE /api/moderation/queues/{id}', 'moderation:manage'],
  ['DELETE /api/people/me/avatar', 'social:write'],
  ['DELETE /api/pki/profiles/{id}', 'pki:manage'],
  ['DELETE /api/social/blocks/{id}', 'social:write'],
  ['DELETE /api/social/following/{id}', 'social:write'],
  ['DELETE /api/social/lists/{id}', 'social:write'],
  ['DELETE /api/social/lists/{id}/members/{userId}', 'social:write'],
  ['DELETE /api/social/mutes/{id}', 'social:write'],
  ['DELETE /api/training/schedules/{id}', 'training:manage'],
  ['DELETE /api/training/windows/{id}', 'training:manage'],
  ['DELETE /api/vault/database/engines/{name}', 'connections:manage'],
  ['DELETE /api/vault/database/engines/{name}/roles/{role}', 'connections:manage'],
  ['DELETE /api/vault/kv/metadata/{path}', 'secrets:admin'],
  ['DELETE /api/vault/policies/{id}', 'secrets:admin'],
  ['DELETE /api/vault/transit/keys/{name}', 'secrets:admin'],
  ['DELETE /api/workflows/{id}', 'workflows:manage'],
  ['GET /.well-known/acme-challenge/{token}', 'public'],
  ['GET /.well-known/atproto-did', 'public'],
  ['GET /.well-known/did.json', 'public'],
  ['GET /.well-known/jwks.json', 'public'],
  ['GET /.well-known/openid-configuration', 'public'],
  ['GET /api/admin/atproto/accounts', 'identity:manage'],
  ['GET /api/admin/audit', 'audit:read'],
  ['GET /api/admin/audit/{id}', 'audit:read'],
  ['GET /api/admin/audit/checkpoints', 'audit:read'],
  ['GET /api/admin/audit/stream', 'audit:read'],
  ['GET /api/admin/audit/summary', 'audit:read'],
  ['GET /api/admin/billing/price-books', 'billing:read'],
  ['GET /api/admin/billing/settings', 'billing:read'],
  ['GET /api/admin/billing/statements', 'billing:read'],
  ['GET /api/admin/billing/statements/{month}', 'billing:read'],
  ['GET /api/admin/billing/statements/{month}/export', 'billing:read'],
  ['GET /api/admin/classifiers', 'classifiers:manage'],
  ['GET /api/admin/classifiers/{id}', 'classifiers:manage'],
  ['GET /api/admin/connections', 'connections:manage'],
  ['GET /api/admin/connections/{id}', 'connections:manage'],
  ['GET /api/admin/exports', { anyOf: ['audit:read', 'usage:read'] }],
  ['GET /api/admin/exports/{id}/download', { anyOf: ['audit:read', 'usage:read'] }],
  ['GET /api/admin/federation', 'identity:manage'],
  ['GET /api/admin/federation/keys', 'identity:manage'],
  ['GET /api/admin/federation/metadata', 'identity:manage'],
  ['GET /api/admin/federation/oidc/clients', 'identity:manage'],
  ['GET /api/admin/federation/oidc/clients/{id}', 'identity:manage'],
  ['GET /api/admin/federation/proposals', 'identity:manage'],
  ['GET /api/admin/federation/saml/sps', 'identity:manage'],
  ['GET /api/admin/federation/scopes', 'identity:manage'],
  ['GET /api/admin/federation/sessions', 'identity:manage'],
  ['GET /api/admin/federation/settings', 'identity:manage'],
  ['GET /api/admin/federation/upstream', 'identity:manage'],
  ['GET /api/admin/group-mappings', 'identity:manage'],
  ['GET /api/admin/guardrails/sets', 'guardrails:manage'],
  ['GET /api/admin/guardrails/sets/{id}', 'guardrails:manage'],
  ['GET /api/admin/guardrails/sets/{id}/diff', 'guardrails:manage'],
  ['GET /api/admin/guardrails/status', 'guardrails:manage'],
  ['GET /api/admin/identity-policy', 'identity:manage'],
  ['GET /api/admin/identity-providers', 'identity:manage'],
  ['GET /api/admin/identity-providers/{id}', 'identity:manage'],
  ['GET /api/admin/instances/{id}/events', 'pools:manage'],
  ['GET /api/admin/instances/{id}/plan', 'pools:manage'],
  ['GET /api/admin/integrations/hosts', 'tenant:manage'],
  ['GET /api/admin/label-names', 'classifiers:manage'],
  ['GET /api/admin/mcp-servers', 'mcp:manage'],
  ['GET /api/admin/mcp-servers/{id}', 'mcp:manage'],
  ['GET /api/admin/model-servers', 'models:manage'],
  ['GET /api/admin/models', 'models:read'],
  ['GET /api/admin/platform/backups', 'platform:manage'],
  ['GET /api/admin/platform/backups/drills/{id}', 'platform:manage'],
  ['GET /api/admin/platform/bundles', 'platform:manage'],
  ['GET /api/admin/platform/bundles/{id}', 'platform:manage'],
  ['GET /api/admin/platform/bundles/{id}/pushes', 'platform:manage'],
  ['GET /api/admin/platform/certificates', 'platform:manage'],
  ['GET /api/admin/platform/certificates/{id}/chain', 'platform:manage'],
  ['GET /api/admin/platform/certificates/{id}/hooks', 'platform:manage'],
  ['GET /api/admin/platform/keys', 'platform:manage'],
  ['GET /api/admin/platform/mirrors', 'platform:manage'],
  ['GET /api/admin/platform/push-targets', 'platform:manage'],
  ['GET /api/admin/platform/signers', 'platform:manage'],
  ['GET /api/admin/platform/signers/proposals', 'platform:manage'],
  ['GET /api/admin/platform/summary', 'platform:manage'],
  ['GET /api/admin/plugins', 'plugins:manage'],
  ['GET /api/admin/plugins/{id}', 'plugins:manage'],
  ['GET /api/admin/plugins/{id}/invocations', 'plugins:manage'],
  ['GET /api/admin/plugins/{id}/logs', 'plugins:manage'],
  ['GET /api/admin/plugins/{id}/transitions', 'plugins:manage'],
  ['GET /api/admin/plugins/available', 'plugins:manage'],
  ['GET /api/admin/plugins/capabilities', 'plugins:manage'],
  ['GET /api/admin/pools', 'pools:manage'],
  ['GET /api/admin/profiles', 'profiles:manage'],
  ['GET /api/admin/profiles/{id}/evaluations', 'profiles:manage'],
  ['GET /api/admin/red-team', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['GET /api/admin/red-team/attacks', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['GET /api/admin/red-team/runs/{id}', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['GET /api/admin/agent-identities', 'agents:manage'],
  ['GET /api/admin/agent-identities/{name}', 'agents:manage'],
  ['GET /api/admin/profiles/{id}/evaluations/runs/{rid}', 'profiles:manage'],
  ['GET /api/admin/profiles/{id}/versions', 'profiles:manage'],
  ['GET /api/admin/quotas', 'usage:read'],
  ['GET /api/admin/registry', 'tools:manage'],
  ['GET /api/admin/registry/{id}', 'tools:manage'],
  ['GET /api/admin/roles', 'users:manage'],
  ['GET /api/admin/sessions', 'users:manage'],
  ['GET /api/admin/signups', 'users:manage'],
  ['GET /api/admin/social/conversations', 'social:manage'],
  ['GET /api/admin/social/exports/{id}/download', 'social:manage'],
  ['GET /api/admin/social/feed', 'social:manage'],
  ['GET /api/admin/social/groups', 'social:manage'],
  ['GET /api/admin/social/groups/{id}/members', 'social:manage'],
  ['GET /api/admin/social/messaging', 'social:manage'],
  ['GET /api/admin/social/people', 'platform:manage'],
  ['GET /api/admin/social/realtime', 'platform:manage'],
  ['GET /api/admin/social/relations', 'social:manage'],
  ['GET /api/admin/tenant-templates', 'tenant:manage'],
  ['GET /api/admin/tenants', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/quota', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/retention', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/sharing', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/users', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/workspaces', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/workspaces/{wid}/members', 'tenant:manage'],
  ['GET /api/admin/tenants/{tid}/workspaces/{wid}/quota', 'tenant:manage'],
  ['GET /api/admin/usage/daily', 'usage:read'],
  ['GET /api/admin/usage/storage', 'usage:read'],
  ['GET /api/admin/usage/summary', 'usage:read'],
  ['GET /api/admin/user-imports', 'users:manage'],
  ['GET /api/admin/user-imports/{id}', 'users:manage'],
  ['GET /api/admin/users', 'users:manage'],
  ['GET /api/admin/users/{id}', 'users:manage'],
  ['GET /api/admin/webhooks', 'webhooks:manage'],
  ['GET /api/admin/webhooks/{id}/deliveries', 'webhooks:manage'],
  ['GET /api/admin/webhooks/signing-key', 'webhooks:manage'],
  ['GET /api/admin/zones', 'zones:manage'],
  ['GET /api/admin/zones-cluster', 'zones:manage'],
  ['GET /api/admin/zones/{id}/blockers', 'zones:manage'],
  ['GET /api/admin/zones/{id}/diff', 'zones:manage'],
  ['GET /api/admin/zones/{id}/rendered/{format}', 'zones:manage'],
  ['GET /api/admin/zones/{id}/versions', 'zones:manage'],
  ['GET /api/admin/zones/misplaced', 'zones:manage'],
  ['GET /api/admin/zones/rendered/{format}', 'zones:manage'],
  ['GET /api/agent-schedules', { anyOf: ['agents:manage', 'agents:run'] }],
  ['GET /api/agent-schedules/{id}', { anyOf: ['agents:manage', 'agents:run'] }],
  ['GET /api/agent-schedules/{id}/history', { anyOf: ['agents:manage', 'agents:run'] }],
  ['GET /api/agents', 'agents:run'],
  ['GET /api/apps', 'records:read'],
  ['GET /api/apps/{app}', 'records:read'],
  ['GET /api/apps/{app}/entities/{entity}', 'records:read'],
  ['GET /api/apps/{app}/entities/{entity}/fields/{field}/options', 'records:read'],
  ['GET /api/apps/{app}/entities/{entity}/records', 'records:read'],
  ['GET /api/apps/{app}/entities/{entity}/records/{id}', 'records:read'],
  ['GET /api/apps/{app}/export', 'apps:design'],
  ['GET /api/apps/{app}/forms', 'records:read'],
  ['GET /api/apps/{app}/forms/{form}', 'records:read'],
  ['GET /api/apps/{app}/triggers', 'apps:design'],
  ['GET /api/apps/transfers/{id}', 'records:read'],
  ['GET /api/apps/transfers/{id}/download', 'records:read'],
  ['GET /api/atproto', { anyOf: ['labels:manage', 'pki:manage'] }],
  ['GET /api/atproto/feeds', 'firehose:manage'],
  ['GET /api/atproto/feeds/{id}', 'firehose:manage'],
  ['GET /api/atproto/feeds/{id}/skeleton', 'firehose:manage'],
  ['GET /api/atproto/firehose', 'firehose:manage'],
  ['GET /api/atproto/firehose/{id}', 'firehose:manage'],
  ['GET /api/atproto/identity', 'pki:manage'],
  ['GET /api/atproto/labelers', 'labels:manage'],
  ['GET /api/atproto/labelers/{id}/labels', 'labels:manage'],
  ['GET /api/atproto/labels', 'labels:manage'],
  ['GET /api/attachments/{id}', 'chat:read'],
  ['GET /api/auth/device', 'authenticated'],
  ['GET /api/auth/session', 'public'],
  ['GET /api/auth/sign-in-options', 'public'],
  ['GET /api/authz/access', 'roles:manage'],
  ['GET /api/authz/access/explain', 'roles:manage'],
  ['GET /api/authz/matrix', 'roles:manage'],
  ['GET /api/authz/reviews', 'authenticated'],
  ['GET /api/authz/reviews/{id}', 'authenticated'],
  ['GET /api/authz/roles', 'roles:manage'],
  ['GET /api/authz/roles/{id}', 'roles:manage'],
  ['GET /api/authz/roles/{id}/diff', 'roles:manage'],
  ['GET /api/authz/roles/{id}/versions/{version}', 'roles:manage'],
  ['GET /api/authz/who-can', 'roles:manage'],
  ['GET /api/calendar/events', 'groups:read'],
  ['GET /api/calendar/events/{id}', 'groups:read'],
  ['GET /api/calendar/events/{id}/attendees', 'groups:read'],
  ['GET /api/calendar/events/{id}/reminders', 'groups:read'],
  ['GET /api/calendar/feeds', 'groups:read'],
  ['GET /api/channels', { anyOf: ['channels:manage', 'channels:review'] }],
  ['GET /api/channels/{id}', { anyOf: ['channels:manage', 'channels:review'] }],
  ['GET /api/channels/{id}/bounces', 'channels:review'],
  ['GET /api/channels/{id}/sessions', 'channels:review'],
  ['GET /api/channels/{id}/sessions/{sessionId}', 'channels:review'],
  ['GET /api/channels/{id}/sessions/{sessionId}/transcript.csv', 'channels:review'],
  ['GET /api/channels/exports/{id}', 'channels:review'],
  ['GET /api/channels/held', 'channels:review'],
  ['GET /api/chat/profiles', 'chat:read'],
  ['GET /api/conversation-exports', 'chat:read'],
  ['GET /api/conversation-exports/{id}', 'chat:read'],
  ['GET /api/conversation-exports/{id}/download', 'chat:read'],
  ['GET /api/conversations', 'chat:read'],
  ['GET /api/conversations/{id}', 'chat:read'],
  ['GET /api/conversations/{id}/knowledge', 'context:read'],
  ['GET /api/conversations/{id}/messages/{mid}/stream', 'chat:read'],
  ['GET /api/conversations/{id}/share-targets', 'chat:read'],
  ['GET /api/conversations/{id}/shares', 'chat:read'],
  ['GET /api/eval-sets', { anyOf: ['classifiers:manage', 'flags:review'] }],
  ['GET /api/events/catalogue', { anyOf: ['plugins:manage', 'webhooks:manage', 'workflows:manage'] }],
  ['GET /api/feed/bookmarks', 'feed:read'],
  ['GET /api/feed/digests/{id}', 'feed:read'],
  ['GET /api/feed/groups/{id}', 'feed:read'],
  ['GET /api/feed/home', 'feed:read'],
  ['GET /api/feed/lists/{id}', 'feed:read'],
  ['GET /api/feed/posts/{id}', 'feed:read'],
  ['GET /api/feed/posts/{id}/comments', 'feed:read'],
  ['GET /api/feed/tags/{tag}', 'feed:read'],
  ['GET /api/feed/trending', 'feed:read'],
  ['GET /api/feed/users/{id}', 'feed:read'],
  ['GET /api/feed/workspaces/{id}', 'feed:read'],
  ['GET /api/feed/workspaces/{id}/digests', 'feed:read'],
  ['GET /api/feed/workspaces/{id}/settings', 'feed:manage'],
  ['GET /api/files/{id}', 'files:read'],
  ['GET /api/files/{id}/content', 'files:read'],
  ['GET /api/files/{id}/preview', 'files:read'],
  ['GET /api/files/{id}/shares', 'files:read'],
  ['GET /api/files/{id}/versions', 'files:read'],
  ['GET /api/files/{id}/versions/{n}/content', 'files:read'],
  ['GET /api/files/browse', 'files:read'],
  ['GET /api/files/search', 'files:read'],
  ['GET /api/files/shared', 'files:read'],
  ['GET /api/files/trash', 'files:read'],
  ['GET /api/files/usage', 'files:read'],
  ['GET /api/flags', 'flags:review'],
  ['GET /api/flags/{ref}', 'flags:review'],
  ['GET /api/flags/{ref}/reviewers', 'flags:review'],
  ['GET /api/flags/decisions', 'flags:review'],
  ['GET /api/group-categories', 'groups:read'],
  ['GET /api/group-requests', 'groups:read'],
  ['GET /api/groups', 'groups:read'],
  ['GET /api/groups/discover', 'groups:read'],
  ['GET /api/groups/trending', 'groups:read'],
  ['GET /api/groups/{id}', 'groups:read'],
  ['GET /api/groups/{id}/candidates', 'groups:read'],
  ['GET /api/groups/{id}/cases', 'groups:read'],
  ['GET /api/groups/{id}/channels', 'groups:read'],
  ['GET /api/groups/{id}/events', 'groups:read'],
  ['GET /api/groups/{id}/members', 'groups:read'],
  ['GET /api/groups/{id}/posts', 'groups:read'],
  ['GET /api/groups/{id}/requests', 'groups:read'],
  ['GET /api/images', 'images:generate'],
  ['GET /api/images/{id}', 'images:generate'],
  ['GET /api/images/{id}/download', 'images:generate'],
  ['GET /api/images/{id}/image', 'images:generate'],
  ['GET /api/images/{id}/provenance', 'images:generate'],
  ['GET /api/images/backends', 'images:generate'],
  ['GET /api/images/quota', 'images:generate'],
  ['GET /api/invitations', 'members:invite'],
  ['GET /api/knowledge/bases', 'knowledge:read'],
  ['GET /api/knowledge/bases/{id}', 'knowledge:read'],
  ['GET /api/knowledge/bases/{id}/access', 'knowledge:read'],
  ['GET /api/knowledge/bases/{id}/documents', 'knowledge:read'],
  ['GET /api/knowledge/connections', 'knowledge:read'],
  ['GET /api/knowledge/documents/{id}', 'knowledge:read'],
  ['GET /api/knowledge/models', 'knowledge:read'],
  ['GET /api/knowledge/principals', 'knowledge:read'],
  ['GET /api/mcp/servers', 'tools:invoke'],
  ['GET /api/me', 'authenticated'],
  ['GET /api/me/api-keys', 'authenticated'],
  ['GET /api/me/atproto', 'atproto:link'],
  ['GET /api/me/grants', 'authenticated'],
  ['GET /api/me/jobs', 'authenticated'],
  ['GET /api/me/mfa', 'authenticated'],
  ['GET /api/me/notifications', 'authenticated'],
  ['GET /api/me/sessions', 'authenticated'],
  ['GET /api/me/trusted-devices', 'authenticated'],
  ['GET /api/media/assets', 'chat:read'],
  ['GET /api/media/assets/{id}', 'chat:read'],
  ['GET /api/media/assets/{id}/content', 'chat:read'],
  ['GET /api/media/assets/{id}/previews/{i}', 'chat:read'],
  ['GET /api/media/caps', 'chat:read'],
  ['GET /api/media/jobs/{id}', 'chat:read'],
  ['GET /api/media/jobs/{id}/outputs/{i}', 'chat:read'],
  ['GET /api/memory', 'memory:write'],
  ['GET /api/memory/{id}', 'memory:write'],
  ['GET /api/memory/exports/{id}', 'memory:write'],
  ['GET /api/memory/exports/{id}/download', 'memory:write'],
  ['GET /api/memory/settings', 'knowledge:manage'],
  ['GET /api/messaging/conversations', 'messages:read'],
  ['GET /api/messaging/conversations/{id}', 'messages:read'],
  ['GET /api/messaging/conversations/{id}/members', 'messages:read'],
  ['GET /api/messaging/conversations/{id}/messages', 'messages:read'],
  ['GET /api/messaging/conversations/{id}/pins', 'messages:read'],
  ['GET /api/messaging/conversations/{id}/receipts', 'messages:read'],
  ['GET /api/messaging/conversations/{id}/search', 'messages:read'],
  ['GET /api/moderation/actions', 'moderation:review'],
  ['GET /api/moderation/appeals', 'moderation:review'],
  ['GET /api/moderation/appeals/{ref}', { anyOf: ['moderation:appeal', 'moderation:review'] }],
  ['GET /api/moderation/dead-letters', 'moderation:manage'],
  ['GET /api/moderation/mine', 'moderation:appeal'],
  ['GET /api/moderation/providers', 'moderation:manage'],
  ['GET /api/moderation/providers/{id}/verdicts', 'moderation:manage'],
  ['GET /api/moderation/queues', { anyOf: ['moderation:manage', 'moderation:review'] }],
  ['GET /api/moderation/queues/{id}/flags', 'moderation:review'],
  ['GET /api/moderation/sanctions', 'moderation:sanction'],
  ['GET /api/moderation/types', { anyOf: ['moderation:check', 'moderation:report'] }],
  ['GET /api/people/me', 'social:read'],
  ['GET /api/people/{id}', 'social:read'],
  ['GET /api/people/{id}/avatar', 'social:read'],
  ['GET /api/pki', 'pki:manage'],
  ['GET /api/pki/acme', 'pki:manage'],
  ['GET /api/pki/acme/accounts', 'pki:manage'],
  ['GET /api/pki/acme/eab-keys', 'pki:manage'],
  ['GET /api/pki/acme/orders', 'pki:manage'],
  ['GET /api/pki/certificates', 'pki:manage'],
  ['GET /api/pki/certificates/{id}', 'pki:manage'],
  ['GET /api/pki/certificates/{id}/export', 'pki:manage'],
  ['GET /api/pki/issuers', 'pki:manage'],
  ['GET /api/pki/issuers/{id}', 'pki:manage'],
  ['GET /api/pki/issuers/{id}/crls', 'pki:manage'],
  ['GET /api/pki/profiles', 'pki:manage'],
  ['GET /api/presence', 'social:read'],
  ['GET /api/presence/me', 'social:read'],
  ['GET /api/prompts', 'chat:read'],
  ['GET /api/prompts/{id}', 'chat:read'],
  ['GET /api/public/channels/session', 'public'],
  ['GET /api/runs', { anyOf: ['agents:manage', 'agents:run', 'tools:manage'] }],
  ['GET /api/runs/{id}', { anyOf: ['agents:manage', 'agents:run', 'tools:manage'] }],
  ['GET /api/script-runs/{id}', 'scripts:run'],
  ['GET /api/scripts', 'scripts:run'],
  ['GET /api/scripts/{id}', 'scripts:run'],
  ['GET /api/scripts/{id}/runs', 'scripts:run'],
  ['GET /api/scripts/{id}/versions', 'scripts:run'],
  ['GET /api/scripts/{id}/versions/{v}', 'scripts:run'],
  ['GET /api/scripts/runtime', 'scripts:run'],
  ['GET /api/shared-conversations', 'chat:read'],
  ['GET /api/shared-conversations/{id}', 'chat:read'],
  ['GET /api/shared-conversations/{id}/messages/{mid}/stream', 'chat:read'],
  ['GET /api/social/admin/users/{id}', 'social:manage'],
  ['GET /api/social/blocks', 'social:read'],
  ['GET /api/social/followers', 'social:read'],
  ['GET /api/social/following', 'social:read'],
  ['GET /api/social/lists', 'social:read'],
  ['GET /api/social/lists/{id}', 'social:read'],
  ['GET /api/social/mutes', 'social:read'],
  ['GET /api/social/people', 'social:read'],
  ['GET /api/social/settings', 'social:read'],
  ['GET /api/social/users/{id}', 'social:read'],
  ['GET /api/training/base-models', 'training:submit'],
  ['GET /api/training/datasets', 'training:submit'],
  ['GET /api/training/datasets/{id}', 'training:submit'],
  ['GET /api/training/datasets/{id}/report', 'training:submit'],
  ['GET /api/training/evals', 'training:submit'],
  ['GET /api/training/jobs', 'training:submit'],
  ['GET /api/training/jobs/{id}', 'training:submit'],
  ['GET /api/training/jobs/{id}/card', 'training:submit'],
  ['GET /api/training/schedules', 'training:submit'],
  ['GET /api/training/settings', 'training:submit'],
  ['GET /api/training/summary', 'training:submit'],
  ['GET /api/training/windows', 'training:submit'],
  ['GET /api/vault/database/engines', 'connections:manage'],
  ['GET /api/vault/database/engines/{name}', 'connections:manage'],
  ['GET /api/vault/database/leases', 'secrets:read'],
  ['GET /api/vault/database/leases/{id}', 'secrets:read'],
  ['GET /api/vault/database/roles', 'secrets:read'],
  ['GET /api/vault/kv', 'secrets:read'],
  ['GET /api/vault/kv/data/{path}', 'secrets:read'],
  ['GET /api/vault/kv/metadata/{path}', 'secrets:read'],
  ['GET /api/vault/policies', 'secrets:admin'],
  ['GET /api/vault/transit/keys', 'secrets:read'],
  ['GET /api/vault/transit/keys/{name}', 'secrets:read'],
  ['GET /api/workflow-approvals', 'authenticated'],
  ['GET /api/workflow-dead-letters', 'workflows:manage'],
  ['GET /api/workflow-runs/{id}', 'authenticated'],
  ['GET /api/workflow-tools', 'agents:run'],
  ['GET /api/workflow-callees', 'agents:run'],
  ['GET /api/workflows', 'agents:run'],
  ['GET /api/workflows/{id}', 'agents:run'],
  ['GET /api/workflows/{id}/bundle', 'workflows:manage'],
  ['GET /api/workflows/{id}/callers', 'agents:run'],
  ['GET /api/workflows/{id}/runs', 'agents:run'],
  ['GET /api/workflows/{id}/triggers', 'agents:run'],
  ['GET /atproto/{key}/did.json', 'public'],
  ['GET /atproto/{key}/xrpc/app.bsky.feed.describeFeedGenerator', 'public'],
  ['GET /atproto/{key}/xrpc/app.bsky.feed.getFeedSkeleton', 'public'],
  ['GET /atproto/{key}/xrpc/com.atproto.label.queryLabels', 'public'],
  ['GET /auth/negotiate', 'public'],
  ['GET /calendar/feeds/{id}/{file}', 'public'],
  ['GET /device', 'public'],
  ['GET /federation/atproto/callback', 'public'],
  ['GET /federation/atproto/client-metadata.json', 'public'],
  ['GET /federation/atproto/start', 'public'],
  ['GET /federation/github/callback', 'public'],
  ['GET /federation/github/start', 'public'],
  ['GET /federation/oidc/callback', 'public'],
  ['GET /federation/oidc/start', 'public'],
  ['GET /federation/saml/{id}', 'public'],
  ['GET /federation/saml/slo', 'public'],
  ['GET /federation/saml/start', 'public'],
  ['GET /healthz', 'public'],
  ['GET /media-content/{token}', 'public'],
  ['GET /metrics', 'public'],
  ['GET /oauth/authorize', 'public'],
  ['GET /oauth/logged-out', 'public'],
  ['GET /oauth/logout', 'public'],
  ['GET /oauth/userinfo', 'public'],
  ['GET /pki/acme/{tenant}/directory', 'public'],
  ['GET /pki/acme/{tenant}/new-nonce', 'public'],
  ['GET /pki/ca/{file}', 'public'],
  ['GET /pki/crl/{file}', 'public'],
  ['GET /pki/ocsp/{request}', 'public'],
  ['GET /readyz', 'public'],
  ['GET /saml/continue', 'public'],
  ['GET /saml/metadata', 'public'],
  ['GET /saml/slo', 'public'],
  ['GET /saml/sso', 'public'],
  ['GET /t/{tenant}/.well-known/jwks.json', 'public'],
  ['GET /t/{tenant}/.well-known/openid-configuration', 'public'],
  ['GET /t/{tenant}/auth/negotiate', 'public'],
  ['GET /t/{tenant}/device', 'public'],
  ['GET /t/{tenant}/federation/atproto/callback', 'public'],
  ['GET /t/{tenant}/federation/atproto/client-metadata.json', 'public'],
  ['GET /t/{tenant}/federation/atproto/start', 'public'],
  ['GET /t/{tenant}/federation/github/callback', 'public'],
  ['GET /t/{tenant}/federation/github/start', 'public'],
  ['GET /t/{tenant}/federation/oidc/callback', 'public'],
  ['GET /t/{tenant}/federation/oidc/start', 'public'],
  ['GET /t/{tenant}/federation/saml/{id}', 'public'],
  ['GET /t/{tenant}/federation/saml/slo', 'public'],
  ['GET /t/{tenant}/federation/saml/start', 'public'],
  ['GET /t/{tenant}/oauth/authorize', 'public'],
  ['GET /t/{tenant}/oauth/logged-out', 'public'],
  ['GET /t/{tenant}/oauth/logout', 'public'],
  ['GET /t/{tenant}/oauth/userinfo', 'public'],
  ['GET /t/{tenant}/saml/continue', 'public'],
  ['GET /t/{tenant}/saml/metadata', 'public'],
  ['GET /t/{tenant}/saml/slo', 'public'],
  ['GET /t/{tenant}/saml/sso', 'public'],
  ['GET /trainer/v1/artifacts/{grant}/{name}', 'public'],
  ['GET /v1/held/{id}', 'inference:invoke'],
  ['GET /v1/models', 'inference:invoke'],
  ['GET /v1/models/{id}', 'inference:invoke'],
  ['GET /v1/responses/{id}', 'inference:invoke'],
  ['GET /webhooks/keys/{tenant}', 'public'],
  ['GET /xrpc/app.bsky.feed.describeFeedGenerator', 'public'],
  ['GET /xrpc/app.bsky.feed.getFeedSkeleton', 'public'],
  ['GET /xrpc/com.atproto.label.queryLabels', 'public'],
  ['HEAD /pki/acme/{tenant}/new-nonce', 'public'],
  ['PATCH /api/admin/billing/price-books/{id}', 'billing:manage'],
  ['PATCH /api/admin/classifiers/{id}', 'classifiers:manage'],
  ['PATCH /api/admin/connections/{id}', 'connections:manage'],
  ['PATCH /api/admin/federation/oidc/clients/{id}', 'identity:manage'],
  ['PATCH /api/admin/federation/saml/sps/{id}', 'identity:manage'],
  ['PATCH /api/admin/federation/settings', 'identity:manage'],
  ['PATCH /api/admin/group-mappings/{id}', 'identity:manage'],
  ['PATCH /api/admin/identity-providers/{id}', 'identity:manage'],
  ['PATCH /api/admin/instances/{id}', 'pools:manage'],
  ['PATCH /api/admin/models/{id}', 'models:manage'],
  ['PATCH /api/admin/placements/{id}', 'pools:manage'],
  ['PATCH /api/admin/platform/certificates/{id}', 'platform:manage'],
  ['PATCH /api/admin/platform/mirrors/{id}', 'platform:manage'],
  ['PATCH /api/admin/pools/{id}', 'pools:manage'],
  ['PATCH /api/admin/profiles/{id}', 'profiles:manage'],
  ['PATCH /api/admin/profiles/{id}/eval-sets/{sid}', 'profiles:manage'],
  ['PATCH /api/admin/red-team/suites/{id}', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['PATCH /api/admin/registry/{id}', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['PATCH /api/admin/social/group-categories/{id}', 'social:manage'],
  ['PATCH /api/admin/tenants/{tid}', 'tenant:manage'],
  ['PATCH /api/admin/tenants/{tid}/workspaces/{wid}', 'tenant:manage'],
  ['PATCH /api/admin/users/{id}', 'users:manage'],
  ['PATCH /api/admin/webhooks/{id}', 'webhooks:manage'],
  ['PATCH /api/agent-schedules/{id}', { anyOf: ['agents:manage', 'agents:run'] }],
  ['PATCH /api/apps/{app}', 'apps:design'],
  ['PATCH /api/apps/{app}/entities/{entity}', 'apps:design'],
  ['PATCH /api/apps/{app}/entities/{entity}/records/{id}', 'records:write'],
  ['PATCH /api/apps/{app}/forms/{form}', 'apps:design'],
  ['PATCH /api/apps/{app}/triggers/{id}', 'apps:design'],
  ['PATCH /api/atproto/feeds/{id}', 'firehose:manage'],
  ['PATCH /api/atproto/firehose/{id}', 'firehose:manage'],
  ['PATCH /api/atproto/labelers/{id}', 'labels:manage'],
  ['PATCH /api/authz/roles/{id}', 'roles:manage'],
  ['PATCH /api/calendar/events/{id}', 'groups:write'],
  ['PATCH /api/channels/{id}', 'channels:manage'],
  ['PATCH /api/conversations/{id}', 'chat:write'],
  ['PATCH /api/feed/posts/{id}', 'feed:write'],
  ['PATCH /api/files/{id}', 'files:write'],
  ['PATCH /api/files/folders/{id}', 'files:write'],
  ['PATCH /api/groups/{id}', 'groups:write'],
  ['PATCH /api/groups/{id}/members/{userId}', 'groups:write'],
  ['PATCH /api/knowledge/bases/{id}', 'knowledge:read'],
  ['PATCH /api/knowledge/documents/{id}', 'knowledge:read'],
  ['PATCH /api/me/preferences', 'authenticated'],
  ['PATCH /api/memory/{id}', 'memory:write'],
  ['PATCH /api/messaging/conversations/{id}', 'messages:write'],
  ['PATCH /api/messaging/conversations/{id}/members/{userId}', 'messages:write'],
  ['PATCH /api/messaging/messages/{id}', 'messages:write'],
  ['PATCH /api/moderation/providers/{id}', 'moderation:manage'],
  ['PATCH /api/moderation/queues/{id}', 'moderation:manage'],
  ['PATCH /api/people/me', 'social:write'],
  ['PATCH /api/pki/profiles/{id}', 'pki:manage'],
  ['PATCH /api/prompts/{id}', 'prompts:manage'],
  ['PATCH /api/scripts/{id}', 'scripts:run'],
  ['PATCH /api/social/lists/{id}', 'social:write'],
  ['PATCH /api/training/schedules/{id}', 'training:manage'],
  ['PATCH /api/vault/database/engines/{name}', 'connections:manage'],
  ['PATCH /api/vault/kv/metadata/{path}', 'secrets:write'],
  ['PATCH /api/vault/policies/{id}', 'secrets:admin'],
  ['PATCH /api/vault/transit/keys/{name}', 'secrets:admin'],
  ['PATCH /api/workflows/{id}/triggers', 'workflows:manage'],
  ['POST /api/admin/atproto/accounts/check', 'identity:manage'],
  ['POST /api/admin/audit/{id}/corrections', 'audit:read'],
  ['POST /api/admin/audit/checkpoints', 'audit:read'],
  ['POST /api/admin/audit/exports', 'audit:read'],
  ['POST /api/admin/audit/verify', 'audit:read'],
  ['POST /api/admin/authz/evaluate', 'tenant:manage'],
  ['POST /api/admin/billing/price-books', 'billing:manage'],
  ['POST /api/admin/billing/statements/{month}/compute', 'billing:manage'],
  ['POST /api/admin/billing/statements/{month}/push', 'billing:manage'],
  ['POST /api/admin/classifiers', 'classifiers:manage'],
  ['POST /api/admin/classifiers/{id}/evaluate', 'classifiers:manage'],
  ['POST /api/admin/classifiers/{id}/publish', 'classifiers:manage'],
  ['POST /api/admin/classifiers/{id}/samples', 'classifiers:manage'],
  ['POST /api/admin/classifiers/{id}/train', 'classifiers:manage'],
  ['POST /api/admin/connections', 'connections:manage'],
  ['POST /api/admin/connections/{id}/export', 'connections:manage'],
  ['POST /api/admin/connections/{id}/query', 'connections:manage'],
  ['POST /api/admin/connections/{id}/schema', 'connections:manage'],
  ['POST /api/admin/connections/{id}/sync', 'connections:manage'],
  ['POST /api/admin/connections/{id}/test', 'connections:manage'],
  ['POST /api/admin/federation/keys/rotate', 'identity:manage'],
  ['POST /api/admin/federation/metadata/{id}/refresh', 'identity:manage'],
  ['POST /api/admin/federation/oidc/clients', 'identity:manage'],
  ['POST /api/admin/federation/oidc/clients/{id}/disable', 'identity:manage'],
  ['POST /api/admin/federation/oidc/clients/{id}/enable', 'identity:manage'],
  ['POST /api/admin/federation/oidc/clients/{id}/introspect', 'identity:manage'],
  ['POST /api/admin/federation/oidc/clients/{id}/secret', 'identity:manage'],
  ['POST /api/admin/federation/proposals/{id}/approve', 'identity:manage'],
  ['POST /api/admin/federation/proposals/{id}/reject', 'identity:manage'],
  ['POST /api/admin/federation/proposals/{id}/withdraw', 'identity:manage'],
  ['POST /api/admin/federation/saml/parse', 'identity:manage'],
  ['POST /api/admin/federation/saml/sps', 'identity:manage'],
  ['POST /api/admin/federation/sessions/revoke', 'identity:manage'],
  ['POST /api/admin/federation/test-login', 'identity:manage'],
  ['POST /api/admin/federation/upstream', 'identity:manage'],
  ['POST /api/admin/federation/upstream/check', 'identity:manage'],
  ['POST /api/admin/group-mappings', 'identity:manage'],
  ['POST /api/admin/guardrails/requests', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets/{id}/draft/approve', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets/{id}/draft/publish', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets/{id}/draft/submit', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets/{id}/promote', 'guardrails:manage'],
  ['POST /api/admin/guardrails/sets/{id}/replay', 'guardrails:manage'],
  ['POST /api/admin/guardrails/test', 'guardrails:manage'],
  ['POST /api/admin/guardrails/validate', 'guardrails:manage'],
  ['POST /api/admin/identity-providers', 'identity:manage'],
  ['POST /api/admin/identity-providers/{id}/sync', 'identity:manage'],
  ['POST /api/admin/identity-providers/{id}/test', 'identity:manage'],
  ['POST /api/admin/instances/{id}/drain', 'pools:manage'],
  ['POST /api/admin/instances/{id}/load', 'pools:manage'],
  ['POST /api/admin/instances/{id}/probe', 'pools:manage'],
  ['POST /api/admin/instances/{id}/undrain', 'pools:manage'],
  ['POST /api/admin/instances/{id}/unload', 'pools:manage'],
  ['POST /api/admin/mcp-servers', 'mcp:manage'],
  ['POST /api/admin/mcp-servers/{id}/bind', ['mcp:manage', 'profiles:manage']],
  ['POST /api/admin/mcp-servers/{id}/check', 'mcp:manage'],
  ['POST /api/admin/mcp-servers/{id}/tools/{tool}/approve', 'mcp:manage'],
  ['POST /api/admin/mcp-servers/{id}/tools/{tool}/reject-change', 'mcp:manage'],
  ['POST /api/admin/mcp-servers/{id}/tools/{tool}/revoke', 'mcp:manage'],
  ['POST /api/admin/models', 'models:manage'],
  ['POST /api/admin/models/{id}/evaluate', 'models:manage'],
  ['POST /api/admin/models/{id}/lifecycle', 'models:manage'],
  ['POST /api/admin/models/{id}/pull', 'models:manage'],
  ['POST /api/admin/placements', 'pools:manage'],
  ['POST /api/admin/platform/backups', 'platform:manage'],
  ['POST /api/admin/platform/backups/alert/acknowledge', 'platform:manage'],
  ['POST /api/admin/platform/backups/drills', 'platform:manage'],
  ['POST /api/admin/platform/bundles', 'platform:manage'],
  ['POST /api/admin/platform/bundles/{id}/promote', 'platform:manage'],
  ['POST /api/admin/platform/bundles/{id}/push', 'platform:manage'],
  ['POST /api/admin/platform/bundles/{id}/verify', 'platform:manage'],
  ['POST /api/admin/platform/certificates', 'platform:manage'],
  ['POST /api/admin/platform/certificates/{id}/hooks', 'platform:manage'],
  ['POST /api/admin/platform/certificates/{id}/hooks/{hookId}/test', 'platform:manage'],
  ['POST /api/admin/platform/certificates/{id}/key', 'platform:manage'],
  ['POST /api/admin/platform/certificates/{id}/renew', 'platform:manage'],
  ['POST /api/admin/platform/certificates/{id}/revoke', 'platform:manage'],
  ['POST /api/admin/platform/certificates/track', 'platform:manage'],
  ['POST /api/admin/platform/keys/{scope}/rotate', 'platform:manage'],
  ['POST /api/admin/platform/mirrors', 'platform:manage'],
  ['POST /api/admin/platform/mirrors/check', 'platform:manage'],
  ['POST /api/admin/platform/signers', 'platform:manage'],
  ['POST /api/admin/platform/signers/{id}/revoke', 'platform:manage'],
  ['POST /api/admin/platform/signers/proposals/{id}/approve', 'platform:manage'],
  ['POST /api/admin/platform/signers/proposals/{id}/reject', 'platform:manage'],
  ['POST /api/admin/platform/signers/proposals/{id}/withdraw', 'platform:manage'],
  ['POST /api/admin/plugins', 'plugins:manage'],
  ['POST /api/admin/plugins/{id}/disable', 'plugins:manage'],
  ['POST /api/admin/plugins/{id}/enable', 'plugins:manage'],
  ['POST /api/admin/plugins/import', 'plugins:manage'],
  ['POST /api/admin/plugins/validate', 'plugins:manage'],
  ['POST /api/admin/pools', 'pools:manage'],
  ['POST /api/admin/pools/{id}/instances', 'pools:manage'],
  ['POST /api/admin/pools/{id}/upgrade', 'pools:manage'],
  ['POST /api/admin/profiles', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/canary/promote', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/eval-sets', 'profiles:manage'],
  ['POST /api/admin/red-team/suites', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['POST /api/admin/red-team/run', { anyOf: ['profiles:manage', 'agents:manage', 'workflows:manage'] }],
  ['POST /api/admin/agent-identities/{name}/keys', 'agents:manage'],
  ['PUT /api/admin/agent-identities/{name}', 'agents:manage'],
  ['POST /api/admin/profiles/{id}/evaluations/overrides', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/evaluations/overrides/{oid}/decide', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/evaluations/run', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/publish', 'profiles:manage'],
  ['POST /api/admin/profiles/{id}/rollback', 'profiles:manage'],
  ['POST /api/admin/registry', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/checks', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/lifecycle', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/publish', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/review', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/submit', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/test', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/registry/{id}/versions', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['POST /api/admin/signups/{userId}/approve', 'users:manage'],
  ['POST /api/admin/signups/{userId}/reject', 'users:manage'],
  ['POST /api/admin/social/calendar-feeds/{id}/revoke', 'social:manage'],
  ['POST /api/admin/social/digest/test', 'social:manage'],
  ['POST /api/admin/social/exports', 'social:manage'],
  ['POST /api/admin/social/exports/{id}/approve', 'platform:manage'],
  ['POST /api/admin/social/exports/{id}/reject', 'platform:manage'],
  ['POST /api/admin/social/exports/{id}/withdraw', 'social:manage'],
  ['POST /api/admin/social/group-categories', 'social:manage'],
  ['POST /api/admin/social/groups/trending/run', 'social:manage'],
  ['POST /api/admin/social/groups/{id}/archive', 'social:manage'],
  ['POST /api/admin/social/groups/{id}/transfer', 'social:manage'],
  ['POST /api/admin/social/realtime/close', 'platform:manage'],
  ['POST /api/admin/social/trending/exclusions', 'social:manage'],
  ['POST /api/admin/social/trending/run', 'social:manage'],
  ['POST /api/admin/tenants', 'tenant:manage'],
  ['POST /api/admin/tenants/from-template', 'tenant:manage'],
  ['POST /api/admin/tenants/{tid}/offboard', 'tenant:manage'],
  ['POST /api/admin/tenants/{tid}/retention/run', 'tenant:manage'],
  ['POST /api/admin/tenants/{tid}/workspaces', 'tenant:manage'],
  ['POST /api/admin/tenants/{tid}/workspaces/{wid}/members', 'tenant:manage'],
  ['POST /api/admin/test-login', 'identity:manage'],
  ['POST /api/admin/usage/exports', 'usage:read'],
  ['POST /api/admin/user-imports', 'users:manage'],
  ['POST /api/admin/users', 'users:manage'],
  ['POST /api/admin/users/{id}/password', 'users:manage'],
  ['POST /api/admin/users/{id}/reset-mfa', 'users:manage'],
  ['POST /api/admin/webhooks', 'webhooks:manage'],
  ['POST /api/admin/webhooks/{id}/deliveries/{did}/replay', 'webhooks:manage'],
  ['POST /api/admin/webhooks/{id}/secret', 'webhooks:manage'],
  ['POST /api/admin/webhooks/{id}/test', 'webhooks:manage'],
  ['POST /api/admin/webhooks/signing-key/rotate', 'webhooks:manage'],
  ['POST /api/admin/zones', 'zones:manage'],
  ['POST /api/admin/zones-cluster/apply', 'zones:manage'],
  ['POST /api/admin/zones-cluster/check', 'zones:manage'],
  ['POST /api/admin/zones/{id}/draft/approve', 'zones:manage'],
  ['POST /api/admin/zones/{id}/draft/reject', 'zones:manage'],
  ['POST /api/admin/zones/{id}/draft/withdraw', 'zones:manage'],
  ['POST /api/admin/zones/{id}/endpoints', 'zones:manage'],
  ['POST /api/admin/zones/{id}/endpoints/check', 'zones:manage'],
  ['POST /api/admin/zones/{id}/members/{action}', 'zones:manage'],
  ['POST /api/admin/zones/{id}/proposals', 'zones:manage'],
  ['POST /api/admin/zones/seed', 'zones:manage'],
  ['POST /api/agent-schedules', 'agents:run'],
  ['POST /api/apps', 'apps:design'],
  ['POST /api/apps/{app}/entities', 'apps:design'],
  ['POST /api/apps/{app}/entities/{entity}/records', 'records:write'],
  ['POST /api/apps/{app}/entities/{entity}/records/{id}/transition', 'records:write'],
  ['POST /api/apps/{app}/entities/{entity}/records/aggregate', 'records:read'],
  ['POST /api/apps/{app}/entities/{entity}/records/bulk', 'records:write'],
  ['POST /api/apps/{app}/entities/{entity}/records/export', 'records:read'],
  ['POST /api/apps/{app}/entities/{entity}/records/import', 'records:write'],
  ['POST /api/apps/{app}/entities/{entity}/records/query', 'records:read'],
  ['POST /api/apps/{app}/forms', 'apps:design'],
  ['POST /api/apps/{app}/forms/{form}/public', 'apps:design'],
  ['POST /api/apps/{app}/forms/{form}/submit', 'records:write'],
  ['POST /api/apps/{app}/triggers', 'apps:design'],
  ['POST /api/apps/drafts', 'apps:design'],
  ['POST /api/apps/import', 'apps:design'],
  ['POST /api/atproto/feeds', 'firehose:manage'],
  ['POST /api/atproto/firehose', 'firehose:manage'],
  ['POST /api/atproto/firehose/{id}/start', 'firehose:manage'],
  ['POST /api/atproto/firehose/{id}/stop', 'firehose:manage'],
  ['POST /api/atproto/identity', 'pki:manage'],
  ['POST /api/atproto/identity/rotate', 'pki:manage'],
  ['POST /api/atproto/labelers', 'labels:manage'],
  ['POST /api/atproto/labelers/{id}/pull', 'labels:manage'],
  ['POST /api/atproto/labels', 'labels:manage'],
  ['POST /api/atproto/labels/negate', 'labels:manage'],
  ['POST /api/auth/device', 'authenticated'],
  ['POST /api/auth/email/resend', 'public'],
  ['POST /api/auth/email/verify', 'public'],
  ['POST /api/auth/invitations/accept', 'public'],
  ['POST /api/auth/invitations/preview', 'public'],
  ['POST /api/auth/login', 'public'],
  ['POST /api/auth/logout', 'public'],
  ['POST /api/auth/mfa/email', 'authenticated'],
  ['POST /api/auth/mfa/email/send', 'authenticated'],
  ['POST /api/auth/mfa/recovery', 'authenticated'],
  ['POST /api/auth/mfa/totp', 'authenticated'],
  ['POST /api/auth/mfa/webauthn', 'authenticated'],
  ['POST /api/auth/mfa/webauthn/options', 'authenticated'],
  ['POST /api/auth/password/check', 'public'],
  ['POST /api/auth/password/forgot', 'public'],
  ['POST /api/auth/password/reset', 'public'],
  ['POST /api/auth/register', 'public'],
  ['POST /api/authz/reviews', 'roles:manage'],
  ['POST /api/authz/reviews/{id}/close', 'roles:manage'],
  ['POST /api/authz/reviews/{id}/items/{itemId}/decision', 'authenticated'],
  ['POST /api/authz/reviews/{id}/open', 'roles:manage'],
  ['POST /api/authz/roles', 'roles:manage'],
  ['POST /api/authz/roles/{id}/versions/{version}/approve', 'roles:manage'],
  ['POST /api/authz/roles/{id}/versions/{version}/reject', 'roles:manage'],
  ['POST /api/calculate', 'inference:invoke'],
  ['POST /api/calendar/events/{id}/cancel', 'groups:write'],
  ['POST /api/calendar/events/{id}/check-in', 'groups:write'],
  ['POST /api/calendar/events/{id}/rsvp', 'groups:write'],
  ['POST /api/calendar/feeds', 'groups:write'],
  ['POST /api/channels', 'channels:manage'],
  ['POST /api/channels/{id}/exports', 'channels:review'],
  ['POST /api/channels/{id}/poll', 'channels:manage'],
  ['POST /api/channels/{id}/purge', 'channels:manage'],
  ['POST /api/channels/{id}/secrets', 'channels:manage'],
  ['POST /api/channels/{id}/sessions/{sessionId}/close', 'channels:review'],
  ['POST /api/channels/{id}/sessions/{sessionId}/messages', 'channels:review'],
  ['POST /api/channels/held/{id}/decide', 'channels:review'],
  ['POST /api/chat', ['chat:write', 'inference:invoke']],
  ['POST /api/classify', { anyOf: ['classifiers:manage', 'inference:invoke'] }],
  ['POST /api/compare', ['chat:write', 'inference:invoke']],
  ['POST /api/conversations', 'chat:write'],
  ['POST /api/conversations/{id}/exports', 'chat:read'],
  ['POST /api/conversations/{id}/messages', ['chat:write', 'inference:invoke']],
  ['POST /api/conversations/{id}/messages/{mid}/continue', ['chat:write', 'inference:invoke']],
  ['POST /api/conversations/{id}/messages/{mid}/edit', ['chat:write', 'inference:invoke']],
  ['POST /api/conversations/{id}/messages/{mid}/regenerate', ['chat:write', 'inference:invoke']],
  ['POST /api/conversations/{id}/messages/{mid}/stop', 'chat:write'],
  ['POST /api/conversations/{id}/shares', 'chat:write'],
  ['POST /api/feed/posts', 'feed:write'],
  ['POST /api/feed/posts/{id}/comments', 'feed:write'],
  ['POST /api/feed/posts/{id}/repost', 'feed:write'],
  ['POST /api/feed/workspaces/{id}/digest', 'feed:manage'],
  ['POST /api/file-links/download', 'files:read'],
  ['POST /api/file-links/open', 'files:read'],
  ['POST /api/files/{id}/shares', 'files:write'],
  ['POST /api/files/{id}/versions/{n}/restore', 'files:write'],
  ['POST /api/files/folders', 'files:write'],
  ['POST /api/files/trash/empty', 'files:write'],
  ['POST /api/files/trash/restore', 'files:write'],
  ['POST /api/flags/{ref}/decide', 'flags:review'],
  ['POST /api/flags/{ref}/escalate', 'flags:review'],
  ['POST /api/flags/{ref}/eval', 'flags:review'],
  ['POST /api/flags/{ref}/reassign', 'flags:review'],
  ['POST /api/flags/{ref}/rule', ['flags:review', 'guardrails:manage']],
  ['POST /api/flags/report', 'chat:read'],
  ['POST /api/group-requests/{id}/accept', 'groups:write'],
  ['POST /api/group-requests/{id}/decline', 'groups:write'],
  ['POST /api/groups', 'groups:write'],
  ['POST /api/groups/{id}/channels', 'groups:write'],
  ['POST /api/groups/{id}/events', 'groups:write'],
  ['POST /api/groups/{id}/invites', 'groups:write'],
  ['POST /api/groups/{id}/join', 'groups:write'],
  ['POST /api/groups/{id}/posts', 'groups:write'],
  ['POST /api/images', 'images:generate'],
  ['POST /api/images/{id}/attach', ['chat:write', 'images:generate']],
  ['POST /api/images/{id}/cancel', 'images:generate'],
  ['POST /api/images/{id}/vary', 'images:generate'],
  ['POST /api/images/report', 'images:generate'],
  ['POST /api/invitations', 'members:invite'],
  ['POST /api/knowledge/bases', 'knowledge:read'],
  ['POST /api/knowledge/bases/{id}/access', 'knowledge:read'],
  ['POST /api/knowledge/bases/{id}/cancel-build', 'knowledge:read'],
  ['POST /api/knowledge/bases/{id}/reindex', 'knowledge:read'],
  ['POST /api/knowledge/bases/{id}/sources', 'knowledge:read'],
  ['POST /api/knowledge/documents/{id}/reindex', 'knowledge:read'],
  ['POST /api/knowledge/search', 'knowledge:read'],
  ['POST /api/knowledge/sources/{id}/sync', 'knowledge:read'],
  ['POST /api/me/api-keys', 'authenticated'],
  ['POST /api/me/atproto/claim', 'atproto:link'],
  ['POST /api/me/atproto/link', 'atproto:link'],
  ['POST /api/me/atproto/verify', 'atproto:link'],
  ['POST /api/me/email/verify', 'authenticated'],
  ['POST /api/me/invitations/accept', 'authenticated'],
  ['POST /api/me/jobs/{id}/cancel', 'authenticated'],
  ['POST /api/me/mfa/email', 'authenticated'],
  ['POST /api/me/mfa/email/{id}/confirm', 'authenticated'],
  ['POST /api/me/mfa/recovery-codes', 'authenticated'],
  ['POST /api/me/mfa/totp', 'authenticated'],
  ['POST /api/me/mfa/totp/{id}/confirm', 'authenticated'],
  ['POST /api/me/mfa/webauthn', 'authenticated'],
  ['POST /api/me/mfa/webauthn/options', 'authenticated'],
  ['POST /api/me/notifications/read', 'authenticated'],
  ['POST /api/me/password', 'authenticated'],
  ['POST /api/me/sessions/revoke-others', 'authenticated'],
  ['POST /api/me/step-up', 'authenticated'],
  ['POST /api/me/step-up/upstream', 'authenticated'],
  ['POST /api/me/step-up/upstream/complete', 'authenticated'],
  ['POST /api/me/step-up/webauthn/options', 'authenticated'],
  ['POST /api/media/assets/{id}/jobs', 'chat:write'],
  ['POST /api/media/caps/request', 'chat:write'],
  ['POST /api/media/jobs/{id}/cancel', 'chat:write'],
  ['POST /api/media/jobs/{id}/knowledge', 'chat:write'],
  ['POST /api/memory', 'memory:write'],
  ['POST /api/memory/{id}/accept', 'memory:write'],
  ['POST /api/memory/{id}/reject', 'memory:write'],
  ['POST /api/memory/{id}/expiry/accept', 'memory:write'],
  ['POST /api/memory/{id}/expiry/reject', 'memory:write'],
  ['POST /api/memory/exports', 'memory:write'],
  ['POST /api/memory/consolidate', 'knowledge:manage'],
  ['POST /api/memory/reindex', 'knowledge:manage'],
  ['POST /api/messaging/conversations', 'messages:write'],
  ['POST /api/messaging/conversations/{id}/delivered', 'messages:read'],
  ['POST /api/messaging/conversations/{id}/digest', ['inference:invoke', 'messages:read']],
  ['POST /api/messaging/conversations/{id}/members', 'messages:write'],
  ['POST /api/messaging/conversations/{id}/messages', 'messages:write'],
  ['POST /api/messaging/conversations/{id}/read', 'messages:read'],
  ['POST /api/messaging/conversations/{id}/summary', ['inference:invoke', 'messages:read']],
  ['POST /api/messaging/messages/{id}/forward', 'messages:write'],
  ['POST /api/messaging/messages/{id}/pin', 'messages:write'],
  ['POST /api/messaging/messages/{id}/reactions', 'messages:write'],
  ['POST /api/moderation/appeals', { anyOf: ['moderation:appeal', 'moderation:review'] }],
  ['POST /api/moderation/appeals/{ref}/decide', 'moderation:review'],
  ['POST /api/moderation/appeals/{ref}/review', 'moderation:review'],
  ['POST /api/moderation/batch', 'moderation:check'],
  ['POST /api/moderation/check', 'moderation:check'],
  ['POST /api/moderation/dead-letters/{id}/redrive', 'moderation:manage'],
  ['POST /api/moderation/flags/{ref}/action', 'moderation:review'],
  ['POST /api/moderation/providers', 'moderation:manage'],
  ['POST /api/moderation/queues', 'moderation:manage'],
  ['POST /api/moderation/reports', 'moderation:report'],
  ['POST /api/moderation/sanctions', 'moderation:sanction'],
  ['POST /api/moderation/sanctions/{id}/lift', 'moderation:sanction'],
  ['POST /api/pki/acme/accounts/{id}/revoke', 'pki:manage'],
  ['POST /api/pki/acme/eab-keys', 'pki:manage'],
  ['POST /api/pki/acme/eab-keys/{id}/revoke', 'pki:manage'],
  ['POST /api/pki/certificates/{id}/pkcs12', 'pki:manage'],
  ['POST /api/pki/certificates/{id}/renew', 'pki:manage'],
  ['POST /api/pki/certificates/{id}/revoke', 'pki:manage'],
  ['POST /api/pki/issuers', 'pki:manage'],
  ['POST /api/pki/issuers/{id}/crl', 'pki:manage'],
  ['POST /api/pki/issuers/{id}/issue', 'pki:manage'],
  ['POST /api/pki/issuers/{id}/reissue', 'pki:manage'],
  ['POST /api/pki/issuers/{id}/revoke', 'pki:manage'],
  ['POST /api/pki/issuers/{id}/rotate', 'pki:manage'],
  ['POST /api/pki/profiles', 'pki:manage'],
  ['POST /api/prompts', 'prompts:manage'],
  ['POST /api/prompts/{id}/render', 'chat:read'],
  ['POST /api/prompts/{id}/state', 'prompts:manage'],
  ['POST /api/prompts/{id}/versions', 'prompts:manage'],
  ['POST /api/public/channels/{key}/email/{provider}', 'public'],
  ['POST /api/public/channels/session/close', 'public'],
  ['POST /api/public/channels/session/escalate', 'public'],
  ['POST /api/public/channels/session/messages', 'public'],
  ['POST /api/public/channels/sessions', 'public'],
  ['POST /api/public/file-links/download', 'public'],
  ['POST /api/public/forms/open', 'public'],
  ['POST /api/public/forms/submit', 'public'],
  ['POST /api/public/shared-links/open', 'public'],
  ['POST /api/runs', 'agents:run'],
  ['POST /api/runs/{id}/cancel', { anyOf: ['agents:manage', 'agents:run'] }],
  ['POST /api/runs/{id}/replay', { anyOf: ['agents:manage', 'agents:run'] }],
  ['POST /api/runs/{id}/resume', { anyOf: ['agents:manage', 'agents:run'] }],
  ['POST /api/runs/{id}/steps/{n}/decision', { anyOf: ['agents:run', 'tools:manage'] }],
  ['POST /api/scripts', 'scripts:run'],
  ['POST /api/scripts/{id}/checks', 'scripts:run'],
  ['POST /api/scripts/{id}/promote', { all: ['scripts:run'], anyOf: ['tools:manage', 'workflows:manage'] }],
  ['POST /api/scripts/{id}/restore', 'scripts:run'],
  ['POST /api/scripts/{id}/run', 'scripts:run'],
  ['POST /api/shared-links/open', 'chat:read'],
  ['POST /api/social/blocks', 'social:write'],
  ['POST /api/social/following', 'social:write'],
  ['POST /api/social/lists', 'social:write'],
  ['POST /api/social/lists/{id}/members', 'social:write'],
  ['POST /api/social/mutes', 'social:write'],
  ['POST /api/training/datasets', 'training:submit'],
  ['POST /api/training/datasets/{id}/withdraw', 'training:manage'],
  ['POST /api/training/evals', 'training:submit'],
  ['POST /api/training/jobs', 'training:submit'],
  ['POST /api/training/jobs/{id}/approve', 'training:manage'],
  ['POST /api/training/jobs/{id}/cancel', 'training:submit'],
  ['POST /api/training/jobs/{id}/pause', 'training:submit'],
  ['POST /api/training/jobs/{id}/resume', 'training:submit'],
  ['POST /api/training/jobs/{id}/retry', 'training:submit'],
  ['POST /api/training/schedules', 'training:manage'],
  ['POST /api/training/windows', 'training:manage'],
  ['POST /api/vault/database/creds/{engine}/{role}', 'secrets:read'],
  ['POST /api/vault/database/engines', 'connections:manage'],
  ['POST /api/vault/database/engines/{name}/test', 'connections:manage'],
  ['POST /api/vault/database/leases/{id}/renew', 'secrets:read'],
  ['POST /api/vault/database/leases/{id}/revoke', 'secrets:read'],
  ['POST /api/vault/database/sweep', 'connections:manage'],
  ['POST /api/vault/kv/delete/{path}', 'secrets:write'],
  ['POST /api/vault/kv/destroy/{path}', 'secrets:admin'],
  ['POST /api/vault/kv/undelete/{path}', 'secrets:write'],
  ['POST /api/vault/policies', 'secrets:admin'],
  ['POST /api/vault/policies/explain', 'secrets:read'],
  ['POST /api/vault/transit/decrypt/{name}', 'secrets:read'],
  ['POST /api/vault/transit/encrypt/{name}', 'secrets:read'],
  ['POST /api/vault/transit/keys', 'secrets:admin'],
  ['POST /api/vault/transit/keys/{name}/rotate', 'secrets:admin'],
  ['POST /api/vault/transit/keys/{name}/trim', 'secrets:admin'],
  ['POST /api/vault/transit/rewrap/{name}', 'secrets:read'],
  ['POST /api/vault/transit/sign/{name}', 'secrets:read'],
  ['POST /api/vault/transit/verify/{name}', 'secrets:read'],
  ['POST /api/workflow-approvals/{id}', 'authenticated'],
  ['POST /api/workflow-dead-letters/{id}/redrive', 'workflows:manage'],
  ['POST /api/workflow-runs/{id}/cancel', 'agents:run'],
  ['POST /api/workflow-runs/{id}/replay', 'agents:run'],
  ['POST /api/workflows', 'workflows:manage'],
  ['POST /api/workflows/import', 'workflows:manage'],
  ['POST /api/workflows/{id}/dry-run', 'workflows:manage'],
  ['POST /api/workflows/{id}/publish', 'workflows:manage'],
  ['POST /api/workflows/{id}/runs', 'agents:run'],
  ['POST /api/workflows/{id}/tool', 'workflows:manage'],
  ['POST /api/workflows/{id}/validate', 'agents:run'],
  ['POST /billing/stripe/webhook', 'public'],
  ['POST /federation/saml/acs', 'public'],
  ['POST /federation/saml/slo', 'public'],
  ['POST /oauth/authorize', 'public'],
  ['POST /oauth/device_authorization', 'public'],
  ['POST /oauth/introspect', 'public'],
  ['POST /oauth/logout', 'public'],
  ['POST /oauth/par', 'public'],
  ['POST /oauth/revoke', 'public'],
  ['POST /oauth/token', 'public'],
  ['POST /oauth/userinfo', 'public'],
  ['POST /pki/acme/{tenant}/{rest}', 'public'],
  ['POST /pki/ocsp', 'public'],
  ['POST /plugin-broker/v1/calls/{api}', 'public'],
  ['POST /saml/slo', 'public'],
  ['POST /saml/sso', 'public'],
  ['POST /t/{tenant}/federation/saml/acs', 'public'],
  ['POST /t/{tenant}/federation/saml/slo', 'public'],
  ['POST /t/{tenant}/oauth/authorize', 'public'],
  ['POST /t/{tenant}/oauth/device_authorization', 'public'],
  ['POST /t/{tenant}/oauth/introspect', 'public'],
  ['POST /t/{tenant}/oauth/logout', 'public'],
  ['POST /t/{tenant}/oauth/par', 'public'],
  ['POST /t/{tenant}/oauth/revoke', 'public'],
  ['POST /t/{tenant}/oauth/token', 'public'],
  ['POST /t/{tenant}/oauth/userinfo', 'public'],
  ['POST /t/{tenant}/saml/slo', 'public'],
  ['POST /t/{tenant}/saml/sso', 'public'],
  ['POST /trainer/v1/keys/{grant}', 'public'],
  ['POST /v1/chat/completions', 'inference:invoke'],
  ['POST /v1/embeddings', 'inference:invoke'],
  ['POST /v1/responses', 'inference:invoke'],
  ['PUT /api/admin/billing/tenants/{tenantId}', 'billing:manage'],
  ['PUT /api/admin/connections/{id}/allow-list', 'connections:manage'],
  ['PUT /api/admin/connections/{id}/credential', 'connections:manage'],
  ['PUT /api/admin/federation/metadata/{id}', 'identity:manage'],
  ['PUT /api/admin/guardrails/sets/{id}/draft', 'guardrails:manage'],
  ['PUT /api/admin/guardrails/sets/{id}/draft/rules/{ruleId}', 'guardrails:manage'],
  ['PUT /api/admin/identity-policy/mfa', 'identity:manage'],
  ['PUT /api/admin/identity-policy/signup', 'identity:manage'],
  ['PUT /api/admin/integrations/hosts', 'tenant:manage'],
  ['PUT /api/admin/label-names', 'classifiers:manage'],
  ['PUT /api/admin/mcp-servers/{id}/credential', 'mcp:manage'],
  ['PUT /api/admin/platform/bundles/{id}/transfer', 'platform:manage'],
  ['PUT /api/admin/platform/mirrors/{id}/push-target', 'platform:manage'],
  ['PUT /api/admin/plugins/{id}/grants', 'plugins:manage'],
  ['PUT /api/admin/profiles/{id}/canary', 'profiles:manage'],
  ['PUT /api/admin/social/policies/{id}', 'social:manage'],
  ['PUT /api/admin/social/settings', 'social:manage'],
  ['PUT /api/admin/tenants/{tid}/file-quota', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/quota', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/retention', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/retention/scopes', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/sharing', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/workspaces/{wid}/file-quota', 'tenant:manage'],
  ['PUT /api/admin/tenants/{tid}/workspaces/{wid}/quota', 'tenant:manage'],
  ['PUT /api/attachments', 'chat:write'],
  ['PUT /api/atproto/feeds/{id}/publication', 'firehose:manage'],
  ['PUT /api/conversations/{id}/knowledge', 'context:write'],
  ['PUT /api/feed/posts/{id}/bookmark', 'feed:write'],
  ['PUT /api/feed/posts/{id}/reactions/{kind}', 'feed:write'],
  ['PUT /api/feed/workspaces/{id}/settings', 'feed:manage'],
  ['PUT /api/files/{id}/content', 'files:write'],
  ['PUT /api/files/{id}/tags', 'files:write'],
  ['PUT /api/files/uploads', 'files:write'],
  ['PUT /api/knowledge/bases/{id}/uploads', 'knowledge:read'],
  ['PUT /api/mcp/servers/{id}/token', 'tools:invoke'],
  ['PUT /api/me/api-keys/{id}/signature-key', 'authenticated'],
  ['PUT /api/me/atproto/handle', 'atproto:link'],
  ['PUT /api/me/workspace', 'authenticated'],
  ['PUT /api/media/assets', 'chat:write'],
  ['PUT /api/memory/settings', 'knowledge:manage'],
  ['PUT /api/messaging/conversations/{id}/settings', 'messages:write'],
  ['PUT /api/people/me/avatar', 'social:write'],
  ['PUT /api/pki/acme', 'pki:manage'],
  ['PUT /api/presence/me', 'social:write'],
  ['PUT /api/social/settings', 'social:write'],
  ['PUT /api/training/settings', 'training:manage'],
  ['PUT /api/vault/database/engines/{name}/roles/{role}', 'connections:manage'],
  ['PUT /api/vault/kv/data/{path}', 'secrets:write'],
  ['PUT /api/workflows/{id}/draft', 'workflows:manage'],
  ['PUT /trainer/v1/artifacts/{grant}/{name}', 'public'],
  ['COPY /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['COPY /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['DELETE /api/me/app-passwords/{id}', 'authenticated'],
  ['DELETE /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['DELETE /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['GET /.well-known/caldav', 'public'],
  ['GET /.well-known/carddav', 'public'],
  ['GET /api/me/app-passwords', 'authenticated'],
  ['GET /api/me/dav', 'authenticated'],
  ['GET /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['GET /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['HEAD /.well-known/caldav', 'public'],
  ['HEAD /.well-known/carddav', 'public'],
  ['HEAD /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['HEAD /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MKCALENDAR /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MKCALENDAR /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MKCOL /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MKCOL /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MOVE /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['MOVE /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['OPTIONS /.well-known/caldav', 'public'],
  ['OPTIONS /.well-known/carddav', 'public'],
  ['OPTIONS /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['OPTIONS /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['POST /api/me/app-passwords', 'authenticated'],
  ['PROPFIND /.well-known/caldav', 'public'],
  ['PROPFIND /.well-known/carddav', 'public'],
  ['PROPFIND /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['PROPFIND /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['PROPPATCH /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['PROPPATCH /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['PUT /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['PUT /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['REPORT /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['REPORT /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['DELETE /api/admin/pds/invites/{id}', 'pds:manage'],
  ['DELETE /api/me/pds/app-passwords/{id}', 'atproto:link'],
  ['GET /api/admin/pds', 'pds:manage'],
  ['GET /api/admin/pds/accounts', 'pds:manage'],
  ['GET /api/admin/pds/accounts/{id}', 'pds:manage'],
  ['GET /api/admin/pds/feed-generators', 'pds:manage'],
  ['GET /api/admin/pds/invites', 'pds:manage'],
  ['GET /api/admin/pds/tenants', 'platform:manage'],
  ['GET /api/me/pds', 'atproto:link'],
  ['GET /xrpc/com.atproto.identity.getRecommendedDidCredentials', 'atproto:link'],
  ['GET /xrpc/com.atproto.identity.resolveHandle', 'public'],
  ['GET /xrpc/com.atproto.repo.describeRepo', 'public'],
  ['GET /xrpc/com.atproto.repo.getRecord', 'public'],
  ['GET /xrpc/com.atproto.repo.listMissingBlobs', 'atproto:link'],
  ['GET /xrpc/com.atproto.repo.listRecords', 'public'],
  ['GET /xrpc/com.atproto.server.checkAccountStatus', 'atproto:link'],
  ['GET /xrpc/com.atproto.server.describeServer', 'public'],
  ['GET /xrpc/com.atproto.server.getServiceAuth', 'atproto:link'],
  ['GET /xrpc/com.atproto.server.getSession', 'atproto:link'],
  ['GET /xrpc/com.atproto.sync.getBlob', 'public'],
  ['GET /xrpc/com.atproto.sync.getBlocks', 'public'],
  ['GET /xrpc/com.atproto.sync.getLatestCommit', 'public'],
  ['GET /xrpc/com.atproto.sync.getRecord', 'public'],
  ['GET /xrpc/com.atproto.sync.getRepo', 'public'],
  ['GET /xrpc/com.atproto.sync.getRepoStatus', 'public'],
  ['GET /xrpc/com.atproto.sync.listBlobs', 'public'],
  ['GET /xrpc/com.atproto.sync.listRepos', 'public'],
  ['PATCH /api/admin/pds/settings', 'pds:manage'],
  ['POST /api/admin/pds/accounts/{id}/activate', 'pds:manage'],
  ['POST /api/admin/pds/accounts/{id}/deactivate', 'pds:manage'],
  ['POST /api/admin/pds/accounts/{id}/restore', 'pds:manage'],
  ['POST /api/admin/pds/accounts/{id}/takedown', 'pds:manage'],
  ['POST /api/admin/pds/crawl', 'platform:manage'],
  ['POST /api/admin/pds/feed-generators', 'pds:manage'],
  ['POST /api/admin/pds/feed-generators/{id}/withdraw', 'pds:manage'],
  ['POST /api/admin/pds/invites', 'pds:manage'],
  ['POST /api/me/pds', 'atproto:link'],
  ['POST /api/me/pds/activate', 'atproto:link'],
  ['POST /api/me/pds/app-passwords', 'atproto:link'],
  ['POST /api/me/pds/deactivate', 'atproto:link'],
  ['POST /api/me/pds/plc-token', 'atproto:link'],
  ['POST /xrpc/com.atproto.identity.requestPlcOperationSignature', 'atproto:link'],
  ['POST /xrpc/com.atproto.identity.signPlcOperation', 'atproto:link'],
  ['POST /xrpc/com.atproto.identity.submitPlcOperation', 'atproto:link'],
  ['POST /xrpc/com.atproto.identity.updateHandle', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.applyWrites', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.createRecord', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.deleteRecord', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.importRepo', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.putRecord', 'atproto:link'],
  ['POST /xrpc/com.atproto.repo.uploadBlob', 'atproto:link'],
  ['POST /xrpc/com.atproto.server.activateAccount', 'atproto:link'],
  ['POST /xrpc/com.atproto.server.createAccount', 'public'],
  ['POST /xrpc/com.atproto.server.createSession', 'public'],
  ['POST /xrpc/com.atproto.server.deactivateAccount', 'atproto:link'],
  ['POST /xrpc/com.atproto.server.deleteSession', 'public'],
  ['POST /xrpc/com.atproto.server.refreshSession', 'public'],
  ['PUT /api/admin/pds/tenants/{tid}', 'platform:manage'],
  ['PUT /api/me/pds/handle', 'atproto:link'],
  ['DELETE /api/imports/repositories/{id}', 'imports:repositories'],
  ['GET /api/imports', 'imports:run'],
  ['GET /api/imports/{id}', 'imports:run'],
  ['GET /api/imports/bundle-requests', 'platform:manage'],
  ['GET /api/imports/exceptions', { anyOf: ['imports:review', 'imports:run'] }],
  ['GET /api/imports/proxy-allowlist', 'platform:manage'],
  ['GET /api/imports/quota', { anyOf: ['imports:run', 'usage:read'] }],
  ['GET /api/imports/repositories', 'imports:run'],
  ['GET /api/imports/repositories/{id}', 'imports:run'],
  ['GET /api/imports/repositories/{id}/catalog', 'imports:run'],
  ['GET /api/imports/repositories/{id}/item', 'imports:run'],
  ['GET /api/imports/settings', { anyOf: ['imports:review', 'imports:run'] }],
  ['GET /api/imports/types', 'imports:run'],
  ['PATCH /api/imports/repositories/{id}', 'imports:repositories'],
  ['POST /api/imports', 'imports:run'],
  ['POST /api/imports/{id}/cancel', 'imports:run'],
  ['POST /api/imports/{id}/retry', 'imports:run'],
  ['POST /api/imports/exceptions/{id}/decision', 'imports:review'],
  ['POST /api/imports/plan', 'imports:run'],
  ['POST /api/imports/repositories', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/check', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/confirm', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/disable', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/enable', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/gate', 'imports:run'],
  ['POST /api/imports/repositories/{id}/harvest', 'imports:repositories'],
  ['POST /api/imports/repositories/{id}/reject', 'imports:repositories'],
  ['PUT /api/admin/tenants/{tid}/import-quota', 'tenant:manage'],
  ['PUT /api/imports/settings/licences', 'imports:review'],
  ['GET /api/admin/registry/{id}/used-by', { anyOf: ['agents:manage', 'tools:manage'] }],
  ['GET /api/chains/{id}', { anyOf: ['agents:manage', 'agents:run', 'tools:manage', 'workflows:manage'] }],
  ['GET /api/workflows/{id}/used-by', 'agents:run'],
  ['POST /api/chains/{id}/held/{node}/decision', { anyOf: ['agents:manage', 'agents:run', 'tools:manage', 'workflows:manage'] }],
  ['POST /api/chains/{id}/nodes/{node}/replay', { anyOf: ['agents:manage', 'agents:run'] }],
  ['LOCK /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['LOCK /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['UNLOCK /dav', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  ['UNLOCK /dav/{path}', { anyOf: ['calendars:read', 'contacts:read', 'files:read', 'groups:read'] }],
  // 1.6.0, Sprint 35b (B-4202, B-4203): the Overview and Jobs and queues screens
  ['GET /api/admin/cache', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/dead-letters', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/jobs', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/jobs/{id}', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/overview', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/queues', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['GET /api/admin/schedules', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/cache/{ns}/invalidate', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/dead-letters/{source}/{id}/discard', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/dead-letters/{source}/{id}/redrive', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/jobs/retry-failed', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/jobs/{id}/cancel', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/jobs/{id}/retry', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/overview/alerts/acknowledge', { anyOf: ['platform:manage', 'tenant:manage'] }],
  ['POST /api/admin/overview/instances/{id}/drain', 'platform:manage'],
  ['POST /api/admin/queues/{type}/pause', 'platform:manage'],
  ['POST /api/admin/queues/{type}/resume', 'platform:manage'],
  ['POST /api/admin/schedules/{name}/pause', 'platform:manage'],
  ['POST /api/admin/schedules/{name}/resume', 'platform:manage'],
  ['POST /api/admin/schedules/{name}/run', 'platform:manage'],
  // 1.6.0, Sprint 35c (B-4204, B-4205): Storage and Configuration
  ['GET /api/admin/platform/settings', 'platform:manage'],
  ['GET /api/admin/platform/settings/export', 'platform:manage'],
  ['GET /api/admin/storage/integrity', 'platform:manage'],
  ['GET /api/admin/storage/migrations', 'platform:manage'],
  ['GET /api/admin/storage/purges', 'platform:manage'],
  ['GET /api/admin/storage/quarantine', 'platform:manage'],
  ['GET /api/admin/storage/stores', 'platform:manage'],
  ['GET /api/admin/storage/usage', 'platform:manage'],
  ['POST /api/admin/platform/settings/{name}/proposals', 'platform:manage'],
  ['POST /api/admin/platform/settings/proposals/{id}/approve', 'platform:manage'],
  ['POST /api/admin/platform/settings/proposals/{id}/reject', 'platform:manage'],
  ['POST /api/admin/platform/settings/proposals/{id}/withdraw', 'platform:manage'],
  ['POST /api/admin/storage/findings/{id}/accept', 'platform:manage'],
  ['POST /api/admin/storage/integrity/verify', 'platform:manage'],
  ['POST /api/admin/storage/migrations', 'platform:manage'],
  ['POST /api/admin/storage/migrations/{id}/retire', 'platform:manage'],
  ['POST /api/admin/storage/orphans/delete', 'platform:manage'],
  ['POST /api/admin/storage/orphans/dry-run', 'platform:manage'],
  ['POST /api/admin/storage/quarantine/{kind}/{id}/delete', 'platform:manage'],
  ['POST /api/admin/storage/quarantine/{kind}/{id}/rescan', 'platform:manage'],
  // 1.6.0, Sprint 36b (B-4701, B-4803): held form submissions and reveal flags
  ['GET /api/apps/held', { anyOf: ['flags:review', 'moderation:review'] }],
  ['GET /api/apps/held/{id}', { anyOf: ['flags:review', 'moderation:review'] }],
  ['POST /api/apps/held/{id}/decide', { anyOf: ['flags:review', 'moderation:review'] }],
  ['GET /api/vault/reveal-flags', 'secrets:read'],
  ['GET /api/vault/reveal-flags/{id}', 'secrets:read'],
  ['POST /api/vault/reveal-flags/{id}/resolve', 'secrets:read'],
  ['GET /api/knowledge/bases/{id}/labels', 'knowledge:read'],
  ['GET /api/knowledge/documents/{id}/thumbnail', 'knowledge:read'],
  ['POST /api/knowledge/bases/{id}/reclassify', 'knowledge:read'],
  ['POST /api/knowledge/documents/{id}/reclassify', 'knowledge:read'],
  ['PUT /api/admin/classifiers/{id}/samples/image', 'classifiers:manage'],
  ['GET /api/admin/guardrails/injection', 'guardrails:manage'],
  ['DELETE /api/admin/mcp-servers/{id}/oauth', 'mcp:manage'],
  ['DELETE /mcp/{tenant}/{workspace}', 'public'],
  ['GET /.well-known/oauth-authorization-server', 'public'],
  ['GET /.well-known/oauth-authorization-server/t/{tenant}', 'public'],
  ['GET /.well-known/oauth-protected-resource/mcp/{tenant}/{workspace}', 'public'],
  ['GET /.well-known/openid-configuration/t/{tenant}', 'public'],
  ['GET /api/admin/mcp-server', 'identity:manage'],
  ['GET /api/admin/mcp-server/workspaces/{workspaceId}/tools', 'identity:manage'],
  ['GET /api/mcp-oauth/callback', 'public'],
  ['GET /api/me/mcp-holds', 'authenticated'],
  ['GET /api/me/mcp-server', 'authenticated'],
  ['GET /mcp/{tenant}/{workspace}', 'public'],
  ['GET /t/{tenant}/.well-known/oauth-authorization-server', 'public'],
  ['POST /api/admin/mcp-servers/{id}/oauth/discover', 'mcp:manage'],
  ['POST /api/mcp-oauth/start', 'tools:invoke'],
  ['POST /api/me/mcp-holds/{id}/decide', 'authenticated'],
  ['POST /mcp/{tenant}/{workspace}', 'authenticated'],
  ['POST /oauth/register', 'public'],
  ['POST /t/{tenant}/oauth/register', 'public'],
  ['PUT /api/admin/mcp-server/settings', 'identity:manage'],
  ['PUT /api/admin/mcp-server/workspaces/{workspaceId}', 'identity:manage'],
  ['PUT /api/admin/mcp-servers/{id}/oauth', 'mcp:manage'],
  // 1.6.0, Sprint 37c (B-7201, B-7202): SCIM 2.0 (a SCIM token is the credential) and its tokens under Identity
  ['GET /api/admin/identity-providers/{id}/scim', 'identity:manage'],
  ['POST /api/admin/identity-providers/{id}/scim/tokens', 'identity:manage'],
  ['DELETE /api/admin/identity-providers/{id}/scim/tokens/{tokenId}', 'identity:manage'],
  ['POST /api/admin/identity-providers/{id}/scim/reapply', 'identity:manage'],
  ['GET /scim/v2/ServiceProviderConfig', 'public'],
  ['GET /scim/v2/ResourceTypes', 'public'],
  ['GET /scim/v2/ResourceTypes/{id}', 'public'],
  ['GET /scim/v2/Schemas', 'public'],
  ['GET /scim/v2/Schemas/{id}', 'public'],
  ['GET /scim/v2/Users', 'public'],
  ['POST /scim/v2/Users', 'public'],
  ['GET /scim/v2/Users/{id}', 'public'],
  ['PUT /scim/v2/Users/{id}', 'public'],
  ['PATCH /scim/v2/Users/{id}', 'public'],
  ['DELETE /scim/v2/Users/{id}', 'public'],
  ['GET /scim/v2/Groups', 'public'],
  ['POST /scim/v2/Groups', 'public'],
  ['GET /scim/v2/Groups/{id}', 'public'],
  ['PUT /scim/v2/Groups/{id}', 'public'],
  ['PATCH /scim/v2/Groups/{id}', 'public'],
  ['DELETE /scim/v2/Groups/{id}', 'public'],
  // 1.6.0, Sprint 37c (B-4801, B-4901): vault shares; quote posts
  ['GET /api/vault/shared-with-me', 'secrets:read'],
  ['GET /api/vault/kv/shares/{path}', 'secrets:read'],
  ['POST /api/vault/kv/shares/{path}', 'secrets:write'],
  ['DELETE /api/vault/shares/{id}', 'secrets:write'],
  ['POST /api/feed/posts/{id}/quote', 'feed:write'],
  // 1.6.0, Sprint 38a (B-7301, B-7302, B-7401, B-7402, B-7501): the AI inventory, analytics and prices, audit streaming and JSONL exports
  ['DELETE /api/admin/analytics/prices/{id}', ['tenant:manage', 'usage:read']],
  ['GET /api/admin/analytics/chargeback', 'usage:read'],
  ['GET /api/admin/analytics/daily', 'usage:read'],
  ['GET /api/admin/analytics/prices', 'usage:read'],
  ['GET /api/admin/analytics/summary', 'usage:read'],
  ['GET /api/admin/audit/siem', 'audit:read'],
  ['GET /api/admin/inventory', 'models:manage'],
  ['GET /api/admin/inventory/register', 'models:manage'],
  ['GET /api/admin/inventory/settings', 'models:manage'],
  ['PUT /api/admin/inventory/settings', 'models:manage'],
  ['PATCH /api/admin/inventory/{kind}/{id}', 'models:manage'],
  ['POST /api/admin/audit/exports/jsonl', 'audit:read'],
  ['POST /api/admin/audit/siem', ['audit:read', 'tenant:manage']],
  ['POST /api/admin/audit/siem/{id}/approve', ['audit:read', 'tenant:manage']],
  ['POST /api/admin/audit/siem/{id}/disable', ['audit:read', 'tenant:manage']],
  ['POST /api/admin/audit/siem/{id}/reject', ['audit:read', 'tenant:manage']],
  ['POST /api/admin/audit/siem/{id}/test', ['audit:read', 'tenant:manage']],
  ['PUT /api/admin/analytics/prices', ['tenant:manage', 'usage:read']],
  ['DELETE /api/apps/{app}/policies/{id}', 'apps:design'],
  ['DELETE /api/compliance/dlp/patterns/{id}', 'compliance:manage'],
  ['DELETE /api/compliance/dlp/rules/{id}', 'compliance:manage'],
  ['GET /api/apps/{app}/policies', 'apps:design'],
  ['GET /api/compliance/dlp', 'compliance:manage'],
  ['GET /api/compliance/exports', 'compliance:export'],
  ['GET /api/compliance/exports/{id}', 'compliance:export'],
  ['GET /api/compliance/exports/{id}/download', 'compliance:export'],
  ['GET /api/compliance/holds', 'compliance:manage'],
  ['GET /api/compliance/holds/{id}', 'compliance:manage'],
  ['POST /api/apps/{app}/entities/{entity}/policies/explain', 'apps:design'],
  ['POST /api/apps/{app}/policies', 'apps:design'],
  ['POST /api/compliance/dlp/patterns', 'compliance:manage'],
  ['POST /api/compliance/dlp/rules', 'compliance:manage'],
  ['POST /api/compliance/dlp/test', 'compliance:manage'],
  ['POST /api/compliance/exports', 'compliance:export'],
  ['POST /api/compliance/holds', 'compliance:manage'],
  ['POST /api/compliance/holds/{id}/decide', 'compliance:manage'],
  ['POST /api/compliance/holds/{id}/release', 'compliance:manage'],
  ['POST /api/compliance/holds/{id}/withdraw', 'compliance:manage'],
  ['PUT /api/apps/{app}/policies/{id}', 'apps:design'],
  ['PUT /api/compliance/dlp/patterns/{id}', 'compliance:manage'],
  ['PUT /api/compliance/dlp/rules/{id}', 'compliance:manage'],
  // ---- end of routes ----
  // 1.6.0, Sprint 39d (B-8601 to B-8603, B-8701, B-8702): the entity API, the schema API, OpenAPI and client per app,
  // app embedding. Public: the embed pages and their endpoints.
  ['DELETE /api/apps/{app}/embed/keys/{id}', 'apps:design'],
  ['DELETE /api/apps/{app}/embed/pages/{id}', 'apps:design'],
  ['DELETE /api/apps/{app}/schema/entities/{entity}', 'apps:design'],
  ['DELETE /api/apps/{app}/schema/entities/{entity}/fields/{field}', 'apps:design'],
  ['DELETE /api/apps/{app}/schema/forms/{form}', 'apps:design'],
  ['DELETE /api/apps/{app}/{entity}/{id}', 'records:write'],
  ['GET /api/apps/{app}/client.js', 'records:read'],
  ['GET /api/apps/{app}/client.ts', 'records:read'],
  ['GET /api/apps/{app}/embed', 'apps:design'],
  ['GET /api/apps/{app}/openapi.json', 'records:read'],
  ['GET /api/apps/{app}/schema', 'apps:design'],
  ['GET /api/apps/{app}/schema/versions', 'apps:design'],
  ['GET /api/apps/{app}/schema/versions/{version}', 'apps:design'],
  ['GET /api/apps/{app}/{entity}', 'records:read'],
  ['GET /api/apps/{app}/{entity}/{id}', 'records:read'],
  ['GET /embed/app/{tenant}/{app}', 'public'],
  ['GET /embed/{id}', 'public'],
  ['PATCH /api/apps/{app}/schema/entities/{entity}/fields/{field}', 'apps:design'],
  ['PATCH /api/apps/{app}/{entity}/{id}', 'records:write'],
  ['POST /api/apps/{app}/embed/keys', 'apps:design'],
  ['POST /api/apps/{app}/embed/pages', 'apps:design'],
  ['POST /api/apps/{app}/embed/sessions/revoke', 'apps:design'],
  ['POST /api/apps/{app}/schema/entities/{entity}/fields', 'apps:design'],
  ['POST /api/apps/{app}/{entity}', 'records:write'],
  ['POST /api/apps/{app}/{entity}/{id}/transition', 'records:write'],
  ['POST /api/public/embeds/open', 'public'],
  ['POST /api/public/embeds/session', 'public'],
  ['POST /api/public/embeds/submit', 'public'],
  ['PUT /api/apps/{app}/embed', 'apps:design'],
  ['PUT /api/apps/{app}/schema/entities/{entity}', 'apps:design'],
  ['PUT /api/apps/{app}/schema/entities/{entity}/states', 'apps:design'],
  ['PUT /api/apps/{app}/schema/forms/{form}', 'apps:design'],
];

const byRoute = new Map(ROUTE_PERMISSIONS.map(([k, v]) => [k, v]));

/** What a route requires, by `METHOD /path` in OpenAPI form; undefined for a route the registry does not know. */
export const routeAccess = (route: string): RouteAccess | undefined => byRoute.get(route);
