/*
 * B-2902: writes `server/src/atproto/pds/lexicon-docs.ts`, the lexicons the PDS validates records against, from the
 * official lexicon JSON in https://github.com/bluesky-social/atproto (`lexicons/`, MIT or Apache-2.0):
 *
 *   npx tsx server/test/gen-lexicons.ts [<commit>]        (default: the current head of main)
 *
 * It takes every record type a Bluesky client writes (RECORDS below), follows `ref` and union `refs` from their main
 * definitions to every definition they reach, and keeps only those: each document is pruned to its reachable
 * definitions, with descriptions dropped. Review the diff and run the lexicon tests after regenerating.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const RECORDS = [
  'app.bsky.actor.profile',
  'app.bsky.actor.status',
  'app.bsky.actor.contentVisibilityDeclaration',
  'app.bsky.feed.post',
  'app.bsky.feed.like',
  'app.bsky.feed.repost',
  'app.bsky.feed.generator',
  'app.bsky.feed.threadgate',
  'app.bsky.feed.postgate',
  'app.bsky.graph.follow',
  'app.bsky.graph.block',
  'app.bsky.graph.list',
  'app.bsky.graph.listitem',
  'app.bsky.graph.listblock',
  'app.bsky.graph.starterpack',
  'app.bsky.graph.verification',
  'app.bsky.graph.referencelistoptout',
  'app.bsky.labeler.service',
  'app.bsky.notification.declaration',
  'chat.bsky.actor.declaration'
];

type Json = Record<string, unknown>;

async function main(): Promise<void> {
  let commit = process.argv[2];
  if (!commit) {
    const r = await fetch('https://api.github.com/repos/bluesky-social/atproto/commits/main');
    commit = ((await r.json()) as { sha: string }).sha;
  }
  const docs = new Map<string, Json>();
  const load = async (nsid: string): Promise<Json | null> => {
    if (docs.has(nsid)) return docs.get(nsid)!;
    const url = `https://raw.githubusercontent.com/bluesky-social/atproto/${commit}/lexicons/${nsid.split('.').join('/')}.json`;
    const r = await fetch(url);
    if (r.status === 404) return null;
    if (!r.ok) throw new Error(`${url}: ${r.status}`);
    const doc = (await r.json()) as Json;
    docs.set(nsid, doc);
    return doc;
  };

  // Reachable definitions, as `nsid#name`.
  const keep = new Map<string, Set<string>>();
  const queue: string[] = [];
  const reach = (ref: string, from: string) => {
    const full = ref.startsWith('#') ? `${from}${ref}` : ref.includes('#') ? ref : `${ref}#main`;
    const [nsid, name] = full.split('#') as [string, string];
    const set = keep.get(nsid) ?? new Set<string>();
    keep.set(nsid, set);
    if (set.has(name)) return;
    set.add(name);
    queue.push(full);
  };
  const scan = (node: unknown, nsid: string): void => {
    if (Array.isArray(node)) return node.forEach((n) => scan(n, nsid));
    if (!node || typeof node !== 'object') return;
    const o = node as Json;
    if (o.type === 'ref' && typeof o.ref === 'string') reach(o.ref, nsid);
    if (o.type === 'union' && Array.isArray(o.refs)) for (const r of o.refs) reach(String(r), nsid);
    for (const [k, v] of Object.entries(o)) if (k !== 'knownValues') scan(v, nsid);
  };
  for (const r of RECORDS) {
    const doc = await load(r);
    if (!doc) {
      process.stderr.write(`skipped ${r}: not in this commit\n`);
      continue;
    }
    reach(r, r);
  }
  while (queue.length) {
    const full = queue.shift()!;
    const [nsid, name] = full.split('#') as [string, string];
    const doc = await load(nsid);
    if (!doc) throw new Error(`${full} is referenced but has no lexicon`);
    const def = (doc.defs as Json)[name];
    if (!def) throw new Error(`${full} is referenced but not defined`);
    scan(def, nsid);
  }

  const strip = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(strip);
    if (!node || typeof node !== 'object') return node;
    return Object.fromEntries(Object.entries(node as Json).filter(([k]) => k !== 'description').map(([k, v]) => [k, strip(v)]));
  };
  const out = [...keep.keys()].sort().map((nsid) => {
    const doc = docs.get(nsid)!;
    const defs = doc.defs as Json;
    const names = [...keep.get(nsid)!].sort((a, b) => (a === 'main' ? -1 : b === 'main' ? 1 : a.localeCompare(b)));
    return { lexicon: 1, id: nsid, defs: Object.fromEntries(names.map((n) => [n, strip(defs[n])])) };
  });

  const body = out.map((d) => `  ${JSON.stringify(d, null, 2).replace(/\n/g, '\n  ')}`).join(',\n');
  const file = `/*
 * B-2902: the lexicons the PDS validates records against (generated by server/test/gen-lexicons.ts; do not edit).
 *
 * Source: https://github.com/bluesky-social/atproto/tree/${commit}/lexicons
 * (MIT or Apache-2.0, at your option), fetched ${new Date().toISOString().slice(0, 10)}. Only the record types a Bluesky client writes and the definitions they reach are kept,
 * without descriptions. Regenerate with \`npx tsx server/test/gen-lexicons.ts [<commit>]\`.
 */
import type { LexiconDoc } from './lexicon.js';

export const LEXICON_SOURCE = 'bluesky-social/atproto@${commit}';

export const LEXICONS: LexiconDoc[] = [
${body}
] as LexiconDoc[];
`;
  const target = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/atproto/pds/lexicon-docs.ts');
  writeFileSync(target, file);
  process.stdout.write(`wrote ${out.length} lexicons (${[...keep.values()].reduce((n, s) => n + s.size, 0)} definitions) to ${target}\n`);
}

await main();
